#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2026 Tenstorrent USA, Inc.

"""Generate key_digests.c from RSA-3072 PEM key files.

Usage:
    python3 generate_key_digests.py --keys dev0.pem,dev1.pem,prod0.pem,...
    python3 generate_key_digests.py --keys-dir path/to/signing_keys/

Reads RSA-3072 private key PEM files, extracts the public key modulus,
computes SHA-256(modulus_big_endian_384bytes), and outputs key_digests.c.
"""

import argparse
import hashlib
import sys
from pathlib import Path


def extract_modulus_digest(pem_path):
    """Extract RSA-3072 modulus from PEM and return SHA-256 digest."""
    from cryptography.hazmat.primitives import serialization

    with open(pem_path, "rb") as f:
        private_key = serialization.load_pem_private_key(f.read(), password=None)
    pub = private_key.public_key()
    n = pub.public_numbers().n
    modulus_bytes = n.to_bytes(384, byteorder="big")
    return hashlib.sha256(modulus_bytes).digest()


def format_digest(name, digest):
    """Format a digest as a C static const array."""
    lines = [f"static const uint8_t {name}[SHA256_DIGEST_SIZE_BYTES] = {{"]
    for i in range(0, 32, 8):
        chunk = ", ".join(f"0x{digest[i + j]:02x}" for j in range(8))
        lines.append(f"    {chunk},")
    lines.append("};")
    return "\n".join(lines)


SLOT_NAMES = ["dev0", "dev1", "prod0", "prod1", "prod2", "prod3"]


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("--keys", help="Comma-separated PEM files (slot0,slot1,...)")
    group.add_argument(
        "--keys-dir",
        action="append",
        help="Directory with rsa_private_key.*.pem files; repeatable, first match wins",
    )
    parser.add_argument(
        "--test-slots",
        default="",
        help="Comma-separated slot names whose digests are test-only; compiled in "
        "under TEST_BUILD and NULL otherwise",
    )
    parser.add_argument("-o", "--output", default="key_digests.c")
    args = parser.parse_args()

    test_slots = {s.strip() for s in args.test_slots.split(",") if s.strip()}
    unknown = test_slots - set(SLOT_NAMES)
    if unknown:
        sys.exit(f"--test-slots names no such slot: {', '.join(sorted(unknown))}")

    pem_files = {}
    if args.keys_dir:
        for d in (Path(x) for x in args.keys_dir):
            for name in SLOT_NAMES:
                p = d / f"rsa_private_key.{name}.pem"
                if name not in pem_files and p.exists():
                    pem_files[name] = p
    else:
        for i, path in enumerate(args.keys.split(",")):
            path = path.strip()
            if path and path != "-":
                pem_files[SLOT_NAMES[i]] = Path(path)

    # Generate C file
    digest_defs = []
    entries = []
    for name in SLOT_NAMES:
        slot = SLOT_NAMES.index(name)
        if name in pem_files:
            digest = extract_modulus_digest(pem_files[name])
            var = f"digest_{name}"
            body = f"// SHA-256 of the modulus in {pem_files[name]}\n" + format_digest(var, digest)
            entry = f"    {{ .digest = {var} }},  // slot {slot}: {name}"
            if name in test_slots:
                # A release build must not trust a test key, so the digest is not
                # merely commented as test-only -- it is absent from the binary.
                digest_defs.append(f"#if TEST_BUILD\n{body}\n#endif")
                entries.append(
                    f"#if TEST_BUILD\n{entry}  (TEST-ONLY)\n"
                    f"#else\n    {{ .digest = (void *)0 }},     // slot {slot}: {name}\n#endif"
                )
            else:
                digest_defs.append(body)
                entries.append(entry)
            marker = " TEST-ONLY" if name in test_slots else ""
            print(f"  slot {slot} ({name}):{marker} {pem_files[name]}", file=sys.stderr)
        else:
            entries.append(f"    {{ .digest = (void *)0 }},     // slot {slot}: {name}")

    with open(args.output, "w") as f:
        f.write("/* SPDX-License-Identifier: Apache-2.0 */\n")
        f.write("/* SPDX-FileCopyrightText: 2026 Tenstorrent USA, Inc. */\n\n")
        f.write("// Auto-generated by generate_key_digests.py — DO NOT EDIT.\n")
        f.write("//\n")
        f.write("// SHA-256 digests of RSA-3072 public key moduli, one per ROM key slot.\n")
        if test_slots:
            names = ", ".join(n for n in SLOT_NAMES if n in test_slots)
            f.write("//\n")
            f.write(f"// TEST-ONLY SLOTS: {names}.\n")
            f.write("// Their private keys are committed in the clear under\n")
            f.write("// tools/test_signing_keys/, so they authenticate nothing. They are\n")
            f.write("// compiled in only under TEST_BUILD and are NULL otherwise.\n")
            f.write("//\n")
            f.write("// A PRODUCTION ROM MUST supply a real key for EVERY slot and MUST NOT\n")
            f.write("// be built with TEST_BUILD. A slot left NULL is refused at boot with\n")
            f.write("// ROM_KEY_EMPTY, so an unpopulated production slot fails closed rather\n")
            f.write("// than silently trusting the manifest's own modulus.\n")
        f.write("\n")
        f.write('#include "key_digests.h"\n\n')
        for d in digest_defs:
            f.write(d + "\n\n")
        f.write("public_key_info_t public_key_digests[NUM_PUBLIC_KEY_DIGESTS] = {\n")
        f.write("\n".join(entries) + "\n")
        f.write("};\n")

    print(f"Generated {args.output}", file=sys.stderr)


if __name__ == "__main__":
    main()
