# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2026 Tenstorrent USA, Inc.
#
# tclint-disable line-length
#
# SEP VC SpyGlass RDC waivers.

# --- hierarchy-reuse tokens -------------------------------------------------------
# ${PREFIX} re-anchors hierarchical filter fields at the parent instance path. A parent
# run that replays this block predefines PREFIX and apply_prefix before sourcing this
# file; in the block's own run PREFIX is "". ${BLOCKINST} is the containing instance of a
# block-top violation (the design name here, the instance path at the parent).
if { ![info exists PREFIX] } { set PREFIX "" }
if { [info procs apply_prefix] eq "" } {
    proc apply_prefix { filter } {
        set out [string map [list {${PREFIX}} $::PREFIX] $filter]
        if { $::PREFIX eq "" } {
            set bi $::env(DESIGN_NAME)
        } else {
            set bi [string trimright $::PREFIX "/."]
        }
        set out [string map [list {${BLOCKINST}} $bi] $out]
        return $out
    }
}
# ----------------------------------------------------------------------------------

waive_violation -add {SEP_SETUP_RESET_INFERRED_SOFT_2734} -comment {VeeR EL2 debug module dmactive/ndmreset, debugger-written resets contained within the verified vendor core; never reach SEP logic and are quasi-static in functional operation.} -filter [apply_prefix {(PotentialRoot =~ "${PREFIX}u_sep_cpu/u_el2_veer_wrapper/*/dbg/dmcontrol*/genblock.dffs/dout/Q*") AND (Module == "rvdff")}] -app { rdc } -tag { SETUP_RESET_INFERRED_SOFT } -user { danielkim } -timestamp { 17-07-2026 14:20:07 }
waive_violation -add {SEP_RDC_CLOCK_CORRUPT_OBSERVED_726208} -comment {The enable to the clock gaters in VeeR can go metastable only when SEP_RESET_N is asserted; all logic on the gated clock is reset by SEP_RESET_N itself, so this does not create a risk} -filter [apply_prefix {(RdcSourceResets:ResetName == "SEP_RESET_N") AND (RdcDestResets:DestResetInfo:ResetName == "'no-reset'") AND ((DestClockInfoList:DestClockInfo:ClockName == "SEPCLK") OR (DestClockInfoList:DestClockInfo:ClockName == "SMUCLK"))  AND (ReasonInfoList:ReasonInfo:ReasonCode == "NO_BLOCKING_METHOD") AND (ReasonInfoList:ReasonInfo:ReasonCodeMsg == "[ERROR] No valid blocking scheme found") AND (DestObject =~ "${PREFIX}u_sep_cpu/u_el2_veer_wrapper/*/clkhdr/u_clkgater/*") AND (DestObjectType == "latch") AND (AllSrcResets:SrcResetInfo:ResetObject == "${PREFIX}u_sep_reset_ctrl/sep_reset_no") AND (AllSrcResets:SrcResetInfo:ResetName == "SEP_RESET_N") AND (DestSyncResetInfoList:DestResetInfo:ResetName == "'no-reset'") AND ((SrcClockInfoList:SrcClockInfo:ClockName == "SEPCLK") OR (SrcClockInfoList:SrcClockInfo:ClockName == "SMUCLK"))  AND (Module == "sep")}] -app { rdc } -tag { RDC_CLOCK_CORRUPT_OBSERVED } -user { danielkim } -timestamp { 20-07-2026 15:37:28 }
waive_violation -add {SEP_RDC_CLOCK_CORRUPT_OBSERVED_1131758} -comment {The enable to the DMA clock gater can go metastable only when SEP_RESET_N is asserted; all logic on the gated clock (DMA FSM) is reset by SEP_RESET_N itself, so this does not create a risk} -filter [apply_prefix {(RdcSourceResets:ResetName == "SEP_RESET_N") AND (RdcDestResets:DestResetInfo:ResetName == "'no-reset'") AND ((DestClockInfoList:DestClockInfo:ClockName == "SEPCLK") OR (DestClockInfoList:DestClockInfo:ClockName == "SMUCLK"))  AND (ReasonInfoList:ReasonInfo:ReasonCode == "NO_BLOCKING_METHOD") AND (ReasonInfoList:ReasonInfo:ReasonCodeMsg == "[ERROR] No valid blocking scheme found") AND (SrcObject =~ "${PREFIX}u_sep_dma_wrap/u_secure_dma/*") AND (DestObject =~ "${PREFIX}u_sep_dma_wrap/u_secure_dma/dma_clk_gate/*") AND (DestObjectType == "latch") AND (AllSrcResets:SrcResetInfo:ResetObject == "${PREFIX}u_sep_reset_ctrl/sep_reset_no") AND (AllSrcResets:SrcResetInfo:ResetName == "SEP_RESET_N") AND (DestSyncResetInfoList:DestResetInfo:ResetName == "'no-reset'") AND ((SrcClockInfoList:SrcClockInfo:ClockName == "SEPCLK") OR (SrcClockInfoList:SrcClockInfo:ClockName == "SMUCLK"))  AND (Module == "secure_dma")}] -app { rdc } -tag { RDC_CLOCK_CORRUPT_OBSERVED } -user { danielkim } -timestamp { 20-07-2026 15:45:47 }
waive_violation -add {SEP_RDC_CLOCK_CORRUPT_OBSERVED_858994} -comment {The enable to the clock gaters in VeeR can go metastable only when RST_N is asserted; all logic on the gated clock is reset by RST_N itself, so this does not create a risk} -filter [apply_prefix {((RdcSourceResets:ResetName == "RST_NI") OR (RdcSourceResets:ResetName == "PRIMARY_RESET_N_SMC_CLK")) AND (RdcDestResets:DestResetInfo:ResetName == "'no-reset'") AND ((DestClockInfoList:DestClockInfo:ClockName == "SEPCLK") OR (DestClockInfoList:DestClockInfo:ClockName == "SMUCLK"))  AND (ReasonInfoList:ReasonInfo:ReasonCode == "NO_BLOCKING_METHOD") AND (ReasonInfoList:ReasonInfo:ReasonCodeMsg == "[ERROR] No valid blocking scheme found") AND (SrcObject =~ "${PREFIX}u_sep_local_axi_xbar_wrapper/u_sep_local_axi_xbar/u_axi_xbar/*") AND (DestObject =~ "${PREFIX}u_sep_cpu/u_el2_veer_wrapper/veer/*") AND (DestObjectType == "latch") AND ((AllSrcResets:SrcResetInfo:ResetName == "RST_NI") OR (AllSrcResets:SrcResetInfo:ResetName == "PRIMARY_RESET_N_SMC_CLK")) AND (DestSyncResetInfoList:DestResetInfo:ResetName == "'no-reset'") AND ((SrcClockInfoList:SrcClockInfo:ClockName == "SEPCLK") OR (SrcClockInfoList:SrcClockInfo:ClockName == "SMUCLK"))  AND (Module == "sep")}] -app { rdc } -tag { RDC_CLOCK_CORRUPT_OBSERVED } -user { danielkim } -timestamp { 20-07-2026 15:51:57 }
waive_violation -add {SEP_RDC_CLOCK_CORRUPT_OBSERVED_964338} -comment {Enable to VeeR clock gate can go metastable only when cpu reset is asserted; the entire core is reset by the same event and the fanout of the clock doesn't leave the core, so this does not create a risk} -filter [apply_prefix {(RdcSourceResets:ResetName == "SEP_CPU_RESET_N") AND (RdcDestResets:DestResetInfo:ResetName == "'no-reset'") AND ((DestClockInfoList:DestClockInfo:ClockName == "SEPCLK") OR (DestClockInfoList:DestClockInfo:ClockName == "SMUCLK"))  AND (ReasonInfoList:ReasonInfo:ReasonCode == "NO_BLOCKING_METHOD") AND (ReasonInfoList:ReasonInfo:ReasonCodeMsg == "[ERROR] No valid blocking scheme found") AND (DestObject =~ "${PREFIX}u_sep_cpu/u_el2_veer_wrapper/*/clkhdr/u_clkgater/*") AND (DestObjectType == "latch") AND (AllSrcResets:SrcResetInfo:ResetName == "SEP_CPU_RESET_N") AND (DestSyncResetInfoList:DestResetInfo:ResetName == "'no-reset'") AND ((SrcClockInfoList:SrcClockInfo:ClockName == "SEPCLK") OR (SrcClockInfoList:SrcClockInfo:ClockName == "SMUCLK")) }] -app { rdc } -tag { RDC_CLOCK_CORRUPT_OBSERVED } -user { danielkim } -timestamp { 21-07-2026 11:08:15 }
waive_violation -add {SEP_RDC_CLOCK_CORRUPT_OBSERVED_abr_axi4_to_ahb} -comment {ABR AXI4-to-AHB bridge clock gaters: RST_NI / SEP_RESET_N / SEP_SW_RST_ABR flops reach the latch-based ICG enables combinationally; the bridge and its gated-clock consumers share the wrapper reset, so an enable disturbance at reset assertion cannot corrupt state.} -filter [apply_prefix {(DestObject =~ "${PREFIX}u_sep_crypto/u_sep_crypto_abr_wrapper_s3c_scan/u_axi4_to_ahb/*/clkhdr/u_clkgater/*") AND (DestObjectType == "latch") AND (ReasonInfoList:ReasonInfo:ReasonCode == "NO_BLOCKING_METHOD") AND ((RdcSourceResets:ResetName == "RST_NI") OR (RdcSourceResets:ResetName == "PRIMARY_RESET_N_SMC_CLK") OR (RdcSourceResets:ResetName == "SEP_RESET_N") OR (RdcSourceResets:ResetName == "SEP_SW_RST_ABR")) AND ((SrcObject =~ "${PREFIX}u_sep_crypto/axi_demux/*") OR (SrcObject =~ "${PREFIX}u_sep_crypto/u_sep_crypto_abr_wrapper_s3c_scan/*") OR (SrcObject =~ "${PREFIX}u_sep_crypto/u_abr_b_cut/*") OR (SrcObject =~ "${PREFIX}u_sep_crypto/u_sep_crypto_axi_interconnect/*"))}] -app { rdc } -tag { RDC_CLOCK_CORRUPT_OBSERVED } -user { nbetik } -timestamp { 10-09-2026 15:16:11 }
waive_violation -add {SEP_RDC_ON_CDC_DISABLED} -comment {RDC-on-CDC intentionally not enabled in this flow configuration (same disposition as SMC).} -filter [apply_prefix {(Tag == "RDC_ON_CDC_DISABLED")}] -app { rdc } -tag { RDC_ON_CDC_DISABLED } -user { nbetik } -timestamp { 16-09-2026 12:50:22 }

# =====================================================================================
# RDC_CORRUPT WAIVERS
# These can only see the flop directly affected by an async-reset metastability event
# Downstream fanout may be affected and MUST BE AUDITED / RESOLVED
# =====================================================================================

waive_violation -add {SEP_RDC_CORRUPT_SW_RST_ISOLATE_SEQUENCED} -comment {Per-accelerator gated resets are SEPCLK-flopped isolate-sequencer outputs (gated_rst_q), so their software-triggered assertion is clock-aligned with every SEPCLK destination and cannot metastabilise it; the only asynchronous assertion is under RST_NI, covered by the declared ordering. The sequencer drains the main SEP AXI path before asserting (ResetOnlyWhenIsolated_A); the KM private key bus into the *_wrapper_key_reg blocks is NOT routed through the isolate unit, so an outstanding KM key-bus transaction at software reset loses its response - a protocol/firmware-sequencing concern outside RDC, tracked separately.} -filter [apply_prefix {(RdcSourceResets:ResetName =~ "SEP_SW_RST_*") AND ((DestClockInfoList:DestClockInfo:ClockName == "SEPCLK") OR (DestClockInfoList:DestClockInfo:ClockName == "SMUCLK"))}] -app { rdc } -tag { RDC_CORRUPT_OBSERVED } -user { nbetik } -timestamp { 16-09-2026 12:50:22 }
waive_violation -add {SEP_RDC_CORRUPT_SEP_RESET_CONDITIONED} -comment {SEP_RESET_N / SEP_INTERMEDIATE_RESET_N assert only under RST_NI (declared ordering) or during the boot window while all SEPCLK masters are held in reset; functional-scenario JTAG overrides are case-pinned off.} -filter [apply_prefix {((RdcSourceResets:ResetName == "SEP_RESET_N") OR (RdcSourceResets:ResetName == "SEP_INTERMEDIATE_RESET_N")) AND ((DestClockInfoList:DestClockInfo:ClockName == "SEPCLK") OR (DestClockInfoList:DestClockInfo:ClockName == "SMUCLK"))}] -app { rdc } -tag { RDC_CORRUPT_OBSERVED } -user { nbetik } -timestamp { 16-09-2026 12:50:22 }
waive_violation -add {SEP_RDC_CORRUPT_KM_CONDITIONER} -comment {Key manager conditioner resets: KM_COLD ordered from SEP_RESET_N (declared sequence), KM_WARM is the sync-asserting conditioner output - clock-aligned to all SEPCLK destinations.} -filter [apply_prefix {((RdcSourceResets:ResetName == "KM_COLD_RESET_N") OR (RdcSourceResets:ResetName == "KM_WARM_RESET_N")) AND ((DestClockInfoList:DestClockInfo:ClockName == "SEPCLK") OR (DestClockInfoList:DestClockInfo:ClockName == "SMUCLK"))}] -app { rdc } -tag { RDC_CORRUPT_OBSERVED } -user { nbetik } -timestamp { 16-09-2026 12:50:22 }
# REVIEW: "in-flight CPU transactions corrupting bookkeeping during recovery is accepted." ??
waive_violation -add {SEP_RDC_CORRUPT_CPU_WDT_RECOVERY} -comment {SEP_CPU_RESET_N = sep_reset_n & wdt_rst_ni; the WDT-triggered assert is a system recovery event after which firmware re-initializes the fabric.} -filter [apply_prefix {(RdcSourceResets:ResetName == "SEP_CPU_RESET_N") AND ((DestClockInfoList:DestClockInfo:ClockName == "SEPCLK") OR (DestClockInfoList:DestClockInfo:ClockName == "SMUCLK"))}] -app { rdc } -tag { RDC_CORRUPT_OBSERVED } -user { nbetik } -timestamp { 16-09-2026 12:50:22 }
waive_violation -add {SEP_RDC_CORRUPT_JTAG_TAP_TDO_RETIME} -comment {rvjtag_tap TDO retiming flop is reset-less by design; TRST assertion puts the TAP in Test-Logic-Reset where TDO output is disabled, so a corrupted retimed bit is never observable.} -filter [apply_prefix {(DestObject =~ "${PREFIX}u_sep_cpu/u_el2_veer_wrapper/dmi_wrapper/i_jtag_tap/tdo/*") AND (RdcDestResets:DestResetInfo:ResetName == "'no-reset'") AND (Module == "rvjtag_tap")}] -app { rdc } -tag { RDC_CORRUPT_OBSERVED } -user { nbetik } -timestamp { 16-09-2026 12:50:22 }
waive_violation -add {SEP_RDC_CORRUPT_KM_CPU_SYNC_RESET} -comment {PicoRV32 core and AXI adapter are synchronous-reset only (KM_WARM_RESET_N). Each source reset listed asserts KM_WARM in the same instant through the all-asynchronous RST_NI -> SEP_INTERMEDIATE -> SEP_RESET_N -> KM_COLD -> KM_WARM chain (AASD syncs, AND gate, async-cleared hold flop), and KM_WARM holds for MIN_RESET_CYCLES after release, so the synchronous reset overrides any disturbed sample on the same edge it could occur.} -filter [apply_prefix {(((RdcSourceResets:ResetName == "RST_NI") OR (RdcSourceResets:ResetName == "PRIMARY_RESET_N_SMC_CLK")) OR (RdcSourceResets:ResetName == "SEP_INTERMEDIATE_RESET_N") OR (RdcSourceResets:ResetName == "SEP_RESET_N") OR (RdcSourceResets:ResetName == "KM_COLD_RESET_N") OR (RdcSourceResets:ResetName == "KM_WARM_RESET_N")) AND (DestObject =~ "${PREFIX}u_sep_crypto/u_key_manager_s3c_scan/u_cpu/*") AND (RdcDestResets:DestResetInfo:ResetName == "'no-reset'") AND (DestSyncResetInfoList:DestResetInfo:ResetName == "KM_WARM_RESET_N")}] -app { rdc } -tag { RDC_CORRUPT_OBSERVED } -user { nbetik } -timestamp { 16-09-2026 12:50:22 }
waive_violation -add {SEP_RDC_CORRUPT_KM_WARM_SYNC_RESET_FIELDS} -comment {Key-manager PeakRDL fields with resetsignal WARM_RST_N (kmcsr IRQ/OTP/SRAM-lock/exec-mode, KPV CTRL erase/lock/seal, mailbox status/IRQ, DRBG sampler status) are synchronous-reset by KM_WARM_RESET_N. Each listed source reset asserts KM_WARM in the same instant through the all-asynchronous RST_NI -> SEP_INTERMEDIATE -> SEP_RESET_N -> KM_COLD -> KM_WARM chain and KM_WARM holds for MIN_RESET_CYCLES, so the synchronous reset overrides any disturbed sample on the same edge; the fields' hardware consumers are held in KM_COLD reset at that instant.} -filter [apply_prefix {(((RdcSourceResets:ResetName == "RST_NI") OR (RdcSourceResets:ResetName == "PRIMARY_RESET_N_SMC_CLK")) OR (RdcSourceResets:ResetName == "SEP_INTERMEDIATE_RESET_N") OR (RdcSourceResets:ResetName == "SEP_RESET_N") OR (RdcSourceResets:ResetName == "KM_COLD_RESET_N") OR (RdcSourceResets:ResetName == "KM_WARM_RESET_N")) AND (DestObject =~ "${PREFIX}u_sep_crypto/u_key_manager_s3c_scan/*/field_storage.*") AND (RdcDestResets:DestResetInfo:ResetName == "'no-reset'") AND (DestSyncResetInfoList:DestResetInfo:ResetName == "KM_WARM_RESET_N")}] -app { rdc } -tag { RDC_CORRUPT_OBSERVED } -user { nbetik } -timestamp { 16-09-2026 12:50:22 }
waive_violation -add {SEP_RDC_CORRUPT_EFUSE_RST_NI_SYNC_CLEAR} -comment {Efuse wrapper/controller flops cleared synchronously by rst_ni (the same RST_NI as the source); a sample disturbed at assertion is cleared on the next SEPCLK edge before it is consumed.} -filter [apply_prefix {((DestObject =~ "${PREFIX}u_sep_crypto/u_sep_efuse_wrapper/u_efuse_interface_controller/u_efuse_guard/err/*") OR (DestObject =~ "${PREFIX}u_sep_crypto/u_sep_efuse_wrapper/u_efuse_interface_controller/*u_efuse_token_processing/*_token_match_q_n0_scan/*") OR (DestObject =~ "${PREFIX}u_sep_crypto/u_sep_efuse_wrapper/u_efuse_interface_controller/*u_efuse_token_processing/token_match_fault_sticky_q/*") OR (DestObject =~ "${PREFIX}u_sep_crypto/u_sep_efuse_wrapper/fuse_sense_done_1dly/*") OR (DestObject =~ "${PREFIX}u_sep_crypto/u_sep_efuse_wrapper/secure_tm_n0_scan/*")) AND (RdcDestResets:DestResetInfo:ResetName == "'no-reset'") AND ((RdcSourceResets:ResetName == "RST_NI") OR (RdcSourceResets:ResetName == "PRIMARY_RESET_N_SMC_CLK"))}] -app { rdc } -tag { RDC_CORRUPT_OBSERVED } -user { nbetik } -timestamp { 16-09-2026 12:50:22 }

# FIFO storage is safe only if the FIFO's pointer reset asserts whenever the source reset does:
#   KM mailbox in/out FIFOs           ptrs KM_COLD       <- RST_NI / SEP_RESET_N (chain)
#   DRBG csrng/edn/adapter, axis_edn  ptrs SEP_RESET_N   <- SEP_RESET_N / RST_NI (chain)
#   OTBN/KMAC/HMAC tlul/msg FIFOs     ptrs gated SW rst  <- RST_NI (chain) / own SW_RST (clock-aligned)
#   SPI cmd/tx/rx, entropy pool       ptrs SEP_RESET_N / RST_NI  <- same reset
#   sep refcnt cnt_update_async_fifo  both sides SEP_RESET_N-derived (declared sequence)
# Re-verify the pairing whenever a FIFO is added with a reset outside these groups.
waive_violation -add {SEP_RDC_CORRUPT_FIFO_STORAGE} -comment {prim_fifo storage is pointer-qualified: every listed source reset asserts the FIFO's own pointer reset (identical reset, an RST_NI / SEP_RESET_N chain ancestor, or KM_COLD via the chain; refcnt async FIFO has both sides SEP_RESET_N-derived), so an entry torn at reset assertion sits behind reset pointers and is never read.} -filter [apply_prefix {(((RdcSourceResets:ResetName == "RST_NI") OR (RdcSourceResets:ResetName == "PRIMARY_RESET_N_SMC_CLK")) OR (RdcSourceResets:ResetName == "SEP_INTERMEDIATE_RESET_N") OR (RdcSourceResets:ResetName == "SEP_RESET_N") OR (RdcSourceResets:ResetName == "KM_COLD_RESET_N") OR (RdcSourceResets:ResetName == "SEP_RESET_N_REFCNT_SEP_CLK") OR (RdcSourceResets:ResetName == "SEP_RESET_N_REFCNT_REF_CLK")) AND ((DestObject =~ "${PREFIX}*gen_normal_fifo.storage/Q*") OR (DestObject =~ "${PREFIX}*gen_singleton_fifo.storage/Q*") OR (DestObject =~ "${PREFIX}*cnt_update_async_fifo/storage/Q*")) AND (RdcDestResets:DestResetInfo:ResetName == "'no-reset'")}] -app { rdc } -tag { RDC_CORRUPT_OBSERVED } -user { nbetik } -timestamp { 16-09-2026 12:50:22 }

# REVIEW
waive_violation -add {SEP_RDC_CORRUPT_RST_NI_TO_OTBN_EDN_RESETLESS} -comment {RST_NI-sourced state into the resetless OTBN EDN request payload register; RST_NI is the SEP root reset so the consumer is in reset for the whole corruption window.} -filter [apply_prefix {((RdcSourceResets:ResetName == "RST_NI") OR (RdcSourceResets:ResetName == "PRIMARY_RESET_N_SMC_CLK")) AND (DestObject =~ "${PREFIX}u_sep_crypto/u_sep_crypto_otbn_wrapper_s3c_scan/u_otbn/u_prim_edn_rnd_req/*") AND (RdcDestResets:DestResetInfo:ResetName == "'no-reset'")}] -app { rdc } -tag { RDC_CORRUPT_OBSERVED } -user { nbetik } -timestamp { 17-09-2026 11:44:06 }

waive_violation -add {SEP_RDC_CORRUPT_VEER_DBG_DOMAIN} -comment {Debug-reset-only VeeR DM registers capturing functional-domain data across a functional reset; the DM protocol reports the reset to the debugger and the aborted data is unreliable by contract.} -filter [apply_prefix {(DestObject =~ "*u_el2_veer_wrapper/veer/dbg/*") AND ((RdcDestResets:DestResetInfo:ResetName == "DBG_RSTB_I") OR (RdcDestResets:DestResetInfo:ResetName == "POWERGOOD_STABLE_N"))}] -app { rdc } -tag { RDC_CORRUPT_OBSERVED } -user { nbetik } -timestamp { 16-09-2026 12:50:22 }

# REVIEW WHEN UNBLACKBOXED
waive_violation -add {SEP_RDC_CORRUPT_ENTROPY_SOURCE_BLACKBOX_PORTS} -comment {entropy_source is blackboxed; its input ports are modelled reset-less on a virtual clock (configure_unconstrained_ports virtual_sync_all).} -filter [apply_prefix {(DestObject =~ "${PREFIX}u_sep_crypto/u_sep_trng/u_entropy_source_s3c_scan/*") AND (DestObjectType == "black-box") AND (RdcDestResets:DestResetInfo:ResetName == "'no-reset'")}] -app { rdc } -tag { RDC_CORRUPT_OBSERVED } -user { nbetik } -timestamp { 16-09-2026 12:50:22 }

# COVERAGE NOTE: the security-critical persistent state in this block is not
# the token words but the digest / valid LATCHES in efuse_token_digest_sha256 (built as
# latches so the unlock survives cold reset). Their enables (hash_done_q, start_i) and data
# are RST_NI-reset flops, yet the tool reports no RDC record against them, i.e. it is not
# treating these latches as corruption destinations
waive_violation -add {SEP_RDC_CORRUPT_EFUSE_TOKEN_SHADOW_NORESET} -comment {Deliberately reset-less software-written token shadow registers, written from the RST_NI-reset APB cpuif; a word disturbed by a write in flight at RST_NI assertion can only fail the next token compare and firmware must rewrite all words before every go.} -filter [apply_prefix {((RdcSourceResets:ResetName == "RST_NI") OR (RdcSourceResets:ResetName == "PRIMARY_RESET_N_SMC_CLK")) AND (DestObject =~ "${PREFIX}u_sep_crypto/u_sep_efuse_wrapper/u_efuse_interface_controller/*u_efuse_token_processing/*_token_raw_n0_scan/*") AND (RdcDestResets:DestResetInfo:ResetName == "'no-reset'")}] -app { rdc } -tag { RDC_CORRUPT_OBSERVED } -user { nbetik } -timestamp { 16-09-2026 12:50:22 }

# =============================================================================
# Warning-class dispositions
# =============================================================================
waive_violation -add {SEP_INTEGRITY_RESET_ASYNC_AND_SYNC_USAGE_METHODOLOGY} -comment {Async-assert/sync-consume on the reset-controller outputs, the intermediate reset, the KM warm-reset tail and rst_ni is the project reset methodology.} -filter [apply_prefix {(ResetObject =~ "${PREFIX}u_sep_reset_ctrl/*") OR (ResetObject == "${PREFIX}u_sep_crypto/sep_intermediate_reset_no") OR (ResetObject == "${PREFIX}u_sep_crypto/u_key_manager_s3c_scan/u_reset_conditioner/rst_warm_sync_no") OR (ResetObject == "${PREFIX}rst_ni")}] -app { rdc } -tag { INTEGRITY_RESET_ASYNC_AND_SYNC_USAGE } -user { nbetik } -timestamp { 16-09-2026 12:50:22 }
waive_violation -add {SEP_SETUP_RESET_OVERLAP_RESET_TREE} -comment {AND-combined hierarchical reset tree; overlap by construction, ordering declared in sep.resets.tcl. RST_NI / WDT_RST_NI also listed under their SMU aliases.} -filter [apply_prefix {((SrcRstInfo:ResetName == "SEP_INTERMEDIATE_RESET_N") OR (SrcRstInfo:ResetName == "SEP_RESET_N") OR (SrcRstInfo:ResetName == "RST_NI") OR (SrcRstInfo:ResetName == "PRIMARY_RESET_N_SMC_CLK") OR (SrcRstInfo:ResetName == "WDT_RST_NI") OR (SrcRstInfo:ResetName == "WDT_RESET_N_SMC_CLK")) AND ((DesRstInfo:ResetName =~ "SEP_SW_RST_*") OR (DesRstInfo:ResetName == "SEP_CPU_RESET_N") OR (DesRstInfo:ResetName == "SEP_RESET_N") OR (DesRstInfo:ResetName =~ "SEP_RESET_N_REFCNT_*"))}] -app { rdc } -tag { SETUP_RESET_OVERLAP } -user { nbetik } -timestamp { 16-09-2026 12:50:22 }
waive_violation -add {SEP_SETUP_RESET_DRIVING_NON_ASYNC_PIN_SYNC_TAILS} -comment {rst_ni, traced through the EDN ack state flop, reaches efuse-wrapper status/control flops as data; the efuse wrapper is the only consumer.} -filter [apply_prefix {(ResetName == "${PREFIX}rst_ni") AND (NonResetInstance =~ "${PREFIX}u_sep_crypto/u_sep_efuse_wrapper/*")}] -app { rdc } -tag { SETUP_RESET_DRIVING_NON_ASYNC_PIN } -user { nbetik } -timestamp { 16-09-2026 12:50:22 }
waive_violation -add {SEP_SETUP_RESET_DRIVING_NON_ASYNC_PIN_TRNG_CSR_QE} -comment {Tool artifact: the TRNG reset only clears the CSRNG cmd_req0_qe flop, but the tool treats that flop's Q (the SW command-valid pulse) as carrying the reset and follows it into EDN / entropy FIFO data outside the TRNG domain. The downstream flops receive a clock-domain pulse, never the reset value.} -filter [apply_prefix {(ResetName =~ "*sep_crypto_gated_rst_n.trng") AND (ResetInstance =~ "${PREFIX}u_sep_crypto/u_sep_trng/u_drbg_s3c_scan/u_csrng/u_reg/u_cmd_req0_qe/*")}] -app { rdc } -tag { SETUP_RESET_DRIVING_NON_ASYNC_PIN } -user { nbetik } -timestamp { 17-09-2026 11:44:06 }
waive_violation -add {SEP_SETUP_ASYNCRESET_UNUSED_INDIRECT} -comment {AND-tree / conditioner-consumed resets have no direct async-pin fanout by construction.} -filter [apply_prefix {((Reset:ResetName == "WDT_RST_NI") OR (Reset:ResetName == "WDT_RESET_N_SMC_CLK")) OR (Reset:ResetName == "SEP_SW_RST_KM")}] -app { rdc } -tag { SETUP_ASYNCRESET_UNUSED } -user { nbetik } -timestamp { 16-09-2026 12:50:22 }
waive_violation -add {SEP_SETUP_CLOCK_UNUSED_BOUNDARY_CLKS} -comment {Output-port memory clocks (PKA IMEM/DMEM) clock no internal sequentials by construction.} -filter [apply_prefix {(Clock:ClkName =~ "SEPCLK_PKA_*")}] -app { rdc } -tag { SETUP_CLOCK_UNUSED } -user { nbetik } -timestamp { 16-09-2026 12:50:22 }
waive_violation -add {SEP_SETUP_MULTIPLE_CONSTRAINTS_SCAN_RESET} -comment {Intentional mode split: scan reset declared for role modeling, case-pinned inactive in the functional scenario.} -filter [apply_prefix {(InstanceName == "scan_rst_ni")}] -app { rdc } -tag { SETUP_MULTIPLE_CONSTRAINTS } -user { nbetik } -timestamp { 16-09-2026 12:50:22 }
waive_violation -add {SEP_SETUP_RDC_CONSTRAINT_UNUSED_DOC_SEQUENCES} -comment {Reset-ordering declarations retained for documentation and SMU-level reuse; unused here because their crossings are pruned by other orderings.} -filter [apply_prefix {(ConstraintName == "set_rdc_define_assertion_sequence")}] -app { rdc } -tag { SETUP_RDC_CONSTRAINT_UNUSED } -user { nbetik } -timestamp { 16-09-2026 12:50:22 }

# KM_COLD (rst_cold_aasd_no) additionally acts as a synchronous clear/qualifier
# for the DRBG sampler's data staging registers inside the key manager - the
# conditioner tail is already synchronized, so its data-side use introduces no
# new async hazard (same async-assert/sync-consume methodology class).
waive_violation -add {SEP_SETUP_RESET_DRIVING_NON_ASYNC_PIN_KM_SAMPLER} -comment {Synchronized KM cold-reset tail consumed as a synchronous qualifier by the DRBG sampler staging registers (async-assert/sync-consume methodology).} -filter [apply_prefix {(ResetName =~ "*u_key_manager_s3c_scan/u_reset_conditioner/rst_cold_aasd_no") AND (NonResetInstance =~ "*u_key_manager_s3c_scan/*")}] -app { rdc } -tag { SETUP_RESET_DRIVING_NON_ASYNC_PIN } -user { nbetik } -timestamp { 16-09-2026 12:50:22 }
waive_violation -add {SEP_SETUP_RESET_DRIVING_NON_ASYNC_PIN_TRNG_RESET_ACTIVE_SYNC} -comment {The TRNG reset-active synchroniser samples the gated TRNG reset as data by design, to report reset status into the live domain; a two-stage prim_flop_2sync, not a reset pin.} -filter [apply_prefix {(ResetName =~ "*sep_crypto_gated_rst_n.trng") AND (NonResetInstance =~ "${PREFIX}u_sep_crypto/u_sep_trng/u_trng_reset_active_sync/*")}] -app { rdc } -tag { SETUP_RESET_DRIVING_NON_ASYNC_PIN } -user { nbetik } -timestamp { 02-10-2026 14:00:00 }
