#------------------------------------------------------------------------------
# Copyright 2025 Tenstorrent Inc.
# Entropy Source Component
#
# Description:
# Timing constraints for the entropy_source module.
# Special considerations:
# 1. The clk_i signal is the global synchronous clock and rst_ni is the global
#    asynchronous, active low reset signal. They have high fanout as they feed
#    most flip-flop instances in the design. Define the clock period as a
#    parameter named PERIOD that we set to a value determined by the target
#    technology. The default value is 1 ns.
# 2. entropy_ring_oscillator.sv
#    The timing path on the feedback path must be broken. Also, we do
#    not want any logic optimization to be performed on any of the logic cells
#    in this module other than direct mapping to equivalent technology specific
#    cells.
# 3. entropy_sampler_clocks.sv and entropy_noise_source.sv
#    The sample_clk_o output signals must be treated as clocks for the smpl
#    flip-flop instance in the entropy_noise_source.sv module.
#    The input timing path to the sync0 flip-flop instance in
#    entropy_noise_sourc.sv should be broken as this is the first stage of a
#    synchronizer. The second stage is instance sync1 and is treated as normal.
# 4. entropy_ripple_divider.sv
#    Asynchronous ripple dividers contain combinational feedback paths
#    (D=QB for toggle operation) and ripple chain connections where each stage
#    clocks the next. These paths must be marked as false paths and the divider
#    instances must not be optimized by synthesis. The structure is critical for
#    proper frequency division operation.
#------------------------------------------------------------------------------

#------------------------------------------------------------------------------
# DESIGN PARAMETERS
#------------------------------------------------------------------------------

# Define clock period parameter - adjust based on target technology
# Default: 1.0 ns (1.0 GHz)
set PERIOD 1.0

# APB interface timing margins (as percentage of clock period)
set INPUT_DELAY_PERCENT  0.3
set OUTPUT_DELAY_PERCENT 0.3

#------------------------------------------------------------------------------
# CLOCK DEFINITIONS
#------------------------------------------------------------------------------

# Primary system clock - drives all synchronous logic
create_clock -name clk_sys -period $PERIOD [get_ports clk_i]

# External ring oscillator sample clock
# Estimated period 2.5 ns (400 MHz)
# This clock is used as an alternative to internal sampling ring oscillators

create_clock -name clk_sample_ext -period 2.5 [get_ports rosc_sample_clk_i]

# Internal shared ring oscillator sample clock (generated by entropy_sampler_clocks)
# Single shared RO (length 109) distributed to all 12 generators
# Approximate clock frequency is 435 MHz (109 stages)
create_clock -name clk_sample_shared -period 2.3 \
    [get_pins -hierarchical -filter "name =~ *sclk/shared_ro/noise_o"]

#------------------------------------------------------------------------------
# CLOCK GROUPS - ASYNCHRONOUS DOMAINS
#------------------------------------------------------------------------------

# System clock and external sample clock are asynchronous
set_clock_groups -asynchronous \
    -group [get_clocks clk_sys] \
    -group [get_clocks clk_sample_ext]

# Shared internal sample clock is asynchronous to system clock and external clock
# The shared RO is distributed to all 12 generators via muxes and dividers
set_clock_groups -asynchronous \
    -group [get_clocks clk_sys] \
    -group [get_clocks clk_sample_ext] \
    -group [get_clocks clk_sample_shared]

#------------------------------------------------------------------------------
# RING OSCILLATOR CONSTRAINTS - *** may need adjustment for tech mapping ***
#------------------------------------------------------------------------------
# Ring oscillators must not be optimized by synthesis or place & route
# Set size_only to prevent buffering/optimization while allowing technology mapping
set_dont_touch [get_cells -hierarchical -filter "ref_name =~ entropy_ring_oscillator"]

# Prevent optimization of individual ring oscillator cells
# These must maintain their structure for proper oscillation
set_dont_touch [get_cells -hierarchical -filter "ref_name =~ prim_clock_nand2"]
set_dont_touch [get_cells -hierarchical -filter "ref_name =~ prim_stdbuf"]
set_dont_touch [get_cells -hierarchical -filter "ref_name =~ prim_stdmux2"]

# Break timing paths on ring oscillator feedback loops
# The feedback path is a combinational loop and is not a timed path
set_false_path -through [get_pins -hierarchical -filter "name =~ */ro/feedback"]

# Break timing on all ring oscillator internal paths
# These are asynchronous self-timed circuits
set_false_path -through [get_cells -hierarchical -filter "ref_name =~ entropy_ring_oscillator"]

# Shared ring oscillator fanout constraint
# The shared RO has 12-way fanout to generator muxes
# May need buffer insertion if technology limits fanout
set_max_fanout 12 [get_nets -hierarchical -filter "name =~ *sclk/shared_ring_osc_clk"]

#------------------------------------------------------------------------------
# RIPPLE DIVIDER CONSTRAINTS
#------------------------------------------------------------------------------
# Asynchronous ripple dividers divide sample clocks for entropy generators
# Each divider has 5 stages providing division factors: 1, 2, 4, 8, 16, 32
#
# Critical constraints:
# 1. Toggle flip-flops (D=QB) create combinational feedback paths
# 2. Each stage's Q output clocks the next stage (ripple chain)
# 3. Dividers must not be optimized - structure is critical for function
# 4. No timing analysis should be performed on the ripple paths
#
# Locations:
# - Debug monitor: dbg/u_ripple_divider (1 instance for signal monitoring)
# - Sampler clocks: egen/sclk/gen_ecmplx[*]/u_sample_clk_divider (12 instances for sample clock division)

# Prevent optimization of ripple divider instances
# Structure must be preserved for proper ripple operation
set_dont_touch [get_cells -hierarchical -filter "ref_name =~ entropy_ripple_divider"]

# Prevent optimization of generic cells used in ripple dividers
# set_dont_touch [get_cells -hierarchical -filter "ref_name =~ prim_dffrxq"]

# Break timing paths on ripple divider feedback loops
# Each toggle flip-flop has D connected to QB (feedback path)
# Pattern: ripple_divider instance -> stage generate block -> flip-flop -> i_D pin
set_false_path -through [get_pins -hierarchical -filter "name =~ *u_ripple_divider*/u_div_ff/i_D"]
set_false_path -through [get_pins -hierarchical -filter "name =~ *u_sample_clk_divider*/u_div_ff/i_D"]

# Break timing paths on ripple chain connections
# Each stage's Q output clocks the next stage (asynchronous ripple)
# Pattern: stage[N]/o_Q -> stage[N+1]/i_CK
set_false_path -through [get_pins -hierarchical -filter "name =~ *u_ripple_divider*/u_div_ff/o_Q"]
set_false_path -through [get_pins -hierarchical -filter "name =~ *u_sample_clk_divider*/u_div_ff/o_Q"]
set_false_path -through [get_pins -hierarchical -filter "name =~ *u_ripple_divider*/u_div_ff/i_CK"]
set_false_path -through [get_pins -hierarchical -filter "name =~ *u_sample_clk_divider*/u_div_ff/i_CK"]

# Break timing on divided clock outputs
# These outputs are used as clock sources (not data) and should not have timing checks
set_false_path -from [get_pins -hierarchical -filter "name =~ *u_ripple_divider*/div_o*"]
set_false_path -from [get_pins -hierarchical -filter "name =~ *u_sample_clk_divider*/div_o*"]

# Note: The divided clocks are selected by a mux in entropy_sampler_clocks
# and output as sample_clk_o[i] to each entropy_generator instance.
# The mux selection logic operates in the system clock domain and is
# already properly constrained by normal timing analysis

#------------------------------------------------------------------------------
# METASTABLE SAMPLING CONSTRAINTS
#------------------------------------------------------------------------------

# The sampling flip-flop (u_smpl) captures metastable events from the
# asynchronous ring oscillator; those events are the entropy source
# Disable timing checks on the data input to the sampling flip-flop
set_false_path -to [get_pins -hierarchical -filter "name =~ *u_noise_source*/u_smpl/i_D"]

# First stage of synchronizer (u_sync0) receives potentially metastable data
# Break input timing path to allow metastability to settle
set_false_path -to [get_pins -hierarchical -filter "name =~ *u_noise_source*/u_sync0/i_D"]

# Note: sync1 (second synchronizer stage) has normal timing constraints
# This allows checking that the synchronized output meets timing

#------------------------------------------------------------------------------
# DECORRELATOR SHIFT REGISTER
#------------------------------------------------------------------------------

# Optional multi-cycle relaxation for the decorrelator shift register;
# enable if single-cycle timing closure fails:
# set_multicycle_path -setup 2 -through [get_cells -hierarchical -filter "ref_name =~ entropy_decorrelator"]
# set_multicycle_path -hold 1 -through [get_cells -hierarchical -filter "ref_name =~ entropy_decorrelator"]

#------------------------------------------------------------------------------
# HEALTH TEST CONSTRAINTS
#------------------------------------------------------------------------------

# Health tests process data serially and may benefit from multi-cycle paths
# The tests operate on 32-bit words and iterate through bits
# Uncomment if timing closure is difficult on health test logic:
# set_multicycle_path -setup 2 -through [get_cells -hierarchical -filter "ref_name =~ entropy_health_test*"]
# set_multicycle_path -hold 1 -through [get_cells -hierarchical -filter "ref_name =~ entropy_health_test*"]

#------------------------------------------------------------------------------
# FIFO CONSTRAINTS
#------------------------------------------------------------------------------

# FIFO gray code pointer domain crossing paths are handled by the design
# with proper synchronization - treat as normal timing paths
# If timing issues arise, consider multi-cycle:
# set_multicycle_path -setup 2 -from [get_cells -hierarchical -filter "name =~ */entropy_fifo/wptr_q*"] \
#                                -to [get_cells -hierarchical -filter "name =~ */entropy_fifo/rptr_q*"]

#------------------------------------------------------------------------------
# APB INTERFACE CONSTRAINTS
#------------------------------------------------------------------------------

# APB interface input delays (relative to clk_sys)
# Assume APB signals arrive 30% of clock period after clock edge
set INPUT_DELAY [expr $PERIOD * $INPUT_DELAY_PERCENT]

set_input_delay -clock clk_sys $INPUT_DELAY [get_ports paddr_i*]
set_input_delay -clock clk_sys $INPUT_DELAY [get_ports pprot_i*]
set_input_delay -clock clk_sys $INPUT_DELAY [get_ports psel_i]
set_input_delay -clock clk_sys $INPUT_DELAY [get_ports penable_i]
set_input_delay -clock clk_sys $INPUT_DELAY [get_ports pwrite_i]
set_input_delay -clock clk_sys $INPUT_DELAY [get_ports pwdata_i*]
set_input_delay -clock clk_sys $INPUT_DELAY [get_ports pstrb_i*]

# APB interface output delays (relative to clk_sys)
# Outputs must be stable 30% of clock period before next clock edge
set OUTPUT_DELAY [expr $PERIOD * $OUTPUT_DELAY_PERCENT]

set_output_delay -clock clk_sys $OUTPUT_DELAY [get_ports pready_o]
set_output_delay -clock clk_sys $OUTPUT_DELAY [get_ports prdata_o*]
set_output_delay -clock clk_sys $OUTPUT_DELAY [get_ports pslverr_o]

# Interrupt output
set_output_delay -clock clk_sys $OUTPUT_DELAY [get_ports irq_o]

# Entropy stream outputs (synchronous to clk_sys)
set_output_delay -clock clk_sys $OUTPUT_DELAY [get_ports entropy_stream_data_o*]
set_output_delay -clock clk_sys $OUTPUT_DELAY [get_ports entropy_stream_vld_o*]

# Debug monitor output (asynchronous, driven by selected internal signal)
# No timing constraint needed - false path
set_false_path -to [get_ports signal_monitor_o]

#------------------------------------------------------------------------------
# RESET CONSTRAINTS
#------------------------------------------------------------------------------

# Asynchronous active-low reset
# Set as false path since it's asynchronous
set_false_path -from [get_ports rst_ni]

# If using synchronous reset internally, uncomment:
# set_input_delay -clock clk_sys 0.0 [get_ports rst_ni]

#------------------------------------------------------------------------------
# CASE ANALYSIS (CONSTANT PROPAGATION)
#------------------------------------------------------------------------------

# If certain configuration bits are known at synthesis time,
# they can be set as constants for optimization
# Example: If decorrelator is never bypassed:
# set_case_analysis 0 [get_pins -hierarchical -filter "name =~ */decorrelator_bypass_i*"]

#------------------------------------------------------------------------------
# DESIGN RULE CONSTRAINTS
#------------------------------------------------------------------------------

# Maximum transition time for signals (technology dependent)
# set_max_transition 0.5 [current_design]

# Maximum fanout for high fanout nets (clock, reset)
# set_max_fanout 64 [current_design]

# Maximum capacitance (technology dependent)
# set_max_capacitance 0.5 [current_design]

#------------------------------------------------------------------------------
# AREA CONSTRAINTS
#------------------------------------------------------------------------------

# Optimize for area after meeting timing
# set_max_area 0

#------------------------------------------------------------------------------
# VERIFICATION
#------------------------------------------------------------------------------

# Report timing on all clocks
# report_timing -from [all_registers] -to [all_registers]
# report_timing -from [all_inputs] -to [all_registers]
# report_timing -from [all_registers] -to [all_outputs]

# Report clock networks
# report_clocks
# report_clock_networks

#------------------------------------------------------------------------------
# END OF FILE
#------------------------------------------------------------------------------
