# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2026 Tenstorrent USA, Inc.

"""Per-slot coverage of the six ROM-embedded public keys.

`key_digests.c` pins six root-key digests (`PUBK_SEL_NUM_ROM_KEYS`, slots 0-5).
Until now exactly one of them was tested:
slot 0, by `test_signed_boots_to_bl1`. Slots 1-5 held NULL digests, so they
refused everything and nothing exercised them.

This module covers all six along three axes:

  * **use** -- each digest authorizes its own key and the image boots
  * **revoke** -- setting that slot's `CHIPLET_PUBK_REVOKE` bit refuses it
  * **isolate** -- revoking every OTHER slot does not affect it

Why each slot needs its own key
-------------------------------
The six images are signed by six DIFFERENT keys. That is the point, not an
accident of setup: if every slot's digest were the same key, a slot resolved
off-by-one would still find a matching digest, every test here would pass, and
the suite would prove only that *some* digest matched. Distinct keys make the
slot index load-bearing.

That failure mode is not hypothetical. `public_key_select_classic` and
`CHIPLET_PUBK_REVOKE` share one numbering (`sep_efuse_map.rdl`: bits [7:0] are
the ROM classical keys), and an earlier revision of this integration had
authorization and revocation naming different keys -- authorization would pass
while revocation checked an unrelated bit, and a revoked key would boot.

The **isolate** axis is what pins that down. A revocation check that ignored the
slot entirely, or that was offset by one, would still pass "use" and "revoke"
for at least some slots; it cannot pass a case that revokes five specific bits
and requires the sixth key to still work.
"""

from __future__ import annotations

import pytest
from sepvp import SimConfig, paths
from tests.bootcode import shared

TIMEOUT = 180

# The six ROM key slots. Each is signed by tests/signing_keys/rsa_private_key.rom_key<n>.pem;
# the slot number is the whole identity, which is the point of the naming -- the
# old dev*/prod* names implied a trust distinction the ROM does not make.
ALL_SLOTS = list(range(6))
# Every ROM classical slot the digest table pins, as a revocation bitmap.
ALL_SLOTS_MASK = sum(1 << n for n in ALL_SLOTS)


def _slot_image(oca_images, slot):
    """Image signed by slot *slot*'s key.

    Slot 0 is the existing "signed" image (ROM key 0); 1-5 are the
    per-slot images added for this coverage. Resolved here rather than in the
    fixture so every fixture value stays a plain path and the fixture's
    existence check keeps working.
    """
    return oca_images["signed"] if slot == 0 else oca_images[f"rom_key{slot}"]


def _cfg(name, elf, image, **kw):
    return SimConfig(
        name=name, elf=str(elf), flash_image=str(image), boot="primary", boot_timeout=TIMEOUT, **kw
    )


def _revoke_map(tmp_path, name, revoke_bits):
    """Write a fuse map revoking exactly *revoke_bits* and return its path.

    Generated rather than committed as six near-identical YAMLs: the whole
    content that varies is one derived integer, and computing it next to the
    assertion keeps the slot-to-bit relationship visible. `SimConfig.otp` takes
    any path, so a tmp_path file works the same as a checked-in one.

    lc_state TEST_DEV with sboot_dis 0 leaves the device's own opinion of secure
    boot neutral -- the manifest's secure_boot_control bit is what puts
    verification in force, so these maps only have to avoid contradicting it.
    """
    path = tmp_path / f"{name}.yaml"
    path.write_text(
        "# Generated by test_bootcode_oca_rom_keys.py.\n"
        f"# CHIPLET_PUBK_REVOKE = 0x{revoke_bits:08x}"
        f" (slots revoked: {sorted(n for n in ALL_SLOTS if revoke_bits >> n & 1)})\n"
        "lc_state: TEST_DEV\n"
        "sboot_dis: 0\n"
        f"chiplet_pubk_revoke: 0x{revoke_bits:08x}\n"
    )
    return str(path)


@pytest.mark.parametrize("slot", ALL_SLOTS, ids=[f"slot{n}" for n in ALL_SLOTS])
def test_each_rom_key_slot_authorizes_and_boots(vp, bootcode_elf, oca_images, slot):
    """Each of the six ROM digests authorizes its own key and the image boots.

    PUBK_AUTHORIZED before RSA_VERIFY_OK, in that order, for the same reason as
    the slot-0 test: expect() consumes the stream, so this passes only if the key
    was vouched for before it was used.

    A slot whose digest is NULL prints PUBK_SLOT_UNPROVISIONED and never reaches
    RSA -- which is exactly what slots 1-5 did before this work.
    """
    image = _slot_image(oca_images, slot)
    t = vp(_cfg(f"oca_rom_key{slot}", bootcode_elf, image))
    t.spawn()
    shared.expect_common_early(t, timeout=TIMEOUT)
    t.expect("PUBK_AUTHORIZED", timeout=TIMEOUT)
    t.expect("RSA_VERIFY_OK", timeout=TIMEOUT)
    t.expect_status("SEP_MSG_MANIFEST_VALIDATED", type="INFO", timeout=TIMEOUT)
    t.expect_status("SEP_MSG_STARTING_BL1", type="INFO", timeout=TIMEOUT)
    t.close()


@pytest.mark.parametrize("slot", ALL_SLOTS, ids=[f"slot{n}" for n in ALL_SLOTS])
def test_each_rom_key_slot_can_be_revoked(vp, bootcode_elf, oca_images, slot, tmp_path):
    """Revoking slot N's bit refuses slot N's key.

    PUBK_AUTHORIZED must still appear: authorization looks up the ROM digest and
    succeeds, and only then does the revocation check refuse. That ordering is
    the difference between REVOKED_KEY and INVALID_KEY_HASH, and asserting the
    marker as well as the status is what distinguishes "revoked" from "never
    recognised in the first place" -- both of which would otherwise just be a
    boot that did not happen.
    """
    image = _slot_image(oca_images, slot)
    otp = _revoke_map(tmp_path, f"revoke_slot{slot}", 1 << slot)
    t = vp(_cfg(f"oca_rom_key{slot}_revoked", bootcode_elf, image, otp=otp))
    t.spawn()
    t.expect("PUBK_AUTHORIZED", timeout=TIMEOUT)
    match = t.expect_status("SEP_MSG_REVOKED_KEY", type="ERROR", timeout=TIMEOUT)
    assert "ERROR" in match.group(0)
    t.close()


@pytest.mark.parametrize("slot", ALL_SLOTS, ids=[f"slot{n}" for n in ALL_SLOTS])
def test_revoking_the_other_rom_key_slots_leaves_this_one_usable(
    vp, bootcode_elf, oca_images, slot, tmp_path
):
    """Revoking all five OTHER slots must not stop slot N booting.

    The sharpest of the three axes. "Use" and "revoke" can both pass on a
    revocation check that is offset by one or that ignores the slot index
    altogether; neither survives a case that revokes five specific bits and
    requires the sixth key to still verify.

    It also rules out the opposite error -- a check that treats a non-empty
    revocation bitmap as "something is revoked, refuse" without asking which
    bit. That would boot fine in every other test here.
    """
    image = _slot_image(oca_images, slot)
    others = ALL_SLOTS_MASK & ~(1 << slot)
    otp = _revoke_map(tmp_path, f"revoke_all_but_slot{slot}", others)
    t = vp(_cfg(f"oca_rom_key{slot}_others_revoked", bootcode_elf, image, otp=otp))
    t.spawn()
    t.expect("PUBK_AUTHORIZED", timeout=TIMEOUT)
    t.expect("RSA_VERIFY_OK", timeout=TIMEOUT)
    t.expect_status("SEP_MSG_STARTING_BL1", type="INFO", timeout=TIMEOUT)
    t.close()


def test_digest_table_pins_six_slots(bootcode_elf):
    """Guard the premise: six slots, six distinct digests, none NULL.

    Every test above is parametrised over range(6) on the assumption that
    key_digests.c pins exactly that many and that each entry differs. If a slot
    regressed to NULL, or two slots ended up sharing a key, the parametrised
    tests would still pass -- a NULL slot's image would simply never have been
    built, and duplicate digests defeat the whole point of per-slot keys without
    failing anything. Cheap to state here rather than infer from six boots.
    """
    src = paths.KEY_DIGESTS_C.read_text()
    slots = [ln for ln in src.splitlines() if ".digest =" in ln]
    assert len(slots) == 6, f"expected 6 ROM key slots, found {len(slots)}:\n" + "\n".join(slots)
    empty = [ln.strip() for ln in slots if "(void *)0" in ln]
    assert not empty, (
        "ROM key slots left unprovisioned, so their per-slot tests prove nothing:\n"
        + "\n".join(empty)
    )

    # Distinctness, from the digest arrays themselves rather than the table.
    bodies = src.split("static const uint8_t digest_")[1:]
    digests = {b.split("]")[0]: "".join(b.split("{")[1].split("}")[0].split()) for b in bodies}
    assert len(digests) == 6, f"expected 6 digest arrays, found {len(digests)}"
    assert len(set(digests.values())) == 6, (
        "two or more ROM key slots share a digest; a slot resolved off-by-one "
        f"would still match and the per-slot tests would pass regardless: {digests.keys()}"
    )
