# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2026 Tenstorrent USA, Inc.

"""Copy the generated register-field masks the boot ROM assembly uses into a macro-only header.

The generated field headers also declare C types, which the assembler cannot read. This
script copies each selected macro, name and value unchanged, so the assembly aliases in
smc_rom_defs.h still resolve to the owner-generated definition.

Usage:
  python3 gen_asm_reg_defs.py --output out.h dfx_ctrl_status.h smc_efuse_map.h zeroer_ctrl.h
"""

import argparse
import pathlib
import re
import sys

SYMBOLS = (
    "DFX_CTRL_STATUS__STATUS__MEM_REPAIR_DONE_bm",
    "DFX_CTRL_STATUS__STATUS__MEM_REPAIR_SUCCESS_bm",
    "DFX_CTRL_STATUS__STATUS__MBIST_DONE_bm",
    "DFX_CTRL_STATUS__STATUS__MBIST_PASS_bm",
    "DFX_CTRL_STATUS__STATUS__MBIST_ABORT_bm",
    "SMC_EFUSE_MAP__SMC_CONFIG__SRAM_AUTO_ZERO_DISABLE_bm",
    "SMC_EFUSE_MAP__SMC_CONFIG__DFT_IGNORE_ERROR_bm",
    "ZEROER_CTRL__CTRL_STATUS__STATUS_bm",
)

DEFINE = re.compile(r"^\s*#\s*define\s+(\w+)\s+(.*?)\s*$")
NUMBER = re.compile(r"^(0[xX][0-9a-fA-F]+|[0-9]+)$")


def collect(headers):
    """Return {symbol: [(header, value), ...]} for every selected symbol defined in headers."""
    found = {}
    for header in headers:
        for line in header.read_text(encoding="utf-8").splitlines():
            match = DEFINE.match(line)
            if match and match.group(1) in SYMBOLS:
                found.setdefault(match.group(1), []).append((header, match.group(2)))
    return found


def check(found):
    """Return one error message per selected symbol that is absent, repeated or not numeric."""
    errors = []
    for name in SYMBOLS:
        defs = found.get(name, [])
        if not defs:
            errors.append(f"{name} is not defined in any input header")
        elif len(defs) > 1:
            where = ", ".join(str(header) for header, _ in defs)
            errors.append(f"{name} is defined {len(defs)} times: {where}")
        elif not NUMBER.match(defs[0][1]):
            errors.append(f"{name} is {defs[0][1]!r} in {defs[0][0]}, not a single numeric value")
    return errors


def render(found):
    lines = [
        f"/* Generated by {pathlib.Path(__file__).name}. Do not edit. */",
        "#ifndef SMC_ROM_ASM_REG_DEFS_H",
        "#define SMC_ROM_ASM_REG_DEFS_H",
        "",
    ]
    lines += [f"#define {name} {found[name][0][1]}" for name in SYMBOLS]
    lines += ["", "#endif /* SMC_ROM_ASM_REG_DEFS_H */", ""]
    return "\n".join(lines)


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--output", required=True, type=pathlib.Path)
    parser.add_argument("headers", nargs="+", type=pathlib.Path)
    args = parser.parse_args(argv)

    found = collect(args.headers)
    errors = check(found)
    if errors:
        for error in errors:
            print(f"gen_asm_reg_defs.py: error: {error}", file=sys.stderr)
        return 1
    args.output.write_text(render(found), encoding="utf-8")
    return 0


if __name__ == "__main__":
    sys.exit(main())
