# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2026 Tenstorrent USA, Inc.

site:
  title: Open Chiplet Atlas Harness (OCAH) Contributing Guide
  url: /
  start_page: ocah-contributing::index.adoc
content:
  sources:
    - url: .
      branches: HEAD
      start_path: doc/contributing
      edit_url: false
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ./doc/ui-supplemental
output:
  dir: ./doc/contributing/_build/html_antora