# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2026 Tenstorrent USA, Inc.

site:
  title: Open Chiplet Atlas Harness (OCAH) Technical Reference Manual
  url: /
  start_page: ocah-docs::index.adoc
content:
  sources:
    - url: .
      branches: HEAD
      start_path: doc/trm
      edit_url: false
    - url: .
      branches: HEAD
      start_path: doc/home
      edit_url: false
    - url: .
      branches: HEAD
      start_path: doc/integrator
      edit_url: false
    - url: .
      branches: HEAD
      start_path: doc/programmer
      edit_url: false
    - url: .
      branches: HEAD
      start_path: doc/appnotes
      edit_url: false
    - url: .
      branches: HEAD
      start_path: doc/starting
      edit_url: false
asciidoc:
  attributes:
    kroki-default-format: svg
    kroki-fetch-diagram: true
  extensions:
    - asciidoctor-kroki
    - ./tools/doc/block-captions.js
runtime:
  log:
    # See antora-playbook.yml for why this is raised from the default.
    failure_level: error
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ./doc/ui-supplemental
antora:
  extensions:
    - ./tools/doc/block-indexes.js
    - ./tools/doc/preserve-smn-fragments.js
output:
  dir: ./doc/trm/_build/html_antora
