// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 Tenstorrent USA, Inc.
//==================================================
// SEP VCS coverage exclusions -- OTBN instruction-set scope (tier 2).
// Format Version: 2
// ExclMode: default
//
// SEPARATE FILE ON PURPOSE. sep_unreachable_exclusions.el carries only logic an
// RTL tie makes unreachable. This file carries a scope decision instead: OTBN
// instruction decode and the bignum ALU are lowRISC's DV, not SEP's, so SEP does
// not claim them. Adopting this file lowers the denominator on an ownership
// argument, which is a different kind of claim, and it is kept opt-in so the two
// are never confused in a review.
//
// These modules are NOT entirely dark, so they do not belong in
// sep_cov_scope.hier: modinfo.txt reports otbn_decoder 39.52 % line,
// otbn_predecode 49.24 %, otbn_alu_bignum 58.37 %. A hierarchy exclusion would
// also remove the lines SEP does cover. Arm granularity keeps those graded.
//
// Checksums come from `urg -dump full_exclusions line` on the merged vdb at
// build/runs/20260919_225443__vcs__all/cov/merged.vdb. Never hand-written.
//==================================================

CHECKSUM: "2760151689 1247607259"
ANNOTATION: "SEP-OTBN-ISA-NOT-CLAIMED: this is an OWNERSHIP/SCOPE waiver, not a structural unreachability claim. SEP exercises OTBN through its CSR and memory interfaces, not across the full BN.* instruction set. Instruction decode and the bignum ALU are verified by lowRISC's own OTBN DV; SEP DV does not claim them. The remaining OTBN logic -- the controller, the scramble control and the memory path -- stays graded because SEP tests drive it. Nothing in the SEP integration ties these arms off: otbn is elaborated in full with Stub(1'b0) and RegFile(RegFileFF) at hw/sys/sep/rtl/sep_crypto_otbn_wrapper.sv:161-165, so a firmware test that executed the missing instructions would cover them. Only the never-executed decode arms are listed; every line any SEP test reached stays in the denominator. NOT waived: otbn_controller, otbn_scramble_ctrl, otbn_core, otbn_reg_top and the OTBN memory path."
MODULE: otbn_decoder
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_decoder.sv, LineNumber: 223"
Block 5 "3064683239" "imm_b_base = imm_b_type_base;"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_decoder.sv, LineNumber: 224"
Block 6 "2419867905" "imm_b_base = imm_j_type_base;"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_decoder.sv, LineNumber: 391"
Block 14 "2421066452" "case (insn[31:25])"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_decoder.sv, LineNumber: 392"
Block 15 "3652931631" "illegal_insn = 1'b0;"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_decoder.sv, LineNumber: 393"
Block 16 "2327227586" "illegal_insn = 1'b1;"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_decoder.sv, LineNumber: 398"
Block 17 "2408908492" "case (insn[31:25])"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_decoder.sv, LineNumber: 400"
Block 18 "2159224758" "illegal_insn = 1'b0;"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_decoder.sv, LineNumber: 402"
Block 19 "2732101030" "illegal_insn = 1'b1;"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_decoder.sv, LineNumber: 406"
Block 20 "2483568170" "illegal_insn = 1'b1;"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_decoder.sv, LineNumber: 428"
Block 23 "1378415622" "illegal_insn = 1'b1;"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_decoder.sv, LineNumber: 445"
Block 25 "2563676722" "illegal_insn = 1'b1;"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_decoder.sv, LineNumber: 456"
Block 28 "1352124157" "illegal_insn = 1'b1;"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_decoder.sv, LineNumber: 465"
Block 30 "211627533" "insn_subset = InsnSubsetBase;"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_decoder.sv, LineNumber: 472"
Block 31 "1492846166" "illegal_insn = 1'b1;"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_decoder.sv, LineNumber: 477"
Block 33 "476219672" "insn_subset = InsnSubsetBase;"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_decoder.sv, LineNumber: 484"
Block 34 "2353595461" "insn_subset = InsnSubsetBase;"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_decoder.sv, LineNumber: 491"
Block 35 "1631712347" "illegal_insn = 1'b1;"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_decoder.sv, LineNumber: 508"
Block 40 "3751197417" "illegal_insn = 1'b1;"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_decoder.sv, LineNumber: 513"
Block 42 "1418136111" "illegal_insn = 1'b1;"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_decoder.sv, LineNumber: 524"
Block 45 "872343632" "ispr_rd_insn = (((insn_rd != 5'b0) | (imm_b_base[11:0] == CsrFg0)) | (imm_b_base[11:0] == CsrFg1));"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_decoder.sv, LineNumber: 533"
Block 48 "476602599" "ispr_rs_insn = 1'b1;"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_decoder.sv, LineNumber: 540"
Block 50 "1897258876" "illegal_insn = 1'b1;"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_decoder.sv, LineNumber: 550"
Block 51 "2402783334" "insn_subset = InsnSubsetBignum;"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_decoder.sv, LineNumber: 556"
Block 52 "1120488012" "rf_ren_b_bignum = 1'b1;"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_decoder.sv, LineNumber: 559"
Block 54 "3965784436" "case (insn[14:12])"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_decoder.sv, LineNumber: 561"
Block 55 "1127367424" "illegal_insn = 1'b1;"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_decoder.sv, LineNumber: 562"
Block 56 "3526460819" ";"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_decoder.sv, LineNumber: 573"
Block 57 "3682949320" "case (insn[14:12])"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_decoder.sv, LineNumber: 576"
Block 58 "3161520334" "insn_subset = InsnSubsetBignum;"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_decoder.sv, LineNumber: 582"
Block 59 "301043809" "alu_elen_bignum = AluElen32;"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_decoder.sv, LineNumber: 583"
Block 60 "3827901433" "illegal_insn = 1'b1;"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_decoder.sv, LineNumber: 588"
Block 61 "3099884281" "insn_subset = InsnSubsetBignum;"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_decoder.sv, LineNumber: 594"
Block 62 "1200963194" "trn_elen_bignum = TrnElen32;"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_decoder.sv, LineNumber: 595"
Block 63 "3896737932" "trn_elen_bignum = TrnElen64;"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_decoder.sv, LineNumber: 596"
Block 64 "333852887" "trn_elen_bignum = TrnElen128;"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_decoder.sv, LineNumber: 597"
Block 65 "3327953604" "illegal_insn = 1'b1;"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_decoder.sv, LineNumber: 602"
Block 66 "1780316154" "insn_subset = InsnSubsetBignum;"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_decoder.sv, LineNumber: 607"
Block 67 "3028180424" "alu_elen_bignum = AluElen32;"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_decoder.sv, LineNumber: 608"
Block 68 "3530267254" "illegal_insn = 1'b1;"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_decoder.sv, LineNumber: 614"
Block 69 "2438984993" "insn_subset = InsnSubsetBignum;"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_decoder.sv, LineNumber: 625"
Block 70 "3207508608" "mac_elen_bignum = MacElen32;"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_decoder.sv, LineNumber: 626"
Block 71 "1097249779" "illegal_insn = 1'b1;"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_decoder.sv, LineNumber: 631"
Block 72 "2879505608" "insn_subset = InsnSubsetBignum;"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_decoder.sv, LineNumber: 637"
Block 73 "652579856" "illegal_insn = 1'b1;"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_decoder.sv, LineNumber: 638"
Block 74 "1427504783" "illegal_insn = 1'b1;"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_decoder.sv, LineNumber: 649"
Block 76 "3854879680" "insn_subset = InsnSubsetBase;"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_decoder.sv, LineNumber: 660"
Block 78 "2916369697" "insn_subset = InsnSubsetBignum;"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_decoder.sv, LineNumber: 664"
Block 79 "3933802194" "illegal_insn = 1'b1;"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_decoder.sv, LineNumber: 677"
Block 81 "100416461" "rf_we_bignum = 1'b1;"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_decoder.sv, LineNumber: 684"
Block 82 "45396311" "rf_ren_a_bignum = 1'b1;"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_decoder.sv, LineNumber: 688"
Block 83 "2138950554" "ld_insn = 1'b1;"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_decoder.sv, LineNumber: 696"
Block 84 "2566299835" "a_wlen_word_inc_bignum = 1'b1;"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_decoder.sv, LineNumber: 701"
Block 86 "2762989365" "if (insn[7])"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_decoder.sv, LineNumber: 702"
Block 87 "3519288929" "d_inc_bignum = 1'b1;"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_decoder.sv, LineNumber: 707"
Block 89 "3313617619" "if ((insn[8] & insn[7]))"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_decoder.sv, LineNumber: 709"
Block 90 "499684707" "a_wlen_word_inc_bignum = 1'b0;"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_decoder.sv, LineNumber: 722"
Block 93 "2901684077" "a_wlen_word_inc_bignum = 1'b1;"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_decoder.sv, LineNumber: 728"
Block 96 "3367920734" "b_inc_bignum = 1'b1;"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_decoder.sv, LineNumber: 735"
Block 99 "3937584431" "a_wlen_word_inc_bignum = 1'b0;"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_decoder.sv, LineNumber: 741"
Block 101 "184443922" "insn_subset = InsnSubsetBignum;"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_decoder.sv, LineNumber: 747"
Block 102 "1433444256" "rf_a_indirect_bignum = 1'b1;"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_decoder.sv, LineNumber: 753"
Block 103 "4044734519" "a_inc_bignum = 1'b1;"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_decoder.sv, LineNumber: 758"
Block 105 "2924370817" "if (insn[7])"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_decoder.sv, LineNumber: 759"
Block 106 "2337242981" "d_inc_bignum = 1'b1;"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_decoder.sv, LineNumber: 764"
Block 108 "273258053" "if ((insn[9] & insn[7]))"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_decoder.sv, LineNumber: 766"
Block 109 "2463846534" "a_inc_bignum = 1'b0;"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_decoder.sv, LineNumber: 774"
Block 113 "763514566" "rf_ren_a_bignum = 1'b1;"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_decoder.sv, LineNumber: 782"
Block 115 "1272723953" "illegal_insn = 1'b1;"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_decoder.sv, LineNumber: 791"
Block 116 "137901581" "insn_subset = InsnSubsetBignum;"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_decoder.sv, LineNumber: 802"
Block 117 "1609109514" "rf_we_bignum = 1'b1;"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_decoder.sv, LineNumber: 806"
Block 119 "1176563560" "mac_acc_add_en = (~insn[12]);"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_decoder.sv, LineNumber: 829"
Block 122 "3636836435" "alu_adder_carry_sel_bignum = 1'b1;"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_decoder.sv, LineNumber: 837"
Block 124 "3815634698" "alu_adder_carry_sel_bignum = 1'b0;"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_decoder.sv, LineNumber: 861"
Block 129 "3613209534" "mac_adder_carry_sel_bignum = 4'b1111;"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_decoder.sv, LineNumber: 863"
Block 131 "2157044784" "mac_adder_carry_sel_bignum = 4'b0;"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_decoder.sv, LineNumber: 909"
Block 136 "216258271" "alu_operator_base = AluOpBaseXor;"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_decoder.sv, LineNumber: 910"
Block 137 "3378341805" "alu_operator_base = AluOpBaseOr;"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_decoder.sv, LineNumber: 911"
Block 138 "3552352503" "alu_operator_base = AluOpBaseAnd;"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_decoder.sv, LineNumber: 914"
Block 139 "2718190176" "alu_operator_base = AluOpBaseSll;"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_decoder.sv, LineNumber: 918"
Block 140 "2616965265" "if ((insn_alu[31:27] == 5'b0))"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_decoder.sv, LineNumber: 919"
Block 141 "3690987430" "alu_operator_base = AluOpBaseSrl;"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_decoder.sv, LineNumber: 920"
Block 142 "4029839123" "if ((insn_alu[31:27] == 5'b01000))"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_decoder.sv, LineNumber: 921"
Block 143 "1248606983" "alu_operator_base = AluOpBaseSra;"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_decoder.sv, LineNumber: 925"
Block 145 "202815504" ";"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_decoder.sv, LineNumber: 937"
Block 149 "2290763313" "alu_operator_base = AluOpBaseSub;"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_decoder.sv, LineNumber: 939"
Block 151 "635145527" "alu_operator_base = AluOpBaseOr;"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_decoder.sv, LineNumber: 941"
Block 153 "531089255" "alu_operator_base = AluOpBaseSll;"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_decoder.sv, LineNumber: 942"
Block 154 "3319171411" "alu_operator_base = AluOpBaseSrl;"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_decoder.sv, LineNumber: 943"
Block 155 "2699228359" "alu_operator_base = AluOpBaseSra;"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_decoder.sv, LineNumber: 944"
Block 156 "2997116772" ";"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_decoder.sv, LineNumber: 972"
Block 160 "4045110830" "alu_op_a_mux_sel_base = OpASelCurrPc;"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_decoder.sv, LineNumber: 980"
Block 161 "1267722792" "alu_op_a_mux_sel_base = OpASelCurrPc;"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_decoder.sv, LineNumber: 987"
Block 162 "51255520" "alu_op_a_mux_sel_base = OpASelRegister;"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_decoder.sv, LineNumber: 1008"
Block 164 "1753380413" "alu_flag_en_bignum = 1'b1;"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_decoder.sv, LineNumber: 1011"
Block 165 "2938182266" "alu_operator_bignum = AluOpBignumAdd;"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_decoder.sv, LineNumber: 1012"
Block 166 "379534570" "alu_operator_bignum = AluOpBignumSub;"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_decoder.sv, LineNumber: 1013"
Block 167 "3166733153" "alu_operator_bignum = AluOpBignumAddc;"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_decoder.sv, LineNumber: 1014"
Block 168 "239040925" "alu_operator_bignum = AluOpBignumSubb;"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_decoder.sv, LineNumber: 1016"
Block 169 "562387084" "if (insn_alu[30])"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_decoder.sv, LineNumber: 1017"
Block 170 "689719887" "alu_operator_bignum = AluOpBignumSub;"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_decoder.sv, LineNumber: 1019"
Block 171 "2038574404" "alu_operator_bignum = AluOpBignumAdd;"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_decoder.sv, LineNumber: 1023"
Block 172 "2702571755" "if (insn_alu[30])"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_decoder.sv, LineNumber: 1024"
Block 173 "2237269037" "alu_operator_bignum = AluOpBignumSubm;"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_decoder.sv, LineNumber: 1026"
Block 174 "948310095" "alu_operator_bignum = AluOpBignumAddm;"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_decoder.sv, LineNumber: 1029"
Block 175 "641785138" ";"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_decoder.sv, LineNumber: 1032"
Block 176 "2755066298" "if ((insn_alu[14:12] != 3'b100))"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_decoder.sv, LineNumber: 1033"
Block 177 "731973409" "alu_op_b_mux_sel_bignum = OpBSelRegister;"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_decoder.sv, LineNumber: 1036"
Block 178 "3803198888" "alu_op_b_mux_sel_bignum = OpBSelImmediate;"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_decoder.sv, LineNumber: 1049"
Block 179 "4082109822" "case (insn_alu[14:12])"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_decoder.sv, LineNumber: 1052"
Block 180 "3903968379" "alu_shift_amt_bignum = '0;"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_decoder.sv, LineNumber: 1056"
Block 181 "2142743425" "alu_operator_bignum = AluOpBignumAddv;"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_decoder.sv, LineNumber: 1057"
Block 182 "292764520" "alu_operator_bignum = AluOpBignumAddvm;"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_decoder.sv, LineNumber: 1058"
Block 183 "4025009946" "alu_operator_bignum = AluOpBignumSubv;"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_decoder.sv, LineNumber: 1059"
Block 184 "2307273664" "alu_operator_bignum = AluOpBignumSubvm;"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_decoder.sv, LineNumber: 1060"
Block 185 "3332535098" "alu_operator_bignum = AluOpBignumAddv;"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_decoder.sv, LineNumber: 1065"
Block 186 "1895380554" "alu_op_b_mux_sel_bignum = OpBSelRegister;"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_decoder.sv, LineNumber: 1070"
Block 187 "12308382" "alu_shift_amt_bignum = shift_amt_shv_bignum;"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_decoder.sv, LineNumber: 1076"
Block 188 "999253802" "alu_shift_amt_bignum = shift_amt_pack_bignum;"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_decoder.sv, LineNumber: 1080"
Block 189 "3440081077" ";"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_decoder.sv, LineNumber: 1096"
Block 191 "2217184303" "alu_shift_amt_bignum = shift_amt_a_type_bignum;"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_decoder.sv, LineNumber: 1101"
Block 192 "744127904" "alu_shift_amt_bignum = shift_amt_a_type_bignum;"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_decoder.sv, LineNumber: 1106"
Block 193 "3726263665" "alu_shift_amt_bignum = shift_amt_a_type_bignum;"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_decoder.sv, LineNumber: 1117"
Block 195 "3071804483" "alu_shift_amt_bignum = shift_amt_s_type_bignum;"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_decoder.sv, LineNumber: 1120"
Block 196 "987722930" ";"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_decoder.sv, LineNumber: 1131"
Block 198 "1733324947" "alu_operator_bignum = AluOpBignumSub;"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_decoder.sv, LineNumber: 1137"
Block 199 "3434948791" "alu_operator_bignum = AluOpBignumSubb;"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_decoder.sv, LineNumber: 1159"
Block 202 "3366406210" "if (((insn[30] == 1'b1) || (insn[29] == 1'b1)))"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_decoder.sv, LineNumber: 1160"
Block 203 "3020868160" "mac_flag_en_bignum = 1'b1;"

CHECKSUM: "800684319 1647014817"
ANNOTATION: "SEP-OTBN-ISA-NOT-CLAIMED: this is an OWNERSHIP/SCOPE waiver, not a structural unreachability claim. SEP exercises OTBN through its CSR and memory interfaces, not across the full BN.* instruction set. Instruction decode and the bignum ALU are verified by lowRISC's own OTBN DV; SEP DV does not claim them. The remaining OTBN logic -- the controller, the scramble control and the memory path -- stays graded because SEP tests drive it. Nothing in the SEP integration ties these arms off: otbn is elaborated in full with Stub(1'b0) and RegFile(RegFileFF) at hw/sys/sep/rtl/sep_crypto_otbn_wrapper.sv:161-165, so a firmware test that executed the missing instructions would cover them. Only the never-executed decode arms are listed; every line any SEP test reached stays in the denominator. NOT waived: otbn_controller, otbn_scramble_ctrl, otbn_core, otbn_reg_top and the OTBN memory path."
MODULE: otbn_predecode
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_predecode.sv, LineNumber: 306"
Block 12 "3062992740" "rf_ren_a_base = 1'b1;"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_predecode.sv, LineNumber: 313"
Block 13 "2046089817" "rf_we_d_base = 1'b1;"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_predecode.sv, LineNumber: 339"
Block 19 "1540565926" "ispr_rd_en = 1'b0;"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_predecode.sv, LineNumber: 345"
Block 21 "1976659984" "ispr_rd_en = (((imem_rdata_i[11:7] != 5'b0) | (csr_addr == CsrFg0)) | (csr_addr == CsrFg1));"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_predecode.sv, LineNumber: 353"
Block 24 "1957719223" "ispr_rd_en = 1'b1;"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_predecode.sv, LineNumber: 368"
Block 27 "3908173135" "case (imem_rdata_i[14:12])"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_predecode.sv, LineNumber: 371"
Block 28 "273676125" "rf_ren_a_bignum = 1'b1;"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_predecode.sv, LineNumber: 384"
Block 29 "860810144" "alu_bignum_adder_y_op_b_invert = 1'b1;"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_predecode.sv, LineNumber: 389"
Block 31 "2385623003" "rf_ren_a_bignum = 1'b1;"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_predecode.sv, LineNumber: 401"
Block 32 "2447034608" "alu_bignum_adder_y_op_b_invert = 1'b1;"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_predecode.sv, LineNumber: 406"
Block 34 "3415418783" "rf_ren_a_bignum = 1'b1;"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_predecode.sv, LineNumber: 418"
Block 35 "3253391368" "alu_bignum_adder_x_carries_in = 8'(1);"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_predecode.sv, LineNumber: 421"
Block 36 "4088054233" "alu_bignum_adder_y_op_b_invert = 1'b1;"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_predecode.sv, LineNumber: 424"
Block 37 "358680954" ";"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_predecode.sv, LineNumber: 439"
Block 39 "3483997225" "rf_ren_a_bignum = 1'b1;"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_predecode.sv, LineNumber: 447"
Block 40 "3275361208" "alu_bignum_alu_elen = AluElen32;"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_predecode.sv, LineNumber: 448"
Block 41 "1355512438" "alu_bignum_alu_elen = AluElen256;"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_predecode.sv, LineNumber: 451"
Block 42 "454490802" "if (imem_rdata_i[28])"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_predecode.sv, LineNumber: 452"
Block 43 "2438684651" "alu_bignum_adder_x_en = 1'b1;"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_predecode.sv, LineNumber: 459"
Block 44 "2606646793" "alu_bignum_adder_x_carries_in = {otbn_pkg::NVecProc {1'b1}};"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_predecode.sv, LineNumber: 462"
Block 45 "316729199" "alu_bignum_adder_y_carries_top = {(otbn_pkg::NVecProc - 1) {1'b1}};"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_predecode.sv, LineNumber: 466"
Block 46 "1383586970" "alu_bignum_shift_en = 1'b1;"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_predecode.sv, LineNumber: 473"
Block 47 "77941617" "alu_bignum_adder_y_carries_top = {(otbn_pkg::NVecProc - 1) {1'b1}};"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_predecode.sv, LineNumber: 480"
Block 49 "254134794" "rf_ren_a_bignum = 1'b1;"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_predecode.sv, LineNumber: 489"
Block 50 "780053660" "alu_bignum_trn_elen = TrnElen32;"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_predecode.sv, LineNumber: 490"
Block 51 "2175275626" "alu_bignum_trn_elen = TrnElen64;"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_predecode.sv, LineNumber: 491"
Block 52 "2606232735" "alu_bignum_trn_elen = TrnElen128;"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_predecode.sv, LineNumber: 492"
Block 53 "1490095231" "alu_bignum_trn_elen = TrnElen32;"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_predecode.sv, LineNumber: 497"
Block 54 "1635793308" "rf_ren_b_bignum = 1'b1;"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_predecode.sv, LineNumber: 512"
Block 55 "1723188753" "alu_bignum_alu_elen = AluElen32;"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_predecode.sv, LineNumber: 513"
Block 56 "1720304633" "alu_bignum_alu_elen = AluElen256;"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_predecode.sv, LineNumber: 519"
Block 57 "394842692" "rf_ren_a_bignum = 1'b1;"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_predecode.sv, LineNumber: 530"
Block 58 "1116290480" "mac_bignum_elen = MacElen32;"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_predecode.sv, LineNumber: 531"
Block 59 "195582056" "mac_bignum_elen = MacElen64;"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_predecode.sv, LineNumber: 544"
Block 61 "3511820099" "alu_bignum_shift_op_a_sel[AluShiftOpDense] = 1'b1;"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_predecode.sv, LineNumber: 556"
Block 63 "2066346491" ";"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_predecode.sv, LineNumber: 587"
Block 67 "3159102658" "rf_we_bignum = 1'b1;"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_predecode.sv, LineNumber: 601"
Block 68 "1158261257" "rf_we_bignum = 1'b1;"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_predecode.sv, LineNumber: 611"
Block 69 "2677475346" ";"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_predecode.sv, LineNumber: 628"
Block 72 "1132113245" "rf_ren_a_bignum = 1'b1;"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_predecode.sv, LineNumber: 645"
Block 74 "1616029007" "rf_we_a_base = 1'b1;"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_predecode.sv, LineNumber: 649"
Block 77 "3088967801" "rf_we_b_base = 1'b1;"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_predecode.sv, LineNumber: 653"
Block 79 "3142284300" "if (imem_rdata_i[31])"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_predecode.sv, LineNumber: 659"
Block 80 "1913059008" "rf_ren_a_base = 1'b1;"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_predecode.sv, LineNumber: 663"
Block 81 "1601601269" "rf_we_a_base = 1'b1;"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_predecode.sv, LineNumber: 664"
Block 82 "3001675732" "if (imem_rdata_i[7])"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_predecode.sv, LineNumber: 665"
Block 83 "4162031447" "rf_we_b_base = 1'b1;"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_predecode.sv, LineNumber: 668"
Block 85 "1651385740" "rf_we_bignum = 1'b1;"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_predecode.sv, LineNumber: 674"
Block 87 "334820006" "rf_ren_a_bignum = 1'b1;"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_predecode.sv, LineNumber: 681"
Block 89 "1474723092" ";"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_predecode.sv, LineNumber: 728"
Block 96 "1189211452" "alu_bignum_adder_carry_sel = 1'b1;"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_predecode.sv, LineNumber: 736"
Block 98 "3956146785" "alu_bignum_adder_carry_sel = 1'b0;"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_predecode.sv, LineNumber: 746"
Block 100 "1788917087" "mac_bignum_adder_carry_sel = 4'b1111;"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_predecode.sv, LineNumber: 748"
Block 102 "216269472" "mac_bignum_adder_carry_sel = 4'b0;"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_predecode.sv, LineNumber: 759"
Block 106 "3077146078" "ispr_addr = IsprFlags;"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_predecode.sv, LineNumber: 761"
Block 107 "2799540599" "ispr_addr = IsprMod;"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_predecode.sv, LineNumber: 763"
Block 109 "3703571397" "ispr_addr = IsprUrnd;"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_predecode.sv, LineNumber: 764"
Block 110 "2320132539" "ispr_addr = IsprMaiCtrl;"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_predecode.sv, LineNumber: 765"
Block 111 "3261573760" "ispr_addr = IsprMaiStatus;"

CHECKSUM: "2653048841 557863462"
ANNOTATION: "SEP-OTBN-ISA-NOT-CLAIMED: this is an OWNERSHIP/SCOPE waiver, not a structural unreachability claim. SEP exercises OTBN through its CSR and memory interfaces, not across the full BN.* instruction set. Instruction decode and the bignum ALU are verified by lowRISC's own OTBN DV; SEP DV does not claim them. The remaining OTBN logic -- the controller, the scramble control and the memory path -- stays graded because SEP tests drive it. Nothing in the SEP integration ties these arms off: otbn is elaborated in full with Stub(1'b0) and RegFile(RegFileFF) at hw/sys/sep/rtl/sep_crypto_otbn_wrapper.sv:161-165, so a firmware test that executed the missing instructions would cover them. Only the never-executed decode arms are listed; every line any SEP test reached stays in the denominator. NOT waived: otbn_controller, otbn_scramble_ctrl, otbn_core, otbn_reg_top and the OTBN memory path."
MODULE: otbn_alu_bignum
ANNOTATION: "vcs_gen_start:i_word=0:vcs_gen_end:FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_alu_bignum.sv, LineNumber: 465"
Block 38 "956038075" "mod_no_intg_d[(0 * 32)+:32] = ispr_base_wdata_i;"
ANNOTATION: "vcs_gen_start:i_word=1:vcs_gen_end:FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_alu_bignum.sv, LineNumber: 465"
Block 45 "3291246159" "mod_no_intg_d[(1 * 32)+:32] = ispr_base_wdata_i;"
ANNOTATION: "vcs_gen_start:i_word=2:vcs_gen_end:FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_alu_bignum.sv, LineNumber: 465"
Block 52 "3431703340" "mod_no_intg_d[(2 * 32)+:32] = ispr_base_wdata_i;"
ANNOTATION: "vcs_gen_start:i_word=3:vcs_gen_end:FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_alu_bignum.sv, LineNumber: 465"
Block 59 "811349720" "mod_no_intg_d[(3 * 32)+:32] = ispr_base_wdata_i;"
ANNOTATION: "vcs_gen_start:i_word=4:vcs_gen_end:FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_alu_bignum.sv, LineNumber: 465"
Block 66 "2581064395" "mod_no_intg_d[(4 * 32)+:32] = ispr_base_wdata_i;"
ANNOTATION: "vcs_gen_start:i_word=5:vcs_gen_end:FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_alu_bignum.sv, LineNumber: 465"
Block 73 "1694531391" "mod_no_intg_d[(5 * 32)+:32] = ispr_base_wdata_i;"
ANNOTATION: "vcs_gen_start:i_word=6:vcs_gen_end:FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_alu_bignum.sv, LineNumber: 465"
Block 80 "1839706716" "mod_no_intg_d[(6 * 32)+:32] = ispr_base_wdata_i;"
ANNOTATION: "vcs_gen_start:i_word=7:vcs_gen_end:FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_alu_bignum.sv, LineNumber: 465"
Block 87 "2440046504" "mod_no_intg_d[(7 * 32)+:32] = ispr_base_wdata_i;"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_alu_bignum.sv, LineNumber: 1006"
Block 94 "2390664991" "expected_adder_y_carries_top = '0;"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_alu_bignum.sv, LineNumber: 1016"
Block 95 "503936762" "adder_update_flags_en_raw = 1'b1;"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_alu_bignum.sv, LineNumber: 1024"
Block 97 "262754606" "expected_adder_y_carries_top = '0;"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_alu_bignum.sv, LineNumber: 1042"
Block 98 "172825883" "expected_adder_x_carries_in = '0;"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_alu_bignum.sv, LineNumber: 1058"
Block 99 "264279508" "expected_adder_y_carries_top = ((operation_i.op == AluOpBignumSub) ? '0 : {(otbn_pkg::NVecProc - 1) {1'b1}});"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_alu_bignum.sv, LineNumber: 1069"
Block 100 "2117391667" "adder_update_flags_en_raw = 1'b1;"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_alu_bignum.sv, LineNumber: 1077"
Block 102 "591282404" "expected_adder_y_carries_top = '0;"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_alu_bignum.sv, LineNumber: 1095"
Block 103 "1819106920" "expected_adder_x_carries_in = ((operation_i.op == AluOpBignumSubm) ? 8'(1) : {otbn_pkg::NVecProc {1'b1}});"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_alu_bignum.sv, LineNumber: 1112"
Block 104 "169304120" "expected_shift_op_a_sel[AluShiftOpFull] = 1'b1;"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_alu_bignum.sv, LineNumber: 1143"
Block 106 "1047634862" "expected_trn_en = 1'b1;"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_alu_bignum.sv, LineNumber: 1147"
Block 107 "2028188105" "expected_shift_op_b_sel[AluShiftOpFull] = 1'b1;"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_alu_bignum.sv, LineNumber: 1156"
Block 108 "3066204874" "expected_shift_op_a_sel[AluShiftOpDense] = 1'b1;"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_alu_bignum.sv, LineNumber: 1166"
Block 109 "2072495830" "expected_shift_op_a_sel[AluShiftOpFull] = 1'b1;"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_alu_bignum.sv, LineNumber: 1174"
Block 111 "2753740455" ";"
ANNOTATION: "FileName: /proj_soc/user_dev/yenhenglai/tt-oca-harness/vendor/lowRISC/opentitan/upstream/hw/ip/otbn/rtl/otbn_alu_bignum.sv, LineNumber: 1331"
Block 113 "3306625028" "adder_y_res_used = arithmetic_result_used_adder_y;"
