// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 Tenstorrent USA, Inc.
//==================================================
// SEP VCS coverage exclusions -- crossbar and interconnect toggle bits that the
// RTL makes constant.
// Format Version: 2
// ExclMode: default
//
// Scope: the cocotb VCS elaboration of sep_uvm_top, target `default`, on top of
// the other cov/config/vcs exclusion files. Instances: sep_local_axi_xbar_wrapper and its
// sep_local_axi_xbar, sep_system_peripherals_xbar_wrapper and its
// sep_system_peripherals_xbar, and sep_crypto_axi_interconnect.
//
// Each block waives request-side bits that cannot take a second value in any
// legal system: a field every connected initiator ties in RTL, an initiator
// index bit that no connected initiator sets, an address bit outside every
// decode rule of a target port, or a direct copy of a port the base file waives.
//
// Two rules keep this file honest:
//   * A field that the SMN inbound port, an integrator-driven target, or any
//     free CPU/DMA field can reach is NOT listed. Those holes are stimulus gaps.
//   * A bit that any leaf toggled in either direction is NOT listed. Every
//     listed bit had no 0->1 and no 1->0 toggle in the merged database that
//     supplies the checksums, and urg -excl_strict accepts the file.
//
// Checksums come from `urg -dump full_exclusions tgl` on the merged VDB.
//==================================================

CHECKSUM: "3529663893 1660934675"
INSTANCE: sep_uvm_top.u_dut.u_sep.u_sep_local_axi_xbar_wrapper.u_sep_local_axi_xbar
ANNOTATION: "SEP-XBAR-INPUT-COPY: xbar_slv_req[0..3] are direct copies of the initiator ports (hw/sys/sep/rtl/crossbars/sep_local_axi_xbar.sv:215-227). Each listed field is the same tied field that sep_master_tie_exclusions.el waives on the port (IFU el2_ifu_mem_ctl.sv:1074-1101, LSU el2_lsu_bus_buffer.sv:881-907, debug el2_dbg.sv:738-774, DMA axi_lite_to_axi.sv:39-67 and sep_dma_wrap.sv:283-284, AxUSER/AWATOP sep_cpu.sv:493-508). NOT waived: xbar_slv_req[4] (ext, integrator-driven) and every field the base file leaves graded. aw.addr bit 28 stays graded on the ports after the IFU window remap: axi_window_remap (hw/common/axi/axi_window_remap.sv:39-51) moves a raw address of 0 to 0x1000_0000 when SEP_LOCAL_BASE_ADDR[31:0] is 0, and that CSR is software-writable (sep_cpu_ctrl.rdl:181-188)."
Toggle xbar_slv_req[0].ar.size "logic xbar_slv_req[0].ar.size[2:0]"
Toggle xbar_slv_req[0].ar.prot "logic xbar_slv_req[0].ar.prot[2:0]"
Toggle xbar_slv_req[0].ar.cache "logic xbar_slv_req[0].ar.cache[3:0]"
Toggle xbar_slv_req[0].ar.len "logic xbar_slv_req[0].ar.len[7:0]"
Toggle xbar_slv_req[0].ar.burst "logic xbar_slv_req[0].ar.burst[1:0]"
Toggle xbar_slv_req[0].ar.qos "logic xbar_slv_req[0].ar.qos[3:0]"
Toggle xbar_slv_req[0].ar.lock "logic xbar_slv_req[0].ar.lock"
Toggle xbar_slv_req[0].ar.user "logic xbar_slv_req[0].ar.user[11:0]"
Toggle xbar_slv_req[0].aw_valid "logic xbar_slv_req[0].aw_valid"
Toggle xbar_slv_req[0].aw.id "logic xbar_slv_req[0].aw.id[2:0]"
Toggle xbar_slv_req[0].aw.addr [0] "logic xbar_slv_req[0].aw.addr[31:0]"
Toggle xbar_slv_req[0].aw.addr [1] "logic xbar_slv_req[0].aw.addr[31:0]"
Toggle xbar_slv_req[0].aw.addr [2] "logic xbar_slv_req[0].aw.addr[31:0]"
Toggle xbar_slv_req[0].aw.addr [3] "logic xbar_slv_req[0].aw.addr[31:0]"
Toggle xbar_slv_req[0].aw.addr [4] "logic xbar_slv_req[0].aw.addr[31:0]"
Toggle xbar_slv_req[0].aw.addr [5] "logic xbar_slv_req[0].aw.addr[31:0]"
Toggle xbar_slv_req[0].aw.addr [6] "logic xbar_slv_req[0].aw.addr[31:0]"
Toggle xbar_slv_req[0].aw.addr [7] "logic xbar_slv_req[0].aw.addr[31:0]"
Toggle xbar_slv_req[0].aw.addr [8] "logic xbar_slv_req[0].aw.addr[31:0]"
Toggle xbar_slv_req[0].aw.addr [9] "logic xbar_slv_req[0].aw.addr[31:0]"
Toggle xbar_slv_req[0].aw.addr [10] "logic xbar_slv_req[0].aw.addr[31:0]"
Toggle xbar_slv_req[0].aw.addr [11] "logic xbar_slv_req[0].aw.addr[31:0]"
Toggle xbar_slv_req[0].aw.addr [12] "logic xbar_slv_req[0].aw.addr[31:0]"
Toggle xbar_slv_req[0].aw.addr [13] "logic xbar_slv_req[0].aw.addr[31:0]"
Toggle xbar_slv_req[0].aw.addr [14] "logic xbar_slv_req[0].aw.addr[31:0]"
Toggle xbar_slv_req[0].aw.addr [15] "logic xbar_slv_req[0].aw.addr[31:0]"
Toggle xbar_slv_req[0].aw.addr [16] "logic xbar_slv_req[0].aw.addr[31:0]"
Toggle xbar_slv_req[0].aw.addr [17] "logic xbar_slv_req[0].aw.addr[31:0]"
Toggle xbar_slv_req[0].aw.addr [18] "logic xbar_slv_req[0].aw.addr[31:0]"
Toggle xbar_slv_req[0].aw.addr [19] "logic xbar_slv_req[0].aw.addr[31:0]"
Toggle xbar_slv_req[0].aw.addr [20] "logic xbar_slv_req[0].aw.addr[31:0]"
Toggle xbar_slv_req[0].aw.addr [21] "logic xbar_slv_req[0].aw.addr[31:0]"
Toggle xbar_slv_req[0].aw.addr [22] "logic xbar_slv_req[0].aw.addr[31:0]"
Toggle xbar_slv_req[0].aw.addr [23] "logic xbar_slv_req[0].aw.addr[31:0]"
Toggle xbar_slv_req[0].aw.addr [24] "logic xbar_slv_req[0].aw.addr[31:0]"
Toggle xbar_slv_req[0].aw.addr [25] "logic xbar_slv_req[0].aw.addr[31:0]"
Toggle xbar_slv_req[0].aw.addr [26] "logic xbar_slv_req[0].aw.addr[31:0]"
Toggle xbar_slv_req[0].aw.addr [27] "logic xbar_slv_req[0].aw.addr[31:0]"
Toggle xbar_slv_req[0].aw.addr [29] "logic xbar_slv_req[0].aw.addr[31:0]"
Toggle xbar_slv_req[0].aw.addr [30] "logic xbar_slv_req[0].aw.addr[31:0]"
Toggle xbar_slv_req[0].aw.addr [31] "logic xbar_slv_req[0].aw.addr[31:0]"
Toggle xbar_slv_req[0].aw.len "logic xbar_slv_req[0].aw.len[7:0]"
Toggle xbar_slv_req[0].aw.size "logic xbar_slv_req[0].aw.size[2:0]"
Toggle xbar_slv_req[0].aw.burst "logic xbar_slv_req[0].aw.burst[1:0]"
Toggle xbar_slv_req[0].aw.lock "logic xbar_slv_req[0].aw.lock"
Toggle xbar_slv_req[0].aw.cache "logic xbar_slv_req[0].aw.cache[3:0]"
Toggle xbar_slv_req[0].aw.prot "logic xbar_slv_req[0].aw.prot[2:0]"
Toggle xbar_slv_req[0].aw.qos "logic xbar_slv_req[0].aw.qos[3:0]"
Toggle xbar_slv_req[0].aw.region "logic xbar_slv_req[0].aw.region[3:0]"
Toggle xbar_slv_req[0].aw.atop "logic xbar_slv_req[0].aw.atop[5:0]"
Toggle xbar_slv_req[0].aw.user "logic xbar_slv_req[0].aw.user[11:0]"
Toggle xbar_slv_req[0].w_valid "logic xbar_slv_req[0].w_valid"
Toggle xbar_slv_req[0].w.data "logic xbar_slv_req[0].w.data[63:0]"
Toggle xbar_slv_req[0].w.strb "logic xbar_slv_req[0].w.strb[7:0]"
Toggle xbar_slv_req[0].w.last "logic xbar_slv_req[0].w.last"
Toggle xbar_slv_req[0].w.user "logic xbar_slv_req[0].w.user[11:0]"
Toggle xbar_slv_req[0].b_ready "logic xbar_slv_req[0].b_ready"
Toggle xbar_slv_req[1].aw.qos "logic xbar_slv_req[1].aw.qos[3:0]"
Toggle xbar_slv_req[1].aw.lock "logic xbar_slv_req[1].aw.lock"
Toggle xbar_slv_req[1].aw.user "logic xbar_slv_req[1].aw.user[11:0]"
Toggle xbar_slv_req[1].aw.atop "logic xbar_slv_req[1].aw.atop[5:0]"
Toggle xbar_slv_req[1].ar.qos "logic xbar_slv_req[1].ar.qos[3:0]"
Toggle xbar_slv_req[1].ar.lock "logic xbar_slv_req[1].ar.lock"
Toggle xbar_slv_req[1].ar.user "logic xbar_slv_req[1].ar.user[11:0]"
Toggle xbar_slv_req[1].w.user "logic xbar_slv_req[1].w.user[11:0]"
Toggle xbar_slv_req[2].aw.id "logic xbar_slv_req[2].aw.id[2:0]"
Toggle xbar_slv_req[2].aw.prot "logic xbar_slv_req[2].aw.prot[2:0]"
Toggle xbar_slv_req[2].aw.cache "logic xbar_slv_req[2].aw.cache[3:0]"
Toggle xbar_slv_req[2].aw.len "logic xbar_slv_req[2].aw.len[7:0]"
Toggle xbar_slv_req[2].aw.burst "logic xbar_slv_req[2].aw.burst[1:0]"
Toggle xbar_slv_req[2].aw.qos "logic xbar_slv_req[2].aw.qos[3:0]"
Toggle xbar_slv_req[2].aw.lock "logic xbar_slv_req[2].aw.lock"
Toggle xbar_slv_req[2].aw.user "logic xbar_slv_req[2].aw.user[11:0]"
Toggle xbar_slv_req[2].aw.atop "logic xbar_slv_req[2].aw.atop[5:0]"
Toggle xbar_slv_req[2].ar.id "logic xbar_slv_req[2].ar.id[2:0]"
Toggle xbar_slv_req[2].ar.prot "logic xbar_slv_req[2].ar.prot[2:0]"
Toggle xbar_slv_req[2].ar.cache "logic xbar_slv_req[2].ar.cache[3:0]"
Toggle xbar_slv_req[2].ar.len "logic xbar_slv_req[2].ar.len[7:0]"
Toggle xbar_slv_req[2].ar.burst "logic xbar_slv_req[2].ar.burst[1:0]"
Toggle xbar_slv_req[2].ar.qos "logic xbar_slv_req[2].ar.qos[3:0]"
Toggle xbar_slv_req[2].ar.lock "logic xbar_slv_req[2].ar.lock"
Toggle xbar_slv_req[2].ar.user "logic xbar_slv_req[2].ar.user[11:0]"
Toggle xbar_slv_req[2].w.last "logic xbar_slv_req[2].w.last"
Toggle xbar_slv_req[2].w.user "logic xbar_slv_req[2].w.user[11:0]"
Toggle xbar_slv_req[2].b_ready "logic xbar_slv_req[2].b_ready"
Toggle xbar_slv_req[2].r_ready "logic xbar_slv_req[2].r_ready"
Toggle xbar_slv_req[3].aw.id "logic xbar_slv_req[3].aw.id[2:0]"
Toggle xbar_slv_req[3].aw.len "logic xbar_slv_req[3].aw.len[7:0]"
Toggle xbar_slv_req[3].aw.burst "logic xbar_slv_req[3].aw.burst[1:0]"
Toggle xbar_slv_req[3].aw.lock "logic xbar_slv_req[3].aw.lock"
Toggle xbar_slv_req[3].aw.cache "logic xbar_slv_req[3].aw.cache[3:0]"
Toggle xbar_slv_req[3].aw.qos "logic xbar_slv_req[3].aw.qos[3:0]"
Toggle xbar_slv_req[3].aw.region "logic xbar_slv_req[3].aw.region[3:0]"
Toggle xbar_slv_req[3].aw.atop "logic xbar_slv_req[3].aw.atop[5:0]"
Toggle xbar_slv_req[3].aw.user "logic xbar_slv_req[3].aw.user[11:0]"
Toggle xbar_slv_req[3].ar.id "logic xbar_slv_req[3].ar.id[2:0]"
Toggle xbar_slv_req[3].ar.len "logic xbar_slv_req[3].ar.len[7:0]"
Toggle xbar_slv_req[3].ar.burst "logic xbar_slv_req[3].ar.burst[1:0]"
Toggle xbar_slv_req[3].ar.lock "logic xbar_slv_req[3].ar.lock"
Toggle xbar_slv_req[3].ar.cache "logic xbar_slv_req[3].ar.cache[3:0]"
Toggle xbar_slv_req[3].ar.qos "logic xbar_slv_req[3].ar.qos[3:0]"
Toggle xbar_slv_req[3].ar.region "logic xbar_slv_req[3].ar.region[3:0]"
Toggle xbar_slv_req[3].ar.user "logic xbar_slv_req[3].ar.user[11:0]"
Toggle xbar_slv_req[3].w.user "logic xbar_slv_req[3].w.user[11:0]"
ANNOTATION: "SEP-XBAR-TEST-TIED: sep_local_axi_xbar_wrapper.sv:205 drives test_i with 1'b0; no other driver exists."
Toggle test_i "logic test_i"
ANNOTATION: "SEP-XBAR-EXT-ID-ADDR: the ext initiator is the sep_system_peripherals forward path only (sep.sv:432). Its ID passes axi_id_remap with 4 table entries, which drives mst aw/ar id as {1'b0, 2-bit index} (vendor/pulp-platform/axi/upstream/src/axi_id_remap.sv:198-200; MAX_INFLIGHT_IDS=4 at hw/sys/sep/rtl/sep_system_peripherals/rtl/sep_system_peripherals.sv:642), so id[2] is constant 0. Its address comes from peripheral-xbar port 0, whose rules end at 0x4000_0000 (hw/sys/sep/rtl/crossbars/sep_system_peripherals_xbar.sv:63-67, sep_system_peripherals_xbar_pkg.sv:186-194), truncated to 32 bits, so addr[31:30] are constant 0. NOT waived: id[1:0], addr[29:0] and every other field, which the SMN inbound port drives."
Toggle ext_req_i.aw.id [2] "logic ext_req_i.aw.id[2:0]"
Toggle ext_req_i.aw.addr [31:30] "logic ext_req_i.aw.addr[31:0]"
Toggle ext_req_i.ar.id [2] "logic ext_req_i.ar.id[2:0]"
Toggle ext_req_i.ar.addr [31:30] "logic ext_req_i.ar.addr[31:0]"
Toggle xbar_slv_req[4].aw.id [2] "logic xbar_slv_req[4].aw.id[2:0]"
Toggle xbar_slv_req[4].aw.addr [31:30] "logic xbar_slv_req[4].aw.addr[31:0]"
Toggle xbar_slv_req[4].ar.id [2] "logic xbar_slv_req[4].ar.id[2:0]"
Toggle xbar_slv_req[4].ar.addr [31:30] "logic xbar_slv_req[4].ar.addr[31:0]"
ANNOTATION: "SEP-XBAR-TARGET-TIED: each target port carries only beats from the initiators that Connectivity (sep_local_axi_xbar_pkg.sv:140-146) lets reach it, held in axi_mux spill registers that reset to 0 and load only on a valid handshake (vendor/pulp-platform/common_cells/upstream/src/spill_register_flushable.sv:45-47,78; LatencyMode CUT_ALL_PORTS at sep_local_axi_xbar_pkg.sv:126). axi_mux prepends the 3-bit initiator index above the 3-bit initiator ID (axi_id_prepend.sv:92-93). A listed bit is 0 in every address of the target's AddrMap rules (sep_local_axi_xbar.sv:96-206, extents from hw/sys/sep/regs/gen/sv/sep_addrmap_pkg.sv:17-21,234-235), or 0 in the index of every connected initiator, or a field every connected initiator ties to 0 (IFU el2_ifu_mem_ctl.sv:1074-1101; LSU qos/lock/AWATOP/AxUSER[11:4] el2_lsu_bus_buffer.sv:881-907 and sep_cpu.sv:497-507; debug el2_dbg.sv:738-774 and sep_cpu.sv:501-508; DMA axi_lite_to_axi.sv:39-67 and sep_dma_wrap.sv:283-284; ext id[2] axi_id_remap.sv:198-200). SEP_SOURCE_ID is 4'b1111 (sep_pkg.sv:489), so AxUSER[11:4] is 0 for the CPU masters. LSU prot/len/burst are not used as ties because a no_cpu TB force moves them. NOT waived: address bits that are 1 inside a rule (0->1 after the first access, 1->0 only on reset), and every field an integrator-driven initiator (ext) or a free CPU/DMA field can move."
Toggle cpu_tcm_req_o.ar.qos "logic cpu_tcm_req_o.ar.qos[3:0]"
Toggle xbar_mst_req[0].ar.qos "logic xbar_mst_req[0].ar.qos[3:0]"
Toggle cpu_tcm_req_o.ar.user "logic cpu_tcm_req_o.ar.user[11:0]"
Toggle xbar_mst_req[0].ar.user "logic xbar_mst_req[0].ar.user[11:0]"
Toggle cpu_tcm_req_o.ar.lock "logic cpu_tcm_req_o.ar.lock"
Toggle xbar_mst_req[0].ar.lock "logic xbar_mst_req[0].ar.lock"
Toggle cpu_tcm_req_o.ar.len "logic cpu_tcm_req_o.ar.len[7:0]"
Toggle xbar_mst_req[0].ar.len "logic xbar_mst_req[0].ar.len[7:0]"
Toggle cpu_tcm_req_o.ar.burst "logic cpu_tcm_req_o.ar.burst[1:0]"
Toggle xbar_mst_req[0].ar.burst "logic xbar_mst_req[0].ar.burst[1:0]"
Toggle cpu_tcm_req_o.ar.region "logic cpu_tcm_req_o.ar.region[3:0]"
Toggle xbar_mst_req[0].ar.region "logic xbar_mst_req[0].ar.region[3:0]"
Toggle cpu_tcm_req_o.ar.cache "logic cpu_tcm_req_o.ar.cache[3:0]"
Toggle xbar_mst_req[0].ar.cache "logic xbar_mst_req[0].ar.cache[3:0]"
Toggle cpu_tcm_req_o.ar.id [2:0] "logic cpu_tcm_req_o.ar.id[5:0]"
Toggle cpu_tcm_req_o.ar.id [5] "logic cpu_tcm_req_o.ar.id[5:0]"
Toggle xbar_mst_req[0].ar.id [2:0] "logic xbar_mst_req[0].ar.id[5:0]"
Toggle xbar_mst_req[0].ar.id [5] "logic xbar_mst_req[0].ar.id[5:0]"
Toggle cpu_tcm_req_o.ar.addr [29:19] "logic cpu_tcm_req_o.ar.addr[31:0]"
Toggle xbar_mst_req[0].ar.addr [29:19] "logic xbar_mst_req[0].ar.addr[31:0]"
Toggle cpu_tcm_req_o.aw.qos "logic cpu_tcm_req_o.aw.qos[3:0]"
Toggle xbar_mst_req[0].aw.qos "logic xbar_mst_req[0].aw.qos[3:0]"
Toggle cpu_tcm_req_o.aw.user "logic cpu_tcm_req_o.aw.user[11:0]"
Toggle xbar_mst_req[0].aw.user "logic xbar_mst_req[0].aw.user[11:0]"
Toggle cpu_tcm_req_o.aw.lock "logic cpu_tcm_req_o.aw.lock"
Toggle xbar_mst_req[0].aw.lock "logic xbar_mst_req[0].aw.lock"
Toggle cpu_tcm_req_o.aw.atop "logic cpu_tcm_req_o.aw.atop[5:0]"
Toggle xbar_mst_req[0].aw.atop "logic xbar_mst_req[0].aw.atop[5:0]"
Toggle cpu_tcm_req_o.aw.len "logic cpu_tcm_req_o.aw.len[7:0]"
Toggle xbar_mst_req[0].aw.len "logic xbar_mst_req[0].aw.len[7:0]"
Toggle cpu_tcm_req_o.aw.burst "logic cpu_tcm_req_o.aw.burst[1:0]"
Toggle xbar_mst_req[0].aw.burst "logic xbar_mst_req[0].aw.burst[1:0]"
Toggle cpu_tcm_req_o.aw.region "logic cpu_tcm_req_o.aw.region[3:0]"
Toggle xbar_mst_req[0].aw.region "logic xbar_mst_req[0].aw.region[3:0]"
Toggle cpu_tcm_req_o.aw.cache "logic cpu_tcm_req_o.aw.cache[3:0]"
Toggle xbar_mst_req[0].aw.cache "logic xbar_mst_req[0].aw.cache[3:0]"
Toggle cpu_tcm_req_o.aw.id [2:0] "logic cpu_tcm_req_o.aw.id[5:0]"
Toggle cpu_tcm_req_o.aw.id [5] "logic cpu_tcm_req_o.aw.id[5:0]"
Toggle xbar_mst_req[0].aw.id [2:0] "logic xbar_mst_req[0].aw.id[5:0]"
Toggle xbar_mst_req[0].aw.id [5] "logic xbar_mst_req[0].aw.id[5:0]"
Toggle cpu_tcm_req_o.aw.addr [29:19] "logic cpu_tcm_req_o.aw.addr[31:0]"
Toggle xbar_mst_req[0].aw.addr [29:19] "logic xbar_mst_req[0].aw.addr[31:0]"
Toggle cpu_tcm_req_o.w.user "logic cpu_tcm_req_o.w.user[11:0]"
Toggle xbar_mst_req[0].w.user "logic xbar_mst_req[0].w.user[11:0]"
Toggle sram_req_o.ar.addr [27:18] "logic sram_req_o.ar.addr[31:0]"
Toggle sram_req_o.ar.addr [31:29] "logic sram_req_o.ar.addr[31:0]"
Toggle xbar_mst_req[1].ar.addr [27:18] "logic xbar_mst_req[1].ar.addr[31:0]"
Toggle xbar_mst_req[1].ar.addr [31:29] "logic xbar_mst_req[1].ar.addr[31:0]"
Toggle sram_req_o.aw.addr [27:18] "logic sram_req_o.aw.addr[31:0]"
Toggle sram_req_o.aw.addr [31:29] "logic sram_req_o.aw.addr[31:0]"
Toggle xbar_mst_req[1].aw.addr [27:18] "logic xbar_mst_req[1].aw.addr[31:0]"
Toggle xbar_mst_req[1].aw.addr [31:29] "logic xbar_mst_req[1].aw.addr[31:0]"
Toggle dma_csr_req_o.ar.addr [22:9] "logic dma_csr_req_o.ar.addr[31:0]"
Toggle dma_csr_req_o.ar.addr [27:24] "logic dma_csr_req_o.ar.addr[31:0]"
Toggle dma_csr_req_o.ar.addr [31:29] "logic dma_csr_req_o.ar.addr[31:0]"
Toggle xbar_mst_req[2].ar.addr [22:9] "logic xbar_mst_req[2].ar.addr[31:0]"
Toggle xbar_mst_req[2].ar.addr [27:24] "logic xbar_mst_req[2].ar.addr[31:0]"
Toggle xbar_mst_req[2].ar.addr [31:29] "logic xbar_mst_req[2].ar.addr[31:0]"
Toggle dma_csr_req_o.aw.addr [22:9] "logic dma_csr_req_o.aw.addr[31:0]"
Toggle dma_csr_req_o.aw.addr [27:24] "logic dma_csr_req_o.aw.addr[31:0]"
Toggle dma_csr_req_o.aw.addr [31:29] "logic dma_csr_req_o.aw.addr[31:0]"
Toggle xbar_mst_req[2].aw.addr [22:9] "logic xbar_mst_req[2].aw.addr[31:0]"
Toggle xbar_mst_req[2].aw.addr [27:24] "logic xbar_mst_req[2].aw.addr[31:0]"
Toggle xbar_mst_req[2].aw.addr [31:29] "logic xbar_mst_req[2].aw.addr[31:0]"
Toggle sep_wdt_req_o.ar.addr [11:6] "logic sep_wdt_req_o.ar.addr[31:0]"
Toggle sep_wdt_req_o.ar.addr [22:13] "logic sep_wdt_req_o.ar.addr[31:0]"
Toggle sep_wdt_req_o.ar.addr [27:24] "logic sep_wdt_req_o.ar.addr[31:0]"
Toggle sep_wdt_req_o.ar.addr [31:29] "logic sep_wdt_req_o.ar.addr[31:0]"
Toggle xbar_mst_req[3].ar.addr [11:6] "logic xbar_mst_req[3].ar.addr[31:0]"
Toggle xbar_mst_req[3].ar.addr [22:13] "logic xbar_mst_req[3].ar.addr[31:0]"
Toggle xbar_mst_req[3].ar.addr [27:24] "logic xbar_mst_req[3].ar.addr[31:0]"
Toggle xbar_mst_req[3].ar.addr [31:29] "logic xbar_mst_req[3].ar.addr[31:0]"
Toggle sep_wdt_req_o.aw.addr [11:6] "logic sep_wdt_req_o.aw.addr[31:0]"
Toggle sep_wdt_req_o.aw.addr [22:13] "logic sep_wdt_req_o.aw.addr[31:0]"
Toggle sep_wdt_req_o.aw.addr [27:24] "logic sep_wdt_req_o.aw.addr[31:0]"
Toggle sep_wdt_req_o.aw.addr [31:29] "logic sep_wdt_req_o.aw.addr[31:0]"
Toggle xbar_mst_req[3].aw.addr [11:6] "logic xbar_mst_req[3].aw.addr[31:0]"
Toggle xbar_mst_req[3].aw.addr [22:13] "logic xbar_mst_req[3].aw.addr[31:0]"
Toggle xbar_mst_req[3].aw.addr [27:24] "logic xbar_mst_req[3].aw.addr[31:0]"
Toggle xbar_mst_req[3].aw.addr [31:29] "logic xbar_mst_req[3].aw.addr[31:0]"
Toggle sep_reset_ctrl_req_o.ar.user [11:4] "logic sep_reset_ctrl_req_o.ar.user[11:0]"
Toggle xbar_mst_req[4].ar.user [11:4] "logic xbar_mst_req[4].ar.user[11:0]"
Toggle sep_reset_ctrl_req_o.ar.qos "logic sep_reset_ctrl_req_o.ar.qos[3:0]"
Toggle xbar_mst_req[4].ar.qos "logic xbar_mst_req[4].ar.qos[3:0]"
Toggle sep_reset_ctrl_req_o.ar.lock "logic sep_reset_ctrl_req_o.ar.lock"
Toggle xbar_mst_req[4].ar.lock "logic xbar_mst_req[4].ar.lock"
Toggle sep_reset_ctrl_req_o.ar.id [5] "logic sep_reset_ctrl_req_o.ar.id[5:0]"
Toggle xbar_mst_req[4].ar.id [5] "logic xbar_mst_req[4].ar.id[5:0]"
Toggle sep_reset_ctrl_req_o.ar.addr [11:3] "logic sep_reset_ctrl_req_o.ar.addr[31:0]"
Toggle sep_reset_ctrl_req_o.ar.addr [22:14] "logic sep_reset_ctrl_req_o.ar.addr[31:0]"
Toggle sep_reset_ctrl_req_o.ar.addr [27:24] "logic sep_reset_ctrl_req_o.ar.addr[31:0]"
Toggle sep_reset_ctrl_req_o.ar.addr [31:29] "logic sep_reset_ctrl_req_o.ar.addr[31:0]"
Toggle xbar_mst_req[4].ar.addr [11:3] "logic xbar_mst_req[4].ar.addr[31:0]"
Toggle xbar_mst_req[4].ar.addr [22:14] "logic xbar_mst_req[4].ar.addr[31:0]"
Toggle xbar_mst_req[4].ar.addr [27:24] "logic xbar_mst_req[4].ar.addr[31:0]"
Toggle xbar_mst_req[4].ar.addr [31:29] "logic xbar_mst_req[4].ar.addr[31:0]"
Toggle sep_reset_ctrl_req_o.aw.user [11:4] "logic sep_reset_ctrl_req_o.aw.user[11:0]"
Toggle xbar_mst_req[4].aw.user [11:4] "logic xbar_mst_req[4].aw.user[11:0]"
Toggle sep_reset_ctrl_req_o.aw.qos "logic sep_reset_ctrl_req_o.aw.qos[3:0]"
Toggle xbar_mst_req[4].aw.qos "logic xbar_mst_req[4].aw.qos[3:0]"
Toggle sep_reset_ctrl_req_o.aw.lock "logic sep_reset_ctrl_req_o.aw.lock"
Toggle xbar_mst_req[4].aw.lock "logic xbar_mst_req[4].aw.lock"
Toggle sep_reset_ctrl_req_o.aw.atop "logic sep_reset_ctrl_req_o.aw.atop[5:0]"
Toggle xbar_mst_req[4].aw.atop "logic xbar_mst_req[4].aw.atop[5:0]"
Toggle sep_reset_ctrl_req_o.aw.id [5] "logic sep_reset_ctrl_req_o.aw.id[5:0]"
Toggle xbar_mst_req[4].aw.id [5] "logic xbar_mst_req[4].aw.id[5:0]"
Toggle sep_reset_ctrl_req_o.aw.addr [11:3] "logic sep_reset_ctrl_req_o.aw.addr[31:0]"
Toggle sep_reset_ctrl_req_o.aw.addr [22:14] "logic sep_reset_ctrl_req_o.aw.addr[31:0]"
Toggle sep_reset_ctrl_req_o.aw.addr [27:24] "logic sep_reset_ctrl_req_o.aw.addr[31:0]"
Toggle sep_reset_ctrl_req_o.aw.addr [31:29] "logic sep_reset_ctrl_req_o.aw.addr[31:0]"
Toggle xbar_mst_req[4].aw.addr [11:3] "logic xbar_mst_req[4].aw.addr[31:0]"
Toggle xbar_mst_req[4].aw.addr [22:14] "logic xbar_mst_req[4].aw.addr[31:0]"
Toggle xbar_mst_req[4].aw.addr [27:24] "logic xbar_mst_req[4].aw.addr[31:0]"
Toggle xbar_mst_req[4].aw.addr [31:29] "logic xbar_mst_req[4].aw.addr[31:0]"
Toggle sep_reset_ctrl_req_o.w.user [11:4] "logic sep_reset_ctrl_req_o.w.user[11:0]"
Toggle xbar_mst_req[4].w.user [11:4] "logic xbar_mst_req[4].w.user[11:0]"
Toggle sep_crypto_req_o.ar.addr [19] "logic sep_crypto_req_o.ar.addr[31:0]"
Toggle sep_crypto_req_o.ar.addr [22:21] "logic sep_crypto_req_o.ar.addr[31:0]"
Toggle sep_crypto_req_o.ar.addr [27:24] "logic sep_crypto_req_o.ar.addr[31:0]"
Toggle sep_crypto_req_o.ar.addr [31:29] "logic sep_crypto_req_o.ar.addr[31:0]"
Toggle xbar_mst_req[5].ar.addr [19] "logic xbar_mst_req[5].ar.addr[31:0]"
Toggle xbar_mst_req[5].ar.addr [22:21] "logic xbar_mst_req[5].ar.addr[31:0]"
Toggle xbar_mst_req[5].ar.addr [27:24] "logic xbar_mst_req[5].ar.addr[31:0]"
Toggle xbar_mst_req[5].ar.addr [31:29] "logic xbar_mst_req[5].ar.addr[31:0]"
Toggle sep_crypto_req_o.aw.addr [19] "logic sep_crypto_req_o.aw.addr[31:0]"
Toggle sep_crypto_req_o.aw.addr [22:21] "logic sep_crypto_req_o.aw.addr[31:0]"
Toggle sep_crypto_req_o.aw.addr [27:24] "logic sep_crypto_req_o.aw.addr[31:0]"
Toggle sep_crypto_req_o.aw.addr [31:29] "logic sep_crypto_req_o.aw.addr[31:0]"
Toggle xbar_mst_req[5].aw.addr [19] "logic xbar_mst_req[5].aw.addr[31:0]"
Toggle xbar_mst_req[5].aw.addr [22:21] "logic xbar_mst_req[5].aw.addr[31:0]"
Toggle xbar_mst_req[5].aw.addr [27:24] "logic xbar_mst_req[5].aw.addr[31:0]"
Toggle xbar_mst_req[5].aw.addr [31:29] "logic xbar_mst_req[5].aw.addr[31:0]"
Toggle sep_system_peripherals_req_o.ar.user [11:4] "logic sep_system_peripherals_req_o.ar.user[11:0]"
Toggle xbar_mst_req[6].ar.user [11:4] "logic xbar_mst_req[6].ar.user[11:0]"
Toggle sep_system_peripherals_req_o.ar.qos "logic sep_system_peripherals_req_o.ar.qos[3:0]"
Toggle xbar_mst_req[6].ar.qos "logic xbar_mst_req[6].ar.qos[3:0]"
Toggle sep_system_peripherals_req_o.ar.lock "logic sep_system_peripherals_req_o.ar.lock"
Toggle xbar_mst_req[6].ar.lock "logic xbar_mst_req[6].ar.lock"
Toggle sep_system_peripherals_req_o.ar.id [5] "logic sep_system_peripherals_req_o.ar.id[5:0]"
Toggle xbar_mst_req[6].ar.id [5] "logic xbar_mst_req[6].ar.id[5:0]"
Toggle sep_system_peripherals_req_o.aw.user [11:4] "logic sep_system_peripherals_req_o.aw.user[11:0]"
Toggle xbar_mst_req[6].aw.user [11:4] "logic xbar_mst_req[6].aw.user[11:0]"
Toggle sep_system_peripherals_req_o.aw.qos "logic sep_system_peripherals_req_o.aw.qos[3:0]"
Toggle xbar_mst_req[6].aw.qos "logic xbar_mst_req[6].aw.qos[3:0]"
Toggle sep_system_peripherals_req_o.aw.lock "logic sep_system_peripherals_req_o.aw.lock"
Toggle xbar_mst_req[6].aw.lock "logic xbar_mst_req[6].aw.lock"
Toggle sep_system_peripherals_req_o.aw.atop "logic sep_system_peripherals_req_o.aw.atop[5:0]"
Toggle xbar_mst_req[6].aw.atop "logic xbar_mst_req[6].aw.atop[5:0]"
Toggle sep_system_peripherals_req_o.aw.id [5] "logic sep_system_peripherals_req_o.aw.id[5:0]"
Toggle xbar_mst_req[6].aw.id [5] "logic xbar_mst_req[6].aw.id[5:0]"
Toggle sep_system_peripherals_req_o.w.user [11:4] "logic sep_system_peripherals_req_o.w.user[11:0]"
Toggle xbar_mst_req[6].w.user [11:4] "logic xbar_mst_req[6].w.user[11:0]"
Toggle sep_io_req_o.ar.addr [19:6] "logic sep_io_req_o.ar.addr[31:0]"
Toggle sep_io_req_o.ar.addr [22] "logic sep_io_req_o.ar.addr[31:0]"
Toggle sep_io_req_o.ar.addr [27:24] "logic sep_io_req_o.ar.addr[31:0]"
Toggle sep_io_req_o.ar.addr [31:29] "logic sep_io_req_o.ar.addr[31:0]"
Toggle xbar_mst_req[7].ar.addr [19:6] "logic xbar_mst_req[7].ar.addr[31:0]"
Toggle xbar_mst_req[7].ar.addr [22] "logic xbar_mst_req[7].ar.addr[31:0]"
Toggle xbar_mst_req[7].ar.addr [27:24] "logic xbar_mst_req[7].ar.addr[31:0]"
Toggle xbar_mst_req[7].ar.addr [31:29] "logic xbar_mst_req[7].ar.addr[31:0]"
Toggle sep_io_req_o.aw.addr [19:6] "logic sep_io_req_o.aw.addr[31:0]"
Toggle sep_io_req_o.aw.addr [22] "logic sep_io_req_o.aw.addr[31:0]"
Toggle sep_io_req_o.aw.addr [27:24] "logic sep_io_req_o.aw.addr[31:0]"
Toggle sep_io_req_o.aw.addr [31:29] "logic sep_io_req_o.aw.addr[31:0]"
Toggle xbar_mst_req[7].aw.addr [19:6] "logic xbar_mst_req[7].aw.addr[31:0]"
Toggle xbar_mst_req[7].aw.addr [22] "logic xbar_mst_req[7].aw.addr[31:0]"
Toggle xbar_mst_req[7].aw.addr [27:24] "logic xbar_mst_req[7].aw.addr[31:0]"
Toggle xbar_mst_req[7].aw.addr [31:29] "logic xbar_mst_req[7].aw.addr[31:0]"
Toggle entropy_fifo_req_o.ar.addr [17] "logic entropy_fifo_req_o.ar.addr[31:0]"
Toggle entropy_fifo_req_o.ar.addr [19] "logic entropy_fifo_req_o.ar.addr[31:0]"
Toggle entropy_fifo_req_o.ar.addr [22:21] "logic entropy_fifo_req_o.ar.addr[31:0]"
Toggle entropy_fifo_req_o.ar.addr [27:24] "logic entropy_fifo_req_o.ar.addr[31:0]"
Toggle entropy_fifo_req_o.ar.addr [31:29] "logic entropy_fifo_req_o.ar.addr[31:0]"
Toggle xbar_mst_req[8].ar.addr [17] "logic xbar_mst_req[8].ar.addr[31:0]"
Toggle xbar_mst_req[8].ar.addr [19] "logic xbar_mst_req[8].ar.addr[31:0]"
Toggle xbar_mst_req[8].ar.addr [22:21] "logic xbar_mst_req[8].ar.addr[31:0]"
Toggle xbar_mst_req[8].ar.addr [27:24] "logic xbar_mst_req[8].ar.addr[31:0]"
Toggle xbar_mst_req[8].ar.addr [31:29] "logic xbar_mst_req[8].ar.addr[31:0]"
Toggle entropy_fifo_req_o.aw.addr [17] "logic entropy_fifo_req_o.aw.addr[31:0]"
Toggle entropy_fifo_req_o.aw.addr [19] "logic entropy_fifo_req_o.aw.addr[31:0]"
Toggle entropy_fifo_req_o.aw.addr [22:21] "logic entropy_fifo_req_o.aw.addr[31:0]"
Toggle entropy_fifo_req_o.aw.addr [27:24] "logic entropy_fifo_req_o.aw.addr[31:0]"
Toggle entropy_fifo_req_o.aw.addr [31:29] "logic entropy_fifo_req_o.aw.addr[31:0]"
Toggle xbar_mst_req[8].aw.addr [17] "logic xbar_mst_req[8].aw.addr[31:0]"
Toggle xbar_mst_req[8].aw.addr [19] "logic xbar_mst_req[8].aw.addr[31:0]"
Toggle xbar_mst_req[8].aw.addr [22:21] "logic xbar_mst_req[8].aw.addr[31:0]"
Toggle xbar_mst_req[8].aw.addr [27:24] "logic xbar_mst_req[8].aw.addr[31:0]"
Toggle xbar_mst_req[8].aw.addr [31:29] "logic xbar_mst_req[8].aw.addr[31:0]"
Toggle sep_external_req_o.ar.addr [31:30] "logic sep_external_req_o.ar.addr[31:0]"
Toggle xbar_mst_req[9].ar.addr [31:30] "logic xbar_mst_req[9].ar.addr[31:0]"
Toggle sep_external_req_o.aw.addr [31:30] "logic sep_external_req_o.aw.addr[31:0]"
Toggle xbar_mst_req[9].aw.addr [31:30] "logic xbar_mst_req[9].aw.addr[31:0]"
ANNOTATION: "SEP-XBAR-IFU-NO-WRITE: the IFU never writes: aw_valid and w_valid are tied 0 (el2_ifu_mem_ctl.sv:1085-1101, waived on the port by sep_master_tie_exclusions.el). The IFU port reaches only the sram target (sep_local_axi_xbar_pkg.sv:141), so no AW is ever accepted on it and no B can be routed to it; the B spill register in the slave-port demux resets to 0 and loads only on b_valid (spill_register_flushable.sv:45-47,78; the IFU-port demux B spill exists because LatencyMode is CUT_ALL_PORTS at sep_local_axi_xbar_pkg.sv:126). NOT waived: aw_ready and w_ready, which the demux drives from its own state."
Toggle ifu_sram_resp_o.b_valid "logic ifu_sram_resp_o.b_valid"
Toggle ifu_sram_resp_o.b.id "logic ifu_sram_resp_o.b.id[2:0]"
Toggle ifu_sram_resp_o.b.resp "logic ifu_sram_resp_o.b.resp[1:0]"
Toggle ifu_sram_resp_o.b.user "logic ifu_sram_resp_o.b.user[11:0]"
Toggle xbar_slv_resp[0].b_valid "logic xbar_slv_resp[0].b_valid"
Toggle xbar_slv_resp[0].b.id "logic xbar_slv_resp[0].b.id[2:0]"
Toggle xbar_slv_resp[0].b.resp "logic xbar_slv_resp[0].b.resp[1:0]"
Toggle xbar_slv_resp[0].b.user "logic xbar_slv_resp[0].b.user[11:0]"
ANNOTATION: "SEP-XBAR-TCM-RESP-USER-TIED: the cpu_tcm target is the VeeR DMA slave port of u_sep_cpu (hw/sys/sep/rtl/sep.sv:437,695), and sep_cpu.sv:511-512 drive its B and R USER to SEP_SOURCE_ID, 4'b1111 zero-extended to 12 bits (sep_pkg.sv:489), from time 0. NOT waived: response user on every other target and on the initiator side, which integrator-driven targets (sep_system_peripherals, sep_external) can move."
Toggle cpu_tcm_resp_i.r.user "logic cpu_tcm_resp_i.r.user[11:0]"
Toggle cpu_tcm_resp_i.b.user "logic cpu_tcm_resp_i.b.user[11:0]"
Toggle xbar_mst_resp[0].r.user "logic xbar_mst_resp[0].r.user[11:0]"
Toggle xbar_mst_resp[0].b.user "logic xbar_mst_resp[0].b.user[11:0]"

CHECKSUM: "366726899 3902493086"
INSTANCE: sep_uvm_top.u_dut.u_sep.u_sep_local_axi_xbar_wrapper
ANNOTATION: "SEP-XBAR-EXT-ID-ADDR: the ext initiator is the sep_system_peripherals forward path only (sep.sv:432). Its ID passes axi_id_remap with 4 table entries, which drives mst aw/ar id as {1'b0, 2-bit index} (vendor/pulp-platform/axi/upstream/src/axi_id_remap.sv:198-200; MAX_INFLIGHT_IDS=4 at hw/sys/sep/rtl/sep_system_peripherals/rtl/sep_system_peripherals.sv:642), so id[2] is constant 0. Its address comes from peripheral-xbar port 0, whose rules end at 0x4000_0000 (hw/sys/sep/rtl/crossbars/sep_system_peripherals_xbar.sv:63-67, sep_system_peripherals_xbar_pkg.sv:186-194), truncated to 32 bits, so addr[31:30] are constant 0. NOT waived: id[1:0], addr[29:0] and every other field, which the SMN inbound port drives."
Toggle ext_axi_req_i.aw.id [2] "logic ext_axi_req_i.aw.id[2:0]"
Toggle ext_axi_req_i.aw.addr [31:30] "logic ext_axi_req_i.aw.addr[31:0]"
Toggle ext_axi_req_i.ar.id [2] "logic ext_axi_req_i.ar.id[2:0]"
Toggle ext_axi_req_i.ar.addr [31:30] "logic ext_axi_req_i.ar.addr[31:0]"
Toggle ext_req.aw.id [2] "logic ext_req.aw.id[2:0]"
Toggle ext_req.aw.addr [31:30] "logic ext_req.aw.addr[31:0]"
Toggle ext_req.ar.id [2] "logic ext_req.ar.id[2:0]"
Toggle ext_req.ar.addr [31:30] "logic ext_req.ar.addr[31:0]"
ANNOTATION: "SEP-XBAR-TARGET-TIED: each target port carries only beats from the initiators that Connectivity (sep_local_axi_xbar_pkg.sv:140-146) lets reach it, held in axi_mux spill registers that reset to 0 and load only on a valid handshake (vendor/pulp-platform/common_cells/upstream/src/spill_register_flushable.sv:45-47,78; LatencyMode CUT_ALL_PORTS at sep_local_axi_xbar_pkg.sv:126). axi_mux prepends the 3-bit initiator index above the 3-bit initiator ID (axi_id_prepend.sv:92-93). A listed bit is 0 in every address of the target's AddrMap rules (sep_local_axi_xbar.sv:96-206, extents from hw/sys/sep/regs/gen/sv/sep_addrmap_pkg.sv:17-21,234-235), or 0 in the index of every connected initiator, or a field every connected initiator ties to 0 (IFU el2_ifu_mem_ctl.sv:1074-1101; LSU qos/lock/AWATOP/AxUSER[11:4] el2_lsu_bus_buffer.sv:881-907 and sep_cpu.sv:497-507; debug el2_dbg.sv:738-774 and sep_cpu.sv:501-508; DMA axi_lite_to_axi.sv:39-67 and sep_dma_wrap.sv:283-284; ext id[2] axi_id_remap.sv:198-200). SEP_SOURCE_ID is 4'b1111 (sep_pkg.sv:489), so AxUSER[11:4] is 0 for the CPU masters. LSU prot/len/burst are not used as ties because a no_cpu TB force moves them. NOT waived: address bits that are 1 inside a rule (0->1 after the first access, 1->0 only on reset), and every field an integrator-driven initiator (ext) or a free CPU/DMA field can move."
Toggle cpu_tcm_axi_req_o.ar.qos "logic cpu_tcm_axi_req_o.ar.qos[3:0]"
Toggle cpu_tcm_req.ar.qos "logic cpu_tcm_req.ar.qos[3:0]"
Toggle cpu_tcm_axi_req_o.ar.user "logic cpu_tcm_axi_req_o.ar.user[11:0]"
Toggle cpu_tcm_req.ar.user "logic cpu_tcm_req.ar.user[11:0]"
Toggle cpu_tcm_axi_req_o.ar.lock "logic cpu_tcm_axi_req_o.ar.lock"
Toggle cpu_tcm_req.ar.lock "logic cpu_tcm_req.ar.lock"
Toggle cpu_tcm_axi_req_o.ar.len "logic cpu_tcm_axi_req_o.ar.len[7:0]"
Toggle cpu_tcm_req.ar.len "logic cpu_tcm_req.ar.len[7:0]"
Toggle cpu_tcm_axi_req_o.ar.burst "logic cpu_tcm_axi_req_o.ar.burst[1:0]"
Toggle cpu_tcm_req.ar.burst "logic cpu_tcm_req.ar.burst[1:0]"
Toggle cpu_tcm_axi_req_o.ar.region "logic cpu_tcm_axi_req_o.ar.region[3:0]"
Toggle cpu_tcm_req.ar.region "logic cpu_tcm_req.ar.region[3:0]"
Toggle cpu_tcm_axi_req_o.ar.cache "logic cpu_tcm_axi_req_o.ar.cache[3:0]"
Toggle cpu_tcm_req.ar.cache "logic cpu_tcm_req.ar.cache[3:0]"
Toggle cpu_tcm_axi_req_o.ar.id [2:0] "logic cpu_tcm_axi_req_o.ar.id[5:0]"
Toggle cpu_tcm_axi_req_o.ar.id [5] "logic cpu_tcm_axi_req_o.ar.id[5:0]"
Toggle cpu_tcm_req.ar.id [2:0] "logic cpu_tcm_req.ar.id[5:0]"
Toggle cpu_tcm_req.ar.id [5] "logic cpu_tcm_req.ar.id[5:0]"
Toggle cpu_tcm_axi_req_o.ar.addr [29:19] "logic cpu_tcm_axi_req_o.ar.addr[31:0]"
Toggle cpu_tcm_req.ar.addr [29:19] "logic cpu_tcm_req.ar.addr[31:0]"
Toggle cpu_tcm_axi_req_o.aw.qos "logic cpu_tcm_axi_req_o.aw.qos[3:0]"
Toggle cpu_tcm_req.aw.qos "logic cpu_tcm_req.aw.qos[3:0]"
Toggle cpu_tcm_axi_req_o.aw.user "logic cpu_tcm_axi_req_o.aw.user[11:0]"
Toggle cpu_tcm_req.aw.user "logic cpu_tcm_req.aw.user[11:0]"
Toggle cpu_tcm_axi_req_o.aw.lock "logic cpu_tcm_axi_req_o.aw.lock"
Toggle cpu_tcm_req.aw.lock "logic cpu_tcm_req.aw.lock"
Toggle cpu_tcm_axi_req_o.aw.atop "logic cpu_tcm_axi_req_o.aw.atop[5:0]"
Toggle cpu_tcm_req.aw.atop "logic cpu_tcm_req.aw.atop[5:0]"
Toggle cpu_tcm_axi_req_o.aw.len "logic cpu_tcm_axi_req_o.aw.len[7:0]"
Toggle cpu_tcm_req.aw.len "logic cpu_tcm_req.aw.len[7:0]"
Toggle cpu_tcm_axi_req_o.aw.burst "logic cpu_tcm_axi_req_o.aw.burst[1:0]"
Toggle cpu_tcm_req.aw.burst "logic cpu_tcm_req.aw.burst[1:0]"
Toggle cpu_tcm_axi_req_o.aw.region "logic cpu_tcm_axi_req_o.aw.region[3:0]"
Toggle cpu_tcm_req.aw.region "logic cpu_tcm_req.aw.region[3:0]"
Toggle cpu_tcm_axi_req_o.aw.cache "logic cpu_tcm_axi_req_o.aw.cache[3:0]"
Toggle cpu_tcm_req.aw.cache "logic cpu_tcm_req.aw.cache[3:0]"
Toggle cpu_tcm_axi_req_o.aw.id [2:0] "logic cpu_tcm_axi_req_o.aw.id[5:0]"
Toggle cpu_tcm_axi_req_o.aw.id [5] "logic cpu_tcm_axi_req_o.aw.id[5:0]"
Toggle cpu_tcm_req.aw.id [2:0] "logic cpu_tcm_req.aw.id[5:0]"
Toggle cpu_tcm_req.aw.id [5] "logic cpu_tcm_req.aw.id[5:0]"
Toggle cpu_tcm_axi_req_o.aw.addr [29:19] "logic cpu_tcm_axi_req_o.aw.addr[31:0]"
Toggle cpu_tcm_req.aw.addr [29:19] "logic cpu_tcm_req.aw.addr[31:0]"
Toggle cpu_tcm_axi_req_o.w.user "logic cpu_tcm_axi_req_o.w.user[11:0]"
Toggle cpu_tcm_req.w.user "logic cpu_tcm_req.w.user[11:0]"
Toggle sram_axi_req_o.ar.addr [27:18] "logic sram_axi_req_o.ar.addr[31:0]"
Toggle sram_axi_req_o.ar.addr [31:29] "logic sram_axi_req_o.ar.addr[31:0]"
Toggle sram_req.ar.addr [27:18] "logic sram_req.ar.addr[31:0]"
Toggle sram_req.ar.addr [31:29] "logic sram_req.ar.addr[31:0]"
Toggle sram_axi_req_o.aw.addr [27:18] "logic sram_axi_req_o.aw.addr[31:0]"
Toggle sram_axi_req_o.aw.addr [31:29] "logic sram_axi_req_o.aw.addr[31:0]"
Toggle sram_req.aw.addr [27:18] "logic sram_req.aw.addr[31:0]"
Toggle sram_req.aw.addr [31:29] "logic sram_req.aw.addr[31:0]"
Toggle dma_csr_axi_req_o.ar.addr [22:9] "logic dma_csr_axi_req_o.ar.addr[31:0]"
Toggle dma_csr_axi_req_o.ar.addr [27:24] "logic dma_csr_axi_req_o.ar.addr[31:0]"
Toggle dma_csr_axi_req_o.ar.addr [31:29] "logic dma_csr_axi_req_o.ar.addr[31:0]"
Toggle dma_csr_req.ar.addr [22:9] "logic dma_csr_req.ar.addr[31:0]"
Toggle dma_csr_req.ar.addr [27:24] "logic dma_csr_req.ar.addr[31:0]"
Toggle dma_csr_req.ar.addr [31:29] "logic dma_csr_req.ar.addr[31:0]"
Toggle dma_csr_axi_req_o.aw.addr [22:9] "logic dma_csr_axi_req_o.aw.addr[31:0]"
Toggle dma_csr_axi_req_o.aw.addr [27:24] "logic dma_csr_axi_req_o.aw.addr[31:0]"
Toggle dma_csr_axi_req_o.aw.addr [31:29] "logic dma_csr_axi_req_o.aw.addr[31:0]"
Toggle dma_csr_req.aw.addr [22:9] "logic dma_csr_req.aw.addr[31:0]"
Toggle dma_csr_req.aw.addr [27:24] "logic dma_csr_req.aw.addr[31:0]"
Toggle dma_csr_req.aw.addr [31:29] "logic dma_csr_req.aw.addr[31:0]"
Toggle sep_wdt_axi_req_o.ar.addr [11:6] "logic sep_wdt_axi_req_o.ar.addr[31:0]"
Toggle sep_wdt_axi_req_o.ar.addr [22:13] "logic sep_wdt_axi_req_o.ar.addr[31:0]"
Toggle sep_wdt_axi_req_o.ar.addr [27:24] "logic sep_wdt_axi_req_o.ar.addr[31:0]"
Toggle sep_wdt_axi_req_o.ar.addr [31:29] "logic sep_wdt_axi_req_o.ar.addr[31:0]"
Toggle sep_wdt_req.ar.addr [11:6] "logic sep_wdt_req.ar.addr[31:0]"
Toggle sep_wdt_req.ar.addr [22:13] "logic sep_wdt_req.ar.addr[31:0]"
Toggle sep_wdt_req.ar.addr [27:24] "logic sep_wdt_req.ar.addr[31:0]"
Toggle sep_wdt_req.ar.addr [31:29] "logic sep_wdt_req.ar.addr[31:0]"
Toggle sep_wdt_axi_req_o.aw.addr [11:6] "logic sep_wdt_axi_req_o.aw.addr[31:0]"
Toggle sep_wdt_axi_req_o.aw.addr [22:13] "logic sep_wdt_axi_req_o.aw.addr[31:0]"
Toggle sep_wdt_axi_req_o.aw.addr [27:24] "logic sep_wdt_axi_req_o.aw.addr[31:0]"
Toggle sep_wdt_axi_req_o.aw.addr [31:29] "logic sep_wdt_axi_req_o.aw.addr[31:0]"
Toggle sep_wdt_req.aw.addr [11:6] "logic sep_wdt_req.aw.addr[31:0]"
Toggle sep_wdt_req.aw.addr [22:13] "logic sep_wdt_req.aw.addr[31:0]"
Toggle sep_wdt_req.aw.addr [27:24] "logic sep_wdt_req.aw.addr[31:0]"
Toggle sep_wdt_req.aw.addr [31:29] "logic sep_wdt_req.aw.addr[31:0]"
Toggle sep_reset_ctrl_axi_req_o.ar.user [11:4] "logic sep_reset_ctrl_axi_req_o.ar.user[11:0]"
Toggle sep_reset_ctrl_req.ar.user [11:4] "logic sep_reset_ctrl_req.ar.user[11:0]"
Toggle sep_reset_ctrl_axi_req_o.ar.qos "logic sep_reset_ctrl_axi_req_o.ar.qos[3:0]"
Toggle sep_reset_ctrl_req.ar.qos "logic sep_reset_ctrl_req.ar.qos[3:0]"
Toggle sep_reset_ctrl_axi_req_o.ar.lock "logic sep_reset_ctrl_axi_req_o.ar.lock"
Toggle sep_reset_ctrl_req.ar.lock "logic sep_reset_ctrl_req.ar.lock"
Toggle sep_reset_ctrl_axi_req_o.ar.id [5] "logic sep_reset_ctrl_axi_req_o.ar.id[5:0]"
Toggle sep_reset_ctrl_req.ar.id [5] "logic sep_reset_ctrl_req.ar.id[5:0]"
Toggle sep_reset_ctrl_axi_req_o.ar.addr [11:3] "logic sep_reset_ctrl_axi_req_o.ar.addr[31:0]"
Toggle sep_reset_ctrl_axi_req_o.ar.addr [22:14] "logic sep_reset_ctrl_axi_req_o.ar.addr[31:0]"
Toggle sep_reset_ctrl_axi_req_o.ar.addr [27:24] "logic sep_reset_ctrl_axi_req_o.ar.addr[31:0]"
Toggle sep_reset_ctrl_axi_req_o.ar.addr [31:29] "logic sep_reset_ctrl_axi_req_o.ar.addr[31:0]"
Toggle sep_reset_ctrl_req.ar.addr [11:3] "logic sep_reset_ctrl_req.ar.addr[31:0]"
Toggle sep_reset_ctrl_req.ar.addr [22:14] "logic sep_reset_ctrl_req.ar.addr[31:0]"
Toggle sep_reset_ctrl_req.ar.addr [27:24] "logic sep_reset_ctrl_req.ar.addr[31:0]"
Toggle sep_reset_ctrl_req.ar.addr [31:29] "logic sep_reset_ctrl_req.ar.addr[31:0]"
Toggle sep_reset_ctrl_axi_req_o.aw.user [11:4] "logic sep_reset_ctrl_axi_req_o.aw.user[11:0]"
Toggle sep_reset_ctrl_req.aw.user [11:4] "logic sep_reset_ctrl_req.aw.user[11:0]"
Toggle sep_reset_ctrl_axi_req_o.aw.qos "logic sep_reset_ctrl_axi_req_o.aw.qos[3:0]"
Toggle sep_reset_ctrl_req.aw.qos "logic sep_reset_ctrl_req.aw.qos[3:0]"
Toggle sep_reset_ctrl_axi_req_o.aw.lock "logic sep_reset_ctrl_axi_req_o.aw.lock"
Toggle sep_reset_ctrl_req.aw.lock "logic sep_reset_ctrl_req.aw.lock"
Toggle sep_reset_ctrl_axi_req_o.aw.atop "logic sep_reset_ctrl_axi_req_o.aw.atop[5:0]"
Toggle sep_reset_ctrl_req.aw.atop "logic sep_reset_ctrl_req.aw.atop[5:0]"
Toggle sep_reset_ctrl_axi_req_o.aw.id [5] "logic sep_reset_ctrl_axi_req_o.aw.id[5:0]"
Toggle sep_reset_ctrl_req.aw.id [5] "logic sep_reset_ctrl_req.aw.id[5:0]"
Toggle sep_reset_ctrl_axi_req_o.aw.addr [11:3] "logic sep_reset_ctrl_axi_req_o.aw.addr[31:0]"
Toggle sep_reset_ctrl_axi_req_o.aw.addr [22:14] "logic sep_reset_ctrl_axi_req_o.aw.addr[31:0]"
Toggle sep_reset_ctrl_axi_req_o.aw.addr [27:24] "logic sep_reset_ctrl_axi_req_o.aw.addr[31:0]"
Toggle sep_reset_ctrl_axi_req_o.aw.addr [31:29] "logic sep_reset_ctrl_axi_req_o.aw.addr[31:0]"
Toggle sep_reset_ctrl_req.aw.addr [11:3] "logic sep_reset_ctrl_req.aw.addr[31:0]"
Toggle sep_reset_ctrl_req.aw.addr [22:14] "logic sep_reset_ctrl_req.aw.addr[31:0]"
Toggle sep_reset_ctrl_req.aw.addr [27:24] "logic sep_reset_ctrl_req.aw.addr[31:0]"
Toggle sep_reset_ctrl_req.aw.addr [31:29] "logic sep_reset_ctrl_req.aw.addr[31:0]"
Toggle sep_reset_ctrl_axi_req_o.w.user [11:4] "logic sep_reset_ctrl_axi_req_o.w.user[11:0]"
Toggle sep_reset_ctrl_req.w.user [11:4] "logic sep_reset_ctrl_req.w.user[11:0]"
Toggle sep_crypto_axi_req_o.ar.addr [19] "logic sep_crypto_axi_req_o.ar.addr[31:0]"
Toggle sep_crypto_axi_req_o.ar.addr [22:21] "logic sep_crypto_axi_req_o.ar.addr[31:0]"
Toggle sep_crypto_axi_req_o.ar.addr [27:24] "logic sep_crypto_axi_req_o.ar.addr[31:0]"
Toggle sep_crypto_axi_req_o.ar.addr [31:29] "logic sep_crypto_axi_req_o.ar.addr[31:0]"
Toggle sep_crypto_req.ar.addr [19] "logic sep_crypto_req.ar.addr[31:0]"
Toggle sep_crypto_req.ar.addr [22:21] "logic sep_crypto_req.ar.addr[31:0]"
Toggle sep_crypto_req.ar.addr [27:24] "logic sep_crypto_req.ar.addr[31:0]"
Toggle sep_crypto_req.ar.addr [31:29] "logic sep_crypto_req.ar.addr[31:0]"
Toggle sep_crypto_axi_req_o.aw.addr [19] "logic sep_crypto_axi_req_o.aw.addr[31:0]"
Toggle sep_crypto_axi_req_o.aw.addr [22:21] "logic sep_crypto_axi_req_o.aw.addr[31:0]"
Toggle sep_crypto_axi_req_o.aw.addr [27:24] "logic sep_crypto_axi_req_o.aw.addr[31:0]"
Toggle sep_crypto_axi_req_o.aw.addr [31:29] "logic sep_crypto_axi_req_o.aw.addr[31:0]"
Toggle sep_crypto_req.aw.addr [19] "logic sep_crypto_req.aw.addr[31:0]"
Toggle sep_crypto_req.aw.addr [22:21] "logic sep_crypto_req.aw.addr[31:0]"
Toggle sep_crypto_req.aw.addr [27:24] "logic sep_crypto_req.aw.addr[31:0]"
Toggle sep_crypto_req.aw.addr [31:29] "logic sep_crypto_req.aw.addr[31:0]"
Toggle sep_system_peripherals_axi_req_o.ar.user [11:4] "logic sep_system_peripherals_axi_req_o.ar.user[11:0]"
Toggle sep_system_peripherals_req.ar.user [11:4] "logic sep_system_peripherals_req.ar.user[11:0]"
Toggle sep_system_peripherals_axi_req_o.ar.qos "logic sep_system_peripherals_axi_req_o.ar.qos[3:0]"
Toggle sep_system_peripherals_req.ar.qos "logic sep_system_peripherals_req.ar.qos[3:0]"
Toggle sep_system_peripherals_axi_req_o.ar.lock "logic sep_system_peripherals_axi_req_o.ar.lock"
Toggle sep_system_peripherals_req.ar.lock "logic sep_system_peripherals_req.ar.lock"
Toggle sep_system_peripherals_axi_req_o.ar.id [5] "logic sep_system_peripherals_axi_req_o.ar.id[5:0]"
Toggle sep_system_peripherals_req.ar.id [5] "logic sep_system_peripherals_req.ar.id[5:0]"
Toggle sep_system_peripherals_axi_req_o.aw.user [11:4] "logic sep_system_peripherals_axi_req_o.aw.user[11:0]"
Toggle sep_system_peripherals_req.aw.user [11:4] "logic sep_system_peripherals_req.aw.user[11:0]"
Toggle sep_system_peripherals_axi_req_o.aw.qos "logic sep_system_peripherals_axi_req_o.aw.qos[3:0]"
Toggle sep_system_peripherals_req.aw.qos "logic sep_system_peripherals_req.aw.qos[3:0]"
Toggle sep_system_peripherals_axi_req_o.aw.lock "logic sep_system_peripherals_axi_req_o.aw.lock"
Toggle sep_system_peripherals_req.aw.lock "logic sep_system_peripherals_req.aw.lock"
Toggle sep_system_peripherals_axi_req_o.aw.atop "logic sep_system_peripherals_axi_req_o.aw.atop[5:0]"
Toggle sep_system_peripherals_req.aw.atop "logic sep_system_peripherals_req.aw.atop[5:0]"
Toggle sep_system_peripherals_axi_req_o.aw.id [5] "logic sep_system_peripherals_axi_req_o.aw.id[5:0]"
Toggle sep_system_peripherals_req.aw.id [5] "logic sep_system_peripherals_req.aw.id[5:0]"
Toggle sep_system_peripherals_axi_req_o.w.user [11:4] "logic sep_system_peripherals_axi_req_o.w.user[11:0]"
Toggle sep_system_peripherals_req.w.user [11:4] "logic sep_system_peripherals_req.w.user[11:0]"
Toggle sep_io_axi_req_o.ar.addr [19:6] "logic sep_io_axi_req_o.ar.addr[31:0]"
Toggle sep_io_axi_req_o.ar.addr [22] "logic sep_io_axi_req_o.ar.addr[31:0]"
Toggle sep_io_axi_req_o.ar.addr [27:24] "logic sep_io_axi_req_o.ar.addr[31:0]"
Toggle sep_io_axi_req_o.ar.addr [31:29] "logic sep_io_axi_req_o.ar.addr[31:0]"
Toggle sep_io_req.ar.addr [19:6] "logic sep_io_req.ar.addr[31:0]"
Toggle sep_io_req.ar.addr [22] "logic sep_io_req.ar.addr[31:0]"
Toggle sep_io_req.ar.addr [27:24] "logic sep_io_req.ar.addr[31:0]"
Toggle sep_io_req.ar.addr [31:29] "logic sep_io_req.ar.addr[31:0]"
Toggle sep_io_axi_req_o.aw.addr [19:6] "logic sep_io_axi_req_o.aw.addr[31:0]"
Toggle sep_io_axi_req_o.aw.addr [22] "logic sep_io_axi_req_o.aw.addr[31:0]"
Toggle sep_io_axi_req_o.aw.addr [27:24] "logic sep_io_axi_req_o.aw.addr[31:0]"
Toggle sep_io_axi_req_o.aw.addr [31:29] "logic sep_io_axi_req_o.aw.addr[31:0]"
Toggle sep_io_req.aw.addr [19:6] "logic sep_io_req.aw.addr[31:0]"
Toggle sep_io_req.aw.addr [22] "logic sep_io_req.aw.addr[31:0]"
Toggle sep_io_req.aw.addr [27:24] "logic sep_io_req.aw.addr[31:0]"
Toggle sep_io_req.aw.addr [31:29] "logic sep_io_req.aw.addr[31:0]"
Toggle entropy_fifo_axi_req_o.ar.addr [17] "logic entropy_fifo_axi_req_o.ar.addr[31:0]"
Toggle entropy_fifo_axi_req_o.ar.addr [19] "logic entropy_fifo_axi_req_o.ar.addr[31:0]"
Toggle entropy_fifo_axi_req_o.ar.addr [22:21] "logic entropy_fifo_axi_req_o.ar.addr[31:0]"
Toggle entropy_fifo_axi_req_o.ar.addr [27:24] "logic entropy_fifo_axi_req_o.ar.addr[31:0]"
Toggle entropy_fifo_axi_req_o.ar.addr [31:29] "logic entropy_fifo_axi_req_o.ar.addr[31:0]"
Toggle entropy_fifo_req.ar.addr [17] "logic entropy_fifo_req.ar.addr[31:0]"
Toggle entropy_fifo_req.ar.addr [19] "logic entropy_fifo_req.ar.addr[31:0]"
Toggle entropy_fifo_req.ar.addr [22:21] "logic entropy_fifo_req.ar.addr[31:0]"
Toggle entropy_fifo_req.ar.addr [27:24] "logic entropy_fifo_req.ar.addr[31:0]"
Toggle entropy_fifo_req.ar.addr [31:29] "logic entropy_fifo_req.ar.addr[31:0]"
Toggle entropy_fifo_axi_req_o.aw.addr [17] "logic entropy_fifo_axi_req_o.aw.addr[31:0]"
Toggle entropy_fifo_axi_req_o.aw.addr [19] "logic entropy_fifo_axi_req_o.aw.addr[31:0]"
Toggle entropy_fifo_axi_req_o.aw.addr [22:21] "logic entropy_fifo_axi_req_o.aw.addr[31:0]"
Toggle entropy_fifo_axi_req_o.aw.addr [27:24] "logic entropy_fifo_axi_req_o.aw.addr[31:0]"
Toggle entropy_fifo_axi_req_o.aw.addr [31:29] "logic entropy_fifo_axi_req_o.aw.addr[31:0]"
Toggle entropy_fifo_req.aw.addr [17] "logic entropy_fifo_req.aw.addr[31:0]"
Toggle entropy_fifo_req.aw.addr [19] "logic entropy_fifo_req.aw.addr[31:0]"
Toggle entropy_fifo_req.aw.addr [22:21] "logic entropy_fifo_req.aw.addr[31:0]"
Toggle entropy_fifo_req.aw.addr [27:24] "logic entropy_fifo_req.aw.addr[31:0]"
Toggle entropy_fifo_req.aw.addr [31:29] "logic entropy_fifo_req.aw.addr[31:0]"
Toggle sep_external_axi_req_o.ar.addr [31:30] "logic sep_external_axi_req_o.ar.addr[31:0]"
Toggle sep_external_req.ar.addr [31:30] "logic sep_external_req.ar.addr[31:0]"
Toggle sep_external_axi_req_o.aw.addr [31:30] "logic sep_external_axi_req_o.aw.addr[31:0]"
Toggle sep_external_req.aw.addr [31:30] "logic sep_external_req.aw.addr[31:0]"
ANNOTATION: "SEP-XBAR-IFU-NO-WRITE: the IFU never writes: aw_valid and w_valid are tied 0 (el2_ifu_mem_ctl.sv:1085-1101, waived on the port by sep_master_tie_exclusions.el). The IFU port reaches only the sram target (sep_local_axi_xbar_pkg.sv:141), so no AW is ever accepted on it and no B can be routed to it; the B spill register in the slave-port demux resets to 0 and loads only on b_valid (spill_register_flushable.sv:45-47,78; the IFU-port demux B spill exists because LatencyMode is CUT_ALL_PORTS at sep_local_axi_xbar_pkg.sv:126). NOT waived: aw_ready and w_ready, which the demux drives from its own state."
Toggle ifu_sram_axi_resp_o.b_valid "logic ifu_sram_axi_resp_o.b_valid"
Toggle ifu_sram_axi_resp_o.b.id "logic ifu_sram_axi_resp_o.b.id[2:0]"
Toggle ifu_sram_axi_resp_o.b.resp "logic ifu_sram_axi_resp_o.b.resp[1:0]"
Toggle ifu_sram_axi_resp_o.b.user "logic ifu_sram_axi_resp_o.b.user[11:0]"
Toggle ifu_sram_resp.b_valid "logic ifu_sram_resp.b_valid"
Toggle ifu_sram_resp.b.id "logic ifu_sram_resp.b.id[2:0]"
Toggle ifu_sram_resp.b.resp "logic ifu_sram_resp.b.resp[1:0]"
Toggle ifu_sram_resp.b.user "logic ifu_sram_resp.b.user[11:0]"
ANNOTATION: "SEP-XBAR-TCM-RESP-USER-TIED: the cpu_tcm target is the VeeR DMA slave port of u_sep_cpu (hw/sys/sep/rtl/sep.sv:437,695), and sep_cpu.sv:511-512 drive its B and R USER to SEP_SOURCE_ID, 4'b1111 zero-extended to 12 bits (sep_pkg.sv:489), from time 0. NOT waived: response user on every other target and on the initiator side, which integrator-driven targets (sep_system_peripherals, sep_external) can move."
Toggle cpu_tcm_axi_resp_i.r.user "logic cpu_tcm_axi_resp_i.r.user[11:0]"
Toggle cpu_tcm_axi_resp_i.b.user "logic cpu_tcm_axi_resp_i.b.user[11:0]"
Toggle cpu_tcm_resp.r.user "logic cpu_tcm_resp.r.user[11:0]"
Toggle cpu_tcm_resp.b.user "logic cpu_tcm_resp.b.user[11:0]"

CHECKSUM: "1490650064 2890434499"
INSTANCE: sep_uvm_top.u_dut.u_sep.u_sep_system_peripherals.u_sep_system_peripherals_xbar_wrapper.u_sep_system_peripherals_xbar
ANNOTATION: "SEP-PXBAR-LOCAL-TIED: the sep_local_from_remap input carries only local-xbar target 6 traffic (hw/sys/sep/rtl/sep.sv:454,1079), which Connectivity limits to LSU, debug and DMA (sep_local_axi_xbar_pkg.sv:142-144). prim_axi_addr_fixer.sv:31-68, axi_alias_remap.sv:128-140, axi_cut and axi_demux pass qos, lock, atop, user and id unchanged. All three initiators tie qos, lock and AWATOP to 0 and AxUSER/WUSER[11:4] to 0 (LSU el2_lsu_bus_buffer.sv:881-907, debug el2_dbg.sv:738-774, sep_cpu.sv:493-508 with SEP_SOURCE_ID 4'b1111 at sep_pkg.sv:489; DMA axi_lite_to_axi.sv:39-67), and id[5] is bit 2 of the local-xbar initiator index, which is 1, 2 or 3 (axi_id_prepend.sv:92-93). NOT waived: smn_inbound inputs, addr (alias remap is programmable), id[4:0], AxUSER[3:0], prot, cache, size, len, burst and region."
Toggle sep_local_from_remap_req_i.aw.qos "logic sep_local_from_remap_req_i.aw.qos[3:0]"
Toggle sep_local_from_remap_req_i.aw.lock "logic sep_local_from_remap_req_i.aw.lock"
Toggle sep_local_from_remap_req_i.aw.user [11:4] "logic sep_local_from_remap_req_i.aw.user[11:0]"
Toggle sep_local_from_remap_req_i.aw.id [5] "logic sep_local_from_remap_req_i.aw.id[5:0]"
Toggle sep_local_from_remap_req_i.ar.qos "logic sep_local_from_remap_req_i.ar.qos[3:0]"
Toggle sep_local_from_remap_req_i.ar.lock "logic sep_local_from_remap_req_i.ar.lock"
Toggle sep_local_from_remap_req_i.ar.user [11:4] "logic sep_local_from_remap_req_i.ar.user[11:0]"
Toggle sep_local_from_remap_req_i.ar.id [5] "logic sep_local_from_remap_req_i.ar.id[5:0]"
Toggle sep_local_from_remap_req_i.aw.atop "logic sep_local_from_remap_req_i.aw.atop[5:0]"
Toggle sep_local_from_remap_req_i.w.user [11:4] "logic sep_local_from_remap_req_i.w.user[11:0]"
Toggle xbar_slv_req[0].aw.qos "logic xbar_slv_req[0].aw.qos[3:0]"
Toggle xbar_slv_req[0].aw.lock "logic xbar_slv_req[0].aw.lock"
Toggle xbar_slv_req[0].aw.user [11:4] "logic xbar_slv_req[0].aw.user[11:0]"
Toggle xbar_slv_req[0].aw.id [5] "logic xbar_slv_req[0].aw.id[5:0]"
Toggle xbar_slv_req[0].ar.qos "logic xbar_slv_req[0].ar.qos[3:0]"
Toggle xbar_slv_req[0].ar.lock "logic xbar_slv_req[0].ar.lock"
Toggle xbar_slv_req[0].ar.user [11:4] "logic xbar_slv_req[0].ar.user[11:0]"
Toggle xbar_slv_req[0].ar.id [5] "logic xbar_slv_req[0].ar.id[5:0]"
Toggle xbar_slv_req[0].aw.atop "logic xbar_slv_req[0].aw.atop[5:0]"
Toggle xbar_slv_req[0].w.user [11:4] "logic xbar_slv_req[0].w.user[11:0]"
ANNOTATION: "SEP-PXBAR-TARGET-DECODE: a peripheral-xbar target port carries only addresses inside its AddrMap rules (hw/sys/sep/rtl/crossbars/sep_system_peripherals_xbar.sv:62-126, LatencyMode CUT_ALL_PORTS at sep_system_peripherals_xbar_pkg.sv:210; extents from sep_addrmap_pkg.sv:23-27,173-232); the axi_mux spill registers reset to 0 and load only on a valid handshake (spill_register_flushable.sv:45-47,78). On the AXI-Lite side of axi_to_axi_lite the burst splitter can step the address, so those signals use the rule extent widened by 0x8000 (256 beats of 128 B). A listed bit is 0 over that whole extent. NOT waived: address bits that are 1 inside a rule, and addr[1:0] and every non-address field, which the SMN inbound port drives."
Toggle smn_inbound_from_xbar_req_o.aw.addr [55:30] "logic smn_inbound_from_xbar_req_o.aw.addr[55:0]"
Toggle smn_inbound_from_xbar_req_o.ar.addr [55:30] "logic smn_inbound_from_xbar_req_o.ar.addr[55:0]"
Toggle xbar_mst_req[0].aw.addr [55:30] "logic xbar_mst_req[0].aw.addr[55:0]"
Toggle xbar_mst_req[0].ar.addr [55:30] "logic xbar_mst_req[0].ar.addr[55:0]"
Toggle xbar_mst_req[1].aw.addr [20:16] "logic xbar_mst_req[1].aw.addr[55:0]"
Toggle xbar_mst_req[1].aw.addr [22] "logic xbar_mst_req[1].aw.addr[55:0]"
Toggle xbar_mst_req[1].aw.addr [27:24] "logic xbar_mst_req[1].aw.addr[55:0]"
Toggle xbar_mst_req[1].aw.addr [55:29] "logic xbar_mst_req[1].aw.addr[55:0]"
Toggle xbar_mst_req[1].ar.addr [20:16] "logic xbar_mst_req[1].ar.addr[55:0]"
Toggle xbar_mst_req[1].ar.addr [22] "logic xbar_mst_req[1].ar.addr[55:0]"
Toggle xbar_mst_req[1].ar.addr [27:24] "logic xbar_mst_req[1].ar.addr[55:0]"
Toggle xbar_mst_req[1].ar.addr [55:29] "logic xbar_mst_req[1].ar.addr[55:0]"
Toggle xbar_out_mailbox_req.aw.addr [20:16] "logic xbar_out_mailbox_req.aw.addr[55:0]"
Toggle xbar_out_mailbox_req.aw.addr [22] "logic xbar_out_mailbox_req.aw.addr[55:0]"
Toggle xbar_out_mailbox_req.aw.addr [27:24] "logic xbar_out_mailbox_req.aw.addr[55:0]"
Toggle xbar_out_mailbox_req.aw.addr [55:29] "logic xbar_out_mailbox_req.aw.addr[55:0]"
Toggle xbar_out_mailbox_req.ar.addr [20:16] "logic xbar_out_mailbox_req.ar.addr[55:0]"
Toggle xbar_out_mailbox_req.ar.addr [22] "logic xbar_out_mailbox_req.ar.addr[55:0]"
Toggle xbar_out_mailbox_req.ar.addr [27:24] "logic xbar_out_mailbox_req.ar.addr[55:0]"
Toggle xbar_out_mailbox_req.ar.addr [55:29] "logic xbar_out_mailbox_req.ar.addr[55:0]"
Toggle mailbox_req.aw.addr [20:17] "logic mailbox_req.aw.addr[55:0]"
Toggle mailbox_req.aw.addr [22] "logic mailbox_req.aw.addr[55:0]"
Toggle mailbox_req.aw.addr [27:24] "logic mailbox_req.aw.addr[55:0]"
Toggle mailbox_req.aw.addr [55:29] "logic mailbox_req.aw.addr[55:0]"
Toggle mailbox_req.ar.addr [20:17] "logic mailbox_req.ar.addr[55:0]"
Toggle mailbox_req.ar.addr [22] "logic mailbox_req.ar.addr[55:0]"
Toggle mailbox_req.ar.addr [27:24] "logic mailbox_req.ar.addr[55:0]"
Toggle mailbox_req.ar.addr [55:29] "logic mailbox_req.ar.addr[55:0]"
Toggle mailbox_req_o.aw.addr [20:17] "logic mailbox_req_o.aw.addr[55:0]"
Toggle mailbox_req_o.aw.addr [22] "logic mailbox_req_o.aw.addr[55:0]"
Toggle mailbox_req_o.aw.addr [27:24] "logic mailbox_req_o.aw.addr[55:0]"
Toggle mailbox_req_o.aw.addr [55:29] "logic mailbox_req_o.aw.addr[55:0]"
Toggle mailbox_req_o.ar.addr [20:17] "logic mailbox_req_o.ar.addr[55:0]"
Toggle mailbox_req_o.ar.addr [22] "logic mailbox_req_o.ar.addr[55:0]"
Toggle mailbox_req_o.ar.addr [27:24] "logic mailbox_req_o.ar.addr[55:0]"
Toggle mailbox_req_o.ar.addr [55:29] "logic mailbox_req_o.ar.addr[55:0]"
Toggle xbar_mst_req[2].aw.addr [15:14] "logic xbar_mst_req[2].aw.addr[55:0]"
Toggle xbar_mst_req[2].aw.addr [20:18] "logic xbar_mst_req[2].aw.addr[55:0]"
Toggle xbar_mst_req[2].aw.addr [22] "logic xbar_mst_req[2].aw.addr[55:0]"
Toggle xbar_mst_req[2].aw.addr [27:24] "logic xbar_mst_req[2].aw.addr[55:0]"
Toggle xbar_mst_req[2].aw.addr [55:29] "logic xbar_mst_req[2].aw.addr[55:0]"
Toggle xbar_mst_req[2].ar.addr [15:14] "logic xbar_mst_req[2].ar.addr[55:0]"
Toggle xbar_mst_req[2].ar.addr [20:18] "logic xbar_mst_req[2].ar.addr[55:0]"
Toggle xbar_mst_req[2].ar.addr [22] "logic xbar_mst_req[2].ar.addr[55:0]"
Toggle xbar_mst_req[2].ar.addr [27:24] "logic xbar_mst_req[2].ar.addr[55:0]"
Toggle xbar_mst_req[2].ar.addr [55:29] "logic xbar_mst_req[2].ar.addr[55:0]"
Toggle xbar_out_system_csr_req.aw.addr [15:14] "logic xbar_out_system_csr_req.aw.addr[55:0]"
Toggle xbar_out_system_csr_req.aw.addr [20:18] "logic xbar_out_system_csr_req.aw.addr[55:0]"
Toggle xbar_out_system_csr_req.aw.addr [22] "logic xbar_out_system_csr_req.aw.addr[55:0]"
Toggle xbar_out_system_csr_req.aw.addr [27:24] "logic xbar_out_system_csr_req.aw.addr[55:0]"
Toggle xbar_out_system_csr_req.aw.addr [55:29] "logic xbar_out_system_csr_req.aw.addr[55:0]"
Toggle xbar_out_system_csr_req.ar.addr [15:14] "logic xbar_out_system_csr_req.ar.addr[55:0]"
Toggle xbar_out_system_csr_req.ar.addr [20:18] "logic xbar_out_system_csr_req.ar.addr[55:0]"
Toggle xbar_out_system_csr_req.ar.addr [22] "logic xbar_out_system_csr_req.ar.addr[55:0]"
Toggle xbar_out_system_csr_req.ar.addr [27:24] "logic xbar_out_system_csr_req.ar.addr[55:0]"
Toggle xbar_out_system_csr_req.ar.addr [55:29] "logic xbar_out_system_csr_req.ar.addr[55:0]"
Toggle system_csr_req.aw.addr [20:18] "logic system_csr_req.aw.addr[55:0]"
Toggle system_csr_req.aw.addr [22] "logic system_csr_req.aw.addr[55:0]"
Toggle system_csr_req.aw.addr [27:24] "logic system_csr_req.aw.addr[55:0]"
Toggle system_csr_req.aw.addr [55:29] "logic system_csr_req.aw.addr[55:0]"
Toggle system_csr_req.ar.addr [20:18] "logic system_csr_req.ar.addr[55:0]"
Toggle system_csr_req.ar.addr [22] "logic system_csr_req.ar.addr[55:0]"
Toggle system_csr_req.ar.addr [27:24] "logic system_csr_req.ar.addr[55:0]"
Toggle system_csr_req.ar.addr [55:29] "logic system_csr_req.ar.addr[55:0]"
Toggle system_csr_req_o.aw.addr [20:18] "logic system_csr_req_o.aw.addr[55:0]"
Toggle system_csr_req_o.aw.addr [22] "logic system_csr_req_o.aw.addr[55:0]"
Toggle system_csr_req_o.aw.addr [27:24] "logic system_csr_req_o.aw.addr[55:0]"
Toggle system_csr_req_o.aw.addr [55:29] "logic system_csr_req_o.aw.addr[55:0]"
Toggle system_csr_req_o.ar.addr [20:18] "logic system_csr_req_o.ar.addr[55:0]"
Toggle system_csr_req_o.ar.addr [22] "logic system_csr_req_o.ar.addr[55:0]"
Toggle system_csr_req_o.ar.addr [27:24] "logic system_csr_req_o.ar.addr[55:0]"
Toggle system_csr_req_o.ar.addr [55:29] "logic system_csr_req_o.ar.addr[55:0]"

CHECKSUM: "3560311852 126358546"
INSTANCE: sep_uvm_top.u_dut.u_sep.u_sep_system_peripherals.u_sep_system_peripherals_xbar_wrapper
ANNOTATION: "SEP-PXBAR-LOCAL-TIED: the sep_local_from_remap input carries only local-xbar target 6 traffic (hw/sys/sep/rtl/sep.sv:454,1079), which Connectivity limits to LSU, debug and DMA (sep_local_axi_xbar_pkg.sv:142-144). prim_axi_addr_fixer.sv:31-68, axi_alias_remap.sv:128-140, axi_cut and axi_demux pass qos, lock, atop, user and id unchanged. All three initiators tie qos, lock and AWATOP to 0 and AxUSER/WUSER[11:4] to 0 (LSU el2_lsu_bus_buffer.sv:881-907, debug el2_dbg.sv:738-774, sep_cpu.sv:493-508 with SEP_SOURCE_ID 4'b1111 at sep_pkg.sv:489; DMA axi_lite_to_axi.sv:39-67), and id[5] is bit 2 of the local-xbar initiator index, which is 1, 2 or 3 (axi_id_prepend.sv:92-93). NOT waived: smn_inbound inputs, addr (alias remap is programmable), id[4:0], AxUSER[3:0], prot, cache, size, len, burst and region."
Toggle sep_local_from_remap_req_i.aw.qos "logic sep_local_from_remap_req_i.aw.qos[3:0]"
Toggle sep_local_from_remap_req_i.aw.lock "logic sep_local_from_remap_req_i.aw.lock"
Toggle sep_local_from_remap_req_i.aw.user [11:4] "logic sep_local_from_remap_req_i.aw.user[11:0]"
Toggle sep_local_from_remap_req_i.aw.id [5] "logic sep_local_from_remap_req_i.aw.id[5:0]"
Toggle sep_local_from_remap_req_i.ar.qos "logic sep_local_from_remap_req_i.ar.qos[3:0]"
Toggle sep_local_from_remap_req_i.ar.lock "logic sep_local_from_remap_req_i.ar.lock"
Toggle sep_local_from_remap_req_i.ar.user [11:4] "logic sep_local_from_remap_req_i.ar.user[11:0]"
Toggle sep_local_from_remap_req_i.ar.id [5] "logic sep_local_from_remap_req_i.ar.id[5:0]"
Toggle sep_local_from_remap_req_i.aw.atop "logic sep_local_from_remap_req_i.aw.atop[5:0]"
Toggle sep_local_from_remap_req_i.w.user [11:4] "logic sep_local_from_remap_req_i.w.user[11:0]"
Toggle sep_local_from_remap_req.aw.qos "logic sep_local_from_remap_req.aw.qos[3:0]"
Toggle sep_local_from_remap_req.aw.lock "logic sep_local_from_remap_req.aw.lock"
Toggle sep_local_from_remap_req.aw.user [11:4] "logic sep_local_from_remap_req.aw.user[11:0]"
Toggle sep_local_from_remap_req.aw.id [5] "logic sep_local_from_remap_req.aw.id[5:0]"
Toggle sep_local_from_remap_req.ar.qos "logic sep_local_from_remap_req.ar.qos[3:0]"
Toggle sep_local_from_remap_req.ar.lock "logic sep_local_from_remap_req.ar.lock"
Toggle sep_local_from_remap_req.ar.user [11:4] "logic sep_local_from_remap_req.ar.user[11:0]"
Toggle sep_local_from_remap_req.ar.id [5] "logic sep_local_from_remap_req.ar.id[5:0]"
Toggle sep_local_from_remap_req.aw.atop "logic sep_local_from_remap_req.aw.atop[5:0]"
Toggle sep_local_from_remap_req.w.user [11:4] "logic sep_local_from_remap_req.w.user[11:0]"
ANNOTATION: "SEP-PXBAR-TARGET-DECODE: a peripheral-xbar target port carries only addresses inside its AddrMap rules (hw/sys/sep/rtl/crossbars/sep_system_peripherals_xbar.sv:62-126, LatencyMode CUT_ALL_PORTS at sep_system_peripherals_xbar_pkg.sv:210; extents from sep_addrmap_pkg.sv:23-27,173-232); the axi_mux spill registers reset to 0 and load only on a valid handshake (spill_register_flushable.sv:45-47,78). On the AXI-Lite side of axi_to_axi_lite the burst splitter can step the address, so those signals use the rule extent widened by 0x8000 (256 beats of 128 B). A listed bit is 0 over that whole extent. NOT waived: address bits that are 1 inside a rule, and addr[1:0] and every non-address field, which the SMN inbound port drives."
Toggle smn_inbound_from_xbar_axi_req_o.aw.addr [55:30] "logic smn_inbound_from_xbar_axi_req_o.aw.addr[55:0]"
Toggle smn_inbound_from_xbar_axi_req_o.ar.addr [55:30] "logic smn_inbound_from_xbar_axi_req_o.ar.addr[55:0]"
Toggle smn_inbound_from_xbar_axi_req.aw.addr [55:30] "logic smn_inbound_from_xbar_axi_req.aw.addr[55:0]"
Toggle smn_inbound_from_xbar_axi_req.ar.addr [55:30] "logic smn_inbound_from_xbar_axi_req.ar.addr[55:0]"
Toggle mailbox_req_o.aw.addr [20:17] "logic mailbox_req_o.aw.addr[55:0]"
Toggle mailbox_req_o.aw.addr [22] "logic mailbox_req_o.aw.addr[55:0]"
Toggle mailbox_req_o.aw.addr [27:24] "logic mailbox_req_o.aw.addr[55:0]"
Toggle mailbox_req_o.aw.addr [55:29] "logic mailbox_req_o.aw.addr[55:0]"
Toggle mailbox_req_o.ar.addr [20:17] "logic mailbox_req_o.ar.addr[55:0]"
Toggle mailbox_req_o.ar.addr [22] "logic mailbox_req_o.ar.addr[55:0]"
Toggle mailbox_req_o.ar.addr [27:24] "logic mailbox_req_o.ar.addr[55:0]"
Toggle mailbox_req_o.ar.addr [55:29] "logic mailbox_req_o.ar.addr[55:0]"
Toggle mailbox_req.aw.addr [20:17] "logic mailbox_req.aw.addr[55:0]"
Toggle mailbox_req.aw.addr [22] "logic mailbox_req.aw.addr[55:0]"
Toggle mailbox_req.aw.addr [27:24] "logic mailbox_req.aw.addr[55:0]"
Toggle mailbox_req.aw.addr [55:29] "logic mailbox_req.aw.addr[55:0]"
Toggle mailbox_req.ar.addr [20:17] "logic mailbox_req.ar.addr[55:0]"
Toggle mailbox_req.ar.addr [22] "logic mailbox_req.ar.addr[55:0]"
Toggle mailbox_req.ar.addr [27:24] "logic mailbox_req.ar.addr[55:0]"
Toggle mailbox_req.ar.addr [55:29] "logic mailbox_req.ar.addr[55:0]"
Toggle system_csr_req_o.aw.addr [20:18] "logic system_csr_req_o.aw.addr[55:0]"
Toggle system_csr_req_o.aw.addr [22] "logic system_csr_req_o.aw.addr[55:0]"
Toggle system_csr_req_o.aw.addr [27:24] "logic system_csr_req_o.aw.addr[55:0]"
Toggle system_csr_req_o.aw.addr [55:29] "logic system_csr_req_o.aw.addr[55:0]"
Toggle system_csr_req_o.ar.addr [20:18] "logic system_csr_req_o.ar.addr[55:0]"
Toggle system_csr_req_o.ar.addr [22] "logic system_csr_req_o.ar.addr[55:0]"
Toggle system_csr_req_o.ar.addr [27:24] "logic system_csr_req_o.ar.addr[55:0]"
Toggle system_csr_req_o.ar.addr [55:29] "logic system_csr_req_o.ar.addr[55:0]"
Toggle system_csr_req.aw.addr [20:18] "logic system_csr_req.aw.addr[55:0]"
Toggle system_csr_req.aw.addr [22] "logic system_csr_req.aw.addr[55:0]"
Toggle system_csr_req.aw.addr [27:24] "logic system_csr_req.aw.addr[55:0]"
Toggle system_csr_req.aw.addr [55:29] "logic system_csr_req.aw.addr[55:0]"
Toggle system_csr_req.ar.addr [20:18] "logic system_csr_req.ar.addr[55:0]"
Toggle system_csr_req.ar.addr [22] "logic system_csr_req.ar.addr[55:0]"
Toggle system_csr_req.ar.addr [27:24] "logic system_csr_req.ar.addr[55:0]"
Toggle system_csr_req.ar.addr [55:29] "logic system_csr_req.ar.addr[55:0]"

CHECKSUM: "2309898495 127789342"
INSTANCE: sep_uvm_top.u_dut.u_sep.u_sep_crypto.u_sep_crypto_axi_interconnect
ANNOTATION: "SEP-CRYPTO-HOST-WINDOW: every host-path request in this module descends from sep_crypto_axi_req_i, which only the local-xbar sep_crypto target drives (hw/sys/sep/rtl/sep.sv:445,903; sep_crypto.sv:384). That target holds only addresses inside 0x1090_0000-0x1094_FFFF (sep_local_axi_xbar.sv:145-150) in axi_mux spill registers that reset to 0. The axi_demux broadcasts the address to every port, and the dw_converter and axi_to_axi_lite steps add at most 0x8000. A listed bit is 0 over 0x1090_0000-0x1095_7FFF. NOT waived: the Key Manager key-bus and eFuse ports (*_key_*, km_efuse_*), which the KM AXI-Lite xbar drives, and every non-address field, which the SMN inbound path can move."
Toggle sep_crypto_axi_req_i.ar.addr [19] "logic sep_crypto_axi_req_i.ar.addr[31:0]"
Toggle sep_crypto_axi_req_i.ar.addr [22:21] "logic sep_crypto_axi_req_i.ar.addr[31:0]"
Toggle sep_crypto_axi_req_i.ar.addr [27:24] "logic sep_crypto_axi_req_i.ar.addr[31:0]"
Toggle sep_crypto_axi_req_i.ar.addr [31:29] "logic sep_crypto_axi_req_i.ar.addr[31:0]"
Toggle sep_crypto_axi_req_i.aw.addr [19] "logic sep_crypto_axi_req_i.aw.addr[31:0]"
Toggle sep_crypto_axi_req_i.aw.addr [22:21] "logic sep_crypto_axi_req_i.aw.addr[31:0]"
Toggle sep_crypto_axi_req_i.aw.addr [27:24] "logic sep_crypto_axi_req_i.aw.addr[31:0]"
Toggle sep_crypto_axi_req_i.aw.addr [31:29] "logic sep_crypto_axi_req_i.aw.addr[31:0]"
Toggle otbn_axil_isolated_req_o.ar.addr [19] "logic otbn_axil_isolated_req_o.ar.addr[31:0]"
Toggle otbn_axil_isolated_req_o.ar.addr [22:21] "logic otbn_axil_isolated_req_o.ar.addr[31:0]"
Toggle otbn_axil_isolated_req_o.ar.addr [27:24] "logic otbn_axil_isolated_req_o.ar.addr[31:0]"
Toggle otbn_axil_isolated_req_o.ar.addr [31:29] "logic otbn_axil_isolated_req_o.ar.addr[31:0]"
Toggle otbn_axil_isolated_req_o.aw.addr [19] "logic otbn_axil_isolated_req_o.aw.addr[31:0]"
Toggle otbn_axil_isolated_req_o.aw.addr [22:21] "logic otbn_axil_isolated_req_o.aw.addr[31:0]"
Toggle otbn_axil_isolated_req_o.aw.addr [27:24] "logic otbn_axil_isolated_req_o.aw.addr[31:0]"
Toggle otbn_axil_isolated_req_o.aw.addr [31:29] "logic otbn_axil_isolated_req_o.aw.addr[31:0]"
Toggle hmac_axil_isolated_req_o.ar.addr [19] "logic hmac_axil_isolated_req_o.ar.addr[31:0]"
Toggle hmac_axil_isolated_req_o.ar.addr [22:21] "logic hmac_axil_isolated_req_o.ar.addr[31:0]"
Toggle hmac_axil_isolated_req_o.ar.addr [27:24] "logic hmac_axil_isolated_req_o.ar.addr[31:0]"
Toggle hmac_axil_isolated_req_o.ar.addr [31:29] "logic hmac_axil_isolated_req_o.ar.addr[31:0]"
Toggle hmac_axil_isolated_req_o.aw.addr [19] "logic hmac_axil_isolated_req_o.aw.addr[31:0]"
Toggle hmac_axil_isolated_req_o.aw.addr [22:21] "logic hmac_axil_isolated_req_o.aw.addr[31:0]"
Toggle hmac_axil_isolated_req_o.aw.addr [27:24] "logic hmac_axil_isolated_req_o.aw.addr[31:0]"
Toggle hmac_axil_isolated_req_o.aw.addr [31:29] "logic hmac_axil_isolated_req_o.aw.addr[31:0]"
Toggle aes_axil_isolated_req_o.ar.addr [19] "logic aes_axil_isolated_req_o.ar.addr[31:0]"
Toggle aes_axil_isolated_req_o.ar.addr [22:21] "logic aes_axil_isolated_req_o.ar.addr[31:0]"
Toggle aes_axil_isolated_req_o.ar.addr [27:24] "logic aes_axil_isolated_req_o.ar.addr[31:0]"
Toggle aes_axil_isolated_req_o.ar.addr [31:29] "logic aes_axil_isolated_req_o.ar.addr[31:0]"
Toggle aes_axil_isolated_req_o.aw.addr [19] "logic aes_axil_isolated_req_o.aw.addr[31:0]"
Toggle aes_axil_isolated_req_o.aw.addr [22:21] "logic aes_axil_isolated_req_o.aw.addr[31:0]"
Toggle aes_axil_isolated_req_o.aw.addr [27:24] "logic aes_axil_isolated_req_o.aw.addr[31:0]"
Toggle aes_axil_isolated_req_o.aw.addr [31:29] "logic aes_axil_isolated_req_o.aw.addr[31:0]"
Toggle kmac_axil_isolated_req_o.ar.addr [19] "logic kmac_axil_isolated_req_o.ar.addr[31:0]"
Toggle kmac_axil_isolated_req_o.ar.addr [22:21] "logic kmac_axil_isolated_req_o.ar.addr[31:0]"
Toggle kmac_axil_isolated_req_o.ar.addr [27:24] "logic kmac_axil_isolated_req_o.ar.addr[31:0]"
Toggle kmac_axil_isolated_req_o.ar.addr [31:29] "logic kmac_axil_isolated_req_o.ar.addr[31:0]"
Toggle kmac_axil_isolated_req_o.aw.addr [19] "logic kmac_axil_isolated_req_o.aw.addr[31:0]"
Toggle kmac_axil_isolated_req_o.aw.addr [22:21] "logic kmac_axil_isolated_req_o.aw.addr[31:0]"
Toggle kmac_axil_isolated_req_o.aw.addr [27:24] "logic kmac_axil_isolated_req_o.aw.addr[31:0]"
Toggle kmac_axil_isolated_req_o.aw.addr [31:29] "logic kmac_axil_isolated_req_o.aw.addr[31:0]"
Toggle abr_axi_isolated_req_o.ar.addr [19] "logic abr_axi_isolated_req_o.ar.addr[31:0]"
Toggle abr_axi_isolated_req_o.ar.addr [22:21] "logic abr_axi_isolated_req_o.ar.addr[31:0]"
Toggle abr_axi_isolated_req_o.ar.addr [27:24] "logic abr_axi_isolated_req_o.ar.addr[31:0]"
Toggle abr_axi_isolated_req_o.ar.addr [31:29] "logic abr_axi_isolated_req_o.ar.addr[31:0]"
Toggle abr_axi_isolated_req_o.aw.addr [19] "logic abr_axi_isolated_req_o.aw.addr[31:0]"
Toggle abr_axi_isolated_req_o.aw.addr [22:21] "logic abr_axi_isolated_req_o.aw.addr[31:0]"
Toggle abr_axi_isolated_req_o.aw.addr [27:24] "logic abr_axi_isolated_req_o.aw.addr[31:0]"
Toggle abr_axi_isolated_req_o.aw.addr [31:29] "logic abr_axi_isolated_req_o.aw.addr[31:0]"
Toggle km_mbox_axil_req_o.ar.addr [19] "logic km_mbox_axil_req_o.ar.addr[31:0]"
Toggle km_mbox_axil_req_o.ar.addr [22:21] "logic km_mbox_axil_req_o.ar.addr[31:0]"
Toggle km_mbox_axil_req_o.ar.addr [27:24] "logic km_mbox_axil_req_o.ar.addr[31:0]"
Toggle km_mbox_axil_req_o.ar.addr [31:29] "logic km_mbox_axil_req_o.ar.addr[31:0]"
Toggle km_mbox_axil_req_o.aw.addr [19] "logic km_mbox_axil_req_o.aw.addr[31:0]"
Toggle km_mbox_axil_req_o.aw.addr [22:21] "logic km_mbox_axil_req_o.aw.addr[31:0]"
Toggle km_mbox_axil_req_o.aw.addr [27:24] "logic km_mbox_axil_req_o.aw.addr[31:0]"
Toggle km_mbox_axil_req_o.aw.addr [31:29] "logic km_mbox_axil_req_o.aw.addr[31:0]"
Toggle esrc_axil_isolated_req_o.ar.addr [19] "logic esrc_axil_isolated_req_o.ar.addr[31:0]"
Toggle esrc_axil_isolated_req_o.ar.addr [22:21] "logic esrc_axil_isolated_req_o.ar.addr[31:0]"
Toggle esrc_axil_isolated_req_o.ar.addr [27:24] "logic esrc_axil_isolated_req_o.ar.addr[31:0]"
Toggle esrc_axil_isolated_req_o.ar.addr [31:29] "logic esrc_axil_isolated_req_o.ar.addr[31:0]"
Toggle esrc_axil_isolated_req_o.aw.addr [19] "logic esrc_axil_isolated_req_o.aw.addr[31:0]"
Toggle esrc_axil_isolated_req_o.aw.addr [22:21] "logic esrc_axil_isolated_req_o.aw.addr[31:0]"
Toggle esrc_axil_isolated_req_o.aw.addr [27:24] "logic esrc_axil_isolated_req_o.aw.addr[31:0]"
Toggle esrc_axil_isolated_req_o.aw.addr [31:29] "logic esrc_axil_isolated_req_o.aw.addr[31:0]"
Toggle csrng_axil_isolated_req_o.ar.addr [19] "logic csrng_axil_isolated_req_o.ar.addr[31:0]"
Toggle csrng_axil_isolated_req_o.ar.addr [22:21] "logic csrng_axil_isolated_req_o.ar.addr[31:0]"
Toggle csrng_axil_isolated_req_o.ar.addr [27:24] "logic csrng_axil_isolated_req_o.ar.addr[31:0]"
Toggle csrng_axil_isolated_req_o.ar.addr [31:29] "logic csrng_axil_isolated_req_o.ar.addr[31:0]"
Toggle csrng_axil_isolated_req_o.aw.addr [19] "logic csrng_axil_isolated_req_o.aw.addr[31:0]"
Toggle csrng_axil_isolated_req_o.aw.addr [22:21] "logic csrng_axil_isolated_req_o.aw.addr[31:0]"
Toggle csrng_axil_isolated_req_o.aw.addr [27:24] "logic csrng_axil_isolated_req_o.aw.addr[31:0]"
Toggle csrng_axil_isolated_req_o.aw.addr [31:29] "logic csrng_axil_isolated_req_o.aw.addr[31:0]"
Toggle edn_axil_isolated_req_o.ar.addr [19] "logic edn_axil_isolated_req_o.ar.addr[31:0]"
Toggle edn_axil_isolated_req_o.ar.addr [22:21] "logic edn_axil_isolated_req_o.ar.addr[31:0]"
Toggle edn_axil_isolated_req_o.ar.addr [27:24] "logic edn_axil_isolated_req_o.ar.addr[31:0]"
Toggle edn_axil_isolated_req_o.ar.addr [31:29] "logic edn_axil_isolated_req_o.ar.addr[31:0]"
Toggle edn_axil_isolated_req_o.aw.addr [19] "logic edn_axil_isolated_req_o.aw.addr[31:0]"
Toggle edn_axil_isolated_req_o.aw.addr [22:21] "logic edn_axil_isolated_req_o.aw.addr[31:0]"
Toggle edn_axil_isolated_req_o.aw.addr [27:24] "logic edn_axil_isolated_req_o.aw.addr[31:0]"
Toggle edn_axil_isolated_req_o.aw.addr [31:29] "logic edn_axil_isolated_req_o.aw.addr[31:0]"
Toggle ext_trng_axil_req_o.ar.addr [19] "logic ext_trng_axil_req_o.ar.addr[31:0]"
Toggle ext_trng_axil_req_o.ar.addr [22:21] "logic ext_trng_axil_req_o.ar.addr[31:0]"
Toggle ext_trng_axil_req_o.ar.addr [27:24] "logic ext_trng_axil_req_o.ar.addr[31:0]"
Toggle ext_trng_axil_req_o.ar.addr [31:29] "logic ext_trng_axil_req_o.ar.addr[31:0]"
Toggle ext_trng_axil_req_o.aw.addr [19] "logic ext_trng_axil_req_o.aw.addr[31:0]"
Toggle ext_trng_axil_req_o.aw.addr [22:21] "logic ext_trng_axil_req_o.aw.addr[31:0]"
Toggle ext_trng_axil_req_o.aw.addr [27:24] "logic ext_trng_axil_req_o.aw.addr[31:0]"
Toggle ext_trng_axil_req_o.aw.addr [31:29] "logic ext_trng_axil_req_o.aw.addr[31:0]"
Toggle fuse_axi_req_o.ar.addr [19] "logic fuse_axi_req_o.ar.addr[31:0]"
Toggle fuse_axi_req_o.ar.addr [22:21] "logic fuse_axi_req_o.ar.addr[31:0]"
Toggle fuse_axi_req_o.ar.addr [27:24] "logic fuse_axi_req_o.ar.addr[31:0]"
Toggle fuse_axi_req_o.ar.addr [31:29] "logic fuse_axi_req_o.ar.addr[31:0]"
Toggle fuse_axi_req_o.aw.addr [19] "logic fuse_axi_req_o.aw.addr[31:0]"
Toggle fuse_axi_req_o.aw.addr [22:21] "logic fuse_axi_req_o.aw.addr[31:0]"
Toggle fuse_axi_req_o.aw.addr [27:24] "logic fuse_axi_req_o.aw.addr[31:0]"
Toggle fuse_axi_req_o.aw.addr [31:29] "logic fuse_axi_req_o.aw.addr[31:0]"
Toggle lifecycle_axi_req_o.ar.addr [19] "logic lifecycle_axi_req_o.ar.addr[31:0]"
Toggle lifecycle_axi_req_o.ar.addr [22:21] "logic lifecycle_axi_req_o.ar.addr[31:0]"
Toggle lifecycle_axi_req_o.ar.addr [27:24] "logic lifecycle_axi_req_o.ar.addr[31:0]"
Toggle lifecycle_axi_req_o.ar.addr [31:29] "logic lifecycle_axi_req_o.ar.addr[31:0]"
Toggle lifecycle_axi_req_o.aw.addr [19] "logic lifecycle_axi_req_o.aw.addr[31:0]"
Toggle lifecycle_axi_req_o.aw.addr [22:21] "logic lifecycle_axi_req_o.aw.addr[31:0]"
Toggle lifecycle_axi_req_o.aw.addr [27:24] "logic lifecycle_axi_req_o.aw.addr[31:0]"
Toggle lifecycle_axi_req_o.aw.addr [31:29] "logic lifecycle_axi_req_o.aw.addr[31:0]"
Toggle sep_crypto_axi_reqs[0].ar.addr [19] "logic sep_crypto_axi_reqs[0].ar.addr[31:0]"
Toggle sep_crypto_axi_reqs[0].ar.addr [22:21] "logic sep_crypto_axi_reqs[0].ar.addr[31:0]"
Toggle sep_crypto_axi_reqs[0].ar.addr [27:24] "logic sep_crypto_axi_reqs[0].ar.addr[31:0]"
Toggle sep_crypto_axi_reqs[0].ar.addr [31:29] "logic sep_crypto_axi_reqs[0].ar.addr[31:0]"
Toggle sep_crypto_axi_reqs[0].aw.addr [19] "logic sep_crypto_axi_reqs[0].aw.addr[31:0]"
Toggle sep_crypto_axi_reqs[0].aw.addr [22:21] "logic sep_crypto_axi_reqs[0].aw.addr[31:0]"
Toggle sep_crypto_axi_reqs[0].aw.addr [27:24] "logic sep_crypto_axi_reqs[0].aw.addr[31:0]"
Toggle sep_crypto_axi_reqs[0].aw.addr [31:29] "logic sep_crypto_axi_reqs[0].aw.addr[31:0]"
Toggle sep_crypto_axi_reqs[1].ar.addr [19] "logic sep_crypto_axi_reqs[1].ar.addr[31:0]"
Toggle sep_crypto_axi_reqs[1].ar.addr [22:21] "logic sep_crypto_axi_reqs[1].ar.addr[31:0]"
Toggle sep_crypto_axi_reqs[1].ar.addr [27:24] "logic sep_crypto_axi_reqs[1].ar.addr[31:0]"
Toggle sep_crypto_axi_reqs[1].ar.addr [31:29] "logic sep_crypto_axi_reqs[1].ar.addr[31:0]"
Toggle sep_crypto_axi_reqs[1].aw.addr [19] "logic sep_crypto_axi_reqs[1].aw.addr[31:0]"
Toggle sep_crypto_axi_reqs[1].aw.addr [22:21] "logic sep_crypto_axi_reqs[1].aw.addr[31:0]"
Toggle sep_crypto_axi_reqs[1].aw.addr [27:24] "logic sep_crypto_axi_reqs[1].aw.addr[31:0]"
Toggle sep_crypto_axi_reqs[1].aw.addr [31:29] "logic sep_crypto_axi_reqs[1].aw.addr[31:0]"
Toggle sep_crypto_axi_reqs[2].ar.addr [19] "logic sep_crypto_axi_reqs[2].ar.addr[31:0]"
Toggle sep_crypto_axi_reqs[2].ar.addr [22:21] "logic sep_crypto_axi_reqs[2].ar.addr[31:0]"
Toggle sep_crypto_axi_reqs[2].ar.addr [27:24] "logic sep_crypto_axi_reqs[2].ar.addr[31:0]"
Toggle sep_crypto_axi_reqs[2].ar.addr [31:29] "logic sep_crypto_axi_reqs[2].ar.addr[31:0]"
Toggle sep_crypto_axi_reqs[2].aw.addr [19] "logic sep_crypto_axi_reqs[2].aw.addr[31:0]"
Toggle sep_crypto_axi_reqs[2].aw.addr [22:21] "logic sep_crypto_axi_reqs[2].aw.addr[31:0]"
Toggle sep_crypto_axi_reqs[2].aw.addr [27:24] "logic sep_crypto_axi_reqs[2].aw.addr[31:0]"
Toggle sep_crypto_axi_reqs[2].aw.addr [31:29] "logic sep_crypto_axi_reqs[2].aw.addr[31:0]"
Toggle sep_crypto_axi_reqs[3].ar.addr [19] "logic sep_crypto_axi_reqs[3].ar.addr[31:0]"
Toggle sep_crypto_axi_reqs[3].ar.addr [22:21] "logic sep_crypto_axi_reqs[3].ar.addr[31:0]"
Toggle sep_crypto_axi_reqs[3].ar.addr [27:24] "logic sep_crypto_axi_reqs[3].ar.addr[31:0]"
Toggle sep_crypto_axi_reqs[3].ar.addr [31:29] "logic sep_crypto_axi_reqs[3].ar.addr[31:0]"
Toggle sep_crypto_axi_reqs[3].aw.addr [19] "logic sep_crypto_axi_reqs[3].aw.addr[31:0]"
Toggle sep_crypto_axi_reqs[3].aw.addr [22:21] "logic sep_crypto_axi_reqs[3].aw.addr[31:0]"
Toggle sep_crypto_axi_reqs[3].aw.addr [27:24] "logic sep_crypto_axi_reqs[3].aw.addr[31:0]"
Toggle sep_crypto_axi_reqs[3].aw.addr [31:29] "logic sep_crypto_axi_reqs[3].aw.addr[31:0]"
Toggle sep_crypto_axi_reqs[4].ar.addr [19] "logic sep_crypto_axi_reqs[4].ar.addr[31:0]"
Toggle sep_crypto_axi_reqs[4].ar.addr [22:21] "logic sep_crypto_axi_reqs[4].ar.addr[31:0]"
Toggle sep_crypto_axi_reqs[4].ar.addr [27:24] "logic sep_crypto_axi_reqs[4].ar.addr[31:0]"
Toggle sep_crypto_axi_reqs[4].ar.addr [31:29] "logic sep_crypto_axi_reqs[4].ar.addr[31:0]"
Toggle sep_crypto_axi_reqs[4].aw.addr [19] "logic sep_crypto_axi_reqs[4].aw.addr[31:0]"
Toggle sep_crypto_axi_reqs[4].aw.addr [22:21] "logic sep_crypto_axi_reqs[4].aw.addr[31:0]"
Toggle sep_crypto_axi_reqs[4].aw.addr [27:24] "logic sep_crypto_axi_reqs[4].aw.addr[31:0]"
Toggle sep_crypto_axi_reqs[4].aw.addr [31:29] "logic sep_crypto_axi_reqs[4].aw.addr[31:0]"
Toggle sep_crypto_axi_reqs[5].ar.addr [19] "logic sep_crypto_axi_reqs[5].ar.addr[31:0]"
Toggle sep_crypto_axi_reqs[5].ar.addr [22:21] "logic sep_crypto_axi_reqs[5].ar.addr[31:0]"
Toggle sep_crypto_axi_reqs[5].ar.addr [27:24] "logic sep_crypto_axi_reqs[5].ar.addr[31:0]"
Toggle sep_crypto_axi_reqs[5].ar.addr [31:29] "logic sep_crypto_axi_reqs[5].ar.addr[31:0]"
Toggle sep_crypto_axi_reqs[5].aw.addr [19] "logic sep_crypto_axi_reqs[5].aw.addr[31:0]"
Toggle sep_crypto_axi_reqs[5].aw.addr [22:21] "logic sep_crypto_axi_reqs[5].aw.addr[31:0]"
Toggle sep_crypto_axi_reqs[5].aw.addr [27:24] "logic sep_crypto_axi_reqs[5].aw.addr[31:0]"
Toggle sep_crypto_axi_reqs[5].aw.addr [31:29] "logic sep_crypto_axi_reqs[5].aw.addr[31:0]"
Toggle sep_crypto_axi_reqs[6].ar.addr [19] "logic sep_crypto_axi_reqs[6].ar.addr[31:0]"
Toggle sep_crypto_axi_reqs[6].ar.addr [22:21] "logic sep_crypto_axi_reqs[6].ar.addr[31:0]"
Toggle sep_crypto_axi_reqs[6].ar.addr [27:24] "logic sep_crypto_axi_reqs[6].ar.addr[31:0]"
Toggle sep_crypto_axi_reqs[6].ar.addr [31:29] "logic sep_crypto_axi_reqs[6].ar.addr[31:0]"
Toggle sep_crypto_axi_reqs[6].aw.addr [19] "logic sep_crypto_axi_reqs[6].aw.addr[31:0]"
Toggle sep_crypto_axi_reqs[6].aw.addr [22:21] "logic sep_crypto_axi_reqs[6].aw.addr[31:0]"
Toggle sep_crypto_axi_reqs[6].aw.addr [27:24] "logic sep_crypto_axi_reqs[6].aw.addr[31:0]"
Toggle sep_crypto_axi_reqs[6].aw.addr [31:29] "logic sep_crypto_axi_reqs[6].aw.addr[31:0]"
Toggle sep_crypto_axi_reqs[7].ar.addr [19] "logic sep_crypto_axi_reqs[7].ar.addr[31:0]"
Toggle sep_crypto_axi_reqs[7].ar.addr [22:21] "logic sep_crypto_axi_reqs[7].ar.addr[31:0]"
Toggle sep_crypto_axi_reqs[7].ar.addr [27:24] "logic sep_crypto_axi_reqs[7].ar.addr[31:0]"
Toggle sep_crypto_axi_reqs[7].ar.addr [31:29] "logic sep_crypto_axi_reqs[7].ar.addr[31:0]"
Toggle sep_crypto_axi_reqs[7].aw.addr [19] "logic sep_crypto_axi_reqs[7].aw.addr[31:0]"
Toggle sep_crypto_axi_reqs[7].aw.addr [22:21] "logic sep_crypto_axi_reqs[7].aw.addr[31:0]"
Toggle sep_crypto_axi_reqs[7].aw.addr [27:24] "logic sep_crypto_axi_reqs[7].aw.addr[31:0]"
Toggle sep_crypto_axi_reqs[7].aw.addr [31:29] "logic sep_crypto_axi_reqs[7].aw.addr[31:0]"
Toggle sep_crypto_axi_reqs[8].ar.addr [19] "logic sep_crypto_axi_reqs[8].ar.addr[31:0]"
Toggle sep_crypto_axi_reqs[8].ar.addr [22:21] "logic sep_crypto_axi_reqs[8].ar.addr[31:0]"
Toggle sep_crypto_axi_reqs[8].ar.addr [27:24] "logic sep_crypto_axi_reqs[8].ar.addr[31:0]"
Toggle sep_crypto_axi_reqs[8].ar.addr [31:29] "logic sep_crypto_axi_reqs[8].ar.addr[31:0]"
Toggle sep_crypto_axi_reqs[8].aw.addr [19] "logic sep_crypto_axi_reqs[8].aw.addr[31:0]"
Toggle sep_crypto_axi_reqs[8].aw.addr [22:21] "logic sep_crypto_axi_reqs[8].aw.addr[31:0]"
Toggle sep_crypto_axi_reqs[8].aw.addr [27:24] "logic sep_crypto_axi_reqs[8].aw.addr[31:0]"
Toggle sep_crypto_axi_reqs[8].aw.addr [31:29] "logic sep_crypto_axi_reqs[8].aw.addr[31:0]"
Toggle sep_crypto_axi_reqs[9].ar.addr [19] "logic sep_crypto_axi_reqs[9].ar.addr[31:0]"
Toggle sep_crypto_axi_reqs[9].ar.addr [22:21] "logic sep_crypto_axi_reqs[9].ar.addr[31:0]"
Toggle sep_crypto_axi_reqs[9].ar.addr [27:24] "logic sep_crypto_axi_reqs[9].ar.addr[31:0]"
Toggle sep_crypto_axi_reqs[9].ar.addr [31:29] "logic sep_crypto_axi_reqs[9].ar.addr[31:0]"
Toggle sep_crypto_axi_reqs[9].aw.addr [19] "logic sep_crypto_axi_reqs[9].aw.addr[31:0]"
Toggle sep_crypto_axi_reqs[9].aw.addr [22:21] "logic sep_crypto_axi_reqs[9].aw.addr[31:0]"
Toggle sep_crypto_axi_reqs[9].aw.addr [27:24] "logic sep_crypto_axi_reqs[9].aw.addr[31:0]"
Toggle sep_crypto_axi_reqs[9].aw.addr [31:29] "logic sep_crypto_axi_reqs[9].aw.addr[31:0]"
Toggle sep_crypto_axi_reqs[10].ar.addr [19] "logic sep_crypto_axi_reqs[10].ar.addr[31:0]"
Toggle sep_crypto_axi_reqs[10].ar.addr [22:21] "logic sep_crypto_axi_reqs[10].ar.addr[31:0]"
Toggle sep_crypto_axi_reqs[10].ar.addr [27:24] "logic sep_crypto_axi_reqs[10].ar.addr[31:0]"
Toggle sep_crypto_axi_reqs[10].ar.addr [31:29] "logic sep_crypto_axi_reqs[10].ar.addr[31:0]"
Toggle sep_crypto_axi_reqs[10].aw.addr [19] "logic sep_crypto_axi_reqs[10].aw.addr[31:0]"
Toggle sep_crypto_axi_reqs[10].aw.addr [22:21] "logic sep_crypto_axi_reqs[10].aw.addr[31:0]"
Toggle sep_crypto_axi_reqs[10].aw.addr [27:24] "logic sep_crypto_axi_reqs[10].aw.addr[31:0]"
Toggle sep_crypto_axi_reqs[10].aw.addr [31:29] "logic sep_crypto_axi_reqs[10].aw.addr[31:0]"
Toggle sep_crypto_axi_reqs[11].ar.addr [19] "logic sep_crypto_axi_reqs[11].ar.addr[31:0]"
Toggle sep_crypto_axi_reqs[11].ar.addr [22:21] "logic sep_crypto_axi_reqs[11].ar.addr[31:0]"
Toggle sep_crypto_axi_reqs[11].ar.addr [27:24] "logic sep_crypto_axi_reqs[11].ar.addr[31:0]"
Toggle sep_crypto_axi_reqs[11].ar.addr [31:29] "logic sep_crypto_axi_reqs[11].ar.addr[31:0]"
Toggle sep_crypto_axi_reqs[11].aw.addr [19] "logic sep_crypto_axi_reqs[11].aw.addr[31:0]"
Toggle sep_crypto_axi_reqs[11].aw.addr [22:21] "logic sep_crypto_axi_reqs[11].aw.addr[31:0]"
Toggle sep_crypto_axi_reqs[11].aw.addr [27:24] "logic sep_crypto_axi_reqs[11].aw.addr[31:0]"
Toggle sep_crypto_axi_reqs[11].aw.addr [31:29] "logic sep_crypto_axi_reqs[11].aw.addr[31:0]"
Toggle sep_crypto_axi_reqs[12].ar.addr [19] "logic sep_crypto_axi_reqs[12].ar.addr[31:0]"
Toggle sep_crypto_axi_reqs[12].ar.addr [22:21] "logic sep_crypto_axi_reqs[12].ar.addr[31:0]"
Toggle sep_crypto_axi_reqs[12].ar.addr [27:24] "logic sep_crypto_axi_reqs[12].ar.addr[31:0]"
Toggle sep_crypto_axi_reqs[12].ar.addr [31:29] "logic sep_crypto_axi_reqs[12].ar.addr[31:0]"
Toggle sep_crypto_axi_reqs[12].aw.addr [19] "logic sep_crypto_axi_reqs[12].aw.addr[31:0]"
Toggle sep_crypto_axi_reqs[12].aw.addr [22:21] "logic sep_crypto_axi_reqs[12].aw.addr[31:0]"
Toggle sep_crypto_axi_reqs[12].aw.addr [27:24] "logic sep_crypto_axi_reqs[12].aw.addr[31:0]"
Toggle sep_crypto_axi_reqs[12].aw.addr [31:29] "logic sep_crypto_axi_reqs[12].aw.addr[31:0]"
Toggle otbn_conv_axil_req.ar.addr [19] "logic otbn_conv_axil_req.ar.addr[31:0]"
Toggle otbn_conv_axil_req.ar.addr [22:21] "logic otbn_conv_axil_req.ar.addr[31:0]"
Toggle otbn_conv_axil_req.ar.addr [27:24] "logic otbn_conv_axil_req.ar.addr[31:0]"
Toggle otbn_conv_axil_req.ar.addr [31:29] "logic otbn_conv_axil_req.ar.addr[31:0]"
Toggle otbn_conv_axil_req.aw.addr [19] "logic otbn_conv_axil_req.aw.addr[31:0]"
Toggle otbn_conv_axil_req.aw.addr [22:21] "logic otbn_conv_axil_req.aw.addr[31:0]"
Toggle otbn_conv_axil_req.aw.addr [27:24] "logic otbn_conv_axil_req.aw.addr[31:0]"
Toggle otbn_conv_axil_req.aw.addr [31:29] "logic otbn_conv_axil_req.aw.addr[31:0]"
Toggle hmac_conv_axil_req.ar.addr [19] "logic hmac_conv_axil_req.ar.addr[31:0]"
Toggle hmac_conv_axil_req.ar.addr [22:21] "logic hmac_conv_axil_req.ar.addr[31:0]"
Toggle hmac_conv_axil_req.ar.addr [27:24] "logic hmac_conv_axil_req.ar.addr[31:0]"
Toggle hmac_conv_axil_req.ar.addr [31:29] "logic hmac_conv_axil_req.ar.addr[31:0]"
Toggle hmac_conv_axil_req.aw.addr [19] "logic hmac_conv_axil_req.aw.addr[31:0]"
Toggle hmac_conv_axil_req.aw.addr [22:21] "logic hmac_conv_axil_req.aw.addr[31:0]"
Toggle hmac_conv_axil_req.aw.addr [27:24] "logic hmac_conv_axil_req.aw.addr[31:0]"
Toggle hmac_conv_axil_req.aw.addr [31:29] "logic hmac_conv_axil_req.aw.addr[31:0]"
Toggle aes_conv_axil_req.ar.addr [19] "logic aes_conv_axil_req.ar.addr[31:0]"
Toggle aes_conv_axil_req.ar.addr [22:21] "logic aes_conv_axil_req.ar.addr[31:0]"
Toggle aes_conv_axil_req.ar.addr [27:24] "logic aes_conv_axil_req.ar.addr[31:0]"
Toggle aes_conv_axil_req.ar.addr [31:29] "logic aes_conv_axil_req.ar.addr[31:0]"
Toggle aes_conv_axil_req.aw.addr [19] "logic aes_conv_axil_req.aw.addr[31:0]"
Toggle aes_conv_axil_req.aw.addr [22:21] "logic aes_conv_axil_req.aw.addr[31:0]"
Toggle aes_conv_axil_req.aw.addr [27:24] "logic aes_conv_axil_req.aw.addr[31:0]"
Toggle aes_conv_axil_req.aw.addr [31:29] "logic aes_conv_axil_req.aw.addr[31:0]"
Toggle kmac_conv_axil_req.ar.addr [19] "logic kmac_conv_axil_req.ar.addr[31:0]"
Toggle kmac_conv_axil_req.ar.addr [22:21] "logic kmac_conv_axil_req.ar.addr[31:0]"
Toggle kmac_conv_axil_req.ar.addr [27:24] "logic kmac_conv_axil_req.ar.addr[31:0]"
Toggle kmac_conv_axil_req.ar.addr [31:29] "logic kmac_conv_axil_req.ar.addr[31:0]"
Toggle kmac_conv_axil_req.aw.addr [19] "logic kmac_conv_axil_req.aw.addr[31:0]"
Toggle kmac_conv_axil_req.aw.addr [22:21] "logic kmac_conv_axil_req.aw.addr[31:0]"
Toggle kmac_conv_axil_req.aw.addr [27:24] "logic kmac_conv_axil_req.aw.addr[31:0]"
Toggle kmac_conv_axil_req.aw.addr [31:29] "logic kmac_conv_axil_req.aw.addr[31:0]"
Toggle otbn_axi_req_cache_forced.ar.addr [19] "logic otbn_axi_req_cache_forced.ar.addr[31:0]"
Toggle otbn_axi_req_cache_forced.ar.addr [22:21] "logic otbn_axi_req_cache_forced.ar.addr[31:0]"
Toggle otbn_axi_req_cache_forced.ar.addr [27:24] "logic otbn_axi_req_cache_forced.ar.addr[31:0]"
Toggle otbn_axi_req_cache_forced.ar.addr [31:29] "logic otbn_axi_req_cache_forced.ar.addr[31:0]"
Toggle otbn_axi_req_cache_forced.aw.addr [19] "logic otbn_axi_req_cache_forced.aw.addr[31:0]"
Toggle otbn_axi_req_cache_forced.aw.addr [22:21] "logic otbn_axi_req_cache_forced.aw.addr[31:0]"
Toggle otbn_axi_req_cache_forced.aw.addr [27:24] "logic otbn_axi_req_cache_forced.aw.addr[31:0]"
Toggle otbn_axi_req_cache_forced.aw.addr [31:29] "logic otbn_axi_req_cache_forced.aw.addr[31:0]"
Toggle otbn_axi32_req.ar.addr [19] "logic otbn_axi32_req.ar.addr[31:0]"
Toggle otbn_axi32_req.ar.addr [22:21] "logic otbn_axi32_req.ar.addr[31:0]"
Toggle otbn_axi32_req.ar.addr [27:24] "logic otbn_axi32_req.ar.addr[31:0]"
Toggle otbn_axi32_req.ar.addr [31:29] "logic otbn_axi32_req.ar.addr[31:0]"
Toggle otbn_axi32_req.aw.addr [19] "logic otbn_axi32_req.aw.addr[31:0]"
Toggle otbn_axi32_req.aw.addr [22:21] "logic otbn_axi32_req.aw.addr[31:0]"
Toggle otbn_axi32_req.aw.addr [27:24] "logic otbn_axi32_req.aw.addr[31:0]"
Toggle otbn_axi32_req.aw.addr [31:29] "logic otbn_axi32_req.aw.addr[31:0]"
Toggle hmac_axi32_req.ar.addr [19] "logic hmac_axi32_req.ar.addr[31:0]"
Toggle hmac_axi32_req.ar.addr [22:21] "logic hmac_axi32_req.ar.addr[31:0]"
Toggle hmac_axi32_req.ar.addr [27:24] "logic hmac_axi32_req.ar.addr[31:0]"
Toggle hmac_axi32_req.ar.addr [31:29] "logic hmac_axi32_req.ar.addr[31:0]"
Toggle hmac_axi32_req.aw.addr [19] "logic hmac_axi32_req.aw.addr[31:0]"
Toggle hmac_axi32_req.aw.addr [22:21] "logic hmac_axi32_req.aw.addr[31:0]"
Toggle hmac_axi32_req.aw.addr [27:24] "logic hmac_axi32_req.aw.addr[31:0]"
Toggle hmac_axi32_req.aw.addr [31:29] "logic hmac_axi32_req.aw.addr[31:0]"
Toggle aes_axi32_req.ar.addr [19] "logic aes_axi32_req.ar.addr[31:0]"
Toggle aes_axi32_req.ar.addr [22:21] "logic aes_axi32_req.ar.addr[31:0]"
Toggle aes_axi32_req.ar.addr [27:24] "logic aes_axi32_req.ar.addr[31:0]"
Toggle aes_axi32_req.ar.addr [31:29] "logic aes_axi32_req.ar.addr[31:0]"
Toggle aes_axi32_req.aw.addr [19] "logic aes_axi32_req.aw.addr[31:0]"
Toggle aes_axi32_req.aw.addr [22:21] "logic aes_axi32_req.aw.addr[31:0]"
Toggle aes_axi32_req.aw.addr [27:24] "logic aes_axi32_req.aw.addr[31:0]"
Toggle aes_axi32_req.aw.addr [31:29] "logic aes_axi32_req.aw.addr[31:0]"
Toggle kmac_axi32_req.ar.addr [19] "logic kmac_axi32_req.ar.addr[31:0]"
Toggle kmac_axi32_req.ar.addr [22:21] "logic kmac_axi32_req.ar.addr[31:0]"
Toggle kmac_axi32_req.ar.addr [27:24] "logic kmac_axi32_req.ar.addr[31:0]"
Toggle kmac_axi32_req.ar.addr [31:29] "logic kmac_axi32_req.ar.addr[31:0]"
Toggle kmac_axi32_req.aw.addr [19] "logic kmac_axi32_req.aw.addr[31:0]"
Toggle kmac_axi32_req.aw.addr [22:21] "logic kmac_axi32_req.aw.addr[31:0]"
Toggle kmac_axi32_req.aw.addr [27:24] "logic kmac_axi32_req.aw.addr[31:0]"
Toggle kmac_axi32_req.aw.addr [31:29] "logic kmac_axi32_req.aw.addr[31:0]"
Toggle km_axi32_req.ar.addr [19] "logic km_axi32_req.ar.addr[31:0]"
Toggle km_axi32_req.ar.addr [22:21] "logic km_axi32_req.ar.addr[31:0]"
Toggle km_axi32_req.ar.addr [27:24] "logic km_axi32_req.ar.addr[31:0]"
Toggle km_axi32_req.ar.addr [31:29] "logic km_axi32_req.ar.addr[31:0]"
Toggle km_axi32_req.aw.addr [19] "logic km_axi32_req.aw.addr[31:0]"
Toggle km_axi32_req.aw.addr [22:21] "logic km_axi32_req.aw.addr[31:0]"
Toggle km_axi32_req.aw.addr [27:24] "logic km_axi32_req.aw.addr[31:0]"
Toggle km_axi32_req.aw.addr [31:29] "logic km_axi32_req.aw.addr[31:0]"
Toggle esrc_axi32_req.ar.addr [19] "logic esrc_axi32_req.ar.addr[31:0]"
Toggle esrc_axi32_req.ar.addr [22:21] "logic esrc_axi32_req.ar.addr[31:0]"
Toggle esrc_axi32_req.ar.addr [27:24] "logic esrc_axi32_req.ar.addr[31:0]"
Toggle esrc_axi32_req.ar.addr [31:29] "logic esrc_axi32_req.ar.addr[31:0]"
Toggle esrc_axi32_req.aw.addr [19] "logic esrc_axi32_req.aw.addr[31:0]"
Toggle esrc_axi32_req.aw.addr [22:21] "logic esrc_axi32_req.aw.addr[31:0]"
Toggle esrc_axi32_req.aw.addr [27:24] "logic esrc_axi32_req.aw.addr[31:0]"
Toggle esrc_axi32_req.aw.addr [31:29] "logic esrc_axi32_req.aw.addr[31:0]"
Toggle esrc_conv_axil_req.ar.addr [19] "logic esrc_conv_axil_req.ar.addr[31:0]"
Toggle esrc_conv_axil_req.ar.addr [22:21] "logic esrc_conv_axil_req.ar.addr[31:0]"
Toggle esrc_conv_axil_req.ar.addr [27:24] "logic esrc_conv_axil_req.ar.addr[31:0]"
Toggle esrc_conv_axil_req.ar.addr [31:29] "logic esrc_conv_axil_req.ar.addr[31:0]"
Toggle esrc_conv_axil_req.aw.addr [19] "logic esrc_conv_axil_req.aw.addr[31:0]"
Toggle esrc_conv_axil_req.aw.addr [22:21] "logic esrc_conv_axil_req.aw.addr[31:0]"
Toggle esrc_conv_axil_req.aw.addr [27:24] "logic esrc_conv_axil_req.aw.addr[31:0]"
Toggle esrc_conv_axil_req.aw.addr [31:29] "logic esrc_conv_axil_req.aw.addr[31:0]"
Toggle csrng_conv_axil_req.ar.addr [19] "logic csrng_conv_axil_req.ar.addr[31:0]"
Toggle csrng_conv_axil_req.ar.addr [22:21] "logic csrng_conv_axil_req.ar.addr[31:0]"
Toggle csrng_conv_axil_req.ar.addr [27:24] "logic csrng_conv_axil_req.ar.addr[31:0]"
Toggle csrng_conv_axil_req.ar.addr [31:29] "logic csrng_conv_axil_req.ar.addr[31:0]"
Toggle csrng_conv_axil_req.aw.addr [19] "logic csrng_conv_axil_req.aw.addr[31:0]"
Toggle csrng_conv_axil_req.aw.addr [22:21] "logic csrng_conv_axil_req.aw.addr[31:0]"
Toggle csrng_conv_axil_req.aw.addr [27:24] "logic csrng_conv_axil_req.aw.addr[31:0]"
Toggle csrng_conv_axil_req.aw.addr [31:29] "logic csrng_conv_axil_req.aw.addr[31:0]"
Toggle edn_conv_axil_req.ar.addr [19] "logic edn_conv_axil_req.ar.addr[31:0]"
Toggle edn_conv_axil_req.ar.addr [22:21] "logic edn_conv_axil_req.ar.addr[31:0]"
Toggle edn_conv_axil_req.ar.addr [27:24] "logic edn_conv_axil_req.ar.addr[31:0]"
Toggle edn_conv_axil_req.ar.addr [31:29] "logic edn_conv_axil_req.ar.addr[31:0]"
Toggle edn_conv_axil_req.aw.addr [19] "logic edn_conv_axil_req.aw.addr[31:0]"
Toggle edn_conv_axil_req.aw.addr [22:21] "logic edn_conv_axil_req.aw.addr[31:0]"
Toggle edn_conv_axil_req.aw.addr [27:24] "logic edn_conv_axil_req.aw.addr[31:0]"
Toggle edn_conv_axil_req.aw.addr [31:29] "logic edn_conv_axil_req.aw.addr[31:0]"
Toggle trng_axi32_req.ar.addr [19] "logic trng_axi32_req.ar.addr[31:0]"
Toggle trng_axi32_req.ar.addr [22:21] "logic trng_axi32_req.ar.addr[31:0]"
Toggle trng_axi32_req.ar.addr [27:24] "logic trng_axi32_req.ar.addr[31:0]"
Toggle trng_axi32_req.ar.addr [31:29] "logic trng_axi32_req.ar.addr[31:0]"
Toggle trng_axi32_req.aw.addr [19] "logic trng_axi32_req.aw.addr[31:0]"
Toggle trng_axi32_req.aw.addr [22:21] "logic trng_axi32_req.aw.addr[31:0]"
Toggle trng_axi32_req.aw.addr [27:24] "logic trng_axi32_req.aw.addr[31:0]"
Toggle trng_axi32_req.aw.addr [31:29] "logic trng_axi32_req.aw.addr[31:0]"
Toggle trng_axil_req.ar.addr [19] "logic trng_axil_req.ar.addr[31:0]"
Toggle trng_axil_req.ar.addr [22:21] "logic trng_axil_req.ar.addr[31:0]"
Toggle trng_axil_req.ar.addr [27:24] "logic trng_axil_req.ar.addr[31:0]"
Toggle trng_axil_req.ar.addr [31:29] "logic trng_axil_req.ar.addr[31:0]"
Toggle trng_axil_req.aw.addr [19] "logic trng_axil_req.aw.addr[31:0]"
Toggle trng_axil_req.aw.addr [22:21] "logic trng_axil_req.aw.addr[31:0]"
Toggle trng_axil_req.aw.addr [27:24] "logic trng_axil_req.aw.addr[31:0]"
Toggle trng_axil_req.aw.addr [31:29] "logic trng_axil_req.aw.addr[31:0]"
ANNOTATION: "SEP-CRYPTO-OTBN-CACHE-FORCED: sep_crypto_axi_interconnect.sv:343-350 ORs axi_pkg::CACHE_MODIFIABLE (4'b0010) into the OTBN AxCACHE, so bit 1 is constant 1. NOT waived: cache bits 0, 2 and 3."
Toggle otbn_axi_req_cache_forced.aw.cache [1] "logic otbn_axi_req_cache_forced.aw.cache[3:0]"
Toggle otbn_axi_req_cache_forced.ar.cache [1] "logic otbn_axi_req_cache_forced.ar.cache[3:0]"
