// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 Tenstorrent USA, Inc.
//==================================================
// SEP VCS coverage exclusions -- RTL ties in the CPU wrapper, reset control,
// IO/SPI, watchdog and DMA wrappers, the CPU control regblock and the mailbox
// unit.
// Format Version: 2
//
// Scope: the cocotb VCS elaboration of sep_uvm_top, target `default`.
// TT-owned instances only. tlul_* and el2_mem_if submodules are a scope (.hier)
// question and are not waived here.
//
// Each block waives toggle bits, condition vectors, branch arms or FSM states
// that an RTL constant, an elaborated parameter or a single tied master fixes on
// every path into the instance. The annotation names the tie (file:line) and
// the fields that stay graded.
//
// Two rules keep this file honest:
//   * A net that a master, the inbound SoC port, JTAG, an integrator port or
//     software (a sw-writable CSR) can move is NOT listed. Those are stimulus gaps.
//   * A bit that any leaf moved is NOT listed. No listed bit toggles in either
//     direction in the merged `all` database; the file passes urg -excl_strict.
//
// Checksums come from `urg -dump full_exclusions tgl` on the merged VDB.
//==================================================

CHECKSUM: "3579852188 1455020830"
INSTANCE: sep_uvm_top.u_dut.u_sep.u_sep_cpu
ANNOTATION: "SEP-CPU-IFU-TIED: only the VeeR IFU drives these nets. el2_ifu_mem_ctl.sv:1074-1082 tie AR size 3, prot 5, cache 4'hF, len 0, burst INCR, qos 0, lock 0 and rready 1; :1085-1101 hold the whole AW and W channels and bready at 0 (the IFU never writes); sep_cpu.sv:493-495 drive AxUSER/WUSER to SEP_SOURCE_ID and :506 AWATOP to 0. axi_window_remap.sv passes every non-address field unchanged, and axi_demux_simple.sv:488,495,507 copy the AW, W and AR payload to every demux port, including the DECERR port [2]. NOT waived: AR addr, id, region and the post-remap AW addr, which SEP_LOCAL_BASE_ADDR (sw=rw, sep_cpu_ctrl.rdl:181-188) can move through the remap subtractor."
Toggle ifu_demux_req[0].ar.size "logic ifu_demux_req[0].ar.size[2:0]"
Toggle ifu_demux_req[0].ar.prot "logic ifu_demux_req[0].ar.prot[2:0]"
Toggle ifu_demux_req[0].ar.cache "logic ifu_demux_req[0].ar.cache[3:0]"
Toggle ifu_demux_req[0].ar.len "logic ifu_demux_req[0].ar.len[7:0]"
Toggle ifu_demux_req[0].ar.burst "logic ifu_demux_req[0].ar.burst[1:0]"
Toggle ifu_demux_req[0].ar.qos "logic ifu_demux_req[0].ar.qos[3:0]"
Toggle ifu_demux_req[0].ar.lock "logic ifu_demux_req[0].ar.lock"
Toggle ifu_demux_req[0].ar.user "logic ifu_demux_req[0].ar.user[11:0]"
Toggle ifu_demux_req[0].aw_valid "logic ifu_demux_req[0].aw_valid"
Toggle ifu_demux_req[0].aw.id "logic ifu_demux_req[0].aw.id[2:0]"
Toggle ifu_demux_req[0].aw.len "logic ifu_demux_req[0].aw.len[7:0]"
Toggle ifu_demux_req[0].aw.size "logic ifu_demux_req[0].aw.size[2:0]"
Toggle ifu_demux_req[0].aw.burst "logic ifu_demux_req[0].aw.burst[1:0]"
Toggle ifu_demux_req[0].aw.lock "logic ifu_demux_req[0].aw.lock"
Toggle ifu_demux_req[0].aw.cache "logic ifu_demux_req[0].aw.cache[3:0]"
Toggle ifu_demux_req[0].aw.prot "logic ifu_demux_req[0].aw.prot[2:0]"
Toggle ifu_demux_req[0].aw.qos "logic ifu_demux_req[0].aw.qos[3:0]"
Toggle ifu_demux_req[0].aw.region "logic ifu_demux_req[0].aw.region[3:0]"
Toggle ifu_demux_req[0].aw.atop "logic ifu_demux_req[0].aw.atop[5:0]"
Toggle ifu_demux_req[0].aw.user "logic ifu_demux_req[0].aw.user[11:0]"
Toggle ifu_demux_req[0].w_valid "logic ifu_demux_req[0].w_valid"
Toggle ifu_demux_req[0].w.data "logic ifu_demux_req[0].w.data[63:0]"
Toggle ifu_demux_req[0].w.strb "logic ifu_demux_req[0].w.strb[7:0]"
Toggle ifu_demux_req[0].w.last "logic ifu_demux_req[0].w.last"
Toggle ifu_demux_req[0].w.user "logic ifu_demux_req[0].w.user[11:0]"
Toggle ifu_demux_req[0].b_ready "logic ifu_demux_req[0].b_ready"
Toggle ifu_demux_req[1].ar.size "logic ifu_demux_req[1].ar.size[2:0]"
Toggle ifu_demux_req[1].ar.prot "logic ifu_demux_req[1].ar.prot[2:0]"
Toggle ifu_demux_req[1].ar.cache "logic ifu_demux_req[1].ar.cache[3:0]"
Toggle ifu_demux_req[1].ar.len "logic ifu_demux_req[1].ar.len[7:0]"
Toggle ifu_demux_req[1].ar.burst "logic ifu_demux_req[1].ar.burst[1:0]"
Toggle ifu_demux_req[1].ar.qos "logic ifu_demux_req[1].ar.qos[3:0]"
Toggle ifu_demux_req[1].ar.lock "logic ifu_demux_req[1].ar.lock"
Toggle ifu_demux_req[1].ar.user "logic ifu_demux_req[1].ar.user[11:0]"
Toggle ifu_demux_req[1].aw_valid "logic ifu_demux_req[1].aw_valid"
Toggle ifu_demux_req[1].aw.id "logic ifu_demux_req[1].aw.id[2:0]"
Toggle ifu_demux_req[1].aw.len "logic ifu_demux_req[1].aw.len[7:0]"
Toggle ifu_demux_req[1].aw.size "logic ifu_demux_req[1].aw.size[2:0]"
Toggle ifu_demux_req[1].aw.burst "logic ifu_demux_req[1].aw.burst[1:0]"
Toggle ifu_demux_req[1].aw.lock "logic ifu_demux_req[1].aw.lock"
Toggle ifu_demux_req[1].aw.cache "logic ifu_demux_req[1].aw.cache[3:0]"
Toggle ifu_demux_req[1].aw.prot "logic ifu_demux_req[1].aw.prot[2:0]"
Toggle ifu_demux_req[1].aw.qos "logic ifu_demux_req[1].aw.qos[3:0]"
Toggle ifu_demux_req[1].aw.region "logic ifu_demux_req[1].aw.region[3:0]"
Toggle ifu_demux_req[1].aw.atop "logic ifu_demux_req[1].aw.atop[5:0]"
Toggle ifu_demux_req[1].aw.user "logic ifu_demux_req[1].aw.user[11:0]"
Toggle ifu_demux_req[1].w_valid "logic ifu_demux_req[1].w_valid"
Toggle ifu_demux_req[1].w.data "logic ifu_demux_req[1].w.data[63:0]"
Toggle ifu_demux_req[1].w.strb "logic ifu_demux_req[1].w.strb[7:0]"
Toggle ifu_demux_req[1].w.last "logic ifu_demux_req[1].w.last"
Toggle ifu_demux_req[1].w.user "logic ifu_demux_req[1].w.user[11:0]"
Toggle ifu_demux_req[1].b_ready "logic ifu_demux_req[1].b_ready"
Toggle ifu_demux_req[2].ar.size "logic ifu_demux_req[2].ar.size[2:0]"
Toggle ifu_demux_req[2].ar.prot "logic ifu_demux_req[2].ar.prot[2:0]"
Toggle ifu_demux_req[2].ar.cache "logic ifu_demux_req[2].ar.cache[3:0]"
Toggle ifu_demux_req[2].ar.len "logic ifu_demux_req[2].ar.len[7:0]"
Toggle ifu_demux_req[2].ar.burst "logic ifu_demux_req[2].ar.burst[1:0]"
Toggle ifu_demux_req[2].ar.qos "logic ifu_demux_req[2].ar.qos[3:0]"
Toggle ifu_demux_req[2].ar.lock "logic ifu_demux_req[2].ar.lock"
Toggle ifu_demux_req[2].ar.user "logic ifu_demux_req[2].ar.user[11:0]"
Toggle ifu_demux_req[2].aw_valid "logic ifu_demux_req[2].aw_valid"
Toggle ifu_demux_req[2].aw.id "logic ifu_demux_req[2].aw.id[2:0]"
Toggle ifu_demux_req[2].aw.len "logic ifu_demux_req[2].aw.len[7:0]"
Toggle ifu_demux_req[2].aw.size "logic ifu_demux_req[2].aw.size[2:0]"
Toggle ifu_demux_req[2].aw.burst "logic ifu_demux_req[2].aw.burst[1:0]"
Toggle ifu_demux_req[2].aw.lock "logic ifu_demux_req[2].aw.lock"
Toggle ifu_demux_req[2].aw.cache "logic ifu_demux_req[2].aw.cache[3:0]"
Toggle ifu_demux_req[2].aw.prot "logic ifu_demux_req[2].aw.prot[2:0]"
Toggle ifu_demux_req[2].aw.qos "logic ifu_demux_req[2].aw.qos[3:0]"
Toggle ifu_demux_req[2].aw.region "logic ifu_demux_req[2].aw.region[3:0]"
Toggle ifu_demux_req[2].aw.atop "logic ifu_demux_req[2].aw.atop[5:0]"
Toggle ifu_demux_req[2].aw.user "logic ifu_demux_req[2].aw.user[11:0]"
Toggle ifu_demux_req[2].w_valid "logic ifu_demux_req[2].w_valid"
Toggle ifu_demux_req[2].w.data "logic ifu_demux_req[2].w.data[63:0]"
Toggle ifu_demux_req[2].w.strb "logic ifu_demux_req[2].w.strb[7:0]"
Toggle ifu_demux_req[2].w.last "logic ifu_demux_req[2].w.last"
Toggle ifu_demux_req[2].w.user "logic ifu_demux_req[2].w.user[11:0]"
Toggle ifu_demux_req[2].b_ready "logic ifu_demux_req[2].b_ready"
Toggle ifu_axi_req.r_ready "logic ifu_axi_req.r_ready"
Toggle ifu_axi_req_raw.r_ready "logic ifu_axi_req_raw.r_ready"

CHECKSUM: "3579852188 1455020830"
INSTANCE: sep_uvm_top.u_dut.u_sep.u_sep_cpu
ANNOTATION: "SEP-CPU-LSU-TIED: only the VeeR LSU drives these nets. el2_lsu_bus_buffer.sv:881-907 tie qos 0 and lock 0; sep_cpu.sv:497-499 drive AxUSER/WUSER to SEP_SOURCE_ID and :507 AWATOP to 0; the window remap and axi_demux_simple.sv:488,495,507 copy them to both demux ports. NOT waived: prot, len, burst and wlast, which a no_cpu leaf moves through its TB force."
Toggle lsu_demux_req[0].aw.qos "logic lsu_demux_req[0].aw.qos[3:0]"
Toggle lsu_demux_req[0].aw.lock "logic lsu_demux_req[0].aw.lock"
Toggle lsu_demux_req[0].aw.user "logic lsu_demux_req[0].aw.user[11:0]"
Toggle lsu_demux_req[0].aw.atop "logic lsu_demux_req[0].aw.atop[5:0]"
Toggle lsu_demux_req[0].ar.qos "logic lsu_demux_req[0].ar.qos[3:0]"
Toggle lsu_demux_req[0].ar.lock "logic lsu_demux_req[0].ar.lock"
Toggle lsu_demux_req[0].ar.user "logic lsu_demux_req[0].ar.user[11:0]"
Toggle lsu_demux_req[0].w.user "logic lsu_demux_req[0].w.user[11:0]"
Toggle lsu_demux_req[1].aw.qos "logic lsu_demux_req[1].aw.qos[3:0]"
Toggle lsu_demux_req[1].aw.lock "logic lsu_demux_req[1].aw.lock"
Toggle lsu_demux_req[1].aw.user "logic lsu_demux_req[1].aw.user[11:0]"
Toggle lsu_demux_req[1].aw.atop "logic lsu_demux_req[1].aw.atop[5:0]"
Toggle lsu_demux_req[1].ar.qos "logic lsu_demux_req[1].ar.qos[3:0]"
Toggle lsu_demux_req[1].ar.lock "logic lsu_demux_req[1].ar.lock"
Toggle lsu_demux_req[1].ar.user "logic lsu_demux_req[1].ar.user[11:0]"
Toggle lsu_demux_req[1].w.user "logic lsu_demux_req[1].w.user[11:0]"

CHECKSUM: "3579852188 1455020830"
INSTANCE: sep_uvm_top.u_dut.u_sep.u_sep_cpu
ANNOTATION: "SEP-CPU-IFU-DECERR-CONST: port [2] of the IFU demux is the axi_err_slv at sep_cpu.sv:630-643 (Resp DECERR, default RespData). axi_err_slv.sv:193-197 drive r.data to the RespData constant and r.user to 0 on every cycle; :142-145 drive b.user 0 and b.resp DECERR. The IFU never issues AW or W (el2_ifu_mem_ctl.sv:1085-1101), so the B FIFO is never pushed (b_valid 0, b.id holds the tied AW id 0), the W FIFO stays empty (w_ready 0, axi_err_slv.sv:109-114) and aw_ready = ~w_fifo_full stays 1 (:88). NOT waived: ar_ready, r_valid, r.id, r.last and r.resp, which an IFU fetch from an unmapped address moves."
Toggle ifu_demux_resp[2].r.data "logic ifu_demux_resp[2].r.data[63:0]"
Toggle ifu_demux_resp[2].r.user "logic ifu_demux_resp[2].r.user[11:0]"
Toggle ifu_demux_resp[2].b.user "logic ifu_demux_resp[2].b.user[11:0]"
Toggle ifu_demux_resp[2].b.resp "logic ifu_demux_resp[2].b.resp[1:0]"
Toggle ifu_demux_resp[2].b.id "logic ifu_demux_resp[2].b.id[2:0]"
Toggle ifu_demux_resp[2].b_valid "logic ifu_demux_resp[2].b_valid"
Toggle ifu_demux_resp[2].w_ready "logic ifu_demux_resp[2].w_ready"
Toggle ifu_demux_resp[2].aw_ready "logic ifu_demux_resp[2].aw_ready"

CHECKSUM: "3579852188 1455020830"
INSTANCE: sep_uvm_top.u_dut.u_sep.u_sep_cpu
ANNOTATION: "SEP-CPU-TCM-RESP-USER-TIED: sep_cpu.sv:511-512 drive cpu_tcm_axi_resp_o B and R USER to the SEP_SOURCE_ID constant. NOT waived: the B/R id, resp, data and last from the VeeR DMA port."
Toggle cpu_tcm_axi_resp_o.r.user "logic cpu_tcm_axi_resp_o.r.user[11:0]"
Toggle cpu_tcm_axi_resp_o.b.user "logic cpu_tcm_axi_resp_o.b.user[11:0]"

CHECKSUM: "3579852188 1455020830"
INSTANCE: sep_uvm_top.u_dut.u_sep.u_sep_cpu
ANNOTATION: "SEP-CPU-IRQ38-TIED: PIC source 39 is sep_internal_interrupts[38] = entropy_pool_err (sep.sv:586, :1059). sep_entropy_fifo.sv:191-197 builds the pool FIFO with Secure=0, and prim_fifo_sync_cnt.sv:142 then ties err_o to 0. NOT waived: every other interrupt line."
Toggle extintsrc_req_i [38] "logic extintsrc_req_i[254:0]"

CHECKSUM: "3579852188 1455020830"
INSTANCE: sep_uvm_top.u_dut.u_sep.u_sep_cpu
ANNOTATION: "SEP-CPU-LOCKSTEP-OFF: this build does not define RV_LOCKSTEP_ENABLE, so sep_cpu.sv:438-440 assign lockstep_status_o to 0. NOT waived: lockstep_ctrl_i, an integrator input."
Toggle lockstep_status_o.corruption_detected "logic lockstep_status_o.corruption_detected"

CHECKSUM: "3579852188 1455020830"
INSTANCE: sep_uvm_top.u_dut.u_sep.u_sep_cpu
ANNOTATION: "SEP-CPU-SB-ID-TIED: el2_dbg.sv:738 and :760 tie the system-bus AWID/ARID to 0; sep_cpu.sv:362 and :383 connect them to these nets. NOT waived: the B/R ids returned by the fabric."
Toggle sb_axi_awid_raw "logic sb_axi_awid_raw[0:0]"
Toggle sb_axi_arid_raw "logic sb_axi_arid_raw[0:0]"

CHECKSUM: "2196427632 2116802384"
INSTANCE: sep_uvm_top.u_dut.u_sep.u_sep_cpu.u_lsu_local_alias_remap
ANNOTATION: "SEP-REMAP-CONST-PORT: region_size_i and target_base_i are the sep_pkg constants SEP_LOCAL_ALIAS_REGION_SIZE/BASE at the instantiation (sep_cpu.sv:529-530). NOT waived: local_alias_base_i and the derived end/adjust nets, which SEP_LOCAL_BASE_ADDR moves."
Toggle region_size_i "logic region_size_i[31:0]"
Toggle target_base_i "logic target_base_i[31:0]"

CHECKSUM: "2196427632 2116802384"
INSTANCE: sep_uvm_top.u_dut.u_sep.u_sep_cpu.u_ifu_local_alias_remap
ANNOTATION: "SEP-REMAP-CONST-PORT: region_size_i and target_base_i are the sep_pkg constants SEP_LOCAL_ALIAS_REGION_SIZE/BASE at the instantiation (sep_cpu.sv:544-545). NOT waived: local_alias_base_i and the derived end/adjust nets, which SEP_LOCAL_BASE_ADDR moves."
Toggle region_size_i "logic region_size_i[31:0]"
Toggle target_base_i "logic target_base_i[31:0]"

CHECKSUM: "2196427632 2116802384"
INSTANCE: sep_uvm_top.u_dut.u_sep.u_sep_cpu.u_dbg_local_alias_remap
ANNOTATION: "SEP-REMAP-CONST-PORT: region_size_i and target_base_i are the sep_pkg constants SEP_LOCAL_ALIAS_REGION_SIZE/BASE at the instantiation (sep_cpu.sv:559-560). NOT waived: local_alias_base_i and the derived end/adjust nets, which SEP_LOCAL_BASE_ADDR moves."
Toggle region_size_i "logic region_size_i[31:0]"
Toggle target_base_i "logic target_base_i[31:0]"

CHECKSUM: "2196427632 2116802384"
INSTANCE: sep_uvm_top.u_dut.u_sep.u_sep_dma_wrap.u_dma_local_alias_remap
ANNOTATION: "SEP-REMAP-CONST-PORT: region_size_i and target_base_i are the sep_pkg constants SEP_LOCAL_ALIAS_REGION_SIZE/BASE at the instantiation (hw/sys/sep/rtl/sep_dma_wrap.sv:333-334). NOT waived: local_alias_base_i and the derived end/adjust nets, which SEP_LOCAL_BASE_ADDR moves."
Toggle region_size_i "logic region_size_i[31:0]"
Toggle target_base_i "logic target_base_i[31:0]"

CHECKSUM: "2196427632 2116802384"
INSTANCE: sep_uvm_top.u_dut.u_sep.u_sep_cpu.u_ifu_local_alias_remap
ANNOTATION: "SEP-CPU-IFU-TIED: only the VeeR IFU drives these nets. el2_ifu_mem_ctl.sv:1074-1082 tie AR size 3, prot 5, cache 4'hF, len 0, burst INCR, qos 0, lock 0 and rready 1; :1085-1101 hold the whole AW and W channels and bready at 0 (the IFU never writes); sep_cpu.sv:493-495 drive AxUSER/WUSER to SEP_SOURCE_ID and :506 AWATOP to 0. axi_window_remap.sv passes every non-address field unchanged, and axi_demux_simple.sv:488,495,507 copy the AW, W and AR payload to every demux port, including the DECERR port [2]. NOT waived: AR addr, id, region and the post-remap AW addr, which SEP_LOCAL_BASE_ADDR (sw=rw, sep_cpu_ctrl.rdl:181-188) can move through the remap subtractor."
Toggle slv_req_i.ar.size "logic slv_req_i.ar.size[2:0]"
Toggle slv_req_i.ar.prot "logic slv_req_i.ar.prot[2:0]"
Toggle slv_req_i.ar.cache "logic slv_req_i.ar.cache[3:0]"
Toggle slv_req_i.ar.len "logic slv_req_i.ar.len[7:0]"
Toggle slv_req_i.ar.burst "logic slv_req_i.ar.burst[1:0]"
Toggle slv_req_i.ar.qos "logic slv_req_i.ar.qos[3:0]"
Toggle slv_req_i.ar.lock "logic slv_req_i.ar.lock"
Toggle slv_req_i.ar.user "logic slv_req_i.ar.user[11:0]"
Toggle slv_req_i.aw_valid "logic slv_req_i.aw_valid"
Toggle slv_req_i.aw.id "logic slv_req_i.aw.id[2:0]"
Toggle slv_req_i.aw.len "logic slv_req_i.aw.len[7:0]"
Toggle slv_req_i.aw.size "logic slv_req_i.aw.size[2:0]"
Toggle slv_req_i.aw.burst "logic slv_req_i.aw.burst[1:0]"
Toggle slv_req_i.aw.lock "logic slv_req_i.aw.lock"
Toggle slv_req_i.aw.cache "logic slv_req_i.aw.cache[3:0]"
Toggle slv_req_i.aw.prot "logic slv_req_i.aw.prot[2:0]"
Toggle slv_req_i.aw.qos "logic slv_req_i.aw.qos[3:0]"
Toggle slv_req_i.aw.region "logic slv_req_i.aw.region[3:0]"
Toggle slv_req_i.aw.atop "logic slv_req_i.aw.atop[5:0]"
Toggle slv_req_i.aw.user "logic slv_req_i.aw.user[11:0]"
Toggle slv_req_i.w_valid "logic slv_req_i.w_valid"
Toggle slv_req_i.w.data "logic slv_req_i.w.data[63:0]"
Toggle slv_req_i.w.strb "logic slv_req_i.w.strb[7:0]"
Toggle slv_req_i.w.last "logic slv_req_i.w.last"
Toggle slv_req_i.w.user "logic slv_req_i.w.user[11:0]"
Toggle slv_req_i.b_ready "logic slv_req_i.b_ready"
Toggle slv_req_i.r_ready "logic slv_req_i.r_ready"
Toggle mst_req_o.ar.size "logic mst_req_o.ar.size[2:0]"
Toggle mst_req_o.ar.prot "logic mst_req_o.ar.prot[2:0]"
Toggle mst_req_o.ar.cache "logic mst_req_o.ar.cache[3:0]"
Toggle mst_req_o.ar.len "logic mst_req_o.ar.len[7:0]"
Toggle mst_req_o.ar.burst "logic mst_req_o.ar.burst[1:0]"
Toggle mst_req_o.ar.qos "logic mst_req_o.ar.qos[3:0]"
Toggle mst_req_o.ar.lock "logic mst_req_o.ar.lock"
Toggle mst_req_o.ar.user "logic mst_req_o.ar.user[11:0]"
Toggle mst_req_o.aw_valid "logic mst_req_o.aw_valid"
Toggle mst_req_o.aw.id "logic mst_req_o.aw.id[2:0]"
Toggle mst_req_o.aw.len "logic mst_req_o.aw.len[7:0]"
Toggle mst_req_o.aw.size "logic mst_req_o.aw.size[2:0]"
Toggle mst_req_o.aw.burst "logic mst_req_o.aw.burst[1:0]"
Toggle mst_req_o.aw.lock "logic mst_req_o.aw.lock"
Toggle mst_req_o.aw.cache "logic mst_req_o.aw.cache[3:0]"
Toggle mst_req_o.aw.prot "logic mst_req_o.aw.prot[2:0]"
Toggle mst_req_o.aw.qos "logic mst_req_o.aw.qos[3:0]"
Toggle mst_req_o.aw.region "logic mst_req_o.aw.region[3:0]"
Toggle mst_req_o.aw.atop "logic mst_req_o.aw.atop[5:0]"
Toggle mst_req_o.aw.user "logic mst_req_o.aw.user[11:0]"
Toggle mst_req_o.w_valid "logic mst_req_o.w_valid"
Toggle mst_req_o.w.data "logic mst_req_o.w.data[63:0]"
Toggle mst_req_o.w.strb "logic mst_req_o.w.strb[7:0]"
Toggle mst_req_o.w.last "logic mst_req_o.w.last"
Toggle mst_req_o.w.user "logic mst_req_o.w.user[11:0]"
Toggle mst_req_o.b_ready "logic mst_req_o.b_ready"
Toggle mst_req_o.r_ready "logic mst_req_o.r_ready"
Toggle slv_req_i.aw.addr "logic slv_req_i.aw.addr[31:0]"

CHECKSUM: "2196427632 2116802384"
INSTANCE: sep_uvm_top.u_dut.u_sep.u_sep_cpu.u_lsu_local_alias_remap
ANNOTATION: "SEP-CPU-LSU-TIED: only the VeeR LSU drives these nets. el2_lsu_bus_buffer.sv:881-907 tie qos 0 and lock 0; sep_cpu.sv:497-499 drive AxUSER/WUSER to SEP_SOURCE_ID and :507 AWATOP to 0; the window remap and axi_demux_simple.sv:488,495,507 copy them to both demux ports. NOT waived: prot, len, burst and wlast, which a no_cpu leaf moves through its TB force."
Toggle slv_req_i.aw.qos "logic slv_req_i.aw.qos[3:0]"
Toggle slv_req_i.aw.lock "logic slv_req_i.aw.lock"
Toggle slv_req_i.aw.user "logic slv_req_i.aw.user[11:0]"
Toggle slv_req_i.aw.atop "logic slv_req_i.aw.atop[5:0]"
Toggle slv_req_i.ar.qos "logic slv_req_i.ar.qos[3:0]"
Toggle slv_req_i.ar.lock "logic slv_req_i.ar.lock"
Toggle slv_req_i.ar.user "logic slv_req_i.ar.user[11:0]"
Toggle slv_req_i.w.user "logic slv_req_i.w.user[11:0]"
Toggle mst_req_o.aw.qos "logic mst_req_o.aw.qos[3:0]"
Toggle mst_req_o.aw.lock "logic mst_req_o.aw.lock"
Toggle mst_req_o.aw.user "logic mst_req_o.aw.user[11:0]"
Toggle mst_req_o.aw.atop "logic mst_req_o.aw.atop[5:0]"
Toggle mst_req_o.ar.qos "logic mst_req_o.ar.qos[3:0]"
Toggle mst_req_o.ar.lock "logic mst_req_o.ar.lock"
Toggle mst_req_o.ar.user "logic mst_req_o.ar.user[11:0]"
Toggle mst_req_o.w.user "logic mst_req_o.w.user[11:0]"

CHECKSUM: "2196427632 2116802384"
INSTANCE: sep_uvm_top.u_dut.u_sep.u_sep_cpu.u_dbg_local_alias_remap
ANNOTATION: "SEP-CPU-DBG-TIED: only the VeeR debug system-bus master drives this remap. el2_dbg.sv:738-774 tie id 0, prot 3'b001, AW cache 4'hF, AR cache 0, len 0, burst INCR, qos 0, lock 0, wlast 1, bready 1 and rready 1; sep_cpu.sv:501-503 and :508 drive AxUSER/WUSER to SEP_SOURCE_ID and AWATOP to 0; axi_window_remap.sv passes them unchanged. NOT waived: addr, size, region, valid, data and strobe, which a system-bus access moves."
Toggle slv_req_i.aw.id "logic slv_req_i.aw.id[2:0]"
Toggle slv_req_i.aw.prot "logic slv_req_i.aw.prot[2:0]"
Toggle slv_req_i.aw.cache "logic slv_req_i.aw.cache[3:0]"
Toggle slv_req_i.aw.len "logic slv_req_i.aw.len[7:0]"
Toggle slv_req_i.aw.burst "logic slv_req_i.aw.burst[1:0]"
Toggle slv_req_i.aw.qos "logic slv_req_i.aw.qos[3:0]"
Toggle slv_req_i.aw.lock "logic slv_req_i.aw.lock"
Toggle slv_req_i.aw.user "logic slv_req_i.aw.user[11:0]"
Toggle slv_req_i.aw.atop "logic slv_req_i.aw.atop[5:0]"
Toggle slv_req_i.ar.id "logic slv_req_i.ar.id[2:0]"
Toggle slv_req_i.ar.prot "logic slv_req_i.ar.prot[2:0]"
Toggle slv_req_i.ar.cache "logic slv_req_i.ar.cache[3:0]"
Toggle slv_req_i.ar.len "logic slv_req_i.ar.len[7:0]"
Toggle slv_req_i.ar.burst "logic slv_req_i.ar.burst[1:0]"
Toggle slv_req_i.ar.qos "logic slv_req_i.ar.qos[3:0]"
Toggle slv_req_i.ar.lock "logic slv_req_i.ar.lock"
Toggle slv_req_i.ar.user "logic slv_req_i.ar.user[11:0]"
Toggle slv_req_i.w.last "logic slv_req_i.w.last"
Toggle slv_req_i.w.user "logic slv_req_i.w.user[11:0]"
Toggle slv_req_i.b_ready "logic slv_req_i.b_ready"
Toggle slv_req_i.r_ready "logic slv_req_i.r_ready"
Toggle mst_req_o.aw.id "logic mst_req_o.aw.id[2:0]"
Toggle mst_req_o.aw.prot "logic mst_req_o.aw.prot[2:0]"
Toggle mst_req_o.aw.cache "logic mst_req_o.aw.cache[3:0]"
Toggle mst_req_o.aw.len "logic mst_req_o.aw.len[7:0]"
Toggle mst_req_o.aw.burst "logic mst_req_o.aw.burst[1:0]"
Toggle mst_req_o.aw.qos "logic mst_req_o.aw.qos[3:0]"
Toggle mst_req_o.aw.lock "logic mst_req_o.aw.lock"
Toggle mst_req_o.aw.user "logic mst_req_o.aw.user[11:0]"
Toggle mst_req_o.aw.atop "logic mst_req_o.aw.atop[5:0]"
Toggle mst_req_o.ar.id "logic mst_req_o.ar.id[2:0]"
Toggle mst_req_o.ar.prot "logic mst_req_o.ar.prot[2:0]"
Toggle mst_req_o.ar.cache "logic mst_req_o.ar.cache[3:0]"
Toggle mst_req_o.ar.len "logic mst_req_o.ar.len[7:0]"
Toggle mst_req_o.ar.burst "logic mst_req_o.ar.burst[1:0]"
Toggle mst_req_o.ar.qos "logic mst_req_o.ar.qos[3:0]"
Toggle mst_req_o.ar.lock "logic mst_req_o.ar.lock"
Toggle mst_req_o.ar.user "logic mst_req_o.ar.user[11:0]"
Toggle mst_req_o.w.last "logic mst_req_o.w.last"
Toggle mst_req_o.w.user "logic mst_req_o.w.user[11:0]"
Toggle mst_req_o.b_ready "logic mst_req_o.b_ready"
Toggle mst_req_o.r_ready "logic mst_req_o.r_ready"

CHECKSUM: "2196427632 2116802384"
INSTANCE: sep_uvm_top.u_dut.u_sep.u_sep_dma_wrap.u_dma_local_alias_remap
ANNOTATION: "SEP-DMA-MASTER-TIED: only the secure DMA host port drives this path. axi_lite_to_axi.sv:39-67 set burst FIXED, size log2(4), wlast 1 and id, len, lock, qos, region, atop and user to 0; sep_dma_wrap.sv:283-284 feed cache 4'b0000; the upsizer and the remap pass them unchanged. NOT waived: addr, size, prot and the W data/strobe."
Toggle slv_req_i.aw.id "logic slv_req_i.aw.id[2:0]"
Toggle slv_req_i.aw.len "logic slv_req_i.aw.len[7:0]"
Toggle slv_req_i.aw.burst "logic slv_req_i.aw.burst[1:0]"
Toggle slv_req_i.aw.lock "logic slv_req_i.aw.lock"
Toggle slv_req_i.aw.cache "logic slv_req_i.aw.cache[3:0]"
Toggle slv_req_i.aw.qos "logic slv_req_i.aw.qos[3:0]"
Toggle slv_req_i.aw.region "logic slv_req_i.aw.region[3:0]"
Toggle slv_req_i.aw.atop "logic slv_req_i.aw.atop[5:0]"
Toggle slv_req_i.aw.user "logic slv_req_i.aw.user[11:0]"
Toggle slv_req_i.ar.id "logic slv_req_i.ar.id[2:0]"
Toggle slv_req_i.ar.len "logic slv_req_i.ar.len[7:0]"
Toggle slv_req_i.ar.burst "logic slv_req_i.ar.burst[1:0]"
Toggle slv_req_i.ar.lock "logic slv_req_i.ar.lock"
Toggle slv_req_i.ar.cache "logic slv_req_i.ar.cache[3:0]"
Toggle slv_req_i.ar.qos "logic slv_req_i.ar.qos[3:0]"
Toggle slv_req_i.ar.region "logic slv_req_i.ar.region[3:0]"
Toggle slv_req_i.ar.user "logic slv_req_i.ar.user[11:0]"
Toggle slv_req_i.w.user "logic slv_req_i.w.user[11:0]"
Toggle mst_req_o.aw.id "logic mst_req_o.aw.id[2:0]"
Toggle mst_req_o.aw.len "logic mst_req_o.aw.len[7:0]"
Toggle mst_req_o.aw.burst "logic mst_req_o.aw.burst[1:0]"
Toggle mst_req_o.aw.lock "logic mst_req_o.aw.lock"
Toggle mst_req_o.aw.cache "logic mst_req_o.aw.cache[3:0]"
Toggle mst_req_o.aw.qos "logic mst_req_o.aw.qos[3:0]"
Toggle mst_req_o.aw.region "logic mst_req_o.aw.region[3:0]"
Toggle mst_req_o.aw.atop "logic mst_req_o.aw.atop[5:0]"
Toggle mst_req_o.aw.user "logic mst_req_o.aw.user[11:0]"
Toggle mst_req_o.ar.id "logic mst_req_o.ar.id[2:0]"
Toggle mst_req_o.ar.len "logic mst_req_o.ar.len[7:0]"
Toggle mst_req_o.ar.burst "logic mst_req_o.ar.burst[1:0]"
Toggle mst_req_o.ar.lock "logic mst_req_o.ar.lock"
Toggle mst_req_o.ar.cache "logic mst_req_o.ar.cache[3:0]"
Toggle mst_req_o.ar.qos "logic mst_req_o.ar.qos[3:0]"
Toggle mst_req_o.ar.region "logic mst_req_o.ar.region[3:0]"
Toggle mst_req_o.ar.user "logic mst_req_o.ar.user[11:0]"
Toggle mst_req_o.w.user "logic mst_req_o.w.user[11:0]"

CHECKSUM: "3743219407 170345763"
INSTANCE: sep_uvm_top.u_dut.u_sep.u_sep_reset_ctrl.u_reg
ANNOTATION: "SEP-REGBLOCK-READBACK-WIDTH: SW_RESET_N is the only register and holds bits [6:0]; sep_reset_ctrl_reg.sv:498-517 start readback_data at 0 and set only bits 0-6, so read data [63:7] is 0 on every path. SEP-REGBLOCK-ALIGNED-ADDR: :128-147 build cpuif_addr as {addr[3], 3'b0}, and decoded_addr/rd_mux_addr copy it, so bits [2:0] are 0. NOT waived: the write data and the AXI address inputs, which a master drives."
Toggle cpuif_addr [2:0] "logic cpuif_addr[3:0]"
Toggle decoded_addr [2:0] "logic decoded_addr[3:0]"
Toggle rd_mux_addr [2:0] "logic rd_mux_addr[3:0]"
Toggle s_axil_rdata [63:7] "logic s_axil_rdata[63:0]"
Toggle cpuif_rd_data [63:7] "logic cpuif_rd_data[63:0]"
Toggle readback_data [63:7] "logic readback_data[63:0]"

CHECKSUM: "3683425261 2769646694"
INSTANCE: sep_uvm_top.u_dut.u_sep.u_sep_reset_ctrl
ANNOTATION: "SEP-RSTCTL-LITE-RESP-TIED: axil_resp is the u_reg response. Its bresp/rresp hold OKAY (SEP-REGBLOCK-A2-NOERROR, sep_reset_ctrl_reg.sv:209-213 never take the SLVERR arm) and its read data [63:7] is 0 (sep_reset_ctrl_reg.sv:498-517). SEP-RSTCTL-AXI-USER-TIED: sep_reset_ctrl_axi_resp_o comes from axi_to_axi_lite (sep_reset_ctrl.sv:100-120). Its B/R user is 0 on every source: axi_to_axi_lite.sv:157-170 default '0, axi_atop_filter.sv:220 and :287 inject '0, axi_err_slv.sv:142 and :193 inject '0. NOT waived: the full-AXI r.data and r/b resp, which the burst splitter error slave and the ATOP filter can drive."
Toggle axil_resp.r.resp "logic axil_resp.r.resp[1:0]"
Toggle axil_resp.b.resp "logic axil_resp.b.resp[1:0]"
Toggle axil_resp.r.data [63:7] "logic axil_resp.r.data[63:0]"
Toggle sep_reset_ctrl_axi_resp_o.r.user "logic sep_reset_ctrl_axi_resp_o.r.user[11:0]"
Toggle sep_reset_ctrl_axi_resp_o.b.user "logic sep_reset_ctrl_axi_resp_o.b.user[11:0]"

CHECKSUM: "2905179362 2073096279"
INSTANCE: sep_uvm_top.u_dut.u_sep.u_sep_system_peripherals.u_sep_system_csr.u_sep_cpu_ctrl_reg
ANNOTATION: "SEP-CPUCTRL-HWIN-TIED: sep_system_csr.sv:779 and :781-786 tie timeout_interrupt_rsvd, sep_standalone and fast_{pka,sram,dccm,iccm,spi}_en to 0, and :817 and :820-825 drive these hw=w inputs from them. SEP-REGBLOCK-ALIGNED-ADDR: sep_cpu_ctrl_reg.sv:129-148 build cpuif_addr as {addr[12:3], 3'b0}; :317 and :1537 copy it, so bits [2:0] are 0. NOT waived: the sw-writable reserved TIMEOUT_* fields and the 64-bit REFERENCE_COUNTER, which software can write."
Toggle hwif_in.SEP_TEST_CTRL.fast_spi_en.next "logic hwif_in.SEP_TEST_CTRL.fast_spi_en.next"
Toggle hwif_in.SEP_TEST_CTRL.fast_iccm_en.next "logic hwif_in.SEP_TEST_CTRL.fast_iccm_en.next"
Toggle hwif_in.SEP_TEST_CTRL.fast_dccm_en.next "logic hwif_in.SEP_TEST_CTRL.fast_dccm_en.next"
Toggle hwif_in.SEP_TEST_CTRL.fast_sram_en.next "logic hwif_in.SEP_TEST_CTRL.fast_sram_en.next"
Toggle hwif_in.SEP_TEST_CTRL.fast_pka_en.next "logic hwif_in.SEP_TEST_CTRL.fast_pka_en.next"
Toggle hwif_in.SEP_TEST_CTRL.sep_standalone.next "logic hwif_in.SEP_TEST_CTRL.sep_standalone.next"
Toggle hwif_in.TIMEOUT_INTERRUPT.reserved.next "logic hwif_in.TIMEOUT_INTERRUPT.reserved.next"
Toggle cpuif_addr [2:0] "logic cpuif_addr[12:0]"
Toggle decoded_addr [2:0] "logic decoded_addr[12:0]"
Toggle rd_mux_addr [2:0] "logic rd_mux_addr[12:0]"

CHECKSUM: "2097437693 2552262841"
INSTANCE: sep_uvm_top.u_dut.u_sep.u_sep_wdt_wrap.u_wdt_axi_lite_to_tlul
ANNOTATION: "SEP-A2T-TIED: axi_lite_to_tlul.sv:132-134 start tl_o at 0, set a_size 2 and instr_type MuBi4False, and never assign a_param, a_source or a_user.rsvd; the only opcodes it drives are GET, PUT_FULL_DATA and PUT_PARTIAL_DATA (:173, :213, :215), so a_opcode[1] is 0. Its AXI-Lite resp is OKAY or SLVERR only (:54-55, :128-129, :195, :234), so resp[0] is 0. The TL-UL device answers from tlul_adapter_reg.sv:174-178 (or tlul_adapter_sram.sv:391-395 and tlul_err_resp.sv:67-71 behind tlul_socket_1n.sv:179-183): d_param and d_sink 0, d_opcode ACCESS_ACK or ACCESS_ACK_DATA, d_source and d_size echo the tied a_source 0 and a_size 2, so d_size[0] is 0. NOT waived: a_address, a_mask, a_data, a_opcode[0], the integrity fields, d_error and d_data."
Toggle tl_o.a_user.instr_type "logic tl_o.a_user.instr_type[3:0]"
Toggle tl_o.a_user.rsvd "logic tl_o.a_user.rsvd[9:0]"
Toggle tl_o.a_source "logic tl_o.a_source[7:0]"
Toggle tl_o.a_size "logic tl_o.a_size[1:0]"
Toggle tl_o.a_param "logic tl_o.a_param[2:0]"
Toggle tl_o.a_opcode [1] "logic tl_o.a_opcode[2:0]"
Toggle tl_i.d_sink "logic tl_i.d_sink[0:0]"
Toggle tl_i.d_param "logic tl_i.d_param[2:0]"
Toggle tl_i.d_source "logic tl_i.d_source[7:0]"
Toggle tl_i.d_size [0] "logic tl_i.d_size[1:0]"
Toggle tl_i.d_opcode [2:1] "logic tl_i.d_opcode[2:0]"
Toggle axi_lite_rsp_o.r.resp [0] "logic axi_lite_rsp_o.r.resp[1:0]"
Toggle axi_lite_rsp_o.b.resp [0] "logic axi_lite_rsp_o.b.resp[1:0]"

CHECKSUM: "2097437693 2552262841"
INSTANCE: sep_uvm_top.u_dut.u_sep.u_sep_io.u_sep_ot_spi_wrap.u_spi_axi_lite_to_tlul
ANNOTATION: "SEP-A2T-TIED: axi_lite_to_tlul.sv:132-134 start tl_o at 0, set a_size 2 and instr_type MuBi4False, and never assign a_param, a_source or a_user.rsvd; the only opcodes it drives are GET, PUT_FULL_DATA and PUT_PARTIAL_DATA (:173, :213, :215), so a_opcode[1] is 0. Its AXI-Lite resp is OKAY or SLVERR only (:54-55, :128-129, :195, :234), so resp[0] is 0. The TL-UL device answers from tlul_adapter_reg.sv:174-178 (or tlul_adapter_sram.sv:391-395 and tlul_err_resp.sv:67-71 behind tlul_socket_1n.sv:179-183): d_param and d_sink 0, d_opcode ACCESS_ACK or ACCESS_ACK_DATA, d_source and d_size echo the tied a_source 0 and a_size 2, so d_size[0] is 0. NOT waived: a_address, a_mask, a_data, a_opcode[0], the integrity fields, d_error and d_data."
Toggle tl_o.a_user.instr_type "logic tl_o.a_user.instr_type[3:0]"
Toggle tl_o.a_user.rsvd "logic tl_o.a_user.rsvd[9:0]"
Toggle tl_o.a_source "logic tl_o.a_source[7:0]"
Toggle tl_o.a_size "logic tl_o.a_size[1:0]"
Toggle tl_o.a_param "logic tl_o.a_param[2:0]"
Toggle tl_o.a_opcode [1] "logic tl_o.a_opcode[2:0]"
Toggle tl_i.d_sink "logic tl_i.d_sink[0:0]"
Toggle tl_i.d_param "logic tl_i.d_param[2:0]"
Toggle tl_i.d_source "logic tl_i.d_source[7:0]"
Toggle tl_i.d_size [0] "logic tl_i.d_size[1:0]"
Toggle tl_i.d_opcode [2:1] "logic tl_i.d_opcode[2:0]"
Toggle axi_lite_rsp_o.r.resp [0] "logic axi_lite_rsp_o.r.resp[1:0]"
Toggle axi_lite_rsp_o.b.resp [0] "logic axi_lite_rsp_o.b.resp[1:0]"

CHECKSUM: "2097437693 2552262841"
INSTANCE: sep_uvm_top.u_dut.u_sep.u_sep_dma_wrap.u_axi_lite_to_tlul_reg
ANNOTATION: "SEP-A2T-TIED: axi_lite_to_tlul.sv:132-134 start tl_o at 0, set a_size 2 and instr_type MuBi4False, and never assign a_param, a_source or a_user.rsvd; the only opcodes it drives are GET, PUT_FULL_DATA and PUT_PARTIAL_DATA (:173, :213, :215), so a_opcode[1] is 0. Its AXI-Lite resp is OKAY or SLVERR only (:54-55, :128-129, :195, :234), so resp[0] is 0. The TL-UL device answers from tlul_adapter_reg.sv:174-178 (or tlul_adapter_sram.sv:391-395 and tlul_err_resp.sv:67-71 behind tlul_socket_1n.sv:179-183): d_param and d_sink 0, d_opcode ACCESS_ACK or ACCESS_ACK_DATA, d_source and d_size echo the tied a_source 0 and a_size 2, so d_size[0] is 0. NOT waived: a_address, a_mask, a_data, a_opcode[0], the integrity fields, d_error and d_data."
Toggle tl_o.a_user.instr_type "logic tl_o.a_user.instr_type[3:0]"
Toggle tl_o.a_user.rsvd "logic tl_o.a_user.rsvd[9:0]"
Toggle tl_o.a_source "logic tl_o.a_source[7:0]"
Toggle tl_o.a_size "logic tl_o.a_size[1:0]"
Toggle tl_o.a_param "logic tl_o.a_param[2:0]"
Toggle tl_o.a_opcode [1] "logic tl_o.a_opcode[2:0]"
Toggle tl_i.d_sink "logic tl_i.d_sink[0:0]"
Toggle tl_i.d_param "logic tl_i.d_param[2:0]"
Toggle tl_i.d_source "logic tl_i.d_source[7:0]"
Toggle tl_i.d_size [0] "logic tl_i.d_size[1:0]"
Toggle tl_i.d_opcode [2:1] "logic tl_i.d_opcode[2:0]"
Toggle axi_lite_rsp_o.r.resp [0] "logic axi_lite_rsp_o.r.resp[1:0]"
Toggle axi_lite_rsp_o.b.resp [0] "logic axi_lite_rsp_o.b.resp[1:0]"

CHECKSUM: "2097437693 2552262841"
INSTANCE: sep_uvm_top.u_dut.u_sep.u_sep_io.u_sep_ot_spi_wrap.u_spi_axi_lite_to_tlul
ANNOTATION: "SEP-SPI-ADDR-MASK: sep_ot_spi_wrap.sv:75-86 AND both AXI-Lite addresses with SpiAddrMask = (1 << spi_host_reg_pkg::BlockAw) - 1, and BlockAw is 6 (spi_host_reg_pkg.sv:17), so address bits [31:6] are 0 on every path into the bridge. NOT waived: bits [5:0], which select the spi_host register."
Toggle axi_lite_req_i.ar.addr [31:6] "logic axi_lite_req_i.ar.addr[31:0]"
Toggle axi_lite_req_i.aw.addr [31:6] "logic axi_lite_req_i.aw.addr[31:0]"
Toggle tl_o.a_address [31:6] "logic tl_o.a_address[31:0]"
Toggle req_addr_q [31:6] "logic req_addr_q[31:0]"
Toggle req_addr_d [31:6] "logic req_addr_d[31:0]"

CHECKSUM: "3927392748 3613800401"
INSTANCE: sep_uvm_top.u_dut.u_sep.u_sep_io.u_sep_ot_spi_wrap
ANNOTATION: "SEP-SPI-ADDR-MASK: sep_ot_spi_wrap.sv:75-86 AND both AXI-Lite addresses with SpiAddrMask = (1 << spi_host_reg_pkg::BlockAw) - 1, and BlockAw is 6 (spi_host_reg_pkg.sv:17), so address bits [31:6] are 0 on every path into the bridge. NOT waived: bits [5:0], which select the spi_host register."
Toggle axil_req_masked.ar.addr [31:6] "logic axil_req_masked.ar.addr[31:0]"
Toggle axil_req_masked.aw.addr [31:6] "logic axil_req_masked.aw.addr[31:0]"
Toggle tl_req.a_address [31:6] "logic tl_req.a_address[31:0]"

CHECKSUM: "3927392748 3613800401"
INSTANCE: sep_uvm_top.u_dut.u_sep.u_sep_io.u_sep_ot_spi_wrap
ANNOTATION: "SEP-A2T-TIED: axi_lite_to_tlul.sv:132-134 start tl_o at 0, set a_size 2 and instr_type MuBi4False, and never assign a_param, a_source or a_user.rsvd; the only opcodes it drives are GET, PUT_FULL_DATA and PUT_PARTIAL_DATA (:173, :213, :215), so a_opcode[1] is 0. Its AXI-Lite resp is OKAY or SLVERR only (:54-55, :128-129, :195, :234), so resp[0] is 0. The TL-UL device answers from tlul_adapter_reg.sv:174-178 (or tlul_adapter_sram.sv:391-395 and tlul_err_resp.sv:67-71 behind tlul_socket_1n.sv:179-183): d_param and d_sink 0, d_opcode ACCESS_ACK or ACCESS_ACK_DATA, d_source and d_size echo the tied a_source 0 and a_size 2, so d_size[0] is 0. NOT waived: a_address, a_mask, a_data, a_opcode[0], the integrity fields, d_error and d_data."
Toggle tl_req.a_user.instr_type "logic tl_req.a_user.instr_type[3:0]"
Toggle tl_req.a_user.rsvd "logic tl_req.a_user.rsvd[9:0]"
Toggle tl_req.a_source "logic tl_req.a_source[7:0]"
Toggle tl_req.a_size "logic tl_req.a_size[1:0]"
Toggle tl_req.a_param "logic tl_req.a_param[2:0]"
Toggle tl_req.a_opcode [1] "logic tl_req.a_opcode[2:0]"
Toggle tl_resp.d_sink "logic tl_resp.d_sink[0:0]"
Toggle tl_resp.d_param "logic tl_resp.d_param[2:0]"
Toggle tl_resp.d_source "logic tl_resp.d_source[7:0]"
Toggle tl_resp.d_size [0] "logic tl_resp.d_size[1:0]"
Toggle tl_resp.d_opcode [2:1] "logic tl_resp.d_opcode[2:0]"
Toggle axil_resp_o.r.resp [0] "logic axil_resp_o.r.resp[1:0]"
Toggle axil_resp_o.b.resp [0] "logic axil_resp_o.b.resp[1:0]"

CHECKSUM: "883981495 759020956"
INSTANCE: sep_uvm_top.u_dut.u_sep.u_sep_wdt_wrap
ANNOTATION: "SEP-A2A-RESP-USER-TIED: the B/R user leaving axi_to_axi_lite is 0 on every source: axi_to_axi_lite.sv:157-170 default '0, axi_atop_filter.sv:220 and :287 inject '0, axi_err_slv.sv:142 and :193 inject '0; the 64-to-32 axi_dw_downsizer copies it (axi_dw_downsizer.sv:594, :737) or starts from '0 (:386, :561). Its resp[0] is 0 because the bridge below returns OKAY or SLVERR only (axi_lite_to_tlul.sv:54-55) and the injected errors are SLVERR. NOT waived: the resp at the downsizer output, which axi_dw_downsizer.sv:408 and :491 seed with EXOKAY."
Toggle sep_wdt_tlul_axi_resp.r.user "logic sep_wdt_tlul_axi_resp.r.user[11:0]"
Toggle sep_wdt_tlul_axi_resp.b.user "logic sep_wdt_tlul_axi_resp.b.user[11:0]"
Toggle sep_wdt_tlul_axi_resp.r.resp [0] "logic sep_wdt_tlul_axi_resp.r.resp[1:0]"
Toggle sep_wdt_tlul_axi_resp.b.resp [0] "logic sep_wdt_tlul_axi_resp.b.resp[1:0]"
Toggle axi_lite_resp.r.resp [0] "logic axi_lite_resp.r.resp[1:0]"
Toggle axi_lite_resp.b.resp [0] "logic axi_lite_resp.b.resp[1:0]"
Toggle sep_wdt_axi_resp_o.r.user "logic sep_wdt_axi_resp_o.r.user[11:0]"
Toggle sep_wdt_axi_resp_o.b.user "logic sep_wdt_axi_resp_o.b.user[11:0]"

CHECKSUM: "883981495 759020956"
INSTANCE: sep_uvm_top.u_dut.u_sep.u_sep_wdt_wrap
ANNOTATION: "SEP-A2T-TIED: axi_lite_to_tlul.sv:132-134 start tl_o at 0, set a_size 2 and instr_type MuBi4False, and never assign a_param, a_source or a_user.rsvd; the only opcodes it drives are GET, PUT_FULL_DATA and PUT_PARTIAL_DATA (:173, :213, :215), so a_opcode[1] is 0. Its AXI-Lite resp is OKAY or SLVERR only (:54-55, :128-129, :195, :234), so resp[0] is 0. The TL-UL device answers from tlul_adapter_reg.sv:174-178 (or tlul_adapter_sram.sv:391-395 and tlul_err_resp.sv:67-71 behind tlul_socket_1n.sv:179-183): d_param and d_sink 0, d_opcode ACCESS_ACK or ACCESS_ACK_DATA, d_source and d_size echo the tied a_source 0 and a_size 2, so d_size[0] is 0. NOT waived: a_address, a_mask, a_data, a_opcode[0], the integrity fields, d_error and d_data."
Toggle tl_d_i.a_user.instr_type "logic tl_d_i.a_user.instr_type[3:0]"
Toggle tl_d_i.a_user.rsvd "logic tl_d_i.a_user.rsvd[9:0]"
Toggle tl_d_i.a_source "logic tl_d_i.a_source[7:0]"
Toggle tl_d_i.a_size "logic tl_d_i.a_size[1:0]"
Toggle tl_d_i.a_param "logic tl_d_i.a_param[2:0]"
Toggle tl_d_i.a_opcode [1] "logic tl_d_i.a_opcode[2:0]"
Toggle tl_d_o.d_sink "logic tl_d_o.d_sink[0:0]"
Toggle tl_d_o.d_param "logic tl_d_o.d_param[2:0]"
Toggle tl_d_o.d_source "logic tl_d_o.d_source[7:0]"
Toggle tl_d_o.d_size [0] "logic tl_d_o.d_size[1:0]"
Toggle tl_d_o.d_opcode [2:1] "logic tl_d_o.d_opcode[2:0]"

CHECKSUM: "883981495 759020956"
INSTANCE: sep_uvm_top.u_dut.u_sep.u_sep_wdt_wrap
ANNOTATION: "SEP-WDT-ALERT-PING-TIED: sep_wdt_wrap.sv:193 ties ping_req_i to 1'b0 on the alert receiver, so the ping wires of its rx struct cannot move. NOT waived: alert_p and ack_p, which move when the timer raises an alert -- a fault-injection gap."
Toggle wdt_alert_rx[0].ping_p "logic wdt_alert_rx[0].ping_p"
Toggle wdt_alert_rx[0].ping_n "logic wdt_alert_rx[0].ping_n"

CHECKSUM: "828256374 178008815"
INSTANCE: sep_uvm_top.u_dut.u_sep.u_sep_io
ANNOTATION: "SEP-IO-ERRSLV-CONST: axil_resps[1] is prim_axi_lite_err_slv (sep_io.sv:190-204, RESP DECERR, RESP_DATA 32'hBADCAB1E). axi_err_slv.sv:142-145 and :193-197 drive r.data, r.resp and b.resp to those constants on every cycle and axi_lite_to_axi.sv:70-86 pass them through. NOT waived: the valid/ready handshakes, which an access to an unmapped IO address moves."
Toggle axil_resps[1].r.data "logic axil_resps[1].r.data[31:0]"
Toggle axil_resps[1].r.resp "logic axil_resps[1].r.resp[1:0]"
Toggle axil_resps[1].b.resp "logic axil_resps[1].b.resp[1:0]"

CHECKSUM: "828256374 178008815"
INSTANCE: sep_uvm_top.u_dut.u_sep.u_sep_io
ANNOTATION: "SEP-A2A-RESP-USER-TIED: the B/R user leaving axi_to_axi_lite is 0 on every source: axi_to_axi_lite.sv:157-170 default '0, axi_atop_filter.sv:220 and :287 inject '0, axi_err_slv.sv:142 and :193 inject '0; the 64-to-32 axi_dw_downsizer copies it (axi_dw_downsizer.sv:594, :737) or starts from '0 (:386, :561). Its resp[0] is 0 because the bridge below returns OKAY or SLVERR only (axi_lite_to_tlul.sv:54-55) and the injected errors are SLVERR. NOT waived: the resp at the downsizer output, which axi_dw_downsizer.sv:408 and :491 seed with EXOKAY."
Toggle axil_resps[0].r.resp [0] "logic axil_resps[0].r.resp[1:0]"
Toggle axil_resps[0].b.resp [0] "logic axil_resps[0].b.resp[1:0]"
Toggle axi_resp.r.user "logic axi_resp.r.user[11:0]"
Toggle axi_resp.b.user "logic axi_resp.b.user[11:0]"
Toggle sep_io_axi_resp_o.r.user "logic sep_io_axi_resp_o.r.user[11:0]"
Toggle sep_io_axi_resp_o.b.user "logic sep_io_axi_resp_o.b.user[11:0]"

CHECKSUM: "834177952 2569679982"
INSTANCE: sep_uvm_top.u_dut.u_sep.u_sep_io.u_axil_err_slv
ANNOTATION: "SEP-ERRSLV-INTERNAL-TIED: inside prim_axi_lite_err_slv, axi_lite_to_axi.sv:39-67 set burst FIXED, size log2(4), wlast 1 and id, len, lock, qos, region, atop and user to 0, and prim_axi_lite_err_slv.sv:82-83 feed cache 0. axi_err_slv.sv:142-145 and :193-197 drive r.data RESP_DATA, r.resp and b.resp RESP, and r/b user 0; the 1-bit id is the tied 0. NOT waived: addr, prot, data, strobe and every valid/ready, which an unmapped access moves."
Toggle axi_req.ar.id "logic axi_req.ar.id"
Toggle axi_req.ar.len "logic axi_req.ar.len[7:0]"
Toggle axi_req.ar.lock "logic axi_req.ar.lock"
Toggle axi_req.ar.qos "logic axi_req.ar.qos[3:0]"
Toggle axi_req.ar.region "logic axi_req.ar.region[3:0]"
Toggle axi_req.ar.user "logic axi_req.ar.user"
Toggle axi_req.ar.size "logic axi_req.ar.size[2:0]"
Toggle axi_req.ar.burst "logic axi_req.ar.burst[1:0]"
Toggle axi_req.ar.cache "logic axi_req.ar.cache[3:0]"
Toggle axi_req.aw.id "logic axi_req.aw.id"
Toggle axi_req.aw.len "logic axi_req.aw.len[7:0]"
Toggle axi_req.aw.lock "logic axi_req.aw.lock"
Toggle axi_req.aw.qos "logic axi_req.aw.qos[3:0]"
Toggle axi_req.aw.region "logic axi_req.aw.region[3:0]"
Toggle axi_req.aw.user "logic axi_req.aw.user"
Toggle axi_req.aw.size "logic axi_req.aw.size[2:0]"
Toggle axi_req.aw.burst "logic axi_req.aw.burst[1:0]"
Toggle axi_req.aw.cache "logic axi_req.aw.cache[3:0]"
Toggle axi_req.aw.atop "logic axi_req.aw.atop[5:0]"
Toggle axi_req.w.user "logic axi_req.w.user"
Toggle axi_req.w.last "logic axi_req.w.last"
Toggle axi_resp.r.user "logic axi_resp.r.user"
Toggle axi_resp.b.user "logic axi_resp.b.user"
Toggle axi_resp.r.data "logic axi_resp.r.data[31:0]"
Toggle axi_resp.r.resp "logic axi_resp.r.resp[1:0]"
Toggle axi_resp.b.resp "logic axi_resp.b.resp[1:0]"
Toggle axi_resp.r.id "logic axi_resp.r.id"
Toggle axi_resp.b.id "logic axi_resp.b.id"
Toggle axil_resp_o.r.data "logic axil_resp_o.r.data[31:0]"
Toggle axil_resp_o.r.resp "logic axil_resp_o.r.resp[1:0]"
Toggle axil_resp_o.b.resp "logic axil_resp_o.b.resp[1:0]"

CHECKSUM: "3519459534 3972236298"
INSTANCE: sep_uvm_top.u_dut.u_sep.u_sep_dma_wrap
ANNOTATION: "SEP-DMA-MASTER-TIED: only the secure DMA host port drives this path. axi_lite_to_axi.sv:39-67 set burst FIXED, size log2(4), wlast 1 and id, len, lock, qos, region, atop and user to 0; sep_dma_wrap.sv:283-284 feed cache 4'b0000; the upsizer and the remap pass them unchanged. NOT waived: addr, size, prot and the W data/strobe."
Toggle axi32_mst_req.aw.id "logic axi32_mst_req.aw.id[2:0]"
Toggle axi32_mst_req.aw.len "logic axi32_mst_req.aw.len[7:0]"
Toggle axi32_mst_req.aw.burst "logic axi32_mst_req.aw.burst[1:0]"
Toggle axi32_mst_req.aw.lock "logic axi32_mst_req.aw.lock"
Toggle axi32_mst_req.aw.cache "logic axi32_mst_req.aw.cache[3:0]"
Toggle axi32_mst_req.aw.qos "logic axi32_mst_req.aw.qos[3:0]"
Toggle axi32_mst_req.aw.region "logic axi32_mst_req.aw.region[3:0]"
Toggle axi32_mst_req.aw.atop "logic axi32_mst_req.aw.atop[5:0]"
Toggle axi32_mst_req.aw.user "logic axi32_mst_req.aw.user[11:0]"
Toggle axi32_mst_req.aw.size "logic axi32_mst_req.aw.size[2:0]"
Toggle axi32_mst_req.ar.id "logic axi32_mst_req.ar.id[2:0]"
Toggle axi32_mst_req.ar.len "logic axi32_mst_req.ar.len[7:0]"
Toggle axi32_mst_req.ar.burst "logic axi32_mst_req.ar.burst[1:0]"
Toggle axi32_mst_req.ar.lock "logic axi32_mst_req.ar.lock"
Toggle axi32_mst_req.ar.cache "logic axi32_mst_req.ar.cache[3:0]"
Toggle axi32_mst_req.ar.qos "logic axi32_mst_req.ar.qos[3:0]"
Toggle axi32_mst_req.ar.region "logic axi32_mst_req.ar.region[3:0]"
Toggle axi32_mst_req.ar.user "logic axi32_mst_req.ar.user[11:0]"
Toggle axi32_mst_req.ar.size "logic axi32_mst_req.ar.size[2:0]"
Toggle axi32_mst_req.w.user "logic axi32_mst_req.w.user[11:0]"
Toggle axi32_mst_req.w.last "logic axi32_mst_req.w.last"

CHECKSUM: "3519459534 3972236298"
INSTANCE: sep_uvm_top.u_dut.u_sep.u_sep_dma_wrap
ANNOTATION: "SEP-A2A-RESP-USER-TIED: the B/R user leaving axi_to_axi_lite is 0 on every source: axi_to_axi_lite.sv:157-170 default '0, axi_atop_filter.sv:220 and :287 inject '0, axi_err_slv.sv:142 and :193 inject '0; the 64-to-32 axi_dw_downsizer copies it (axi_dw_downsizer.sv:594, :737) or starts from '0 (:386, :561). Its resp[0] is 0 because the bridge below returns OKAY or SLVERR only (axi_lite_to_tlul.sv:54-55) and the injected errors are SLVERR. NOT waived: the resp at the downsizer output, which axi_dw_downsizer.sv:408 and :491 seed with EXOKAY."
Toggle axi32_slv_resp.r.user "logic axi32_slv_resp.r.user[11:0]"
Toggle axi32_slv_resp.b.user "logic axi32_slv_resp.b.user[11:0]"
Toggle axi32_slv_resp.r.resp [0] "logic axi32_slv_resp.r.resp[1:0]"
Toggle axi32_slv_resp.b.resp [0] "logic axi32_slv_resp.b.resp[1:0]"
Toggle axi_lite_slv_resp.r.resp [0] "logic axi_lite_slv_resp.r.resp[1:0]"
Toggle axi_lite_slv_resp.b.resp [0] "logic axi_lite_slv_resp.b.resp[1:0]"
Toggle reg_resp_o.r.user "logic reg_resp_o.r.user[11:0]"
Toggle reg_resp_o.b.user "logic reg_resp_o.b.user[11:0]"

CHECKSUM: "3519459534 3972236298"
INSTANCE: sep_uvm_top.u_dut.u_sep.u_sep_dma_wrap
ANNOTATION: "SEP-A2T-TIED: axi_lite_to_tlul.sv:132-134 start tl_o at 0, set a_size 2 and instr_type MuBi4False, and never assign a_param, a_source or a_user.rsvd; the only opcodes it drives are GET, PUT_FULL_DATA and PUT_PARTIAL_DATA (:173, :213, :215), so a_opcode[1] is 0. Its AXI-Lite resp is OKAY or SLVERR only (:54-55, :128-129, :195, :234), so resp[0] is 0. The TL-UL device answers from tlul_adapter_reg.sv:174-178 (or tlul_adapter_sram.sv:391-395 and tlul_err_resp.sv:67-71 behind tlul_socket_1n.sv:179-183): d_param and d_sink 0, d_opcode ACCESS_ACK or ACCESS_ACK_DATA, d_source and d_size echo the tied a_source 0 and a_size 2, so d_size[0] is 0. NOT waived: a_address, a_mask, a_data, a_opcode[0], the integrity fields, d_error and d_data."
Toggle tl_d_i.a_user.instr_type "logic tl_d_i.a_user.instr_type[3:0]"
Toggle tl_d_i.a_user.rsvd "logic tl_d_i.a_user.rsvd[9:0]"
Toggle tl_d_i.a_source "logic tl_d_i.a_source[7:0]"
Toggle tl_d_i.a_size "logic tl_d_i.a_size[1:0]"
Toggle tl_d_i.a_param "logic tl_d_i.a_param[2:0]"
Toggle tl_d_i.a_opcode [1] "logic tl_d_i.a_opcode[2:0]"
Toggle tl_d_o.d_sink "logic tl_d_o.d_sink[0:0]"
Toggle tl_d_o.d_param "logic tl_d_o.d_param[2:0]"
Toggle tl_d_o.d_source "logic tl_d_o.d_source[7:0]"
Toggle tl_d_o.d_size [0] "logic tl_d_o.d_size[1:0]"
Toggle tl_d_o.d_opcode [2:1] "logic tl_d_o.d_opcode[2:0]"

CHECKSUM: "3519459534 3972236298"
INSTANCE: sep_uvm_top.u_dut.u_sep.u_sep_dma_wrap
ANNOTATION: "SEP-DMA-HOST-TL-TIED: host_tl_h_o comes from tlul_adapter_host in secure_dma. tlul_adapter_host.sv:108-118 drive a_param 0, a_size WordSize, a_address[1:0] 0, d_ready 1 and opcode GET/PUT_FULL/PUT_PARTIAL (a_opcode[1] 0); MAX_REQS = NUM_MAX_OUTSTANDING_REQS = 1 (secure_dma_pkg.sv:103) ties a_source to 0 (tlul_adapter_host.sv:69-70); instr_type is MuBi4False and rsvd is TL_USER_RSVD = '0 (sep.sv:1189). host_tl_h_i comes from tlul_to_axi_lite.sv:151-153 and :255-264: d_param and d_sink 0, d_source and d_size echo the tied a_source and a_size, d_opcode ACCESS_ACK or ACCESS_ACK_DATA. NOT waived: address, data, mask, d_error and the integrity fields."
Toggle host_tl_h_o.a_user.instr_type "logic host_tl_h_o.a_user.instr_type[3:0]"
Toggle host_tl_h_o.a_user.rsvd "logic host_tl_h_o.a_user.rsvd[9:0]"
Toggle host_tl_h_o.a_address [1:0] "logic host_tl_h_o.a_address[31:0]"
Toggle host_tl_h_o.a_source "logic host_tl_h_o.a_source[7:0]"
Toggle host_tl_h_o.a_size "logic host_tl_h_o.a_size[1:0]"
Toggle host_tl_h_o.a_param "logic host_tl_h_o.a_param[2:0]"
Toggle host_tl_h_o.a_opcode [1] "logic host_tl_h_o.a_opcode[2:0]"
Toggle host_tl_h_o.d_ready "logic host_tl_h_o.d_ready"
Toggle host_tl_h_i.d_sink "logic host_tl_h_i.d_sink[0:0]"
Toggle host_tl_h_i.d_param "logic host_tl_h_i.d_param[2:0]"
Toggle host_tl_h_i.d_source "logic host_tl_h_i.d_source[7:0]"
Toggle host_tl_h_i.d_size [0] "logic host_tl_h_i.d_size[1:0]"
Toggle host_tl_h_i.d_opcode [2:1] "logic host_tl_h_i.d_opcode[2:0]"

CHECKSUM: "2470472206 1152219882"
INSTANCE: sep_uvm_top.u_dut.u_sep.u_sep_dma_wrap.u_tlul_to_axi_lite_dma
ANNOTATION: "SEP-DMA-HOST-TL-TIED: host_tl_h_o comes from tlul_adapter_host in secure_dma. tlul_adapter_host.sv:108-118 drive a_param 0, a_size WordSize, a_address[1:0] 0, d_ready 1 and opcode GET/PUT_FULL/PUT_PARTIAL (a_opcode[1] 0); MAX_REQS = NUM_MAX_OUTSTANDING_REQS = 1 (secure_dma_pkg.sv:103) ties a_source to 0 (tlul_adapter_host.sv:69-70); instr_type is MuBi4False and rsvd is TL_USER_RSVD = '0 (sep.sv:1189). host_tl_h_i comes from tlul_to_axi_lite.sv:151-153 and :255-264: d_param and d_sink 0, d_source and d_size echo the tied a_source and a_size, d_opcode ACCESS_ACK or ACCESS_ACK_DATA. NOT waived: address, data, mask, d_error and the integrity fields."
Toggle tl_i.a_user.instr_type "logic tl_i.a_user.instr_type[3:0]"
Toggle tl_i.a_user.rsvd "logic tl_i.a_user.rsvd[9:0]"
Toggle tl_i.a_address [1:0] "logic tl_i.a_address[31:0]"
Toggle tl_i.a_source "logic tl_i.a_source[7:0]"
Toggle tl_i.a_size "logic tl_i.a_size[1:0]"
Toggle tl_i.a_param "logic tl_i.a_param[2:0]"
Toggle tl_i.a_opcode [1] "logic tl_i.a_opcode[2:0]"
Toggle tl_i.d_ready "logic tl_i.d_ready"

CHECKSUM: "888281972 1013753887"
INSTANCE: sep_uvm_top.u_dut.u_sep.u_sep_system_peripherals.u_sep_axil_mailbox
ANNOTATION: "SEP-MBX-RESP-BIT0: axi_lite_mailbox.sv:319-478 answer every access with RESP_OKAY or RESP_SLVERR only, and the 16-port axi_lite_demux has no error port (all 4-bit selects are valid ports, axi_lite_mailbox_unit.sv:74-96), so resp bit 0 (EXOKAY/DECERR) is 0 on every response net of the unit. NOT waived: resp bit 1, which a mailbox error moves."
Toggle mailbox_axi_resp_o.r.resp [0] "logic mailbox_axi_resp_o.r.resp[1:0]"
Toggle mailbox_axi_resp_o.b.resp [0] "logic mailbox_axi_resp_o.b.resp[1:0]"
Toggle mailbox_axi_resp_internal.r.resp [0] "logic mailbox_axi_resp_internal.r.resp[1:0]"
Toggle mailbox_axi_resp_internal.b.resp [0] "logic mailbox_axi_resp_internal.b.resp[1:0]"
Toggle mst_resps[0].r.resp [0] "logic mst_resps[0].r.resp[1:0]"
Toggle mst_resps[0].b.resp [0] "logic mst_resps[0].b.resp[1:0]"
Toggle mst_resps[1].r.resp [0] "logic mst_resps[1].r.resp[1:0]"
Toggle mst_resps[1].b.resp [0] "logic mst_resps[1].b.resp[1:0]"
Toggle mst_resps[2].r.resp [0] "logic mst_resps[2].r.resp[1:0]"
Toggle mst_resps[2].b.resp [0] "logic mst_resps[2].b.resp[1:0]"
Toggle mst_resps[3].r.resp [0] "logic mst_resps[3].r.resp[1:0]"
Toggle mst_resps[3].b.resp [0] "logic mst_resps[3].b.resp[1:0]"
Toggle mst_resps[4].r.resp [0] "logic mst_resps[4].r.resp[1:0]"
Toggle mst_resps[4].b.resp [0] "logic mst_resps[4].b.resp[1:0]"
Toggle mst_resps[5].r.resp [0] "logic mst_resps[5].r.resp[1:0]"
Toggle mst_resps[5].b.resp [0] "logic mst_resps[5].b.resp[1:0]"
Toggle mst_resps[6].r.resp [0] "logic mst_resps[6].r.resp[1:0]"
Toggle mst_resps[6].b.resp [0] "logic mst_resps[6].b.resp[1:0]"
Toggle mst_resps[7].r.resp [0] "logic mst_resps[7].r.resp[1:0]"
Toggle mst_resps[7].b.resp [0] "logic mst_resps[7].b.resp[1:0]"
Toggle mst_resps[8].r.resp [0] "logic mst_resps[8].r.resp[1:0]"
Toggle mst_resps[8].b.resp [0] "logic mst_resps[8].b.resp[1:0]"
Toggle mst_resps[9].r.resp [0] "logic mst_resps[9].r.resp[1:0]"
Toggle mst_resps[9].b.resp [0] "logic mst_resps[9].b.resp[1:0]"
Toggle mst_resps[10].r.resp [0] "logic mst_resps[10].r.resp[1:0]"
Toggle mst_resps[10].b.resp [0] "logic mst_resps[10].b.resp[1:0]"
Toggle mst_resps[11].r.resp [0] "logic mst_resps[11].r.resp[1:0]"
Toggle mst_resps[11].b.resp [0] "logic mst_resps[11].b.resp[1:0]"
Toggle mst_resps[12].r.resp [0] "logic mst_resps[12].r.resp[1:0]"
Toggle mst_resps[12].b.resp [0] "logic mst_resps[12].b.resp[1:0]"
Toggle mst_resps[13].r.resp [0] "logic mst_resps[13].r.resp[1:0]"
Toggle mst_resps[13].b.resp [0] "logic mst_resps[13].b.resp[1:0]"
Toggle mst_resps[14].r.resp [0] "logic mst_resps[14].r.resp[1:0]"
Toggle mst_resps[14].b.resp [0] "logic mst_resps[14].b.resp[1:0]"
Toggle mst_resps[15].r.resp [0] "logic mst_resps[15].r.resp[1:0]"
Toggle mst_resps[15].b.resp [0] "logic mst_resps[15].b.resp[1:0]"
Toggle gen_mailbox[0].inbound_rsp.r.resp [0] "logic gen_mailbox[0].inbound_rsp.r.resp[1:0]"
Toggle gen_mailbox[0].inbound_rsp.b.resp [0] "logic gen_mailbox[0].inbound_rsp.b.resp[1:0]"
Toggle gen_mailbox[0].outbound_rsp.r.resp [0] "logic gen_mailbox[0].outbound_rsp.r.resp[1:0]"
Toggle gen_mailbox[0].outbound_rsp.b.resp [0] "logic gen_mailbox[0].outbound_rsp.b.resp[1:0]"
Toggle gen_mailbox[1].inbound_rsp.r.resp [0] "logic gen_mailbox[1].inbound_rsp.r.resp[1:0]"
Toggle gen_mailbox[1].inbound_rsp.b.resp [0] "logic gen_mailbox[1].inbound_rsp.b.resp[1:0]"
Toggle gen_mailbox[1].outbound_rsp.r.resp [0] "logic gen_mailbox[1].outbound_rsp.r.resp[1:0]"
Toggle gen_mailbox[1].outbound_rsp.b.resp [0] "logic gen_mailbox[1].outbound_rsp.b.resp[1:0]"
Toggle gen_mailbox[2].inbound_rsp.r.resp [0] "logic gen_mailbox[2].inbound_rsp.r.resp[1:0]"
Toggle gen_mailbox[2].inbound_rsp.b.resp [0] "logic gen_mailbox[2].inbound_rsp.b.resp[1:0]"
Toggle gen_mailbox[2].outbound_rsp.r.resp [0] "logic gen_mailbox[2].outbound_rsp.r.resp[1:0]"
Toggle gen_mailbox[2].outbound_rsp.b.resp [0] "logic gen_mailbox[2].outbound_rsp.b.resp[1:0]"
Toggle gen_mailbox[3].inbound_rsp.r.resp [0] "logic gen_mailbox[3].inbound_rsp.r.resp[1:0]"
Toggle gen_mailbox[3].inbound_rsp.b.resp [0] "logic gen_mailbox[3].inbound_rsp.b.resp[1:0]"
Toggle gen_mailbox[3].outbound_rsp.r.resp [0] "logic gen_mailbox[3].outbound_rsp.r.resp[1:0]"
Toggle gen_mailbox[3].outbound_rsp.b.resp [0] "logic gen_mailbox[3].outbound_rsp.b.resp[1:0]"
Toggle gen_mailbox[4].inbound_rsp.r.resp [0] "logic gen_mailbox[4].inbound_rsp.r.resp[1:0]"
Toggle gen_mailbox[4].inbound_rsp.b.resp [0] "logic gen_mailbox[4].inbound_rsp.b.resp[1:0]"
Toggle gen_mailbox[4].outbound_rsp.r.resp [0] "logic gen_mailbox[4].outbound_rsp.r.resp[1:0]"
Toggle gen_mailbox[4].outbound_rsp.b.resp [0] "logic gen_mailbox[4].outbound_rsp.b.resp[1:0]"
Toggle gen_mailbox[5].inbound_rsp.r.resp [0] "logic gen_mailbox[5].inbound_rsp.r.resp[1:0]"
Toggle gen_mailbox[5].inbound_rsp.b.resp [0] "logic gen_mailbox[5].inbound_rsp.b.resp[1:0]"
Toggle gen_mailbox[5].outbound_rsp.r.resp [0] "logic gen_mailbox[5].outbound_rsp.r.resp[1:0]"
Toggle gen_mailbox[5].outbound_rsp.b.resp [0] "logic gen_mailbox[5].outbound_rsp.b.resp[1:0]"
Toggle gen_mailbox[6].inbound_rsp.r.resp [0] "logic gen_mailbox[6].inbound_rsp.r.resp[1:0]"
Toggle gen_mailbox[6].inbound_rsp.b.resp [0] "logic gen_mailbox[6].inbound_rsp.b.resp[1:0]"
Toggle gen_mailbox[6].outbound_rsp.r.resp [0] "logic gen_mailbox[6].outbound_rsp.r.resp[1:0]"
Toggle gen_mailbox[6].outbound_rsp.b.resp [0] "logic gen_mailbox[6].outbound_rsp.b.resp[1:0]"
Toggle gen_mailbox[7].inbound_rsp.r.resp [0] "logic gen_mailbox[7].inbound_rsp.r.resp[1:0]"
Toggle gen_mailbox[7].inbound_rsp.b.resp [0] "logic gen_mailbox[7].inbound_rsp.b.resp[1:0]"
Toggle gen_mailbox[7].outbound_rsp.r.resp [0] "logic gen_mailbox[7].outbound_rsp.r.resp[1:0]"
Toggle gen_mailbox[7].outbound_rsp.b.resp [0] "logic gen_mailbox[7].outbound_rsp.b.resp[1:0]"

CHECKSUM: "2905179362 2615609264"
INSTANCE: sep_uvm_top.u_dut.u_sep.u_sep_system_peripherals.u_sep_system_csr.u_sep_cpu_ctrl_reg
ANNOTATION: "SEP-REGBLOCK-A1-NOSTALL-COND: the PeakRDL cpuif hardwires cpuif_req_stall_rd and cpuif_req_stall_wr to 0 (sep_cpu_ctrl_reg.sv:221-222), so no vector with a stall term at 1 can occur. Only those vectors are listed. NOT waived: the cpuif_req and cpuif_req_is_wr vectors."
Condition 226 "1986659825" "(cpuif_req & ( ! (((!cpuif_req_is_wr)) & cpuif_req_stall_rd) ) & ( ! (cpuif_req_is_wr & cpuif_req_stall_wr) )) 1 -1" (2 "101")
Condition 226 "1986659825" "(cpuif_req & ( ! (((!cpuif_req_is_wr)) & cpuif_req_stall_rd) ) & ( ! (cpuif_req_is_wr & cpuif_req_stall_wr) )) 1 -1" (3 "110")
Condition 227 "2444199068" "( ! (((!cpuif_req_is_wr)) & cpuif_req_stall_rd) ) 1 -1" (2 "1")
Condition 228 "1170080477" "(((!cpuif_req_is_wr)) & cpuif_req_stall_rd) 1 -1" (1 "01")
Condition 228 "1170080477" "(((!cpuif_req_is_wr)) & cpuif_req_stall_rd) 1 -1" (3 "11")
Condition 229 "333285110" "( ! (cpuif_req_is_wr & cpuif_req_stall_wr) ) 1 -1" (2 "1")
Condition 230 "3073733329" "(cpuif_req_is_wr & cpuif_req_stall_wr) 1 -1" (1 "01")
Condition 230 "3073733329" "(cpuif_req_is_wr & cpuif_req_stall_wr) 1 -1" (3 "11")

CHECKSUM: "3743219407 3214460824"
INSTANCE: sep_uvm_top.u_dut.u_sep.u_sep_reset_ctrl.u_reg
ANNOTATION: "SEP-REGBLOCK-A1-NOSTALL-COND: the PeakRDL cpuif hardwires cpuif_req_stall_rd and cpuif_req_stall_wr to 0 (sep_reset_ctrl_reg.sv:220-221), so no vector with a stall term at 1 can occur. Only those vectors are listed. NOT waived: the cpuif_req and cpuif_req_is_wr vectors."
Condition 48 "1986659825" "(cpuif_req & ( ! (((!cpuif_req_is_wr)) & cpuif_req_stall_rd) ) & ( ! (cpuif_req_is_wr & cpuif_req_stall_wr) )) 1 -1" (2 "101")
Condition 48 "1986659825" "(cpuif_req & ( ! (((!cpuif_req_is_wr)) & cpuif_req_stall_rd) ) & ( ! (cpuif_req_is_wr & cpuif_req_stall_wr) )) 1 -1" (3 "110")
Condition 49 "2444199068" "( ! (((!cpuif_req_is_wr)) & cpuif_req_stall_rd) ) 1 -1" (2 "1")
Condition 50 "1170080477" "(((!cpuif_req_is_wr)) & cpuif_req_stall_rd) 1 -1" (1 "01")
Condition 50 "1170080477" "(((!cpuif_req_is_wr)) & cpuif_req_stall_rd) 1 -1" (3 "11")
Condition 51 "333285110" "( ! (cpuif_req_is_wr & cpuif_req_stall_wr) ) 1 -1" (2 "1")
Condition 52 "3073733329" "(cpuif_req_is_wr & cpuif_req_stall_wr) 1 -1" (1 "01")
Condition 52 "3073733329" "(cpuif_req_is_wr & cpuif_req_stall_wr) 1 -1" (3 "11")

CHECKSUM: "2097437693 17421044"
INSTANCE: sep_uvm_top.u_dut.u_sep.u_sep_wdt_wrap.u_wdt_axi_lite_to_tlul
ANNOTATION: "SEP-A2T-ACKZERO-OFF: this instance keeps ACK_ZERO_STROBE_WRITE at its default 0 (axi_lite_to_tlul.sv:30; sep_wdt_wrap.sv:137-153), so the zero-strobe early-OKAY path at :158-162 is dead by parameter: its statements, its IDLE branch arm and the IDLE->AXI_B_RESP transition cannot occur. NOT waived: the PUT_PARTIAL_DATA path and every reset-to-IDLE transition."
Block 12 "2970101142" "req_error_d = 1'b0;"

CHECKSUM: "2097437693 2178003635"
INSTANCE: sep_uvm_top.u_dut.u_sep.u_sep_wdt_wrap.u_wdt_axi_lite_to_tlul
ANNOTATION: "SEP-A2T-ACKZERO-OFF: this instance keeps ACK_ZERO_STROBE_WRITE at its default 0 (axi_lite_to_tlul.sv:30; sep_wdt_wrap.sv:137-153), so the zero-strobe early-OKAY path at :158-162 is dead by parameter: its statements, its IDLE branch arm and the IDLE->AXI_B_RESP transition cannot occur. NOT waived: the PUT_PARTIAL_DATA path and every reset-to-IDLE transition."
Branch 2 "3464338896" "state_q" (1) "state_q IDLE ,0,1,1,-,-,-,-,-,-,-,-,-"

CHECKSUM: "2097437693 3453034612"
INSTANCE: sep_uvm_top.u_dut.u_sep.u_sep_wdt_wrap.u_wdt_axi_lite_to_tlul
ANNOTATION: "SEP-A2T-ACKZERO-OFF: this instance keeps ACK_ZERO_STROBE_WRITE at its default 0 (axi_lite_to_tlul.sv:30; sep_wdt_wrap.sv:137-153), so the zero-strobe early-OKAY path at :158-162 is dead by parameter: its statements, its IDLE branch arm and the IDLE->AXI_B_RESP transition cannot occur. NOT waived: the PUT_PARTIAL_DATA path and every reset-to-IDLE transition."
Fsm state_q "3453034612"
Transition IDLE->AXI_B_RESP "0->6"

CHECKSUM: "2097437693 17421044"
INSTANCE: sep_uvm_top.u_dut.u_sep.u_sep_dma_wrap.u_axi_lite_to_tlul_reg
ANNOTATION: "SEP-A2T-ACKZERO-OFF: this instance keeps ACK_ZERO_STROBE_WRITE at its default 0 (axi_lite_to_tlul.sv:30; sep_dma_wrap.sv:227-245), so the zero-strobe early-OKAY path at :158-162 is dead by parameter: its statements, its IDLE branch arm and the IDLE->AXI_B_RESP transition cannot occur. NOT waived: the PUT_PARTIAL_DATA path and every reset-to-IDLE transition."
Block 12 "2970101142" "req_error_d = 1'b0;"

CHECKSUM: "2097437693 2178003635"
INSTANCE: sep_uvm_top.u_dut.u_sep.u_sep_dma_wrap.u_axi_lite_to_tlul_reg
ANNOTATION: "SEP-A2T-ACKZERO-OFF: this instance keeps ACK_ZERO_STROBE_WRITE at its default 0 (axi_lite_to_tlul.sv:30; sep_dma_wrap.sv:227-245), so the zero-strobe early-OKAY path at :158-162 is dead by parameter: its statements, its IDLE branch arm and the IDLE->AXI_B_RESP transition cannot occur. NOT waived: the PUT_PARTIAL_DATA path and every reset-to-IDLE transition."
Branch 2 "3464338896" "state_q" (1) "state_q IDLE ,0,1,1,-,-,-,-,-,-,-,-,-"

CHECKSUM: "2097437693 3453034612"
INSTANCE: sep_uvm_top.u_dut.u_sep.u_sep_dma_wrap.u_axi_lite_to_tlul_reg
ANNOTATION: "SEP-A2T-ACKZERO-OFF: this instance keeps ACK_ZERO_STROBE_WRITE at its default 0 (axi_lite_to_tlul.sv:30; sep_dma_wrap.sv:227-245), so the zero-strobe early-OKAY path at :158-162 is dead by parameter: its statements, its IDLE branch arm and the IDLE->AXI_B_RESP transition cannot occur. NOT waived: the PUT_PARTIAL_DATA path and every reset-to-IDLE transition."
Fsm state_q "3453034612"
Transition IDLE->AXI_B_RESP "0->6"

CHECKSUM: "2097437693 17421044"
INSTANCE: sep_uvm_top.u_dut.u_sep.u_sep_wdt_wrap.u_wdt_axi_lite_to_tlul
ANNOTATION: "SEP-INTG-GEN-ON: ENABLE_CMD_INTG_GEN and ENABLE_DATA_INTG_GEN are 1 for this instance (defaults at axi_lite_to_tlul.sv:28-29, sep_wdt_wrap.sv:137-153), so the else arms that drive the all-ones integrity placeholder are dead by parameter. NOT waived: the generate-on arms."
Block 39 "915842203" "cmd_intg = {tlul_pkg::H2D_CMD_INTG_WIDTH {1'b1}};"

CHECKSUM: "2097437693 17421044"
INSTANCE: sep_uvm_top.u_dut.u_sep.u_sep_wdt_wrap.u_wdt_axi_lite_to_tlul
ANNOTATION: "SEP-INTG-GEN-ON: ENABLE_CMD_INTG_GEN and ENABLE_DATA_INTG_GEN are 1 for this instance (defaults at axi_lite_to_tlul.sv:28-29, sep_wdt_wrap.sv:137-153), so the else arms that drive the all-ones integrity placeholder are dead by parameter. NOT waived: the generate-on arms."
Block 42 "2397383519" "data_intg = {tlul_pkg::DATA_INTG_WIDTH {1'b1}};"

CHECKSUM: "2097437693 2178003635"
INSTANCE: sep_uvm_top.u_dut.u_sep.u_sep_wdt_wrap.u_wdt_axi_lite_to_tlul
ANNOTATION: "SEP-INTG-GEN-ON: ENABLE_CMD_INTG_GEN and ENABLE_DATA_INTG_GEN are 1 for this instance (defaults at axi_lite_to_tlul.sv:28-29, sep_wdt_wrap.sv:137-153), so the else arms that drive the all-ones integrity placeholder are dead by parameter. NOT waived: the generate-on arms."
Branch 3 "1189517418" "ENABLE_CMD_INTG_GEN" (1) "ENABLE_CMD_INTG_GEN 0"
Branch 4 "2160096988" "ENABLE_DATA_INTG_GEN" (1) "ENABLE_DATA_INTG_GEN 0"

CHECKSUM: "2097437693 17421044"
INSTANCE: sep_uvm_top.u_dut.u_sep.u_sep_io.u_sep_ot_spi_wrap.u_spi_axi_lite_to_tlul
ANNOTATION: "SEP-INTG-GEN-ON: ENABLE_CMD_INTG_GEN and ENABLE_DATA_INTG_GEN are 1 for this instance (defaults at axi_lite_to_tlul.sv:28-29, sep_ot_spi_wrap.sv:110-126), so the else arms that drive the all-ones integrity placeholder are dead by parameter. NOT waived: the generate-on arms."
Block 39 "915842203" "cmd_intg = {tlul_pkg::H2D_CMD_INTG_WIDTH {1'b1}};"

CHECKSUM: "2097437693 17421044"
INSTANCE: sep_uvm_top.u_dut.u_sep.u_sep_io.u_sep_ot_spi_wrap.u_spi_axi_lite_to_tlul
ANNOTATION: "SEP-INTG-GEN-ON: ENABLE_CMD_INTG_GEN and ENABLE_DATA_INTG_GEN are 1 for this instance (defaults at axi_lite_to_tlul.sv:28-29, sep_ot_spi_wrap.sv:110-126), so the else arms that drive the all-ones integrity placeholder are dead by parameter. NOT waived: the generate-on arms."
Block 42 "2397383519" "data_intg = {tlul_pkg::DATA_INTG_WIDTH {1'b1}};"

CHECKSUM: "2097437693 2178003635"
INSTANCE: sep_uvm_top.u_dut.u_sep.u_sep_io.u_sep_ot_spi_wrap.u_spi_axi_lite_to_tlul
ANNOTATION: "SEP-INTG-GEN-ON: ENABLE_CMD_INTG_GEN and ENABLE_DATA_INTG_GEN are 1 for this instance (defaults at axi_lite_to_tlul.sv:28-29, sep_ot_spi_wrap.sv:110-126), so the else arms that drive the all-ones integrity placeholder are dead by parameter. NOT waived: the generate-on arms."
Branch 3 "1189517418" "ENABLE_CMD_INTG_GEN" (1) "ENABLE_CMD_INTG_GEN 0"
Branch 4 "2160096988" "ENABLE_DATA_INTG_GEN" (1) "ENABLE_DATA_INTG_GEN 0"

CHECKSUM: "2097437693 17421044"
INSTANCE: sep_uvm_top.u_dut.u_sep.u_sep_dma_wrap.u_axi_lite_to_tlul_reg
ANNOTATION: "SEP-INTG-GEN-ON: ENABLE_CMD_INTG_GEN and ENABLE_DATA_INTG_GEN are 1 for this instance (hw/sys/sep/rtl/sep_dma_wrap.sv:234-235 from ENABLE_DATA_INTG_GEN = 1, sep.sv:1187), so the else arms that drive the all-ones integrity placeholder are dead by parameter. NOT waived: the generate-on arms."
Block 39 "915842203" "cmd_intg = {tlul_pkg::H2D_CMD_INTG_WIDTH {1'b1}};"

CHECKSUM: "2097437693 17421044"
INSTANCE: sep_uvm_top.u_dut.u_sep.u_sep_dma_wrap.u_axi_lite_to_tlul_reg
ANNOTATION: "SEP-INTG-GEN-ON: ENABLE_CMD_INTG_GEN and ENABLE_DATA_INTG_GEN are 1 for this instance (hw/sys/sep/rtl/sep_dma_wrap.sv:234-235 from ENABLE_DATA_INTG_GEN = 1, sep.sv:1187), so the else arms that drive the all-ones integrity placeholder are dead by parameter. NOT waived: the generate-on arms."
Block 42 "2397383519" "data_intg = {tlul_pkg::DATA_INTG_WIDTH {1'b1}};"

CHECKSUM: "2097437693 2178003635"
INSTANCE: sep_uvm_top.u_dut.u_sep.u_sep_dma_wrap.u_axi_lite_to_tlul_reg
ANNOTATION: "SEP-INTG-GEN-ON: ENABLE_CMD_INTG_GEN and ENABLE_DATA_INTG_GEN are 1 for this instance (hw/sys/sep/rtl/sep_dma_wrap.sv:234-235 from ENABLE_DATA_INTG_GEN = 1, sep.sv:1187), so the else arms that drive the all-ones integrity placeholder are dead by parameter. NOT waived: the generate-on arms."
Branch 3 "1189517418" "ENABLE_CMD_INTG_GEN" (1) "ENABLE_CMD_INTG_GEN 0"
Branch 4 "2160096988" "ENABLE_DATA_INTG_GEN" (1) "ENABLE_DATA_INTG_GEN 0"

CHECKSUM: "2470472206 3216173326"
INSTANCE: sep_uvm_top.u_dut.u_sep.u_sep_dma_wrap.u_tlul_to_axi_lite_dma
ANNOTATION: "SEP-INTG-GEN-ON: ENABLE_RSP_INTG_GEN and ENABLE_DATA_INTG_GEN are 1 for this instance (hw/sys/sep/rtl/sep_dma_wrap.sv:259-260 from ENABLE_DATA_INTG_GEN = 1, sep.sv:1187), so the else arms that drive the all-ones integrity placeholder are dead by parameter. NOT waived: the generate-on arms."
Block 43 "993725118" "rsp_intg = {tlul_pkg::D2H_RSP_INTG_WIDTH {1'b1}};"

CHECKSUM: "2470472206 3216173326"
INSTANCE: sep_uvm_top.u_dut.u_sep.u_sep_dma_wrap.u_tlul_to_axi_lite_dma
ANNOTATION: "SEP-INTG-GEN-ON: ENABLE_RSP_INTG_GEN and ENABLE_DATA_INTG_GEN are 1 for this instance (hw/sys/sep/rtl/sep_dma_wrap.sv:259-260 from ENABLE_DATA_INTG_GEN = 1, sep.sv:1187), so the else arms that drive the all-ones integrity placeholder are dead by parameter. NOT waived: the generate-on arms."
Block 46 "2397383519" "data_intg = {tlul_pkg::DATA_INTG_WIDTH {1'b1}};"

CHECKSUM: "2470472206 1300994536"
INSTANCE: sep_uvm_top.u_dut.u_sep.u_sep_dma_wrap.u_tlul_to_axi_lite_dma
ANNOTATION: "SEP-INTG-GEN-ON: ENABLE_RSP_INTG_GEN and ENABLE_DATA_INTG_GEN are 1 for this instance (hw/sys/sep/rtl/sep_dma_wrap.sv:259-260 from ENABLE_DATA_INTG_GEN = 1, sep.sv:1187), so the else arms that drive the all-ones integrity placeholder are dead by parameter. NOT waived: the generate-on arms."
Branch 4 "3993283767" "ENABLE_RSP_INTG_GEN" (1) "ENABLE_RSP_INTG_GEN 0"
Branch 5 "2160096988" "ENABLE_DATA_INTG_GEN" (1) "ENABLE_DATA_INTG_GEN 0"

CHECKSUM: "2470472206 1300994536"
INSTANCE: sep_uvm_top.u_dut.u_sep.u_sep_dma_wrap.u_tlul_to_axi_lite_dma
ANNOTATION: "SEP-DMA-HOST-DREADY-TIED: tl_i is host_tl_h_o from tlul_adapter_host in secure_dma (hw/sys/sep/rtl/sep_dma_wrap.sv:265), and tlul_adapter_host.sv:118 ties d_ready to 1, so the TL_D_RESP arm that waits on d_ready = 0 (tlul_to_axi_lite.sv:267) cannot occur. NOT waived: the d_ready = 1 arm."
Branch 3 "255991702" "state_q" (18) "state_q TL_D_RESP ,-,-,-,-,-,-,-,-,-,0"

CHECKSUM: "186726968 3375809789"
ANNOTATION: "SEP-ISO-FSM-DEFAULT: isolate_state_e is 2 bits with 3 states (sep_isolate_rst_seq.sv:27-31). state_q resets to ST_RESET (:64) and loads only state_d, which every arm sets to ST_RUN, ST_DRAIN or ST_RESET (:37-55), so encoding 2'b11 and the default arm at :55 cannot occur. NOT waived: the reset-in-run transition ST_RUN->ST_RESET, which a mid-run reset reaches."
MODULE: sep_isolate_rst_seq
Block 11 "361841972" "state_d = ST_RESET;"

CHECKSUM: "186726968 3582565788"
ANNOTATION: "SEP-ISO-FSM-DEFAULT: isolate_state_e is 2 bits with 3 states (sep_isolate_rst_seq.sv:27-31). state_q resets to ST_RESET (:64) and loads only state_d, which every arm sets to ST_RUN, ST_DRAIN or ST_RESET (:37-55), so encoding 2'b11 and the default arm at :55 cannot occur. NOT waived: the reset-in-run transition ST_RUN->ST_RESET, which a mid-run reset reaches."
MODULE: sep_isolate_rst_seq
Branch 0 "2997770946" "state_q" (6) "state_q default,-,-,-"

