// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 Tenstorrent USA, Inc.
//==================================================
// SEP VCS coverage exclusions -- AXI fields a single internal master ties.
// Format Version: 2
// ExclMode: default
//
// Scope: the cocotb VCS elaboration of sep_uvm_top, target `default`.
// Do not merge a `rom_boot` target run against this file.
//
// Each block waives request fields on a port that exactly ONE internal master
// drives -- the VeeR IFU, LSU or debug system-bus master, or the secure DMA host
// port -- where that master's RTL assigns the field a constant and every module
// on the path passes it unchanged. The annotation names the tie and the fields
// that stay graded.
//
// Two rules keep this file honest:
//   * A port that the inbound SoC port, the JTAG bridge or a second master can
//     reach is NOT listed. Those fields are an integrator's to drive, so a hole
//     there is a stimulus gap.
//   * A tied field that any leaf moved (for example, the no_cpu TB force on the
//     LSU path) is NOT listed. Every listed signal had no 0->1 and no 1->0
//     toggle in the merged `all` database that supplies the checksums.
//
// Checksums come from `urg -dump full_exclusions tgl` on the merged VDB.
//==================================================

CHECKSUM: "3441942924 3928759875"
ANNOTATION: "SEP-CPU-DBG-TIED: only the VeeR debug system-bus master drives this port. el2_dbg.sv:738-774 tie id 0, prot 3'b001, AW cache 4'hF, AR cache 0, len 0, burst INCR, qos 0, lock 0, wlast 1, bready 1 and rready 1; sep_cpu.sv:501-503 and :508 drive AxUSER/WUSER to SEP_SOURCE_ID and AWATOP to 0; the window remap passes them unchanged. NOT waived: addr, size and region. SEP-DMA-MASTER-TIED: only the secure DMA host port drives this path, through axi_lite_to_axi, axi_dw_upsizer and the window remap. axi_lite_to_axi.sv:39-67 sets burst FIXED and id, len, lock, qos, region, atop and user to '0; sep_dma_wrap.sv:283-284 feed cache 4'b0000, a non-modifiable transfer the upsizer passes unchanged. NOT waived: addr, size, prot, the W data/strobe, and wlast, which the upsizer drives and a run moved. SEP-CPU-IFU-TIED: only the VeeR IFU drives this port. el2_ifu_mem_ctl.sv:1074-1082 ties AR size 3, prot 5, cache 4'hF, len 0, burst INCR, qos 0 and lock 0; :1085-1101 hold the whole AW and W channels and bready at 0 (the IFU never writes); sep_cpu.sv:493-495 drive AxUSER/WUSER to SEP_SOURCE_ID and :506 AWATOP to 0; the window remap and IFU demux pass these fields unchanged. NOT waived: AR addr, id and region, which follow the fetch address, and rready, which a run moved. SEP-CPU-LSU-TIED: only the VeeR LSU drives this port. el2_lsu_bus_buffer.sv:881-907 tie prot 3'b001, len 0, burst INCR, qos 0, lock 0, wlast 1, bready 1 and rready 1; sep_cpu.sv:497-499 and :507 drive AxUSER/WUSER to SEP_SOURCE_ID and AWATOP to 0; the window remap and LSU demux pass them unchanged. NOT waived: addr, id, size, cache and region, which follow the access, and every tied field a no_cpu leaf moves through its TB force on this path (prot, len, burst, wlast, bready, rready): only fields no leaf moved are listed."
MODULE: sep
Toggle ifu_sram_axi_req.ar.size "logic ifu_sram_axi_req.ar.size[2:0]"
Toggle ifu_sram_axi_req.ar.prot "logic ifu_sram_axi_req.ar.prot[2:0]"
Toggle ifu_sram_axi_req.ar.cache "logic ifu_sram_axi_req.ar.cache[3:0]"
Toggle ifu_sram_axi_req.ar.len "logic ifu_sram_axi_req.ar.len[7:0]"
Toggle ifu_sram_axi_req.ar.burst "logic ifu_sram_axi_req.ar.burst[1:0]"
Toggle ifu_sram_axi_req.ar.qos "logic ifu_sram_axi_req.ar.qos[3:0]"
Toggle ifu_sram_axi_req.ar.lock "logic ifu_sram_axi_req.ar.lock"
Toggle ifu_sram_axi_req.ar.user "logic ifu_sram_axi_req.ar.user[11:0]"
Toggle ifu_sram_axi_req.aw_valid "logic ifu_sram_axi_req.aw_valid"
Toggle ifu_sram_axi_req.aw.id "logic ifu_sram_axi_req.aw.id[2:0]"
Toggle ifu_sram_axi_req.aw.addr "logic ifu_sram_axi_req.aw.addr[31:0]"
Toggle ifu_sram_axi_req.aw.len "logic ifu_sram_axi_req.aw.len[7:0]"
Toggle ifu_sram_axi_req.aw.size "logic ifu_sram_axi_req.aw.size[2:0]"
Toggle ifu_sram_axi_req.aw.burst "logic ifu_sram_axi_req.aw.burst[1:0]"
Toggle ifu_sram_axi_req.aw.lock "logic ifu_sram_axi_req.aw.lock"
Toggle ifu_sram_axi_req.aw.cache "logic ifu_sram_axi_req.aw.cache[3:0]"
Toggle ifu_sram_axi_req.aw.prot "logic ifu_sram_axi_req.aw.prot[2:0]"
Toggle ifu_sram_axi_req.aw.qos "logic ifu_sram_axi_req.aw.qos[3:0]"
Toggle ifu_sram_axi_req.aw.region "logic ifu_sram_axi_req.aw.region[3:0]"
Toggle ifu_sram_axi_req.aw.atop "logic ifu_sram_axi_req.aw.atop[5:0]"
Toggle ifu_sram_axi_req.aw.user "logic ifu_sram_axi_req.aw.user[11:0]"
Toggle ifu_sram_axi_req.w_valid "logic ifu_sram_axi_req.w_valid"
Toggle ifu_sram_axi_req.w.data "logic ifu_sram_axi_req.w.data[63:0]"
Toggle ifu_sram_axi_req.w.strb "logic ifu_sram_axi_req.w.strb[7:0]"
Toggle ifu_sram_axi_req.w.last "logic ifu_sram_axi_req.w.last"
Toggle ifu_sram_axi_req.w.user "logic ifu_sram_axi_req.w.user[11:0]"
Toggle ifu_sram_axi_req.b_ready "logic ifu_sram_axi_req.b_ready"
Toggle ifu_rom_axi_req.ar.size "logic ifu_rom_axi_req.ar.size[2:0]"
Toggle ifu_rom_axi_req.ar.prot "logic ifu_rom_axi_req.ar.prot[2:0]"
Toggle ifu_rom_axi_req.ar.cache "logic ifu_rom_axi_req.ar.cache[3:0]"
Toggle ifu_rom_axi_req.ar.len "logic ifu_rom_axi_req.ar.len[7:0]"
Toggle ifu_rom_axi_req.ar.burst "logic ifu_rom_axi_req.ar.burst[1:0]"
Toggle ifu_rom_axi_req.ar.qos "logic ifu_rom_axi_req.ar.qos[3:0]"
Toggle ifu_rom_axi_req.ar.lock "logic ifu_rom_axi_req.ar.lock"
Toggle ifu_rom_axi_req.ar.user "logic ifu_rom_axi_req.ar.user[11:0]"
Toggle ifu_rom_axi_req.aw_valid "logic ifu_rom_axi_req.aw_valid"
Toggle ifu_rom_axi_req.aw.id "logic ifu_rom_axi_req.aw.id[2:0]"
Toggle ifu_rom_axi_req.aw.addr "logic ifu_rom_axi_req.aw.addr[31:0]"
Toggle ifu_rom_axi_req.aw.len "logic ifu_rom_axi_req.aw.len[7:0]"
Toggle ifu_rom_axi_req.aw.size "logic ifu_rom_axi_req.aw.size[2:0]"
Toggle ifu_rom_axi_req.aw.burst "logic ifu_rom_axi_req.aw.burst[1:0]"
Toggle ifu_rom_axi_req.aw.lock "logic ifu_rom_axi_req.aw.lock"
Toggle ifu_rom_axi_req.aw.cache "logic ifu_rom_axi_req.aw.cache[3:0]"
Toggle ifu_rom_axi_req.aw.prot "logic ifu_rom_axi_req.aw.prot[2:0]"
Toggle ifu_rom_axi_req.aw.qos "logic ifu_rom_axi_req.aw.qos[3:0]"
Toggle ifu_rom_axi_req.aw.region "logic ifu_rom_axi_req.aw.region[3:0]"
Toggle ifu_rom_axi_req.aw.atop "logic ifu_rom_axi_req.aw.atop[5:0]"
Toggle ifu_rom_axi_req.aw.user "logic ifu_rom_axi_req.aw.user[11:0]"
Toggle ifu_rom_axi_req.w_valid "logic ifu_rom_axi_req.w_valid"
Toggle ifu_rom_axi_req.w.data "logic ifu_rom_axi_req.w.data[63:0]"
Toggle ifu_rom_axi_req.w.strb "logic ifu_rom_axi_req.w.strb[7:0]"
Toggle ifu_rom_axi_req.w.last "logic ifu_rom_axi_req.w.last"
Toggle ifu_rom_axi_req.w.user "logic ifu_rom_axi_req.w.user[11:0]"
Toggle ifu_rom_axi_req.b_ready "logic ifu_rom_axi_req.b_ready"
Toggle lsu_xbar_axi_req.aw.qos "logic lsu_xbar_axi_req.aw.qos[3:0]"
Toggle lsu_xbar_axi_req.aw.lock "logic lsu_xbar_axi_req.aw.lock"
Toggle lsu_xbar_axi_req.aw.user "logic lsu_xbar_axi_req.aw.user[11:0]"
Toggle lsu_xbar_axi_req.aw.atop "logic lsu_xbar_axi_req.aw.atop[5:0]"
Toggle lsu_xbar_axi_req.ar.qos "logic lsu_xbar_axi_req.ar.qos[3:0]"
Toggle lsu_xbar_axi_req.ar.lock "logic lsu_xbar_axi_req.ar.lock"
Toggle lsu_xbar_axi_req.ar.user "logic lsu_xbar_axi_req.ar.user[11:0]"
Toggle lsu_xbar_axi_req.w.user "logic lsu_xbar_axi_req.w.user[11:0]"
Toggle lsu_rom_axi_req.aw.qos "logic lsu_rom_axi_req.aw.qos[3:0]"
Toggle lsu_rom_axi_req.aw.lock "logic lsu_rom_axi_req.aw.lock"
Toggle lsu_rom_axi_req.aw.user "logic lsu_rom_axi_req.aw.user[11:0]"
Toggle lsu_rom_axi_req.aw.atop "logic lsu_rom_axi_req.aw.atop[5:0]"
Toggle lsu_rom_axi_req.ar.qos "logic lsu_rom_axi_req.ar.qos[3:0]"
Toggle lsu_rom_axi_req.ar.lock "logic lsu_rom_axi_req.ar.lock"
Toggle lsu_rom_axi_req.ar.user "logic lsu_rom_axi_req.ar.user[11:0]"
Toggle lsu_rom_axi_req.w.user "logic lsu_rom_axi_req.w.user[11:0]"
Toggle dbg_axi_req.aw.id "logic dbg_axi_req.aw.id[2:0]"
Toggle dbg_axi_req.aw.prot "logic dbg_axi_req.aw.prot[2:0]"
Toggle dbg_axi_req.aw.cache "logic dbg_axi_req.aw.cache[3:0]"
Toggle dbg_axi_req.aw.len "logic dbg_axi_req.aw.len[7:0]"
Toggle dbg_axi_req.aw.burst "logic dbg_axi_req.aw.burst[1:0]"
Toggle dbg_axi_req.aw.qos "logic dbg_axi_req.aw.qos[3:0]"
Toggle dbg_axi_req.aw.lock "logic dbg_axi_req.aw.lock"
Toggle dbg_axi_req.aw.user "logic dbg_axi_req.aw.user[11:0]"
Toggle dbg_axi_req.aw.atop "logic dbg_axi_req.aw.atop[5:0]"
Toggle dbg_axi_req.ar.id "logic dbg_axi_req.ar.id[2:0]"
Toggle dbg_axi_req.ar.prot "logic dbg_axi_req.ar.prot[2:0]"
Toggle dbg_axi_req.ar.cache "logic dbg_axi_req.ar.cache[3:0]"
Toggle dbg_axi_req.ar.len "logic dbg_axi_req.ar.len[7:0]"
Toggle dbg_axi_req.ar.burst "logic dbg_axi_req.ar.burst[1:0]"
Toggle dbg_axi_req.ar.qos "logic dbg_axi_req.ar.qos[3:0]"
Toggle dbg_axi_req.ar.lock "logic dbg_axi_req.ar.lock"
Toggle dbg_axi_req.ar.user "logic dbg_axi_req.ar.user[11:0]"
Toggle dbg_axi_req.w.last "logic dbg_axi_req.w.last"
Toggle dbg_axi_req.w.user "logic dbg_axi_req.w.user[11:0]"
Toggle dbg_axi_req.b_ready "logic dbg_axi_req.b_ready"
Toggle dbg_axi_req.r_ready "logic dbg_axi_req.r_ready"
Toggle dma_axi_req.aw.id "logic dma_axi_req.aw.id[2:0]"
Toggle dma_axi_req.aw.len "logic dma_axi_req.aw.len[7:0]"
Toggle dma_axi_req.aw.burst "logic dma_axi_req.aw.burst[1:0]"
Toggle dma_axi_req.aw.lock "logic dma_axi_req.aw.lock"
Toggle dma_axi_req.aw.cache "logic dma_axi_req.aw.cache[3:0]"
Toggle dma_axi_req.aw.qos "logic dma_axi_req.aw.qos[3:0]"
Toggle dma_axi_req.aw.region "logic dma_axi_req.aw.region[3:0]"
Toggle dma_axi_req.aw.atop "logic dma_axi_req.aw.atop[5:0]"
Toggle dma_axi_req.aw.user "logic dma_axi_req.aw.user[11:0]"
Toggle dma_axi_req.ar.id "logic dma_axi_req.ar.id[2:0]"
Toggle dma_axi_req.ar.len "logic dma_axi_req.ar.len[7:0]"
Toggle dma_axi_req.ar.burst "logic dma_axi_req.ar.burst[1:0]"
Toggle dma_axi_req.ar.lock "logic dma_axi_req.ar.lock"
Toggle dma_axi_req.ar.cache "logic dma_axi_req.ar.cache[3:0]"
Toggle dma_axi_req.ar.qos "logic dma_axi_req.ar.qos[3:0]"
Toggle dma_axi_req.ar.region "logic dma_axi_req.ar.region[3:0]"
Toggle dma_axi_req.ar.user "logic dma_axi_req.ar.user[11:0]"
Toggle dma_axi_req.w.user "logic dma_axi_req.w.user[11:0]"

CHECKSUM: "366726899 3902493086"
ANNOTATION: "SEP-CPU-DBG-TIED: only the VeeR debug system-bus master drives this port. el2_dbg.sv:738-774 tie id 0, prot 3'b001, AW cache 4'hF, AR cache 0, len 0, burst INCR, qos 0, lock 0, wlast 1, bready 1 and rready 1; sep_cpu.sv:501-503 and :508 drive AxUSER/WUSER to SEP_SOURCE_ID and AWATOP to 0; the window remap passes them unchanged. NOT waived: addr, size and region. SEP-DMA-MASTER-TIED: only the secure DMA host port drives this path, through axi_lite_to_axi, axi_dw_upsizer and the window remap. axi_lite_to_axi.sv:39-67 sets burst FIXED and id, len, lock, qos, region, atop and user to '0; sep_dma_wrap.sv:283-284 feed cache 4'b0000, a non-modifiable transfer the upsizer passes unchanged. NOT waived: addr, size, prot, the W data/strobe, and wlast, which the upsizer drives and a run moved. SEP-CPU-IFU-TIED: only the VeeR IFU drives this port. el2_ifu_mem_ctl.sv:1074-1082 ties AR size 3, prot 5, cache 4'hF, len 0, burst INCR, qos 0 and lock 0; :1085-1101 hold the whole AW and W channels and bready at 0 (the IFU never writes); sep_cpu.sv:493-495 drive AxUSER/WUSER to SEP_SOURCE_ID and :506 AWATOP to 0; the window remap and IFU demux pass these fields unchanged. NOT waived: AR addr, id and region, which follow the fetch address, and rready, which a run moved. SEP-CPU-LSU-TIED: only the VeeR LSU drives this port. el2_lsu_bus_buffer.sv:881-907 tie prot 3'b001, len 0, burst INCR, qos 0, lock 0, wlast 1, bready 1 and rready 1; sep_cpu.sv:497-499 and :507 drive AxUSER/WUSER to SEP_SOURCE_ID and AWATOP to 0; the window remap and LSU demux pass them unchanged. NOT waived: addr, id, size, cache and region, which follow the access, and every tied field a no_cpu leaf moves through its TB force on this path (prot, len, burst, wlast, bready, rready): only fields no leaf moved are listed."
MODULE: sep_local_axi_xbar_wrapper
Toggle ifu_sram_axi_req_i.ar.size "logic ifu_sram_axi_req_i.ar.size[2:0]"
Toggle ifu_sram_axi_req_i.ar.prot "logic ifu_sram_axi_req_i.ar.prot[2:0]"
Toggle ifu_sram_axi_req_i.ar.cache "logic ifu_sram_axi_req_i.ar.cache[3:0]"
Toggle ifu_sram_axi_req_i.ar.len "logic ifu_sram_axi_req_i.ar.len[7:0]"
Toggle ifu_sram_axi_req_i.ar.burst "logic ifu_sram_axi_req_i.ar.burst[1:0]"
Toggle ifu_sram_axi_req_i.ar.qos "logic ifu_sram_axi_req_i.ar.qos[3:0]"
Toggle ifu_sram_axi_req_i.ar.lock "logic ifu_sram_axi_req_i.ar.lock"
Toggle ifu_sram_axi_req_i.ar.user "logic ifu_sram_axi_req_i.ar.user[11:0]"
Toggle ifu_sram_axi_req_i.aw_valid "logic ifu_sram_axi_req_i.aw_valid"
Toggle ifu_sram_axi_req_i.aw.id "logic ifu_sram_axi_req_i.aw.id[2:0]"
Toggle ifu_sram_axi_req_i.aw.addr "logic ifu_sram_axi_req_i.aw.addr[31:0]"
Toggle ifu_sram_axi_req_i.aw.len "logic ifu_sram_axi_req_i.aw.len[7:0]"
Toggle ifu_sram_axi_req_i.aw.size "logic ifu_sram_axi_req_i.aw.size[2:0]"
Toggle ifu_sram_axi_req_i.aw.burst "logic ifu_sram_axi_req_i.aw.burst[1:0]"
Toggle ifu_sram_axi_req_i.aw.lock "logic ifu_sram_axi_req_i.aw.lock"
Toggle ifu_sram_axi_req_i.aw.cache "logic ifu_sram_axi_req_i.aw.cache[3:0]"
Toggle ifu_sram_axi_req_i.aw.prot "logic ifu_sram_axi_req_i.aw.prot[2:0]"
Toggle ifu_sram_axi_req_i.aw.qos "logic ifu_sram_axi_req_i.aw.qos[3:0]"
Toggle ifu_sram_axi_req_i.aw.region "logic ifu_sram_axi_req_i.aw.region[3:0]"
Toggle ifu_sram_axi_req_i.aw.atop "logic ifu_sram_axi_req_i.aw.atop[5:0]"
Toggle ifu_sram_axi_req_i.aw.user "logic ifu_sram_axi_req_i.aw.user[11:0]"
Toggle ifu_sram_axi_req_i.w_valid "logic ifu_sram_axi_req_i.w_valid"
Toggle ifu_sram_axi_req_i.w.data "logic ifu_sram_axi_req_i.w.data[63:0]"
Toggle ifu_sram_axi_req_i.w.strb "logic ifu_sram_axi_req_i.w.strb[7:0]"
Toggle ifu_sram_axi_req_i.w.last "logic ifu_sram_axi_req_i.w.last"
Toggle ifu_sram_axi_req_i.w.user "logic ifu_sram_axi_req_i.w.user[11:0]"
Toggle ifu_sram_axi_req_i.b_ready "logic ifu_sram_axi_req_i.b_ready"
Toggle ifu_sram_req.ar.size "logic ifu_sram_req.ar.size[2:0]"
Toggle ifu_sram_req.ar.prot "logic ifu_sram_req.ar.prot[2:0]"
Toggle ifu_sram_req.ar.cache "logic ifu_sram_req.ar.cache[3:0]"
Toggle ifu_sram_req.ar.len "logic ifu_sram_req.ar.len[7:0]"
Toggle ifu_sram_req.ar.burst "logic ifu_sram_req.ar.burst[1:0]"
Toggle ifu_sram_req.ar.qos "logic ifu_sram_req.ar.qos[3:0]"
Toggle ifu_sram_req.ar.lock "logic ifu_sram_req.ar.lock"
Toggle ifu_sram_req.ar.user "logic ifu_sram_req.ar.user[11:0]"
Toggle ifu_sram_req.aw_valid "logic ifu_sram_req.aw_valid"
Toggle ifu_sram_req.aw.id "logic ifu_sram_req.aw.id[2:0]"
Toggle ifu_sram_req.aw.addr "logic ifu_sram_req.aw.addr[31:0]"
Toggle ifu_sram_req.aw.len "logic ifu_sram_req.aw.len[7:0]"
Toggle ifu_sram_req.aw.size "logic ifu_sram_req.aw.size[2:0]"
Toggle ifu_sram_req.aw.burst "logic ifu_sram_req.aw.burst[1:0]"
Toggle ifu_sram_req.aw.lock "logic ifu_sram_req.aw.lock"
Toggle ifu_sram_req.aw.cache "logic ifu_sram_req.aw.cache[3:0]"
Toggle ifu_sram_req.aw.prot "logic ifu_sram_req.aw.prot[2:0]"
Toggle ifu_sram_req.aw.qos "logic ifu_sram_req.aw.qos[3:0]"
Toggle ifu_sram_req.aw.region "logic ifu_sram_req.aw.region[3:0]"
Toggle ifu_sram_req.aw.atop "logic ifu_sram_req.aw.atop[5:0]"
Toggle ifu_sram_req.aw.user "logic ifu_sram_req.aw.user[11:0]"
Toggle ifu_sram_req.w_valid "logic ifu_sram_req.w_valid"
Toggle ifu_sram_req.w.data "logic ifu_sram_req.w.data[63:0]"
Toggle ifu_sram_req.w.strb "logic ifu_sram_req.w.strb[7:0]"
Toggle ifu_sram_req.w.last "logic ifu_sram_req.w.last"
Toggle ifu_sram_req.w.user "logic ifu_sram_req.w.user[11:0]"
Toggle ifu_sram_req.b_ready "logic ifu_sram_req.b_ready"
Toggle lsu_axi_req_i.aw.qos "logic lsu_axi_req_i.aw.qos[3:0]"
Toggle lsu_axi_req_i.aw.lock "logic lsu_axi_req_i.aw.lock"
Toggle lsu_axi_req_i.aw.user "logic lsu_axi_req_i.aw.user[11:0]"
Toggle lsu_axi_req_i.aw.atop "logic lsu_axi_req_i.aw.atop[5:0]"
Toggle lsu_axi_req_i.ar.qos "logic lsu_axi_req_i.ar.qos[3:0]"
Toggle lsu_axi_req_i.ar.lock "logic lsu_axi_req_i.ar.lock"
Toggle lsu_axi_req_i.ar.user "logic lsu_axi_req_i.ar.user[11:0]"
Toggle lsu_axi_req_i.w.user "logic lsu_axi_req_i.w.user[11:0]"
Toggle lsu_req.aw.qos "logic lsu_req.aw.qos[3:0]"
Toggle lsu_req.aw.lock "logic lsu_req.aw.lock"
Toggle lsu_req.aw.user "logic lsu_req.aw.user[11:0]"
Toggle lsu_req.aw.atop "logic lsu_req.aw.atop[5:0]"
Toggle lsu_req.ar.qos "logic lsu_req.ar.qos[3:0]"
Toggle lsu_req.ar.lock "logic lsu_req.ar.lock"
Toggle lsu_req.ar.user "logic lsu_req.ar.user[11:0]"
Toggle lsu_req.w.user "logic lsu_req.w.user[11:0]"
Toggle dbg_axi_req_i.aw.id "logic dbg_axi_req_i.aw.id[2:0]"
Toggle dbg_axi_req_i.aw.prot "logic dbg_axi_req_i.aw.prot[2:0]"
Toggle dbg_axi_req_i.aw.cache "logic dbg_axi_req_i.aw.cache[3:0]"
Toggle dbg_axi_req_i.aw.len "logic dbg_axi_req_i.aw.len[7:0]"
Toggle dbg_axi_req_i.aw.burst "logic dbg_axi_req_i.aw.burst[1:0]"
Toggle dbg_axi_req_i.aw.qos "logic dbg_axi_req_i.aw.qos[3:0]"
Toggle dbg_axi_req_i.aw.lock "logic dbg_axi_req_i.aw.lock"
Toggle dbg_axi_req_i.aw.user "logic dbg_axi_req_i.aw.user[11:0]"
Toggle dbg_axi_req_i.aw.atop "logic dbg_axi_req_i.aw.atop[5:0]"
Toggle dbg_axi_req_i.ar.id "logic dbg_axi_req_i.ar.id[2:0]"
Toggle dbg_axi_req_i.ar.prot "logic dbg_axi_req_i.ar.prot[2:0]"
Toggle dbg_axi_req_i.ar.cache "logic dbg_axi_req_i.ar.cache[3:0]"
Toggle dbg_axi_req_i.ar.len "logic dbg_axi_req_i.ar.len[7:0]"
Toggle dbg_axi_req_i.ar.burst "logic dbg_axi_req_i.ar.burst[1:0]"
Toggle dbg_axi_req_i.ar.qos "logic dbg_axi_req_i.ar.qos[3:0]"
Toggle dbg_axi_req_i.ar.lock "logic dbg_axi_req_i.ar.lock"
Toggle dbg_axi_req_i.ar.user "logic dbg_axi_req_i.ar.user[11:0]"
Toggle dbg_axi_req_i.w.last "logic dbg_axi_req_i.w.last"
Toggle dbg_axi_req_i.w.user "logic dbg_axi_req_i.w.user[11:0]"
Toggle dbg_axi_req_i.b_ready "logic dbg_axi_req_i.b_ready"
Toggle dbg_axi_req_i.r_ready "logic dbg_axi_req_i.r_ready"
Toggle dbg_req.aw.id "logic dbg_req.aw.id[2:0]"
Toggle dbg_req.aw.prot "logic dbg_req.aw.prot[2:0]"
Toggle dbg_req.aw.cache "logic dbg_req.aw.cache[3:0]"
Toggle dbg_req.aw.len "logic dbg_req.aw.len[7:0]"
Toggle dbg_req.aw.burst "logic dbg_req.aw.burst[1:0]"
Toggle dbg_req.aw.qos "logic dbg_req.aw.qos[3:0]"
Toggle dbg_req.aw.lock "logic dbg_req.aw.lock"
Toggle dbg_req.aw.user "logic dbg_req.aw.user[11:0]"
Toggle dbg_req.aw.atop "logic dbg_req.aw.atop[5:0]"
Toggle dbg_req.ar.id "logic dbg_req.ar.id[2:0]"
Toggle dbg_req.ar.prot "logic dbg_req.ar.prot[2:0]"
Toggle dbg_req.ar.cache "logic dbg_req.ar.cache[3:0]"
Toggle dbg_req.ar.len "logic dbg_req.ar.len[7:0]"
Toggle dbg_req.ar.burst "logic dbg_req.ar.burst[1:0]"
Toggle dbg_req.ar.qos "logic dbg_req.ar.qos[3:0]"
Toggle dbg_req.ar.lock "logic dbg_req.ar.lock"
Toggle dbg_req.ar.user "logic dbg_req.ar.user[11:0]"
Toggle dbg_req.w.last "logic dbg_req.w.last"
Toggle dbg_req.w.user "logic dbg_req.w.user[11:0]"
Toggle dbg_req.b_ready "logic dbg_req.b_ready"
Toggle dbg_req.r_ready "logic dbg_req.r_ready"
Toggle dma_axi_req_i.aw.id "logic dma_axi_req_i.aw.id[2:0]"
Toggle dma_axi_req_i.aw.len "logic dma_axi_req_i.aw.len[7:0]"
Toggle dma_axi_req_i.aw.burst "logic dma_axi_req_i.aw.burst[1:0]"
Toggle dma_axi_req_i.aw.lock "logic dma_axi_req_i.aw.lock"
Toggle dma_axi_req_i.aw.cache "logic dma_axi_req_i.aw.cache[3:0]"
Toggle dma_axi_req_i.aw.qos "logic dma_axi_req_i.aw.qos[3:0]"
Toggle dma_axi_req_i.aw.region "logic dma_axi_req_i.aw.region[3:0]"
Toggle dma_axi_req_i.aw.atop "logic dma_axi_req_i.aw.atop[5:0]"
Toggle dma_axi_req_i.aw.user "logic dma_axi_req_i.aw.user[11:0]"
Toggle dma_axi_req_i.ar.id "logic dma_axi_req_i.ar.id[2:0]"
Toggle dma_axi_req_i.ar.len "logic dma_axi_req_i.ar.len[7:0]"
Toggle dma_axi_req_i.ar.burst "logic dma_axi_req_i.ar.burst[1:0]"
Toggle dma_axi_req_i.ar.lock "logic dma_axi_req_i.ar.lock"
Toggle dma_axi_req_i.ar.cache "logic dma_axi_req_i.ar.cache[3:0]"
Toggle dma_axi_req_i.ar.qos "logic dma_axi_req_i.ar.qos[3:0]"
Toggle dma_axi_req_i.ar.region "logic dma_axi_req_i.ar.region[3:0]"
Toggle dma_axi_req_i.ar.user "logic dma_axi_req_i.ar.user[11:0]"
Toggle dma_axi_req_i.w.user "logic dma_axi_req_i.w.user[11:0]"
Toggle dma_req.aw.id "logic dma_req.aw.id[2:0]"
Toggle dma_req.aw.len "logic dma_req.aw.len[7:0]"
Toggle dma_req.aw.burst "logic dma_req.aw.burst[1:0]"
Toggle dma_req.aw.lock "logic dma_req.aw.lock"
Toggle dma_req.aw.cache "logic dma_req.aw.cache[3:0]"
Toggle dma_req.aw.qos "logic dma_req.aw.qos[3:0]"
Toggle dma_req.aw.region "logic dma_req.aw.region[3:0]"
Toggle dma_req.aw.atop "logic dma_req.aw.atop[5:0]"
Toggle dma_req.aw.user "logic dma_req.aw.user[11:0]"
Toggle dma_req.ar.id "logic dma_req.ar.id[2:0]"
Toggle dma_req.ar.len "logic dma_req.ar.len[7:0]"
Toggle dma_req.ar.burst "logic dma_req.ar.burst[1:0]"
Toggle dma_req.ar.lock "logic dma_req.ar.lock"
Toggle dma_req.ar.cache "logic dma_req.ar.cache[3:0]"
Toggle dma_req.ar.qos "logic dma_req.ar.qos[3:0]"
Toggle dma_req.ar.region "logic dma_req.ar.region[3:0]"
Toggle dma_req.ar.user "logic dma_req.ar.user[11:0]"
Toggle dma_req.w.user "logic dma_req.w.user[11:0]"

CHECKSUM: "493051728 1660934675"
ANNOTATION: "SEP-CPU-DBG-TIED: only the VeeR debug system-bus master drives this port. el2_dbg.sv:738-774 tie id 0, prot 3'b001, AW cache 4'hF, AR cache 0, len 0, burst INCR, qos 0, lock 0, wlast 1, bready 1 and rready 1; sep_cpu.sv:501-503 and :508 drive AxUSER/WUSER to SEP_SOURCE_ID and AWATOP to 0; the window remap passes them unchanged. NOT waived: addr, size and region. SEP-DMA-MASTER-TIED: only the secure DMA host port drives this path, through axi_lite_to_axi, axi_dw_upsizer and the window remap. axi_lite_to_axi.sv:39-67 sets burst FIXED and id, len, lock, qos, region, atop and user to '0; sep_dma_wrap.sv:283-284 feed cache 4'b0000, a non-modifiable transfer the upsizer passes unchanged. NOT waived: addr, size, prot, the W data/strobe, and wlast, which the upsizer drives and a run moved. SEP-CPU-IFU-TIED: only the VeeR IFU drives this port. el2_ifu_mem_ctl.sv:1074-1082 ties AR size 3, prot 5, cache 4'hF, len 0, burst INCR, qos 0 and lock 0; :1085-1101 hold the whole AW and W channels and bready at 0 (the IFU never writes); sep_cpu.sv:493-495 drive AxUSER/WUSER to SEP_SOURCE_ID and :506 AWATOP to 0; the window remap and IFU demux pass these fields unchanged. NOT waived: AR addr, id and region, which follow the fetch address, and rready, which a run moved. SEP-CPU-LSU-TIED: only the VeeR LSU drives this port. el2_lsu_bus_buffer.sv:881-907 tie prot 3'b001, len 0, burst INCR, qos 0, lock 0, wlast 1, bready 1 and rready 1; sep_cpu.sv:497-499 and :507 drive AxUSER/WUSER to SEP_SOURCE_ID and AWATOP to 0; the window remap and LSU demux pass them unchanged. NOT waived: addr, id, size, cache and region, which follow the access, and every tied field a no_cpu leaf moves through its TB force on this path (prot, len, burst, wlast, bready, rready): only fields no leaf moved are listed."
MODULE: sep_local_axi_xbar
Toggle ifu_sram_req_i.ar.size "logic ifu_sram_req_i.ar.size[2:0]"
Toggle ifu_sram_req_i.ar.prot "logic ifu_sram_req_i.ar.prot[2:0]"
Toggle ifu_sram_req_i.ar.cache "logic ifu_sram_req_i.ar.cache[3:0]"
Toggle ifu_sram_req_i.ar.len "logic ifu_sram_req_i.ar.len[7:0]"
Toggle ifu_sram_req_i.ar.burst "logic ifu_sram_req_i.ar.burst[1:0]"
Toggle ifu_sram_req_i.ar.qos "logic ifu_sram_req_i.ar.qos[3:0]"
Toggle ifu_sram_req_i.ar.lock "logic ifu_sram_req_i.ar.lock"
Toggle ifu_sram_req_i.ar.user "logic ifu_sram_req_i.ar.user[11:0]"
Toggle ifu_sram_req_i.aw_valid "logic ifu_sram_req_i.aw_valid"
Toggle ifu_sram_req_i.aw.id "logic ifu_sram_req_i.aw.id[2:0]"
Toggle ifu_sram_req_i.aw.addr "logic ifu_sram_req_i.aw.addr[31:0]"
Toggle ifu_sram_req_i.aw.len "logic ifu_sram_req_i.aw.len[7:0]"
Toggle ifu_sram_req_i.aw.size "logic ifu_sram_req_i.aw.size[2:0]"
Toggle ifu_sram_req_i.aw.burst "logic ifu_sram_req_i.aw.burst[1:0]"
Toggle ifu_sram_req_i.aw.lock "logic ifu_sram_req_i.aw.lock"
Toggle ifu_sram_req_i.aw.cache "logic ifu_sram_req_i.aw.cache[3:0]"
Toggle ifu_sram_req_i.aw.prot "logic ifu_sram_req_i.aw.prot[2:0]"
Toggle ifu_sram_req_i.aw.qos "logic ifu_sram_req_i.aw.qos[3:0]"
Toggle ifu_sram_req_i.aw.region "logic ifu_sram_req_i.aw.region[3:0]"
Toggle ifu_sram_req_i.aw.atop "logic ifu_sram_req_i.aw.atop[5:0]"
Toggle ifu_sram_req_i.aw.user "logic ifu_sram_req_i.aw.user[11:0]"
Toggle ifu_sram_req_i.w_valid "logic ifu_sram_req_i.w_valid"
Toggle ifu_sram_req_i.w.data "logic ifu_sram_req_i.w.data[63:0]"
Toggle ifu_sram_req_i.w.strb "logic ifu_sram_req_i.w.strb[7:0]"
Toggle ifu_sram_req_i.w.last "logic ifu_sram_req_i.w.last"
Toggle ifu_sram_req_i.w.user "logic ifu_sram_req_i.w.user[11:0]"
Toggle ifu_sram_req_i.b_ready "logic ifu_sram_req_i.b_ready"
Toggle lsu_req_i.aw.qos "logic lsu_req_i.aw.qos[3:0]"
Toggle lsu_req_i.aw.lock "logic lsu_req_i.aw.lock"
Toggle lsu_req_i.aw.user "logic lsu_req_i.aw.user[11:0]"
Toggle lsu_req_i.aw.atop "logic lsu_req_i.aw.atop[5:0]"
Toggle lsu_req_i.ar.qos "logic lsu_req_i.ar.qos[3:0]"
Toggle lsu_req_i.ar.lock "logic lsu_req_i.ar.lock"
Toggle lsu_req_i.ar.user "logic lsu_req_i.ar.user[11:0]"
Toggle lsu_req_i.w.user "logic lsu_req_i.w.user[11:0]"
Toggle dbg_req_i.aw.id "logic dbg_req_i.aw.id[2:0]"
Toggle dbg_req_i.aw.prot "logic dbg_req_i.aw.prot[2:0]"
Toggle dbg_req_i.aw.cache "logic dbg_req_i.aw.cache[3:0]"
Toggle dbg_req_i.aw.len "logic dbg_req_i.aw.len[7:0]"
Toggle dbg_req_i.aw.burst "logic dbg_req_i.aw.burst[1:0]"
Toggle dbg_req_i.aw.qos "logic dbg_req_i.aw.qos[3:0]"
Toggle dbg_req_i.aw.lock "logic dbg_req_i.aw.lock"
Toggle dbg_req_i.aw.user "logic dbg_req_i.aw.user[11:0]"
Toggle dbg_req_i.aw.atop "logic dbg_req_i.aw.atop[5:0]"
Toggle dbg_req_i.ar.id "logic dbg_req_i.ar.id[2:0]"
Toggle dbg_req_i.ar.prot "logic dbg_req_i.ar.prot[2:0]"
Toggle dbg_req_i.ar.cache "logic dbg_req_i.ar.cache[3:0]"
Toggle dbg_req_i.ar.len "logic dbg_req_i.ar.len[7:0]"
Toggle dbg_req_i.ar.burst "logic dbg_req_i.ar.burst[1:0]"
Toggle dbg_req_i.ar.qos "logic dbg_req_i.ar.qos[3:0]"
Toggle dbg_req_i.ar.lock "logic dbg_req_i.ar.lock"
Toggle dbg_req_i.ar.user "logic dbg_req_i.ar.user[11:0]"
Toggle dbg_req_i.w.last "logic dbg_req_i.w.last"
Toggle dbg_req_i.w.user "logic dbg_req_i.w.user[11:0]"
Toggle dbg_req_i.b_ready "logic dbg_req_i.b_ready"
Toggle dbg_req_i.r_ready "logic dbg_req_i.r_ready"
Toggle dma_req_i.aw.id "logic dma_req_i.aw.id[2:0]"
Toggle dma_req_i.aw.len "logic dma_req_i.aw.len[7:0]"
Toggle dma_req_i.aw.burst "logic dma_req_i.aw.burst[1:0]"
Toggle dma_req_i.aw.lock "logic dma_req_i.aw.lock"
Toggle dma_req_i.aw.cache "logic dma_req_i.aw.cache[3:0]"
Toggle dma_req_i.aw.qos "logic dma_req_i.aw.qos[3:0]"
Toggle dma_req_i.aw.region "logic dma_req_i.aw.region[3:0]"
Toggle dma_req_i.aw.atop "logic dma_req_i.aw.atop[5:0]"
Toggle dma_req_i.aw.user "logic dma_req_i.aw.user[11:0]"
Toggle dma_req_i.ar.id "logic dma_req_i.ar.id[2:0]"
Toggle dma_req_i.ar.len "logic dma_req_i.ar.len[7:0]"
Toggle dma_req_i.ar.burst "logic dma_req_i.ar.burst[1:0]"
Toggle dma_req_i.ar.lock "logic dma_req_i.ar.lock"
Toggle dma_req_i.ar.cache "logic dma_req_i.ar.cache[3:0]"
Toggle dma_req_i.ar.qos "logic dma_req_i.ar.qos[3:0]"
Toggle dma_req_i.ar.region "logic dma_req_i.ar.region[3:0]"
Toggle dma_req_i.ar.user "logic dma_req_i.ar.user[11:0]"
Toggle dma_req_i.w.user "logic dma_req_i.w.user[11:0]"

CHECKSUM: "1107365883 3972236298"
ANNOTATION: "SEP-DMA-MASTER-TIED: only the secure DMA host port drives this path, through axi_lite_to_axi, axi_dw_upsizer and the window remap. axi_lite_to_axi.sv:39-67 sets burst FIXED and id, len, lock, qos, region, atop and user to '0; sep_dma_wrap.sv:283-284 feed cache 4'b0000, a non-modifiable transfer the upsizer passes unchanged. NOT waived: addr, size, prot, the W data/strobe, and wlast, which the upsizer drives and a run moved."
MODULE: sep_dma_wrap
Toggle dma_axi_req_raw.aw.id "logic dma_axi_req_raw.aw.id[2:0]"
Toggle dma_axi_req_raw.aw.len "logic dma_axi_req_raw.aw.len[7:0]"
Toggle dma_axi_req_raw.aw.burst "logic dma_axi_req_raw.aw.burst[1:0]"
Toggle dma_axi_req_raw.aw.lock "logic dma_axi_req_raw.aw.lock"
Toggle dma_axi_req_raw.aw.cache "logic dma_axi_req_raw.aw.cache[3:0]"
Toggle dma_axi_req_raw.aw.qos "logic dma_axi_req_raw.aw.qos[3:0]"
Toggle dma_axi_req_raw.aw.region "logic dma_axi_req_raw.aw.region[3:0]"
Toggle dma_axi_req_raw.aw.atop "logic dma_axi_req_raw.aw.atop[5:0]"
Toggle dma_axi_req_raw.aw.user "logic dma_axi_req_raw.aw.user[11:0]"
Toggle dma_axi_req_raw.ar.id "logic dma_axi_req_raw.ar.id[2:0]"
Toggle dma_axi_req_raw.ar.len "logic dma_axi_req_raw.ar.len[7:0]"
Toggle dma_axi_req_raw.ar.burst "logic dma_axi_req_raw.ar.burst[1:0]"
Toggle dma_axi_req_raw.ar.lock "logic dma_axi_req_raw.ar.lock"
Toggle dma_axi_req_raw.ar.cache "logic dma_axi_req_raw.ar.cache[3:0]"
Toggle dma_axi_req_raw.ar.qos "logic dma_axi_req_raw.ar.qos[3:0]"
Toggle dma_axi_req_raw.ar.region "logic dma_axi_req_raw.ar.region[3:0]"
Toggle dma_axi_req_raw.ar.user "logic dma_axi_req_raw.ar.user[11:0]"
Toggle dma_axi_req_raw.w.user "logic dma_axi_req_raw.w.user[11:0]"
Toggle dma_req_o.aw.id "logic dma_req_o.aw.id[2:0]"
Toggle dma_req_o.aw.len "logic dma_req_o.aw.len[7:0]"
Toggle dma_req_o.aw.burst "logic dma_req_o.aw.burst[1:0]"
Toggle dma_req_o.aw.lock "logic dma_req_o.aw.lock"
Toggle dma_req_o.aw.cache "logic dma_req_o.aw.cache[3:0]"
Toggle dma_req_o.aw.qos "logic dma_req_o.aw.qos[3:0]"
Toggle dma_req_o.aw.region "logic dma_req_o.aw.region[3:0]"
Toggle dma_req_o.aw.atop "logic dma_req_o.aw.atop[5:0]"
Toggle dma_req_o.aw.user "logic dma_req_o.aw.user[11:0]"
Toggle dma_req_o.ar.id "logic dma_req_o.ar.id[2:0]"
Toggle dma_req_o.ar.len "logic dma_req_o.ar.len[7:0]"
Toggle dma_req_o.ar.burst "logic dma_req_o.ar.burst[1:0]"
Toggle dma_req_o.ar.lock "logic dma_req_o.ar.lock"
Toggle dma_req_o.ar.cache "logic dma_req_o.ar.cache[3:0]"
Toggle dma_req_o.ar.qos "logic dma_req_o.ar.qos[3:0]"
Toggle dma_req_o.ar.region "logic dma_req_o.ar.region[3:0]"
Toggle dma_req_o.ar.user "logic dma_req_o.ar.user[11:0]"
Toggle dma_req_o.w.user "logic dma_req_o.w.user[11:0]"

