# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2026 Tenstorrent USA, Inc.
#
# tclint-disable line-length

# For waiving violations on IP developed by Tenstorrent teams

#=======================================================================================================================
# RULE INFO:
#=======================================================================================================================
# STARC05-1_1_1_1: Module name should be the same as file name
# STARC05-3_3_1_4b: Flop should have async set or reset
# W362: Arithmetic comparison with unequal length
# W164b: LHS of assignment wider than RHS
# STARC05-2_1_3_1: width of function arguments must match width of function inputs
# W553: Different bits of a bus are driven in different combinational blocks
# W391: Module driven by both edges of a clock
# STARC05-2_10_6_1: Possible loss of carry or borrow in addition or subtraction when width of LHS = width of RHS
# W401: Clock generated internally in module
# W193: Empty statement (isolated semicolon)
# W123: Signal is read but not set
# W240: Input declared but not read
# STARC05-1_3_1_3: Async reset used as sync reset or non-reset
# STARC05-2_11_3_1: Sequential and combinational parts of FSM described in same "always" block
# W415: Signal has multiple drivers but is not declared a tri-state
# STARC05-1_4_3_2: Flip-flop clocked by another flop output (ripple/derived clock)
# CombLoop: Combinational loop
# UnrecSynthDir-ML: Unrecognized synthesis directive (pragma)
# STARC05-2_2_3_3: Flip-flop assigned more than once in a sequential always block
# W287a: Input of instance is undriven
#=======================================================================================================================

# Rule Waivers (should be consolidated into new ruleset)

#=======================================================================================================================
# Module-name prefix support
#=======================================================================================================================

if { ![info exists PREFIX] } {
    set PREFIX ""
}
# Substitute the literal ${PREFIX} token in a -filter expression with $PREFIX's
# value. Uses string map rather than brace interpolation so that $clog2, bus
# indices like [i], and embedded quotes inside the filter are preserved verbatim.
proc apply_prefix { filter } {
    return [string map [list {${PREFIX}} $::PREFIX] $filter]
}

waive_violation -add {ocah_sep_ReserveName} -comment {Error is meant for flagging reserved words in VHDL -- not relevant since not intended to port it to VHDL. Created by nbetik on 26-Feb-2026} -filter {(Module =~ "*")} -app { lint } -tag { ReserveName } -user { nbetik } -timestamp { 26-02-2026 14:27:03 }
waive_violation -add {ocah_sep_STARC05-1_1_1_1} -comment {Not functionally relevant, only important for code readability. Created by nbetik on 26-Feb-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND ((Module == "${PREFIX}axi_window_remap") OR (Module == "${PREFIX}el2_btb_tag_hash") OR (Module =~ "${PREFIX}entropy_ring_*_wrapper") OR (Module == "${PREFIX}prim_axi_user_override_struct") OR (Module == "${PREFIX}rvdff"))}] -app { lint } -tag { STARC05-1.1.1.1 } -user { nbetik } -timestamp { 26-02-2026 14:27:45 }

# Entropy source (intentional asynchronous design)
waive_violation -add {STARC05-1_4_3_2_ripple_divider} -comment {Asynchronous ripple frequency divider: each toggle-flop stage is intentionally clocked by the previous stage's Q output. Documented intentional violation of synchronous design rules. TT IP. Created by gchang on 09-Jun-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}prim_dffrxq") AND (DesignObjSignal =~ "*gen_div_stage*u_div_ff*") AND (DesignSeqNet =~ "*gen_div_stage*u_div_ff*")}] -app { lint } -tag { STARC05-1.4.3.2 } -user { gchang } -timestamp { 09-06-2026 14:10:33 }
waive_violation -add {CombLoop_entropy_ring_oscillator} -comment {Hand-instantiated ring oscillator (buffer/inverter delay chain with feedback) - the physical noise source for the TRNG. The combinational feedback loop is intentional and must not be synthesized/optimized; timing is broken via set_false_path SDC. Documented intentional violation. TT IP. Created by gchang on 09-Jun-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}entropy_ring_oscillator") AND (DesignNode =~ "*.feedback")}] -app { lint } -tag { CombLoop } -user { gchang } -timestamp { 09-06-2026 14:34:55 }
waive_violation -add {STARC05-1_4_3_4_entropy_source_noise_obs_sclk} -comment {TRNG raw-noise observation path. The asynchronously divided sampler clock is deliberately sampled as data into the clk_i domain so an edge detect (noise_obs_sample_stb) can strobe capture of one raw noise bit per sample period. Metastability is already handled by the 2-FF synchroniser on these very lines; removing this would delete a feature required for entropy certification. Created by gchang on 17-Aug-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}entropy_source") AND (NonClkPath =~ "*.noise_obs_raw_sclk") AND (Statement =~ "*noise_obs_sclk_meta <= noise_obs_raw_sclk;")}] -app { lint } -tag { STARC05-1.4.3.4 } -user { gchang } -timestamp { 17-08-2026 00:00:00 }

# Vendored VeeR EL2 AXI-to-AHB bridge (write-response channel)

waive_violation -add {CombLoop_report_pointer} -comment {CombLoopReport.rpt summary row violation just there to point to comb loop violations. It carries no information beyond the per-loop rows already reported. Waive. Created by gchang on 17-Aug-2026} -filter {(Goal == "lint_rtl_enhanced") AND (FILE_NAME_C == "CombLoopReport.rpt")} -app { lint } -tag { CombLoop } -user { gchang } -timestamp { 17-08-2026 00:00:00 }

#=======================================================================================================================
# TT PeakRDL-generated register blocks (explicit per-module waivers - exact Module match to avoid picking up non-PeakRDL modules)
#=======================================================================================================================
# STARC05-2.2.3.3 (FF assigned >1x in sequential always - default-then-override AXI-Lite handshake idiom, last-write-wins):
waive_violation -add {STARC05-2_2_3_3_abr_wrapper_key_reg} -comment {TT PeakRDL-generated register block (ABR ML-DSA/ML-KEM). Created by nbetik on 14-Jul-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}abr_wrapper_key_reg")}] -app { lint } -tag { STARC05-2.2.3.3 } -user { nbetik } -timestamp { 14-07-2026 10:00:00 }
waive_violation -add {STARC05-2_2_3_3_aes_wrapper_key_reg} -comment {TT PeakRDL-generated register block. FF assigned >1x in sequential always, last-write-wins, intentional. Generated RTL. TT IP. Created by gchang on 10-Jun-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}aes_wrapper_key_reg")}] -app { lint } -tag { STARC05-2.2.3.3 } -user { gchang } -timestamp { 10-06-2026 16:30:26 }
waive_violation -add {STARC05-2_2_3_3_alias_remap_reg} -comment {TT PeakRDL-generated register block. FF assigned >1x in sequential always, last-write-wins, intentional. Generated RTL. TT IP. Created by gchang on 10-Jun-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}alias_remap_reg")}] -app { lint } -tag { STARC05-2.2.3.3 } -user { gchang } -timestamp { 10-06-2026 16:30:26 }
waive_violation -add {STARC05-2_2_3_3_entropy_source_reg} -comment {TT PeakRDL-generated register block. FF assigned >1x in sequential always, last-write-wins, intentional. Generated RTL. TT IP. Created by gchang on 10-Jun-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}entropy_source_reg")}] -app { lint } -tag { STARC05-2.2.3.3 } -user { gchang } -timestamp { 10-06-2026 16:30:26 }
waive_violation -add {STARC05-2_2_3_3_filter_ctrl_reg} -comment {TT PeakRDL-generated register block. FF assigned >1x in sequential always, last-write-wins, intentional. Generated RTL. TT IP. Created by gchang on 10-Jun-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}filter_ctrl_reg")}] -app { lint } -tag { STARC05-2.2.3.3 } -user { gchang } -timestamp { 10-06-2026 16:30:26 }
waive_violation -add {STARC05-2_2_3_3_hmac_wrapper_key_reg} -comment {TT PeakRDL-generated register block. FF assigned >1x in sequential always, last-write-wins, intentional. Generated RTL. TT IP. Created by gchang on 10-Jun-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}hmac_wrapper_key_reg")}] -app { lint } -tag { STARC05-2.2.3.3 } -user { gchang } -timestamp { 10-06-2026 16:30:26 }
waive_violation -add {STARC05-2_2_3_3_kmac_wrapper_key_reg} -comment {TT PeakRDL-generated register block. FF assigned >1x in sequential always, last-write-wins, intentional. Generated RTL. TT IP. Created by gchang on 10-Jun-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}kmac_wrapper_key_reg")}] -app { lint } -tag { STARC05-2.2.3.3 } -user { gchang } -timestamp { 10-06-2026 16:30:26 }
waive_violation -add {STARC05-2_2_3_3_km_csr_reg} -comment {TT PeakRDL-generated register block. FF assigned >1x in sequential always, last-write-wins, intentional. Generated RTL. TT IP. Created by gchang on 10-Jun-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}km_csr_reg")}] -app { lint } -tag { STARC05-2.2.3.3 } -user { gchang } -timestamp { 10-06-2026 16:30:26 }
waive_violation -add {STARC05-2_2_3_3_km_drbg_sampler_reg} -comment {TT PeakRDL-generated register block. FF assigned >1x in sequential always, last-write-wins, intentional. Generated RTL. TT IP. Created by gchang on 10-Jun-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}km_drbg_sampler_reg")}] -app { lint } -tag { STARC05-2.2.3.3 } -user { gchang } -timestamp { 10-06-2026 16:30:26 }
waive_violation -add {STARC05-2_2_3_3_km_kpv_reg} -comment {TT PeakRDL-generated register block. FF assigned >1x in sequential always, last-write-wins, intentional. Generated RTL. TT IP. Created by gchang on 10-Jun-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}km_kpv_reg")}] -app { lint } -tag { STARC05-2.2.3.3 } -user { gchang } -timestamp { 10-06-2026 16:30:26 }
waive_violation -add {STARC05-2_2_3_3_km_mailbox_km_reg} -comment {TT PeakRDL-generated register block. FF assigned >1x in sequential always, last-write-wins, intentional. Generated RTL. TT IP. Created by gchang on 10-Jun-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}km_mailbox_km_reg")}] -app { lint } -tag { STARC05-2.2.3.3 } -user { gchang } -timestamp { 10-06-2026 16:30:26 }
waive_violation -add {STARC05-2_2_3_3_km_mailbox_sep_reg} -comment {TT PeakRDL-generated register block. FF assigned >1x in sequential always, last-write-wins, intentional. Generated RTL. TT IP. Created by gchang on 10-Jun-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}km_mailbox_sep_reg")}] -app { lint } -tag { STARC05-2.2.3.3 } -user { gchang } -timestamp { 10-06-2026 16:30:26 }
waive_violation -add {STARC05-2_2_3_3_otbn_wrapper_key_reg} -comment {TT PeakRDL-generated register block. FF assigned >1x in sequential always, last-write-wins, intentional. Generated RTL. TT IP. Created by gchang on 10-Jun-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}otbn_wrapper_key_reg")}] -app { lint } -tag { STARC05-2.2.3.3 } -user { gchang } -timestamp { 10-06-2026 16:30:26 }
waive_violation -add {STARC05-2_2_3_3_output_remap_reg} -comment {TT PeakRDL-generated register block. FF assigned >1x in sequential always, last-write-wins, intentional. Generated RTL. TT IP. Created by gchang on 10-Jun-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}output_remap_reg")}] -app { lint } -tag { STARC05-2.2.3.3 } -user { gchang } -timestamp { 10-06-2026 16:30:26 }
waive_violation -add {STARC05-2_2_3_3_sep_cpu_ctrl_reg} -comment {TT PeakRDL-generated register block. FF assigned >1x in sequential always, last-write-wins, intentional. Generated RTL. TT IP. Created by gchang on 10-Jun-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}sep_cpu_ctrl_reg")}] -app { lint } -tag { STARC05-2.2.3.3 } -user { gchang } -timestamp { 10-06-2026 16:30:26 }
waive_violation -add {STARC05-2_2_3_3_sep_lifecycle_ctrl_reg} -comment {TT PeakRDL-generated register block. FF assigned >1x in sequential always, last-write-wins, intentional. Generated RTL. TT IP. Created by gchang on 10-Jun-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}sep_lifecycle_ctrl_reg")}] -app { lint } -tag { STARC05-2.2.3.3 } -user { gchang } -timestamp { 10-06-2026 16:30:26 }
waive_violation -add {STARC05-2_2_3_3_sep_reset_ctrl_reg} -comment {TT PeakRDL-generated register block. FF assigned >1x in sequential always, last-write-wins, intentional. Generated RTL. TT IP. Created by gchang on 10-Jun-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}sep_reset_ctrl_reg")}] -app { lint } -tag { STARC05-2.2.3.3 } -user { gchang } -timestamp { 10-06-2026 16:30:26 }
waive_violation -add {STARC05-2_2_3_3_sep_scratch_reg} -comment {TT PeakRDL-generated register block. FF assigned >1x in sequential always, last-write-wins, intentional. Generated RTL. TT IP. Created by gchang on 10-Jun-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}sep_scratch_reg")}] -app { lint } -tag { STARC05-2.2.3.3 } -user { gchang } -timestamp { 10-06-2026 16:30:26 }
waive_violation -add {STARC05-2_2_3_3_spi_controller_reg} -comment {TT PeakRDL-generated register block. FF assigned >1x in sequential always, last-write-wins, intentional. Generated RTL. TT IP. Created by gchang on 10-Jun-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}spi_controller_reg")}] -app { lint } -tag { STARC05-2.2.3.3 } -user { gchang } -timestamp { 10-06-2026 16:30:26 }
# STARC05-3.3.1.4b (no async set/reset)
waive_violation -add {STARC05-3_3_1_4b_km_csr_reg} -comment {TT PeakRDL-generated key_manager register block. Flagged for no async reset, but there is a sync reset. Intentional - no async reset by design per project preference to limit async resets. TT IP. Created by gchang on 09-Jun-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}km_csr_reg")}] -app { lint } -tag { STARC05-3.3.1.4b } -user { gchang } -timestamp { 09-06-2026 14:03:55 }
waive_violation -add {STARC05-3_3_1_4b_km_drbg_sampler_reg} -comment {TT PeakRDL-generated key_manager register block. Flagged for no async reset, but there is a sync reset. Intentional - no async reset by design per project preference to limit async resets. TT IP. Created by gchang on 09-Jun-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}km_drbg_sampler_reg")}] -app { lint } -tag { STARC05-3.3.1.4b } -user { gchang } -timestamp { 09-06-2026 14:03:55 }
waive_violation -add {STARC05-3_3_1_4b_km_kpv_reg} -comment {TT PeakRDL-generated key_manager register block. Flagged for no async reset, but there is a sync reset. Intentional - no async reset by design per project preference to limit async resets. TT IP. Created by gchang on 09-Jun-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}km_kpv_reg")}] -app { lint } -tag { STARC05-3.3.1.4b } -user { gchang } -timestamp { 09-06-2026 14:03:55 }
waive_violation -add {STARC05-3_3_1_4b_km_mailbox_km_reg} -comment {TT PeakRDL-generated key_manager register block. Flagged for no async reset, but there is a sync reset. Intentional - no async reset by design per project preference to limit async resets. TT IP. Created by gchang on 09-Jun-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}km_mailbox_km_reg")}] -app { lint } -tag { STARC05-3.3.1.4b } -user { gchang } -timestamp { 09-06-2026 14:03:55 }
# STARC05-3.3.1.4b (no async set/reset)
waive_violation -add {STARC05-3_3_1_4b_aes_wrapper_key_reg} -comment {TT PeakRDL-generated key-register blocks. Confirmed in the RDL source: key data is INTENTIONALLY unreset by design - "No reset: key data should power up random/undefined for security". The safety-relevant control bit KEY_CTRL.KEY_VALID has reset=1'b0 (resets to invalid at power-up), so only the key data is unreset. Generated RTL. Benign / intended security behavior. TT IP. Created by gchang on 12-Jun-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}aes_wrapper_key_reg") AND (Signal =~ "field_storage.KEY_SHARE*.data.value*")}] -app { lint } -tag { STARC05-3.3.1.4b } -user { gchang } -timestamp { 12-06-2026 14:03:09 }
waive_violation -add {STARC05-3_3_1_4b_hmac_wrapper_key_reg} -comment {TT PeakRDL-generated key-register blocks. Confirmed in the RDL source: key data is INTENTIONALLY unreset by design - "No reset: key data should power up random/undefined for security". The safety-relevant control bit KEY_CTRL.KEY_VALID has reset=1'b0 (resets to invalid at power-up), so only the key data is unreset. Generated RTL. Benign / intended security behavior. TT IP. Created by gchang on 12-Jun-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}hmac_wrapper_key_reg") AND (Signal =~ "field_storage.KEY_SHARE*.data.value*")}] -app { lint } -tag { STARC05-3.3.1.4b } -user { gchang } -timestamp { 12-06-2026 14:03:09 }
waive_violation -add {STARC05-3_3_1_4b_kmac_wrapper_key_reg} -comment {TT PeakRDL-generated key-register blocks. Confirmed in the RDL source: key data is INTENTIONALLY unreset by design - "No reset: key data should power up random/undefined for security". The safety-relevant control bit KEY_CTRL.KEY_VALID has reset=1'b0 (resets to invalid at power-up), so only the key data is unreset. Generated RTL. Benign / intended security behavior. TT IP. Created by gchang on 12-Jun-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}kmac_wrapper_key_reg") AND (Signal =~ "field_storage.KEY_SHARE*.data.value*")}] -app { lint } -tag { STARC05-3.3.1.4b } -user { gchang } -timestamp { 12-06-2026 14:03:09 }
waive_violation -add {STARC05-3_3_1_4b_otbn_wrapper_key_reg} -comment {TT PeakRDL-generated key-register blocks. Confirmed in the RDL source: key data is INTENTIONALLY unreset by design - "No reset: key data should power up random/undefined for security". The safety-relevant control bit KEY_CTRL.KEY_VALID has reset=1'b0 (resets to invalid at power-up), so only the key data is unreset. Generated RTL. Benign / intended security behavior. TT IP. Created by gchang on 12-Jun-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}otbn_wrapper_key_reg") AND (Signal =~ "field_storage.KEY_SHARE*.data.value*")}] -app { lint } -tag { STARC05-3.3.1.4b } -user { gchang } -timestamp { 12-06-2026 14:03:09 }
waive_violation -add {STARC05-3_3_1_4b_abr_wrapper_key_reg} -comment {TT PeakRDL-generated key-register block (ABR ML-DSA/ML-KEM seeds). Key data is INTENTIONALLY unreset by design (key data should power up random/undefined for security); the KEY_VALID control bit resets to invalid, so only key data is unreset. Created by nbetik on 14-Jul-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}abr_wrapper_key_reg") AND (Signal =~ "field_storage.*KEY_SHARE*.data.value*")}] -app { lint } -tag { STARC05-3.3.1.4b } -user { nbetik } -timestamp { 14-07-2026 10:00:00 }

# W193 (empty statement - trailing semicolon after endpackage in generated address-map packages)

#=======================================================================================================================
# Hand-written key_manager / entropy modules (NOT PeakRDL-generated) - precise per-module waivers
#=======================================================================================================================
# STARC05-2.2.3.3 (the only genuine hand-written hits; generated *_reg blocks are covered by the PeakRDL group above):
waive_violation -add {STARC05-2_2_3_3_km_mailbox} -comment {FF assigned >1x in sequential always; last-write-wins gives clear-over-set priority when a write-accept and transaction-complete coincide. Intentional, not a double-drive. Hand-written TT IP. Created by gchang on 17-Jun-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}km_mailbox")}] -app { lint } -tag { STARC05-2.2.3.3 } -user { gchang } -timestamp { 17-06-2026 15:38:31 }
waive_violation -add {STARC05-2_2_3_3_km_drbg_sampler} -comment {FF assigned >1x in sequential always, last-write-wins (default-then-override, e.g. slot_done <= 0 default, <= 1 when data_read_done). Intentional, not a double-drive. Hand-written TT IP. Created by gchang on 17-Jun-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}km_drbg_sampler")}] -app { lint } -tag { STARC05-2.2.3.3 } -user { gchang } -timestamp { 17-06-2026 15:38:31 }
# STARC05-3.3.1.4b (datapath-vs-control reset pattern, FR-0000-149 - datapath regs deliberately left unreset, gated by reset control bits):
waive_violation -add {STARC05-3_3_1_4b_km_drbg_sampler_slot_rdata} -comment {Datapath reg slot_rdata lacks async set/reset by design; gated by control signals that do have async reset. Control-vs-datapath reset pattern per FR-0000-149. Benign by design. TT IP. Created by gchang on 12-Jun-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}km_drbg_sampler") AND (Signal == "slot_rdata[31:0]")}] -app { lint } -tag { STARC05-3.3.1.4b } -user { gchang } -timestamp { 12-06-2026 13:49:59 }
waive_violation -add {STARC05-3_3_1_4b_km_drbg_sampler_prefetch_data_reg} -comment {Datapath reg prefetch_data_reg lacks async set/reset by design; gated by control signals that do have async reset. Control-vs-datapath reset pattern per FR-0000-149. Benign by design. TT IP. Created by gchang on 12-Jun-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}km_drbg_sampler") AND (Signal == "prefetch_data_reg[31:0]")}] -app { lint } -tag { STARC05-3.3.1.4b } -user { gchang } -timestamp { 12-06-2026 13:49:59 }
waive_violation -add {STARC05-3_3_1_4b_km_drbg_sampler_prefetch_word_acc} -comment {Datapath reg prefetch_word_acc lacks async set/reset by design; gated by control signals that do have async reset. Control-vs-datapath reset pattern per FR-0000-149. Benign by design. TT IP. Created by gchang on 12-Jun-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}km_drbg_sampler") AND (Signal == "prefetch_word_acc[31:0]")}] -app { lint } -tag { STARC05-3.3.1.4b } -user { gchang } -timestamp { 12-06-2026 13:49:59 }
waive_violation -add {STARC05-3_3_1_4b_km_drbg_sampler_word_reg} -comment {Datapath reg word_reg lacks async set/reset by design; gated by control signals that do have async reset. Control-vs-datapath reset pattern per FR-0000-149. Benign by design. TT IP. Created by gchang on 12-Jun-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}km_drbg_sampler") AND (Signal == "word_reg[31:0]")}] -app { lint } -tag { STARC05-3.3.1.4b } -user { gchang } -timestamp { 12-06-2026 13:49:59 }
waive_violation -add {STARC05-3_3_1_4b_entropy_decorrelator} -comment {Data lacks async set/reset by design, as they are gated by control signals that do have async reset. Control-vs-datapath reset pattern per FR-0000-149. Benign by design. TT IP. Created by gchang on 12-Jun-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}entropy_decorrelator") AND (Signal == "entropy_byte_sample_o[7:0]")}] -app { lint } -tag { STARC05-3.3.1.4b } -user { gchang } -timestamp { 12-06-2026 17:11:32 }
waive_violation -add {STARC05-3_3_1_4b_prim_clk_counter} -comment {Uses sync reset instead of async reset by design, per preference to use less async resets. Benign. TT IP. Created by gchang on 12-Jun-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}prim_clk_counter")}] -app { lint } -tag { STARC05-3.3.1.4b } -user { gchang } -timestamp { 12-06-2026 12:02:19 }
waive_violation -add {STARC05-3_3_1_4b_prim_flop_3sync} -comment {3-stage CDC synchronizer (q_d/q_dd/q_ddd) has explicit sync reset but no async reset. Sync-only is the canonical CDC pattern - async reset on a CDC flop introduces a reset-domain-crossing hazard. Created by nbetik on 14-Jul-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}prim_flop_3sync") AND (Signal =~ "q_d*")}] -app { lint } -tag { STARC05-3.3.1.4b } -user { nbetik } -timestamp { 14-07-2026 10:00:00 }
waive_violation -add {STARC05-3_3_1_4b_efuse_guard} -comment {efuse_guard err status flop has an intentional SYNCHRONOUS reset (if(!rst_ni) inside always_ff @(posedge clk_i)); no async reset by design, per project preference to limit async resets. Created by nbetik on 14-Jul-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}efuse_guard") AND (Signal == "err")}] -app { lint } -tag { STARC05-3.3.1.4b } -user { nbetik } -timestamp { 14-07-2026 10:00:00 }
waive_violation -add {STARC05-3_3_1_4b_entropy_fifo_mem} -comment {entropy_fifo storage array mem[] intentionally unreset (entries are written before read; the pointers/validity track it), only control/pointers need reset. Same rationale as the prim_fifo waiver. Created by nbetik on 14-Jul-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}entropy_fifo") AND (Signal =~ "mem*")}] -app { lint } -tag { STARC05-3.3.1.4b } -user { nbetik } -timestamp { 14-07-2026 10:00:00 }
waive_violation -add {STARC05-3_3_1_4b_sep_efuse_wrapper} -comment {sep_efuse_wrapper flops (fuse_sense_done_1dly, reset_cycle_cnt, secure_tm) have intentional SYNCHRONOUS reset only (always_ff @(posedge clk_i) with if(!rst_ni)); no async reset by design, per project preference to limit async resets. Created by nbetik on 14-Jul-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}sep_efuse_wrapper") AND ((Signal == "fuse_sense_done_1dly") OR (Signal =~ "reset_cycle_cnt*") OR (Signal =~ "secure_tm*"))}] -app { lint } -tag { STARC05-3.3.1.4b } -user { nbetik } -timestamp { 14-07-2026 10:00:00 }

# STARC05-2.3.4.2 (initial construct used - assertion-only initial blocks, non-synthesizable, benign)
waive_violation -add {STARC05-2_3_4_2_memory_interface} -comment {initial block only used for assertions, which are not synthesized. Created by gchang on 11-Jun-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}memory_interface")}] -app { lint } -tag { STARC05-2.3.4.2 } -user { gchang } -timestamp { 11-06-2026 18:16:22 }
waive_violation -add {STARC05-2_3_4_2_sep_entropy_fifo} -comment {Initial block only used for assertions only, not synthesized. Created by gchang on 17-Aug-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}sep_entropy_fifo")}] -app { lint } -tag { STARC05-2.3.4.2 } -user { gchang } -timestamp { 17-08-2026 00:00:00 }
waive_violation -add {STARC05-2_2_3_3_sep_entropy_fifo_recv} -comment {Default then override, last write wins idiom. Cosmetic coding style. Waiving as its more readable currently than restructuring. Created by gchang on 17-Aug-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}sep_entropy_fifo") AND (Clock_Register =~ "*_recv_q")}] -app { lint } -tag { STARC05-2.2.3.3 } -user { gchang } -timestamp { 17-08-2026 00:00:00 }

# STARC05-1.3.1.3 (set/reset used as data/clock) - reset used as both reset + functional select/data.
waive_violation -add {STARC05-1_3_1_3_km_reset_conditioner} -comment {Reset-as-data is for synchronous reset condition in flop. The conditioner warm-reset output (rst_warm_sync_no) is intentionally consumed as a sync reset by downstream flops. Created by gchang on 15-Jun-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}km_reset_conditioner") AND (SeqSetRstNet =~ "*u_sep_crypto.u_key_manager_s3c_scan.u_reset_conditioner.rst_warm_sync_no") AND (DesignSeqNet =~ "*u_sep_crypto.u_key_manager_s3c_scan.u_xbar.u_axi_lite_xbar.gen_slv_port_demux[0].i_axi_lite_demux.gen_demux.lock_aw_valid_q")}] -app { lint } -tag { STARC05-1.3.1.3 } -user { gchang } -timestamp { 15-06-2026 11:06:55 }
waive_violation -add {STARC05-1_3_1_3_prim_metastab_hardened_dffr} -comment {The set/reset-used-as-data-or-clock pattern is inherent to this cell's purpose. Benign / intended CDC reset synchronization. TT IP. Created by gchang on 15-Jun-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}prim_metastab_hardened_dffr") AND (SeqSetRstNet =~ "*u_sep_system_peripherals.u_sep_system_csr.u_reference_counter_counter.u_sync_refclk_cnt_done.u_dest.u_src_reset_n_sync.gen_rst_sync_stage[2].u_sync_dffr.q_d") AND (DesignSeqNet =~ "*u_sep_system_peripherals.u_sep_system_csr.u_reference_counter_counter.u_sync_refclk_cnt_done.u_dest.u_sync3.q_ddd")}] -app { lint } -tag { STARC05-1.3.1.3 } -user { gchang } -timestamp { 15-06-2026 11:11:12 }
waive_violation -add {STARC05-1_3_1_3_prim_stdmux2_clk_counter} -comment {Reset-as-data is for synchronous reset condition in flop. Intentional. Created by gchang on 16-Jun-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}prim_stdmux2") AND (SeqSetRstNet =~ "*u_sep_system_peripherals.u_sep_system_csr.u_reference_counter_counter.u_sync_reset_n.u_sync_rst_n_bypass.u_rst_bypassmux.o_Y[0]") AND (DesignSeqNet =~ "*u_sep_system_peripherals.u_sep_system_csr.u_reference_counter_counter.u_sync_cnt_en.i_dst.ack_dst_q")}] -app { lint } -tag { STARC05-1.3.1.3 } -user { gchang } -timestamp { 16-06-2026 00:00:00 }

waive_violation -add {STARC05-1_3_1_3_prim_flop_km} -comment {Not a real error. Reset-as-data is for synchronous reset condition in flop. Created by gchang on 16-Jun-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}prim_flop") AND (SeqSetRstNet =~ "*u_sep_crypto.u_key_manager_s3c_scan.u_reset_conditioner.u_cold_rst_sync.u_sync.u_sync_2.q_o[0]") AND (DesignSeqNet =~ "*u_sep_crypto.u_key_manager_s3c_scan.wipe_event_d")}] -app { lint } -tag { STARC05-1.3.1.3 } -user { gchang } -timestamp { 16-06-2026 00:00:00 }
waive_violation -add {STARC05-1_3_1_3_prim_clock_mux2_efuse} -comment {Synchronized reset from u_reset_n_sync; tagged async only because it traverses the DFT scan-bypass mux (g_scan_mux) before resetting the efuse program-interface state. Reset is properly synchronized. Created by nbetik on 14-Jul-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}prim_clock_mux2") AND (SeqSetRstNet =~ "*u_sep_crypto.u_sep_efuse_wrapper.u_efuse_interface_controller.u_reset_n_sync.g_scan_mux.u_scan_mux.clk_o") AND (DesignSeqNet =~ "*u_sep_crypto.u_sep_efuse_wrapper.u_efuse_interface_controller.u_efuse_program_interface.program_state_q*")}] -app { lint } -tag { STARC05-1.3.1.3 } -user { nbetik } -timestamp { 14-07-2026 10:00:00 }
waive_violation -add {STARC05-1_3_1_3_prim_clock_mux2_km_cold} -comment {Synchronized cold reset from u_cold_rst_sync; tagged async only because it traverses the DFT scan-bypass mux (g_scan_mux) before resetting wipe_event_d. Reset is properly synchronized. Created by nbetik on 14-Jul-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}prim_clock_mux2") AND (SeqSetRstNet =~ "*u_sep_crypto.u_key_manager_s3c_scan.u_reset_conditioner.u_cold_rst_sync.g_scan_mux.u_scan_mux.clk_o") AND (DesignSeqNet =~ "*u_sep_crypto.u_key_manager_s3c_scan.wipe_event_d")}] -app { lint } -tag { STARC05-1.3.1.3 } -user { nbetik } -timestamp { 14-07-2026 10:00:00 }
waive_violation -add {checkIOPinConnectedToNet_km_csr} -comment {The linter sees print_enable.next as a pin not connected to any net, true but intentional: it is a simulation-only debug knob (VUART printf gate), driven only by the testbench. In real hardware it has no driver, no flop, and no consumer (the whole VUART is tied off), so the dangling signal can't affect anything. Benign by design. TT IP. No-flop confirmed: grep field_storage.*print_enable in km_csr_reg.sv returns 0 (RDL sw=r/hw=w no-we -> read combinationally via .next). Created by gchang on 15-Jun-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}km_csr") AND (ObjInputPin =~ "*VUART_STATUS.print_enable.next*")}] -app { lint } -tag { checkIOPinConnectedToNet } -user { gchang } -timestamp { 15-06-2026 11:39:49 }
waive_violation -add {W287a_km_csr} -comment {The linter sees print_enable.next as an input that nothing drives, true but intentional: it is a simulation-only debug knob (VUART printf gate), driven only by the testbench. In real hardware it has no driver, no flop, and no consumer (the whole VUART is tied off), so the dangling signal can't affect anything. Benign by design. TT IP. No-flop confirmed: grep field_storage.*print_enable in km_csr_reg.sv returns 0 (RDL sw=r/hw=w no-we -> read combinationally via .next). Created by gchang on 17-Jun-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}km_csr") AND (Signal =~ "*VUART_STATUS.print_enable.next*")}] -app { lint } -tag { W287a } -user { gchang } -timestamp { 17-06-2026 15:17:22 }

# OpenTitan coverage pragma (present in vendored OpenTitan RTL and TT-derived code)
waive_violation -add {UnrecSynthDir-ML_coverage_pragma} -comment {Pragma coverage off/on is an OpenTitan coverage-tool directive (used in vendored OpenTitan RTL and TT-derived code). Not a synthesis pragma - no functional or synthesis impact; VC SpyGlass simply does not recognize it. Created by gchang on 09-Jun-2026} -filter {(Goal == "lint_rtl_enhanced") AND (Statement =~ "*pragma coverage*")} -app { lint } -tag { UnrecSynthDir-ML } -user { gchang } -timestamp { 09-06-2026 14:54:49 }
waive_violation -add {W336_prim_clkgater} -comment {Intentional clock-gate latch: standard behavioral ICG model that latches enable while clock is low to prevent glitches on the gated clock. Blocking is the conventional always_latch idiom. Benign / intended clock-gating behavior. TT IP. Created by gchang on 16-Jun-2026.} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}prim_clkgater") AND (HDL_STATEMENT =~ "latched_en =*en_i*")}] -app { lint } -tag { W336 } -user { gchang } -timestamp { 16-06-2026 00:00:00 }
waive_violation -add {ImproperRangeIndex-ML_km_drbg_sampler} -comment {On w[8*pos +: 8] where pos is logic [2:0] - SpyGlass sizes 8*pos at 6 bits, w needs only a 5-bit base. The pack_bytes function has an explicit guard pos < 3'd4, so pos is always in {0,1,2,3. Created by gchang on 16-Jun-2026}, making 8*pos in {0,8,16,24} and every slice in range. Benign width-syntax flag, no real out-of-bounds risk. TT IP. Created by gchang on 16-Jun-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}km_drbg_sampler") AND (NodeName == "w") AND (RTL_EXPRESSION =~ "*pos*")}] -app { lint } -tag { ImproperRangeIndex-ML } -user { gchang } -timestamp { 16-06-2026 00:00:00 }
waive_violation -add {STARC05-3_3_1_4b_prim_sync3_pulse} -comment {Explicit sync reset but no async reset. Sync-only is the canonical CDC handshake pattern - async reset on a CDC flop introduces a reset-domain-crossing hazard. TT IP. Created by gchang on 16-Jun-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module =~ "${PREFIX}prim_sync3_pulse_*") AND (Signal =~ "toggle*")}] -app { lint } -tag { STARC05-3.3.1.4b } -user { gchang } -timestamp { 16-06-2026 00:00:00 }
waive_violation -add {STARC05-3_3_1_4b_km_kpv_regfile} -comment {Intentionally unreset per FR-0000-149: "key data should power up random/undefined for security". A synchronous wipe_i input clears all entries on demand. TT IP. Created by gchang on 16-Jun-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}km_kpv_regfile") AND (Signal == "mem[1023:0][31:0]")}] -app { lint } -tag { STARC05-3.3.1.4b } -user { gchang } -timestamp { 16-06-2026 00:00:00 }
waive_violation -add {W216_km_kpv} -comment {Loop bounds guarantee i < NUM_SLOTS, so the SLOT_W'(i) narrowing of the loop index is definitively in range. Benign loop-bounded int part-select. TT IP. Created by gchang on 16-Jun-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}km_kpv") AND (Statement =~ "*km_ext_slot*")}] -app { lint } -tag { W216 } -user { gchang } -timestamp { 16-06-2026 00:00:00 }
waive_violation -add {STARC05-3_3_1_4b_efuse_token_processing} -comment {Flagged for no async reset, but there is a sync reset (output-register stage for the token-compare results; flops properly reset to '0). Intentional - no async reset by design per project preference to limit async resets. TT IP. Created by gchang on 19-Jun-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}efuse_token_processing") AND (Signal =~ "*token_match_q*")}] -app { lint } -tag { STARC05-3.3.1.4b } -user { gchang } -timestamp { 19-06-2026 11:28:43 }
waive_violation -add {STARC05-3_3_1_4b_efuse_token_processing_fault_sticky} -comment {Flagged for no async reset, but there is a sync reset. Intentional per project preference to limit async resets. TT IP. Created by gchang on 03-Sep-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}efuse_token_processing") AND (Signal =~ "*token_match_fault_sticky_q*")}] -app { lint } -tag { STARC05-3.3.1.4b } -user { gchang } -timestamp { 03-09-2026 00:00:00 }
waive_violation -add {STARC05-3_3_1_4b_km_kpv_regfile_mem} -comment {Key-parameter storage array, intentionally unreset by design - the RTL says NO RESET for security, power-up value is undefined/random. TT IP. Created by gchang on 03-Sep-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}km_kpv_regfile") AND (Signal =~ "*mem*")}] -app { lint } -tag { STARC05-3.3.1.4b } -user { gchang } -timestamp { 03-09-2026 00:00:00 }
waive_violation -add {STARC05-2_2_3_3_sep_entropy_fifo_rd_stage} -comment {FF assigned >1x in sequential always; last-write-wins gives a new read accept priority over the entropy_clear_i scrub when both coincide. Intentional, not a double-drive. Hand-written TT IP. Created by gchang on 03-Sep-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}sep_entropy_fifo") AND ((Statement =~ "*rd_data_q*") OR (Statement =~ "*rd_resp_q*"))}] -app { lint } -tag { STARC05-2.2.3.3 } -user { gchang } -timestamp { 03-09-2026 00:00:00 }
waive_violation -add {STARC05-3_3_1_4b_efuse_token_processing_raw} -comment {Data lacks async set/reset by design, as they are gated by control signals that do have async reset. Control-vs-datapath reset pattern per FR-0000-149. Benign by design. Created by gchang on 17-Aug-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}efuse_token_processing") AND (Signal =~ "*_token_raw_n0_scan*")}] -app { lint } -tag { STARC05-3.3.1.4b } -user { gchang } -timestamp { 17-08-2026 00:00:00 }
waive_violation -add {STARC05-1_3_1_3_sep_reset_ctrl_cpu_reset} -comment {Not a real error. Reset-as-data is for synchronous reset condition in flop. sep_cpu_reset_no is intentionally consumed as a sync reset by downstream flops. TT IP. Created by gchang on 19-Jun-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (SeqSetRstNet =~ "*u_sep_reset_ctrl.u_sep_cpu_rst_and*") AND (DesignSeqNet =~ "*u_sep_cpu.u_ifu_axi_demux.i_demux_simple.genblk1.lock_aw_valid_q")}] -app { lint } -tag { STARC05-1.3.1.3 } -user { gchang } -timestamp { 19-06-2026 11:57:46 }
waive_violation -add {STARC05-1_3_1_3_sep_reset_ctrl_reset_n} -comment {Not a real error. Reset-as-data is for synchronous reset condition in flop. sep_reset_n is intentionally consumed as a sync reset by downstream flops. TT IP. Created by gchang on 19-Jun-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}sep_reset_ctrl") AND (SeqSetRstNet =~ "*u_sep_reset_ctrl.sep_reset_n") AND (DesignSeqNet =~ "*u_sram_memory_interface.u_axi_to_mem.i_axi_to_detailed_mem.r_cnt_q[0]")}] -app { lint } -tag { STARC05-1.3.1.3 } -user { gchang } -timestamp { 19-06-2026 11:57:46 }
waive_violation -add {STARC05-1_3_1_3_efuse_sense_state_start_on_reset_release} -comment {The efuse sense FSM has no separate start signal: it reads rst_ni as data so it can leave StIdle when reset releases. Safe because rst_ni here is a synchronised reset, async assert and sync deassert through prim_sync_reset in smc_reset_sync, so it changes on a clk_i edge and the state register never samples it mid-transition. TT IP. Created by gchang on 11-Sep-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}sep") AND (SeqSetRstNet == "rst_ni") AND (DesignInstanceName =~ "*u_efuse_shadow_regs.efuse_sense_state_q.D*")}] -app { lint } -tag { STARC05-1.3.1.3 } -user { gchang } -timestamp { 11-09-2026 00:00:00 }
waive_violation -add {W123_efuse_shadow_regs_shadow_reg_preload} -comment {W123 (read but never set) on shadow_reg_preload - a SIMULATION-ONLY shadow-register preload array (loads shadow regs from a hex file to skip fuse-sense in sim). Written only inside `ifdef SIMULATION initial blocks; in synthesis it has no driver and is read only inside if(sim_skip_fuse_sense ...) branches where sim_skip_fuse_sense is hardwired 1'b0 (synthesis prunes those reads). Benign sim-only infrastructure, no hardware effect. TT IP. Created by gchang on 19-Jun-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}efuse_shadow_regs") AND (VariableName == "shadow_reg_preload")}] -app { lint } -tag { W123 } -user { gchang } -timestamp { 19-06-2026 14:30:00 }
waive_violation -add {STARC05-3_3_1_4b_efuse_mmr_reg} -comment {These data registers are flagged for lacking async set/reset. Intentional: the RDL defines the token data fields without a reset value, so PeakRDL generates them with no reset. Not an issue because the control bits (which DO reset) guarantee the data is never read before it is written. Generated RTL - regen overwrites. TT IP. Created by gchang on 19-Jun-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}efuse_mmr_reg") AND (Signal =~ "*_TOKEN_I.token.value*")}] -app { lint } -tag { STARC05-3.3.1.4b } -user { gchang } -timestamp { 19-06-2026 12:41:01 }
waive_violation -add {UndrivenInTerm-ML_efuse_shadow_regs_shadow_reg_preload} -comment {Undriven input terminal on shadow_reg_preload - a SIMULATION-ONLY shadow-register preload array (written only inside `ifdef SIMULATION initial blocks; undriven in synthesis and read only inside if(sim_skip_fuse_sense ...) branches where sim_skip_fuse_sense is hardwired 1'b0, which synthesis prunes). Same sim-only signal as the W123 waiver. Benign, no hardware effect. TT IP. Created by gchang on 19-Jun-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}efuse_shadow_regs") AND (DesignObjSignal =~ "*shadow_reg_preload*")}] -app { lint } -tag { UndrivenInTerm-ML } -user { gchang } -timestamp { 19-06-2026 14:45:00 }
waive_violation -add {UndrivenNet-ML_efuse_shadow_regs_shadow_reg_preload} -comment {Undriven net shadow_reg_preload - a SIMULATION-ONLY shadow-register preload array (written only inside `ifdef SIMULATION initial blocks; undriven in synthesis and read only inside if(sim_skip_fuse_sense ...) branches where sim_skip_fuse_sense is hardwired 1'b0, which synthesis prunes). Same sim-only signal as the W123 / UndrivenInTerm-ML waivers. Benign, no hardware effect. TT IP. Created by gchang on 19-Jun-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}efuse_shadow_regs") AND (DesignObjSignal =~ "*shadow_reg_preload*")}] -app { lint } -tag { UndrivenNet-ML } -user { gchang } -timestamp { 19-06-2026 14:50:00 }
waive_violation -add {STARC05-2_1_3_1_efuse_shadow_regs_word_idx} -comment {Helper function argument is zero-extended to match input. No information lost, safe. Created by gchang on 17-Aug-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}efuse_shadow_regs") AND (NodeType1 == "word_idx") AND (Exp_Size == "8") AND (ExprSize == "32")}] -app { lint } -tag { STARC05-2.1.3.1 } -user { gchang } -timestamp { 17-08-2026 00:00:00 }
waive_violation -add {ImproperRangeIndex-ML_efuse_shadow_class1_storage} -comment {Both the array index and size are computed from the same source of truth value CLASS1_SHADOW_RANGES, therefore the size and index always agree. So the range of values of the index always matches the array size. There are also assertions to validate. Created by gchang on 17-Aug-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}efuse_shadow_regs") AND (NodeName == "shadow_efuse_values_n0_scan") AND (RTL_EXPRESSION =~ "*class1_shadow_storage_idx*") AND (NewExprSize == "32")}] -app { lint } -tag { ImproperRangeIndex-ML } -user { gchang } -timestamp { 17-08-2026 00:00:00 }
waive_violation -add {ImproperRangeIndex-ML_efuse_shadow_normal_storage} -comment {Indexed by efuse_pkg::normal_shadow_storage_idx(), which returns a 32-bit int unsigned. The array is sized NumNormalShadowWords = NumShadowWords - ActualNumClass1ShadowWords, and the function subtracts exactly those same class-1 words from the incoming word index, so the result always lands inside the array. Covered by the same Class1ShadowRangesValid_A / Class1ShadowCountFits_A elaboration assertions. Created by gchang on 17-Aug-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}efuse_shadow_regs") AND (NodeName == "shadow_efuse_values") AND (RTL_EXPRESSION =~ "*normal_shadow_storage_idx*") AND (NewExprSize == "32")}] -app { lint } -tag { ImproperRangeIndex-ML } -user { gchang } -timestamp { 17-08-2026 00:00:00 }
waive_violation -add {SetBeforeRead-ML_efuse_token_digest_sha256_sticky} -comment {Intentional sticky HOLD-LATCHES (always_latch) that retain the SHA digest and its valid bit across cold reset (by design; see comments L166-167/L176). The flagged "read before set" is the latch's own hold path (x <= x), the latches are deliberately unreset so the value persists across cold reset. Benign: the valid bit (cleared by start_i) gates use of the digest, and a power-up garbage 256-bit digest cannot spuriously match the fused token. TT IP. Created by gchang on 19-Jun-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}efuse_token_digest_sha256") AND (Signal_Name =~ "*sticky_n0_scan*")}] -app { lint } -tag { SetBeforeRead-ML } -user { gchang } -timestamp { 19-06-2026 15:00:00 }
waive_violation -add {STARC05-2_11_3_1_sep_efuse_wrapper_reset_cycle_cnt} -comment {The lint tool thinks this is an FSM, but it's really just a counter. Writing a counter in one block is safe, no need to split it into different always blocks. TT IP. Created by gchang on 19-Jun-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}sep_efuse_wrapper") AND (Signal == "reset_cycle_cnt")}] -app { lint } -tag { STARC05-2.11.3.1 } -user { gchang } -timestamp { 19-06-2026 14:51:59 }

#=======================================================================================================================
# STARC05-2.3.4.2 (initial construct used)
#=======================================================================================================================

#=======================================================================================================================
# Misc. Waivers
#=======================================================================================================================
# STARC05-2.11.3.1 (comb+seq in same always block)
waive_violation -add {STARC05-2_11_3_1_entropy_source_downsample_count} -comment {downsample_count is a simple reload/decrement down-counter written in one always_ff, not a real mixed comb/seq FSM. Created by nbetik on 09-Jul-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}entropy_source") AND (Signal == "downsample_count")}] -app { lint } -tag { STARC05-2.11.3.1 } -user { nbetik } -timestamp { 09-07-2026 10:00:00 }
# W216 (int part-select)
waive_violation -add {W216_entropy_debug_monitor} -comment {Integer part-select of loop index i[$clog2(N)-1:0] driving *_binary_decode[i]; loop variable i is bounded by N (NISGNALS or FREQ_DIV_WIDTH) so the select is definitively in range. Created by nbetik on 09-Jul-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}entropy_debug_monitor") AND (Statement =~ "*binary_decode*")}] -app { lint } -tag { W216 } -user { nbetik } -timestamp { 09-07-2026 10:00:00 }

# W486 (RHS shift may exceed LHS width)
waive_violation -add {W486_scrambler_pkg_rol} -comment {scrambler_pkg rolN barrel-rotate: {d,d,d} replicate then shift the d_xtnd_s* staging regs, top WIDTH bits returned; shift-out of replicated bits is intentional. Scoped to the d_xtnd_s* shift stages so other shifts in the package still lint. Created by nbetik on 13-Jul-2026} -filter {(Goal == "lint_rtl_enhanced") AND (((LHSExpr == "d_xtnd_s0") AND (RHSExpr == "(d_xtnd << 1)")) OR ((LHSExpr == "d_xtnd_s1") AND (RHSExpr == "(d_xtnd_s0 << 2)")) OR ((LHSExpr == "d_xtnd_s2") AND (RHSExpr == "(d_xtnd_s1 << 4)")) OR ((LHSExpr == "d_xtnd_s3") AND (RHSExpr == "(d_xtnd_s2 << 8)")))} -app { lint } -tag { W486 } -user { nbetik } -timestamp { 13-07-2026 10:00:00 }
