# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2026 Tenstorrent USA, Inc.
#
# tclint-disable line-length

# For waiving violations on open-source 3rd party IP

#=======================================================================================================================
# RULE INFO:
#=======================================================================================================================
# STARC05-1_1_1_1: Module name should be the same as file name
# STARC05-3_3_1_4b: Flop should have async set or reset
# W362: Arithmetic comparison with unequal length
# W164b: LHS of assignment wider than RHS
# W116: Operand width mismatch in operator
# W416: Return type width is less than return value width in a function
# STARC05-2_1_3_1: width of function arguments must match width of function inputs
# W553: Different bits of a bus are driven in different combinational blocks
# W391: Module driven by both edges of a clock
# STARC05-2_10_6_1: Possible loss of carry or borrow in addition or subtraction when width of LHS = width of RHS
# W401: Clock generated internally in module
# W193: Empty statement (isolated semicolon)
# W123: Signal is read but not set
# W240: Input declared but not read
# STARC05-1_3_1_3: Async reset used as sync reset or non-reset
# STARC05-2_11_3_1: Sequential and combinational parts of FSM described in same "always" block
# W415: Signal has multiple drivers but is not declared a tri-state
# InferLatch: Latch inferred for signal
# W263: Case label width does not match selector width
# W239: Hierarchical references may not be synthesizable
# W146: Explicit named association recommended in instance references
# W238: Mixing combinational and sequential styles
# W342: Constant will be X-extended, value has fewer bits than size specification
# W443: Based number contains an X - has no meaning in synthesis
# W444: Tristate value specified
# NoAssignX-ML: RHS of assignment contains X
# STARC05-2_2_3_3: Flip-flop assigned more than once in a sequential always block
# W576: Logical operator used on a multibit value
# STARC05-2_1_4_5: Use bit-wise operator instead of logical operator on a multibit value
# STARC05-2_10_2_3: Logical negation used on a vector
# ImproperRangeIndex-ML: Index width larger than required for the array size
# STARC05-2_1_5_3: Conditional expression does not evaluate to a scalar
# STARC05-2_10_3_2a: Operand bit-width mismatch for operator
# W575: Logical NOT operator used on a multibit value
# W481a: Possibly unsynthesizable loop - step variable not used in condition
#=======================================================================================================================

# iDMA

# PULP AXI

#=======================================================================================================================
# Vendor module inventories
#=======================================================================================================================
# These lists scope third-party blanket waivers by MODULE rather than by file path.
#
# The lists are INCLUSIVE ON PURPOSE; a newly added vendor module is simply
# not waived, so it surfaces as a lint error and gets triaged.
#
# Regenerate after a vendor bump (paths below are the top-of-tree vendored layout):
#   grep -hoE '^[[:space:]]*module[[:space:]]+\w+' vendor/pulp-platform/axi/upstream/src/*.sv | awk '{print $2}' | sort -u
#   grep -hoE '^[[:space:]]*module[[:space:]]+\w+' vendor/tenstorrent/tt-picorv32/upstream/picorv32* | awk '{print $2}' | sort -u
#   grep -hoE '^[[:space:]]*module[[:space:]]+\w+' vendor/opentitan/upstream/hw/ip/otbn/**/*.sv | awk '{print $2}' | sort -u
#=======================================================================================================================
set VENDOR_PULP_AXI_MODULES {
    axi5_lite_demux axi5_lite_demux_brcst axi5_lite_demux_brcst_intf axi5_lite_demux_intf axi5_lite_mux
    axi5_lite_mux_brcst axi5_lite_mux_brcst_intf axi5_lite_mux_intf axi5_lite_to_axi5 axi5_lite_to_axi5_intf
    axi5_lite_xbar axi5_lite_xbar_brcst axi_atop_filter axi_atop_filter_intf axi_burst_counters
    axi_burst_splitter axi_burst_splitter_gran axi_burst_splitter_gran_ax_chan axi_burst_splitter_gran_counters
    axi_burst_unwrap axi_burst_unwrap_ax_chan axi_bus_compare axi_cdc axi_cdc_clearable axi_cdc_dst
    axi_cdc_dst_intf axi_cdc_intf axi_cdc_src axi_cdc_src_intf axi_chan_compare axi_chan_logger axi_cut
    axi_cut_intf axi_delayer axi_delayer_intf axi_demux axi_demux_id_counters axi_demux_intf axi_demux_simple
    axi_dumper axi_dumper_intf axi_dw_converter axi_dw_converter_intf axi_dw_downsizer axi_dw_upsizer
    axi_err_slv axi_fifo axi_fifo_delay_dyn axi_fifo_delay_dyn_intf axi_fifo_intf axi_from_mem axi_hidestrb
    axi_id_prepend axi_id_remap axi_id_remap_intf axi_id_remap_table axi_id_serialize axi_id_serialize_intf
    axi_interleaved_xbar axi_interleaved_xbar_intf axi_inval_filter axi_isolate axi_isolate_inner
    axi_isolate_intf axi_iw_converter axi_iw_converter_intf axi_join_intf axi_lfsr axi_lite_cdc_dst_intf
    axi_lite_cdc_intf axi_lite_cdc_src_intf axi_lite_cut_intf axi_lite_demux axi_lite_demux_intf
    axi_lite_dw_converter axi_lite_dw_converter_intf axi_lite_from_mem axi_lite_join_intf axi_lite_lfsr
    axi_lite_mailbox axi_lite_mailbox_intf axi_lite_mailbox_slave axi_lite_multicut_intf axi_lite_mux
    axi_lite_mux_intf axi_lite_regs axi_lite_regs_intf axi_lite_to_apb axi_lite_to_apb_intf axi_lite_to_axi
    axi_lite_to_axi_intf axi_lite_xbar axi_lite_xbar_intf axi_modify_address axi_modify_address_intf
    axi_multicut axi_multicut_intf axi_mux axi_mux_intf axi_opt_lfsr axi_rw_join axi_rw_split axi_serializer
    axi_serializer_intf axi_sim_mem axi_sim_mem_intf axi_sim_mem_multiport_intf axi_slave_compare axi_spill_regs
    axi_throttle axi_to_axi_lite axi_to_axi_lite_id_reflect axi_to_axi_lite_intf axi_to_detailed_mem
    axi_to_detailed_mem_intf axi_to_mem axi_to_mem_banked axi_to_mem_banked_intf axi_to_mem_interleaved
    axi_to_mem_interleaved_intf axi_to_mem_intf axi_to_mem_split axi_to_mem_split_intf axi_xbar axi_xbar_intf
    axi_xbar_unmuxed axi_xbar_unmuxed_intf axi_xp axi_xp_intf axi_zero_mem mem_stream_to_banks_detailed
    stream_fifo_delay_dyn
}
set VENDOR_PULP_AXI_DW_MODULES {
    axi_dw_converter axi_dw_converter_intf axi_dw_downsizer axi_dw_upsizer
}
set VENDOR_PICORV32_MODULES {
    picorv32 picorv32_axi picorv32_axi_adapter picorv32_pcpi_div picorv32_pcpi_fast_mul picorv32_pcpi_mul
    picorv32_regs picorv32_wb
}
set VENDOR_PICORV32_DIV_MODULES {
    picorv32_pcpi_div
}
set VENDOR_OTBN_MODULES {
    otbn otbn_alu_base otbn_alu_bignum otbn_controller otbn_core otbn_decoder otbn_instruction_fetch
    otbn_kmac_if otbn_loop_controller otbn_lsu otbn_mac_bignum otbn_mac_bignum_fsm otbn_mod_result_selector
    otbn_predecode otbn_reg_top otbn_rf_base otbn_rf_base_ff otbn_rf_bignum otbn_rf_bignum_ff otbn_rnd
    otbn_scramble_ctrl otbn_sec_add otbn_stack otbn_start_stop_control otbn_tracer otbn_vec_adder
    otbn_vec_multiplier otbn_vec_shifter otbn_vec_transposer
}
set VENDOR_ABR_COMPRESS_MODULES {
    compress_top compress_ctrl decompress_top decompress
}
set VENDOR_ABR_FSM_COUNTER_MODULES {
    sigdecode_h_ctrl ntt_ctrl
}

# Build an OR-of-equals Module predicate from a module-name list. Applies the packager module-name prefix when the
# ocah_smu auto-pull has set ::PREFIX; at subcomponent level ::PREFIX is unset or empty and the bare vendor names are
# used.
proc module_any { mods } {
    set p ""
    if { [info exists ::PREFIX] } { set p $::PREFIX }
    set parts {}
    foreach m $mods { lappend parts "(Module == \"${p}${m}\")" }
    return "([join $parts { OR }])"
}


#=======================================================================================================================
# Module-name prefix support
#=======================================================================================================================

if { ![info exists PREFIX] } {
    set PREFIX ""
}
# Substitute the literal ${PREFIX} token in a -filter expression with $PREFIX's
# value. Uses string map rather than brace interpolation so that $clog2, bus
# indices like [i], and embedded quotes inside the filter are preserved verbatim.
proc apply_prefix { filter } {
    return [string map [list {${PREFIX}} $::PREFIX] $filter]
}

waive_violation -add {SEP_W146_cdc_fifo_gray_dst} -comment {Created by nbetik on 27-Feb-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}cdc_fifo_gray_dst")}] -app { lint } -tag { W146 } -user { nbetik } -timestamp { 27-02-2026 15:46:58 }
waive_violation -add {SEP_W146_cdc_fifo_gray_src} -comment {Common cells component. Lint category is for visual cleanliness only. Created by nbetik on 27-Feb-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}cdc_fifo_gray_src")}] -app { lint } -tag { W146 } -user { nbetik } -timestamp { 27-02-2026 15:41:45 }
waive_violation -add {SEP_W193_axi_lite_mailbox_slave} -comment {PULP axi component. Lint category is for visual cleanliness only. Created by nbetik on 27-Feb-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}axi_lite_mailbox_slave")}] -app { lint } -tag { W193 } -user { nbetik } -timestamp { 27-02-2026 15:42:58 }
waive_violation -add {SEP_W193_axi_lite_to_apb} -comment {PULP axi component. Lint category is for visual cleanliness only. Created by nbetik on 27-Feb-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}axi_lite_to_apb")}] -app { lint } -tag { W193 } -user { nbetik } -timestamp { 27-02-2026 15:43:44 }
waive_violation -add {SEP_W193_axi_lite_from_mem} -comment {PULP axi component. Lint category is for visual cleanliness only. Created by nbetik on 27-Feb-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}axi_lite_from_mem")}] -app { lint } -tag { W193 } -user { nbetik } -timestamp { 27-02-2026 15:44:14 }
waive_violation -add {SEP_W193_axi_isolate_inner} -comment {PULP axi component. Lint category is for visual cleanliness only. Created by nbetik on 27-Feb-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}axi_isolate_inner")}] -app { lint } -tag { W193 } -user { nbetik } -timestamp { 27-02-2026 15:44:41 }
waive_violation -add {SEP_NoGenLabel-ML_axi_isolate} -comment {PULP axi component. Lint category is for visual cleanliness only. Created by nbetik on 27-Feb-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}axi_isolate")}] -app { lint } -tag { NoGenLabel-ML } -user { nbetik } -timestamp { 27-02-2026 15:45:42 }
waive_violation -add {SEP_NoGenLabel-ML_axi_err_slv} -comment {PULP axi component. Lint category is for visual cleanliness only. Created by nbetik on 27-Feb-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}axi_err_slv")}] -app { lint } -tag { NoGenLabel-ML } -user { nbetik } -timestamp { 27-02-2026 15:46:25 }
waive_violation -add {SEP_NoGenLabel-ML_axi_demux_simple} -comment {PULP AXI library axi_demux_simple. Unlabeled generate-if ("end else begin") - cosmetic/style only, makes elaborated names anonymous (genblk1, ...) but has no functional impact. 3rd party vendor IP shouldn't be modified. Created by gchang on 16-Jun-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}axi_demux_simple")}] -app { lint } -tag { NoGenLabel-ML } -user { gchang } -timestamp { 16-06-2026 00:00:00 }
waive_violation -add {SEP_NoGenLabel-ML_rvdffe} -comment {VeeR EL2 vendor flop helper rvdffe. Duplicate "genblock" label across generate-if branches - tools auto-disambiguate; cosmetic/hierarchical-naming concern only, no functional impact. 3rd party vendor IP shouldn't be modified. Created by gchang on 16-Jun-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}rvdffe")}] -app { lint } -tag { NoGenLabel-ML } -user { gchang } -timestamp { 16-06-2026 00:00:00 }
waive_violation -add {SEP_NoGenLabel-ML_el2} -comment {VeeR EL2 vendor core. Duplicate generate-block labels (e.g. "COMPARE") - tools auto-disambiguate; cosmetic/hierarchical-naming concern only, no functional impact. 3rd party vendor IP shouldn't be modified. Created by gchang on 16-Jun-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module =~ "${PREFIX}el2_*")}] -app { lint } -tag { NoGenLabel-ML } -user { gchang } -timestamp { 16-06-2026 00:00:00 }
waive_violation -add {SEP_W193_axi_burst_splitter} -comment {PULP axi component. Lint category is for visual cleanliness only. Created by nbetik on 27-Feb-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}axi_burst_splitter") AND (Statement == "      default: /*do nothing*/;")}] -app { lint } -tag { W193 } -user { nbetik } -timestamp { 27-02-2026 15:50:34 }
waive_violation -add {SEP_W193_axi_family} -comment {PULP AXI library. On default: ; do-nothing case defaults - intentional explicit defaults (avoid latch / document intent). Benign. 3rd party vendor IP shouldn't be modified. Created by gchang on 10-Jun-2026} -filter "(Goal == \"lint_rtl_enhanced\") AND [module_any $VENDOR_PULP_AXI_MODULES]" -app { lint } -tag { W193 } -user { gchang } -timestamp { 10-06-2026 14:39:45 }
waive_violation -add {SEP_STARC05-2_1_3_1_axi_family} -comment {PULP AXI library. Functions are sized for the maximum parameterized AXI width but called with the actual narrower widths; the narrower arguments zero-extend to the function input width, benign. Intentional parameterized-AXI width pattern. 3rd party vendor IP shouldn't be modified. Created by gchang on 11-Jun-2026} -filter "(Goal == \"lint_rtl_enhanced\") AND [module_any $VENDOR_PULP_AXI_MODULES]" -app { lint } -tag { STARC05-2.1.3.1 } -user { gchang } -timestamp { 11-06-2026 11:28:35 }
waive_violation -add {SEP_W362_axi} -comment {PULP AXI library. Arithmetic comparisons between parameterized-width AXI signals of unequal length (e.g. burst-length / beat-count counters); the narrower operand zero-extends and the values are range-bounded, so the extension never changes the result. Intentional parameterized-AXI width pattern. Benign. 3rd party vendor IP shouldn't be modified. Created by gchang on 11-Jun-2026} -filter "(Goal == \"lint_rtl_enhanced\") AND [module_any $VENDOR_PULP_AXI_MODULES]" -app { lint } -tag { W362 } -user { gchang } -timestamp { 11-06-2026 13:00:00 }
waive_violation -add {SEP_AutomaticFuncTask-ML_axi} -comment {PULP AXI library. Function/task not declared automatic. SystemVerilog defaults to static; the rule recommends automatic to avoid re-entrancy hazards, but a pure combinational function has no persistent local state to corrupt. Benign vendor coding style. 3rd party vendor IP shouldn't be modified. Created by gchang on 15-Jun-2026} -filter "(Goal == \"lint_rtl_enhanced\") AND [module_any $VENDOR_PULP_AXI_MODULES]" -app { lint } -tag { AutomaticFuncTask-ML } -user { gchang } -timestamp { 15-06-2026 11:52:51 }
waive_violation -add {SEP_W164b_axi_dw_burst_len} -comment {PULP AXI library. Burst_len is internally 9-bit to hold the beat count (AXI len+1, up to 256) used by the data-width-conversion logic; the 8-bit AxLEN zero-extends into the wider counter. Intentional parameterized-AXI width pattern. Benign. 3rd party vendor IP shouldn't be modified. Created by gchang on 11-Jun-2026} -filter "(Goal == \"lint_rtl_enhanced\") AND [module_any $VENDOR_PULP_AXI_DW_MODULES] AND (LHSExpr =~ \"*burst_len\")" -app { lint } -tag { W164b } -user { gchang } -timestamp { 11-06-2026 17:38:12 }
waive_violation -add {SEP_W164b_axi_dw_port_offset} -comment {PULP AXI library. The byte-offset is a full 32-bit variable assigned the low address bits selected by the parameterized strobe width; the narrow address slice zero-extends into it. Intentional parameterized-AXI width pattern. Benign. 3rd party vendor IP shouldn't be modified. Created by gchang on 11-Jun-2026} -filter "(Goal == \"lint_rtl_enhanced\") AND [module_any $VENDOR_PULP_AXI_DW_MODULES] AND (LHSExpr =~ \"*port_offset\")" -app { lint } -tag { W164b } -user { gchang } -timestamp { 11-06-2026 17:38:12 }

# axi_pkg width helper
waive_violation -add {SEP_STARC05-2_10_6_1_axi_pkg} -comment {PULP axi_pkg. ret_addr beat-address helper arithmetic (aligned_addr + i_beat*num_bytes); carry/borrow width flag only. Vendor IP unmodified. Created by nbetik on 14-Jul-2026} -filter {(Goal == "lint_rtl_enhanced") AND (((LHSExpr == "ret_addr") AND (RHSExpr == "(aligned_addr(addr,size) + (i_beat * num_bytes(size)))")))} -app { lint } -tag { STARC05-2.10.6.1 } -user { nbetik } -timestamp { 14-07-2026 10:00:00 }

# PULP common_cells
waive_violation -add {SEP_W116_addr_decode_dync} -comment {PULP common_cells. NAPOT match: operands (addr_i / addr_map_i[i].start_addr) compared against addr_map_i[i].end_addr, which is intentionally addr_width+1 bits (1b wider) so the map can express an exclusive upper bound; mismatched-width operands auto zero-extend. Fires at both elaborated address widths (32 vs 33, 56 vs 57). Benign parameterized address-decoder pattern. 3rd party vendor IP shouldn't be modified. Created by gchang on 11-Jun-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}addr_decode_dync") AND (RHSExpr == "addr_map_i[i].end_addr")}] -app { lint } -tag { W116 } -user { gchang } -timestamp { 11-06-2026 15:55:32 }
waive_violation -add {SEP_W362_addr_decode_dync} -comment {PULP common_cells. (addr_i < addr_map_i[i].end_addr), addr_i is 32b vs end_addr 33b. end_addr is intentionally addr_width+1 bits to express an exclusive upper bound up to 2^32; the narrower addr_i zero-extends for the compare. Fires at both elaborated address widths (32 vs 33, 56 vs 57). Benign parameterized address-decoder pattern. 3rd party vendor IP shouldn't be modified. Created by gchang on 12-Jun-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}addr_decode_dync") AND (RHSExpr == "addr_map_i[i].end_addr")}] -app { lint } -tag { W362 } -user { gchang } -timestamp { 12-06-2026 12:33:22 }
waive_violation -add {SEP_STARC05-2_3_4_2_addr_decode_dync} -comment {Initial block only used for assertions, which are not synthesized. PULP common_cells - 3rd party vendor IP shouldn't be modified. Created by gchang on 11-Jun-2026. } -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}addr_decode_dync")}] -app { lint } -tag { STARC05-2.3.4.2 } -user { gchang } -timestamp { 11-06-2026 18:17:14 }

# cf_math_pkg width helper
waive_violation -add {SEP_STARC05-2_10_6_1_cf_math_pkg} -comment {PULP common_cells cf_math_pkg. remainder helper arithmetic (remainder = remainder - divisor) in the elaboration-time gcd/width helper; carry/borrow width flag only. Vendor IP unmodified. Created by nbetik on 14-Jul-2026} -filter {(Goal == "lint_rtl_enhanced") AND (((LHSExpr == "remainder") AND (RHSExpr == "(remainder - divisor)")))} -app { lint } -tag { STARC05-2.10.6.1 } -user { nbetik } -timestamp { 14-07-2026 10:00:00 }

# VeeR EL2 (RISC-V core)
waive_violation -add {SEP_STARC05-1_3_1_3_el2} -comment {VeeR EL2 vendor core. Reset-as-data is for synchronous reset condition in flop. 3rd party vendor IP shouldn't be modified. Created by gchang on 16-Jun-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module =~ "${PREFIX}el2_*")}] -app { lint } -tag { STARC05-1.3.1.3 } -user { gchang } -timestamp { 16-06-2026 00:00:00 }
waive_violation -add {SEP_W391_jtag_tck} -comment {VeeR EL2 JTAG TAP. Dual-edge use of jtag_tck is mandatory per IEEE 1149.1 -- shift register sr clocks on posedge tck, tdo updates on negedge tck so the host samples TDO cleanly on the rising edge. 3rd party vendor IP shouldn't be modified. Created by gchang on 09-Jun-2026} -filter {(Goal == "lint_rtl_enhanced") AND (DesignObjSignal == "jtag_tck")} -app { lint } -tag { W391 } -user { gchang } -timestamp { 09-06-2026 12:06:49 }
waive_violation -add {SEP_W263_rvjtag_tap} -comment {VeeR EL2 JTAG TAP. State constants are untyped localparams (values 0-15) used as case labels against a 4-bit state selector. Values are correct and fit in 4 bits - width-declaration cosmetic only, no functional impact. 3rd party vendor IP shouldn't be modified. Created by gchang on 09-Jun-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}rvjtag_tap")}] -app { lint } -tag { W263 } -user { gchang } -timestamp { 09-06-2026 15:40:34 }
waive_violation -add {SEP_W146_el2} -comment {VeeR EL2 core. EL2 RTL uses positional port connections in some instantiations. Stylistic/cosmetic only, no functional impact. 3rd party vendor IP shouldn't be modified. Created by gchang on 09-Jun-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module =~ "${PREFIX}el2_*")}] -app { lint } -tag { W146 } -user { gchang } -timestamp { 09-06-2026 17:03:52 }
waive_violation -add {SEP_W146_rv} -comment {VeeR EL2 behavioral library primitives. Positional port connections in the EL2 library cells. Stylistic/cosmetic only, no functional impact. 3rd party vendor IP shouldn't be modified. Created by gchang on 10-Jun-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module =~ "${PREFIX}rv*")}] -app { lint } -tag { W146 } -user { gchang } -timestamp { 10-06-2026 15:23:52 }
waive_violation -add {SEP_W123_el2_mem} -comment {VeeR EL2 vendor core. In the SEP config the instruction cache is off (icache_enable=0), so the icache logic isn't built and its memory-export wires (ic_*) are undriven/X (This is what W123 is flagging). This is safe because (1) The undriven write-export wires flow out to sep_cpu but feed no icache SRAM (as it is not instantiated) meaning the X has no consumer and is not propagated. (2) The reverse read-back wires that do feed into the core are tied to 0 in sep_cpu, so the core sees defined 0 and never X. 3rd party vendor IP shouldn't be modified. Created by gchang on 09-Jun-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}el2_mem")}] -app { lint } -tag { W123 } -user { gchang } -timestamp { 09-06-2026 17:10:17 }
waive_violation -add {SEP_checkIOPinConnectedToNet_el2_mem} -comment {VeeR EL2 core. Unconnected on el2_mem icache-export pins because the EL2 icache is DISABLED in the SEP config (icache_enable=0), so the icache memory-export interface is unused. Config-driven, benign. 3rd party vendor IP shouldn't be modified. Created by gchang on 11-Jun-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}el2_mem")}] -app { lint } -tag { checkIOPinConnectedToNet } -user { gchang } -timestamp { 11-06-2026 16:36:49 }
waive_violation -add {SEP_ParamWidthMismatch-ML_el2_veer_wrapper_reset_vec} -comment {Tool widths RESET_VEC at 64 bits. Mismatch when assigned to 32 bits, but the value fits in 32 bits so nothing is lost. 3rd party vendor IP shouldn't be modified. Created by gchang on 17-Aug-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}el2_veer_wrapper") AND (Param == "RESET_VEC") AND (Exp_Size == "32") AND (ExprSize == "64")}] -app { lint } -tag { ParamWidthMismatch-ML } -user { gchang } -timestamp { 17-08-2026 00:00:00 }

waive_violation -add {SEP_checkIOPinConnectedToNet_el2_exu} -comment {VeeR EL2 core. Unconnected because branch prediction / BTB is DISABLED in the SEP config (btb_enabled=0), so the predicted-target bits are unused. Config-driven, benign. 3rd party vendor IP shouldn't be modified. Created by gchang on 15-Jun-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}el2_exu")}] -app { lint } -tag { checkIOPinConnectedToNet } -user { gchang } -timestamp { 15-06-2026 11:35:06 }
waive_violation -add {SEP_AutomaticFuncTask-ML_el2} -comment {VeeR EL2 core. Function/task not declared automatic. SystemVerilog defaults to static; the rule recommends automatic to avoid re-entrancy hazards, but a pure combinational function has no persistent local state to corrupt. Benign vendor coding style. 3rd party vendor IP shouldn't be modified. Created by gchang on 15-Jun-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module =~ "${PREFIX}el2_*")}] -app { lint } -tag { AutomaticFuncTask-ML } -user { gchang } -timestamp { 15-06-2026 11:47:01 }
waive_violation -add {SEP_W575_el2} -comment {VeeR EL2 core. On generate conditions like if(!pt.BTB_FULLYA) - pt.BTB_FULLYA is a multibit config parameter; !param is the standard "param == 0" idiom selecting an implementation at elaboration. Compile-time, benign. 3rd party vendor IP shouldn't be modified. Created by gchang on 11-Jun-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module =~ "${PREFIX}el2_*")}] -app { lint } -tag { W575 } -user { gchang } -timestamp { 11-06-2026 16:39:13 }
waive_violation -add {SEP_STARC05-2_10_2_3_el2} -comment {VeeR EL2 core. On generate conditions like if(!pt.BTB_FULLYA) - pt.BTB_FULLYA is a multibit config parameter; !param is the standard "param == 0" idiom selecting an implementation at elaboration. Compile-time, benign. 3rd party vendor IP shouldn't be modified. Created by gchang on 12-Jun-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module =~ "${PREFIX}el2_*")}] -app { lint } -tag { STARC05-2.10.2.3 } -user { gchang } -timestamp { 12-06-2026 11:48:49 }
waive_violation -add {SEP_W576_el2} -comment {VeeR EL2 core. On generate conditions like if(!pt.BTB_FULLYA) - pt.BTB_FULLYA is a multibit config parameter; !param is the standard "param == 0" idiom selecting an implementation at elaboration. Compile-time, benign. 3rd party vendor IP shouldn't be modified. Created by gchang on 12-Jun-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module =~ "${PREFIX}el2_*")}] -app { lint } -tag { W576 } -user { gchang } -timestamp { 12-06-2026 12:41:36 }
waive_violation -add {SEP_STARC05-2_1_4_5_el2} -comment {VeeR EL2 core. On generate conditions like if(!pt.BTB_FULLYA) - pt.BTB_FULLYA is a multibit config parameter; !param is the standard "param == 0" idiom selecting an implementation at elaboration. Compile-time, benign. 3rd party vendor IP shouldn't be modified. Created by gchang on 12-Jun-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module =~ "${PREFIX}el2_*")}] -app { lint } -tag { STARC05-2.1.4.5 } -user { gchang } -timestamp { 12-06-2026 12:47:27 }
waive_violation -add {SEP_W193_el2_pmp} -comment {VeeR EL2 vendor core. On an intentional do-nothing default (default: ;) in a case statement - keeps the case complete (avoids latch inference) and documents intent. Benign. 3rd party vendor IP shouldn't be modified. Created by gchang on 12-Jun-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}el2_pmp")}] -app { lint } -tag { W193 } -user { gchang } -timestamp { 12-06-2026 13:03:09 }

# PicoRV32 (key_manager CPU, copied_rtl)
waive_violation -add {SEP_STARC05-3_3_1_4b_picorv32_family} -comment {PicoRV32 open-source RISC-V core + coprocessors/adapter. All use synchronous reset by design; no async reset anywhere - async set/reset is intentionally not used by this core family. 3rd party vendor IP shouldn't be modified. Created by gchang on 09-Jun-2026} -filter "(Goal == \"lint_rtl_enhanced\") AND [module_any $VENDOR_PICORV32_MODULES]" -app { lint } -tag { STARC05-3.3.1.4b } -user { gchang } -timestamp { 09-06-2026 12:25:57 }
waive_violation -add {SEP_W238_picorv32_family} -comment {PicoRV32 open-source RISC-V core. Fires because PicoRV32 places `assert(...) immediate assertions inside its clocked FSM always block - the core's standard coding style. 3rd party vendor IP shouldn't be modified. Created by gchang on 10-Jun-2026} -filter "(Goal == \"lint_rtl_enhanced\") AND [module_any $VENDOR_PICORV32_MODULES]" -app { lint } -tag { W238 } -user { gchang } -timestamp { 10-06-2026 12:09:56 }
waive_violation -add {SEP_W342_picorv32_family} -comment {PicoRV32 open-source RISC-V core. Constant 32'bx X-extended - intentional don't-care assignment (32'bx is a single x extended to the 32-bit width). Benign, no functional impact. 3rd party vendor IP shouldn't be modified. Created by gchang on 10-Jun-2026} -filter "(Goal == \"lint_rtl_enhanced\") AND [module_any $VENDOR_PICORV32_MODULES]" -app { lint } -tag { W342 } -user { gchang } -timestamp { 10-06-2026 12:14:09 }
waive_violation -add {SEP_W164b_picorv32_family} -comment {PicoRV32 open-source RISC-V core. On $signed({... Created by gchang on 10-Jun-2026}) assignments in the compressed-instruction (RVC) decompression logic - intentional sign-extension of a narrow signed immediate into the wider instruction field. Benign. 3rd party vendor IP shouldn't be modified. Created by gchang on 09-Jun-2026} -filter "(Goal == \"lint_rtl_enhanced\") AND [module_any $VENDOR_PICORV32_MODULES]" -app { lint } -tag { W164b } -user { gchang } -timestamp { 10-06-2026 12:21:00 }
waive_violation -add {SEP_W443_picorv32_family} -comment {PicoRV32 open-source RISC-V core. Based number 32'bx contains an X - intentional don't-care assignment (pcpi_int_rd = 32'bx); the X marks a don't-care for an unused output, synthesizes as don't-care. Benign. 3rd party vendor IP shouldn't be modified. Created by gchang on 10-Jun-2026} -filter "(Goal == \"lint_rtl_enhanced\") AND [module_any $VENDOR_PICORV32_MODULES]" -app { lint } -tag { W443 } -user { gchang } -timestamp { 10-06-2026 12:25:19 }
waive_violation -add {SEP_NoAssignX-ML_picorv32_family} -comment {PicoRV32 open-source RISC-V core. RHS contains X - intentional don't-care assignment (pcpi_int_rd = 32'bx); X marks a don't-care for an unused output. Benign. 3rd party vendor IP shouldn't be modified. Created by gchang on 10-Jun-2026} -filter "(Goal == \"lint_rtl_enhanced\") AND [module_any $VENDOR_PICORV32_MODULES]" -app { lint } -tag { NoAssignX-ML } -user { gchang } -timestamp { 10-06-2026 12:28:05 }
waive_violation -add {SEP_STARC05-2_2_3_3_picorv32_family} -comment {PicoRV32 open-source RISC-V core. On mem_rdata_q, multiple conditional non-blocking assignments, last-write-wins. Benign. 3rd party vendor IP shouldn't be modified. Created by gchang on 10-Jun-2026} -filter "(Goal == \"lint_rtl_enhanced\") AND [module_any $VENDOR_PICORV32_MODULES]" -app { lint } -tag { STARC05-2.2.3.3 } -user { gchang } -timestamp { 10-06-2026 12:51:41 }
waive_violation -add {SEP_STARC05-2_2_3_3_id_queue} -comment {PULP/ETHZ common_cells id_queue (Solderpad). linked_data_q[i] is written then overridden in the reset branch,last-write-wins yields as intended. Benign. 3rd party vendor IP shouldn't be modified. Created by gchang on 17-Jun-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}id_queue")}] -app { lint } -tag { STARC05-2.2.3.3 } -user { gchang } -timestamp { 17-06-2026 14:40:29 }
waive_violation -add {SEP_W576_picorv32_family} -comment {PicoRV32 open-source RISC-V core. Logical operator ! on a multibit value, e.g. !mem_state where mem_state is 2-bit - intentional idiom meaning "value == 0" (logical NOT is true iff all bits are zero). Benign. 3rd party vendor IP shouldn't be modified. Created by gchang on 10-Jun-2026} -filter "(Goal == \"lint_rtl_enhanced\") AND [module_any $VENDOR_PICORV32_MODULES]" -app { lint } -tag { W576 } -user { gchang } -timestamp { 10-06-2026 14:32:28 }
waive_violation -add {SEP_STARC05-2_1_4_5_picorv32_family} -comment {PicoRV32 open-source RISC-V core. Use bit-wise instead of logical ! on a multibit value, e.g. !mem_state - intentional idiom; !mem_state means "mem_state == 0". Benign. 3rd party vendor IP shouldn't be modified. Created by gchang on 10-Jun-2026} -filter "(Goal == \"lint_rtl_enhanced\") AND [module_any $VENDOR_PICORV32_MODULES]" -app { lint } -tag { STARC05-2.1.4.5 } -user { gchang } -timestamp { 10-06-2026 15:41:01 }
waive_violation -add {SEP_STARC05-2_10_2_3_picorv32_family} -comment {PicoRV32 open-source RISC-V core. Logical negation on a vector, e.g. !mem_wstrb - intentional idiom meaning "mem_wstrb == 0" (no write strobes = read). Benign. 3rd party vendor IP shouldn't be modified. Created by gchang on 10-Jun-2026} -filter "(Goal == \"lint_rtl_enhanced\") AND [module_any $VENDOR_PICORV32_MODULES]" -app { lint } -tag { STARC05-2.10.2.3 } -user { gchang } -timestamp { 10-06-2026 16:49:40 }
waive_violation -add {SEP_W575_picorv32_family} -comment {PicoRV32 open-source RISC-V core. Logical NOT on a multibit value, e.g. !mem_state - intentional idiom meaning "value == 0". Benign. 3rd party vendor IP shouldn't be modified. Created by gchang on 10-Jun-2026} -filter "(Goal == \"lint_rtl_enhanced\") AND [module_any $VENDOR_PICORV32_MODULES]" -app { lint } -tag { W575 } -user { gchang } -timestamp { 10-06-2026 16:52:30 }
waive_violation -add {SEP_STARC05-2_1_5_3_picorv32_family} -comment {PicoRV32 open-source RISC-V core. Conditional expression does not evaluate to a scalar - if(mem_rdata_latched[11:7]) uses a 5-bit instruction field directly as a condition (true if nonzero, implicit reduction-OR), a PicoRV32 instruction-decode idiom. Benign. 3rd party vendor IP shouldn't be modified. Created by gchang on 11-Jun-2026} -filter "(Goal == \"lint_rtl_enhanced\") AND [module_any $VENDOR_PICORV32_MODULES]" -app { lint } -tag { STARC05-2.1.5.3 } -user { gchang } -timestamp { 11-06-2026 11:31:32 }
waive_violation -add {SEP_STARC05-2_10_3_2a_picorv32_family} -comment {PicoRV32 open-source RISC-V core. Operand bit-width mismatch for || - mem_rdata_latched[12] (1b) || mem_rdata_latched[6:2] (5b); || is logical OR so each operand is reduced to a boolean and the widths need not match. PicoRV32 instruction-decode idiom. Benign. 3rd party vendor IP shouldn't be modified. Created by gchang on 11-Jun-2026} -filter "(Goal == \"lint_rtl_enhanced\") AND [module_any $VENDOR_PICORV32_MODULES]" -app { lint } -tag { STARC05-2.10.3.2a } -user { gchang } -timestamp { 11-06-2026 11:34:57 }
waive_violation -add {SEP_W71_picorv32_family} -comment {PicoRV32 open-source RISC-V core. Case statement has no default and target not pre-assigned, but safe. (1) RVC decompressor: mem_rdata_q is always loaded with the fetched word before the case runs (same always_ff, if(mem_xfer)), so its undefined power-up value is never observed. (2) FSM case(cpu_state): cpu_state is reset to cpu_state_fetch and unique0 guarantees at most one match. Vendor IP, benign. 3rd party vendor IP shouldn't be modified. Created by gchang on 11-Jun-2026} -filter "(Goal == \"lint_rtl_enhanced\") AND [module_any $VENDOR_PICORV32_MODULES]" -app { lint } -tag { W71 } -user { gchang } -timestamp { 11-06-2026 13:20:00 }
waive_violation -add {SEP_W116_picorv32_or} -comment {PicoRV32 open-source RISC-V core. cpuregs_wrdata = reg_next_pc (32b, unsigned) | latched_compr (1b, unsigned). Both operands unsigned, so latched_compr zero-extends 1->32b; the OR only affects bit 0 (force PC LSB on IRQ return). Benign vendor idiom. 3rd party vendor IP shouldn't be modified. Created by gchang on 11-Jun-2026} -filter "(Goal == \"lint_rtl_enhanced\") AND [module_any $VENDOR_PICORV32_MODULES] AND (Signal == \"|\")" -app { lint } -tag { W116 } -user { gchang } -timestamp { 11-06-2026 13:20:30 }
waive_violation -add {SEP_W116_picorv32_div} -comment {PicoRV32 open-source RISC-V core divider. dividend (32b, unsigned) - divisor (63b, unsigned) in the restoring-division shift. dividend zero-extends to 63b for the subtract; result truncates back to the 32b LHS by design of the partial-remainder algorithm. Benign vendor idiom. 3rd party vendor IP shouldn't be modified. Created by gchang on 11-Jun-2026} -filter "(Goal == \"lint_rtl_enhanced\") AND [module_any $VENDOR_PICORV32_DIV_MODULES] AND (Signal == \"-\")" -app { lint } -tag { W116 } -user { gchang } -timestamp { 11-06-2026 13:20:30 }
waive_violation -add {SEP_STARC05-2_11_3_1_picorv32_family} -comment {PicoRV32 open-source RISC-V core. Single-always-block (one-process) FSM style: the state-register update (cpu_state/mem_state/irq_state <= ...) and the next-state/output logic share one clocked always block, rather than the separated combinational+sequential processes this rule prefers. Synthesizable and well-defined; methodology/style guideline only, no functional impact. 3rd party vendor IP shouldn't be modified. Created by gchang on 11-Jun-2026} -filter "(Goal == \"lint_rtl_enhanced\") AND [module_any $VENDOR_PICORV32_MODULES]" -app { lint } -tag { STARC05-2.11.3.1 } -user { gchang } -timestamp { 11-06-2026 13:21:00 }
waive_violation -add {SEP_NoGenLabel-ML_picorv32_family} -comment {PicoRV32 open-source RISC-V core. Generate block without a label - vendor uses unlabeled generate constructs. Cosmetic/style only, no functional impact. 3rd party vendor IP shouldn't be modified. Created by gchang on 11-Jun-2026} -filter "(Goal == \"lint_rtl_enhanced\") AND [module_any $VENDOR_PICORV32_MODULES]" -app { lint } -tag { NoGenLabel-ML } -user { gchang } -timestamp { 11-06-2026 13:21:30 }
waive_violation -add {SEP_W362_picorv32_family} -comment {PicoRV32 open-source RISC-V core + coprocessors. Arithmetic comparison with unequal operand width - PicoRV32 instruction/ALU datapath compares operands of differing widths (auto zero/sign-extended). Intentional vendor coding. Benign. 3rd party vendor IP shouldn't be modified. Created by gchang on 11-Jun-2026} -filter "(Goal == \"lint_rtl_enhanced\") AND [module_any $VENDOR_PICORV32_MODULES]" -app { lint } -tag { W362 } -user { gchang } -timestamp { 11-06-2026 13:22:00 }
waive_violation -add {SEP_AutomaticFuncTask-ML_picorv32_family} -comment {PicoRV32 open-source RISC-V core. Function/task not declared automatic on tasks/functions like empty_statement. SystemVerilog defaults functions/tasks to static; the rule recommends automatic to avoid re-entrancy hazards, but these are vendor helpers with no re-entrant local state. Benign vendor coding style. 3rd party vendor IP shouldn't be modified. Created by gchang on 15-Jun-2026} -filter "(Goal == \"lint_rtl_enhanced\") AND [module_any $VENDOR_PICORV32_MODULES]" -app { lint } -tag { AutomaticFuncTask-ML } -user { gchang } -timestamp { 15-06-2026 11:46:37 }
waive_violation -add {SEP_ImproperRangeIndex-ML_picorv32_family} -comment {PicoRV32 open-source RISC-V core register file. raddr2 is 6-bit but regs[] only needs a 5-bit index (NUM_REGS=20, max 19). The index is guarded so regs[raddr2] is only evaluated when raddr2 < NUM_REGS, always in range; out-of-range returns 'x. Width-only flag, never a real out-of-bounds access. Benign. 3rd party vendor IP shouldn't be modified. Created by gchang on 12-Jun-2026} -filter "(Goal == \"lint_rtl_enhanced\") AND [module_any $VENDOR_PICORV32_MODULES]" -app { lint } -tag { ImproperRangeIndex-ML } -user { gchang } -timestamp { 12-06-2026 12:51:24 }

# OpenTitan primitives
waive_violation -add {SEP_STARC05-3_3_1_4b_prim_fifo} -comment {OpenTitan prim FIFOs. Storage is intentionally unreset (entries are written before read; pointers track validity), only control/pointers need reset. Benign. 3rd party vendor IP shouldn't be modified. Created by gchang on 10-Jun-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module =~ "${PREFIX}prim_fifo*")}] -app { lint } -tag { STARC05-3.3.1.4b } -user { gchang } -timestamp { 10-06-2026 16:19:10 }
waive_violation -add {SEP_W416_prim_secded_get_full_width} -comment {OpenTitan prim_secded_pkg. Return type width 32 < return value width 33. It is a compile-time ECC-width helper - real widths (data <=64 + syndrome <=8) fit in 32b, so the 33b is a conservative int+int static estimate, never a real overflow. Benign. 3rd party vendor IP shouldn't be modified. Created by gchang on 12-Jun-2026} -filter {(Goal == "lint_rtl_enhanced") AND (FunctionName == "get_full_width")} -app { lint } -tag { W416 } -user { gchang } -timestamp { 12-06-2026 10:28:15 }
waive_violation -add {SEP_W416_prim_sha2_calc_w} -comment {OpenTitan SHA-2 package. Return type 32/64 < return value 33/65. These compute the SHA-256/SHA-512 message-schedule word, which by spec is addition mod 2^32 / mod 2^64 - the carry-out past the MSB is INTENTIONALLY discarded (truncation = the modular reduction). Also flagged inside deadcode. Benign. 3rd party vendor IP shouldn't be modified. Created by gchang on 12-Jun-2026} -filter {(Goal == "lint_rtl_enhanced") AND (FunctionName =~ "calc_w_*")} -app { lint } -tag { W416 } -user { gchang } -timestamp { 12-06-2026 12:56:36 }
waive_violation -add {SEP_W193_prim_sync_reqack} -comment {OpenTitan prim_sync_reqack. Isolated semicolon in upstream. Style-only. Vendor IP unmodified. Created by nbetik on 13-Jul-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}prim_sync_reqack")}] -app { lint } -tag { W193 } -user { nbetik } -timestamp { 13-07-2026 10:00:00 }
waive_violation -add {SEP_STARC05-2_3_4_2_prim_family} -comment {OpenTitan prim_*. Initial block used only for ASSERT_INIT parameter checks; not synthesized. Vendor IP unmodified. Created by nbetik on 13-Jul-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module =~ "${PREFIX}prim_*")}] -app { lint } -tag { STARC05-2.3.4.2 } -user { nbetik } -timestamp { 13-07-2026 10:00:00 }
waive_violation -add {SEP_STARC05-2_10_6_1_prim_sha2_pkg} -comment {OpenTitan prim_sha2_pkg. SHA-256/512 compression add is modular by design (result truncated to word width); carry/borrow width flag only. Created by nbetik on 13-Jul-2026} -filter {(Goal == "lint_rtl_enhanced") AND (((LHSExpr == "compress_256[0]") AND (RHSExpr == "(temp1 + temp2)")) OR ((LHSExpr == "compress_256[4]") AND (RHSExpr == "(h_i[3] + temp1)")) OR ((LHSExpr == "compress_512[0]") AND (RHSExpr == "(temp1 + temp2)")) OR ((LHSExpr == "compress_512[4]") AND (RHSExpr == "(h_i[3] + temp1)")) OR ((LHSExpr == "temp1") AND (RHSExpr == "((((h_i[7] + sigma_1) + ch) + k) + w)")) OR ((LHSExpr == "temp1") AND (RHSExpr == "((((h_i[7][31:0]  + sigma_1) + ch) + k) + w)")) OR ((LHSExpr == "temp2") AND (RHSExpr == "(sigma_0 + maj)")))} -app { lint } -tag { STARC05-2.10.6.1 } -user { nbetik } -timestamp { 13-07-2026 10:00:00 }
waive_violation -add {SEP_W164a_prim_sha2_pkg} -comment {OpenTitan prim_sha2_pkg. SHA compression sum is intentionally truncated to the word width (modular add); LHS<RHS width flag only. Created by nbetik on 13-Jul-2026} -filter {(Goal == "lint_rtl_enhanced") AND (((LHSExpr == "compress_256[0]") AND (RHSExpr == "(temp1 + temp2)")) OR ((LHSExpr == "compress_256[4]") AND (RHSExpr == "(h_i[3] + temp1)")) OR ((LHSExpr == "compress_512[0]") AND (RHSExpr == "(temp1 + temp2)")) OR ((LHSExpr == "compress_512[4]") AND (RHSExpr == "(h_i[3] + temp1)")) OR ((LHSExpr == "temp1") AND (RHSExpr == "((((h_i[7] + sigma_1) + ch) + k) + w)")) OR ((LHSExpr == "temp1") AND (RHSExpr == "((((h_i[7][31:0]  + sigma_1) + ch) + k) + w)")) OR ((LHSExpr == "temp2") AND (RHSExpr == "(sigma_0 + maj)")))} -app { lint } -tag { W164a } -user { nbetik } -timestamp { 13-07-2026 10:00:00 }
waive_violation -add {SEP_STARC05-2_10_6_1_prim_secded_pkg} -comment {OpenTitan prim_secded_pkg. get_full_width() elaboration-time width helper (width + get_synd_width()); carry/borrow width flag only, no functional overflow. Created by nbetik on 13-Jul-2026} -filter {(Goal == "lint_rtl_enhanced") AND (((LHSExpr == "get_full_width") AND (RHSExpr == "(width + get_synd_width(sd_type,width))")))} -app { lint } -tag { STARC05-2.10.6.1 } -user { nbetik } -timestamp { 13-07-2026 10:00:00 }

# OpenTitan OTBN (vendor) - register-file / datapath storage flops intentionally unreset
waive_violation -add {SEP_STARC05-3_3_1_4b_otbn_vendor} -comment {OpenTitan OTBN core. Fires on flops with no async set/reset. These are register-file / datapath storage. Intentional OpenTitan RF design - entries are always written before read, so resetting the storage array is pure area/timing cost; reset is reserved for control/state. Benign. 3rd party vendor IP shouldn't be modified. Filepath scope covers vendor OTBN only and inherently excludes the TT otbn_wrapper_key_reg (handled separately). Created by gchang on 11-Jun-2026} -filter "(Goal == \"lint_rtl_enhanced\") AND [module_any $VENDOR_OTBN_MODULES]" -app { lint } -tag { STARC05-3.3.1.4b } -user { gchang } -timestamp { 11-06-2026 12:00:00 }
# OTBN empty-statement / assertion-hier-ref / assert-init waivers (module-scoped)
waive_violation -add {SEP_W193_otbn_decoder} -comment {OpenTitan OTBN. Isolated semicolon (empty statement) in upstream case/default arms. Style-only category. Vendor IP unmodified. Created by nbetik on 13-Jul-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}otbn_decoder")}] -app { lint } -tag { W193 } -user { nbetik } -timestamp { 13-07-2026 10:00:00 }
waive_violation -add {SEP_W193_otbn_predecode} -comment {OpenTitan OTBN. Isolated semicolon in upstream. Style-only. Vendor IP unmodified. Created by nbetik on 13-Jul-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}otbn_predecode")}] -app { lint } -tag { W193 } -user { nbetik } -timestamp { 13-07-2026 10:00:00 }
waive_violation -add {SEP_W193_otbn_controller} -comment {OpenTitan OTBN. Isolated semicolon in upstream. Style-only. Vendor IP unmodified. Created by nbetik on 13-Jul-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}otbn_controller")}] -app { lint } -tag { W193 } -user { nbetik } -timestamp { 13-07-2026 10:00:00 }
waive_violation -add {SEP_W193_otbn_alu_bignum} -comment {OpenTitan OTBN. Isolated semicolon in upstream. Style-only. Vendor IP unmodified. Created by nbetik on 13-Jul-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}otbn_alu_bignum")}] -app { lint } -tag { W193 } -user { nbetik } -timestamp { 13-07-2026 10:00:00 }
waive_violation -add {SEP_W193_otbn_alu_base} -comment {OpenTitan OTBN. Isolated semicolon in upstream. Style-only. Vendor IP unmodified. Created by nbetik on 13-Jul-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}otbn_alu_base")}] -app { lint } -tag { W193 } -user { nbetik } -timestamp { 13-07-2026 10:00:00 }
waive_violation -add {SEP_W239_otbn_core} -comment {OpenTitan OTBN. Hierarchical refs inside SVA assertion macros; not synthesized. Vendor IP unmodified. Created by nbetik on 13-Jul-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}otbn_core")}] -app { lint } -tag { W239 } -user { nbetik } -timestamp { 13-07-2026 10:00:00 }

# OpenTitan W239 (hierarchical refs inside SVA assertion macros - not synthesized, benign; one waiver per module)
waive_violation -add {SEP_W239_otbn} -comment {OpenTitan OTBN. Fires on hierarchical references inside SVA assertion macros. Assertions are not synthesized, so the hierarchical references are benign. 3rd party vendor IP shouldn't be modified. Created by gchang on 09-Jun-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}otbn")}] -app { lint } -tag { W239 } -user { gchang } -timestamp { 09-06-2026 15:43:48 }
waive_violation -add {SEP_W239_edn} -comment {OpenTitan edn. Fires on hierarchical references inside SVA assertion macros. Assertions are not synthesized, so the references are benign. 3rd party vendor IP shouldn't be modified. Created by gchang on 10-Jun-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}edn")}] -app { lint } -tag { W239 } -user { gchang } -timestamp { 10-06-2026 11:43:41 }
waive_violation -add {SEP_W239_csrng} -comment {OpenTitan csrng. Fires on hierarchical references inside SVA assertion macros. Assertions are not synthesized, so the references are benign. 3rd party vendor IP shouldn't be modified. Created by gchang on 10-Jun-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}csrng")}] -app { lint } -tag { W239 } -user { gchang } -timestamp { 10-06-2026 11:59:59 }
waive_violation -add {SEP_W239_kmac} -comment {OpenTitan kmac. Fires on hierarchical references inside SVA assertion macros. Assertions are not synthesized, so the references are benign. 3rd party vendor IP shouldn't be modified. Created by gchang on 10-Jun-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}kmac")}] -app { lint } -tag { W239 } -user { gchang } -timestamp { 10-06-2026 11:52:25 }
waive_violation -add {SEP_W239_secure_dma} -comment {OpenTitan-derived secure_dma. Fires on hierarchical references inside an SVA assertion macro. Assertions are not synthesized, so the hierarchical references are benign. 3rd party vendor IP shouldn't be modified. Created by gchang on 12-Jun-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}secure_dma")}] -app { lint } -tag { W239 } -user { gchang } -timestamp { 12-06-2026 13:08:35 }
waive_violation -add {SEP_W239_aon_timer} -comment {OpenTitan aon_timer. Fires on hierarchical references inside SVA assertion macros (ASSERT_PRIM_*). Assertions are not synthesized, so the hierarchical references are benign. 3rd party vendor IP shouldn't be modified. Created by gchang on 12-Jun-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}aon_timer")}] -app { lint } -tag { W239 } -user { gchang } -timestamp { 12-06-2026 13:08:58 }
waive_violation -add {SEP_W193_otbn_family} -comment {OpenTitan OTBN. On empty case labels / defaults (e.g. AluOpBignumNone: ;) - intentional do-nothing branches. Benign. 3rd party vendor IP shouldn't be modified. Created by gchang on 10-Jun-2026} -filter "(Goal == \"lint_rtl_enhanced\") AND [module_any $VENDOR_OTBN_MODULES]" -app { lint } -tag { W193 } -user { gchang } -timestamp { 10-06-2026 14:41:42 }

# OpenTitan crypto W193 (empty do-nothing default: ; - intentional, benign; exact modules to avoid TT hmac_wrapper/kmac_wrapper)
waive_violation -add {SEP_W193_csrng_ctr_drbg} -comment {OpenTitan csrng. W193 (empty statement) - intentional do-nothing default (default: ;) in a case statement. Benign. 3rd party vendor IP shouldn't be modified. Created by gchang on 12-Jun-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}csrng_ctr_drbg")}] -app { lint } -tag { W193 } -user { gchang } -timestamp { 12-06-2026 13:03:35 }
waive_violation -add {SEP_W193_hmac_core} -comment {OpenTitan HMAC. W193 (empty statement) - intentional do-nothing default (default: ;). Benign. 3rd party vendor IP shouldn't be modified. Created by gchang on 12-Jun-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}hmac_core")}] -app { lint } -tag { W193 } -user { gchang } -timestamp { 12-06-2026 13:03:53 }
waive_violation -add {SEP_W193_hmac} -comment {OpenTitan HMAC. W193 (empty statement) - intentional do-nothing default (default: ;). Benign. Exact module (NOT hmac* - keeps TT hmac_wrapper out). 3rd party vendor IP shouldn't be modified. Created by gchang on 12-Jun-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}hmac")}] -app { lint } -tag { W193 } -user { gchang } -timestamp { 12-06-2026 13:04:11 }
waive_violation -add {SEP_W193_kmac_app} -comment {OpenTitan KMAC. W193 (empty statement) - intentional do-nothing default (default: ;). Benign. Exact module (NOT kmac* - keeps TT kmac_wrapper out). 3rd party vendor IP shouldn't be modified. Created by gchang on 12-Jun-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}kmac_app")}] -app { lint } -tag { W193 } -user { gchang } -timestamp { 12-06-2026 13:04:30 }
waive_violation -add {SEP_W193_otbn} -comment {OpenTitan OTBN. W193 (empty statement) - intentional do-nothing default (default: ;). Module==otbn exact (otbn_* handled separately; keeps TT otbn_wrapper_key_reg out). Benign. 3rd party vendor IP shouldn't be modified. Created by gchang on 12-Jun-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}otbn")}] -app { lint } -tag { W193 } -user { gchang } -timestamp { 12-06-2026 13:04:46 }

# OpenTitan Keccak (kmac)
waive_violation -add {SEP_ImproperRangeIndex-ML_keccak_theta} -comment {Localparam logic[2:0] constants {4,0,1,2,3. Created by gchang on 11-Jun-2026}/{1,2,3,4,0}, values 0-4; a 3-bit index can address 8 entries but the array holds only 5, so the index width exceeds the array size - benign because the constants are always in range. 3rd party vendor IP shouldn't be modified. Created by gchang on 09-Jun-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module =~ "${PREFIX}keccak*") AND (Statement =~ "*ThetaIndexX1*")}] -app { lint } -tag { ImproperRangeIndex-ML } -user { gchang } -timestamp { 11-06-2026 11:24:56 }
waive_violation -add {SEP_ImproperRangeIndex-ML_keccak_pi} -comment {Localparam logic[2:0][5][5] constant rotation-index table, values 0-4; a 3-bit index can address 8 entries but the array holds only 5, so the index width exceeds the array size - benign because the constants are always in range. 3rd party vendor IP shouldn't be modified. Created by gchang on 11-Jun-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module =~ "${PREFIX}keccak*") AND (Statement =~ "*PiRotate*")}] -app { lint } -tag { ImproperRangeIndex-ML } -user { gchang } -timestamp { 11-06-2026 11:24:56 }
waive_violation -add {SEP_ImproperRangeIndex-ML_keccak_chi} -comment {Localparam logic[2:0] constants {1,2,3,4,0. Created by gchang on 11-Jun-2026}/{2,3,4,0,1}, values 0-4; a 3-bit index can address 8 entries but the array holds only 5, so the index width exceeds the array size - benign because the constants are always in range. 3rd party vendor IP shouldn't be modified. Created by gchang on 09-Jun-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module =~ "${PREFIX}keccak*") AND (Statement =~ "*ChiIndexX1*")}] -app { lint } -tag { ImproperRangeIndex-ML } -user { gchang } -timestamp { 11-06-2026 11:24:56 }
waive_violation -add {SEP_ImproperRangeIndex-ML_el2} -comment {VeeR EL2 vendor core. ImproperRangeIndex-ML on el2_exu_mul_ctl bit-compress/decompress loops. 32-bit int loop variables indexing 32-element arrays (5 bits needed). For-loop bounds keep the value 0..31, never out of range; tool synthesizes upper bits away. Benign. 3rd party vendor IP shouldn't be modified. Created by gchang on 16-Jun-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module =~ "${PREFIX}el2_*")}] -app { lint } -tag { ImproperRangeIndex-ML } -user { gchang } -timestamp { 16-06-2026 00:00:00 }
waive_violation -add {SEP_STARC05-3_3_1_4b_rvjtag_tap} -comment {VeeR EL2 JTAG TAP tdo flop in always @(negedge tck) - IEEE 1149.1 TAPs do not use a system async reset; soft-reset is via 5 cycles of TMS=1 (Test-Logic-Reset state) and the optional TRST_n pin is not used in this implementation. Vendor follows standard. 3rd party vendor IP shouldn't be modified. Created by gchang on 16-Jun-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}rvjtag_tap")}] -app { lint } -tag { STARC05-3.3.1.4b } -user { gchang } -timestamp { 16-06-2026 00:00:00 }
waive_violation -add {SEP_STARC05-3_3_1_4b_edn_core} -comment {OpenTitan EDN core. Flop has no reset but its safe because its enable register is reset, and when enable low the comb logic forces the flop's next value to 0 the cycle after. It essentially works like a reset, just lint doesn't see it as a reset. 3rd party vendor IP shouldn't be modified. Created by gchang on 16-Jun-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}edn_core") AND (Signal == "csrng_hw_cmd_ack_q")}] -app { lint } -tag { STARC05-3.3.1.4b } -user { gchang } -timestamp { 16-06-2026 00:00:00 }
waive_violation -add {SEP_STARC05-3_3_1_4b_csrng_state_db} -comment {OpenTitan CSRNG state database. state_q[418][3] is the flop flagged for having no reset (RTL comment: "State storage, no reset required"), but the companion control regs ARE reset and gate every read of state_q via the CSRNG FSM - so state_q is only consumed after a valid command has been issued and the corresponding entry has been written. Adding a reset to state_q would be overhead. Benign valid-bit-gated storage. 3rd party vendor IP shouldn't be modified. Created by gchang on 16-Jun-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}csrng_state_db") AND (Signal =~ "state_q*")}] -app { lint } -tag { STARC05-3.3.1.4b } -user { gchang } -timestamp { 16-06-2026 00:00:00 }
waive_violation -add {SEP_STARC05-3_3_1_4b_prim_edn_req} -comment {OpenTitan prim_edn_req. word_data_q is the flop flagged for having no reset, but the companion valid bit chk_rep IS reset to 0 and gates every consumer of word_data_q - so word_data_q's pre-first-write garbage value is never observed. Adding a reset to word_data_q would just be overhead. Benign valid-bit-gated storage. 3rd party vendor IP shouldn't be modified. Created by gchang on 16-Jun-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}prim_edn_req") AND (Signal =~ "*word_data_q*")}] -app { lint } -tag { STARC05-3.3.1.4b } -user { gchang } -timestamp { 16-06-2026 00:00:00 }
waive_violation -add {SEP_W164b_secure_dma} -comment {OpenTitan secure_dma. The byte-count CSR (32b) shifted left 3 = 35b zero-extends to the required 64b. Required by SHA-2 padding spec. Benign zero-extension. 3rd party vendor IP shouldn't be modified. Created by gchang on 16-Jun-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}secure_dma") AND (LHSExpr == "sha2_message_len_bits") AND (RHSExpr == "(reg2hw.total_data_size.q << 3)")}] -app { lint } -tag { W164b } -user { gchang } -timestamp { 16-06-2026 00:00:00 }
waive_violation -add {SEP_W239_hmac} -comment {OpenTitan hmac. W239 fires on hierarchical references inside SVA assertion macro ASSERT_PRIM_REG_WE_ONEHOT_ERROR_TRIGGER_ALERT. Assertions are not synthesized, so the hierarchical references are benign. 3rd party vendor IP shouldn't be modified. Created by gchang on 16-Jun-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}hmac")}] -app { lint } -tag { W239 } -user { gchang } -timestamp { 16-06-2026 00:00:00 }
waive_violation -add {SEP_W239_aes} -comment {OpenTitan aes. W239 fires on hierarchical references inside SVA assertion macro ASSERT_PRIM_REG_WE_ONEHOT_ERROR_TRIGGER_ALERT. Assertions are not synthesized, so the hierarchical references are benign. 3rd party vendor IP shouldn't be modified. Created by gchang on 16-Jun-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}aes")}] -app { lint } -tag { W239 } -user { gchang } -timestamp { 16-06-2026 00:00:00 }
waive_violation -add {SEP_W216_keccak_round} -comment {OpenTitan kmac/keccak_round. For loop with 32 bit i, lint mad about part select on i. Loop bounds prove the upper bits of the 32-bit int are zero, so the part-select equals i. Benign loop-bounded int part-select. 3rd party vendor IP shouldn't be modified. Created by gchang on 16-Jun-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}keccak_round") AND (Statement =~ "*addr_i == i*")}] -app { lint } -tag { W216 } -user { gchang } -timestamp { 16-06-2026 00:00:00 }
waive_violation -add {SEP_W216_prim_leading_one_ppc} -comment {OpenTitan prim_leading_one_ppc. For loop with 32 bit i, lint mad about part select on i. Loop bounds prove the upper bits of the 32-bit int are zero, so the part-select equals i. Benign loop-bounded int part-select. 3rd party vendor IP shouldn't be modified. Created by gchang on 16-Jun-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}prim_leading_one_ppc") AND (Statement =~ "*idx_o = i*")}] -app { lint } -tag { W216 } -user { gchang } -timestamp { 16-06-2026 00:00:00 }
waive_violation -add {SEP_W444_csrng_pkg_undriven_sentinel} -comment {OpenTitan csrng_pkg. CSRNG's command-status field has a special 'nobody set this yet' value written as electrically-floating ('z). The checker flags floating values because a real floating wire is usually a mistake, but here it's just a label used in simulation to catch an undriven status bus (DV coverage is told to ignore it); in real operation the status is always properly driven. Benign. 3rd party vendor IP shouldn't be modified. Created by gchang on 17-Jun-2026} -filter {(Goal == "lint_rtl_enhanced") AND (Statement =~ "*CMD_STS_UNDRIVEN*")} -app { lint } -tag { W444 } -user { gchang } -timestamp { 17-06-2026 16:23:19 }
waive_violation -add {SEP_W481a_prim_util_clog2} -comment {OpenTitan prim_util_pkg. W481a flags the loop for(result=0; v>0; result++) in the _clog2 helper because the counter 'result' isn't what ends the loop - it ends when 'v' (halved each pass) reaches 0; 'result' just counts the halvings, which is the answer. It runs only at build time to size signal widths (never built as real hardware) and always terminates. Benign. 3rd party vendor IP shouldn't be modified. Created by gchang on 17-Jun-2026} -filter {(Goal == "lint_rtl_enhanced") AND (Statement =~ "*result = 0; v > 0*")} -app { lint } -tag { W481a } -user { gchang } -timestamp { 17-06-2026 16:25:31 }
waive_violation -add {SEP_STARC05-1_3_1_3_prim_flop} -comment {Reset-as-data is for synchronous reset condition in flop. 3rd party vendor IP shouldn't be modified. Created by gchang on 19-Jun-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}prim_flop") AND (SeqSetRstNet =~ "*sep_crypto.u_sep_efuse_wrapper.u_efuse_interface_controller.u_reset_n_sync.u_sync.u_sync_2.q_o[0]") AND (DesignSeqNet =~ "*sep_crypto.u_sep_efuse_wrapper.u_efuse_interface_controller.u_efuse_program_interface.program_state_q")}] -app { lint } -tag { STARC05-1.3.1.3 } -user { gchang } -timestamp { 19-06-2026 11:41:34 }
waive_violation -add {SEP_STARC05-1_3_1_3_picorv32_sync_resetn} -comment {The TT wrapper uses the warm reset as an async reset; the vendored picorv32 core uses the same resetn synchronously, as it does throughout. Both correct - the rule fires because one net does both. 3rd party vendor IP shouldn't be modified. Created by gchang on 03-Sep-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (SeqSetRstNet =~ "*u_reset_conditioner.u_warm_rst_scan_mux*") AND (DesignInstanceName =~ "*u_cpu.u_picorv32.*SEL")}] -app { lint } -tag { STARC05-1.3.1.3 } -user { gchang } -timestamp { 03-09-2026 00:00:00 }
waive_violation -add {SEP_STARC05-1_3_1_3_veer_dbg_rst_sync} -comment {The reset is fed as data into VeeR's debug reset synchroniser. Sampling an async reset as data is what a reset synchroniser does, so this is the mechanism working. 3rd party vendor IP shouldn't be modified. Created by gchang on 03-Sep-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (SeqSetRstNet =~ "*u_sep_reset_ctrl.u_sep_reset_ovrd_mux*") AND (DesignInstanceName =~ "*veer.dbg.rstl_syncff*")}] -app { lint } -tag { STARC05-1.3.1.3 } -user { gchang } -timestamp { 03-09-2026 00:00:00 }

# OpenTitan SHA3 / KMAC / Keccak (empty-statement, assertion-hier-ref, assert-init)
waive_violation -add {SEP_W193_sha3pad} -comment {OpenTitan KMAC/SHA3. Isolated semicolon in upstream. Style-only. Vendor IP unmodified. Created by nbetik on 13-Jul-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}sha3pad")}] -app { lint } -tag { W193 } -user { nbetik } -timestamp { 13-07-2026 10:00:00 }
waive_violation -add {SEP_W239_sha3} -comment {OpenTitan KMAC/SHA3. Hierarchical refs inside SVA assertion macros; not synthesized. Vendor IP unmodified. Created by nbetik on 13-Jul-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}sha3")}] -app { lint } -tag { W239 } -user { nbetik } -timestamp { 13-07-2026 10:00:00 }

# OpenTitan AES
waive_violation -add {SEP_W216_aes_ghash} -comment {OpenTitan AES GHASH. Integer part-select of an in-range index; width-style flag only. Vendor IP unmodified. Created by nbetik on 13-Jul-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}aes_ghash")}] -app { lint } -tag { W216 } -user { nbetik } -timestamp { 13-07-2026 10:00:00 }

# OpenTitan CSRNG

# OpenTitan-derived TL-UL (TileLink-UL bridge)

# SPI controller (OpenTitan-overlay)

# Caliptra adams-bridge (ML-DSA / ML-KEM post-quantum accelerator)
# W263 (case label width != selector width)
waive_violation -add {SEP_W263_adams_bridge_compress_mode} -comment {The mode constants are untyped localparams, so 'h0 and 'h1 size to 1 bit while the mode selector is 2 bits. Label zero-extends to the selector width and the values are correct (cosmetic, no functional impact). 3rd party vendor IP shouldn't be modified. Created by gchang on 17-Aug-2026} -filter "(Goal == \"lint_rtl_enhanced\") AND [module_any $VENDOR_ABR_COMPRESS_MODULES] AND (NodeType == \"mode\") AND (Exp_Size == \"1\") AND (ExprSize == \"2\")" -app { lint } -tag { W263 } -user { gchang } -timestamp { 17-08-2026 00:00:00 }
waive_violation -add {SEP_W263_adams_bridge_skencode_mldsa_q} -comment {Labels are 23 bit against a 24 bit selector. Zero extends, cosmetic with no functional impact. 3rd party vendor IP shouldn't be modified. Created by gchang on 17-Aug-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}skencode") AND (RTL_EXPRESSION =~ "(MLDSA_Q - *)") AND (Exp_Size == "23") AND (ExprSize == "24")}] -app { lint } -tag { W263 } -user { gchang } -timestamp { 17-08-2026 00:00:00 }

# W164b (LHS of assignment wider than RHS)
waive_violation -add {SEP_W164b_adams_bridge_ntt_twiddle_mlkem} -comment {The output is sized for 69 bits; the ML-KEM path returns 36 bits, so the upper bits zero-extend. Intentional shared-bus sizing, no information lost. 3rd party vendor IP shouldn't be modified. Created by gchang on 17-Aug-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}ntt_twiddle_lookup") AND (LHSExpr == "rdata") AND (LHS_Size == "69") AND (RHS_Size == "48")}] -app { lint } -tag { W164b } -user { gchang } -timestamp { 17-08-2026 00:00:00 }

# STARC05-3.3.1.4b (no async set/reset)
waive_violation -add {SEP_STARC05-3_3_1_4b_adams_bridge_abr_seq_rom} -comment {Module has no reset port at all; data_o_rom is unconditionally assigned every clock so it never holds an undefined value past the first edge. Benign. 3rd party vendor IP shouldn't be modified. Created by gchang on 17-Aug-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}abr_seq") AND (Signal =~ "data_o_rom.*")}] -app { lint } -tag { STARC05-3.3.1.4b } -user { gchang } -timestamp { 17-08-2026 00:00:00 }

# STARC05-2.11.3.1 (comb+seq in same always block)
waive_violation -add {SEP_STARC05-2_11_3_1_adams_bridge_counters} -comment {poly_count and chunk_count are plain counters updated inside the FSM always block, which the tool reads as a mixed comb/seq FSM; they are not FSM state. 3rd party vendor IP shouldn't be modified. Created by gchang on 17-Aug-2026} -filter "(Goal == \"lint_rtl_enhanced\") AND [module_any $VENDOR_ABR_FSM_COUNTER_MODULES] AND ((Signal == \"poly_count\") OR (Signal == \"chunk_count\"))" -app { lint } -tag { STARC05-2.11.3.1 } -user { gchang } -timestamp { 17-08-2026 00:00:00 }
waive_violation -add {SEP_W193_axi_lite_isolate} -comment {PULP AXI library. On a default: ; do-nothing case default - an intentional explicit default that keeps the case complete and documents intent. Benign. 3rd party vendor IP shouldn't be modified. Created by gchang on 17-Sep-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}axi_lite_isolate")}] -app { lint } -tag { W193 } -user { gchang } -timestamp { 17-09-2026 00:00:00 }
