#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2026 Tenstorrent USA, Inc.

"""Classify license-header state of every tracked source file.

Reproduce: python3 tools/spdx/scan_license_headers.py  (from repo root)

Classes:
  tt_ok        - SPDX Apache-2.0 + Tenstorrent copyright
  dual         - Tenstorrent AND another copyright holder in the header
  foreign      - copyright holder other than Tenstorrent, no TT line (in TT-owned area)
  generated    - tool-generated banner, no SPDX (PeakRDL, reggen, ...)
  missing      - no SPDX identifier and no recognizable license text
  spdx_only    - SPDX identifier but no copyright holder line
"""

import json
import subprocess
import sys
from collections import Counter, defaultdict
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]

SOURCE_SUFFIXES = {
    ".sv",
    ".svh",
    ".v",
    ".vh",
    ".rdl",
    ".py",
    ".c",
    ".h",
    ".cc",
    ".cpp",
    ".ld",
    ".S",
    ".mk",
    ".tcl",
    ".sh",
    ".yml",
    ".yaml",
    ".hjson",
    ".core",
    ".vlt",
    ".f",
    ".toml",
    ".cfg",
    ".rs",
}
SOURCE_NAMES = {"Makefile", "makefile", "Dockerfile"}

# Vendored upstream trees keep their own licenses; exclude from OSPO alignment.
EXCLUDE_PREFIXES = ("vendor/",)
# But TT-owned vendor collateral must comply.
INCLUDE_VENDOR_MARKERS = ("/overlay/", "/patches/")

GENERATED_MARKERS = (
    "generated by peakrdl",
    "do not edit",
    "auto-generated",
    "autogenerated",
    "generated by reggen",
    "this file is generated",
    "generated automatically",
    "generated by",
    "@generated",
)


def tracked_files() -> list[str]:
    out = subprocess.run(["git", "ls-files"], cwd=REPO, capture_output=True, text=True, check=True)
    return out.stdout.splitlines()


def wanted(path: str) -> bool:
    p = Path(path)
    if p.suffix not in SOURCE_SUFFIXES and p.name not in SOURCE_NAMES:
        return False
    if path.startswith(EXCLUDE_PREFIXES):
        return any(marker in f"/{path}" for marker in INCLUDE_VENDOR_MARKERS)
    return True


def classify(path: str) -> tuple[str, str]:
    try:
        text = (REPO / path).read_text(errors="replace")
    except OSError:
        return "unreadable", ""
    head = "\n".join(text.splitlines()[:25]).lower()
    has_spdx = "spdx-license-identifier" in head
    has_tt = "tenstorrent" in head
    others = [
        holder
        for holder, needles in {
            "lowRISC": ("lowrisc",),
            "ETH/Bologna": ("eth zurich", "university of bologna", "solderpad"),
            "BOS": ("bos semiconductor", "bos_semi", "bos semiconductors"),
            "other": ("copyright (c)", "copyright 20"),
        }.items()
        if any(n in head for n in needles)
    ]
    named_others = [o for o in others if o != "other"]
    generic_copyright = "other" in others
    if has_tt and (
        named_others or (generic_copyright and "tenstorrent" not in head.split("copyright")[0])
    ):
        if named_others:
            return "dual", "+".join(named_others)
    if has_spdx and has_tt:
        return "tt_ok", ""
    if not has_spdx and any(m in head for m in GENERATED_MARKERS):
        return "generated", ""
    spdx_id = ""
    if has_spdx:
        for line in head.splitlines():
            if "spdx-license-identifier" in line:
                rest = line.split("spdx-license-identifier", 1)[1].lstrip(": ").split()
                spdx_id = rest[0] if rest else ""
                break
    if has_spdx and spdx_id and spdx_id not in ("apache-2.0",):
        return "non_apache_spdx", spdx_id
    if has_spdx and named_others:
        return "foreign", "+".join(named_others)
    if has_spdx and generic_copyright:
        return "foreign", "unnamed-holder"
    if has_spdx:
        return "spdx_only", ""
    if named_others or generic_copyright:
        return "foreign_no_spdx", "+".join(named_others) or "unknown"
    return "missing", ""


def area(path: str) -> str:
    parts = path.split("/")
    if path.startswith("hw/sys/"):
        return f"hw/sys/{parts[2]}"
    if path.startswith(("hw/ip/", "hw/common/", "hw/top")):
        return "/".join(parts[:2])
    if path.startswith("vendor/"):
        return "/".join(parts[:3])
    return parts[0] if len(parts) > 1 else "(root)"


def main() -> None:
    results: defaultdict[str, defaultdict[str, list[str]]] = defaultdict(lambda: defaultdict(list))
    counts: Counter[str] = Counter()
    for path in tracked_files():
        if not wanted(path):
            continue
        cls, detail = classify(path)
        counts[cls] += 1
        results[area(path)][cls].append(path + (f" [{detail}]" if detail else ""))

    print("== Totals ==")
    for cls, n in counts.most_common():
        print(f"  {cls:16s} {n}")
    print()
    print("== Non-compliant files by area ==")
    interesting = (
        "missing",
        "dual",
        "foreign",
        "foreign_no_spdx",
        "spdx_only",
        "non_apache_spdx",
        "generated",
    )
    for ar in sorted(results):
        rows = {c: results[ar][c] for c in interesting if results[ar][c]}
        if not rows:
            continue
        print(f"\n--- {ar} ---")
        for cls, files in rows.items():
            print(f"  [{cls}] ({len(files)})")
            for f in files:
                print(f"    {f}")

    out_dir = REPO / "build"
    out_dir.mkdir(exist_ok=True)
    out = out_dir / "license_header_scan.json"
    out.write_text(json.dumps({a: dict(v) for a, v in results.items()}, indent=1))
    print(f"\nJSON written to {out}", file=sys.stderr)


if __name__ == "__main__":
    main()
