#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2026 Tenstorrent USA, Inc.
"""Source digest of the SEP EL2 test firmware.

One SHA-256 over every file the EL2 TCM images can draw from: the SEP DV
firmware tree, the shared DV firmware engine, the SEP boot ROM headers the tests
include, and every generated register header directory on the include path
(SEP, IP and vendor overlay). Build output
(any ``build/`` directory) is not an input.

``fw.mk`` compiles the digest into each image as the string
``FW-BUILD-ID:<digest>``. ``sep_base_test`` reads that string back out of the
TCM image the simulation loads and compares it with ``digest()`` of the tree at
the logged commit (CHK-FW-IDENTITY), so an image built from other source fails
a logged checker.

Standard library only; the firmware build runs this with the toolchain
container's python3.

    fw_src_digest.py <repo-root>                      print the digest
    fw_src_digest.py --write-header <file> <repo-root> also write the C header
"""

from __future__ import annotations

import hashlib
import os
import sys
from pathlib import Path

# Inputs, relative to the repository root. A glob entry expands to every match.
# The generated-header entries mirror ocah_fw_reg_includes in
# hw/common/dv/fw/reg_includes.mk: every directory it puts on the include path
# for FW_REG_SYS=sep is an input here. A change there must be made here too.
SOURCE_DIRS = (
    "hw/sys/sep/dv/fw",
    "hw/common/dv/fw",
    "hw/sys/sep/bootrom/prod/include",
    "hw/sys/sep/regs/gen/c",
    "hw/sys/sep/dv/models/regs/gen/c",
    "hw/ip/*/dv/models/regs/gen/c",
    "hw/ip/*/*/dv/models/regs/gen/c",
    "hw/ip/*/regs/gen/c",
    "hw/ip/*/*/regs/gen/c",
    "vendor/*/*/overlay/rdl/gen/c",
    "vendor/*/*/overlay/regs/*/regs/gen/c",
)
_SKIP_DIRS = frozenset({"build", "__pycache__"})
MARKER = b"FW-BUILD-ID:"


def source_files(root: Path) -> list[Path]:
    """Every input file, as a path relative to ``root``, in a stable order."""
    files: set[Path] = set()
    for pattern in SOURCE_DIRS:
        for top in sorted(root.glob(pattern)):
            if not top.is_dir():
                continue
            for dirpath, dirnames, filenames in os.walk(top):
                dirnames[:] = [d for d in dirnames if d not in _SKIP_DIRS]
                for name in filenames:
                    if not name.endswith(".pyc"):
                        files.add((Path(dirpath) / name).relative_to(root))
    return sorted(files, key=lambda p: p.as_posix())


def digest(root: Path) -> str:
    """SHA-256 over each input's relative path and content digest."""
    outer = hashlib.sha256()
    for rel in source_files(root):
        inner = hashlib.sha256((root / rel).read_bytes()).hexdigest()
        outer.update(f"{rel.as_posix()}\0{inner}\n".encode())
    return outer.hexdigest()


def write_header(path: Path, value: str) -> None:
    """Write the C header, replacing it only when its content changes.

    An unchanged header keeps its timestamp, so make does not rebuild the
    object that includes it. The write goes through a temporary name, so a
    parallel build never reads a partial file.
    """
    text = (
        "/* Generated by hw/sys/sep/dv/fw/fw_src_digest.py. Do not edit. */\n"
        f'#define SEP_FW_SRC_DIGEST "{value}"\n'
    )
    if path.is_file() and path.read_text() == text:
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_name(f"{path.name}.tmp.{os.getpid()}")
    tmp.write_text(text)
    os.replace(tmp, path)


def main(argv: list[str]) -> int:
    header = None
    if len(argv) >= 2 and argv[0] == "--write-header":
        header, argv = Path(argv[1]), argv[2:]
    if len(argv) != 1:
        print(__doc__, file=sys.stderr)
        return 2
    value = digest(Path(argv[0]).resolve())
    if header is not None:
        write_header(header, value)
    print(value)
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
