"""Locate the sep-vp binary, the base config, and the SEP firmware trees.

All paths are anchored relative to this file's location
(``virtual_platform/sepvp/paths.py``) so the package is import-location
independent. Environment variables override the defaults:

  SEP_VP_BIN     full path to the sep-vp executable
  SEP_VP_BASE_INI  base accellera_config.ini to @include
"""

import os
from pathlib import Path

# virtual_platform/sepvp/paths.py
_THIS = Path(__file__).resolve()
SEPVP_DIR = _THIS.parent                       # .../sepvp
VP_DIR = SEPVP_DIR.parent                      # .../virtual_platform
OCAH_ROOT = VP_DIR.parent                      # repo root (tt-oca-harness)
SIM_DIR = VP_DIR / "tt-oca-sim"                # the SystemC platform source (submodule)

# --- sep-vp platform -------------------------------------------------------
VP_BUILD_DIR = SIM_DIR / "vp" / "build"
DEFAULT_SEP_VP_BIN = VP_BUILD_DIR / "bin" / "sep-vp"
CONFIG_DIR = SIM_DIR / "vp" / "platform" / "sep" / "config"
DEFAULT_BASE_INI = CONFIG_DIR / "accellera_config.ini"
VEERISS_CONFIG = CONFIG_DIR / "veeriss_config.json"

# Runtime env script written by `make env` (sourced by the sw/sep-vp-tests run.sh).
ENV_SCRIPT = VP_DIR / "setup_environment.sh"

# --- SEP boot ROM (the production tree) --------------------------------------
BOOTCODE_DIR = OCAH_ROOT / "hw" / "sys" / "sep" / "bootrom" / "prod"
# The SEP VP models the OpenTitan SPI host only (the Cadence xSPI controller is
# closed-source IP, not modeled), so the VP always uses the OpenTitan boot-ROM
# build in build_ot/ (the Makefile's ot-toolchain-images target), never the
# default build/ (Cadence).
BOOTCODE_OT_BUILD_DIR = "build_ot"
BOOTCODE_ELF = BOOTCODE_DIR / BOOTCODE_OT_BUILD_DIR / "boot_rom.elf"
# Signed SPI image for the OT-negative suite: GENERATED by
# `make -C <bootrom> secure_boot_spi` (there is no checked-in prebuilt/ anymore).
SECURE_BOOT_PRELOAD = BOOTCODE_DIR / "build" / "secure_boot.spi_preload"

# --- SEP DV firmware engine (replaces the old fw/sep/tests tree) --------------
# Tests live in hw/sys/sep/dv/fw/tests/ and are built by the shared engine
# (`make ocah-dv-fw-tests TARGET=sep TEST=<name>` at the repo root).
FW_DIR = OCAH_ROOT / "hw" / "sys" / "sep" / "dv" / "fw"
FW_TESTS_DIR = FW_DIR / "tests"
FW_TEST_BUILD_DIR = FW_DIR / "build" / "tests"

# Default per-run working-directory root (logs + staged artifacts land here).
LOGS_DIR = VP_DIR / "logs" / "sepvp"

# RISC-V cross toolchain used to build SEP firmware.
DEFAULT_RISCV_TOOLCHAIN = Path("/tools_soc/opensrc/riscv-gnu-toolchain/2025.01.20-rhel-8.10")


def sep_vp_bin() -> Path:
    """Path to the sep-vp executable (env SEP_VP_BIN wins)."""
    return Path(os.environ.get("SEP_VP_BIN", DEFAULT_SEP_VP_BIN))


def base_ini() -> Path:
    return Path(os.environ.get("SEP_VP_BASE_INI", DEFAULT_BASE_INI))


def fw_test_elf(test_name: str) -> Path:
    """Where the DV firmware engine drops a test ELF (default link mode: tcm)."""
    return FW_TEST_BUILD_DIR / test_name / f"{test_name}.tcm.elf"


def vp_env(gcc_toolset: str = "gcc-toolset-11") -> dict:
    """Environment for launching sep-vp.

    sep-vp runs standalone: libsystemc resolves via RPATH and Boost/CCI/OpenSSL are
    static, with the gcc-toolset libstdc++ statically satisfied. We therefore inherit
    the current environment and, as cheap insurance for hosts where the system
    libstdc++ is older, prepend the gcc-toolset runtime lib dir to LD_LIBRARY_PATH
    when it exists.
    """
    env = dict(os.environ)
    toolset_lib = f"/opt/rh/{gcc_toolset}/root/usr/lib64"
    if os.path.isdir(toolset_lib):
        prev = env.get("LD_LIBRARY_PATH", "")
        env["LD_LIBRARY_PATH"] = toolset_lib + (os.pathsep + prev if prev else "")
    return env
