# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2026 Tenstorrent USA, Inc.
#
# tclint-disable line-length
#
# SEP VC SpyGlass CDC waivers.

# --- hierarchy-reuse tokens -------------------------------------------------------
# ${PREFIX} re-anchors hierarchical filter fields at the parent instance path. A parent
# run that replays this block predefines PREFIX and apply_prefix before sourcing this
# file; in the block's own run PREFIX is "". ${BLOCKINST} is the containing instance of a
# block-top violation (the design name here, the instance path at the parent).
if { ![info exists PREFIX] } { set PREFIX "" }
if { [info procs apply_prefix] eq "" } {
    proc apply_prefix { filter } {
        set out [string map [list {${PREFIX}} $::PREFIX] $filter]
        if { $::PREFIX eq "" } {
            set bi $::env(DESIGN_NAME)
        } else {
            set bi [string trimright $::PREFIX "/."]
        }
        set out [string map [list {${BLOCKINST}} $bi] $out]
        return $out
    }
}
# ----------------------------------------------------------------------------------

# Entropy waiver below is non-functional; entropy_source is currently blackboxed.
# waive_violation -add {SEP_SETUP_CLOCK_GLITCH_291}  -comment {signal_monitor_o convergence is observability-only and never feeds functional logic, therefore not a risk}  -filter [apply_prefix {(ConvergencePoint == "${PREFIX}u_sep_crypto/u_sep_trng/u_entropy_source_s3c_scan/dbg/fast_signal") AND (Module == "sep")}]  -app { cdc } -tag { SETUP_CLOCK_GLITCH } -user { danielkim } -timestamp { 29-06-2026 11:30:05 }

#=======================================================================================================================
# CDC_UNSYNC_CTRL / CDC_UNSYNC_DATA : EL2 DMI JTAG-to-core crossings (i_jtag_tap/dr -> veer/dbg)
#=======================================================================================================================
# JTAG DR addr/data bits cross TCK -> SEPCLK unsynchronized by design. Every capture in the debug module
# is gated by dmi_reg_en/dmi_reg_wr_en, single-cycle pulses from the dmi_jtag_to_core_sync multiflop
# synchronizer. DR only reloads at Update-DR, the same TCK edge that launches the enable bits, so all
# crossing bits are static when the qualifier pulse fires: a valid qualifier scheme on every path.
# The two waivers below cover the read path (dmi_rddata_reg) and the qualified write/enable paths.
#=======================================================================================================================
waive_violation -add {SEP_CDC_UNSYNC_CTRL_5822} -comment {el2 DMI read path: dmi_rddata_reg and dbg/sbcs_error_reg is gated by the synchronized dmi_reg_en qualifier, therefore not a risk} -filter [apply_prefix {((DestObject == "${PREFIX}u_sep_cpu/u_el2_veer_wrapper/veer/dbg/dmi_rddata_reg/genblock.genblock.dff/dout/Q[31:0]") OR (DestObject =~ "${PREFIX}u_sep_cpu/u_el2_veer_wrapper/veer/dbg/sbcs_*")) AND (ReasonInfoList:ReasonInfo:ReasonCode == "NO_SYNC_METHOD") AND (SrcObject =~ "${PREFIX}u_sep_cpu/u_el2_veer_wrapper/dmi_wrapper/i_jtag_tap/dr/Q*") AND (SrcClockInfoList:SrcClockInfo:ClockName == "JTAG_TCK") AND ((DestClockInfoList:DestClockInfo:ClockName == "SEPCLK") OR (DestClockInfoList:DestClockInfo:ClockName == "SMUCLK")) AND (SrcObjectType == "flop") AND (DestObjectType == "flop") AND (Module == "el2_veer_wrapper") AND (FullyContainedViolation == "true")}] -app { cdc } -tag { CDC_UNSYNC_NOSCHEME } -user { danielkim } -timestamp { 08-07-2026 17:39:58 }
waive_violation -add {SEP_CDC_UNSYNC_DATA_5705} -comment {el2 DMI write/enable paths are gated by the synchronized dmi_reg_en/dmi_reg_wr_en qualifier, therefore not a risk} -filter [apply_prefix {(DestObject =~ "${PREFIX}u_sep_cpu/u_el2_veer_wrapper/veer/dbg/*") AND (ReasonInfoList:ReasonInfo:ReasonCode == "NFF_USED_AS_QUALIFIER") AND (ReasonInfoList:ReasonInfo:ReasonCodeMsg == "[INFO] Tool detected multiflop synchronizer used as control path qualifier") AND (SrcObject =~ "${PREFIX}u_sep_cpu/u_el2_veer_wrapper/dmi_wrapper/i_jtag_tap/dr/Q*") AND (SrcClockInfoList:SrcClockInfo:ClockName == "JTAG_TCK") AND ((DestClockInfoList:DestClockInfo:ClockName == "SEPCLK") OR (DestClockInfoList:DestClockInfo:ClockName == "SMUCLK")) AND (CtrlPathList:CtrlPathInfo:SyncObject =~ "${PREFIX}u_sep_cpu/u_el2_veer_wrapper/dmi_wrapper/i_dmi_jtag_to_core_sync/*") AND (Module == "el2_veer_wrapper") AND (FullyContainedViolation == "true")}] -app { cdc } -tag { CDC_UNSYNC_DATA } -user { danielkim } -timestamp { 08-07-2026 17:43:08 }

waive_violation -add {SEP_CDC_UNSYNC_ASYNCRESET_7593} -comment {jtag_trst_ni and tck are companion pins of one host-driven JTAG interface; trst is released while tck is idle so there is no edge to race, therefore not a risk} -filter [apply_prefix {(ReasonInfoList:ReasonInfo:ReasonCode == "RST_ASYNC_DEASSERTION") AND (ReasonInfoList:ReasonInfo:ReasonCodeMsg == "[ERROR] Asynchronous reset deassertion") AND (SrcObject == "jtag_trst_ni") AND (DestObject =~ "${PREFIX}u_sep_cpu/u_el2_veer_wrapper/dmi_wrapper/i_jtag_tap*") AND (SrcClockInfoList:SrcClockInfo:ClockName == "ck_feedthru") AND (DestClockInfoList:DestClockInfo:ClockName == "JTAG_TCK")  AND (SrcObjectType == "primary input") AND (AllSrcResets:SrcResetInfo:ResetObject == "jtag_trst_ni") AND ((AllSrcResets:SrcResetInfo:ResetName == "JTAG_TRST_N") OR (AllSrcResets:SrcResetInfo:ResetName == "trst_n_combined")) AND (DestObjectType == "Reset pin of flop") AND (Module == "sep")}] -app { cdc } -tag { CDC_UNSYNC_ASYNCRESET } -user { danielkim } -timestamp { 07-07-2026 11:32:03 }
waive_violation -add {SEP_CDC_UNSYNC_DATA_2959} -comment {Opentitan prim_reg_cdc handles the crossing with a synchronized qualifier, therefore it is not a risk} -filter [apply_prefix {(DestObject =~ "${PREFIX}u_sep_wdt_wrap/u_wdt_aon_timer/u_reg/*") AND (ReasonInfoList:ReasonInfo:ReasonCode == "QUAL_CONVERGES_OTHER_SYNC_SRC") AND (ReasonInfoList:ReasonInfo:ReasonCode == "UDS_USED_AS_QUALIFIER") AND (ReasonInfoList:ReasonInfo:ReasonCodeMsg == "[ERROR] Qualifier converges with another synchronous source before gating logic") AND (ReasonInfoList:ReasonInfo:ReasonCodeMsg == "[INFO] User defined synchronizer cell used as control path qualifier") AND (SrcObject =~ "${PREFIX}u_sep_wdt_wrap/u_wdt_aon_timer/u_reg/*_cdc/src_q/*") AND ((SrcClockInfoList:SrcClockInfo:ClockName == "SEPCLK") OR (SrcClockInfoList:SrcClockInfo:ClockName == "SMUCLK")) AND ((DestClockInfoList:DestClockInfo:ClockName == "WDTCLK") OR (DestClockInfoList:DestClockInfo:ClockName == "SEP_WDT_CLK")) AND (CtrlPathList:CtrlPathInfo:SyncObject =~ "${PREFIX}u_sep_wdt_wrap/u_wdt_aon_timer/u_reg/*_cdc/u_src_to_dst_req/prim_flop_2sync/*") AND (FullyContainedViolation == "true")}] -app { cdc } -tag { CDC_UNSYNC_DATA } -user { danielkim } -timestamp { 08-07-2026 18:53:33 }
waive_violation -add {SEP_CDC_UNSYNC_NOSCHEME_3011} -comment {ext_debug_bus_o is an observability-only primary output with no capture flop, therefore not a risk.} -filter [apply_prefix {(DestObject =~ "ext_debug_bus_o*") AND (ReasonInfoList:ReasonInfo:ReasonCode == "NO_SYNC_METHOD") AND (ReasonInfoList:ReasonInfo:ReasonCodeMsg == "[ERROR] Enable Criteria not satisfied, no valid qualifier") AND (DestClockInfoList:DestClockInfo:ClockName == "ck_feedthru") AND (DestObjectType == "primary output") AND (Module == "sep")}] -app { cdc } -tag { CDC_UNSYNC_NOSCHEME } -user { danielkim } -timestamp { 08-07-2026 19:31:00 }

# DMI read response captured back into the JTAG TAP shift register
waive_violation -add {SEP_CDC_UNSYNC_NOSCHEME_3008} -comment {DMI read-response path: core/uncore read data returns to the JTAG TAP shift register, stable by protocol before Capture-DR, therefore not a risk} -filter [apply_prefix {(DestObject =~ "${PREFIX}u_sep_cpu/u_el2_veer_wrapper/dmi_wrapper/i_jtag_tap/sr/*") AND (ReasonInfoList:ReasonInfo:ReasonCode == "NO_SYNC_METHOD") AND (ReasonInfoList:ReasonInfo:ReasonCodeMsg == "[ERROR] Enable Criteria not satisfied, no valid qualifier") AND ((SrcClockInfoList:SrcClockInfo:ClockName == "SEPCLK") OR (SrcClockInfoList:SrcClockInfo:ClockName == "SMUCLK")) AND (DestClockInfoList:DestClockInfo:ClockName == "JTAG_TCK") AND (DestObjectType == "flop")}] -app { cdc } -tag { CDC_UNSYNC_NOSCHEME } -user { danielkim } -timestamp { 08-07-2026 19:58:31 }
# DMI write to core command register
waive_violation -add {SEP_CDC_UNSYNC_NOSCHEME_5686} -comment {el2 DMI write to dmcommand_reg gated by the synchronized command_wren (dmi_reg_en) qualifier; bit-slice reconverges through command_din so the tool reports no scheme, therefore not a risk} -filter [apply_prefix {(DestObject == "${PREFIX}u_sep_cpu/u_el2_veer_wrapper/veer/dbg/dmcommand_reg/genblock.genblock.dff/dout/Q{ [15:8] ,[6:0] }") AND (ReasonInfoList:ReasonInfo:ReasonCode == "NO_SYNC_METHOD") AND (ReasonInfoList:ReasonInfo:ReasonCodeMsg == "[ERROR] Enable Criteria not satisfied, no valid qualifier") AND (SrcObject == "${PREFIX}u_sep_cpu/u_el2_veer_wrapper/dmi_wrapper/i_jtag_tap/dr/Q{ [33:26] ,[24:18] }") AND (SrcClockInfoList:SrcClockInfo:ClockName == "JTAG_TCK") AND ((DestClockInfoList:DestClockInfo:ClockName == "SEPCLK") OR (DestClockInfoList:DestClockInfo:ClockName == "SMUCLK")) AND (SrcObjectType == "flop") AND (DestObjectType == "flop") AND (Module == "el2_veer_wrapper") AND (FullyContainedViolation == "true")}] -app { cdc } -tag { CDC_UNSYNC_NOSCHEME } -user { danielkim } -timestamp { 08-07-2026 20:01:36 }
# DMI addr/wdata exported to the uncore aperture (primary outputs, qualified by dmi_uncore_en downstream)
waive_violation -add {CDC_UNSYNC_NOSCHEME_5689} -comment {el2 DMI addr/wdata to the uncore aperture; primary outputs stable by protocol from Update-DR, qualified downstream by the exported dmi_uncore_en, therefore not a risk} -filter [apply_prefix {(DestObject =~ "dmi_uncore_*") AND (ReasonInfoList:ReasonInfo:ReasonCode == "NO_SYNC_METHOD") AND (ReasonInfoList:ReasonInfo:ReasonCodeMsg == "[ERROR] Enable Criteria not satisfied, no valid qualifier") AND (SrcObject =~ "${PREFIX}u_sep_cpu/u_el2_veer_wrapper/dmi_wrapper/i_jtag_tap/dr/Q*") AND (SrcClockInfoList:SrcClockInfo:ClockName == "JTAG_TCK") AND ((DestClockInfoList:DestClockInfo:ClockName == "SEPCLK") OR (DestClockInfoList:DestClockInfo:ClockName == "SMUCLK")) AND (SrcObjectType == "flop") AND (DestObjectType == "primary output") AND (Module == "sep")}] -app { cdc } -tag { CDC_UNSYNC_NOSCHEME } -user { danielkim } -timestamp { 08-07-2026 20:03:49 }

#=======================================================================================================================
# CDC_COHERENCY_RECONV_* : reconvergence of independently synchronized control bits (EL2 + aon_timer)
#=======================================================================================================================
# All reconvergence flags fall inside third-party IP and involve independent single-bit control signals,
# not multi-bit encoded values that must arrive coherently. EL2: tlu halt/run/irq requests and the DMI op
# bits are separate handshakes arbitrated by the tlu/dbg FSMs; the lockstep shadow core reuses the same
# synchronized dmi_reg_en qualifier through the delay_input_d buffers, which the tool mistakes for
# synchronizers. aon_timer: prim_reg_cdc handshake syncs converge at the cdc arb FSM / wdog compare /
# sticky intr logic, all designed for asynchronous arrival.
#=======================================================================================================================
waive_violation -add {SEP_CDC_COHERENCY_RECONV_COMB_5939} -comment {Tlu halt/run/irq requests are independent single-bit handshakes each synchronized alone; the tlu FSM arbitrates arrival order so no coherent multi-bit value is required, therefore not a risk} -filter [apply_prefix {(ConvergencePoint =~ "${PREFIX}u_sep_cpu/u_el2_veer_wrapper/veer/dec/tlu/*") AND (ReasonInfoList:ReasonInfo:ReasonCode == "SYNC_SRC_CONV")}] -app { cdc } -tag { CDC_COHERENCY_RECONV_COMB } -user { danielkim } -timestamp { 08-07-2026 21:26:00 }
waive_violation -add {SEP_CDC_COHERENCY_RECONV_COMB_5940} -comment {DMI op bits rd_en/wr_en are mutually exclusive by protocol (op=01 read / 10 write) so only one sync chain pulses per transaction and the OR at reg_en cannot merge skewed pulses, therefore not a risk} -filter [apply_prefix {(ConvergencePoint == "${PREFIX}u_sep_cpu/u_el2_veer_wrapper/dmi_wrapper/i_dmi_jtag_to_core_sync/reg_en") AND (ReasonInfoList:ReasonInfo:ReasonCode == "SYNC_SRC_CONV")}] -app { cdc } -tag { CDC_COHERENCY_RECONV_COMB } -user { danielkim } -timestamp { 08-07-2026 21:26:00 }
waive_violation -add {SEP_CDC_COHERENCY_RECONV_COMB_5942} -comment {Opentitan aon_timer internal single-bit prim_reg_cdc handshake syncs converge at the cdc arb FSM and sticky intr logic, both designed for async arrival, therefore not a risk} -filter [apply_prefix {(ConvergencePoint =~ "${PREFIX}u_sep_wdt_wrap/u_wdt_aon_timer/*") AND (ReasonInfoList:ReasonInfo:ReasonCode == "SYNC_SRC_CONV")}] -app { cdc } -tag { CDC_COHERENCY_RECONV_COMB } -user { danielkim } -timestamp { 08-07-2026 21:26:00 }
waive_violation -add {SEP_CDC_COHERENCY_RECONV_SEQ_5981} -comment {Opentitan aon_timer register cdc handshakes serialize per register and wdog config is quasi-static before enable; convergence is registered in the dest domain, therefore not a risk} -filter [apply_prefix {(ConvergencePoint =~ "${PREFIX}u_sep_wdt_wrap/u_wdt_aon_timer/*") AND (ReasonInfoList:ReasonInfo:ReasonCode == "SYNC_SRC_CONV")}] -app { cdc } -tag { CDC_COHERENCY_RECONV_SEQ } -user { danielkim } -timestamp { 08-07-2026 21:26:00 }
waive_violation -add {SEP_CDC_COHERENCY_ASYNCSRCS_RECONV_SEQ_5975} -comment {Independent requests from different domains (DMI op bits, halt/run reqs, irqs) converge at the mstatus update enable; events are independent so arrival order is functionally arbitrary, therefore not a risk} -filter [apply_prefix {(ConvergencePoint =~ "${PREFIX}u_sep_cpu/u_el2_veer_wrapper/veer/dec/tlu/*") AND (ReasonInfoList:ReasonInfo:ReasonCode == "ASYNC_SRC_CONV")}] -app { cdc } -tag { CDC_COHERENCY_ASYNCSRCS_RECONV_SEQ } -user { danielkim } -timestamp { 08-07-2026 21:26:00 }

# Key Manager reset conditioner / kmcsr: warm_count and warm_hold_active* hold their
# warm-reset state through the sep_intermediate_reset deassert window to sequence
# cold -> warm, and the kmcsr soft_rst_q loads in that mode.
waive_violation -add {SEP_INTEGRITY_SYNCRESET_CONST_DEASSERT_key_manager} \
    -comment {Key Manager reset conditioner / kmcsr constant values under sep_intermediate_reset sync-deassert are intentional (warm-reset sequencing).} \
    -app { cdc } -tag { INTEGRITY_SYNCRESET_CONST_DEASSERT } -user { nbetik } -timestamp { 16-09-2026 12:50:22 } \
    -filter [apply_prefix {(Tag == "INTEGRITY_SYNCRESET_CONST_DEASSERT") AND (InstanceName =~ "${PREFIX}u_sep_crypto/u_key_manager_s3c_scan/*")}]

# =============================================================================
# Warning-class dispositions
# =============================================================================

waive_violation -add {SEP_INTEGRITY_RESET_ASYNC_AND_SYNC_USAGE_METHODOLOGY} -comment {Async-assert/sync-consume on the reset-controller outputs, the intermediate reset, the KM warm-reset tail and rst_ni is the project reset methodology.} -filter [apply_prefix {(ResetObject =~ "${PREFIX}u_sep_reset_ctrl/*") OR (ResetObject == "${PREFIX}u_sep_crypto/sep_intermediate_reset_no") OR (ResetObject == "${PREFIX}u_sep_crypto/u_key_manager_s3c_scan/u_reset_conditioner/rst_warm_sync_no") OR (ResetObject == "${PREFIX}rst_ni")}] -app { cdc } -tag { INTEGRITY_RESET_ASYNC_AND_SYNC_USAGE } -user { nbetik } -timestamp { 16-09-2026 12:50:22 }
waive_violation -add {SEP_INTEGRITY_ASYNCRESET_COMBO_MUX_RESET_DIST} -comment {Reset mux/gating ahead of async pins with registered or conditioned functional sources (reset-controller AND gates, VeeR dbg, efuse reset sync, system CSR); scan legs case-pinned.} -filter [apply_prefix {(ContainerInstance =~ "${PREFIX}u_sep_reset_ctrl/u_*_rst_and") OR (ContainerInstance =~ "${PREFIX}u_sep_cpu/u_el2_veer_wrapper/veer*") OR (ContainerInstance == "${PREFIX}u_sep_crypto/u_sep_efuse_wrapper/u_efuse_interface_controller/u_reset_release_and") OR (ContainerInstance == "${PREFIX}sep_system_peripherals/u_sep_system_csr")}] -app { cdc } -tag { INTEGRITY_ASYNCRESET_COMBO_MUX } -user { nbetik } -timestamp { 16-09-2026 12:50:22 }
waive_violation -add {SEP_SETUP_RESET_OVERLAP_RESET_TREE} -comment {AND-combined hierarchical reset tree; overlap between parent and derived resets is by construction and ordering is declared in sep.resets.tcl. RST_NI / WDT_RST_NI also listed under their SMU aliases.} -filter [apply_prefix {((SrcRstInfo:ResetName == "SEP_INTERMEDIATE_RESET_N") OR (SrcRstInfo:ResetName == "SEP_RESET_N") OR (SrcRstInfo:ResetName == "RST_NI") OR (SrcRstInfo:ResetName == "PRIMARY_RESET_N_SMC_CLK") OR (SrcRstInfo:ResetName == "WDT_RST_NI") OR (SrcRstInfo:ResetName == "WDT_RESET_N_SMC_CLK")) AND ((DesRstInfo:ResetName =~ "SEP_SW_RST_*") OR (DesRstInfo:ResetName == "SEP_CPU_RESET_N") OR (DesRstInfo:ResetName == "SEP_RESET_N") OR (DesRstInfo:ResetName =~ "SEP_RESET_N_REFCNT_*"))}] -app { cdc } -tag { SETUP_RESET_OVERLAP } -user { nbetik } -timestamp { 16-09-2026 12:50:22 }
waive_violation -add {SEP_SETUP_RESET_DRIVING_NON_ASYNC_PIN_SYNC_TAILS} -comment {rst_ni, traced through the EDN ack state flop, reaches efuse-wrapper status/control flops as data; the efuse wrapper is the only consumer.} -filter [apply_prefix {(ResetName == "${PREFIX}rst_ni") AND (NonResetInstance =~ "${PREFIX}u_sep_crypto/u_sep_efuse_wrapper/*")}] -app { cdc } -tag { SETUP_RESET_DRIVING_NON_ASYNC_PIN } -user { nbetik } -timestamp { 16-09-2026 12:50:22 }
waive_violation -add {SEP_SETUP_RESET_DRIVING_NON_ASYNC_PIN_TRNG_CSR_QE} -comment {Tool artifact: the TRNG reset only clears the CSRNG cmd_req0_qe flop, but the tool treats that flop's Q (the SW command-valid pulse) as carrying the reset and follows it into EDN / entropy FIFO data outside the TRNG domain. The downstream flops receive a clock-domain pulse, never the reset value.} -filter [apply_prefix {(ResetName =~ "*sep_crypto_gated_rst_n.trng") AND (ResetInstance =~ "${PREFIX}u_sep_crypto/u_sep_trng/u_drbg_s3c_scan/u_csrng/u_reg/u_cmd_req0_qe/*")}] -app { cdc } -tag { SETUP_RESET_DRIVING_NON_ASYNC_PIN } -user { nbetik } -timestamp { 17-09-2026 11:44:06 }
waive_violation -add {SEP_SETUP_ASYNCRESET_UNUSED_INDIRECT} -comment {AND-tree / conditioner-consumed resets have no direct async-pin fanout by construction.} -filter [apply_prefix {((Reset:ResetName == "WDT_RST_NI") OR (Reset:ResetName == "WDT_RESET_N_SMC_CLK")) OR (Reset:ResetName == "SEP_SW_RST_KM")}] -app { cdc } -tag { SETUP_ASYNCRESET_UNUSED } -user { nbetik } -timestamp { 16-09-2026 12:50:22 }
waive_violation -add {SEP_SETUP_CLOCK_UNUSED_BOUNDARY_CLKS} -comment {Output-port memory clocks (PKA IMEM/DMEM, CPU TCM) clock no internal sequentials by construction.} -filter [apply_prefix {(Clock:ClkName =~ "SEPCLK_PKA_*") OR (Clock:ClkName == "SEPCLK_CPU_TCM")}] -app { cdc } -tag { SETUP_CLOCK_UNUSED } -user { nbetik } -timestamp { 16-09-2026 12:50:22 }
waive_violation -add {SEP_SETUP_MULTIPLE_CONSTRAINTS_SCAN_RESET} -comment {Intentional mode split: scan reset declared for role modeling, case-pinned inactive in the functional scenario.} -filter [apply_prefix {(InstanceName == "scan_rst_ni")}] -app { cdc } -tag { SETUP_MULTIPLE_CONSTRAINTS } -user { nbetik } -timestamp { 16-09-2026 12:50:22 }
