# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2026 Tenstorrent USA, Inc.
"""Backup manifest selects a RESERVED ROM key slot -> terminal.

The primary's magic is broken to force failover. The backup's ``public_key_select_classic`` names
``KEY_SLOT_FIRST_ROM_RESERVED``, the bottom of the ``[7:6]`` pair. All six ROM classical slots
carry a digest in the ``bootrom/prod`` compiled-in table (``include/key_digests.h``, generated by
``tools/generate_key_digests.py``), so a reserved slot is the only anchorless slot a manifest can
select.

The RSA modulus comes from the manifest, and a reserved slot has no anchor and a clear fuse bit. A
skipped bind would verify the manifest against its own modulus, so the ROM must refuse the slot
with ``PUBK_SLOT_RESERVED`` before ``RSA_EXEC``. Only the slot number is invalid.
``sep_firmware_backup_rom_key_index_invalid_test`` drives the same token at
``KEY_SLOT_FIRST_RESERVED`` in ``[31:26]``, so the ``PUBK_SEL=`` echo names the region.
``PUBK_SLOT_UNPROVISIONED``, ``PUBK_SEL_AMBIGUOUS``, ``PUBK_OTP_EMPTY`` and ``RSA_EXEC`` are
forbidden.
"""

from __future__ import annotations

from pathlib import Path

import pyuvm
from env import sep_manifest_mutate as mm
from rom_fw.sep_backup_manifest_fail_base import (
    MANIFEST_ERR_KEY_UNAUTHORIZED,
    sep_backup_manifest_fail_base,
)

_EFUSE_PRELOAD = (
    Path(__file__).resolve().parents[3]
    / "tb"
    / "efuse_preloads"
    / "efuse_configurations"
    / "sep_efuse_lc_prod.toml"
)

# The first RESERVED ROM classical slot. Slots 0..5 all carry a digest, so naming
# one of those would exercise the digest COMPARISON rather than the refusal this
# testcase is about.
_RESERVED_SLOT = mm.KEY_SLOT_FIRST_ROM_RESERVED
_PUBK_SEL_VALUE = _RESERVED_SLOT


@pyuvm.test()
class sep_firmware_backup_unpopulated_rom_key_slot_test(sep_backup_manifest_fail_base):
    """Primary fails over -> backup selects a reserved ROM key slot -> terminal."""

    backup_defect_marker = "PUBK_SLOT_RESERVED"
    expected_error = MANIFEST_ERR_KEY_UNAUTHORIZED
    efuse_preload = _EFUSE_PRELOAD
    # Every arm that would make the verdict mean something other than "the slot
    # had no digest", plus proof the modulus never reached the verifier.
    extra_forbidden = (
        "RSA_EXEC",
        "RSA_VERIFY_OK",
        "PUBK_SLOT_UNPROVISIONED",
        "PUBK_SEL_AMBIGUOUS",
        "PUBK_OTP_EMPTY",
    )

    def corrupt_backup(self, buf: bytearray) -> None:
        mm.set_public_key_sel(buf, "backup", selection=0, index=_RESERVED_SLOT)
        got = mm.get_public_key_sel(buf, "backup")
        assert got == _PUBK_SEL_VALUE, (
            f"backup public_key_sel names slot {got}, expected {_PUBK_SEL_VALUE} "
            f"(the first unprovisioned ROM classical slot)"
        )
        mm.verify_layout(buf, "backup")
        self.logger.info(
            "CHK-STIMULUS-EMPTY-SLOT: backup public_key_sel=0x%04x "
            "(ROM key slot %d, no compiled-in digest), signed region re-hashed",
            got,
            _RESERVED_SLOT,
        )

    def check_efuse(self, image) -> None:
        # Both of these run before slot resolution and would end the run first,
        # making the PUBK_SLOT_RESERVED verdict unreachable and the test vacuous.
        bl1_ver = image.field_int("BL1_VERSION")
        assert bl1_ver == 0, (
            f"BL1_VERSION is 0x{bl1_ver:x}, expected 0: anti-rollback cannot reject a "
            f"manifest when the device carries no security flags, and that is what "
            f"keeps this verdict attributable to the check under test"
        )
        revoke = image.field_int("CHIPLET_PUBK_REVOKE")
        assert revoke == 0, (
            f"CHIPLET_PUBK_REVOKE is 0x{revoke:x}, expected 0: slot "
            f"{_RESERVED_SLOT} must not be revoked, or the rejection would be "
            f"attributable to revocation rather than to the reserved slot"
        )

    def _check(self, console, status_seq, fw_done, fw_pass, retired) -> None:
        super()._check(console, status_seq, fw_done, fw_pass, retired)
        # The selector the ROM actually read, so the verdict belongs to this
        # stimulus rather than to some other malformed field.
        marker = f"PUBK_SEL=0x{_PUBK_SEL_VALUE:08x}"
        assert any(marker in line for line in console), (
            f"ROM never printed {marker}: the PUBK_SLOT_RESERVED verdict cannot be "
            f"attributed to the slot this test selected. Console: {console}"
        )
        self.logger.info("CHK-RESERVED-SLOT-ECHO: ROM read %s", marker)
