# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2026 Tenstorrent USA, Inc.
"""Backup manifest selects REVOKED ROM key slot 1 -> terminal.

The scenario and assertions are in ``sep_pubkey_rom_revoked_base``; this module picks the slot.
``sep_efuse_lc_prod_pubk_revoke1.toml`` is ``sep_efuse_lc_prod.toml`` plus only
``CHIPLET_PUBK_REVOKE`` bit 1. The backup slot is grafted from ``oca_rom_key1_boot.bin``: its
modulus hashes to the slot-1 digest in the ``bootrom/prod`` compiled-in table
(``include/key_digests.h``, generated by ``tools/generate_key_digests.py``) and its signature
verifies under that key. The fuse bit is the only cause of the refusal.

The ROM authorizes before it consults the revocation bitmap, so ``PUBK_UNAUTHORIZED`` and
``PUBK_SLOT_UNPROVISIONED`` are forbidden: either one means the graft did not land.
"""

from __future__ import annotations

import pyuvm
from rom_fw.sep_pubkey_rom_revoked_base import sep_pubkey_rom_revoked_base


@pyuvm.test()
class sep_firmware_backup_pubkey_rom_1_revoked_key_test(sep_pubkey_rom_revoked_base):
    """Primary fails over -> backup selects revoked ROM slot 1 -> terminal."""

    _REVOKED_SLOT = 1
