# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2026 Tenstorrent USA, Inc.
#
# tclint-disable line-length

# For waiving violations on open-source 3rd party IP

#=======================================================================================================================
# RULE INFO:
#=======================================================================================================================
# STARC05-1_1_1_1: Module name should be the same as file name
# STARC05-3_3_1_4b: Flop should have async set or reset
# W362: Arithmetic comparison with unequal length
# W164b: LHS of assignment wider than RHS
# STARC05-2_1_3_1: width of function arguments must match width of function inputs
# W553: Different bits of a bus are driven in different combinational blocks
# W391: Module driven by both edges of a clock
# STARC05-2_10_6_1: Possible loss of carry or borrow in addition or subtraction when width of LHS = width of RHS
# W401: Clock generated internally in module
# W193: Empty statement (isolated semicolon)
# W123: Signal is read but not set
# W240: Input declared but not read
# STARC05-1_3_1_3: Async reset used as sync reset or non-reset
# STARC05-2_11_3_1: Sequential and combinational parts of FSM described in same "always" block
# W415: Signal has multiple drivers but is not declared a tri-state
#=======================================================================================================================

# iDMA

# PULP AXI
# Prefix for Module filters; set by the flow's post_proc script.
# Defaults to empty string so waivers still match unprefixed module names.
if { ![info exists PREFIX] } {
    set PREFIX ""
}
# Substitute the literal ${PREFIX} token in a -filter expression with $PREFIX's
# value. Uses string map rather than brace interpolation so that $clog2, bus
# indices like [i], and embedded quotes inside the filter are preserved verbatim.
proc apply_prefix { filter } {
    return [string map [list {${PREFIX}} $::PREFIX] $filter]
}

# Build an OR-of-equals Module predicate from a module-name list. Applies the packager module-name
# prefix when the occupying flow sets one.
proc module_any { mods } {
    set p ""
    if { [info exists ::PREFIX] } { set p $::PREFIX }
    set parts {}
    foreach m $mods { lappend parts "(Module == \"${p}${m}\")" }
    return "([join $parts { OR }])"
}

waive_violation -add {SMC_W146_cdc_fifo_gray_dst} -comment {Created by nbetik on 27-Feb-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}cdc_fifo_gray_dst")}] -app { lint } -tag { W146 } -user { nbetik } -timestamp { 27-02-2026 15:46:58 }
waive_violation -add {SMC_W146_cdc_fifo_gray_src} -comment {Common cells component. Lint category is for visual cleanliness only. Created by nbetik on 27-Feb-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}cdc_fifo_gray_src")}] -app { lint } -tag { W146 } -user { nbetik } -timestamp { 27-02-2026 15:41:45 }
waive_violation -add {SMC_W193_axi_lite_mailbox_slave} -comment {PULP axi component. Lint category is for visual cleanliness only. Created by nbetik on 27-Feb-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}axi_lite_mailbox_slave")}] -app { lint } -tag { W193 } -user { nbetik } -timestamp { 27-02-2026 15:42:58 }
waive_violation -add {SMC_W193_axi_lite_to_apb} -comment {PULP axi component. Lint category is for visual cleanliness only. Created by nbetik on 27-Feb-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}axi_lite_to_apb")}] -app { lint } -tag { W193 } -user { nbetik } -timestamp { 27-02-2026 15:43:44 }
waive_violation -add {SMC_W193_axi_lite_from_mem} -comment {PULP axi component. Lint category is for visual cleanliness only. Created by nbetik on 27-Feb-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}axi_lite_from_mem")}] -app { lint } -tag { W193 } -user { nbetik } -timestamp { 27-02-2026 15:44:14 }
waive_violation -add {SMC_W193_axi_isolate_inner} -comment {PULP axi component. Lint category is for visual cleanliness only. Created by nbetik on 27-Feb-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}axi_isolate_inner")}] -app { lint } -tag { W193 } -user { nbetik } -timestamp { 27-02-2026 15:44:41 }
waive_violation -add {SMC_NoGenLabel-ML_axi_isolate} -comment {PULP axi component. Lint category is for visual cleanliness only. Created by nbetik on 27-Feb-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}axi_isolate")}] -app { lint } -tag { NoGenLabel-ML } -user { nbetik } -timestamp { 27-02-2026 15:45:42 }
waive_violation -add {SMC_NoGenLabel-ML_axi_err_slv} -comment {PULP axi component. Lint category is for visual cleanliness only. Created by nbetik on 27-Feb-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}axi_err_slv")}] -app { lint } -tag { NoGenLabel-ML } -user { nbetik } -timestamp { 27-02-2026 15:46:25 }
waive_violation -add {SMC_NoGenLabel-ML_axi_demux_simple} -comment {PULP axi component. Lint category is for visual cleanliness only. Created by nbetik on 27-Feb-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}axi_demux_simple") AND (NodeType == "generate-if") AND (Module_Name == "${PREFIX}axi_demux_simple") AND (Statement == "  end else begin")}] -app { lint } -tag { NoGenLabel-ML } -user { nbetik } -timestamp { 27-02-2026 15:50:05 }
waive_violation -add {SMC_W193_axi_burst_splitter} -comment {PULP axi component. Lint category is for visual cleanliness only.Created by nbetik on 27-Feb-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}axi_burst_splitter") AND (Statement == "      default: /*do nothing*/;")}] -app { lint } -tag { W193 } -user { nbetik } -timestamp { 27-02-2026 15:50:34 }

# iDMA (ETH-Z / PULP iDMA)
waive_violation -add {SMC_STARC05-2_1_5_3_idma_next_id_re_temp} -comment {PULP IDMA IP. Bit 0 of multi-bit signal is assigned a value and will drive the condition correctly. Created by nbetik on 28-Apr-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}idma_reg64_2d") AND (Statement == "            if (next_id_re_temp[c]) begin")}] -app { lint } -tag { STARC05-2.1.5.3 } -user { nbetik } -timestamp { 28-04-2026 11:00:49 }
waive_violation -add {SMC_STARC05-2_10_6_1_idma_midend_dst_addr} -comment {ETH-Z IDMA IP. Arithmetic is for stride walker and is intended to wrap around. Created by nbetik on 22-Apr-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}idma_nd_midend") AND (LHS_Size == "56") AND (RHS_Size == "56") AND (Statement == "                dst_addr_d = dst_addr_q + nd_req_i.d_req[stride_sel_q].dst_strides;")}] -app { lint } -tag { STARC05-2.10.6.1 } -user { nbetik } -timestamp { 22-04-2026 15:41:49 }
waive_violation -add {SMC_STARC05-2_10_6_1_idma_legalizer_r_num_bytes} -comment {ETH-Z IDMA IP. Subtraction is guarded by the containing conditional clause. Created by nbetik on 22-Apr-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}idma_legalizer_rw_axi") AND (LHS_Size == "56") AND (RHS_Size == "56") AND (Statement == "            r_tf_d.length = r_tf_q.length - r_num_bytes_possible;")}] -app { lint } -tag { STARC05-2.10.6.1 } -user { nbetik } -timestamp { 22-04-2026 15:54:47 }
waive_violation -add {SMC_STARC05-2_10_6_1_idma_legalizer_r_tf_addition} -comment {Wraparound is intended for AXI DMA. Created by nbetik on 22-Apr-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}idma_legalizer_rw_axi") AND (LHS_Size == "56") AND (RHS_Size == "56") AND (Statement == "            r_tf_d.addr = r_tf_q.addr + r_num_bytes;")}] -app { lint } -tag { STARC05-2.10.6.1 } -user { nbetik } -timestamp { 22-04-2026 15:59:44 }
waive_violation -add {SMC_STARC05-2_10_6_1_idma_legalizer_page_splitter_pb} -comment {ETH-Z IP IDMA IP. Subtraction is guarded by creation of page_offset. Created by nbetik on 22-Apr-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}idma_legalizer_page_splitter") AND (LHS_Size == "12") AND (RHS_Size == "12") AND (Statement == "    assign num_bytes_to_pb_o = page_size - page_offset;")}] -app { lint } -tag { STARC05-2.10.6.1 } -user { nbetik } -timestamp { 22-04-2026 16:10:03 }
waive_violation -add {SMC_STARC05-2_10_6_1_idma_legalizer_num_bytes_possible} -comment {Subtraction underflow is guarded by containing conditional statement. Created by nbetik on 23-Apr-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}idma_legalizer_rw_axi") AND (LHS_Size == "56") AND (RHS_Size == "56") AND (Statement == "            w_tf_d.length = w_tf_q.length - w_num_bytes_possible;")}] -app { lint } -tag { STARC05-2.10.6.1 } -user { nbetik } -timestamp { 23-04-2026 14:19:29 }
waive_violation -add {SMC_STARC05-2_10_6_1_idma_legalizer_rw_axi} -comment {ETH-Z IDMA IP. Software is responsible for not creating writes that will exceed the bounds of the address map. Created by nbetik on 23-Apr-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}idma_legalizer_rw_axi") AND (LHS_Size == "56") AND (RHS_Size == "56") AND (Statement == "            w_tf_d.addr = w_tf_q.addr + w_num_bytes;") AND (HIERARCHY == "smc.u_smc_base.u_smc_data_accelerator_wrap.u_dma_wrap.dma_backend.gen_iDMA_to_axi_out[0].u_iDMA_backend.gen_hw_legalizer.i_idma_legalizer")}] -app { lint } -tag { STARC05-2.10.6.1 } -user { nbetik } -timestamp { 23-04-2026 14:23:23 }
waive_violation -add {SMC_STARC05-2_10_6_1_idma_src_addr_d} -comment {PULP IDMA IP. Wraparound is intended behaviour. Created by nbetik on 28-Apr-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}idma_nd_midend") AND (LHS_Size == "56") AND (RHS_Size == "56") AND (Statement == "                src_addr_d = src_addr_q + nd_req_i.d_req[stride_sel_q].src_strides;")}] -app { lint } -tag { STARC05-2.10.6.1 } -user { nbetik } -timestamp { 28-04-2026 11:02:07 }
waive_violation -add {SMC_checkIOPinConnectedToNet_idma_reg64_2d_reg_top_q} -comment {Created by gchang on 12-Aug-2026. Instances of prim_subreg and prim_subreg_ext have unconnected outputs. The register map specifies no hardware consumer for these outputs, so intentional and not mistakenly disconnected. Directly editing these away would get clobbered on regeneration, so waive.} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}idma_reg64_2d_reg_top") AND (C_CELL_NAME =~ "prim_subreg*") AND (ObjInputPin =~ "*.q")}] -app { lint } -tag { checkIOPinConnectedToNet } -user { gchang } -timestamp { 12-08-2026 12:38:35 }
waive_violation -add {SMC_checkIOPinConnectedToNet_idma_reg64_2d_reg_top_qe} -comment {Created by gchang on 12-Aug-2026. Instances of prim_subreg and prim_subreg_ext have unconnected outputs. The register map specifies no hardware consumer for these outputs, so intentional and not mistakenly disconnected. Directly editing these away would get clobbered on regeneration, so waive.} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}idma_reg64_2d_reg_top") AND (C_CELL_NAME =~ "prim_subreg*") AND (ObjInputPin =~ "*.qe")}] -app { lint } -tag { checkIOPinConnectedToNet } -user { gchang } -timestamp { 12-08-2026 12:38:35 }
waive_violation -add {SMC_checkIOPinConnectedToNet_idma_reg64_2d_reg_top_qre} -comment {Created by gchang on 12-Aug-2026. Instances of prim_subreg and prim_subreg_ext have unconnected outputs. The register map specifies no hardware consumer for these outputs, so intentional and not mistakenly disconnected. Directly editing these away would get clobbered on regeneration, so waive.} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}idma_reg64_2d_reg_top") AND (C_CELL_NAME =~ "prim_subreg*") AND (ObjInputPin =~ "*.qre")}] -app { lint } -tag { checkIOPinConnectedToNet } -user { gchang } -timestamp { 12-08-2026 12:38:35 }
waive_violation -add {SMC_checkIOPinConnectedToNet_idma_reg64_2d_reg_top_ds} -comment {Created by gchang on 12-Aug-2026. Instances of prim_subreg and prim_subreg_ext have unconnected outputs. The register map specifies no hardware consumer for these outputs, so intentional and not mistakenly disconnected. Directly editing these away would get clobbered on regeneration, so waive.} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}idma_reg64_2d_reg_top") AND (C_CELL_NAME =~ "prim_subreg*") AND (ObjInputPin =~ "*.ds")}] -app { lint } -tag { checkIOPinConnectedToNet } -user { gchang } -timestamp { 12-08-2026 12:38:35 }
waive_violation -add {SMC_W116_idma_reg64_2d_read_happens} -comment {Created by nbetik on 22-Apr-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}idma_reg64_2d") AND (LHS_Size == "1") AND (LHSExpr == "read_happens") AND (RHS_Size == "32") AND (RHSExpr == "next_id_re_temp[c]") AND (Signal == "|")}] -app { lint } -tag { W116 } -user { nbetik } -timestamp { 22-04-2026 15:29:20 }
waive_violation -add {SMC_W164b_idma_reg64_2d_next_id_re_temp} -comment {iDMA generated code. Edit was made to uniquify indexes but containing type was not changed accordingly. Upper bits will zero-extend, no risk but should clean up for clarity. Created by nbetik on 22-Apr-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}idma_reg64_2d") AND (LHS_Size == "32") AND (LHSExpr =~ "next_id_re_temp[*]") AND (RHS_Size == "1") AND (RHSExpr =~ "dma_reg2hw[i].next_id_*.re")}] -app { lint } -tag { W164b } -user { nbetik } -timestamp { 22-04-2026 15:14:15 }
waive_violation -add {SMC_W164b_idma_reg64_2d_status} -comment {iDMA generated code. The status register field is one bit wider than the {midend_busy, busy} value; the upper bit zero-extends with no functional impact. 3rd-party generated IP. Created by nbetik on 09-Jun-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}idma_reg64_2d") AND (LHSExpr == "dma_hw2reg[i].status[c]") AND (LHS_Size == "10") AND (RHS_Size == "9")}] -app { lint } -tag { W164b } -user { nbetik } -timestamp { 09-06-2026 10:00:00 }
waive_violation -add {SMC_W362_idma_legalizer_num_bytes_possible} -comment {ETH-Z IP. Comparison will zero-extend the narrower width. Created by nbetik on 23-Apr-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}idma_legalizer_rw_axi") AND (OpType == ">") AND (LHS_Size == "56") AND (RHS_Size == "12") AND (Statement =~ "        if (*_tf_q.length > *_num_bytes_possible) begin")}] -app { lint } -tag { W362 } -user { nbetik } -timestamp { 23-04-2026 14:25:17 }

# I3C (CHIPS Alliance i3c-core)
waive_violation -add {SMC_ImproperRangeIndex-ML_i3c_flow_active_dct_raw_data} -comment {8-entry array indexed by (transfer_cnt_q - 3), where transfer_cnt_q is a 32-bit counter. transfer_cnt_q only ever ranges 3-10, so index ranges 0-7, exactly matches the array. Vendored ChipsAlliance i3c-core IP, not modified. Created by gchang on 12-Aug-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}flow_active") AND (NodeName =~ "dct_raw_data_*") AND (RTL_EXPRESSION == "(transfer_cnt_q - 3)") AND (MaxValue == "7")}] -app { lint } -tag { ImproperRangeIndex-ML } -user { gchang } -timestamp { 12-08-2026 12:38:35 }
waive_violation -add {SMC_ImproperRangeIndex-ML_i3c_flow_active_ibi_data} -comment {32-entry array read as ibi_data_q[ibi_wb_cnt_q-1]. ibi_wb_cnt_q is 6 bits so lint sees a possible overrun. The index is bounded by ceil(data_length/4)-1, data_length is bounded by ibi_max_data_dwords_i, and ibi_max_data_dwords_i is clamped in hardware to IBI_BUFFER_DEPTH (32) at controller_active.sv:196. Max index is 31, in range. NOTE: that clamp is in the parent module, so recheck if flow_active is to be instantiated elsewhere (Only instantiated once currently). Vendored ChipsAlliance i3c-core IP, not modified. Created by gchang on 12-Aug-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}flow_active") AND (NodeName == "ibi_data_q") AND (RTL_EXPRESSION == "(ibi_wb_cnt_q - 1)") AND (MaxValue == "31")}] -app { lint } -tag { ImproperRangeIndex-ML } -user { gchang } -timestamp { 12-08-2026 12:38:35 }
waive_violation -add {SMC_STARC05-2_2_3_3_i3c_controller_standby_err} -comment {Set/clear priority idiom. err_o is set by protocol_err then cleared by get_status_done in the same always_ff, so the clear wins when both fire in a cycle. Last-assignment-wins is well defined and synthesizes to a priority mux. Vendored ChipsAlliance i3c-core IP, not modified. Created by gchang on 12-Aug-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}controller_standby") AND (Clock_Register == "err_o")}] -app { lint } -tag { STARC05-2.2.3.3 } -user { gchang } -timestamp { 12-08-2026 12:38:35 }
waive_violation -add {SMC_STARC05-2_2_3_3_i3c_target_fsm_rx_fifo_wvalid} -comment {Set/clear priority idiom. rx_fifo_wvalid_o is set when data is available and cleared on the (wvalid_o & wready_i) handshake in the same always_ff, so the clear wins when both fire in a cycle. Vendored ChipsAlliance i3c-core IP, not modified. Created by gchang on 12-Aug-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}i3c_target_fsm") AND (Clock_Register == "rx_fifo_wvalid_o")}] -app { lint } -tag { STARC05-2.2.3.3 } -user { gchang } -timestamp { 12-08-2026 12:38:35 }
waive_violation -add {SMC_STARC05-2_2_3_3_i3c_read_queue_fifo_rready} -comment {Set/clear priority idiom. fifo_rready is set on req_i and cleared on the (rready & rvalid) handshake in the same always_ff, so the clear wins when both fire in a cycle. Vendored ChipsAlliance i3c-core IP, not modified. Created by gchang on 12-Aug-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}read_queue") AND (Clock_Register == "fifo_rready")}] -app { lint } -tag { STARC05-2.2.3.3 } -user { gchang } -timestamp { 12-08-2026 12:38:35 }
waive_violation -add {SMC_STARC05-2_2_3_3_i3c_write_queue_fifo_signals} -comment {Set/clear priority idiom. fifo_wvalid and fifo_wdata are set when a request arrives (req_i / start_valid) and cleared on the (wvalid & wready) handshake in the same always_ff, so the clear wins when both fire in a cycle. Vendored ChipsAlliance i3c-core IP, not modified. Created by gchang on 12-Aug-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}write_queue") AND (Clock_Register =~ "fifo_w*")}] -app { lint } -tag { STARC05-2.2.3.3 } -user { gchang } -timestamp { 12-08-2026 12:38:35 }
waive_violation -add {SMC_STARC05-2_2_3_3_i3c_write_queue_ack} -comment {Set/clear priority idiom. ack_o is asserted both when the second dword of a 64-bit command is captured and when the FIFO write handshake completes; the handshake assignment comes later and takes priority. Vendored ChipsAlliance i3c-core IP, not modified. Created by gchang on 12-Aug-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}write_queue") AND (Clock_Register == "ack_o")}] -app { lint } -tag { STARC05-2.2.3.3 } -user { gchang } -timestamp { 12-08-2026 12:38:35 }
waive_violation -add {SMC_STARC05-2_11_3_1_i3c_ctrl_bus_tx_flow_bit_counter} -comment {FSM uses both sequential and combinational logic in same always block. Functions the same as splitting into separate blocks, just a coding style. Vendored IP, don't modify. Created by gchang on 14-Aug-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}ctrl_bus_tx_flow") AND (Signal == "bit_counter") AND (Statement == "          if (bit_counter == 4'h0) bit_counter <= 4'h7;")}] -app { lint } -tag { STARC05-2.11.3.1 } -user { gchang } -timestamp { 14-08-2026 15:30:00 }
waive_violation -add {SMC_W164b_i3c_recovery_receiver_concat_pad} -comment {LHS > RHS. RHS is zero-extended to match, safe. Vendored IP, not modified. Created by gchang on 12-Aug-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}recovery_receiver") AND (LHS_Size == "32") AND (RHSExpr =~ "*'0 ,*")}] -app { lint } -tag { W164b } -user { gchang } -timestamp { 12-08-2026 12:38:35 }
waive_violation -add {SMC_W164b_i3c_bus_start_stop_gen_total_hold_repeated_start} -comment {total_hold_repeated_start is declared one bit wider than the sum assigned to it so the carry cannot be lost. Matching the widths would remove the carry headroom. Vendored IP, not modified. Created by gchang on 12-Aug-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}bus_start_stop_gen") AND (LHSExpr == "total_hold_repeated_start") AND (LHS_Size == "23") AND (RHS_Size == "22")}] -app { lint } -tag { W164b } -user { gchang } -timestamp { 12-08-2026 12:38:35 }
waive_violation -add {SMC_W164b_i3c_ctrl_bus_tx_tcount} -comment {tcount_d is a timer counter declared one bit wider than the t_hd_dat_i timing input it loads, giving headroom for the counter arithmetic. Unsigned, so the value zero-extends on load. Vendored IP, not modified. Created by gchang on 12-Aug-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}ctrl_bus_tx") AND (LHSExpr == "tcount_d") AND (LHS_Size == "21") AND (RHSExpr == "t_hd_dat_i") AND (RHS_Size == "20")}] -app { lint } -tag { W164b } -user { gchang } -timestamp { 12-08-2026 12:38:35 }
waive_violation -add {SMC_W164b_i3c_flow_active_resp_data_length} -comment {The 16-bit response data_length field is assigned a 5-bit difference (dev_count - assigned_addr_cnt_q), which zero-extends. The subtraction cannot underflow: the enclosing if handles the equal case separately (assigned_addr_cnt_q == dev_count assigns '0), and the case where assigned_addr_cnt_q > dev_count is guarded (flow_active.sv:540 only re-arms a DAA frame while assigned_addr_cnt_q <= dev_count, and :1427 terminates DAA once assigned_addr_cnt_q >= dev_count, so the counter cannot pass dev_count). So this branch only runs when assigned_addr_cnt_q is strictly less than dev_count. Vendored IP, not modified. Created by gchang on 12-Aug-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}flow_active") AND (LHSExpr == "resp_data_length_d") AND (LHS_Size == "16") AND (RHSExpr == "(addr_cmd_desc.dev_count - assigned_addr_cnt_q)") AND (RHS_Size == "5")}] -app { lint } -tag { W164b } -user { gchang } -timestamp { 12-08-2026 12:38:35 }
# i3c-core modules whose FSMs use an explicit `default: ;` arm (latch-avoidance idiom).
set SMC_I3C_CORE_FSM_MODULES {
    controller_standby_i3c ctrl_bus_rx_flow ctrl_bus_tx_flow
}

waive_violation -add {SMC_W193_i3c_core_fsm_default} -comment {Created by gchang on 12-Aug-2026. Empty default in FSM case statement. Safe, intentional, and vendor IP.} -filter [concat {(Goal == "lint_rtl_enhanced") AND (Statement =~ "*default: ;") AND} [module_any $SMC_I3C_CORE_FSM_MODULES]] -app { lint } -tag { W193 } -user { gchang } -timestamp { 12-08-2026 12:38:35 }
waive_violation -add {SMC_W287a_i3c_axi_adapter_sideband} -comment {Vendored i3c.sv has no ports for AxCACHE/AxPROT/AxQOS/AxREGION, so those axi_adapter inputs are left with nothing driving them. However, nothing uses those wires so they are dead with no functional effect, safe. Vendored IP, not modified. Created by gchang on 14-Aug-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}axi_adapter") AND (InstName == "axi_sif_i3c") AND (Signal =~ "axi.a*")}] -app { lint } -tag { W287a } -user { gchang } -timestamp { 14-08-2026 15:25:00 }
waive_violation -add {SMC_W362_i3c_flow_active_transfer_cnt_vs_data_length} -comment {transfer_cnt_q is a 32-bit transfer counter compared against the 16-bit data_length. Narrower operand is zero-extended, no information lost. Vendored IP, not modified. Created by gchang on 12-Aug-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}flow_active") AND (LHSExpr == "transfer_cnt_q") AND (LHS_Size == "32") AND (RHSExpr == "data_length") AND (RHS_Size == "16")}] -app { lint } -tag { W362 } -user { gchang } -timestamp { 12-08-2026 12:38:35 }
waive_violation -add {SMC_W362_i3c_flow_active_transfer_cnt_vs_ibi_max} -comment {32-bit transfer_cnt_q compared against ibi_max_data_dwords_i ($clog2(IBI_BUFFER_DEPTH+1) bits wide). Unsigned operands, so the narrow side is zero-extended and no information is lost. Vendored IP, not modified. Created by gchang on 12-Aug-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}flow_active") AND (LHSExpr == "transfer_cnt_q") AND (LHS_Size == "32") AND (RHSExpr =~ "*ibi_max_data_dwords_i*")}] -app { lint } -tag { W362 } -user { gchang } -timestamp { 12-08-2026 12:38:35 }
waive_violation -add {SMC_W362_i3c_bus_start_stop_gen_timer} -comment {Widths are intentionally mismatched to prevent overflow. Narrower operand zero-extended, no information lost. Vendored IP, not modified. Created by gchang on 12-Aug-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}bus_start_stop_gen") AND (LHSExpr == "timer_q") AND (LHS_Size == "24") AND (OpType == "<")}] -app { lint } -tag { W362 } -user { gchang } -timestamp { 12-08-2026 12:38:35 }
waive_violation -add {SMC_W362_i3c_bus_scl_flow_timer} -comment {Comment states operand is intentionally one bit wider. Narrower side is zero-extended, no information lost. Vendored IP, not modified. Created by gchang on 12-Aug-2026} -filter [apply_prefix {(Goal == "lint_rtl_enhanced") AND (Module == "${PREFIX}bus_scl_flow") AND (LHSExpr == "timer_q") AND (LHS_Size == "21") AND (OpType == ">")}] -app { lint } -tag { W362 } -user { gchang } -timestamp { 12-08-2026 12:38:35 }
