#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2026 Tenstorrent USA, Inc.

"""Generate a flattened SystemVerilog header from a SystemRDL register space.

Emits, for every register instance under the target address map: address and
offset localparams (arrays unrolled per index), per-register default-value
localparams, per-field mask/shift localparams, and per-register packed struct
typedefs.
"""

import argparse
import os
import sys

from systemrdl import RDLCompiler, RDLCompileError, RDLListener, RDLWalker
from systemrdl.node import AddressableNode, MemNode, SignalNode

SCRIPT_VERSION = "r2025-06-03"
BAR = "//=============================================================================="


class SvhListener(RDLListener):
    def __init__(self, root, args):
        self.root = root
        self.target_addr_map = args.addrmap
        self.shorten_names = args.shorten_names
        self.add_total_struct = args.add_total_struct
        self.addr_width = int(args.addr_width)
        self.input_file = args.input_rdl_file

        self.under_target = False
        self.header_text = ""
        self.addr_text = ""
        self.struct_text = ""
        self.bitfield_text = ""
        self.default_text = ""
        self.footer_text = ""
        # reg type name -> (raw_absolute_address, regwidth, [field tuples])
        self.regs = {}
        # reg instance name -> [array_dimensions, regwidth, type name, address]
        self.reg_inst_count = {}
        self.curr_reg_fields = []

    def path_minus_root(self, node):
        elems = node.get_path(array_suffix="_{index:d}_").split(".")[1:]
        return "_".join(elems)

    def def_name(self, node):
        if self.shorten_names:
            return node.get_path_segment(array_suffix="_{index:d}_").upper()
        return self.path_minus_root(node).upper()

    def localparam(self, name, value):
        decl = f"localparam {'long' if self.addr_width > 32 else ''}int unsigned {name}"
        digits = -(self.addr_width // -4)
        return f"{decl:110}    = {self.addr_width}'h{value:0{digits}X};\n"

    def section(self, title):
        return f"\n\n{BAR}\n// {title}\n{BAR}\n\n"

    def enter_Addrmap(self, node):
        name = node.get_path_segment()
        if self.shorten_names or node.parent == self.root:
            def_name = node.get_path_segment(array_suffix="_{index:d}_").upper() \
                if self.shorten_names else name.upper()
        else:
            def_name = self.def_name(node)

        if node.parent == self.root:
            if self.target_addr_map is None:
                self.target_addr_map = name
            header_def = self.target_addr_map.upper()
            self.header_text += f"""\
/*******************************************************************************
 * Header file for register addresses and fields
 *
 * This file was auto-generated by this script:
 *       {os.path.basename(sys.argv[0])}   ({SCRIPT_VERSION})
 * ... from this input file:
 *       {os.path.basename(self.input_file)}
 * ... using this as the target address space:
 *       {self.target_addr_map}
 *
 * This file should not be modified by hand.
 *
 ******************************************************************************/

`ifndef {header_def}_REG_SVH
`define {header_def}_REG_SVH

"""
            self.bitfield_text += (
                f"\n\n\n{BAR}\n// Bit Fields for Address Map: {self.target_addr_map}\n{BAR}\n\n"
            )
            self.footer_text += "\n`endif\n"

        if name == self.target_addr_map:
            self.under_target = True

        if not self.under_target:
            return

        if node.parent == self.root:
            # The SystemRDL spec gives a top-level addrmap base address zero;
            # use the lowest child address instead, which is more useful.
            base = min(
                (c.absolute_address for c in node.children(unroll=True)
                 if isinstance(c, AddressableNode)),
                default=0,
            )
            size = node.size - base
        else:
            base = node.absolute_address
            size = node.size

        self.addr_text += self.section(f"Addresses for Address Map: {name}") + "\n"
        self.addr_text += self.localparam(def_name + "_REG_MAP_BASE_ADDR", base)
        self.addr_text += self.localparam(def_name + "_REG_MAP_SIZE", size) + "\n\n"
        self.struct_text += "\n\n\n"

    def exit_Addrmap(self, node):
        if node.get_path_segment() == self.target_addr_map:
            self.under_target = False
            # Sort by address in preparation for the total struct.
            self.reg_inst_count = dict(
                sorted(self.reg_inst_count.items(), key=lambda item: item[1][3])
            )

    def enter_Regfile(self, node):
        if self.under_target:
            self.addr_text += self.section(f"Register File: {node.get_path_segment()}")
            self.addr_text += self.localparam(self.def_name(node) + "_REG_FILE_BASE_ADDR", node.absolute_address)
            self.addr_text += self.localparam(self.def_name(node) + "_REG_FILE_SIZE", node.size) + "\n"

    def enter_Mem(self, node):
        if self.under_target:
            self.addr_text += self.section(f"Memory: {node.get_path_segment()}")
            self.addr_text += self.localparam(self.def_name(node) + "_MEM_BASE_ADDR", node.absolute_address)
            self.addr_text += self.localparam(self.def_name(node) + "_MEM_SIZE", node.size) + "\n"

    def enter_Reg(self, node):
        if not self.under_target:
            return
        if self.shorten_names:
            fullname = (
                node.parent.get_path_segment(array_suffix="_{index:d}_").upper()
                + "_"
                + node.get_path_segment(array_suffix="_{index:d}_")
            )
        else:
            fullname = self.path_minus_root(node).upper()

        self.curr_reg_fields = []

        # No address constants for registers inside a memory array.
        if not (node.is_array and isinstance(node.parent, MemNode)):
            self.addr_text += self.localparam(fullname + "_REG_OFFSET", node.address_offset)
            self.addr_text += self.localparam(fullname + "_REG_ADDR", node.absolute_address)

    def exit_Reg(self, node):
        if not self.under_target:
            return
        parent = node.parent

        # Strip systemrdl's "_ispresent_t" decoration; prefer orig_type_name
        # because type_name grows a hash suffix when fields have
        # dynamically-assigned properties.
        fullname = parent.type_name.removesuffix("_ispresent_t").upper()
        if node.orig_type_name is None:
            fullname += "_" + node.type_name
        else:
            fullname += "_" + node.orig_type_name.upper()

        # Registers below the target addrmap get the parent name prepended to
        # avoid instance-name collisions. Arrays drop the index suffix here.
        if parent.get_path_segment().lower() == self.target_addr_map.lower():
            inst_name = node.get_path_segment(array_suffix="").upper()
        else:
            inst_name = (
                parent.get_path_segment(array_suffix="_{index:d}_").upper()
                + "_"
                + node.get_path_segment(array_suffix="").upper()
            )

        first_in_array = node.is_array and all(i == 0 for i in node.current_idx)
        if not node.is_array or first_in_array:
            self.reg_inst_count[inst_name] = [
                node.array_dimensions if node.is_array else None,
                node.get_property("regwidth"),
                fullname,
                node.absolute_address,
            ]

        self.curr_reg_fields = sorted(self.curr_reg_fields, key=lambda f: f[2])

        # A register type seen twice must have identical fields (reset values
        # may differ).
        if fullname in self.regs and self.regs[fullname][2] != self.curr_reg_fields:
            for i, field in enumerate(self.regs[fullname][2]):
                if any(field[k] != self.curr_reg_fields[i][k] for k in (0, 1, 2, 4)):
                    raise ValueError(f"ERROR: register '{fullname}' already exists")

        self.regs[fullname] = (
            node.raw_absolute_address,
            node.get_property("regwidth"),
            self.curr_reg_fields,
        )

    def enter_Field(self, node):
        if self.under_target:
            reset = node.get_property("reset")
            self.curr_reg_fields.append((
                node.get_path_segment(array_suffix="_{index:d}_"),
                node.high,
                node.low,
                0 if reset is None else reset,
                node.get_property("sw").name,
            ))

    def process_fields(self):
        self.struct_text += "\n"

        for reg_name, (_, reg_width, fields) in self.regs.items():
            mask_type = {
                8: "byte unsigned",
                16: "shortint unsigned",
                32: "int unsigned",
                64: "longint unsigned",
            }.get(reg_width, f"bit [{reg_width - 1}:0]")
            type_width = max(len(mask_type), len("int unsigned"))

            struct_fields = []
            bit_idx = 0
            rsvd_count = 0
            for name, high, low, _reset, _sw in fields:
                if bit_idx < low:
                    struct_fields.append(f"    logic [{low - bit_idx - 1}:0]   rsvd_{rsvd_count} ;\n")
                    bit_idx += low - bit_idx
                    rsvd_count += 1
                struct_fields.append(f"    logic [{high - low}:0]   {name.lower()} ;\n")
                bit_idx += high - low + 1

                max_mask = 2**reg_width - 1
                mask = (max_mask << low) & ~(max_mask << (high + 1))
                mask_decl = f"localparam {mask_type:>{type_width}} {reg_name}_{name.upper()}_MASK"
                shift_decl = f"localparam {'int unsigned':>{type_width}} {reg_name}_{name.upper()}_SHIFT"
                self.bitfield_text += f"{mask_decl:110}    = {reg_width}'h{mask:X};\n"
                self.bitfield_text += f"{shift_decl:110}    = {low};\n\n"

            self.struct_text += "typedef struct packed {\n"
            self.struct_text += "".join(reversed(struct_fields))
            self.struct_text += f"}} {reg_name.lower()}_reg_t;\n\n\n\n"

        if self.add_total_struct:
            rows = []
            for inst, (dims, _width, reg_type, _addr) in self.reg_inst_count.items():
                if dims:
                    vec = "".join(f"[{d - 1}:0]" for d in dims)
                    rows.append(f"    {reg_type.lower()}_reg_t {vec} {inst.lower()};\n")
                else:
                    rows.append(f"    {reg_type.lower()}_reg_t {inst.lower()};\n")
            self.struct_text += "typedef struct packed {\n"
            self.struct_text += "".join(reversed(rows))
            self.struct_text += f"}} {self.target_addr_map}_regmap_t;\n"

    def process_defaults(self):
        self.default_text += self.section("Default values for registers")

        for reg_name, (_, reg_width, fields) in self.regs.items():
            # Registers wider than 64 bits have no standard SV integral type.
            if reg_width > 64:
                continue
            reg_reset = 0
            for _name, _high, low, reset, _sw in fields:
                if isinstance(reset, SignalNode):
                    reset = 0
                reg_reset |= reset << low
            decl = f"localparam longint unsigned {reg_name}_REG_DEFAULT"
            width_str = "32" if reg_width <= 32 else "64"
            digits = -(reg_width // -4)
            self.default_text += f"{decl:110}    = {width_str}'h{reg_reset:0{digits}X};\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("input_rdl_file")
    parser.add_argument("output_svh_file")
    parser.add_argument("-u", "--udp_rdl_file", required=True,
                        help="the PeakRDL UDP RDL file (./regblock_udps.rdl)")
    parser.add_argument("-t", "--top", help="address map to use as the top")
    parser.add_argument("-a", "--addrmap",
                        help="address map (instance name) for which to generate output")
    parser.add_argument("-i", "--incdir", action="append",
                        help="directory to search for included files")
    parser.add_argument("-s", "--shorten_names", action="store_true",
                        help="use shorter constant names")
    parser.add_argument("--addr_width", default=32, help="width of address bus")
    parser.add_argument("--add_total_struct", action="store_true",
                        help="generate total struct for all registers")
    parser.add_argument("--structs_file", default=None,
                        help="if given, write per-register typedef struct definitions AND "
                        "per-field mask/shift localparams to this file instead of including "
                        "them in the main output file")
    args = parser.parse_args()

    rdlc = RDLCompiler()
    try:
        rdlc.compile_file(args.udp_rdl_file)
        rdlc.compile_file(args.input_rdl_file, incl_search_paths=args.incdir)
        root = rdlc.elaborate(args.top)
    except RDLCompileError:
        sys.exit(1)

    listener = SvhListener(root, args)
    RDLWalker(unroll=True).walk(root, listener)
    listener.process_fields()
    listener.process_defaults()

    with open(args.output_svh_file, "w") as f:
        f.write(listener.header_text)
        f.write(listener.addr_text)
        f.write(listener.default_text)
        if args.structs_file is None:
            f.write(listener.bitfield_text)
            f.write(listener.struct_text)
        f.write(listener.footer_text)

    if args.structs_file is not None:
        structs_def = os.path.splitext(os.path.basename(args.structs_file))[0].upper()
        with open(args.structs_file, "w") as sf:
            sf.write(f"""\
/*******************************************************************************
 * Per-field mask/shift localparams and per-register typedef struct definitions
 *
 * This file was auto-generated by this script:
 *       {os.path.basename(sys.argv[0])}   ({SCRIPT_VERSION})
 * ... from this input file:
 *       {os.path.basename(args.input_rdl_file)}
 *
 * This file should not be modified by hand.
 *
 ******************************************************************************/

`ifndef {structs_def}_SVH
`define {structs_def}_SVH
""")
            sf.write(listener.bitfield_text)
            sf.write(listener.struct_text)
            sf.write("\n`endif\n")


if __name__ == "__main__":
    main()
