# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2026 Tenstorrent USA, Inc.
################################################################################
# dtp_cdc_max_delay_generated.tcl - GENERATED, do not hand-edit
#
# One call per CDC element in the DTP design, enumerated offline against the
# elaborated netlist. The procs it calls come from
# flows/synth/constraints/cdc_max_delay_procs.tcl; constraints.sdc sources both.
#
# Paths and clock names are OCAH's. To apply this file to a design that
# instantiates the block elsewhere, or drives it from differently named clocks,
# set ::cdc_hier_prefix / ::cdc_clock_alias rather than editing here.
#
# Regeneration runs in the closed synthesis flow, not here, and is needed only
# when the block is reconfigured such that the set of CDC elements changes. The
# file goes stale silently in that case - nothing warns about an element that
# was never listed. Hand-written overrides belong in dtp_cdc_max_delay.tcl,
# which sources this file.
################################################################################

# Hierarchical instance paths below run past 100 characters and cannot be wrapped:
# a Tcl word does not survive a line break. Brace-quoted words keep a trailing
# backslash-newline literal, and inside quotes it collapses to a space, either way
# corrupting the path. Only the length rule is disabled; the rest still apply.
# tclint-disable line-length

# ---- prim_sync2r (40 instances) ----
set_cdc_max_delay_prim_sync2 u_jtag_intf_unit/u_jtag_ptap/gen_smc_jtag2axi.u_smc_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_ar/i_cdc_reset_ctrlr/i_cdc_reset_ctrlr_half_a/i_state_transition_cdc_dst/i_sync/gen_tt_sync2_async_clr.u_prim_sync2r JTAG_TCK
set_cdc_max_delay_prim_sync2 u_jtag_intf_unit/u_jtag_ptap/gen_smc_jtag2axi.u_smc_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_ar/i_cdc_reset_ctrlr/i_cdc_reset_ctrlr_half_a/i_state_transition_cdc_src/i_sync/gen_tt_sync2_async_clr.u_prim_sync2r JTAG_TCK
set_cdc_max_delay_prim_sync2 u_jtag_intf_unit/u_jtag_ptap/gen_smc_jtag2axi.u_smc_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_ar/i_cdc_reset_ctrlr/i_cdc_reset_ctrlr_half_b/i_state_transition_cdc_dst/i_sync/gen_tt_sync2_async_clr.u_prim_sync2r DTPCLK
set_cdc_max_delay_prim_sync2 u_jtag_intf_unit/u_jtag_ptap/gen_smc_jtag2axi.u_smc_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_ar/i_cdc_reset_ctrlr/i_cdc_reset_ctrlr_half_b/i_state_transition_cdc_src/i_sync/gen_tt_sync2_async_clr.u_prim_sync2r DTPCLK
set_cdc_max_delay_prim_sync2 u_jtag_intf_unit/u_jtag_ptap/gen_smc_jtag2axi.u_smc_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_aw/i_cdc_reset_ctrlr/i_cdc_reset_ctrlr_half_a/i_state_transition_cdc_dst/i_sync/gen_tt_sync2_async_clr.u_prim_sync2r JTAG_TCK
set_cdc_max_delay_prim_sync2 u_jtag_intf_unit/u_jtag_ptap/gen_smc_jtag2axi.u_smc_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_aw/i_cdc_reset_ctrlr/i_cdc_reset_ctrlr_half_a/i_state_transition_cdc_src/i_sync/gen_tt_sync2_async_clr.u_prim_sync2r JTAG_TCK
set_cdc_max_delay_prim_sync2 u_jtag_intf_unit/u_jtag_ptap/gen_smc_jtag2axi.u_smc_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_aw/i_cdc_reset_ctrlr/i_cdc_reset_ctrlr_half_b/i_state_transition_cdc_dst/i_sync/gen_tt_sync2_async_clr.u_prim_sync2r DTPCLK
set_cdc_max_delay_prim_sync2 u_jtag_intf_unit/u_jtag_ptap/gen_smc_jtag2axi.u_smc_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_aw/i_cdc_reset_ctrlr/i_cdc_reset_ctrlr_half_b/i_state_transition_cdc_src/i_sync/gen_tt_sync2_async_clr.u_prim_sync2r DTPCLK
set_cdc_max_delay_prim_sync2 u_jtag_intf_unit/u_jtag_ptap/gen_smc_jtag2axi.u_smc_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_b/i_cdc_reset_ctrlr/i_cdc_reset_ctrlr_half_a/i_state_transition_cdc_dst/i_sync/gen_tt_sync2_async_clr.u_prim_sync2r DTPCLK
set_cdc_max_delay_prim_sync2 u_jtag_intf_unit/u_jtag_ptap/gen_smc_jtag2axi.u_smc_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_b/i_cdc_reset_ctrlr/i_cdc_reset_ctrlr_half_a/i_state_transition_cdc_src/i_sync/gen_tt_sync2_async_clr.u_prim_sync2r DTPCLK
set_cdc_max_delay_prim_sync2 u_jtag_intf_unit/u_jtag_ptap/gen_smc_jtag2axi.u_smc_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_b/i_cdc_reset_ctrlr/i_cdc_reset_ctrlr_half_b/i_state_transition_cdc_dst/i_sync/gen_tt_sync2_async_clr.u_prim_sync2r JTAG_TCK
set_cdc_max_delay_prim_sync2 u_jtag_intf_unit/u_jtag_ptap/gen_smc_jtag2axi.u_smc_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_b/i_cdc_reset_ctrlr/i_cdc_reset_ctrlr_half_b/i_state_transition_cdc_src/i_sync/gen_tt_sync2_async_clr.u_prim_sync2r JTAG_TCK
set_cdc_max_delay_prim_sync2 u_jtag_intf_unit/u_jtag_ptap/gen_smc_jtag2axi.u_smc_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_r/i_cdc_reset_ctrlr/i_cdc_reset_ctrlr_half_a/i_state_transition_cdc_dst/i_sync/gen_tt_sync2_async_clr.u_prim_sync2r DTPCLK
set_cdc_max_delay_prim_sync2 u_jtag_intf_unit/u_jtag_ptap/gen_smc_jtag2axi.u_smc_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_r/i_cdc_reset_ctrlr/i_cdc_reset_ctrlr_half_a/i_state_transition_cdc_src/i_sync/gen_tt_sync2_async_clr.u_prim_sync2r DTPCLK
set_cdc_max_delay_prim_sync2 u_jtag_intf_unit/u_jtag_ptap/gen_smc_jtag2axi.u_smc_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_r/i_cdc_reset_ctrlr/i_cdc_reset_ctrlr_half_b/i_state_transition_cdc_dst/i_sync/gen_tt_sync2_async_clr.u_prim_sync2r JTAG_TCK
set_cdc_max_delay_prim_sync2 u_jtag_intf_unit/u_jtag_ptap/gen_smc_jtag2axi.u_smc_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_r/i_cdc_reset_ctrlr/i_cdc_reset_ctrlr_half_b/i_state_transition_cdc_src/i_sync/gen_tt_sync2_async_clr.u_prim_sync2r JTAG_TCK
set_cdc_max_delay_prim_sync2 u_jtag_intf_unit/u_jtag_ptap/gen_smc_jtag2axi.u_smc_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_w/i_cdc_reset_ctrlr/i_cdc_reset_ctrlr_half_a/i_state_transition_cdc_dst/i_sync/gen_tt_sync2_async_clr.u_prim_sync2r JTAG_TCK
set_cdc_max_delay_prim_sync2 u_jtag_intf_unit/u_jtag_ptap/gen_smc_jtag2axi.u_smc_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_w/i_cdc_reset_ctrlr/i_cdc_reset_ctrlr_half_a/i_state_transition_cdc_src/i_sync/gen_tt_sync2_async_clr.u_prim_sync2r JTAG_TCK
set_cdc_max_delay_prim_sync2 u_jtag_intf_unit/u_jtag_ptap/gen_smc_jtag2axi.u_smc_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_w/i_cdc_reset_ctrlr/i_cdc_reset_ctrlr_half_b/i_state_transition_cdc_dst/i_sync/gen_tt_sync2_async_clr.u_prim_sync2r DTPCLK
set_cdc_max_delay_prim_sync2 u_jtag_intf_unit/u_jtag_ptap/gen_smc_jtag2axi.u_smc_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_w/i_cdc_reset_ctrlr/i_cdc_reset_ctrlr_half_b/i_state_transition_cdc_src/i_sync/gen_tt_sync2_async_clr.u_prim_sync2r DTPCLK
set_cdc_max_delay_prim_sync2 u_jtag_intf_unit/u_jtag_ptap/gen_smc_otp_jtag2axi.u_smc_otp_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_ar/i_cdc_reset_ctrlr/i_cdc_reset_ctrlr_half_a/i_state_transition_cdc_dst/i_sync/gen_tt_sync2_async_clr.u_prim_sync2r JTAG_TCK
set_cdc_max_delay_prim_sync2 u_jtag_intf_unit/u_jtag_ptap/gen_smc_otp_jtag2axi.u_smc_otp_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_ar/i_cdc_reset_ctrlr/i_cdc_reset_ctrlr_half_a/i_state_transition_cdc_src/i_sync/gen_tt_sync2_async_clr.u_prim_sync2r JTAG_TCK
set_cdc_max_delay_prim_sync2 u_jtag_intf_unit/u_jtag_ptap/gen_smc_otp_jtag2axi.u_smc_otp_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_ar/i_cdc_reset_ctrlr/i_cdc_reset_ctrlr_half_b/i_state_transition_cdc_dst/i_sync/gen_tt_sync2_async_clr.u_prim_sync2r DTPCLK
set_cdc_max_delay_prim_sync2 u_jtag_intf_unit/u_jtag_ptap/gen_smc_otp_jtag2axi.u_smc_otp_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_ar/i_cdc_reset_ctrlr/i_cdc_reset_ctrlr_half_b/i_state_transition_cdc_src/i_sync/gen_tt_sync2_async_clr.u_prim_sync2r DTPCLK
set_cdc_max_delay_prim_sync2 u_jtag_intf_unit/u_jtag_ptap/gen_smc_otp_jtag2axi.u_smc_otp_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_aw/i_cdc_reset_ctrlr/i_cdc_reset_ctrlr_half_a/i_state_transition_cdc_dst/i_sync/gen_tt_sync2_async_clr.u_prim_sync2r JTAG_TCK
set_cdc_max_delay_prim_sync2 u_jtag_intf_unit/u_jtag_ptap/gen_smc_otp_jtag2axi.u_smc_otp_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_aw/i_cdc_reset_ctrlr/i_cdc_reset_ctrlr_half_a/i_state_transition_cdc_src/i_sync/gen_tt_sync2_async_clr.u_prim_sync2r JTAG_TCK
set_cdc_max_delay_prim_sync2 u_jtag_intf_unit/u_jtag_ptap/gen_smc_otp_jtag2axi.u_smc_otp_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_aw/i_cdc_reset_ctrlr/i_cdc_reset_ctrlr_half_b/i_state_transition_cdc_dst/i_sync/gen_tt_sync2_async_clr.u_prim_sync2r DTPCLK
set_cdc_max_delay_prim_sync2 u_jtag_intf_unit/u_jtag_ptap/gen_smc_otp_jtag2axi.u_smc_otp_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_aw/i_cdc_reset_ctrlr/i_cdc_reset_ctrlr_half_b/i_state_transition_cdc_src/i_sync/gen_tt_sync2_async_clr.u_prim_sync2r DTPCLK
set_cdc_max_delay_prim_sync2 u_jtag_intf_unit/u_jtag_ptap/gen_smc_otp_jtag2axi.u_smc_otp_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_b/i_cdc_reset_ctrlr/i_cdc_reset_ctrlr_half_a/i_state_transition_cdc_dst/i_sync/gen_tt_sync2_async_clr.u_prim_sync2r DTPCLK
set_cdc_max_delay_prim_sync2 u_jtag_intf_unit/u_jtag_ptap/gen_smc_otp_jtag2axi.u_smc_otp_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_b/i_cdc_reset_ctrlr/i_cdc_reset_ctrlr_half_a/i_state_transition_cdc_src/i_sync/gen_tt_sync2_async_clr.u_prim_sync2r DTPCLK
set_cdc_max_delay_prim_sync2 u_jtag_intf_unit/u_jtag_ptap/gen_smc_otp_jtag2axi.u_smc_otp_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_b/i_cdc_reset_ctrlr/i_cdc_reset_ctrlr_half_b/i_state_transition_cdc_dst/i_sync/gen_tt_sync2_async_clr.u_prim_sync2r JTAG_TCK
set_cdc_max_delay_prim_sync2 u_jtag_intf_unit/u_jtag_ptap/gen_smc_otp_jtag2axi.u_smc_otp_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_b/i_cdc_reset_ctrlr/i_cdc_reset_ctrlr_half_b/i_state_transition_cdc_src/i_sync/gen_tt_sync2_async_clr.u_prim_sync2r JTAG_TCK
set_cdc_max_delay_prim_sync2 u_jtag_intf_unit/u_jtag_ptap/gen_smc_otp_jtag2axi.u_smc_otp_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_r/i_cdc_reset_ctrlr/i_cdc_reset_ctrlr_half_a/i_state_transition_cdc_dst/i_sync/gen_tt_sync2_async_clr.u_prim_sync2r DTPCLK
set_cdc_max_delay_prim_sync2 u_jtag_intf_unit/u_jtag_ptap/gen_smc_otp_jtag2axi.u_smc_otp_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_r/i_cdc_reset_ctrlr/i_cdc_reset_ctrlr_half_a/i_state_transition_cdc_src/i_sync/gen_tt_sync2_async_clr.u_prim_sync2r DTPCLK
set_cdc_max_delay_prim_sync2 u_jtag_intf_unit/u_jtag_ptap/gen_smc_otp_jtag2axi.u_smc_otp_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_r/i_cdc_reset_ctrlr/i_cdc_reset_ctrlr_half_b/i_state_transition_cdc_dst/i_sync/gen_tt_sync2_async_clr.u_prim_sync2r JTAG_TCK
set_cdc_max_delay_prim_sync2 u_jtag_intf_unit/u_jtag_ptap/gen_smc_otp_jtag2axi.u_smc_otp_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_r/i_cdc_reset_ctrlr/i_cdc_reset_ctrlr_half_b/i_state_transition_cdc_src/i_sync/gen_tt_sync2_async_clr.u_prim_sync2r JTAG_TCK
set_cdc_max_delay_prim_sync2 u_jtag_intf_unit/u_jtag_ptap/gen_smc_otp_jtag2axi.u_smc_otp_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_w/i_cdc_reset_ctrlr/i_cdc_reset_ctrlr_half_a/i_state_transition_cdc_dst/i_sync/gen_tt_sync2_async_clr.u_prim_sync2r JTAG_TCK
set_cdc_max_delay_prim_sync2 u_jtag_intf_unit/u_jtag_ptap/gen_smc_otp_jtag2axi.u_smc_otp_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_w/i_cdc_reset_ctrlr/i_cdc_reset_ctrlr_half_a/i_state_transition_cdc_src/i_sync/gen_tt_sync2_async_clr.u_prim_sync2r JTAG_TCK
set_cdc_max_delay_prim_sync2 u_jtag_intf_unit/u_jtag_ptap/gen_smc_otp_jtag2axi.u_smc_otp_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_w/i_cdc_reset_ctrlr/i_cdc_reset_ctrlr_half_b/i_state_transition_cdc_dst/i_sync/gen_tt_sync2_async_clr.u_prim_sync2r DTPCLK
set_cdc_max_delay_prim_sync2 u_jtag_intf_unit/u_jtag_ptap/gen_smc_otp_jtag2axi.u_smc_otp_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_w/i_cdc_reset_ctrlr/i_cdc_reset_ctrlr_half_b/i_state_transition_cdc_src/i_sync/gen_tt_sync2_async_clr.u_prim_sync2r DTPCLK

# ---- prim_sync3r (80 instances) ----
set_cdc_max_delay_prim_sync3 {u_jtag_intf_unit/u_jtag_ptap/gen_smc_jtag2axi.u_smc_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_ar/i_dst/gen_sync[0].i_sync/gen_tt_sync3_async_clr.u_prim_sync3r} DTPCLK
set_cdc_max_delay_prim_sync3 {u_jtag_intf_unit/u_jtag_ptap/gen_smc_jtag2axi.u_smc_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_ar/i_dst/gen_sync[1].i_sync/gen_tt_sync3_async_clr.u_prim_sync3r} DTPCLK
set_cdc_max_delay_prim_sync3 {u_jtag_intf_unit/u_jtag_ptap/gen_smc_jtag2axi.u_smc_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_ar/i_dst/gen_sync[2].i_sync/gen_tt_sync3_async_clr.u_prim_sync3r} DTPCLK
set_cdc_max_delay_prim_sync3 {u_jtag_intf_unit/u_jtag_ptap/gen_smc_jtag2axi.u_smc_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_ar/i_dst/gen_sync[3].i_sync/gen_tt_sync3_async_clr.u_prim_sync3r} DTPCLK
set_cdc_max_delay_prim_sync3 {u_jtag_intf_unit/u_jtag_ptap/gen_smc_jtag2axi.u_smc_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_ar/i_src/gen_sync[0].i_sync/gen_tt_sync3_async_clr.u_prim_sync3r} JTAG_TCK
set_cdc_max_delay_prim_sync3 {u_jtag_intf_unit/u_jtag_ptap/gen_smc_jtag2axi.u_smc_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_ar/i_src/gen_sync[1].i_sync/gen_tt_sync3_async_clr.u_prim_sync3r} JTAG_TCK
set_cdc_max_delay_prim_sync3 {u_jtag_intf_unit/u_jtag_ptap/gen_smc_jtag2axi.u_smc_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_ar/i_src/gen_sync[2].i_sync/gen_tt_sync3_async_clr.u_prim_sync3r} JTAG_TCK
set_cdc_max_delay_prim_sync3 {u_jtag_intf_unit/u_jtag_ptap/gen_smc_jtag2axi.u_smc_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_ar/i_src/gen_sync[3].i_sync/gen_tt_sync3_async_clr.u_prim_sync3r} JTAG_TCK
set_cdc_max_delay_prim_sync3 {u_jtag_intf_unit/u_jtag_ptap/gen_smc_jtag2axi.u_smc_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_aw/i_dst/gen_sync[0].i_sync/gen_tt_sync3_async_clr.u_prim_sync3r} DTPCLK
set_cdc_max_delay_prim_sync3 {u_jtag_intf_unit/u_jtag_ptap/gen_smc_jtag2axi.u_smc_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_aw/i_dst/gen_sync[1].i_sync/gen_tt_sync3_async_clr.u_prim_sync3r} DTPCLK
set_cdc_max_delay_prim_sync3 {u_jtag_intf_unit/u_jtag_ptap/gen_smc_jtag2axi.u_smc_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_aw/i_dst/gen_sync[2].i_sync/gen_tt_sync3_async_clr.u_prim_sync3r} DTPCLK
set_cdc_max_delay_prim_sync3 {u_jtag_intf_unit/u_jtag_ptap/gen_smc_jtag2axi.u_smc_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_aw/i_dst/gen_sync[3].i_sync/gen_tt_sync3_async_clr.u_prim_sync3r} DTPCLK
set_cdc_max_delay_prim_sync3 {u_jtag_intf_unit/u_jtag_ptap/gen_smc_jtag2axi.u_smc_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_aw/i_src/gen_sync[0].i_sync/gen_tt_sync3_async_clr.u_prim_sync3r} JTAG_TCK
set_cdc_max_delay_prim_sync3 {u_jtag_intf_unit/u_jtag_ptap/gen_smc_jtag2axi.u_smc_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_aw/i_src/gen_sync[1].i_sync/gen_tt_sync3_async_clr.u_prim_sync3r} JTAG_TCK
set_cdc_max_delay_prim_sync3 {u_jtag_intf_unit/u_jtag_ptap/gen_smc_jtag2axi.u_smc_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_aw/i_src/gen_sync[2].i_sync/gen_tt_sync3_async_clr.u_prim_sync3r} JTAG_TCK
set_cdc_max_delay_prim_sync3 {u_jtag_intf_unit/u_jtag_ptap/gen_smc_jtag2axi.u_smc_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_aw/i_src/gen_sync[3].i_sync/gen_tt_sync3_async_clr.u_prim_sync3r} JTAG_TCK
set_cdc_max_delay_prim_sync3 {u_jtag_intf_unit/u_jtag_ptap/gen_smc_jtag2axi.u_smc_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_b/i_dst/gen_sync[0].i_sync/gen_tt_sync3_async_clr.u_prim_sync3r} JTAG_TCK
set_cdc_max_delay_prim_sync3 {u_jtag_intf_unit/u_jtag_ptap/gen_smc_jtag2axi.u_smc_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_b/i_dst/gen_sync[1].i_sync/gen_tt_sync3_async_clr.u_prim_sync3r} JTAG_TCK
set_cdc_max_delay_prim_sync3 {u_jtag_intf_unit/u_jtag_ptap/gen_smc_jtag2axi.u_smc_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_b/i_dst/gen_sync[2].i_sync/gen_tt_sync3_async_clr.u_prim_sync3r} JTAG_TCK
set_cdc_max_delay_prim_sync3 {u_jtag_intf_unit/u_jtag_ptap/gen_smc_jtag2axi.u_smc_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_b/i_dst/gen_sync[3].i_sync/gen_tt_sync3_async_clr.u_prim_sync3r} JTAG_TCK
set_cdc_max_delay_prim_sync3 {u_jtag_intf_unit/u_jtag_ptap/gen_smc_jtag2axi.u_smc_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_b/i_src/gen_sync[0].i_sync/gen_tt_sync3_async_clr.u_prim_sync3r} DTPCLK
set_cdc_max_delay_prim_sync3 {u_jtag_intf_unit/u_jtag_ptap/gen_smc_jtag2axi.u_smc_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_b/i_src/gen_sync[1].i_sync/gen_tt_sync3_async_clr.u_prim_sync3r} DTPCLK
set_cdc_max_delay_prim_sync3 {u_jtag_intf_unit/u_jtag_ptap/gen_smc_jtag2axi.u_smc_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_b/i_src/gen_sync[2].i_sync/gen_tt_sync3_async_clr.u_prim_sync3r} DTPCLK
set_cdc_max_delay_prim_sync3 {u_jtag_intf_unit/u_jtag_ptap/gen_smc_jtag2axi.u_smc_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_b/i_src/gen_sync[3].i_sync/gen_tt_sync3_async_clr.u_prim_sync3r} DTPCLK
set_cdc_max_delay_prim_sync3 {u_jtag_intf_unit/u_jtag_ptap/gen_smc_jtag2axi.u_smc_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_r/i_dst/gen_sync[0].i_sync/gen_tt_sync3_async_clr.u_prim_sync3r} JTAG_TCK
set_cdc_max_delay_prim_sync3 {u_jtag_intf_unit/u_jtag_ptap/gen_smc_jtag2axi.u_smc_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_r/i_dst/gen_sync[1].i_sync/gen_tt_sync3_async_clr.u_prim_sync3r} JTAG_TCK
set_cdc_max_delay_prim_sync3 {u_jtag_intf_unit/u_jtag_ptap/gen_smc_jtag2axi.u_smc_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_r/i_dst/gen_sync[2].i_sync/gen_tt_sync3_async_clr.u_prim_sync3r} JTAG_TCK
set_cdc_max_delay_prim_sync3 {u_jtag_intf_unit/u_jtag_ptap/gen_smc_jtag2axi.u_smc_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_r/i_dst/gen_sync[3].i_sync/gen_tt_sync3_async_clr.u_prim_sync3r} JTAG_TCK
set_cdc_max_delay_prim_sync3 {u_jtag_intf_unit/u_jtag_ptap/gen_smc_jtag2axi.u_smc_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_r/i_src/gen_sync[0].i_sync/gen_tt_sync3_async_clr.u_prim_sync3r} DTPCLK
set_cdc_max_delay_prim_sync3 {u_jtag_intf_unit/u_jtag_ptap/gen_smc_jtag2axi.u_smc_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_r/i_src/gen_sync[1].i_sync/gen_tt_sync3_async_clr.u_prim_sync3r} DTPCLK
set_cdc_max_delay_prim_sync3 {u_jtag_intf_unit/u_jtag_ptap/gen_smc_jtag2axi.u_smc_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_r/i_src/gen_sync[2].i_sync/gen_tt_sync3_async_clr.u_prim_sync3r} DTPCLK
set_cdc_max_delay_prim_sync3 {u_jtag_intf_unit/u_jtag_ptap/gen_smc_jtag2axi.u_smc_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_r/i_src/gen_sync[3].i_sync/gen_tt_sync3_async_clr.u_prim_sync3r} DTPCLK
set_cdc_max_delay_prim_sync3 {u_jtag_intf_unit/u_jtag_ptap/gen_smc_jtag2axi.u_smc_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_w/i_dst/gen_sync[0].i_sync/gen_tt_sync3_async_clr.u_prim_sync3r} DTPCLK
set_cdc_max_delay_prim_sync3 {u_jtag_intf_unit/u_jtag_ptap/gen_smc_jtag2axi.u_smc_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_w/i_dst/gen_sync[1].i_sync/gen_tt_sync3_async_clr.u_prim_sync3r} DTPCLK
set_cdc_max_delay_prim_sync3 {u_jtag_intf_unit/u_jtag_ptap/gen_smc_jtag2axi.u_smc_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_w/i_dst/gen_sync[2].i_sync/gen_tt_sync3_async_clr.u_prim_sync3r} DTPCLK
set_cdc_max_delay_prim_sync3 {u_jtag_intf_unit/u_jtag_ptap/gen_smc_jtag2axi.u_smc_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_w/i_dst/gen_sync[3].i_sync/gen_tt_sync3_async_clr.u_prim_sync3r} DTPCLK
set_cdc_max_delay_prim_sync3 {u_jtag_intf_unit/u_jtag_ptap/gen_smc_jtag2axi.u_smc_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_w/i_src/gen_sync[0].i_sync/gen_tt_sync3_async_clr.u_prim_sync3r} JTAG_TCK
set_cdc_max_delay_prim_sync3 {u_jtag_intf_unit/u_jtag_ptap/gen_smc_jtag2axi.u_smc_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_w/i_src/gen_sync[1].i_sync/gen_tt_sync3_async_clr.u_prim_sync3r} JTAG_TCK
set_cdc_max_delay_prim_sync3 {u_jtag_intf_unit/u_jtag_ptap/gen_smc_jtag2axi.u_smc_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_w/i_src/gen_sync[2].i_sync/gen_tt_sync3_async_clr.u_prim_sync3r} JTAG_TCK
set_cdc_max_delay_prim_sync3 {u_jtag_intf_unit/u_jtag_ptap/gen_smc_jtag2axi.u_smc_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_w/i_src/gen_sync[3].i_sync/gen_tt_sync3_async_clr.u_prim_sync3r} JTAG_TCK
set_cdc_max_delay_prim_sync3 {u_jtag_intf_unit/u_jtag_ptap/gen_smc_otp_jtag2axi.u_smc_otp_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_ar/i_dst/gen_sync[0].i_sync/gen_tt_sync3_async_clr.u_prim_sync3r} DTPCLK
set_cdc_max_delay_prim_sync3 {u_jtag_intf_unit/u_jtag_ptap/gen_smc_otp_jtag2axi.u_smc_otp_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_ar/i_dst/gen_sync[1].i_sync/gen_tt_sync3_async_clr.u_prim_sync3r} DTPCLK
set_cdc_max_delay_prim_sync3 {u_jtag_intf_unit/u_jtag_ptap/gen_smc_otp_jtag2axi.u_smc_otp_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_ar/i_dst/gen_sync[2].i_sync/gen_tt_sync3_async_clr.u_prim_sync3r} DTPCLK
set_cdc_max_delay_prim_sync3 {u_jtag_intf_unit/u_jtag_ptap/gen_smc_otp_jtag2axi.u_smc_otp_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_ar/i_dst/gen_sync[3].i_sync/gen_tt_sync3_async_clr.u_prim_sync3r} DTPCLK
set_cdc_max_delay_prim_sync3 {u_jtag_intf_unit/u_jtag_ptap/gen_smc_otp_jtag2axi.u_smc_otp_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_ar/i_src/gen_sync[0].i_sync/gen_tt_sync3_async_clr.u_prim_sync3r} JTAG_TCK
set_cdc_max_delay_prim_sync3 {u_jtag_intf_unit/u_jtag_ptap/gen_smc_otp_jtag2axi.u_smc_otp_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_ar/i_src/gen_sync[1].i_sync/gen_tt_sync3_async_clr.u_prim_sync3r} JTAG_TCK
set_cdc_max_delay_prim_sync3 {u_jtag_intf_unit/u_jtag_ptap/gen_smc_otp_jtag2axi.u_smc_otp_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_ar/i_src/gen_sync[2].i_sync/gen_tt_sync3_async_clr.u_prim_sync3r} JTAG_TCK
set_cdc_max_delay_prim_sync3 {u_jtag_intf_unit/u_jtag_ptap/gen_smc_otp_jtag2axi.u_smc_otp_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_ar/i_src/gen_sync[3].i_sync/gen_tt_sync3_async_clr.u_prim_sync3r} JTAG_TCK
set_cdc_max_delay_prim_sync3 {u_jtag_intf_unit/u_jtag_ptap/gen_smc_otp_jtag2axi.u_smc_otp_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_aw/i_dst/gen_sync[0].i_sync/gen_tt_sync3_async_clr.u_prim_sync3r} DTPCLK
set_cdc_max_delay_prim_sync3 {u_jtag_intf_unit/u_jtag_ptap/gen_smc_otp_jtag2axi.u_smc_otp_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_aw/i_dst/gen_sync[1].i_sync/gen_tt_sync3_async_clr.u_prim_sync3r} DTPCLK
set_cdc_max_delay_prim_sync3 {u_jtag_intf_unit/u_jtag_ptap/gen_smc_otp_jtag2axi.u_smc_otp_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_aw/i_dst/gen_sync[2].i_sync/gen_tt_sync3_async_clr.u_prim_sync3r} DTPCLK
set_cdc_max_delay_prim_sync3 {u_jtag_intf_unit/u_jtag_ptap/gen_smc_otp_jtag2axi.u_smc_otp_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_aw/i_dst/gen_sync[3].i_sync/gen_tt_sync3_async_clr.u_prim_sync3r} DTPCLK
set_cdc_max_delay_prim_sync3 {u_jtag_intf_unit/u_jtag_ptap/gen_smc_otp_jtag2axi.u_smc_otp_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_aw/i_src/gen_sync[0].i_sync/gen_tt_sync3_async_clr.u_prim_sync3r} JTAG_TCK
set_cdc_max_delay_prim_sync3 {u_jtag_intf_unit/u_jtag_ptap/gen_smc_otp_jtag2axi.u_smc_otp_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_aw/i_src/gen_sync[1].i_sync/gen_tt_sync3_async_clr.u_prim_sync3r} JTAG_TCK
set_cdc_max_delay_prim_sync3 {u_jtag_intf_unit/u_jtag_ptap/gen_smc_otp_jtag2axi.u_smc_otp_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_aw/i_src/gen_sync[2].i_sync/gen_tt_sync3_async_clr.u_prim_sync3r} JTAG_TCK
set_cdc_max_delay_prim_sync3 {u_jtag_intf_unit/u_jtag_ptap/gen_smc_otp_jtag2axi.u_smc_otp_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_aw/i_src/gen_sync[3].i_sync/gen_tt_sync3_async_clr.u_prim_sync3r} JTAG_TCK
set_cdc_max_delay_prim_sync3 {u_jtag_intf_unit/u_jtag_ptap/gen_smc_otp_jtag2axi.u_smc_otp_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_b/i_dst/gen_sync[0].i_sync/gen_tt_sync3_async_clr.u_prim_sync3r} JTAG_TCK
set_cdc_max_delay_prim_sync3 {u_jtag_intf_unit/u_jtag_ptap/gen_smc_otp_jtag2axi.u_smc_otp_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_b/i_dst/gen_sync[1].i_sync/gen_tt_sync3_async_clr.u_prim_sync3r} JTAG_TCK
set_cdc_max_delay_prim_sync3 {u_jtag_intf_unit/u_jtag_ptap/gen_smc_otp_jtag2axi.u_smc_otp_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_b/i_dst/gen_sync[2].i_sync/gen_tt_sync3_async_clr.u_prim_sync3r} JTAG_TCK
set_cdc_max_delay_prim_sync3 {u_jtag_intf_unit/u_jtag_ptap/gen_smc_otp_jtag2axi.u_smc_otp_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_b/i_dst/gen_sync[3].i_sync/gen_tt_sync3_async_clr.u_prim_sync3r} JTAG_TCK
set_cdc_max_delay_prim_sync3 {u_jtag_intf_unit/u_jtag_ptap/gen_smc_otp_jtag2axi.u_smc_otp_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_b/i_src/gen_sync[0].i_sync/gen_tt_sync3_async_clr.u_prim_sync3r} DTPCLK
set_cdc_max_delay_prim_sync3 {u_jtag_intf_unit/u_jtag_ptap/gen_smc_otp_jtag2axi.u_smc_otp_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_b/i_src/gen_sync[1].i_sync/gen_tt_sync3_async_clr.u_prim_sync3r} DTPCLK
set_cdc_max_delay_prim_sync3 {u_jtag_intf_unit/u_jtag_ptap/gen_smc_otp_jtag2axi.u_smc_otp_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_b/i_src/gen_sync[2].i_sync/gen_tt_sync3_async_clr.u_prim_sync3r} DTPCLK
set_cdc_max_delay_prim_sync3 {u_jtag_intf_unit/u_jtag_ptap/gen_smc_otp_jtag2axi.u_smc_otp_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_b/i_src/gen_sync[3].i_sync/gen_tt_sync3_async_clr.u_prim_sync3r} DTPCLK
set_cdc_max_delay_prim_sync3 {u_jtag_intf_unit/u_jtag_ptap/gen_smc_otp_jtag2axi.u_smc_otp_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_r/i_dst/gen_sync[0].i_sync/gen_tt_sync3_async_clr.u_prim_sync3r} JTAG_TCK
set_cdc_max_delay_prim_sync3 {u_jtag_intf_unit/u_jtag_ptap/gen_smc_otp_jtag2axi.u_smc_otp_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_r/i_dst/gen_sync[1].i_sync/gen_tt_sync3_async_clr.u_prim_sync3r} JTAG_TCK
set_cdc_max_delay_prim_sync3 {u_jtag_intf_unit/u_jtag_ptap/gen_smc_otp_jtag2axi.u_smc_otp_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_r/i_dst/gen_sync[2].i_sync/gen_tt_sync3_async_clr.u_prim_sync3r} JTAG_TCK
set_cdc_max_delay_prim_sync3 {u_jtag_intf_unit/u_jtag_ptap/gen_smc_otp_jtag2axi.u_smc_otp_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_r/i_dst/gen_sync[3].i_sync/gen_tt_sync3_async_clr.u_prim_sync3r} JTAG_TCK
set_cdc_max_delay_prim_sync3 {u_jtag_intf_unit/u_jtag_ptap/gen_smc_otp_jtag2axi.u_smc_otp_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_r/i_src/gen_sync[0].i_sync/gen_tt_sync3_async_clr.u_prim_sync3r} DTPCLK
set_cdc_max_delay_prim_sync3 {u_jtag_intf_unit/u_jtag_ptap/gen_smc_otp_jtag2axi.u_smc_otp_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_r/i_src/gen_sync[1].i_sync/gen_tt_sync3_async_clr.u_prim_sync3r} DTPCLK
set_cdc_max_delay_prim_sync3 {u_jtag_intf_unit/u_jtag_ptap/gen_smc_otp_jtag2axi.u_smc_otp_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_r/i_src/gen_sync[2].i_sync/gen_tt_sync3_async_clr.u_prim_sync3r} DTPCLK
set_cdc_max_delay_prim_sync3 {u_jtag_intf_unit/u_jtag_ptap/gen_smc_otp_jtag2axi.u_smc_otp_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_r/i_src/gen_sync[3].i_sync/gen_tt_sync3_async_clr.u_prim_sync3r} DTPCLK
set_cdc_max_delay_prim_sync3 {u_jtag_intf_unit/u_jtag_ptap/gen_smc_otp_jtag2axi.u_smc_otp_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_w/i_dst/gen_sync[0].i_sync/gen_tt_sync3_async_clr.u_prim_sync3r} DTPCLK
set_cdc_max_delay_prim_sync3 {u_jtag_intf_unit/u_jtag_ptap/gen_smc_otp_jtag2axi.u_smc_otp_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_w/i_dst/gen_sync[1].i_sync/gen_tt_sync3_async_clr.u_prim_sync3r} DTPCLK
set_cdc_max_delay_prim_sync3 {u_jtag_intf_unit/u_jtag_ptap/gen_smc_otp_jtag2axi.u_smc_otp_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_w/i_dst/gen_sync[2].i_sync/gen_tt_sync3_async_clr.u_prim_sync3r} DTPCLK
set_cdc_max_delay_prim_sync3 {u_jtag_intf_unit/u_jtag_ptap/gen_smc_otp_jtag2axi.u_smc_otp_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_w/i_dst/gen_sync[3].i_sync/gen_tt_sync3_async_clr.u_prim_sync3r} DTPCLK
set_cdc_max_delay_prim_sync3 {u_jtag_intf_unit/u_jtag_ptap/gen_smc_otp_jtag2axi.u_smc_otp_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_w/i_src/gen_sync[0].i_sync/gen_tt_sync3_async_clr.u_prim_sync3r} JTAG_TCK
set_cdc_max_delay_prim_sync3 {u_jtag_intf_unit/u_jtag_ptap/gen_smc_otp_jtag2axi.u_smc_otp_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_w/i_src/gen_sync[1].i_sync/gen_tt_sync3_async_clr.u_prim_sync3r} JTAG_TCK
set_cdc_max_delay_prim_sync3 {u_jtag_intf_unit/u_jtag_ptap/gen_smc_otp_jtag2axi.u_smc_otp_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_w/i_src/gen_sync[2].i_sync/gen_tt_sync3_async_clr.u_prim_sync3r} JTAG_TCK
set_cdc_max_delay_prim_sync3 {u_jtag_intf_unit/u_jtag_ptap/gen_smc_otp_jtag2axi.u_smc_otp_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_w/i_src/gen_sync[3].i_sync/gen_tt_sync3_async_clr.u_prim_sync3r} JTAG_TCK

# ---- sync (120 instances) ----
set_cdc_max_delay_sync u_jtag_intf_unit/u_jtag_ptap/gen_smc_jtag2axi.u_smc_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_ar/i_cdc_reset_ctrlr/i_cdc_reset_ctrlr_half_a/i_state_transition_cdc_dst/i_sync JTAG_TCK
set_cdc_max_delay_sync u_jtag_intf_unit/u_jtag_ptap/gen_smc_jtag2axi.u_smc_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_ar/i_cdc_reset_ctrlr/i_cdc_reset_ctrlr_half_a/i_state_transition_cdc_src/i_sync JTAG_TCK
set_cdc_max_delay_sync u_jtag_intf_unit/u_jtag_ptap/gen_smc_jtag2axi.u_smc_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_ar/i_cdc_reset_ctrlr/i_cdc_reset_ctrlr_half_b/i_state_transition_cdc_dst/i_sync DTPCLK
set_cdc_max_delay_sync u_jtag_intf_unit/u_jtag_ptap/gen_smc_jtag2axi.u_smc_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_ar/i_cdc_reset_ctrlr/i_cdc_reset_ctrlr_half_b/i_state_transition_cdc_src/i_sync DTPCLK
set_cdc_max_delay_sync {u_jtag_intf_unit/u_jtag_ptap/gen_smc_jtag2axi.u_smc_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_ar/i_dst/gen_sync[0].i_sync} DTPCLK
set_cdc_max_delay_sync {u_jtag_intf_unit/u_jtag_ptap/gen_smc_jtag2axi.u_smc_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_ar/i_dst/gen_sync[1].i_sync} DTPCLK
set_cdc_max_delay_sync {u_jtag_intf_unit/u_jtag_ptap/gen_smc_jtag2axi.u_smc_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_ar/i_dst/gen_sync[2].i_sync} DTPCLK
set_cdc_max_delay_sync {u_jtag_intf_unit/u_jtag_ptap/gen_smc_jtag2axi.u_smc_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_ar/i_dst/gen_sync[3].i_sync} DTPCLK
set_cdc_max_delay_sync {u_jtag_intf_unit/u_jtag_ptap/gen_smc_jtag2axi.u_smc_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_ar/i_src/gen_sync[0].i_sync} JTAG_TCK
set_cdc_max_delay_sync {u_jtag_intf_unit/u_jtag_ptap/gen_smc_jtag2axi.u_smc_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_ar/i_src/gen_sync[1].i_sync} JTAG_TCK
set_cdc_max_delay_sync {u_jtag_intf_unit/u_jtag_ptap/gen_smc_jtag2axi.u_smc_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_ar/i_src/gen_sync[2].i_sync} JTAG_TCK
set_cdc_max_delay_sync {u_jtag_intf_unit/u_jtag_ptap/gen_smc_jtag2axi.u_smc_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_ar/i_src/gen_sync[3].i_sync} JTAG_TCK
set_cdc_max_delay_sync u_jtag_intf_unit/u_jtag_ptap/gen_smc_jtag2axi.u_smc_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_aw/i_cdc_reset_ctrlr/i_cdc_reset_ctrlr_half_a/i_state_transition_cdc_dst/i_sync JTAG_TCK
set_cdc_max_delay_sync u_jtag_intf_unit/u_jtag_ptap/gen_smc_jtag2axi.u_smc_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_aw/i_cdc_reset_ctrlr/i_cdc_reset_ctrlr_half_a/i_state_transition_cdc_src/i_sync JTAG_TCK
set_cdc_max_delay_sync u_jtag_intf_unit/u_jtag_ptap/gen_smc_jtag2axi.u_smc_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_aw/i_cdc_reset_ctrlr/i_cdc_reset_ctrlr_half_b/i_state_transition_cdc_dst/i_sync DTPCLK
set_cdc_max_delay_sync u_jtag_intf_unit/u_jtag_ptap/gen_smc_jtag2axi.u_smc_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_aw/i_cdc_reset_ctrlr/i_cdc_reset_ctrlr_half_b/i_state_transition_cdc_src/i_sync DTPCLK
set_cdc_max_delay_sync {u_jtag_intf_unit/u_jtag_ptap/gen_smc_jtag2axi.u_smc_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_aw/i_dst/gen_sync[0].i_sync} DTPCLK
set_cdc_max_delay_sync {u_jtag_intf_unit/u_jtag_ptap/gen_smc_jtag2axi.u_smc_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_aw/i_dst/gen_sync[1].i_sync} DTPCLK
set_cdc_max_delay_sync {u_jtag_intf_unit/u_jtag_ptap/gen_smc_jtag2axi.u_smc_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_aw/i_dst/gen_sync[2].i_sync} DTPCLK
set_cdc_max_delay_sync {u_jtag_intf_unit/u_jtag_ptap/gen_smc_jtag2axi.u_smc_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_aw/i_dst/gen_sync[3].i_sync} DTPCLK
set_cdc_max_delay_sync {u_jtag_intf_unit/u_jtag_ptap/gen_smc_jtag2axi.u_smc_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_aw/i_src/gen_sync[0].i_sync} JTAG_TCK
set_cdc_max_delay_sync {u_jtag_intf_unit/u_jtag_ptap/gen_smc_jtag2axi.u_smc_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_aw/i_src/gen_sync[1].i_sync} JTAG_TCK
set_cdc_max_delay_sync {u_jtag_intf_unit/u_jtag_ptap/gen_smc_jtag2axi.u_smc_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_aw/i_src/gen_sync[2].i_sync} JTAG_TCK
set_cdc_max_delay_sync {u_jtag_intf_unit/u_jtag_ptap/gen_smc_jtag2axi.u_smc_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_aw/i_src/gen_sync[3].i_sync} JTAG_TCK
set_cdc_max_delay_sync u_jtag_intf_unit/u_jtag_ptap/gen_smc_jtag2axi.u_smc_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_b/i_cdc_reset_ctrlr/i_cdc_reset_ctrlr_half_a/i_state_transition_cdc_dst/i_sync DTPCLK
set_cdc_max_delay_sync u_jtag_intf_unit/u_jtag_ptap/gen_smc_jtag2axi.u_smc_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_b/i_cdc_reset_ctrlr/i_cdc_reset_ctrlr_half_a/i_state_transition_cdc_src/i_sync DTPCLK
set_cdc_max_delay_sync u_jtag_intf_unit/u_jtag_ptap/gen_smc_jtag2axi.u_smc_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_b/i_cdc_reset_ctrlr/i_cdc_reset_ctrlr_half_b/i_state_transition_cdc_dst/i_sync JTAG_TCK
set_cdc_max_delay_sync u_jtag_intf_unit/u_jtag_ptap/gen_smc_jtag2axi.u_smc_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_b/i_cdc_reset_ctrlr/i_cdc_reset_ctrlr_half_b/i_state_transition_cdc_src/i_sync JTAG_TCK
set_cdc_max_delay_sync {u_jtag_intf_unit/u_jtag_ptap/gen_smc_jtag2axi.u_smc_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_b/i_dst/gen_sync[0].i_sync} JTAG_TCK
set_cdc_max_delay_sync {u_jtag_intf_unit/u_jtag_ptap/gen_smc_jtag2axi.u_smc_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_b/i_dst/gen_sync[1].i_sync} JTAG_TCK
set_cdc_max_delay_sync {u_jtag_intf_unit/u_jtag_ptap/gen_smc_jtag2axi.u_smc_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_b/i_dst/gen_sync[2].i_sync} JTAG_TCK
set_cdc_max_delay_sync {u_jtag_intf_unit/u_jtag_ptap/gen_smc_jtag2axi.u_smc_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_b/i_dst/gen_sync[3].i_sync} JTAG_TCK
set_cdc_max_delay_sync {u_jtag_intf_unit/u_jtag_ptap/gen_smc_jtag2axi.u_smc_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_b/i_src/gen_sync[0].i_sync} DTPCLK
set_cdc_max_delay_sync {u_jtag_intf_unit/u_jtag_ptap/gen_smc_jtag2axi.u_smc_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_b/i_src/gen_sync[1].i_sync} DTPCLK
set_cdc_max_delay_sync {u_jtag_intf_unit/u_jtag_ptap/gen_smc_jtag2axi.u_smc_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_b/i_src/gen_sync[2].i_sync} DTPCLK
set_cdc_max_delay_sync {u_jtag_intf_unit/u_jtag_ptap/gen_smc_jtag2axi.u_smc_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_b/i_src/gen_sync[3].i_sync} DTPCLK
set_cdc_max_delay_sync u_jtag_intf_unit/u_jtag_ptap/gen_smc_jtag2axi.u_smc_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_r/i_cdc_reset_ctrlr/i_cdc_reset_ctrlr_half_a/i_state_transition_cdc_dst/i_sync DTPCLK
set_cdc_max_delay_sync u_jtag_intf_unit/u_jtag_ptap/gen_smc_jtag2axi.u_smc_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_r/i_cdc_reset_ctrlr/i_cdc_reset_ctrlr_half_a/i_state_transition_cdc_src/i_sync DTPCLK
set_cdc_max_delay_sync u_jtag_intf_unit/u_jtag_ptap/gen_smc_jtag2axi.u_smc_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_r/i_cdc_reset_ctrlr/i_cdc_reset_ctrlr_half_b/i_state_transition_cdc_dst/i_sync JTAG_TCK
set_cdc_max_delay_sync u_jtag_intf_unit/u_jtag_ptap/gen_smc_jtag2axi.u_smc_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_r/i_cdc_reset_ctrlr/i_cdc_reset_ctrlr_half_b/i_state_transition_cdc_src/i_sync JTAG_TCK
set_cdc_max_delay_sync {u_jtag_intf_unit/u_jtag_ptap/gen_smc_jtag2axi.u_smc_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_r/i_dst/gen_sync[0].i_sync} JTAG_TCK
set_cdc_max_delay_sync {u_jtag_intf_unit/u_jtag_ptap/gen_smc_jtag2axi.u_smc_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_r/i_dst/gen_sync[1].i_sync} JTAG_TCK
set_cdc_max_delay_sync {u_jtag_intf_unit/u_jtag_ptap/gen_smc_jtag2axi.u_smc_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_r/i_dst/gen_sync[2].i_sync} JTAG_TCK
set_cdc_max_delay_sync {u_jtag_intf_unit/u_jtag_ptap/gen_smc_jtag2axi.u_smc_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_r/i_dst/gen_sync[3].i_sync} JTAG_TCK
set_cdc_max_delay_sync {u_jtag_intf_unit/u_jtag_ptap/gen_smc_jtag2axi.u_smc_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_r/i_src/gen_sync[0].i_sync} DTPCLK
set_cdc_max_delay_sync {u_jtag_intf_unit/u_jtag_ptap/gen_smc_jtag2axi.u_smc_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_r/i_src/gen_sync[1].i_sync} DTPCLK
set_cdc_max_delay_sync {u_jtag_intf_unit/u_jtag_ptap/gen_smc_jtag2axi.u_smc_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_r/i_src/gen_sync[2].i_sync} DTPCLK
set_cdc_max_delay_sync {u_jtag_intf_unit/u_jtag_ptap/gen_smc_jtag2axi.u_smc_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_r/i_src/gen_sync[3].i_sync} DTPCLK
set_cdc_max_delay_sync u_jtag_intf_unit/u_jtag_ptap/gen_smc_jtag2axi.u_smc_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_w/i_cdc_reset_ctrlr/i_cdc_reset_ctrlr_half_a/i_state_transition_cdc_dst/i_sync JTAG_TCK
set_cdc_max_delay_sync u_jtag_intf_unit/u_jtag_ptap/gen_smc_jtag2axi.u_smc_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_w/i_cdc_reset_ctrlr/i_cdc_reset_ctrlr_half_a/i_state_transition_cdc_src/i_sync JTAG_TCK
set_cdc_max_delay_sync u_jtag_intf_unit/u_jtag_ptap/gen_smc_jtag2axi.u_smc_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_w/i_cdc_reset_ctrlr/i_cdc_reset_ctrlr_half_b/i_state_transition_cdc_dst/i_sync DTPCLK
set_cdc_max_delay_sync u_jtag_intf_unit/u_jtag_ptap/gen_smc_jtag2axi.u_smc_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_w/i_cdc_reset_ctrlr/i_cdc_reset_ctrlr_half_b/i_state_transition_cdc_src/i_sync DTPCLK
set_cdc_max_delay_sync {u_jtag_intf_unit/u_jtag_ptap/gen_smc_jtag2axi.u_smc_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_w/i_dst/gen_sync[0].i_sync} DTPCLK
set_cdc_max_delay_sync {u_jtag_intf_unit/u_jtag_ptap/gen_smc_jtag2axi.u_smc_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_w/i_dst/gen_sync[1].i_sync} DTPCLK
set_cdc_max_delay_sync {u_jtag_intf_unit/u_jtag_ptap/gen_smc_jtag2axi.u_smc_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_w/i_dst/gen_sync[2].i_sync} DTPCLK
set_cdc_max_delay_sync {u_jtag_intf_unit/u_jtag_ptap/gen_smc_jtag2axi.u_smc_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_w/i_dst/gen_sync[3].i_sync} DTPCLK
set_cdc_max_delay_sync {u_jtag_intf_unit/u_jtag_ptap/gen_smc_jtag2axi.u_smc_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_w/i_src/gen_sync[0].i_sync} JTAG_TCK
set_cdc_max_delay_sync {u_jtag_intf_unit/u_jtag_ptap/gen_smc_jtag2axi.u_smc_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_w/i_src/gen_sync[1].i_sync} JTAG_TCK
set_cdc_max_delay_sync {u_jtag_intf_unit/u_jtag_ptap/gen_smc_jtag2axi.u_smc_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_w/i_src/gen_sync[2].i_sync} JTAG_TCK
set_cdc_max_delay_sync {u_jtag_intf_unit/u_jtag_ptap/gen_smc_jtag2axi.u_smc_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_w/i_src/gen_sync[3].i_sync} JTAG_TCK
set_cdc_max_delay_sync u_jtag_intf_unit/u_jtag_ptap/gen_smc_otp_jtag2axi.u_smc_otp_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_ar/i_cdc_reset_ctrlr/i_cdc_reset_ctrlr_half_a/i_state_transition_cdc_dst/i_sync JTAG_TCK
set_cdc_max_delay_sync u_jtag_intf_unit/u_jtag_ptap/gen_smc_otp_jtag2axi.u_smc_otp_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_ar/i_cdc_reset_ctrlr/i_cdc_reset_ctrlr_half_a/i_state_transition_cdc_src/i_sync JTAG_TCK
set_cdc_max_delay_sync u_jtag_intf_unit/u_jtag_ptap/gen_smc_otp_jtag2axi.u_smc_otp_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_ar/i_cdc_reset_ctrlr/i_cdc_reset_ctrlr_half_b/i_state_transition_cdc_dst/i_sync DTPCLK
set_cdc_max_delay_sync u_jtag_intf_unit/u_jtag_ptap/gen_smc_otp_jtag2axi.u_smc_otp_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_ar/i_cdc_reset_ctrlr/i_cdc_reset_ctrlr_half_b/i_state_transition_cdc_src/i_sync DTPCLK
set_cdc_max_delay_sync {u_jtag_intf_unit/u_jtag_ptap/gen_smc_otp_jtag2axi.u_smc_otp_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_ar/i_dst/gen_sync[0].i_sync} DTPCLK
set_cdc_max_delay_sync {u_jtag_intf_unit/u_jtag_ptap/gen_smc_otp_jtag2axi.u_smc_otp_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_ar/i_dst/gen_sync[1].i_sync} DTPCLK
set_cdc_max_delay_sync {u_jtag_intf_unit/u_jtag_ptap/gen_smc_otp_jtag2axi.u_smc_otp_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_ar/i_dst/gen_sync[2].i_sync} DTPCLK
set_cdc_max_delay_sync {u_jtag_intf_unit/u_jtag_ptap/gen_smc_otp_jtag2axi.u_smc_otp_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_ar/i_dst/gen_sync[3].i_sync} DTPCLK
set_cdc_max_delay_sync {u_jtag_intf_unit/u_jtag_ptap/gen_smc_otp_jtag2axi.u_smc_otp_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_ar/i_src/gen_sync[0].i_sync} JTAG_TCK
set_cdc_max_delay_sync {u_jtag_intf_unit/u_jtag_ptap/gen_smc_otp_jtag2axi.u_smc_otp_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_ar/i_src/gen_sync[1].i_sync} JTAG_TCK
set_cdc_max_delay_sync {u_jtag_intf_unit/u_jtag_ptap/gen_smc_otp_jtag2axi.u_smc_otp_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_ar/i_src/gen_sync[2].i_sync} JTAG_TCK
set_cdc_max_delay_sync {u_jtag_intf_unit/u_jtag_ptap/gen_smc_otp_jtag2axi.u_smc_otp_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_ar/i_src/gen_sync[3].i_sync} JTAG_TCK
set_cdc_max_delay_sync u_jtag_intf_unit/u_jtag_ptap/gen_smc_otp_jtag2axi.u_smc_otp_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_aw/i_cdc_reset_ctrlr/i_cdc_reset_ctrlr_half_a/i_state_transition_cdc_dst/i_sync JTAG_TCK
set_cdc_max_delay_sync u_jtag_intf_unit/u_jtag_ptap/gen_smc_otp_jtag2axi.u_smc_otp_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_aw/i_cdc_reset_ctrlr/i_cdc_reset_ctrlr_half_a/i_state_transition_cdc_src/i_sync JTAG_TCK
set_cdc_max_delay_sync u_jtag_intf_unit/u_jtag_ptap/gen_smc_otp_jtag2axi.u_smc_otp_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_aw/i_cdc_reset_ctrlr/i_cdc_reset_ctrlr_half_b/i_state_transition_cdc_dst/i_sync DTPCLK
set_cdc_max_delay_sync u_jtag_intf_unit/u_jtag_ptap/gen_smc_otp_jtag2axi.u_smc_otp_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_aw/i_cdc_reset_ctrlr/i_cdc_reset_ctrlr_half_b/i_state_transition_cdc_src/i_sync DTPCLK
set_cdc_max_delay_sync {u_jtag_intf_unit/u_jtag_ptap/gen_smc_otp_jtag2axi.u_smc_otp_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_aw/i_dst/gen_sync[0].i_sync} DTPCLK
set_cdc_max_delay_sync {u_jtag_intf_unit/u_jtag_ptap/gen_smc_otp_jtag2axi.u_smc_otp_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_aw/i_dst/gen_sync[1].i_sync} DTPCLK
set_cdc_max_delay_sync {u_jtag_intf_unit/u_jtag_ptap/gen_smc_otp_jtag2axi.u_smc_otp_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_aw/i_dst/gen_sync[2].i_sync} DTPCLK
set_cdc_max_delay_sync {u_jtag_intf_unit/u_jtag_ptap/gen_smc_otp_jtag2axi.u_smc_otp_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_aw/i_dst/gen_sync[3].i_sync} DTPCLK
set_cdc_max_delay_sync {u_jtag_intf_unit/u_jtag_ptap/gen_smc_otp_jtag2axi.u_smc_otp_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_aw/i_src/gen_sync[0].i_sync} JTAG_TCK
set_cdc_max_delay_sync {u_jtag_intf_unit/u_jtag_ptap/gen_smc_otp_jtag2axi.u_smc_otp_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_aw/i_src/gen_sync[1].i_sync} JTAG_TCK
set_cdc_max_delay_sync {u_jtag_intf_unit/u_jtag_ptap/gen_smc_otp_jtag2axi.u_smc_otp_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_aw/i_src/gen_sync[2].i_sync} JTAG_TCK
set_cdc_max_delay_sync {u_jtag_intf_unit/u_jtag_ptap/gen_smc_otp_jtag2axi.u_smc_otp_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_aw/i_src/gen_sync[3].i_sync} JTAG_TCK
set_cdc_max_delay_sync u_jtag_intf_unit/u_jtag_ptap/gen_smc_otp_jtag2axi.u_smc_otp_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_b/i_cdc_reset_ctrlr/i_cdc_reset_ctrlr_half_a/i_state_transition_cdc_dst/i_sync DTPCLK
set_cdc_max_delay_sync u_jtag_intf_unit/u_jtag_ptap/gen_smc_otp_jtag2axi.u_smc_otp_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_b/i_cdc_reset_ctrlr/i_cdc_reset_ctrlr_half_a/i_state_transition_cdc_src/i_sync DTPCLK
set_cdc_max_delay_sync u_jtag_intf_unit/u_jtag_ptap/gen_smc_otp_jtag2axi.u_smc_otp_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_b/i_cdc_reset_ctrlr/i_cdc_reset_ctrlr_half_b/i_state_transition_cdc_dst/i_sync JTAG_TCK
set_cdc_max_delay_sync u_jtag_intf_unit/u_jtag_ptap/gen_smc_otp_jtag2axi.u_smc_otp_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_b/i_cdc_reset_ctrlr/i_cdc_reset_ctrlr_half_b/i_state_transition_cdc_src/i_sync JTAG_TCK
set_cdc_max_delay_sync {u_jtag_intf_unit/u_jtag_ptap/gen_smc_otp_jtag2axi.u_smc_otp_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_b/i_dst/gen_sync[0].i_sync} JTAG_TCK
set_cdc_max_delay_sync {u_jtag_intf_unit/u_jtag_ptap/gen_smc_otp_jtag2axi.u_smc_otp_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_b/i_dst/gen_sync[1].i_sync} JTAG_TCK
set_cdc_max_delay_sync {u_jtag_intf_unit/u_jtag_ptap/gen_smc_otp_jtag2axi.u_smc_otp_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_b/i_dst/gen_sync[2].i_sync} JTAG_TCK
set_cdc_max_delay_sync {u_jtag_intf_unit/u_jtag_ptap/gen_smc_otp_jtag2axi.u_smc_otp_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_b/i_dst/gen_sync[3].i_sync} JTAG_TCK
set_cdc_max_delay_sync {u_jtag_intf_unit/u_jtag_ptap/gen_smc_otp_jtag2axi.u_smc_otp_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_b/i_src/gen_sync[0].i_sync} DTPCLK
set_cdc_max_delay_sync {u_jtag_intf_unit/u_jtag_ptap/gen_smc_otp_jtag2axi.u_smc_otp_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_b/i_src/gen_sync[1].i_sync} DTPCLK
set_cdc_max_delay_sync {u_jtag_intf_unit/u_jtag_ptap/gen_smc_otp_jtag2axi.u_smc_otp_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_b/i_src/gen_sync[2].i_sync} DTPCLK
set_cdc_max_delay_sync {u_jtag_intf_unit/u_jtag_ptap/gen_smc_otp_jtag2axi.u_smc_otp_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_b/i_src/gen_sync[3].i_sync} DTPCLK
set_cdc_max_delay_sync u_jtag_intf_unit/u_jtag_ptap/gen_smc_otp_jtag2axi.u_smc_otp_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_r/i_cdc_reset_ctrlr/i_cdc_reset_ctrlr_half_a/i_state_transition_cdc_dst/i_sync DTPCLK
set_cdc_max_delay_sync u_jtag_intf_unit/u_jtag_ptap/gen_smc_otp_jtag2axi.u_smc_otp_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_r/i_cdc_reset_ctrlr/i_cdc_reset_ctrlr_half_a/i_state_transition_cdc_src/i_sync DTPCLK
set_cdc_max_delay_sync u_jtag_intf_unit/u_jtag_ptap/gen_smc_otp_jtag2axi.u_smc_otp_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_r/i_cdc_reset_ctrlr/i_cdc_reset_ctrlr_half_b/i_state_transition_cdc_dst/i_sync JTAG_TCK
set_cdc_max_delay_sync u_jtag_intf_unit/u_jtag_ptap/gen_smc_otp_jtag2axi.u_smc_otp_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_r/i_cdc_reset_ctrlr/i_cdc_reset_ctrlr_half_b/i_state_transition_cdc_src/i_sync JTAG_TCK
set_cdc_max_delay_sync {u_jtag_intf_unit/u_jtag_ptap/gen_smc_otp_jtag2axi.u_smc_otp_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_r/i_dst/gen_sync[0].i_sync} JTAG_TCK
set_cdc_max_delay_sync {u_jtag_intf_unit/u_jtag_ptap/gen_smc_otp_jtag2axi.u_smc_otp_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_r/i_dst/gen_sync[1].i_sync} JTAG_TCK
set_cdc_max_delay_sync {u_jtag_intf_unit/u_jtag_ptap/gen_smc_otp_jtag2axi.u_smc_otp_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_r/i_dst/gen_sync[2].i_sync} JTAG_TCK
set_cdc_max_delay_sync {u_jtag_intf_unit/u_jtag_ptap/gen_smc_otp_jtag2axi.u_smc_otp_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_r/i_dst/gen_sync[3].i_sync} JTAG_TCK
set_cdc_max_delay_sync {u_jtag_intf_unit/u_jtag_ptap/gen_smc_otp_jtag2axi.u_smc_otp_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_r/i_src/gen_sync[0].i_sync} DTPCLK
set_cdc_max_delay_sync {u_jtag_intf_unit/u_jtag_ptap/gen_smc_otp_jtag2axi.u_smc_otp_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_r/i_src/gen_sync[1].i_sync} DTPCLK
set_cdc_max_delay_sync {u_jtag_intf_unit/u_jtag_ptap/gen_smc_otp_jtag2axi.u_smc_otp_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_r/i_src/gen_sync[2].i_sync} DTPCLK
set_cdc_max_delay_sync {u_jtag_intf_unit/u_jtag_ptap/gen_smc_otp_jtag2axi.u_smc_otp_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_r/i_src/gen_sync[3].i_sync} DTPCLK
set_cdc_max_delay_sync u_jtag_intf_unit/u_jtag_ptap/gen_smc_otp_jtag2axi.u_smc_otp_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_w/i_cdc_reset_ctrlr/i_cdc_reset_ctrlr_half_a/i_state_transition_cdc_dst/i_sync JTAG_TCK
set_cdc_max_delay_sync u_jtag_intf_unit/u_jtag_ptap/gen_smc_otp_jtag2axi.u_smc_otp_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_w/i_cdc_reset_ctrlr/i_cdc_reset_ctrlr_half_a/i_state_transition_cdc_src/i_sync JTAG_TCK
set_cdc_max_delay_sync u_jtag_intf_unit/u_jtag_ptap/gen_smc_otp_jtag2axi.u_smc_otp_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_w/i_cdc_reset_ctrlr/i_cdc_reset_ctrlr_half_b/i_state_transition_cdc_dst/i_sync DTPCLK
set_cdc_max_delay_sync u_jtag_intf_unit/u_jtag_ptap/gen_smc_otp_jtag2axi.u_smc_otp_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_w/i_cdc_reset_ctrlr/i_cdc_reset_ctrlr_half_b/i_state_transition_cdc_src/i_sync DTPCLK
set_cdc_max_delay_sync {u_jtag_intf_unit/u_jtag_ptap/gen_smc_otp_jtag2axi.u_smc_otp_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_w/i_dst/gen_sync[0].i_sync} DTPCLK
set_cdc_max_delay_sync {u_jtag_intf_unit/u_jtag_ptap/gen_smc_otp_jtag2axi.u_smc_otp_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_w/i_dst/gen_sync[1].i_sync} DTPCLK
set_cdc_max_delay_sync {u_jtag_intf_unit/u_jtag_ptap/gen_smc_otp_jtag2axi.u_smc_otp_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_w/i_dst/gen_sync[2].i_sync} DTPCLK
set_cdc_max_delay_sync {u_jtag_intf_unit/u_jtag_ptap/gen_smc_otp_jtag2axi.u_smc_otp_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_w/i_dst/gen_sync[3].i_sync} DTPCLK
set_cdc_max_delay_sync {u_jtag_intf_unit/u_jtag_ptap/gen_smc_otp_jtag2axi.u_smc_otp_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_w/i_src/gen_sync[0].i_sync} JTAG_TCK
set_cdc_max_delay_sync {u_jtag_intf_unit/u_jtag_ptap/gen_smc_otp_jtag2axi.u_smc_otp_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_w/i_src/gen_sync[1].i_sync} JTAG_TCK
set_cdc_max_delay_sync {u_jtag_intf_unit/u_jtag_ptap/gen_smc_otp_jtag2axi.u_smc_otp_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_w/i_src/gen_sync[2].i_sync} JTAG_TCK
set_cdc_max_delay_sync {u_jtag_intf_unit/u_jtag_ptap/gen_smc_otp_jtag2axi.u_smc_otp_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_w/i_src/gen_sync[3].i_sync} JTAG_TCK

# ---- cdc_fifo_gray_clearable (10 instances) ----
set_cdc_max_delay_cdc_fifo_gray u_jtag_intf_unit/u_jtag_ptap/gen_smc_jtag2axi.u_smc_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_ar JTAG_TCK DTPCLK
set_cdc_max_delay_cdc_fifo_gray u_jtag_intf_unit/u_jtag_ptap/gen_smc_jtag2axi.u_smc_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_aw JTAG_TCK DTPCLK
set_cdc_max_delay_cdc_fifo_gray u_jtag_intf_unit/u_jtag_ptap/gen_smc_jtag2axi.u_smc_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_b DTPCLK JTAG_TCK
set_cdc_max_delay_cdc_fifo_gray u_jtag_intf_unit/u_jtag_ptap/gen_smc_jtag2axi.u_smc_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_r DTPCLK JTAG_TCK
set_cdc_max_delay_cdc_fifo_gray u_jtag_intf_unit/u_jtag_ptap/gen_smc_jtag2axi.u_smc_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_w JTAG_TCK DTPCLK
set_cdc_max_delay_cdc_fifo_gray u_jtag_intf_unit/u_jtag_ptap/gen_smc_otp_jtag2axi.u_smc_otp_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_ar JTAG_TCK DTPCLK
set_cdc_max_delay_cdc_fifo_gray u_jtag_intf_unit/u_jtag_ptap/gen_smc_otp_jtag2axi.u_smc_otp_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_aw JTAG_TCK DTPCLK
set_cdc_max_delay_cdc_fifo_gray u_jtag_intf_unit/u_jtag_ptap/gen_smc_otp_jtag2axi.u_smc_otp_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_b DTPCLK JTAG_TCK
set_cdc_max_delay_cdc_fifo_gray u_jtag_intf_unit/u_jtag_ptap/gen_smc_otp_jtag2axi.u_smc_otp_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_r DTPCLK JTAG_TCK
set_cdc_max_delay_cdc_fifo_gray u_jtag_intf_unit/u_jtag_ptap/gen_smc_otp_jtag2axi.u_smc_otp_jtag2axi/u_axi_cdc/i_cdc_fifo_gray_clearable_w JTAG_TCK DTPCLK
