// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 Tenstorrent USA, Inc.
//
// Written by cov/tools/gen_fcov_crypto_reg_addrs.py from sep_reg.svh and
// sep_memory_map.py. Do not edit.
//
// First and last byte of each unit aperture (memory_map.adoc, SEP Component
// Address Map).
localparam logic [31:0] FapBaseSepSram = 32'h1000_0000;
localparam logic [31:0] FapLastSepSram = 32'h1003_FFFF;
localparam logic [31:0] FapBaseSepBootRom = 32'h1004_0000;
localparam logic [31:0] FapLastSepBootRom = 32'h1004_FFFF;
localparam logic [31:0] FapBaseSecureDma = 32'h1080_0000;
localparam logic [31:0] FapLastSecureDma = 32'h1080_0FFF;
localparam logic [31:0] FapBaseWdtTimer = 32'h1080_1000;
localparam logic [31:0] FapLastWdtTimer = 32'h1080_1FFF;
localparam logic [31:0] FapBaseSepScratchCold = 32'h1080_2000;
localparam logic [31:0] FapLastSepScratchCold = 32'h1080_203F;
localparam logic [31:0] FapBaseSepScratchWarm = 32'h1080_2080;
localparam logic [31:0] FapLastSepScratchWarm = 32'h1080_20BF;
localparam logic [31:0] FapBaseSepResetCtrl = 32'h1080_3000;
localparam logic [31:0] FapLastSepResetCtrl = 32'h1080_3FFF;
localparam logic [31:0] FapBaseOtbn = 32'h1090_0000;
localparam logic [31:0] FapLastOtbn = 32'h1090_FFFF;
localparam logic [31:0] FapBaseAes = 32'h1091_0000;
localparam logic [31:0] FapLastAes = 32'h1091_0FFF;
localparam logic [31:0] FapBaseHmac = 32'h1091_1000;
localparam logic [31:0] FapLastHmac = 32'h1091_2FFF;
localparam logic [31:0] FapBaseKmac = 32'h1091_3000;
localparam logic [31:0] FapLastKmac = 32'h1091_3FFF;
localparam logic [31:0] FapBaseCsrng = 32'h1091_5000;
localparam logic [31:0] FapLastCsrng = 32'h1091_57FF;
localparam logic [31:0] FapBaseEdn = 32'h1091_5800;
localparam logic [31:0] FapLastEdn = 32'h1091_5FFF;
localparam logic [31:0] FapBaseEntropySource = 32'h1091_6000;
localparam logic [31:0] FapLastEntropySource = 32'h1091_6FFF;
localparam logic [31:0] FapBaseTrng = 32'h1091_7000;
localparam logic [31:0] FapLastTrng = 32'h1091_7FFF;
localparam logic [31:0] FapBaseSepLifecycleCtrl = 32'h1091_8000;
localparam logic [31:0] FapLastSepLifecycleCtrl = 32'h1091_FFFF;
localparam logic [31:0] FapBaseKmMailboxSep = 32'h1092_0000;
localparam logic [31:0] FapLastKmMailboxSep = 32'h1092_0FFF;
localparam logic [31:0] FapBaseSepEfuseMap = 32'h1093_0000;
localparam logic [31:0] FapLastSepEfuseMap = 32'h1093_03FF;
localparam logic [31:0] FapBaseEfuseInterfaceCtrl = 32'h1093_0400;
localparam logic [31:0] FapLastEfuseInterfaceCtrl = 32'h1093_04FF;
localparam logic [31:0] FapBaseEfuseMmr = 32'h1093_0500;
localparam logic [31:0] FapLastEfuseMmr = 32'h1093_05FF;
localparam logic [31:0] FapBaseAbr = 32'h1094_0000;
localparam logic [31:0] FapLastAbr = 32'h1094_FFFF;
localparam logic [31:0] FapBaseEntropyPool = 32'h1095_0000;
localparam logic [31:0] FapLastEntropyPool = 32'h1095_FFFF;
localparam logic [31:0] FapBaseAxilMailbox = 32'h10A0_0000;
localparam logic [31:0] FapLastAxilMailbox = 32'h10A0_FFFF;
localparam logic [31:0] FapBaseLocalMasterAliasRemapCtrl = 32'h10A1_0000;
localparam logic [31:0] FapLastLocalMasterAliasRemapCtrl = 32'h10A1_01FF;
localparam logic [31:0] FapBaseApOutputRemapCtrl = 32'h10A1_0200;
localparam logic [31:0] FapLastApOutputRemapCtrl = 32'h10A1_027F;
localparam logic [31:0] FapBaseSteeOutputRemapCtrl = 32'h10A1_0300;
localparam logic [31:0] FapLastSteeOutputRemapCtrl = 32'h10A1_037F;
localparam logic [31:0] FapBaseOutboundFilterCtrl = 32'h10A2_0000;
localparam logic [31:0] FapLastOutboundFilterCtrl = 32'h10A2_03FF;
localparam logic [31:0] FapBaseInboundFilterCtrl = 32'h10A2_1000;
localparam logic [31:0] FapLastInboundFilterCtrl = 32'h10A2_11FF;
localparam logic [31:0] FapBaseSepCpuCtrl = 32'h10A3_0000;
localparam logic [31:0] FapLastSepCpuCtrl = 32'h10A3_1FFF;
localparam logic [31:0] FapBaseSpiController = 32'h10B0_0000;
localparam logic [31:0] FapLastSpiController = 32'h10BF_FFFF;
localparam logic [31:0] FapBaseApRegion = 32'h1100_0000;
localparam logic [31:0] FapLastApRegion = 32'h117F_FFFF;
localparam logic [31:0] FapBaseSteeRegion = 32'h1180_0000;
localparam logic [31:0] FapLastSteeRegion = 32'h11FF_FFFF;
localparam logic [31:0] FapBaseSepExternal = 32'h2000_0000;
localparam logic [31:0] FapLastSepExternal = 32'h3FFF_FFFF;
localparam logic [31:0] FapBaseSepIccm = 32'hC000_0000;
localparam logic [31:0] FapLastSepIccm = 32'hC003_FFFF;
localparam logic [31:0] FapBaseSepDccm = 32'hC004_0000;
localparam logic [31:0] FapLastSepDccm = 32'hC005_FFFF;
localparam logic [31:0] FapBasePic = 32'hC008_0000;
localparam logic [31:0] FapLastPic = 32'hC008_7FFF;

// 1 when the 32-bit address is a register or lies in a memory window of the
// OTBN, HMAC, KMAC, entropy source or ABR unit; 0 for every other address of
// those units (a hole).
function automatic bit fcov_crypto_reg_addr(input logic [31:0] a);
  if (a >= OTBN_IMEM_MEM_BASE_ADDR && a - OTBN_IMEM_MEM_BASE_ADDR < OTBN_IMEM_MEM_SIZE) return 1'b1;
  if (a >= OTBN_DMEM_MEM_BASE_ADDR && a - OTBN_DMEM_MEM_BASE_ADDR < OTBN_DMEM_MEM_SIZE) return 1'b1;
  if (a >= HMAC_MSG_FIFO_MEM_BASE_ADDR && a - HMAC_MSG_FIFO_MEM_BASE_ADDR < HMAC_MSG_FIFO_MEM_SIZE)
    return 1'b1;
  if (a >= KMAC_STATE_MEM_BASE_ADDR && a - KMAC_STATE_MEM_BASE_ADDR < KMAC_STATE_MEM_SIZE)
    return 1'b1;
  if (a >= KMAC_MSG_FIFO_MEM_BASE_ADDR && a - KMAC_MSG_FIFO_MEM_BASE_ADDR < KMAC_MSG_FIFO_MEM_SIZE)
    return 1'b1;
  if (a >= ABR_MLDSA_PUBKEY_MEM_BASE_ADDR && a - ABR_MLDSA_PUBKEY_MEM_BASE_ADDR < ABR_MLDSA_PUBKEY_MEM_SIZE)
    return 1'b1;
  if (a >= ABR_MLDSA_SIGNATURE_MEM_BASE_ADDR && a - ABR_MLDSA_SIGNATURE_MEM_BASE_ADDR < ABR_MLDSA_SIGNATURE_MEM_SIZE)
    return 1'b1;
  if (a >= ABR_MLDSA_PRIVKEY_OUT_MEM_BASE_ADDR && a - ABR_MLDSA_PRIVKEY_OUT_MEM_BASE_ADDR < ABR_MLDSA_PRIVKEY_OUT_MEM_SIZE)
    return 1'b1;
  if (a >= ABR_MLDSA_PRIVKEY_IN_MEM_BASE_ADDR && a - ABR_MLDSA_PRIVKEY_IN_MEM_BASE_ADDR < ABR_MLDSA_PRIVKEY_IN_MEM_SIZE)
    return 1'b1;
  if (a >= ABR_MLKEM_MSG_MEM_BASE_ADDR && a - ABR_MLKEM_MSG_MEM_BASE_ADDR < ABR_MLKEM_MSG_MEM_SIZE)
    return 1'b1;
  if (a >= ABR_MLKEM_DECAPS_KEY_MEM_BASE_ADDR && a - ABR_MLKEM_DECAPS_KEY_MEM_BASE_ADDR < ABR_MLKEM_DECAPS_KEY_MEM_SIZE)
    return 1'b1;
  if (a >= ABR_MLKEM_ENCAPS_KEY_MEM_BASE_ADDR && a - ABR_MLKEM_ENCAPS_KEY_MEM_BASE_ADDR < ABR_MLKEM_ENCAPS_KEY_MEM_SIZE)
    return 1'b1;
  if (a >= ABR_MLKEM_CIPHERTEXT_MEM_BASE_ADDR && a - ABR_MLKEM_CIPHERTEXT_MEM_BASE_ADDR < ABR_MLKEM_CIPHERTEXT_MEM_SIZE)
    return 1'b1;
  case (a)
    OTBN_INTR_STATE_REG_ADDR, OTBN_INTR_ENABLE_REG_ADDR, OTBN_INTR_TEST_REG_ADDR,
    OTBN_ALERT_TEST_REG_ADDR, OTBN_CMD_REG_ADDR, OTBN_CTRL_REG_ADDR,
    OTBN_STATUS_REG_ADDR, OTBN_ERR_BITS_REG_ADDR, OTBN_FATAL_ALERT_CAUSE_REG_ADDR,
    OTBN_INSN_CNT_REG_ADDR, OTBN_LOAD_CHECKSUM_REG_ADDR, HMAC_INTR_STATE_REG_ADDR,
    HMAC_INTR_ENABLE_REG_ADDR, HMAC_INTR_TEST_REG_ADDR, HMAC_ALERT_TEST_REG_ADDR,
    HMAC_CFG_REG_ADDR, HMAC_CMD_REG_ADDR, HMAC_STATUS_REG_ADDR,
    HMAC_ERR_CODE_REG_ADDR, HMAC_WIPE_SECRET_REG_ADDR, HMAC_KEY_0__REG_ADDR,
    HMAC_KEY_1__REG_ADDR, HMAC_KEY_2__REG_ADDR, HMAC_KEY_3__REG_ADDR,
    HMAC_KEY_4__REG_ADDR, HMAC_KEY_5__REG_ADDR, HMAC_KEY_6__REG_ADDR,
    HMAC_KEY_7__REG_ADDR, HMAC_KEY_8__REG_ADDR, HMAC_KEY_9__REG_ADDR,
    HMAC_KEY_10__REG_ADDR, HMAC_KEY_11__REG_ADDR, HMAC_KEY_12__REG_ADDR,
    HMAC_KEY_13__REG_ADDR, HMAC_KEY_14__REG_ADDR, HMAC_KEY_15__REG_ADDR,
    HMAC_KEY_16__REG_ADDR, HMAC_KEY_17__REG_ADDR, HMAC_KEY_18__REG_ADDR,
    HMAC_KEY_19__REG_ADDR, HMAC_KEY_20__REG_ADDR, HMAC_KEY_21__REG_ADDR,
    HMAC_KEY_22__REG_ADDR, HMAC_KEY_23__REG_ADDR, HMAC_KEY_24__REG_ADDR,
    HMAC_KEY_25__REG_ADDR, HMAC_KEY_26__REG_ADDR, HMAC_KEY_27__REG_ADDR,
    HMAC_KEY_28__REG_ADDR, HMAC_KEY_29__REG_ADDR, HMAC_KEY_30__REG_ADDR,
    HMAC_KEY_31__REG_ADDR, HMAC_DIGEST_0__REG_ADDR, HMAC_DIGEST_1__REG_ADDR,
    HMAC_DIGEST_2__REG_ADDR, HMAC_DIGEST_3__REG_ADDR, HMAC_DIGEST_4__REG_ADDR,
    HMAC_DIGEST_5__REG_ADDR, HMAC_DIGEST_6__REG_ADDR, HMAC_DIGEST_7__REG_ADDR,
    HMAC_DIGEST_8__REG_ADDR, HMAC_DIGEST_9__REG_ADDR, HMAC_DIGEST_10__REG_ADDR,
    HMAC_DIGEST_11__REG_ADDR, HMAC_DIGEST_12__REG_ADDR, HMAC_DIGEST_13__REG_ADDR,
    HMAC_DIGEST_14__REG_ADDR, HMAC_DIGEST_15__REG_ADDR, HMAC_MSG_LENGTH_LOWER_REG_ADDR,
    HMAC_MSG_LENGTH_UPPER_REG_ADDR, KMAC_INTR_STATE_REG_ADDR, KMAC_INTR_ENABLE_REG_ADDR,
    KMAC_INTR_TEST_REG_ADDR, KMAC_ALERT_TEST_REG_ADDR, KMAC_CFG_REGWEN_REG_ADDR,
    KMAC_CFG_SHADOWED_REG_ADDR, KMAC_CMD_REG_ADDR, KMAC_STATUS_REG_ADDR,
    KMAC_ENTROPY_PERIOD_REG_ADDR, KMAC_ENTROPY_REFRESH_HASH_CNT_REG_ADDR, KMAC_ENTROPY_REFRESH_THRESHOLD_SHADOWED_REG_ADDR,
    KMAC_ENTROPY_SEED_REG_ADDR, KMAC_KEY_SHARE0_0__REG_ADDR, KMAC_KEY_SHARE0_1__REG_ADDR,
    KMAC_KEY_SHARE0_2__REG_ADDR, KMAC_KEY_SHARE0_3__REG_ADDR, KMAC_KEY_SHARE0_4__REG_ADDR,
    KMAC_KEY_SHARE0_5__REG_ADDR, KMAC_KEY_SHARE0_6__REG_ADDR, KMAC_KEY_SHARE0_7__REG_ADDR,
    KMAC_KEY_SHARE0_8__REG_ADDR, KMAC_KEY_SHARE0_9__REG_ADDR, KMAC_KEY_SHARE0_10__REG_ADDR,
    KMAC_KEY_SHARE0_11__REG_ADDR, KMAC_KEY_SHARE0_12__REG_ADDR, KMAC_KEY_SHARE0_13__REG_ADDR,
    KMAC_KEY_SHARE0_14__REG_ADDR, KMAC_KEY_SHARE0_15__REG_ADDR, KMAC_KEY_SHARE1_0__REG_ADDR,
    KMAC_KEY_SHARE1_1__REG_ADDR, KMAC_KEY_SHARE1_2__REG_ADDR, KMAC_KEY_SHARE1_3__REG_ADDR,
    KMAC_KEY_SHARE1_4__REG_ADDR, KMAC_KEY_SHARE1_5__REG_ADDR, KMAC_KEY_SHARE1_6__REG_ADDR,
    KMAC_KEY_SHARE1_7__REG_ADDR, KMAC_KEY_SHARE1_8__REG_ADDR, KMAC_KEY_SHARE1_9__REG_ADDR,
    KMAC_KEY_SHARE1_10__REG_ADDR, KMAC_KEY_SHARE1_11__REG_ADDR, KMAC_KEY_SHARE1_12__REG_ADDR,
    KMAC_KEY_SHARE1_13__REG_ADDR, KMAC_KEY_SHARE1_14__REG_ADDR, KMAC_KEY_SHARE1_15__REG_ADDR,
    KMAC_KEY_LEN_REG_ADDR, KMAC_PREFIX_0__REG_ADDR, KMAC_PREFIX_1__REG_ADDR,
    KMAC_PREFIX_2__REG_ADDR, KMAC_PREFIX_3__REG_ADDR, KMAC_PREFIX_4__REG_ADDR,
    KMAC_PREFIX_5__REG_ADDR, KMAC_PREFIX_6__REG_ADDR, KMAC_PREFIX_7__REG_ADDR,
    KMAC_PREFIX_8__REG_ADDR, KMAC_PREFIX_9__REG_ADDR, KMAC_PREFIX_10__REG_ADDR,
    KMAC_ERR_CODE_REG_ADDR, ENTROPY_SOURCE_COMPONENT_ID_REG_ADDR, ENTROPY_SOURCE_CTRL_REG_ADDR,
    ENTROPY_SOURCE_DEBUG_CTRL_REG_ADDR, ENTROPY_SOURCE_INTR_STATUS_REG_ADDR, ENTROPY_SOURCE_INTR_ENABLE_REG_ADDR,
    ENTROPY_SOURCE_INTR_TEST_REG_ADDR, ENTROPY_SOURCE_SHA256_STATUS_REG_ADDR, ENTROPY_SOURCE_FIFO_CTRL_REG_ADDR,
    ENTROPY_SOURCE_FIFO_STATUS_REG_ADDR, ENTROPY_SOURCE_FIFO_RDATA_REG_ADDR, ENTROPY_SOURCE_HEALTH_TEST_CTRL_REG_ADDR,
    ENTROPY_SOURCE_HEALTH_TEST_WINDOW_SIZE_REG_ADDR, ENTROPY_SOURCE_MARKOV_TEST_PROB_THRESHOLDS_REG_ADDR, ENTROPY_SOURCE_HEALTH_TEST_STATUS_REG_ADDR,
    ENTROPY_SOURCE_REPETITION_TEST_COUNT_REG_ADDR, ENTROPY_SOURCE_APT_PATTERN_COUNT_1BIT_REG_ADDR, ENTROPY_SOURCE_APT_PATTERN_COUNT_2BIT_REG_ADDR,
    ENTROPY_SOURCE_APT_PROPORTION_1BIT_REG_ADDR, ENTROPY_SOURCE_APT_PROPORTION_LO_REG_ADDR, ENTROPY_SOURCE_MARKOV_TEST_COUNTS_0_REG_ADDR,
    ENTROPY_SOURCE_RING_OSC_ENABLE_REG_ADDR, ENTROPY_SOURCE_RING_OSC_TUNE_REG_ADDR, ENTROPY_SOURCE_RING_OSC_CTRL_REG_ADDR,
    ENTROPY_SOURCE_DECORRELATOR_CTRL_REG_ADDR, ENTROPY_SOURCE_DECORRELATOR_MASK_REG_ADDR, ENTROPY_SOURCE_MAIN_SM_STATUS_REG_ADDR,
    ENTROPY_SOURCE_GENERATOR_0_HEALTH_STATUS_REG_ADDR, ENTROPY_SOURCE_GENERATOR_1_HEALTH_STATUS_REG_ADDR, ENTROPY_SOURCE_GENERATOR_2_HEALTH_STATUS_REG_ADDR,
    ENTROPY_SOURCE_GENERATOR_3_HEALTH_STATUS_REG_ADDR, ENTROPY_SOURCE_GENERATOR_4_HEALTH_STATUS_REG_ADDR, ENTROPY_SOURCE_GENERATOR_5_HEALTH_STATUS_REG_ADDR,
    ENTROPY_SOURCE_GENERATOR_6_HEALTH_STATUS_REG_ADDR, ENTROPY_SOURCE_GENERATOR_7_HEALTH_STATUS_REG_ADDR, ENTROPY_SOURCE_GENERATOR_8_HEALTH_STATUS_REG_ADDR,
    ENTROPY_SOURCE_GENERATOR_9_HEALTH_STATUS_REG_ADDR, ENTROPY_SOURCE_GENERATOR_10_HEALTH_STATUS_REG_ADDR, ENTROPY_SOURCE_GENERATOR_11_HEALTH_STATUS_REG_ADDR,
    ENTROPY_SOURCE_GENERATOR_0_SAMPLE_CLK_CONFIG_REG_ADDR, ENTROPY_SOURCE_GENERATOR_1_SAMPLE_CLK_CONFIG_REG_ADDR, ENTROPY_SOURCE_GENERATOR_2_SAMPLE_CLK_CONFIG_REG_ADDR,
    ENTROPY_SOURCE_GENERATOR_3_SAMPLE_CLK_CONFIG_REG_ADDR, ENTROPY_SOURCE_GENERATOR_4_SAMPLE_CLK_CONFIG_REG_ADDR, ENTROPY_SOURCE_GENERATOR_5_SAMPLE_CLK_CONFIG_REG_ADDR,
    ENTROPY_SOURCE_GENERATOR_6_SAMPLE_CLK_CONFIG_REG_ADDR, ENTROPY_SOURCE_GENERATOR_7_SAMPLE_CLK_CONFIG_REG_ADDR, ENTROPY_SOURCE_GENERATOR_8_SAMPLE_CLK_CONFIG_REG_ADDR,
    ENTROPY_SOURCE_GENERATOR_9_SAMPLE_CLK_CONFIG_REG_ADDR, ENTROPY_SOURCE_GENERATOR_10_SAMPLE_CLK_CONFIG_REG_ADDR, ENTROPY_SOURCE_GENERATOR_11_SAMPLE_CLK_CONFIG_REG_ADDR,
    ENTROPY_SOURCE_HT_WATERMARK_NUM_REG_ADDR, ENTROPY_SOURCE_HT_WATERMARK_REG_ADDR, ENTROPY_SOURCE_REPCNT_TOTAL_FAILS_REG_ADDR,
    ENTROPY_SOURCE_APT_HI_TOTAL_FAILS_REG_ADDR, ENTROPY_SOURCE_APT_LO_TOTAL_FAILS_REG_ADDR, ENTROPY_SOURCE_MARKOV_HI_TOTAL_FAILS_REG_ADDR,
    ENTROPY_SOURCE_MARKOV_LO_TOTAL_FAILS_REG_ADDR, ENTROPY_SOURCE_ALERT_SUMMARY_FAIL_COUNTS_REG_ADDR, ENTROPY_SOURCE_ALERT_FAIL_COUNTS_REG_ADDR,
    ENTROPY_SOURCE_FIPS_LOCK_REG_ADDR, ENTROPY_SOURCE_ALERT_THRESHOLD_REG_ADDR, ENTROPY_SOURCE_MIN_ENTROPY_H_REG_ADDR,
    ENTROPY_SOURCE_RECOMMENDED_THRESHOLDS_REG_ADDR, ENTROPY_SOURCE_BIW_OBS_CTRL_REG_ADDR, ENTROPY_SOURCE_BIW_OBS_STATUS_REG_ADDR,
    ENTROPY_SOURCE_BIW_OBS_RDATA_REG_ADDR, ENTROPY_SOURCE_NOISE_OBS_CTRL_REG_ADDR, ENTROPY_SOURCE_NOISE_OBS_STATUS_REG_ADDR,
    ENTROPY_SOURCE_NOISE_OBS_RDATA_REG_ADDR, ABR_MLDSA_NAME_0__REG_ADDR, ABR_MLDSA_NAME_1__REG_ADDR,
    ABR_MLDSA_VERSION_0__REG_ADDR, ABR_MLDSA_VERSION_1__REG_ADDR, ABR_MLDSA_CTRL_REG_ADDR,
    ABR_MLDSA_STATUS_REG_ADDR, ABR_ABR_ENTROPY_0__REG_ADDR, ABR_ABR_ENTROPY_1__REG_ADDR,
    ABR_ABR_ENTROPY_2__REG_ADDR, ABR_ABR_ENTROPY_3__REG_ADDR, ABR_ABR_ENTROPY_4__REG_ADDR,
    ABR_ABR_ENTROPY_5__REG_ADDR, ABR_ABR_ENTROPY_6__REG_ADDR, ABR_ABR_ENTROPY_7__REG_ADDR,
    ABR_ABR_ENTROPY_8__REG_ADDR, ABR_ABR_ENTROPY_9__REG_ADDR, ABR_ABR_ENTROPY_10__REG_ADDR,
    ABR_ABR_ENTROPY_11__REG_ADDR, ABR_ABR_ENTROPY_12__REG_ADDR, ABR_ABR_ENTROPY_13__REG_ADDR,
    ABR_ABR_ENTROPY_14__REG_ADDR, ABR_ABR_ENTROPY_15__REG_ADDR, ABR_MLDSA_SEED_0__REG_ADDR,
    ABR_MLDSA_SEED_1__REG_ADDR, ABR_MLDSA_SEED_2__REG_ADDR, ABR_MLDSA_SEED_3__REG_ADDR,
    ABR_MLDSA_SEED_4__REG_ADDR, ABR_MLDSA_SEED_5__REG_ADDR, ABR_MLDSA_SEED_6__REG_ADDR,
    ABR_MLDSA_SEED_7__REG_ADDR, ABR_MLDSA_SIGN_RND_0__REG_ADDR, ABR_MLDSA_SIGN_RND_1__REG_ADDR,
    ABR_MLDSA_SIGN_RND_2__REG_ADDR, ABR_MLDSA_SIGN_RND_3__REG_ADDR, ABR_MLDSA_SIGN_RND_4__REG_ADDR,
    ABR_MLDSA_SIGN_RND_5__REG_ADDR, ABR_MLDSA_SIGN_RND_6__REG_ADDR, ABR_MLDSA_SIGN_RND_7__REG_ADDR,
    ABR_MLDSA_MSG_0__REG_ADDR, ABR_MLDSA_MSG_1__REG_ADDR, ABR_MLDSA_MSG_2__REG_ADDR,
    ABR_MLDSA_MSG_3__REG_ADDR, ABR_MLDSA_MSG_4__REG_ADDR, ABR_MLDSA_MSG_5__REG_ADDR,
    ABR_MLDSA_MSG_6__REG_ADDR, ABR_MLDSA_MSG_7__REG_ADDR, ABR_MLDSA_MSG_8__REG_ADDR,
    ABR_MLDSA_MSG_9__REG_ADDR, ABR_MLDSA_MSG_10__REG_ADDR, ABR_MLDSA_MSG_11__REG_ADDR,
    ABR_MLDSA_MSG_12__REG_ADDR, ABR_MLDSA_MSG_13__REG_ADDR, ABR_MLDSA_MSG_14__REG_ADDR,
    ABR_MLDSA_MSG_15__REG_ADDR, ABR_MLDSA_VERIFY_RES_0__REG_ADDR, ABR_MLDSA_VERIFY_RES_1__REG_ADDR,
    ABR_MLDSA_VERIFY_RES_2__REG_ADDR, ABR_MLDSA_VERIFY_RES_3__REG_ADDR, ABR_MLDSA_VERIFY_RES_4__REG_ADDR,
    ABR_MLDSA_VERIFY_RES_5__REG_ADDR, ABR_MLDSA_VERIFY_RES_6__REG_ADDR, ABR_MLDSA_VERIFY_RES_7__REG_ADDR,
    ABR_MLDSA_VERIFY_RES_8__REG_ADDR, ABR_MLDSA_VERIFY_RES_9__REG_ADDR, ABR_MLDSA_VERIFY_RES_10__REG_ADDR,
    ABR_MLDSA_VERIFY_RES_11__REG_ADDR, ABR_MLDSA_VERIFY_RES_12__REG_ADDR, ABR_MLDSA_VERIFY_RES_13__REG_ADDR,
    ABR_MLDSA_VERIFY_RES_14__REG_ADDR, ABR_MLDSA_VERIFY_RES_15__REG_ADDR, ABR_MLDSA_EXTERNAL_MU_0__REG_ADDR,
    ABR_MLDSA_EXTERNAL_MU_1__REG_ADDR, ABR_MLDSA_EXTERNAL_MU_2__REG_ADDR, ABR_MLDSA_EXTERNAL_MU_3__REG_ADDR,
    ABR_MLDSA_EXTERNAL_MU_4__REG_ADDR, ABR_MLDSA_EXTERNAL_MU_5__REG_ADDR, ABR_MLDSA_EXTERNAL_MU_6__REG_ADDR,
    ABR_MLDSA_EXTERNAL_MU_7__REG_ADDR, ABR_MLDSA_EXTERNAL_MU_8__REG_ADDR, ABR_MLDSA_EXTERNAL_MU_9__REG_ADDR,
    ABR_MLDSA_EXTERNAL_MU_10__REG_ADDR, ABR_MLDSA_EXTERNAL_MU_11__REG_ADDR, ABR_MLDSA_EXTERNAL_MU_12__REG_ADDR,
    ABR_MLDSA_EXTERNAL_MU_13__REG_ADDR, ABR_MLDSA_EXTERNAL_MU_14__REG_ADDR, ABR_MLDSA_EXTERNAL_MU_15__REG_ADDR,
    ABR_MLDSA_MSG_STROBE_REG_ADDR, ABR_MLDSA_CTX_CONFIG_REG_ADDR, ABR_MLDSA_CTX_0__REG_ADDR,
    ABR_MLDSA_CTX_1__REG_ADDR, ABR_MLDSA_CTX_2__REG_ADDR, ABR_MLDSA_CTX_3__REG_ADDR,
    ABR_MLDSA_CTX_4__REG_ADDR, ABR_MLDSA_CTX_5__REG_ADDR, ABR_MLDSA_CTX_6__REG_ADDR,
    ABR_MLDSA_CTX_7__REG_ADDR, ABR_MLDSA_CTX_8__REG_ADDR, ABR_MLDSA_CTX_9__REG_ADDR,
    ABR_MLDSA_CTX_10__REG_ADDR, ABR_MLDSA_CTX_11__REG_ADDR, ABR_MLDSA_CTX_12__REG_ADDR,
    ABR_MLDSA_CTX_13__REG_ADDR, ABR_MLDSA_CTX_14__REG_ADDR, ABR_MLDSA_CTX_15__REG_ADDR,
    ABR_MLDSA_CTX_16__REG_ADDR, ABR_MLDSA_CTX_17__REG_ADDR, ABR_MLDSA_CTX_18__REG_ADDR,
    ABR_MLDSA_CTX_19__REG_ADDR, ABR_MLDSA_CTX_20__REG_ADDR, ABR_MLDSA_CTX_21__REG_ADDR,
    ABR_MLDSA_CTX_22__REG_ADDR, ABR_MLDSA_CTX_23__REG_ADDR, ABR_MLDSA_CTX_24__REG_ADDR,
    ABR_MLDSA_CTX_25__REG_ADDR, ABR_MLDSA_CTX_26__REG_ADDR, ABR_MLDSA_CTX_27__REG_ADDR,
    ABR_MLDSA_CTX_28__REG_ADDR, ABR_MLDSA_CTX_29__REG_ADDR, ABR_MLDSA_CTX_30__REG_ADDR,
    ABR_MLDSA_CTX_31__REG_ADDR, ABR_MLDSA_CTX_32__REG_ADDR, ABR_MLDSA_CTX_33__REG_ADDR,
    ABR_MLDSA_CTX_34__REG_ADDR, ABR_MLDSA_CTX_35__REG_ADDR, ABR_MLDSA_CTX_36__REG_ADDR,
    ABR_MLDSA_CTX_37__REG_ADDR, ABR_MLDSA_CTX_38__REG_ADDR, ABR_MLDSA_CTX_39__REG_ADDR,
    ABR_MLDSA_CTX_40__REG_ADDR, ABR_MLDSA_CTX_41__REG_ADDR, ABR_MLDSA_CTX_42__REG_ADDR,
    ABR_MLDSA_CTX_43__REG_ADDR, ABR_MLDSA_CTX_44__REG_ADDR, ABR_MLDSA_CTX_45__REG_ADDR,
    ABR_MLDSA_CTX_46__REG_ADDR, ABR_MLDSA_CTX_47__REG_ADDR, ABR_MLDSA_CTX_48__REG_ADDR,
    ABR_MLDSA_CTX_49__REG_ADDR, ABR_MLDSA_CTX_50__REG_ADDR, ABR_MLDSA_CTX_51__REG_ADDR,
    ABR_MLDSA_CTX_52__REG_ADDR, ABR_MLDSA_CTX_53__REG_ADDR, ABR_MLDSA_CTX_54__REG_ADDR,
    ABR_MLDSA_CTX_55__REG_ADDR, ABR_MLDSA_CTX_56__REG_ADDR, ABR_MLDSA_CTX_57__REG_ADDR,
    ABR_MLDSA_CTX_58__REG_ADDR, ABR_MLDSA_CTX_59__REG_ADDR, ABR_MLDSA_CTX_60__REG_ADDR,
    ABR_MLDSA_CTX_61__REG_ADDR, ABR_MLDSA_CTX_62__REG_ADDR, ABR_MLDSA_CTX_63__REG_ADDR,
    ABR_KV_MLDSA_SEED_RD_CTRL_REG_ADDR, ABR_KV_MLDSA_SEED_RD_STATUS_REG_ADDR, ABR_INTR_BLOCK_RF_GLOBAL_INTR_EN_R_REG_ADDR,
    ABR_INTR_BLOCK_RF_ERROR_INTR_EN_R_REG_ADDR, ABR_INTR_BLOCK_RF_NOTIF_INTR_EN_R_REG_ADDR, ABR_INTR_BLOCK_RF_ERROR_GLOBAL_INTR_R_REG_ADDR,
    ABR_INTR_BLOCK_RF_NOTIF_GLOBAL_INTR_R_REG_ADDR, ABR_INTR_BLOCK_RF_ERROR_INTERNAL_INTR_R_REG_ADDR, ABR_INTR_BLOCK_RF_NOTIF_INTERNAL_INTR_R_REG_ADDR,
    ABR_INTR_BLOCK_RF_ERROR_INTR_TRIG_R_REG_ADDR, ABR_INTR_BLOCK_RF_NOTIF_INTR_TRIG_R_REG_ADDR, ABR_INTR_BLOCK_RF_ERROR_INTERNAL_INTR_COUNT_R_REG_ADDR,
    ABR_INTR_BLOCK_RF_NOTIF_CMD_DONE_INTR_COUNT_R_REG_ADDR, ABR_INTR_BLOCK_RF_ERROR_INTERNAL_INTR_COUNT_INCR_R_REG_ADDR, ABR_INTR_BLOCK_RF_NOTIF_CMD_DONE_INTR_COUNT_INCR_R_REG_ADDR,
    ABR_MLKEM_NAME_0__REG_ADDR, ABR_MLKEM_NAME_1__REG_ADDR, ABR_MLKEM_VERSION_0__REG_ADDR,
    ABR_MLKEM_VERSION_1__REG_ADDR, ABR_MLKEM_CTRL_REG_ADDR, ABR_MLKEM_STATUS_REG_ADDR,
    ABR_MLKEM_SEED_D_0__REG_ADDR, ABR_MLKEM_SEED_D_1__REG_ADDR, ABR_MLKEM_SEED_D_2__REG_ADDR,
    ABR_MLKEM_SEED_D_3__REG_ADDR, ABR_MLKEM_SEED_D_4__REG_ADDR, ABR_MLKEM_SEED_D_5__REG_ADDR,
    ABR_MLKEM_SEED_D_6__REG_ADDR, ABR_MLKEM_SEED_D_7__REG_ADDR, ABR_MLKEM_SEED_Z_0__REG_ADDR,
    ABR_MLKEM_SEED_Z_1__REG_ADDR, ABR_MLKEM_SEED_Z_2__REG_ADDR, ABR_MLKEM_SEED_Z_3__REG_ADDR,
    ABR_MLKEM_SEED_Z_4__REG_ADDR, ABR_MLKEM_SEED_Z_5__REG_ADDR, ABR_MLKEM_SEED_Z_6__REG_ADDR,
    ABR_MLKEM_SEED_Z_7__REG_ADDR, ABR_MLKEM_SHARED_KEY_0__REG_ADDR, ABR_MLKEM_SHARED_KEY_1__REG_ADDR,
    ABR_MLKEM_SHARED_KEY_2__REG_ADDR, ABR_MLKEM_SHARED_KEY_3__REG_ADDR, ABR_MLKEM_SHARED_KEY_4__REG_ADDR,
    ABR_MLKEM_SHARED_KEY_5__REG_ADDR, ABR_MLKEM_SHARED_KEY_6__REG_ADDR, ABR_MLKEM_SHARED_KEY_7__REG_ADDR,
    ABR_KV_MLKEM_SEED_RD_CTRL_REG_ADDR, ABR_KV_MLKEM_SEED_RD_STATUS_REG_ADDR, ABR_KV_MLKEM_MSG_RD_CTRL_REG_ADDR,
    ABR_KV_MLKEM_MSG_RD_STATUS_REG_ADDR, ABR_KV_MLKEM_SHAREDKEY_WR_CTRL_REG_ADDR, ABR_KV_MLKEM_SHAREDKEY_WR_STATUS_REG_ADDR: return 1'b1;
    default: return 1'b0;
  endcase
endfunction
