// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 Tenstorrent USA, Inc.

= OCAH UART & Log Engine Wrapper
:sectnums:

[#sec-description]
== Description

The OCAH UART & Log Engine Wrapper is a hardware module that integrates an UART 16550 with a Log
Engine. This wrapper is designed to facilitate communication between the UART and the log engine,
allowing for logging capabilities.

[#sec-features]
== Features

The features of this design include:

* An UART 16550
* An optional Log Engine
* Configurable APB4 or AXI4-Lite register interface

[#sec-parameters]
== Parameters and Ports

ifdef::backend-html5[]
The parameters and ports of `uart_log_engine_wrap` are listed in xref:ROOT:rtl-modules-reference/ip/uart_log_engine_wrap/uart_log_engine_wrap.adoc[uart_log_engine_wrap].
endif::backend-html5[]
ifndef::backend-html5[]
The parameters and ports of `uart_log_engine_wrap` are listed in the HTML edition of this manual, under RTL Modules Reference.
endif::backend-html5[]

`LOG_ENGINE_FIFO_DEPTH` must be a power of 2 greater than or equal to 16.

[#sec-registers]
== Registers

The tables below describe the register map and each register in detail.

ifdef::backend-html5[]
++++
include::partial$uart_log_engine_wrap/regs/gen/html/uart_log_engine_wrap.html[]
++++
endif::backend-html5[]

ifdef::backend-pdf[]
include::../regs/gen/adoc/uart_log_engine_wrap.adoc[leveloffset=+1]
endif::backend-pdf[]

[#sec-interrupts]
== Interrupts

TODO

[#sec-programmers-guide]
== Programmer's Guide

TODO
