# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2026 Tenstorrent USA, Inc.
#
# tclint-disable line-length
#
# SMC VC SpyGlass RDC waivers, starting with the FLR cold-domain retention section.

# --- hierarchy-reuse tokens -------------------------------------------------------
# ${PREFIX} re-anchors hierarchical filter fields at the parent instance path. A parent
# run that replays this block predefines PREFIX and apply_prefix before sourcing this
# file; in the block's own run PREFIX is "". ${BLOCKINST} is the containing instance of a
# block-top violation (the design name here, the instance path at the parent).
if { ![info exists PREFIX] } { set PREFIX "" }
if { [info procs apply_prefix] eq "" } {
    proc apply_prefix { filter } {
        set out [string map [list {${PREFIX}} $::PREFIX] $filter]
        if { $::PREFIX eq "" } {
            set bi $::env(DESIGN_NAME)
        } else {
            set bi [string trimright $::PREFIX "/."]
        }
        set out [string map [list {${BLOCKINST}} $bi] $out]
        return $out
    }
}
# ----------------------------------------------------------------------------------

#======================================================================================================================
# FLR cold-domain retention registers: RDC_CORRUPT_OBSERVED into flops that must persist through an FLR event and are therefore reset by cold reset only.
#======================================================================================================================
waive_violation -add {SMC_FLR_RDC_CORRUPT_OBSERVED_9369} -comment {isolate_req_reg is reset by cold reset because it must persist through an FLR event. This flop is only updated by an SMC CPU write; firmware writes ISOLATE_REQ_REG first (otherwise isolation would not take effect), the axil handshake completes, then FLR is triggered. By the time primary reset asserts, there is no active AXI-Lite write into this cold-domain retention flop, so there is no RDC metastability risk and the crossing is safe.} -filter [apply_prefix {(RdcSourceResets:ResetName == "PRIMARY_RESET_N") AND (RdcDestResets:DestResetInfo:ResetObject == "${PREFIX}u_smc_peripherals/u_smc_reset_unit/u_smc_reset_ctrl/stable_cold_rst_no") AND (RdcDestResets:DestResetInfo:ResetObject == "${PREFIX}u_smc_peripherals/u_smc_reset_unit/rst_cold_smc_n") AND (RdcDestResets:DestResetInfo:ResetName == "COLD_RESET_N") AND (RdcDestResets:DestResetInfo:ResetName == "COLD_RESET_N_SMC_CLK") AND ((DestClockInfoList:DestClockInfo:ClockName == "SMCCLK") OR (DestClockInfoList:DestClockInfo:ClockName == "SMUCLK"))  AND (ReasonInfoList:ReasonInfo:ReasonCode == "NO_BLOCKING_METHOD") AND (ReasonInfoList:ReasonInfo:ReasonCodeMsg == "[ERROR] No valid blocking scheme found") AND (SrcObject =~ "${PREFIX}u_smc_peripherals/u_smc_reset_unit/u_reset_unit_reg/*") AND (DestObject == "${PREFIX}u_smc_peripherals/u_smc_reset_unit/u_smc_cool_reset_wrap/isolate_req_reg/Q[31:0]") AND (SrcObjectType == "flop") AND (DestObjectType == "flop") AND (AllSrcResets:SrcResetInfo:ResetObject == "${PREFIX}u_smc_peripherals/u_smc_reset_unit/u_smc_reset_ctrl/rst_primary_no") AND (AllSrcResets:SrcResetInfo:ResetName == "PRIMARY_RESET_N") AND (DestSyncResetInfoList:DestResetInfo:ResetName == "'no-reset'") AND ((SrcClockInfoList:SrcClockInfo:ClockName == "SMCCLK") OR (SrcClockInfoList:SrcClockInfo:ClockName == "SMUCLK"))  AND (ContainerInstance == "${PREFIX}u_smc_peripherals/u_smc_reset_unit") AND (Module == "smc_reset_unit")}] -app { rdc } -tag { RDC_CORRUPT_OBSERVED } -user { nboettcher } -timestamp { 24-06-2026 18:14:54 }
waive_violation -add {SMC_FLR_RDC_CORRUPT_OBSERVED_9385} -comment {isolate_req_smcen_reg is reset by cold reset because it must persist through an FLR event. This flop is only updated by an SMC CPU write; firmware writes the register first, the axil handshake completes, then FLR is triggered. By the time primary reset asserts, there is no active AXI-Lite write into this cold-domain retention flop, so there is no RDC metastability risk and the crossing is safe.} -filter [apply_prefix {(RdcSourceResets:ResetName == "PRIMARY_RESET_N") AND (RdcDestResets:DestResetInfo:ResetObject == "${PREFIX}u_smc_peripherals/u_smc_reset_unit/u_smc_reset_ctrl/stable_cold_rst_no") AND (RdcDestResets:DestResetInfo:ResetObject == "${PREFIX}u_smc_peripherals/u_smc_reset_unit/rst_cold_smc_n") AND (RdcDestResets:DestResetInfo:ResetName == "COLD_RESET_N") AND (RdcDestResets:DestResetInfo:ResetName == "COLD_RESET_N_SMC_CLK") AND ((DestClockInfoList:DestClockInfo:ClockName == "SMCCLK") OR (DestClockInfoList:DestClockInfo:ClockName == "SMUCLK"))  AND (ReasonInfoList:ReasonInfo:ReasonCode == "NO_BLOCKING_METHOD") AND (ReasonInfoList:ReasonInfo:ReasonCodeMsg == "[ERROR] No valid blocking scheme found") AND (SrcObject =~ "${PREFIX}u_smc_peripherals/u_smc_reset_unit/u_reset_unit_reg/*") AND (DestObject == "${PREFIX}u_smc_peripherals/u_smc_reset_unit/u_smc_cool_reset_wrap/isolate_req_smcen_reg/Q[31:0]") AND (SrcObjectType == "flop") AND (DestObjectType == "flop") AND (AllSrcResets:SrcResetInfo:ResetObject == "${PREFIX}u_smc_peripherals/u_smc_reset_unit/u_smc_reset_ctrl/rst_primary_no") AND (AllSrcResets:SrcResetInfo:ResetName == "PRIMARY_RESET_N") AND (DestSyncResetInfoList:DestResetInfo:ResetName == "'no-reset'") AND ((SrcClockInfoList:SrcClockInfo:ClockName == "SMCCLK") OR (SrcClockInfoList:SrcClockInfo:ClockName == "SMUCLK"))  AND (Module == "smc_reset_unit")}] -app { rdc } -tag { RDC_CORRUPT_OBSERVED } -user { nboettcher } -timestamp { 24-06-2026 18:18:53 }
waive_violation -add {SMC_FLR_RDC_CORRUPT_OBSERVED_9392} -comment {flr_set_cnt sets the delay time of the FLR-triggered reset and is reset by cold reset because it must persist through an FLR event. This flop is only updated by an SMC CPU write; firmware writes the register first, the axil handshake completes, then FLR is triggered. By the time primary reset asserts, there is no active AXI-Lite write into this cold-domain retention flop, so there is no RDC metastability risk and the crossing is safe.} -filter [apply_prefix {(RdcSourceResets:ResetName == "PRIMARY_RESET_N") AND (RdcDestResets:DestResetInfo:ResetObject == "${PREFIX}u_smc_peripherals/u_smc_reset_unit/u_smc_reset_ctrl/stable_cold_rst_no") AND (RdcDestResets:DestResetInfo:ResetObject == "${PREFIX}u_smc_peripherals/u_smc_reset_unit/rst_cold_smc_n") AND (RdcDestResets:DestResetInfo:ResetName == "COLD_RESET_N") AND (RdcDestResets:DestResetInfo:ResetName == "COLD_RESET_N_SMC_CLK") AND ((DestClockInfoList:DestClockInfo:ClockName == "SMCCLK") OR (DestClockInfoList:DestClockInfo:ClockName == "SMUCLK"))  AND (ReasonInfoList:ReasonInfo:ReasonCode == "NO_BLOCKING_METHOD") AND (ReasonInfoList:ReasonInfo:ReasonCodeMsg == "[ERROR] No valid blocking scheme found") AND (SrcObject =~ "${PREFIX}u_smc_peripherals/u_smc_reset_unit/u_reset_unit_reg/*") AND (DestObject == "${PREFIX}u_smc_peripherals/u_smc_reset_unit/u_smc_cool_reset_wrap/flr_set_cnt/Q[31:0]") AND (SrcObjectType == "flop") AND (DestObjectType == "flop") AND (AllSrcResets:SrcResetInfo:ResetObject == "${PREFIX}u_smc_peripherals/u_smc_reset_unit/u_smc_reset_ctrl/rst_primary_no") AND (AllSrcResets:SrcResetInfo:ResetName == "PRIMARY_RESET_N") AND (DestSyncResetInfoList:DestResetInfo:ResetName == "'no-reset'") AND ((SrcClockInfoList:SrcClockInfo:ClockName == "SMCCLK") OR (SrcClockInfoList:SrcClockInfo:ClockName == "SMUCLK"))  AND (Module == "smc_reset_unit")}] -app { rdc } -tag { RDC_CORRUPT_OBSERVED } -user { nboettcher } -timestamp { 24-06-2026 18:23:06 }
waive_violation -add {SMC_FLR_RDC_CORRUPT_OBSERVED_9404} -comment {flr_reset_set_cnt sets the delay time of the FLR-triggered reset release and is reset by cold reset because it must persist through an FLR event. This flop is only updated by an SMC CPU write; firmware writes the register first, the axil handshake completes, then FLR is triggered. By the time primary reset asserts, there is no active AXI-Lite write into this cold-domain retention flop, so there is no RDC metastability risk and the crossing is safe.} -filter [apply_prefix {(RdcSourceResets:ResetName == "PRIMARY_RESET_N") AND (RdcDestResets:DestResetInfo:ResetObject == "${PREFIX}u_smc_peripherals/u_smc_reset_unit/u_smc_reset_ctrl/stable_cold_rst_no") AND (RdcDestResets:DestResetInfo:ResetObject == "${PREFIX}u_smc_peripherals/u_smc_reset_unit/rst_cold_smc_n") AND (RdcDestResets:DestResetInfo:ResetName == "COLD_RESET_N") AND (RdcDestResets:DestResetInfo:ResetName == "COLD_RESET_N_SMC_CLK") AND ((DestClockInfoList:DestClockInfo:ClockName == "SMCCLK") OR (DestClockInfoList:DestClockInfo:ClockName == "SMUCLK"))  AND (ReasonInfoList:ReasonInfo:ReasonCode == "NO_BLOCKING_METHOD") AND (ReasonInfoList:ReasonInfo:ReasonCodeMsg == "[ERROR] No valid blocking scheme found") AND (SrcObject =~ "${PREFIX}u_smc_peripherals/u_smc_reset_unit/u_reset_unit_reg/*") AND (DestObject == "${PREFIX}u_smc_peripherals/u_smc_reset_unit/u_smc_cool_reset_wrap/flr_reset_set_cnt/Q[31:0]") AND (SrcObjectType == "flop") AND (DestObjectType == "flop") AND (AllSrcResets:SrcResetInfo:ResetObject == "${PREFIX}u_smc_peripherals/u_smc_reset_unit/u_smc_reset_ctrl/rst_primary_no") AND (AllSrcResets:SrcResetInfo:ResetName == "PRIMARY_RESET_N") AND (DestSyncResetInfoList:DestResetInfo:ResetName == "'no-reset'") AND ((SrcClockInfoList:SrcClockInfo:ClockName == "SMCCLK") OR (SrcClockInfoList:SrcClockInfo:ClockName == "SMUCLK"))  AND (Module == "smc_reset_unit")}] -app { rdc } -tag { RDC_CORRUPT_OBSERVED } -user { nboettcher } -timestamp { 24-06-2026 18:24:37 }
waive_violation -add {SMC_FLR_RDC_CORRUPT_OBSERVED_9376} -comment {isolate_req_smc_reg is reset by cold reset because it must remain asserted through the FLR cool reset after cfg_flr_pf_active sets it. This waiver covers the register-block write path used by SMC CPU firmware to clear the bit after FLR, not the cfg_flr_pf_active set path. By the time primary reset asserts for FLR, there is no active AXI-Lite write into this cold-domain retention flop, so there is no RDC metastability risk for this crossing and the waiver is safe.} -filter [apply_prefix {(RdcSourceResets:ResetName == "PRIMARY_RESET_N") AND (RdcDestResets:DestResetInfo:ResetObject == "${PREFIX}u_smc_peripherals/u_smc_reset_unit/u_smc_reset_ctrl/stable_cold_rst_no") AND (RdcDestResets:DestResetInfo:ResetObject == "${PREFIX}u_smc_peripherals/u_smc_reset_unit/rst_cold_smc_n") AND (RdcDestResets:DestResetInfo:ResetName == "COLD_RESET_N") AND (RdcDestResets:DestResetInfo:ResetName == "COLD_RESET_N_SMC_CLK") AND ((DestClockInfoList:DestClockInfo:ClockName == "SMCCLK") OR (DestClockInfoList:DestClockInfo:ClockName == "SMUCLK"))  AND (ReasonInfoList:ReasonInfo:ReasonCode == "NO_BLOCKING_METHOD") AND (ReasonInfoList:ReasonInfo:ReasonCodeMsg == "[ERROR] No valid blocking scheme found") AND (SrcObject =~ "${PREFIX}u_smc_peripherals/u_smc_reset_unit/u_reset_unit_reg/*") AND (DestObject == "${PREFIX}u_smc_peripherals/u_smc_reset_unit/u_smc_cool_reset_wrap/isolate_req_smc_reg/Q") AND (SrcObjectType == "flop") AND (DestObjectType == "flop") AND (AllSrcResets:SrcResetInfo:ResetObject == "${PREFIX}u_smc_peripherals/u_smc_reset_unit/u_smc_reset_ctrl/rst_primary_no") AND (AllSrcResets:SrcResetInfo:ResetName == "PRIMARY_RESET_N") AND (DestSyncResetInfoList:DestResetInfo:ResetName == "'no-reset'") AND ((SrcClockInfoList:SrcClockInfo:ClockName == "SMCCLK") OR (SrcClockInfoList:SrcClockInfo:ClockName == "SMUCLK"))  AND (Module == "smc_reset_unit")}] -app { rdc } -tag { RDC_CORRUPT_OBSERVED } -user { nboettcher } -timestamp { 24-06-2026 18:32:24 }
# isolate_req_pinen_reg is the fifth register of the same retention set (Section 4.9 of the reset spec): it is
# written only through the same AXI-Lite external-register path, but it carries no async reset (cleared
# synchronously by cold reset only while isolate_req_pin is low), so the sibling waivers above, which key on the
# COLD destination reset objects, do not match it.
waive_violation -add {SMC_FLR_RDC_CORRUPT_OBSERVED_ISOLATE_REQ_PINEN} -comment {isolate_req_pinen_reg persists through FLR and cool reset (synchronous cold clear gated by isolate_req_pin low, no async reset) and is only updated by an SMC CPU write through the reset-unit register block; firmware writes ISOLATE_REQ_PINEN_REG first, the axil handshake completes, then FLR is triggered. By the time primary reset asserts there is no active AXI-Lite write into this retention register, so there is no RDC metastability risk and the crossing is safe (same disposition as the four sibling registers above).} -filter [apply_prefix {(RdcSourceResets:ResetName == "PRIMARY_RESET_N") AND (SrcObject =~ "${PREFIX}u_smc_peripherals/u_smc_reset_unit/u_reset_unit_reg/*") AND (RdcDestResets:DestResetInfo:ResetName == "'no-reset'") AND (DestSyncResetInfoList:DestResetInfo:ResetName == "COLD_RESET_N_SMC_CLK") AND (DestObject =~ "${PREFIX}u_smc_peripherals/u_smc_reset_unit/u_smc_cool_reset_wrap/isolate_req_pinen_reg/Q*")}] -app { rdc } -tag { RDC_CORRUPT_OBSERVED } -user { nbetik } -timestamp { 17-09-2026 11:44:06 }

# waive_violation -add {SMC_RDC_CORRUPT_OBSERVED_72174}  -comment {Dest 'no-reset' flop}  -filter [apply_prefix {(ReasonInfoList:ReasonInfo:ReasonCode == "NO_BLOCKING_METHOD") AND (ReasonInfoList:ReasonInfo:ReasonCodeMsg == "[ERROR] No valid blocking scheme found") AND (RdcDestResets:DestResetInfo:ResetName == "'no-reset'") AND (SrcObjectType == "flop") AND (DestObjectType == "flop")}]  -app { rdc } -tag { RDC_CORRUPT_OBSERVED } -user { nboettcher } -timestamp { 17-04-2026 14:31:41 }
waive_violation -add {SMC_RDC_CLOCK_CORRUPT_OBSERVED_74685} -comment {The enable to the clock gater could go meta stable only when primary_reset is asserted, however the whole SMU will be reset by primary_reset so this does not create a risk.} -filter [apply_prefix {(RdcSourceResets:ResetName == "PRIMARY_RESET_N") AND (RdcDestResets:DestResetInfo:ResetName == "'no-reset'") AND ((DestClockInfoList:DestClockInfo:ClockName == "SMCCLK") OR (DestClockInfoList:DestClockInfo:ClockName == "SMUCLK")) AND (ReasonInfoList:ReasonInfo:ReasonCode == "NO_BLOCKING_METHOD") AND (ReasonInfoList:ReasonInfo:ReasonCodeMsg == "[ERROR] No valid blocking scheme found") AND (DestObject =~ "*/u_clk_gater/u_clkgater/d0nt_clkgate/ECK") AND ((SrcObjectType == "flop") OR (SrcObjectType == "library-cell")) AND (DestObjectType == "clock-gating-cell") AND (AllSrcResets:SrcResetInfo:ResetName == "PRIMARY_RESET_N")}] -app { rdc } -tag { RDC_CLOCK_CORRUPT_OBSERVED } -user { nboettcher } -timestamp { 30-04-2026 22:16:45 }
waive_violation -add {SMC_RDC_CLOCK_CORRUPT_OBSERVED_75247} -comment {The enable to the clock gater could go meta stable only when primary_reset is asserted, however the whole SMU will be reset by primary_reset so this does not create a risk.} -filter [apply_prefix {(RdcSourceResets:ResetName == "PRIMARY_RESET_N") AND (RdcDestResets:DestResetInfo:ResetName == "'no-reset'") AND ((DestClockInfoList:DestClockInfo:ClockName == "SMCCLK") OR (DestClockInfoList:DestClockInfo:ClockName == "SMUCLK")) AND (ReasonInfoList:ReasonInfo:ReasonCode == "NO_BLOCKING_METHOD") AND (ReasonInfoList:ReasonInfo:ReasonCodeMsg == "[ERROR] No valid blocking scheme found") AND (DestObject =~ "*/u_axi_clk_gater/d0nt_clkgate/ECK") AND ((SrcObjectType == "flop") OR (SrcObjectType == "library-cell")) AND (DestObjectType == "clock-gating-cell") AND (AllSrcResets:SrcResetInfo:ResetName == "PRIMARY_RESET_N")}] -app { rdc } -tag { RDC_CLOCK_CORRUPT_OBSERVED } -user { nboettcher } -timestamp { 30-04-2026 22:20:51 }
waive_violation -add {SMC_RDC_CLOCK_CORRUPT_OBSERVED_75219} -comment {The enable to the clock gater could go meta stable only when primary_reset is asserted, however the whole SMU will be reset by primary_reset so this does not create a risk.} -filter [apply_prefix {(RdcSourceResets:ResetName == "PRIMARY_RESET_N") AND (RdcDestResets:DestResetInfo:ResetName == "'no-reset'") AND (ReasonInfoList:ReasonInfo:ReasonCode == "NO_BLOCKING_METHOD") AND (ReasonInfoList:ReasonInfo:ReasonCodeMsg == "[ERROR] No valid blocking scheme found") AND (DestObject =~ "*/u_clkgater/d0nt_clkgate/ECK") AND ((SrcObjectType == "flop") OR (SrcObjectType == "library-cell")) AND (DestObjectType == "clock-gating-cell") AND (AllSrcResets:SrcResetInfo:ResetName == "PRIMARY_RESET_N")}] -app { rdc } -tag { RDC_CLOCK_CORRUPT_OBSERVED } -user { nboettcher } -timestamp { 30-04-2026 22:22:08 }
waive_violation -add {SMC_RDC_CLOCK_CORRUPT_OBSERVED_94722} -comment {The enable to the clock gater could go meta stable only when primary_reset is asserted, however the whole SMU will be reset by primary_reset so this does not create a risk.} -filter [apply_prefix {(ReasonInfoList:ReasonInfo:ReasonCode == "NO_BLOCKING_METHOD") AND (ReasonInfoList:ReasonInfo:ReasonCodeMsg == "[ERROR] No valid blocking scheme found") AND (RdcSourceResets:ResetName == "PRIMARY_RESET_N") AND (DestObject =~ "*/u_clk0_gate/d0nt_clkgate/ECK") AND (RdcDestResets:DestResetInfo:ResetName == "'no-reset'") AND (DestClockInfoList:DestClockInfo:ClockName == "PERIPHERALCLK") AND ((SrcObjectType == "flop") OR (SrcObjectType == "library-cell")) AND (DestObjectType == "clock-gating-cell") AND (AllSrcResets:SrcResetInfo:ResetName == "PRIMARY_RESET_N") AND (DestSyncResetInfoList:DestResetInfo:ResetName == "'no-reset'") AND (SrcClockInfoList:SrcClockInfo:ClockName == "PERIPHERALCLK") AND (Module == "prim_ag_clk_mux")}] -app { rdc } -tag { RDC_CLOCK_CORRUPT_OBSERVED } -user { nboettcher } -timestamp { 30-04-2026 22:42:46 }
waive_violation -add {SMC_RDC_CLOCK_CORRUPT_OBSERVED_95309} -comment {The enable to the clock gater could go meta stable only when primary_reset is asserted, however the whole SMU will be reset by primary_reset so this does not create a risk.} -filter [apply_prefix {(ReasonInfoList:ReasonInfo:ReasonCode == "NO_BLOCKING_METHOD") AND (ReasonInfoList:ReasonInfo:ReasonCodeMsg == "[ERROR] No valid blocking scheme found") AND (RdcSourceResets:ResetName == "PRIMARY_RESET_N") AND (DestObject =~ "*/u_tel_clk_smc_gater/d0nt_clkgate/ECK") AND (RdcDestResets:DestResetInfo:ResetName == "'no-reset'") AND ((DestClockInfoList:DestClockInfo:ClockName == "SMCCLK") OR (DestClockInfoList:DestClockInfo:ClockName == "SMUCLK")) AND ((SrcObjectType == "flop") OR (SrcObjectType == "library-cell")) AND (DestObjectType == "clock-gating-cell") AND (AllSrcResets:SrcResetInfo:ResetName == "PRIMARY_RESET_N") AND (DestSyncResetInfoList:DestResetInfo:ResetName == "'no-reset'") AND (Module == "smc")}] -app { rdc } -tag { RDC_CLOCK_CORRUPT_OBSERVED } -user { nboettcher } -timestamp { 30-04-2026 22:43:41 }
waive_violation -add {SMC_RDC_CLOCK_CORRUPT_OBSERVED_94723} -comment {The enable to the clock gater could go meta stable only when primary_reset is asserted, however the whole SMU will be reset by primary_reset so this does not create a risk.} -filter [apply_prefix {(ReasonInfoList:ReasonInfo:ReasonCode == "NO_BLOCKING_METHOD") AND (ReasonInfoList:ReasonInfo:ReasonCodeMsg == "[ERROR] No valid blocking scheme found") AND (RdcSourceResets:ResetName == "PRIMARY_RESET_N") AND (DestObject =~ "*/u_clk1_gate/d0nt_clkgate/ECK") AND (RdcDestResets:DestResetInfo:ResetName == "'no-reset'") AND (DestClockInfoList:DestClockInfo:ClockName == "REFCLK") AND ((SrcObjectType == "flop") OR (SrcObjectType == "library-cell")) AND (DestObjectType == "clock-gating-cell") AND (DestSyncResetInfoList:DestResetInfo:ResetName == "'no-reset'") AND (Module == "prim_ag_clk_mux")}] -app { rdc } -tag { RDC_CLOCK_CORRUPT_OBSERVED } -user { nboettcher } -timestamp { 30-04-2026 22:44:38 }
waive_violation -add {RDC_CLOCK_CORRUPT_OBSERVED_47111} -comment {The enable to the clock gater can go meta stable only when AVS_CLK_DIV_RESET_N (tied to powergood_stable) is asserted, however the whole SMU will be in reset if powergood_stable deasserts so this does not create a risk.} -filter [apply_prefix {(ReasonInfoList:ReasonInfo:ReasonCode == "NO_BLOCKING_METHOD") AND (ReasonInfoList:ReasonInfo:ReasonCodeMsg == "[ERROR] No valid blocking scheme found") AND (SrcObject == "${PREFIX}u_smc_peripherals/u_avsbus_controller/u_clk_div/u_postdiv_mux/gen_sync_clk0_not_selected.sync_clk0/d0nt_wrap_sync/Q") AND (RdcSourceResets:ResetName == "AVS_CLK_DIV_RESET_N") AND (DestObject == "${PREFIX}u_smc_peripherals/u_avsbus_controller/u_clk_div/u_postdiv_mux/u_clk0_gate/d0nt_clkgate/ECK") AND (RdcDestResets:DestResetInfo:ResetName == "'no-reset'") AND (DestClockInfoList:DestClockInfo:ClockName == "AVS_CLKMUX_OUTPUT_FROM_PERIPHERALCLK") AND (DestClockInfoList:DestClockInfo:ClockName == "AVS_CLKMUX_OUTPUT_FROM_REFCLK") AND (DestClockInfoList:DestClockInfo:ClockObject == "${PREFIX}u_smc_peripherals/u_avsbus_controller/u_refclk_apbclk_mux/u_clk1_gate/clk_o") AND (DestClockInfoList:DestClockInfo:ClockObject == "${PREFIX}u_smc_peripherals/u_avsbus_controller/u_refclk_apbclk_mux/u_clk0_gate/clk_o") AND ((SrcObjectType == "flop") OR (SrcObjectType == "library-cell")) AND (DestObjectType == "clock-gating-cell") AND (AllSrcResets:SrcResetInfo:ResetObject == "${PREFIX}u_smc_peripherals/u_avsbus_controller/u_clk_div/u_reset_sync/gen_rst_sync_stage[5].u_sync_dffr/d0nt_dffr/Q") AND (AllSrcResets:SrcResetInfo:ResetName == "AVS_CLK_DIV_RESET_N") AND (DestSyncResetInfoList:DestResetInfo:ResetName == "'no-reset'") AND (SrcClockInfoList:SrcClockInfo:ClockName == "AVS_CLKMUX_OUTPUT_FROM_PERIPHERALCLK") AND (SrcClockInfoList:SrcClockInfo:ClockName == "AVS_CLKMUX_OUTPUT_FROM_REFCLK") AND (SrcClockInfoList:SrcClockInfo:ClockObject == "${PREFIX}u_smc_peripherals/u_avsbus_controller/u_refclk_apbclk_mux/u_clk1_gate/clk_o") AND (SrcClockInfoList:SrcClockInfo:ClockObject == "${PREFIX}u_smc_peripherals/u_avsbus_controller/u_refclk_apbclk_mux/u_clk0_gate/clk_o") AND (Module == "prim_ag_clk_mux")}] -app { rdc } -tag { RDC_CLOCK_CORRUPT_OBSERVED } -user { danielkim } -timestamp { 19-06-2026 12:04:21 }
waive_violation -add {SMC_RDC_CLOCK_CORRUPT_OBSERVED_47112} -comment {The enable to the clock gater can go meta stable only when AVS_CLK_DIV_RESET_N (tied to powergood_stable) is asserted, however the whole SMU will be in reset if powergood_stable deasserts so this does not create a risk.} -filter [apply_prefix {(ReasonInfoList:ReasonInfo:ReasonCode == "NO_BLOCKING_METHOD") AND (ReasonInfoList:ReasonInfo:ReasonCodeMsg == "[ERROR] No valid blocking scheme found") AND (SrcObject == "${PREFIX}u_smc_peripherals/u_avsbus_controller/u_clk_div/u_postdiv_mux/gen_sync_clk1_selected.sync_clk1/d0nt_wrap_sync/Q") AND (RdcSourceResets:ResetName == "AVS_CLK_DIV_RESET_N") AND (DestObject == "${PREFIX}u_smc_peripherals/u_avsbus_controller/u_clk_div/u_postdiv_mux/u_clk1_gate/d0nt_clkgate/ECK") AND (RdcDestResets:DestResetInfo:ResetName == "'no-reset'") AND (DestClockInfoList:DestClockInfo:ClockName == "AVS_DIV_CLK_Q_FROM_REFCLK") AND (DestClockInfoList:DestClockInfo:ClockName == "AVS_DIV_CLK_Q_FROM_PERIPHERALCLK") AND (DestClockInfoList:DestClockInfo:ClockObject == "${PREFIX}u_smc_peripherals/u_avsbus_controller/u_clk_div/div_clk/Q") AND ((SrcObjectType == "flop") OR (SrcObjectType == "library-cell")) AND (DestObjectType == "clock-gating-cell") AND (AllSrcResets:SrcResetInfo:ResetObject == "${PREFIX}u_smc_peripherals/u_avsbus_controller/u_clk_div/u_reset_sync/gen_rst_sync_stage[5].u_sync_dffr/d0nt_dffr/Q") AND (AllSrcResets:SrcResetInfo:ResetName == "AVS_CLK_DIV_RESET_N") AND (DestSyncResetInfoList:DestResetInfo:ResetName == "'no-reset'") AND (SrcClockInfoList:SrcClockInfo:ClockName == "AVS_DIV_CLK_Q_FROM_REFCLK") AND (SrcClockInfoList:SrcClockInfo:ClockName == "AVS_DIV_CLK_Q_FROM_PERIPHERALCLK") AND (SrcClockInfoList:SrcClockInfo:ClockObject == "${PREFIX}u_smc_peripherals/u_avsbus_controller/u_clk_div/div_clk/Q") AND (Module == "prim_ag_clk_mux")}] -app { rdc } -tag { RDC_CLOCK_CORRUPT_OBSERVED } -user { danielkim } -timestamp { 19-06-2026 12:05:47 }
waive_violation -add {SMC_RDC_CLOCK_CORRUPT_OBSERVED_47115} -comment {The enable to the clock gater can go meta stable only when AVS_CLK_DIV_RESET_N (tied to primary_reset_n) is asserted, however the whole SMU will be in reset by primary_reset_n so this does not create a risk.} -filter [apply_prefix {(ReasonInfoList:ReasonInfo:ReasonCode == "NO_BLOCKING_METHOD") AND (ReasonInfoList:ReasonInfo:ReasonCodeMsg == "[ERROR] No valid blocking scheme found") AND (SrcObject == "${PREFIX}u_smc_peripherals/u_avsbus_controller/u_avsbus_controller_reg_inst/field_storage.AVS_CFG_1.TURN_OFF_ALL_PREMUX_CLOCKS.value") AND (RdcSourceResets:ResetName == "AVS_APB_CLK_RESET_N") AND (DestObject == "${PREFIX}u_smc_peripherals/u_avsbus_controller/u_apbclk_clkgate/d0nt_clkgate/ECK") AND (RdcDestResets:DestResetInfo:ResetName == "'no-reset'") AND (DestClockInfoList:DestClockInfo:ClockName == "PERIPHERALCLK")  AND ((SrcObjectType == "flop") OR (SrcObjectType == "library-cell")) AND (DestObjectType == "clock-gating-cell") AND (AllSrcResets:SrcResetInfo:ResetObject == "${PREFIX}u_smc_peripherals/u_avsbus_controller/u_apb_clk_reset_sync/gen_rst_sync_stage[5].u_sync_dffr/d0nt_dffr/Q") AND (AllSrcResets:SrcResetInfo:ResetName == "AVS_APB_CLK_RESET_N") AND (DestSyncResetInfoList:DestResetInfo:ResetName == "'no-reset'") AND (SrcClockInfoList:SrcClockInfo:ClockName == "PERIPHERALCLK")  AND (Module == "avsbus_controller")}] -app { rdc } -tag { RDC_CLOCK_CORRUPT_OBSERVED } -user { danielkim } -timestamp { 19-06-2026 12:06:49 }
waive_violation -add {SMC_DFD_RDC_CLOCK_CORRUPT_IPX_CLK_RST_CTRL} -comment {DFD generic_ipx_clk_rst_ctrl clock gaters (dst_sink, dst_crc, funnel, cla, tnif): the synchronized PRIMARY reset feeds the functional clock-enable term combinationally, so the enable can be disturbed only while PRIMARY asserts, when the DFD IP and every consumer of its gated clocks are held in that same reset.} -filter [apply_prefix {((RdcSourceResets:ResetName == "PRIMARY_RESET_N") OR (RdcSourceResets:ResetName == "PRIMARY_RESET_N_SMC_CLK")) AND (RdcDestResets:DestResetInfo:ResetName == "'no-reset'") AND (ReasonInfoList:ReasonInfo:ReasonCode == "NO_BLOCKING_METHOD") AND (DestObjectType == "clock-gating-cell") AND (SrcObject =~ "${PREFIX}u_smc_peripherals/u_smc_reset_unit/*") AND (DestObject =~ "${PREFIX}u_smc_base/u_internal_regs/u_smc_dfd_wrap/u_dfd_top/clk_rst_wrapper/*ipx_clk_rst_ctrl/u_clk_gater/u_clkgater/d0nt_clkgate/ECK")}] -app { rdc } -tag { RDC_CLOCK_CORRUPT_OBSERVED } -user { nbetik } -timestamp { 17-09-2026 18:15:09 }
waive_violation -add {SMC_CPU_RDC_CLOCK_CORRUPT_DEBUG_CLOCK_GATE_ENABLE} -comment {smc_4core_cpu debug_clock_gate: the enable flop clock_en is asynchronously reset to 1 by rst_debug_ni, the reset of every consumer of the gated debug clock, so the reset event only ungates the clock; the enable change is absorbed by the glitch-free gater and the consumers are held in that same reset.} -filter [apply_prefix {(RdcDestResets:DestResetInfo:ResetName == "'no-reset'") AND (ReasonInfoList:ReasonInfo:ReasonCode == "NO_BLOCKING_METHOD") AND (DestObjectType == "clock-gating-cell") AND (SrcObject =~ "${PREFIX}u_smc_cpu_wrapper/u_smc_cpu/clock_en/*") AND (DestObject =~ "${PREFIX}u_smc_cpu_wrapper/u_smc_cpu/debug_clock_gate/*/ECK")}] -app { rdc } -tag { RDC_CLOCK_CORRUPT_OBSERVED } -user { nbetik } -timestamp { 17-09-2026 18:15:09 }
waive_violation -add {SMC_RDC_CORRUPT_OBSERVED_9423} -comment {The axi_isolate state registers can go meta stable when cluster_uncore_reset is asserted, however uncore reset always follows the cluster isolate/drain handshake or a warm/WDT reset that holds the isolate in its safe state, so this does not create a risk} -filter [apply_prefix {(RdcSourceResets:ResetName == "CLUSTER_UNCORE_RESET_N") AND (RdcDestResets:DestResetInfo:ResetObject == "${PREFIX}u_smc_peripherals/u_smc_reset_unit/u_smc_reset_ctrl/rst_primary_no") AND (RdcDestResets:DestResetInfo:ResetObject == "${PREFIX}u_smc_peripherals/u_smc_reset_unit/rst_primary_smc_clk_no") AND (RdcDestResets:DestResetInfo:ResetName == "PRIMARY_RESET_N") AND (RdcDestResets:DestResetInfo:ResetName == "PRIMARY_RESET_N_SMC_CLK") AND ((DestClockInfoList:DestClockInfo:ClockName == "SMCCLK") OR (DestClockInfoList:DestClockInfo:ClockName == "SMUCLK"))  AND (ReasonInfoList:ReasonInfo:ReasonCode == "NO_BLOCKING_METHOD") AND (ReasonInfoList:ReasonInfo:ReasonCodeMsg == "[ERROR] No valid blocking scheme found") AND (SrcObject =~ "${PREFIX}u_smc_cpu_wrapper/u_smc_cpu/cluster_boundary_isolate_shift/Q[*]") AND ((DestObject =~ "${PREFIX}u_smc_cpu_wrapper/u_smc_cpu/u_mmio_axi_isolate/i_axi_isolate/state_a*_q/Q[1:0]") OR (DestObject =~ "${PREFIX}u_smc_cpu_wrapper/u_smc_cpu/u_mmio_axi_isolate/g_terminate.sel_a*_q/Q")) AND (SrcObjectType == "flop") AND (DestObjectType == "flop") AND (AllSrcResets:SrcResetInfo:ResetObject == "${PREFIX}u_smc_peripherals/u_smc_reset_unit/u_smc_reset_ctrl/rst_warm_no") AND (AllSrcResets:SrcResetInfo:ResetObject == "${PREFIX}u_smc_peripherals/u_smc_reset_unit/rst_warm_smc_clk_no") AND (AllSrcResets:SrcResetInfo:ResetObject == "${PREFIX}u_smc_cpu_wrapper/u_smc_cpu_ctrl_wrap/cluster_uncore_reset_n_n0_scan_o") AND (AllSrcResets:SrcResetInfo:ResetName == "WARM_RESET_N") AND (AllSrcResets:SrcResetInfo:ResetName == "WARM_RESET_N_SMC_CLK") AND (AllSrcResets:SrcResetInfo:ResetName == "CLUSTER_UNCORE_RESET_N") AND (DestSyncResetInfoList:DestResetInfo:ResetName == "'no-reset'") AND ((SrcClockInfoList:SrcClockInfo:ClockName == "SMCCLK") OR (SrcClockInfoList:SrcClockInfo:ClockName == "SMUCLK"))  AND (Module == "smc_4core_cpu")}] -app { rdc } -tag { RDC_CORRUPT_OBSERVED } -user { danielkim } -timestamp { 22-06-2026 12:36:59 }
waive_violation -add {SMC_RDC_CORRUPT_OBSERVED_9421} -comment {The axi_isolate state registers can go meta stable when cluster_uncore_reset is asserted, however uncore reset always follows the cluster isolate/drain handshake or a warm/WDT reset that holds the isolate in its safe state, so this does not create a risk} -filter [apply_prefix {(RdcSourceResets:ResetName == "CLUSTER_UNCORE_RESET_N") AND (RdcDestResets:DestResetInfo:ResetObject == "${PREFIX}u_smc_peripherals/u_smc_reset_unit/u_smc_reset_ctrl/rst_primary_no") AND (RdcDestResets:DestResetInfo:ResetObject == "${PREFIX}u_smc_peripherals/u_smc_reset_unit/rst_primary_smc_clk_no") AND (RdcDestResets:DestResetInfo:ResetName == "PRIMARY_RESET_N") AND (RdcDestResets:DestResetInfo:ResetName == "PRIMARY_RESET_N_SMC_CLK") AND ((DestClockInfoList:DestClockInfo:ClockName == "SMCCLK") OR (DestClockInfoList:DestClockInfo:ClockName == "SMUCLK"))  AND (ReasonInfoList:ReasonInfo:ReasonCode == "NO_BLOCKING_METHOD") AND (ReasonInfoList:ReasonInfo:ReasonCodeMsg == "[ERROR] No valid blocking scheme found") AND (SrcObject =~ "${PREFIX}u_smc_cpu_wrapper/u_smc_cpu/cluster_boundary_isolate_shift/Q[*]") AND (DestObject =~ "${PREFIX}u_smc_cpu_wrapper/u_smc_cpu/u_l2_frontend_axi_isolate/i_axi_isolate/state_a*_q/Q[1:0]") AND (SrcObjectType == "flop") AND (DestObjectType == "flop") AND (AllSrcResets:SrcResetInfo:ResetObject == "${PREFIX}u_smc_peripherals/u_smc_reset_unit/u_smc_reset_ctrl/rst_warm_no") AND (AllSrcResets:SrcResetInfo:ResetObject == "${PREFIX}u_smc_peripherals/u_smc_reset_unit/rst_warm_smc_clk_no") AND (AllSrcResets:SrcResetInfo:ResetObject == "${PREFIX}u_smc_cpu_wrapper/u_smc_cpu_ctrl_wrap/cluster_uncore_reset_n_n0_scan_o") AND (AllSrcResets:SrcResetInfo:ResetName == "WARM_RESET_N") AND (AllSrcResets:SrcResetInfo:ResetName == "WARM_RESET_N_SMC_CLK") AND (AllSrcResets:SrcResetInfo:ResetName == "CLUSTER_UNCORE_RESET_N") AND (DestSyncResetInfoList:DestResetInfo:ResetName == "'no-reset'") AND ((SrcClockInfoList:SrcClockInfo:ClockName == "SMCCLK") OR (SrcClockInfoList:SrcClockInfo:ClockName == "SMUCLK"))  AND (Module == "smc_4core_cpu")}] -app { rdc } -tag { RDC_CORRUPT_OBSERVED } -user { danielkim } -timestamp { 22-06-2026 12:43:39 }
waive_violation -add {SMC_RDC_ON_CDC_DISABLED} -comment {On purpose, covered by CDC analysis} -app { rdc } -tag { RDC_ON_CDC_DISABLED } -user { nboettcher } -timestamp { 24-06-2026 18:33:29 }

# =====================================================================================
# RDC_CORRUPT WAIVERS
# These can only see the flop directly affected by an async-reset metastability event
# Downstream fanout may be affected and MUST BE AUDITED / RESOLVED
# =====================================================================================

waive_violation -add {SMC_RDC_CORRUPT_AUTOHS_SAME_RESET_SYNC_STYLE} -comment {prim_sync_data_autohs state flop with synchronous reset on the same net as its sync cell's async reset; reset holds D low from the second edge and is held for the synchronizer window.} -filter [apply_prefix {(Module == "prim_sync_data_autohs") AND (RdcDestResets:DestResetInfo:ResetName == "'no-reset'") AND (((RdcSourceResets:ResetName == "AVS_APB_CLK_RESET_N") AND (DestSyncResetInfoList:DestResetInfo:ResetName == "AVS_APB_CLK_RESET_N")) OR ((RdcSourceResets:ResetName == "AVS_CLK_RESET_N") AND (DestSyncResetInfoList:DestResetInfo:ResetName == "AVS_CLK_RESET_N")) OR ((RdcSourceResets:ResetName == "AVS_PRE_DIV_CLK_RESET_N") AND (DestSyncResetInfoList:DestResetInfo:ResetName == "AVS_PRE_DIV_CLK_RESET_N")) OR ((RdcSourceResets:ResetName == "COLD_RESET_N_SMC_CLK") AND (DestSyncResetInfoList:DestResetInfo:ResetName == "COLD_RESET_N_SMC_CLK")) OR ((RdcSourceResets:ResetName == "COLD_RESET_N_REF_CLK") AND (DestSyncResetInfoList:DestResetInfo:ResetName == "COLD_RESET_N_REF_CLK")) OR ((RdcSourceResets:ResetName == "PRIMARY_RESET_N_SMC_CLK") AND (DestSyncResetInfoList:DestResetInfo:ResetName == "PRIMARY_RESET_N_SMC_CLK")) OR ((RdcSourceResets:ResetName == "PRIMARY_RESET_N_PERIPH_CLK") AND (DestSyncResetInfoList:DestResetInfo:ResetName == "PRIMARY_RESET_N_PERIPH_CLK")))}] -app { rdc } -tag { RDC_CORRUPT_OBSERVED } -user { nbetik } -timestamp { 16-09-2026 12:50:22 }
waive_violation -add {SMC_RDC_CORRUPT_SYNC3_PULSE_DEST_RESYNCED_SRC_RESET} -comment {prim_sync3_pulse_dest edge flops synchronously reset by the re-synchronized source reset that also async-resets their sync cell; D held low from the second edge, held 3 destination clocks, output gated during reset.} -filter [apply_prefix {(Module == "prim_sync3_pulse_dest") AND (RdcDestResets:DestResetInfo:ResetName == "'no-reset'") AND (DestObject =~ "*/toggle_synced_d*") AND ((SrcObject =~ "*/u_sync3/*") OR (SrcObject =~ "*/u_src_reset_n_sync/*"))}] -app { rdc } -tag { RDC_CORRUPT_OBSERVED } -user { nbetik } -timestamp { 16-09-2026 12:50:22 }
waive_violation -add {SMC_CPU_RDC_CORRUPT_CLUSTER_SYNC_RESET_APPLICATION} -comment {Cluster reset net applied as synchronous reset; destination is forced from the second edge and held.} -filter [apply_prefix {(RdcDestResets:DestResetInfo:ResetName == "'no-reset'") AND (DestObject =~ "${PREFIX}u_smc_cpu_wrapper/u_smc_cpu/u_digital_top/*") AND ((SrcObject == "${PREFIX}u_smc_cpu_wrapper/u_smc_cpu_ctrl_wrap/cluster_uncore_reset_n_n0_scan_o/Q") OR (SrcObject =~ "${PREFIX}u_smc_cpu_wrapper/u_smc_cpu_ctrl_wrap/core_reset_n_n0_scan_o/Q*") OR (SrcObject == "${PREFIX}u_smc_cpu_wrapper/u_smc_cpu/init_mem_complete/Q") OR (SrcObject =~ "${PREFIX}u_smc_cpu_wrapper/u_smc_cpu/u_digital_top/chipyard_prcictrl_domain/resetSynchronizer/*_reset_catcher/io_sync_reset_chain/output_chain/u_prim_flop_3sync_r/d0nt_wrap_sync/Q"))}] -app { rdc } -tag { RDC_CORRUPT_OBSERVED } -user { nbetik } -timestamp { 16-09-2026 12:50:22 }

# NOTE REVIEW whenever the chipyard cluster is regenerated:
# the filter cannot separate sync-reset flops from never-reset payload, so a new unqualified
# never-reset register would be waived silently.
waive_violation -add {SMC_CPU_RDC_CORRUPT_CLUSTER_CONTAINED_SOURCE_RESET} -comment {All source resets imply the cluster uncore/core reset through the async AND tree; destination sync reset is active on the same edge and held.} -filter [apply_prefix {(RdcDestResets:DestResetInfo:ResetName == "'no-reset'") AND (DestObject =~ "${PREFIX}u_smc_cpu_wrapper/u_smc_cpu/u_digital_top/*") AND ((SrcObject =~ "${PREFIX}u_smc_cpu_wrapper/u_*") OR (SrcObject =~ "${PREFIX}u_smc_cpu_wrapper/u_tilelink_to_rom_memory_convert/*") OR (SrcObject =~ "${PREFIX}u_smc_peripherals/*") OR (SrcObject =~ "${PREFIX}u_smc_base/*") OR (SrcObject =~ "${PREFIX}u_smc_cpu_wrapper/u_smc_cpu/u_l2_frontend_axi_isolate/*") OR (SrcObject =~ "${PREFIX}u_smc_cpu_wrapper/u_smc_cpu/u_mmio_axi_isolate/*") OR (SrcObject =~ "${PREFIX}u_smc_cpu_wrapper/u_smc_cpu/u_digital_top/plic_domain/*") OR (SrcObject =~ "${PREFIX}u_smc_cpu_wrapper/u_smc_cpu/u_digital_top/clint_domain/*") OR (SrcObject =~ "${PREFIX}u_smc_cpu_wrapper/u_smc_cpu/u_digital_top/wdtClockDomainWrapper*/*")) AND ((RdcSourceResets:ResetName == "PRIMARY_RESET_N") OR (RdcSourceResets:ResetName == "PRIMARY_RESET_N_SMC_CLK") OR (RdcSourceResets:ResetName == "PRIMARY_RESET_N_REF_CLK") OR (RdcSourceResets:ResetName == "PRIMARY_RESET_N_PERIPH_CLK") OR (RdcSourceResets:ResetName == "COLD_RESET_N") OR (RdcSourceResets:ResetName == "COLD_RESET_N_SMC_CLK") OR (RdcSourceResets:ResetName == "COLD_RESET_N_REF_CLK") OR (RdcSourceResets:ResetName == "POWERGOOD_STABLE_N") OR (RdcSourceResets:ResetName == "WARM_RESET_N") OR (RdcSourceResets:ResetName == "WARM_RESET_N_SMC_CLK") OR (RdcSourceResets:ResetName == "WDT_RESET_N") OR (RdcSourceResets:ResetName == "WDT_RESET_N_SMC_CLK") OR (RdcSourceResets:ResetName == "FUSE_RESET_N") OR (RdcSourceResets:ResetName == "CLUSTER_UNCORE_RESET_N") OR (RdcSourceResets:ResetName == "CORE_RESET_0_N") OR (RdcSourceResets:ResetName == "CORE_RESET_1_N") OR (RdcSourceResets:ResetName == "CORE_RESET_2_N") OR (RdcSourceResets:ResetName == "CORE_RESET_3_N") OR (RdcSourceResets:ResetName == "MEM_INIT_DONE_N"))}] -app { rdc } -tag { RDC_CORRUPT_OBSERVED } -user { nbetik } -timestamp { 16-09-2026 12:50:22 }

waive_violation -add {SMC_CPU_RDC_CORRUPT_DM_DEBUG_DOMAIN_INTERNAL} -comment {Debug-module inner registers cleared by dmactive-low derived from the same io_debug_reset that async-clears the source sync cells; AsyncQueue payload pointer-qualified.} -filter [apply_prefix {(RdcSourceResets:ResetName == "DEBUG_RESET_N") AND (RdcDestResets:DestResetInfo:ResetName == "'no-reset'") AND (SrcObject =~ "${PREFIX}u_smc_cpu_wrapper/u_smc_cpu/u_digital_top/tlDM/dmInner/*") AND ((DestObject =~ "${PREFIX}u_smc_cpu_wrapper/u_smc_cpu/u_digital_top/tlDM/dmInner/dmInner/ctrlStateReg/Q*") OR (DestObject =~ "${PREFIX}u_smc_cpu_wrapper/u_smc_cpu/u_digital_top/tlDM/dmInner/dmInner/haltedBitRegs/Q*") OR (DestObject =~ "${PREFIX}u_smc_cpu_wrapper/u_smc_cpu/u_digital_top/tlDM/dmInner/dmInner/resumeReqRegs/Q*") OR (DestObject =~ "${PREFIX}u_smc_cpu_wrapper/u_smc_cpu/u_digital_top/tlDM/dmInner/dmInner/haveResetBitRegs/Q*") OR (DestObject =~ "${PREFIX}u_smc_cpu_wrapper/u_smc_cpu/u_digital_top/tlDM/dmInner/dmInner/selectedHartReg/Q*") OR (DestObject =~ "${PREFIX}u_smc_cpu_wrapper/u_smc_cpu/u_digital_top/tlDM/dmInner/dmInner/goReg/Q*") OR (DestObject =~ "${PREFIX}u_smc_cpu_wrapper/u_smc_cpu/u_digital_top/tlDM/dmInner/dmInner/ABSTRACT*/Q*") OR (DestObject =~ "${PREFIX}u_smc_cpu_wrapper/u_smc_cpu/u_digital_top/tlDM/dmInner/dmInner/COMMANDReg_*/Q*") OR (DestObject =~ "${PREFIX}u_smc_cpu_wrapper/u_smc_cpu/u_digital_top/tlDM/dmInner/dmInner/SBCSFieldsReg_*/Q*") OR (DestObject =~ "${PREFIX}u_smc_cpu_wrapper/u_smc_cpu/u_digital_top/tlDM/dmInner/dmInner/SBADDRESSFieldsReg_*/Q*") OR (DestObject =~ "${PREFIX}u_smc_cpu_wrapper/u_smc_cpu/u_digital_top/tlDM/dmInner/dmInner/SBDATAFieldsReg_*/Q*") OR (DestObject =~ "${PREFIX}u_smc_cpu_wrapper/u_smc_cpu/u_digital_top/tlDM/dmInner/dmInner/sbErrorReg_*/Q*") OR (DestObject =~ "${PREFIX}u_smc_cpu_wrapper/u_smc_cpu/u_digital_top/tlDM/dmInner/dmInner/hamaskReg_*/Q*") OR (DestObject =~ "${PREFIX}u_smc_cpu_wrapper/u_smc_cpu/u_digital_top/tlDM/dmInner/dmInner/hrmaskReg_*/Q*") OR (DestObject =~ "${PREFIX}u_smc_cpu_wrapper/u_smc_cpu/u_digital_top/tlDM/dmInner/dmInner/abstractDataMem_*/Q*") OR (DestObject =~ "${PREFIX}u_smc_cpu_wrapper/u_smc_cpu/u_digital_top/tlDM/dmInner/dmInner/programBufferMem_*/Q*") OR (DestObject =~ "${PREFIX}u_smc_cpu_wrapper/u_smc_cpu/u_digital_top/tlDM/dmInner/dmInner/hg*/Q*") OR (DestObject =~ "${PREFIX}u_smc_cpu_wrapper/u_smc_cpu/u_digital_top/tlDM/dmInner/dmInner/hr*/Q*") OR (DestObject =~ "${PREFIX}u_smc_cpu_wrapper/u_smc_cpu/u_digital_top/tlDM/dmInner/dmiXing/*/mem_0_*/Q*") OR (DestObject =~ "${PREFIX}u_smc_cpu_wrapper/u_smc_cpu/u_digital_top/tlDM/dmInner/dmiXing/*/cdc_reg/Q*") OR (DestObject =~ "${PREFIX}u_smc_cpu_wrapper/u_smc_cpu/u_digital_top/tlDM/dmInner/dmactive_synced_dmInner_io_innerCtrl_sink/*/Q*"))}] -app { rdc } -tag { RDC_CORRUPT_OBSERVED } -user { nbetik } -timestamp { 16-09-2026 12:50:22 }
waive_violation -add {SMC_CPU_RDC_CORRUPT_DM_JTAG_DOMAIN_INTERNAL} -comment {DTM / debug-module outer crossings within the single JTAG reset domain (sync-reset flops, pointer-qualified AsyncQueue payload, 1149.1 scan chains), and the AsyncQueue safe-reset handshake: the source_valid / sink_extend 3-flop chains exchange reset state between the JTAG and PRIMARY sides of every tlDM AsyncQueue so each side is emptied while the other is in reset; the chains are the synchronizers.} -filter [apply_prefix {((RdcSourceResets:ResetName == "JTAG_RESET") AND (RdcDestResets:DestResetInfo:ResetName == "'no-reset'") AND ((SrcObject =~ "${PREFIX}u_smc_cpu_wrapper/u_smc_cpu/u_digital_top/tlDM/dmOuter/*") OR (SrcObject =~ "${PREFIX}u_smc_cpu_wrapper/u_smc_cpu/u_digital_top/dtm/*")) AND ((DestObject =~ "${PREFIX}u_smc_cpu_wrapper/u_smc_cpu/u_digital_top/tlDM/dmOuter/*") OR (DestObject =~ "${PREFIX}u_smc_cpu_wrapper/u_smc_cpu/u_digital_top/dtm/*"))) OR ((ReasonInfoList:ReasonInfo:ReasonCode == "NFF_BEYOND_UDS") AND (SrcObject =~ "${PREFIX}u_smc_cpu_wrapper/u_smc_cpu/u_digital_top/tlDM/*/io_out_source_valid_0/output_chain/*") AND (DestObject =~ "${PREFIX}u_smc_cpu_wrapper/u_smc_cpu/u_digital_top/tlDM/*/io_out_source_valid_0/output_chain/*") AND ((RdcDestResets:DestResetInfo:ResetName == "JTAG_RESET") OR (RdcDestResets:DestResetInfo:ResetName == "PRIMARY_RESET_N") OR (RdcDestResets:DestResetInfo:ResetName == "PRIMARY_RESET_N_SMC_CLK")))}] -app { rdc } -tag { RDC_CORRUPT_OBSERVED } -user { nbetik } -timestamp { 16-09-2026 12:50:22 }
# Core reset status and the init-done flag enter the debug module through its hartIsInResetSync 3-flop
# synchronizers (WARM/FUSE-class sources, PRIMARY-reset chain); the synchronizer is the intended structure for
# reset-as-data and the DM reads the resolved value as hart status.
waive_violation -add {SMC_CPU_RDC_CORRUPT_DM_HART_RESET_STATUS_SYNC} -comment {Core reset / init_mem_complete status sampled into the debug module through the hartIsInResetSync 3-flop synchronizers; reset-as-data by the debug spec, the synchronizer resolves the sample and the DM consumes it as hart status.} -filter [apply_prefix {(ReasonInfoList:ReasonInfo:ReasonCode == "NFF_BEYOND_UDS") AND ((SrcObject =~ "${PREFIX}u_smc_cpu_wrapper/u_smc_cpu_ctrl_wrap/core_reset_n_n0_scan_o/*") OR (SrcObject =~ "${PREFIX}u_smc_cpu_wrapper/u_smc_cpu/init_mem_complete/*")) AND (DestObject =~ "${PREFIX}u_smc_cpu_wrapper/u_smc_cpu/u_digital_top/tlDM/dmInner/dmInner/hartIsInResetSync_*/output_chain/u_prim_flop_3sync_r/*")}] -app { rdc } -tag { RDC_CORRUPT_OBSERVED } -user { nbetik } -timestamp { 17-09-2026 18:15:09 }
waive_violation -add {SMC_AVS_RDC_CORRUPT_AG_CLK_MUX_SELECT_SYNC} -comment {Clock-select CSR into the glitch-free mux's async-reset select synchronizer; destination reset is upstream of source and the mux tolerates select changes by design.} -filter [apply_prefix {(ReasonInfoList:ReasonInfo:ReasonCode == "NFF_BEYOND_UDS") AND (SrcObject =~ "${PREFIX}u_smc_peripherals/u_avsbus_controller/u_avsbus_controller_reg_inst/field_storage.AVS_CFG_1.AVS_CLOCK_SELECT.value*") AND (DestObject =~ "${PREFIX}u_smc_peripherals/u_avsbus_controller/u_refclk_apbclk_mux/*sync_clk*/d0nt_wrap_sync/Q")}] -app { rdc } -tag { RDC_CORRUPT_OBSERVED } -user { nbetik } -timestamp { 16-09-2026 12:50:22 }
waive_violation -add {SMC_DFD_RDC_CORRUPT_DBM_LANE_CAPTURE} -comment {DBM lane/control flops sync-reset by PRIMARY: PRIMARY sources are same-net sync style; tapped reset nets are the observed event with one-cycle sampling ambiguity, consumed only by the CLA/trace debug path.} -filter [apply_prefix {(RdcDestResets:DestResetInfo:ResetName == "'no-reset'") AND (DestSyncResetInfoList:DestResetInfo:ResetName == "PRIMARY_RESET_N_SMC_CLK") AND (DestObject =~ "${PREFIX}u_smc_base/u_internal_regs/u_smc_dfd_wrap/gen_dbm_l*/*")}] -app { rdc } -tag { RDC_CORRUPT_OBSERVED } -user { nbetik } -timestamp { 16-09-2026 12:50:22 }
waive_violation -add {SMC_DFD_RDC_CORRUPT_DFD_IP_PRIMARY_SYNC} -comment {DFD IP sync-reset flops (PRIMARY) with PRIMARY-class sources; same-net sync style, forced from the second edge and held.} -filter [apply_prefix {(RdcDestResets:DestResetInfo:ResetName == "'no-reset'") AND ((DestSyncResetInfoList:DestResetInfo:ResetName == "PRIMARY_RESET_N_SMC_CLK") OR (DestSyncResetInfoList:DestResetInfo:ResetName == "PRIMARY_RESET_N_REF_CLK")) AND ((DestObject =~ "${PREFIX}u_smc_base/u_internal_regs/u_smc_dfd_wrap/u_dfd_top/*") OR (DestObject =~ "${PREFIX}u_smc_base/u_internal_regs/u_smc_dfd_wrap/dfd_clk_gate/*")) AND ((RdcSourceResets:ResetName == "PRIMARY_RESET_N") OR (RdcSourceResets:ResetName == "PRIMARY_RESET_N_SMC_CLK") OR (RdcSourceResets:ResetName == "PRIMARY_RESET_N_REF_CLK") OR (RdcSourceResets:ResetName == "PRIMARY_RESET_N_PERIPH_CLK") OR (RdcSourceResets:ResetName == "COLD_RESET_N") OR (RdcSourceResets:ResetName == "COLD_RESET_N_SMC_CLK") OR (RdcSourceResets:ResetName == "COLD_RESET_N_REF_CLK") OR (RdcSourceResets:ResetName == "POWERGOOD_STABLE_N"))}] -app { rdc } -tag { RDC_CORRUPT_OBSERVED } -user { nbetik } -timestamp { 16-09-2026 12:50:22 }
waive_violation -add {SMC_RDC_CORRUPT_REFCNT_FIFO_STORAGE} -comment {prim_fifo_async storage with write and read pointers reset from the same PRIMARY root; pointer-qualified, torn entries unreachable.} -filter [apply_prefix {(RdcDestResets:DestResetInfo:ResetName == "'no-reset'") AND (DestObject =~ "${PREFIX}u_smc_cpu_wrapper/u_smc_cpu_ctrl_wrap/u_refclk_counter/cnt_update_async_fifo/storage/Q*") AND ((RdcSourceResets:ResetName == "PRIMARY_RESET_N") OR (RdcSourceResets:ResetName == "PRIMARY_RESET_N_SMC_CLK") OR (RdcSourceResets:ResetName == "PRIMARY_RESET_N_REFCNT_SMC_CLK") OR (RdcSourceResets:ResetName == "PRIMARY_RESET_N_REFCNT_REF_CLK"))}] -app { rdc } -tag { RDC_CORRUPT_OBSERVED } -user { nbetik } -timestamp { 16-09-2026 12:50:22 }

# --- telemetry AT-request FIFO storage (prim_fifo_async, TELEMETRY write side / PRIMARY read side) ---
waive_violation -add {SMC_RDC_CORRUPT_TELEM_FIFO_STORAGE} -comment {prim_fifo_async storage; write and read pointers clear together because TELEMETRY and PRIMARY resets are co-asserted (rst_telemetry_ni asserts with PRIMARY and never alone); pointer-qualified.} -filter [apply_prefix {(RdcDestResets:DestResetInfo:ResetName == "'no-reset'") AND (DestObject =~ "${PREFIX}u_smc_peripherals/u_telemetry_receiver_wrap/*at_req_fifo_async/storage/Q*") AND (RdcSourceResets:ResetName == "TELEMETRY_RESET_N")}] -app { rdc } -tag { RDC_CORRUPT_OBSERVED } -user { nbetik } -timestamp { 16-09-2026 12:50:22 }
waive_violation -add {SMC_RDC_CORRUPT_SYNC_RESET_APPLICATION} -comment {prim_sync_reset tail into a flop synchronously reset by that same chain's output; forced from the second edge and held for the chain depth.} -filter [apply_prefix {(RdcDestResets:DestResetInfo:ResetName == "'no-reset'") AND (((SrcObject =~ "${PREFIX}u_smc_peripherals/u_smc_reset_unit/u_smc_reset_sync/u_rst_cold_smc_sync/*") AND (DestSyncResetInfoList:DestResetInfo:ResetName == "COLD_RESET_N_SMC_CLK")) OR ((SrcObject =~ "${PREFIX}u_smc_peripherals/u_smc_reset_unit/u_smc_reset_sync/u_rst_cold_ref_clk_sync/*") AND (DestSyncResetInfoList:DestResetInfo:ResetName == "COLD_RESET_N_REF_CLK")) OR ((SrcObject =~ "${PREFIX}u_smc_peripherals/u_smc_reset_unit/u_smc_reset_sync/u_rst_primary_smc_sync/*") AND (DestSyncResetInfoList:DestResetInfo:ResetName == "PRIMARY_RESET_N_SMC_CLK")) OR ((SrcObject =~ "${PREFIX}u_smc_peripherals/u_smc_reset_unit/u_smc_reset_sync/u_rst_primary_ref_clk_sync/*") AND (DestSyncResetInfoList:DestResetInfo:ResetName == "PRIMARY_RESET_N_REF_CLK")) OR ((SrcObject =~ "${PREFIX}u_smc_peripherals/u_smc_reset_unit/u_smc_reset_sync/u_rst_primary_periph_clk_sync/*") AND (DestSyncResetInfoList:DestResetInfo:ResetName == "PRIMARY_RESET_N_PERIPH_CLK")) OR ((SrcObject =~ "${PREFIX}u_smc_peripherals/u_smc_reset_unit/u_smc_reset_sync/u_rst_warm_smc_sync/*") AND (DestSyncResetInfoList:DestResetInfo:ResetName == "WARM_RESET_N_SMC_CLK")) OR ((SrcObject =~ "${PREFIX}u_smc_peripherals/u_smc_reset_unit/u_smc_reset_sync/u_rst_wdt_smc_sync/*") AND (DestSyncResetInfoList:DestResetInfo:ResetName == "WDT_RESET_N_SMC_CLK")) OR ((SrcObject =~ "${PREFIX}u_smc_peripherals/u_avsbus_controller/u_apb_clk_reset_sync/*") AND (DestSyncResetInfoList:DestResetInfo:ResetName == "AVS_APB_CLK_RESET_N")) OR ((SrcObject =~ "${PREFIX}u_smc_peripherals/u_avsbus_controller/u_avs_clk_reset_sync/*") AND (DestSyncResetInfoList:DestResetInfo:ResetName == "AVS_CLK_RESET_N")) OR ((SrcObject =~ "${PREFIX}u_smc_peripherals/u_avsbus_controller/u_pre_div_clk_reset_sync/*") AND (DestSyncResetInfoList:DestResetInfo:ResetName == "AVS_PRE_DIV_CLK_RESET_N")) OR ((SrcObject =~ "${PREFIX}u_smc_peripherals/u_avsbus_controller/u_clk_div/u_reset_sync/*") AND (DestSyncResetInfoList:DestResetInfo:ResetName == "AVS_CLK_DIV_RESET_N")) OR ((SrcObject =~ "${PREFIX}u_smc_cpu_wrapper/u_smc_cpu_ctrl_wrap/u_refclk_counter/u_prst_wr_clk_domain_sync/*") AND (DestSyncResetInfoList:DestResetInfo:ResetName == "PRIMARY_RESET_N_REFCNT_SMC_CLK")) OR ((SrcObject =~ "${PREFIX}u_smc_cpu_wrapper/u_smc_cpu_ctrl_wrap/u_refclk_counter/u_prst_rd_clk_domain_sync/*") AND (DestSyncResetInfoList:DestResetInfo:ResetName == "PRIMARY_RESET_N_REFCNT_REF_CLK")) OR ((SrcObject =~ "${PREFIX}u_smc_base/u_internal_regs/u_smc_dfd_wrap/u_ref_rst_sync/*") AND (DestObject =~ "${PREFIX}u_smc_base/u_internal_regs/u_smc_dfd_wrap/ref_cnt*")))}] -app { rdc } -tag { RDC_CORRUPT_OBSERVED } -user { nbetik } -timestamp { 16-09-2026 12:50:22 }
waive_violation -add {SMC_AVS_RDC_CORRUPT_PULSE_SYNC_TAIL_INTO_IRQ_FLAG} -comment {Pulse-sync re-synced APB reset tail into AVS_CLK-reset interrupt flags; both resets derive from rst_reg_ni and assert together.} -filter [apply_prefix {(RdcDestResets:DestResetInfo:ResetName == "'no-reset'") AND (DestSyncResetInfoList:DestResetInfo:ResetName == "AVS_CLK_RESET_N") AND (SrcObject =~ "${PREFIX}u_smc_peripherals/u_avsbus_controller/u_clear_*_resync/u_dest/u_src_reset_n_sync/*") AND (DestObject =~ "${PREFIX}u_smc_peripherals/u_avsbus_controller/R_avs_interrupt_F_*_AVSCLK/Q*")}] -app { rdc } -tag { RDC_CORRUPT_OBSERVED } -user { nbetik } -timestamp { 16-09-2026 12:50:22 }
waive_violation -add {SMC_TELEM_RDC_CORRUPT_MSG_BUFFER} -comment {Pointer-qualified message buffer; pointers and all writers on the same PRIMARY reset, reads return zero when empty.} -filter [apply_prefix {(RdcDestResets:DestResetInfo:ResetName == "'no-reset'") AND (DestSyncResetInfoList:DestResetInfo:ResetName == "PRIMARY_RESET_N_SMC_CLK") AND (DestObject =~ "${PREFIX}u_smc_peripherals/u_telemetry_receiver_wrap/*telemetry_receiver/message_buffer*") AND ((RdcSourceResets:ResetName == "PRIMARY_RESET_N") OR (RdcSourceResets:ResetName == "PRIMARY_RESET_N_SMC_CLK"))}] -app { rdc } -tag { RDC_CORRUPT_OBSERVED } -user { nbetik } -timestamp { 16-09-2026 12:50:22 }
waive_violation -add {SMC_RDC_CORRUPT_IRQ_STAGING_FLOPS} -comment {Unreset one-stage staging flops recomputed every cycle from PRIMARY-class level sources; a torn sample is overwritten next edge and consumers are in the same reset (see block comment).} -filter [apply_prefix {(RdcDestResets:DestResetInfo:ResetName == "'no-reset'") AND (DestSyncResetInfoList:DestResetInfo:ResetName == "'no-reset'") AND ((DestObject =~ "${PREFIX}u_smc_peripherals/u_smc_peripherals_cdc/*_periph_clk_flopped/Q*") OR (DestObject =~ "${PREFIX}u_smc_peripherals/u_smc_peripherals_cdc/*_smc_clk_flopped/Q*")) AND ((RdcSourceResets:ResetName == "PRIMARY_RESET_N") OR (RdcSourceResets:ResetName == "PRIMARY_RESET_N_SMC_CLK") OR (RdcSourceResets:ResetName == "PRIMARY_RESET_N_PERIPH_CLK") OR (RdcSourceResets:ResetName == "AVS_APB_CLK_RESET_N"))}] -app { rdc } -tag { RDC_CORRUPT_OBSERVED } -user { nbetik } -timestamp { 16-09-2026 12:50:22 }
waive_violation -add {SMC_RDC_CORRUPT_QS_CONFIG_INTO_SYNC} -comment {GPIO DATA_CTRL.lsio_disable / lsio_select (PRIMARY-reset CSRs, reset value unmasks the pin) into the first stage of the isolate-req / boot-stall pad-input prim_sync3; a single-bit asynchronous input change the 3-stage chain absorbs by design, output equals the live pin after 3 SMCCLK edges, consumers are built to follow the pin across PRIMARY.} -filter [apply_prefix {((SrcObject =~ "${PREFIX}u_smc_peripherals/u_smc_padring/gen_gpio_intf[*].u_gpio_interface/u_gpio_intf_reg/field_storage.DATA_CTRL.lsio_disable.value") OR (SrcObject =~ "${PREFIX}u_smc_peripherals/u_smc_padring/gen_gpio_intf[*].u_gpio_interface/u_gpio_intf_reg/field_storage.DATA_CTRL.lsio_select.value")) AND ((DestObject == "${PREFIX}u_smc_peripherals/u_boot_stall_combined_sync/u_sync3[0]/d0nt_wrap_sync/Q") OR (DestObject == "${PREFIX}u_smc_peripherals/u_smc_reset_unit/u_smc_cool_reset_wrap/u_isolate_req_pin_sync/u_sync3[0]/d0nt_wrap_sync/Q")) AND (RdcDestResets:DestResetInfo:ResetName == "'no-reset'") AND (ReasonInfoList:ReasonInfo:ReasonCode == "NFF_BEYOND_UDS")}] -app { rdc } -tag { RDC_CORRUPT_OBSERVED } -user { nbetik } -timestamp { 16-09-2026 12:50:22 }
# --- PRIMARY-class sources into flops synchronously reset by PRIMARY_RESET_N_SMC_CLK (per-mechanism) ---
# Common argument: rst_primary_smc_clk_no is a prim_sync_reset whose every stage has i_RN(rst_n) = rst_primary_no, so it
# asserts in the same instant as PRIMARY and holds; the destination is forced to its reset value on the first SMCCLK
# edge after PRIMARY asserts, so a torn sample lives one cycle. Each waiver below adds the destination mechanism and
# why that one cycle is unobservable. Destinations with any other sync reset (COLD, FLR, ...) deliberately do not match.
waive_violation -add {SMC_RDC_CORRUPT_PRIMARY_INTO_HYST_GATER_STATE} -comment {prim_clk_gater_hysteresis hyst_cnt_q / busy_seen_q (axi_cg_snoop u_clk_gater and the DMA request-manager gater): sync-reset by PRIMARY_RESET_N_SMC_CLK, and run = ~rst_ni | ... keeps the gated clock running for the whole reset, so a torn count or busy flag cannot stop a clock or leak past the reset. 2406 crossings 16-Sep.} -filter [apply_prefix {(RdcSourceResets:ResetName == "PRIMARY_RESET_N") AND (RdcDestResets:DestResetInfo:ResetName == "'no-reset'") AND (DestSyncResetInfoList:DestResetInfo:ResetName == "PRIMARY_RESET_N_SMC_CLK") AND ((DestClockInfoList:DestClockInfo:ClockName == "SMCCLK") OR (DestClockInfoList:DestClockInfo:ClockName == "SMUCLK")) AND ((DestObject =~ "${PREFIX}*_cg/u_clk_gater/hyst_cnt_q/*") OR (DestObject =~ "${PREFIX}*_cg/u_clk_gater/busy_seen_q/*") OR (DestObject =~ "${PREFIX}*_cg/hyst_cnt_q/*") OR (DestObject =~ "${PREFIX}*_cg/busy_seen_q/*"))}] -app { rdc } -tag { RDC_CORRUPT_OBSERVED } -user { nbetik } -timestamp { 17-09-2026 11:44:06 }
waive_violation -add {SMC_RDC_CORRUPT_PRIMARY_INTO_DMA_ZEROER_BUSY_INTP} -comment {idma_wrapper dma_prev_busy / dma_intp_o and zeroer prev_busy / zeroer_intp_o: sync-reset by PRIMARY_RESET_N_SMC_CLK; the only consumer of the transfer-complete pulse is the interrupt path, itself under PRIMARY reset, so a one-cycle spurious pulse during reset assertion is never delivered. 365 crossings 16-Sep.} -filter [apply_prefix {(RdcSourceResets:ResetName == "PRIMARY_RESET_N") AND (RdcDestResets:DestResetInfo:ResetName == "'no-reset'") AND (DestSyncResetInfoList:DestResetInfo:ResetName == "PRIMARY_RESET_N_SMC_CLK") AND ((DestClockInfoList:DestClockInfo:ClockName == "SMCCLK") OR (DestClockInfoList:DestClockInfo:ClockName == "SMUCLK")) AND ((DestObject =~ "${PREFIX}u_smc_base/u_smc_data_accelerator_wrap/u_dma_wrap/dma_intp_o/*") OR (DestObject =~ "${PREFIX}u_smc_base/u_smc_data_accelerator_wrap/u_dma_wrap/dma_prev_busy/*") OR (DestObject =~ "${PREFIX}u_smc_base/u_smc_data_accelerator_wrap/u_zeroer/zeroer_intp_o/*") OR (DestObject =~ "${PREFIX}u_smc_base/u_smc_data_accelerator_wrap/u_zeroer/prev_busy/*"))}] -app { rdc } -tag { RDC_CORRUPT_OBSERVED } -user { nbetik } -timestamp { 17-09-2026 11:44:06 }
waive_violation -add {SMC_RDC_CORRUPT_PRIMARY_INTO_CORE_RESET_PULSE_GEN} -comment {smc_cpu_ctrl_wrap prim_pulse_signal core-reset pulse generators (pulse_state, pulse_in_initial_val, prim_updown_counter cnt_unforced_q): sync-reset by PRIMARY_RESET_N_SMC_CLK; their output only reaches core_reset_n_n0_scan_o, which is async-reset by WARM, and rst_warm_no = wdt_reset_n & rst_primary_no & fuse_reset_ni, so the cores are held in reset for as long as PRIMARY is asserted and a torn pulse state cannot release or glitch a core reset. 152 crossings 16-Sep.} -filter [apply_prefix {(RdcSourceResets:ResetName == "PRIMARY_RESET_N") AND (RdcDestResets:DestResetInfo:ResetName == "'no-reset'") AND (DestSyncResetInfoList:DestResetInfo:ResetName == "PRIMARY_RESET_N_SMC_CLK") AND ((DestClockInfoList:DestClockInfo:ClockName == "SMCCLK") OR (DestClockInfoList:DestClockInfo:ClockName == "SMUCLK")) AND (DestObject =~ "${PREFIX}u_smc_cpu_wrapper/u_smc_cpu_ctrl_wrap/gen_pulse[*].gen_pulse_core_resets.u_pulse_core_reset/*")}] -app { rdc } -tag { RDC_CORRUPT_OBSERVED } -user { nbetik } -timestamp { 17-09-2026 11:44:06 }
waive_violation -add {SMC_CPU_CTRL_RDC_CORRUPT_PRIMARY_INTO_SYNC_RESET_REGS} -comment {smc_cpu_ctrl_wrap wb_reg_pc_sr / cycle_count / mutex / sema: SMCCLK flops with a synchronous rst_primary_ni clear fed by PRIMARY-reset CSR fields, reset-control register values, AXI-lite request flops and the core-reset pulse generators; same-net synchronous style, forced from the second edge and held.} -filter [apply_prefix {((RdcSourceResets:ResetName == "PRIMARY_RESET_N") OR (RdcSourceResets:ResetName == "PRIMARY_RESET_N_SMC_CLK")) AND (RdcDestResets:DestResetInfo:ResetName == "'no-reset'") AND (DestSyncResetInfoList:DestResetInfo:ResetName == "PRIMARY_RESET_N_SMC_CLK") AND ((DestClockInfoList:DestClockInfo:ClockName == "SMCCLK") OR (DestClockInfoList:DestClockInfo:ClockName == "SMUCLK")) AND ((DestObject =~ "${PREFIX}u_smc_cpu_wrapper/u_smc_cpu_ctrl_wrap/wb_reg_pc_sr/*") OR (DestObject =~ "${PREFIX}u_smc_cpu_wrapper/u_smc_cpu_ctrl_wrap/cycle_count/*") OR (DestObject =~ "${PREFIX}u_smc_cpu_wrapper/u_smc_cpu_ctrl_wrap/mutex/*") OR (DestObject =~ "${PREFIX}u_smc_cpu_wrapper/u_smc_cpu_ctrl_wrap/sema/*"))}] -app { rdc } -tag { RDC_CORRUPT_OBSERVED } -user { nbetik } -timestamp { 17-09-2026 18:15:09 }
waive_violation -add {SMC_CPU_CTRL_RDC_CORRUPT_CORE_RESET_STATUS_INTO_TRACE_WDT} -comment {smc_cpu_ctrl_wrap wb_reg_pc_sr / cycle_count sampling the core, uncore and cluster reset status flops, the init-done flag and the cluster WDT reset registers (WARM / FUSE / CLUSTER_UNCORE-class sources). The PC trace shift register is observability only; the WDT countdown is reloaded while the reset status that disturbed it is held.} -filter [apply_prefix {((RdcSourceResets:ResetName == "WARM_RESET_N") OR (RdcSourceResets:ResetName == "WARM_RESET_N_SMC_CLK") OR (RdcSourceResets:ResetName == "FUSE_RESET_N") OR (RdcSourceResets:ResetName == "CLUSTER_UNCORE_RESET_N")) AND (SrcObject =~ "${PREFIX}u_smc_cpu_wrapper/*") AND (RdcDestResets:DestResetInfo:ResetName == "'no-reset'") AND (DestSyncResetInfoList:DestResetInfo:ResetName == "PRIMARY_RESET_N_SMC_CLK") AND ((DestClockInfoList:DestClockInfo:ClockName == "SMCCLK") OR (DestClockInfoList:DestClockInfo:ClockName == "SMUCLK")) AND ((DestObject =~ "${PREFIX}u_smc_cpu_wrapper/u_smc_cpu_ctrl_wrap/wb_reg_pc_sr/*") OR (DestObject =~ "${PREFIX}u_smc_cpu_wrapper/u_smc_cpu_ctrl_wrap/cycle_count/*"))}] -app { rdc } -tag { RDC_CORRUPT_OBSERVED } -user { nbetik } -timestamp { 17-09-2026 18:15:09 }
waive_violation -add {SMC_EFUSE_RDC_CORRUPT_PRIMARY_INTO_GUARD_ERR} -comment {efuse_guard err: synchronous rst clear on the same PRIMARY reset as the eFuse controller CSR, program/read state and shadow flops that feed it; same-net synchronous style, forced from the second edge and held.} -filter [apply_prefix {((RdcSourceResets:ResetName == "PRIMARY_RESET_N") OR (RdcSourceResets:ResetName == "PRIMARY_RESET_N_SMC_CLK")) AND (RdcDestResets:DestResetInfo:ResetName == "'no-reset'") AND (DestSyncResetInfoList:DestResetInfo:ResetName == "PRIMARY_RESET_N_SMC_CLK") AND ((DestClockInfoList:DestClockInfo:ClockName == "SMCCLK") OR (DestClockInfoList:DestClockInfo:ClockName == "SMUCLK")) AND (SrcObject =~ "${PREFIX}u_smc_peripherals/u_smc_efuse_wrapper/*") AND (DestObject =~ "${PREFIX}u_smc_peripherals/u_smc_efuse_wrapper/u_efuse_interface_controller/u_efuse_guard/err/*")}] -app { rdc } -tag { RDC_CORRUPT_OBSERVED } -user { nbetik } -timestamp { 17-09-2026 18:15:09 }
# --- PRIMARY-class sources into resetless FIFO storage arrays (pointer-qualified, per FIFO primitive) ---
# The storage array of these FIFOs has no reset by design; a word is only observable through the read pointer, and the
# write/read pointers are reset from the same root as every writer, so a word torn by the reset is never addressed
# again before it is overwritten. Destinations are named per FIFO primitive so a storage array whose pointers sit on
# a different reset root (FLR, COLD, ...) does not match.
waive_violation -add {SMC_RDC_CORRUPT_PRIMARY_INTO_PERIPH_FIFO_SYNC_STORAGE} -comment {prim_fifo_sync / prim_fifo_sync_parity gen_normal_fifo.storage in the I3C HCI/TTI queues, I2C controller/target FIFOs, UART 16550 RX/TX FIFOs and log-engine rdata FIFO: storage is written without reset and read as storage[fifo_rptr] qualified by the depth counter; u_fifo_cnt write/read pointers are async-reset by the peripheral rst_ni = rst_primary_periph_clk_n, the same PRIMARY root as every writer, so the FIFO restarts empty and a torn word is unreachable.} -filter [apply_prefix {(RdcDestResets:DestResetInfo:ResetName == "'no-reset'") AND (DestSyncResetInfoList:DestResetInfo:ResetName == "'no-reset'") AND ((DestObject =~ "${PREFIX}u_smc_peripherals/u_i3ccore_wrapper/*/gen_normal_fifo.storage/Q*") OR (DestObject =~ "${PREFIX}u_smc_peripherals/u_i2c_wrap/*/gen_normal_fifo.storage/Q*") OR (DestObject =~ "${PREFIX}u_smc_peripherals/u_uart_wrap/*/gen_normal_fifo.storage/Q*")) AND ((RdcSourceResets:ResetName == "PRIMARY_RESET_N") OR (RdcSourceResets:ResetName == "PRIMARY_RESET_N_PERIPH_CLK"))}] -app { rdc } -tag { RDC_CORRUPT_OBSERVED } -user { nbetik } -timestamp { 17-09-2026 11:44:06 }
waive_violation -add {SMC_AVS_RDC_CORRUPT_CMD_FIFO_ARRAY} -comment {avsbus_async_fifo command FIFO fifo_array: written on clk_reg_i without reset, read through gray pointers; the write pointer is sync-reset by reset_n_apb_clk_syncd (AVS_APB_CLK_RESET_N) and the read pointer by reset_n_avs_clk_syncd (AVS_CLK_RESET_N), both prim_sync_reset tails of rst_reg_ni = rst_primary_periph_clk_n that assert with PRIMARY (assertion sequences in smc.resets.tcl); the pointer reset takes priority over the increment, so a word torn on the last write is never published to the read side and both sides restart empty. Writers are the AXI-to-APB bridge (PRIMARY) and the APB register interface (AVS_APB tail).} -filter [apply_prefix {(RdcDestResets:DestResetInfo:ResetName == "'no-reset'") AND (DestSyncResetInfoList:DestResetInfo:ResetName == "'no-reset'") AND (DestObject =~ "${PREFIX}u_smc_peripherals/u_avsbus_controller/u_cmd_async_fifo_inst/fifo_array/Q*") AND ((RdcSourceResets:ResetName == "PRIMARY_RESET_N") OR (RdcSourceResets:ResetName == "PRIMARY_RESET_N_PERIPH_CLK") OR (RdcSourceResets:ResetName == "AVS_APB_CLK_RESET_N"))}] -app { rdc } -tag { RDC_CORRUPT_OBSERVED } -user { nbetik } -timestamp { 17-09-2026 11:44:06 }
# --- AVS_APB-domain CSRs into flops synchronously reset by the same reset_n_apb_clk_syncd ---
waive_violation -add {SMC_AVS_RDC_CORRUPT_APB_CSR_INTO_APB_SYNC_RESET_FLOPS} -comment {avsbus_controller register block (async-reset by reset_n_apb_clk_syncd) into clk_reg_i flops that are synchronously reset by the very same net: interrupt flag regs R_avs_interrupt_F_*, slave_resync_pending / clock_cycles_since_last_resync, prim_sync3_pulse source toggles, prim_sync_data_autohs clk1_val_reg, and the async FIFO gray pointers. reset_n_apb_clk_syncd is a prim_sync_reset tail with async assert, so the source clears in the same instant the destination's sync reset becomes active; the first clk_reg_i edge that could sample the torn value forces the destination to its reset value instead.} -filter [apply_prefix {(RdcSourceResets:ResetName == "AVS_APB_CLK_RESET_N") AND (RdcDestResets:DestResetInfo:ResetName == "'no-reset'") AND (DestSyncResetInfoList:DestResetInfo:ResetName == "AVS_APB_CLK_RESET_N") AND (SrcObject =~ "${PREFIX}u_smc_peripherals/u_avsbus_controller/u_avsbus_controller_reg_inst/*") AND (DestObject =~ "${PREFIX}u_smc_peripherals/u_avsbus_controller/*")}] -app { rdc } -tag { RDC_CORRUPT_OBSERVED } -user { nbetik } -timestamp { 17-09-2026 11:44:06 }
# --- cool-reset wrap: COLD-domain state into flops synchronously reset by the same COLD tail ---
waive_violation -add {SMC_RDC_CORRUPT_COOL_RESET_WRAP_COLD_INTO_COLD_SYNC_RESET_FLOPS} -comment {smc_cool_reset_wrap: FLR counter FSM state and the cfg_flr_pf_active edge flop (async-reset by rst_cold_ref_ni) into the prim_updown_counter cnt_unforced_q that is sync-reset by rst_cold_ref_ni, and the FLR set-count registers (async-reset by rst_cold_smc_ni) into the prim_sync_data_autohs clk1_val_reg sync-reset by rst_cold_smc_ni. Source and destination share one reset net per clock domain; the cold tails assert asynchronously, so the first edge that could sample the torn value forces the destination to its reset value.} -filter [apply_prefix {(RdcDestResets:DestResetInfo:ResetName == "'no-reset'") AND (SrcObject =~ "${PREFIX}u_smc_peripherals/u_smc_reset_unit/u_smc_cool_reset_wrap/*") AND (DestObject =~ "${PREFIX}u_smc_peripherals/u_smc_reset_unit/u_smc_cool_reset_wrap/*") AND (((RdcSourceResets:ResetName == "COLD_RESET_N_REF_CLK") AND (DestSyncResetInfoList:DestResetInfo:ResetName == "COLD_RESET_N_REF_CLK")) OR ((RdcSourceResets:ResetName == "COLD_RESET_N_SMC_CLK") AND (DestSyncResetInfoList:DestResetInfo:ResetName == "COLD_RESET_N_SMC_CLK")))}] -app { rdc } -tag { RDC_CORRUPT_OBSERVED } -user { nbetik } -timestamp { 17-09-2026 11:44:06 }

# =============================================================================
# Warning-class dispositions
# =============================================================================
waive_violation -add {SMC_CPU_SETUP_RESET_DRIVING_NON_ASYNC_PIN_CLUSTER} -comment {11 -async cluster resets (smc.resets.tcl) pass one chipyard ResetCatchAndSync_d3 each and are then consumed as Chisel synchronous resets; async use is limited to IntSyncCrossingSource, clock_en and cluster_ded_o. Also covers the cluster boundary axi_isolate control (init_mem_complete & rst_*_ni) in smc_4core_cpu.} -filter [apply_prefix {(ResetName =~ "${PREFIX}u_smc_cpu_wrapper/*") AND ((NonResetInstance =~ "${PREFIX}u_smc_cpu_wrapper/*") OR (NonResetInstance =~ "cluster_*") OR (NonResetInstance =~ "smc_cluster_*"))}] -app { rdc } -tag { SETUP_RESET_DRIVING_NON_ASYNC_PIN } -user { nbetik } -timestamp { 16-09-2026 12:50:22 }
waive_violation -add {SMC_SETUP_CLOCK_UNUSED_BOUNDARY_CLKS} -comment {Output-port memory clocks and AVS/GPIO modeling clocks clock no internal sequentials by construction.} -filter [apply_prefix {(Clock:ClkName =~ "SMCCLK_*") OR (Clock:ClkName =~ "AVS_*") OR (Clock:ClkName == "SPICLK_IN_GPIO") OR (Clock:ClkName == "SPICLK_OUT_GPIO")}] -app { rdc } -tag { SETUP_CLOCK_UNUSED } -user { nbetik } -timestamp { 16-09-2026 12:50:22 }
waive_violation -add {SMC_INTEGRITY_RESET_ASYNC_AND_SYNC_USAGE_METHODOLOGY} -comment {Async-assert/sync-consume on the reset-unit outputs, the AVS reset-sync tails, the JTAG reset input and the CPU-wrapper generated resets is the project reset methodology.} -filter [apply_prefix {(ResetObject =~ "${PREFIX}u_smc_peripherals/u_smc_reset_unit/rst_*") OR (ResetObject =~ "${PREFIX}u_smc_peripherals/u_avsbus_controller/*/gen_rst_sync_stage*.u_sync_dffr/d0nt_dffr/Q") OR (ResetObject == "${PREFIX}smc_cpu_jtag_reset_i") OR (ResetObject =~ "${PREFIX}u_smc_cpu_wrapper/u_smc_cpu_ctrl_wrap/*reset_n*") OR (ResetObject =~ "${PREFIX}u_smc_cpu_wrapper/u_smc_cpu/u_digital_top/tlDM/dmOuter/dmOuter/hartResetReg_*/Q") OR (ResetObject == "${PREFIX}u_smc_cpu_wrapper/u_smc_cpu/init_mem_complete/Q")}] -app { rdc } -tag { INTEGRITY_RESET_ASYNC_AND_SYNC_USAGE } -user { nbetik } -timestamp { 16-09-2026 12:50:22 }
waive_violation -add {SMC_SETUP_RESET_OVERLAP_RESET_TREE} -comment {AND-combined hierarchical reset tree; overlap between parent and derived resets is by construction; ordering declared in smc.resets.tcl.} -filter [apply_prefix {((SrcRstInfo:ResetName == "PRIMARY_RESET_N_SMC_CLK") OR (SrcRstInfo:ResetName == "PRIMARY_RESET_N_PERIPH_CLK") OR (SrcRstInfo:ResetName == "POWERGOOD_STABLE_N") OR (SrcRstInfo:ResetName == "POWERGOOD_RESET_N") OR (SrcRstInfo:ResetName == "COOL_RESET_FROM_FLR_N") OR (SrcRstInfo:ResetName == "BOOT_STALL_N")) AND ((DesRstInfo:ResetName == "WARM_RESET_N") OR (DesRstInfo:ResetName == "FUSE_RESET_N") OR (DesRstInfo:ResetName == "PRIMARY_RESET_N") OR (DesRstInfo:ResetName =~ "PRIMARY_RESET_N_REFCNT_*") OR (DesRstInfo:ResetName =~ "AVS_*_RESET_N") OR (DesRstInfo:ResetName == "COLD_RESET_N") OR (DesRstInfo:ResetName == "POWERGOOD_STABLE_N"))}] -app { rdc } -tag { SETUP_RESET_OVERLAP } -user { nbetik } -timestamp { 16-09-2026 12:50:22 }
waive_violation -add {SMC_SETUP_RESET_UNUSED_INDIRECT} -comment {Raw pad / scan / AND-tree contributor resets are consumed indirectly by construction.} -filter [apply_prefix {(Reset:ResetName == "SCAN_RESET_N") OR (Reset:ResetName == "COOL_RESET_FROM_FLR_N") OR (Reset:ResetName == "WDT_RESET_N_SMC_CLK") OR (Reset:ResetName == "COLD_RESET_PAD_N") OR (Reset:ResetName == "COOL_RESET_FROM_PIN_N") OR (Reset:ResetName == "BOOT_STALL_N")}] -app { rdc } -tag { SETUP_RESET_UNUSED } -user { nbetik } -timestamp { 16-09-2026 12:50:22 }
waive_violation -add {SMC_SETUP_ASYNCRESET_UNUSED_INDIRECT} -comment {Raw pad / boot-stall resets are deglitched/stretched before any flop consumption.} -filter [apply_prefix {(Reset:ResetName == "COLD_RESET_PAD_N") OR (Reset:ResetName == "COOL_RESET_FROM_PIN_N") OR (Reset:ResetName == "BOOT_STALL_N")}] -app { rdc } -tag { SETUP_ASYNCRESET_UNUSED } -user { nbetik } -timestamp { 16-09-2026 12:50:22 }

# Reset-unit AND/deglitch combinational terms ahead of downstream reset syncs:
# every functional input to the reset AND-tree is itself registered or
# deglitched, and each consuming domain re-synchronizes the combined reset
# through its prim_sync_reset chain, so a combinational hazard on the tree
# cannot reach a flop reset pin unfiltered.
waive_violation -add {SMC_INTEGRITY_RESET_GLITCH_RESET_TREE} -comment {AND-combined reset tree with registered/deglitched inputs and per-domain resynchronization; every flagged destination is a reset-unit resynchronizer or stretcher flop.} -filter [apply_prefix {(GlitchyDestObjectList:GlitchyDestObject =~ "${PREFIX}u_smc_peripherals/u_smc_reset_unit/*")}] -app { rdc } -tag { INTEGRITY_RESET_GLITCH } -user { nbetik } -timestamp { 16-09-2026 12:50:22 }

waive_violation -add {SMC_AVS_SETUP_ASYNC_CLOCK_OVERWRITE_MUX_MODELING} -comment {Two -add generated clocks per shared AVS mux/divider node (logically exclusive groups); overwrite reports are inherent to that modeling (see vccdc smc_waiver.tcl).} -filter [apply_prefix {(OverWriteClock:ClkName =~ "AVS_*") OR (PrimaryClock:ClkName =~ "AVS_*")}] -app { rdc } -tag { SETUP_ASYNC_CLOCK_OVERWRITE } -user { nbetik } -timestamp { 16-09-2026 12:50:22 }

# --- assertion sequences retained for documentation / parent reuse ---
waive_violation -add {SMC_SETUP_RDC_CONSTRAINT_UNUSED_DOC_SEQUENCES} -comment {Reset-ordering declarations retained for documentation and SMU-level reuse; unused here because their crossings are pruned by other orderings.} -filter [apply_prefix {(ConstraintName == "set_rdc_define_assertion_sequence")}] -app { rdc } -tag { SETUP_RDC_CONSTRAINT_UNUSED } -user { nbetik } -timestamp { 16-09-2026 12:50:22 }

# --- cold-reset deglitch shift register ---
waive_violation -add {SMC_SETUP_RESET_SOFT_NOASSERT_DEGLITCHER} -comment {Deglitch shift register on the cold reset pad path; not a reset root.} -filter [apply_prefix {(PotentialRoot =~ "${PREFIX}u_smc_peripherals/u_smc_reset_unit/u_smc_reset_ctrl/*deglitch_shift_reg*")}] -app { rdc } -tag { SETUP_RESET_SOFT_NOASSERT } -user { nbetik } -timestamp { 16-09-2026 12:50:22 }

# --- DFD debug-bus observation taps of reset values ---
# The DBM lanes deliberately observe cluster reset nets on the debug bus
# (reset value visibility for debug); the "reset used as data" at debug_bus_ff
# is that observation tap, with no functional consumer.
waive_violation -add {SMC_DFD_SETUP_RESET_DRIVING_NON_ASYNC_PIN_OBSERVATION} -comment {Reset nets tapped onto the DFD debug observation bus; data usage is the debug tap only.} -filter [apply_prefix {(NonResetInstance =~ "${PREFIX}u_smc_base/u_internal_regs/u_smc_dfd_wrap/*")}] -app { rdc } -tag { SETUP_RESET_DRIVING_NON_ASYNC_PIN } -user { nbetik } -timestamp { 16-09-2026 12:50:22 }

# scan_rst_ni is deliberately BOTH declared as a reset (SCAN_RESET_N, so the
# tool models the pin's role and DFT-mode scenarios can activate it) and
# case-pinned inactive by smc_case_analysis.tcl for the functional scenario.
waive_violation -add {SMC_SETUP_MULTIPLE_CONSTRAINTS_SCAN_RESET} -comment {Intentional mode split: scan reset declared for role modeling, case-pinned inactive in the functional scenario.} -filter [apply_prefix {(InstanceName == "scan_rst_ni")}] -app { rdc } -tag { SETUP_MULTIPLE_CONSTRAINTS } -user { nbetik } -timestamp { 16-09-2026 12:50:22 }
