// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 Tenstorrent USA, Inc.

// Generated by CIRCT unknown git version
// Standard header to adapt well known macros to our needs.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

module OCAH4CORECluster_PLICClockSinkDomain(	// @[generators/rocket-chip/src/main/scala/prci/ClockDomain.scala:14:9]
  input         auto_plic_int_in_0,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_1,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_2,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_3,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_4,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_5,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_6,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_7,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_8,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_9,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_10,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_11,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_12,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_13,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_14,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_15,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_16,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_17,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_18,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_19,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_20,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_21,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_22,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_23,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_24,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_25,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_26,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_27,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_28,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_29,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_30,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_31,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_32,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_33,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_34,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_35,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_36,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_37,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_38,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_39,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_40,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_41,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_42,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_43,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_44,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_45,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_46,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_47,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_48,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_49,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_50,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_51,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_52,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_53,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_54,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_55,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_56,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_57,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_58,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_59,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_60,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_61,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_62,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_63,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_64,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_65,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_66,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_67,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_68,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_69,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_70,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_71,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_72,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_73,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_74,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_75,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_76,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_77,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_78,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_79,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_80,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_81,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_82,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_83,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_84,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_85,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_86,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_87,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_88,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_89,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_90,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_91,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_92,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_93,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_94,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_95,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_96,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_97,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_98,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_99,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_100,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_101,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_102,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_103,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_104,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_105,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_106,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_107,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_108,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_109,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_110,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_111,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_112,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_113,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_114,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_115,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_116,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_117,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_118,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_119,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_120,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_121,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_122,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_123,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_124,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_125,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_126,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_127,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_128,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_129,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_130,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_131,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_132,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_133,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_134,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_135,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_136,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_137,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_138,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_139,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_140,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_141,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_142,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_143,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_144,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_145,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_146,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_147,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_148,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_149,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_150,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_151,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_152,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_153,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_154,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_155,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_156,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_157,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_158,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_159,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_160,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_161,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_162,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_163,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_164,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_165,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_166,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_167,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_168,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_169,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_170,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_171,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_172,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_173,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_174,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_175,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_176,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_177,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_178,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_179,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_180,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_181,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_182,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_183,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_184,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_185,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_186,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_187,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_188,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_189,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_190,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_191,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_192,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_193,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_194,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_195,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_196,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_197,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_198,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_199,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_200,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_201,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_202,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_203,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_204,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_205,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_206,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_207,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_208,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_209,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_210,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_211,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_212,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_213,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_214,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_215,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_216,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_217,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_218,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_219,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_220,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_221,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_222,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_223,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_224,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_225,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_226,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_227,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_228,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_229,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_230,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_231,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_232,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_233,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_234,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_235,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_236,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_237,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_238,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_239,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_240,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_241,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_242,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_243,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_244,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_245,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_246,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_247,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_248,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_249,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_250,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_251,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_252,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_253,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_254,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_255,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_256,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_257,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_258,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_259,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_260,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_261,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_262,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_263,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_264,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_265,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_266,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_267,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_268,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_269,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_270,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_271,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_272,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_273,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_274,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_275,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_276,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_277,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_278,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_279,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_280,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_281,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_282,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_283,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_284,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_285,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_286,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_287,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_288,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_289,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_290,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_291,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_292,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_293,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_294,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_295,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_296,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_297,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_298,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_299,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_300,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_301,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_302,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_303,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_304,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_305,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_306,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_307,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_308,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_309,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_310,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_311,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_312,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_313,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_314,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_315,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_316,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_317,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_318,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_319,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_320,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_321,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_322,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_323,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_324,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_325,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_326,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_327,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_328,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_329,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_330,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_int_in_331,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_plic_in_a_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_in_a_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [2:0]  auto_plic_in_a_bits_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [1:0]  auto_plic_in_a_bits_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [12:0] auto_plic_in_a_bits_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [31:0] auto_plic_in_a_bits_address,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [7:0]  auto_plic_in_a_bits_mask,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [63:0] auto_plic_in_a_bits_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_plic_in_d_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_plic_in_d_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [2:0]  auto_plic_in_d_bits_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [1:0]  auto_plic_in_d_bits_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [12:0] auto_plic_in_d_bits_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [63:0] auto_plic_in_d_bits_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_int_out_clock_xing_in_3_sync_0,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_int_in_clock_xing_out_7_sync_0,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_int_in_clock_xing_out_6_sync_0,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_int_out_clock_xing_in_2_sync_0,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_int_in_clock_xing_out_5_sync_0,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_int_in_clock_xing_out_4_sync_0,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_int_out_clock_xing_in_1_sync_0,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_int_in_clock_xing_out_3_sync_0,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_int_in_clock_xing_out_2_sync_0,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_int_out_clock_xing_in_0_sync_0,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_int_in_clock_xing_out_1_sync_0,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_int_in_clock_xing_out_0_sync_0,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_clock_in_clock,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_clock_in_reset	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
);

  wire _intsink_3_auto_out_0;	// @[generators/rocket-chip/src/main/scala/interrupts/Crossing.scala:109:29]
  wire _intsink_2_auto_out_0;	// @[generators/rocket-chip/src/main/scala/interrupts/Crossing.scala:109:29]
  wire _intsink_1_auto_out_0;	// @[generators/rocket-chip/src/main/scala/interrupts/Crossing.scala:109:29]
  wire _intsink_auto_out_0;	// @[generators/rocket-chip/src/main/scala/interrupts/Crossing.scala:109:29]
  wire _plic_auto_int_out_7_0;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:367:46]
  wire _plic_auto_int_out_6_0;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:367:46]
  wire _plic_auto_int_out_5_0;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:367:46]
  wire _plic_auto_int_out_4_0;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:367:46]
  wire _plic_auto_int_out_3_0;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:367:46]
  wire _plic_auto_int_out_2_0;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:367:46]
  wire _plic_auto_int_out_1_0;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:367:46]
  wire _plic_auto_int_out_0_0;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:367:46]
  OCAH4CORECluster_TLPLIC plic (	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:367:46]
    .clock                  (auto_clock_in_clock),
    .reset                  (auto_clock_in_reset),
    .auto_int_in_4_0        (_intsink_3_auto_out_0),	// @[generators/rocket-chip/src/main/scala/interrupts/Crossing.scala:109:29]
    .auto_int_in_3_0        (_intsink_2_auto_out_0),	// @[generators/rocket-chip/src/main/scala/interrupts/Crossing.scala:109:29]
    .auto_int_in_2_0        (_intsink_1_auto_out_0),	// @[generators/rocket-chip/src/main/scala/interrupts/Crossing.scala:109:29]
    .auto_int_in_1_0        (_intsink_auto_out_0),	// @[generators/rocket-chip/src/main/scala/interrupts/Crossing.scala:109:29]
    .auto_int_in_0_0        (auto_plic_int_in_0),
    .auto_int_in_0_1        (auto_plic_int_in_1),
    .auto_int_in_0_2        (auto_plic_int_in_2),
    .auto_int_in_0_3        (auto_plic_int_in_3),
    .auto_int_in_0_4        (auto_plic_int_in_4),
    .auto_int_in_0_5        (auto_plic_int_in_5),
    .auto_int_in_0_6        (auto_plic_int_in_6),
    .auto_int_in_0_7        (auto_plic_int_in_7),
    .auto_int_in_0_8        (auto_plic_int_in_8),
    .auto_int_in_0_9        (auto_plic_int_in_9),
    .auto_int_in_0_10       (auto_plic_int_in_10),
    .auto_int_in_0_11       (auto_plic_int_in_11),
    .auto_int_in_0_12       (auto_plic_int_in_12),
    .auto_int_in_0_13       (auto_plic_int_in_13),
    .auto_int_in_0_14       (auto_plic_int_in_14),
    .auto_int_in_0_15       (auto_plic_int_in_15),
    .auto_int_in_0_16       (auto_plic_int_in_16),
    .auto_int_in_0_17       (auto_plic_int_in_17),
    .auto_int_in_0_18       (auto_plic_int_in_18),
    .auto_int_in_0_19       (auto_plic_int_in_19),
    .auto_int_in_0_20       (auto_plic_int_in_20),
    .auto_int_in_0_21       (auto_plic_int_in_21),
    .auto_int_in_0_22       (auto_plic_int_in_22),
    .auto_int_in_0_23       (auto_plic_int_in_23),
    .auto_int_in_0_24       (auto_plic_int_in_24),
    .auto_int_in_0_25       (auto_plic_int_in_25),
    .auto_int_in_0_26       (auto_plic_int_in_26),
    .auto_int_in_0_27       (auto_plic_int_in_27),
    .auto_int_in_0_28       (auto_plic_int_in_28),
    .auto_int_in_0_29       (auto_plic_int_in_29),
    .auto_int_in_0_30       (auto_plic_int_in_30),
    .auto_int_in_0_31       (auto_plic_int_in_31),
    .auto_int_in_0_32       (auto_plic_int_in_32),
    .auto_int_in_0_33       (auto_plic_int_in_33),
    .auto_int_in_0_34       (auto_plic_int_in_34),
    .auto_int_in_0_35       (auto_plic_int_in_35),
    .auto_int_in_0_36       (auto_plic_int_in_36),
    .auto_int_in_0_37       (auto_plic_int_in_37),
    .auto_int_in_0_38       (auto_plic_int_in_38),
    .auto_int_in_0_39       (auto_plic_int_in_39),
    .auto_int_in_0_40       (auto_plic_int_in_40),
    .auto_int_in_0_41       (auto_plic_int_in_41),
    .auto_int_in_0_42       (auto_plic_int_in_42),
    .auto_int_in_0_43       (auto_plic_int_in_43),
    .auto_int_in_0_44       (auto_plic_int_in_44),
    .auto_int_in_0_45       (auto_plic_int_in_45),
    .auto_int_in_0_46       (auto_plic_int_in_46),
    .auto_int_in_0_47       (auto_plic_int_in_47),
    .auto_int_in_0_48       (auto_plic_int_in_48),
    .auto_int_in_0_49       (auto_plic_int_in_49),
    .auto_int_in_0_50       (auto_plic_int_in_50),
    .auto_int_in_0_51       (auto_plic_int_in_51),
    .auto_int_in_0_52       (auto_plic_int_in_52),
    .auto_int_in_0_53       (auto_plic_int_in_53),
    .auto_int_in_0_54       (auto_plic_int_in_54),
    .auto_int_in_0_55       (auto_plic_int_in_55),
    .auto_int_in_0_56       (auto_plic_int_in_56),
    .auto_int_in_0_57       (auto_plic_int_in_57),
    .auto_int_in_0_58       (auto_plic_int_in_58),
    .auto_int_in_0_59       (auto_plic_int_in_59),
    .auto_int_in_0_60       (auto_plic_int_in_60),
    .auto_int_in_0_61       (auto_plic_int_in_61),
    .auto_int_in_0_62       (auto_plic_int_in_62),
    .auto_int_in_0_63       (auto_plic_int_in_63),
    .auto_int_in_0_64       (auto_plic_int_in_64),
    .auto_int_in_0_65       (auto_plic_int_in_65),
    .auto_int_in_0_66       (auto_plic_int_in_66),
    .auto_int_in_0_67       (auto_plic_int_in_67),
    .auto_int_in_0_68       (auto_plic_int_in_68),
    .auto_int_in_0_69       (auto_plic_int_in_69),
    .auto_int_in_0_70       (auto_plic_int_in_70),
    .auto_int_in_0_71       (auto_plic_int_in_71),
    .auto_int_in_0_72       (auto_plic_int_in_72),
    .auto_int_in_0_73       (auto_plic_int_in_73),
    .auto_int_in_0_74       (auto_plic_int_in_74),
    .auto_int_in_0_75       (auto_plic_int_in_75),
    .auto_int_in_0_76       (auto_plic_int_in_76),
    .auto_int_in_0_77       (auto_plic_int_in_77),
    .auto_int_in_0_78       (auto_plic_int_in_78),
    .auto_int_in_0_79       (auto_plic_int_in_79),
    .auto_int_in_0_80       (auto_plic_int_in_80),
    .auto_int_in_0_81       (auto_plic_int_in_81),
    .auto_int_in_0_82       (auto_plic_int_in_82),
    .auto_int_in_0_83       (auto_plic_int_in_83),
    .auto_int_in_0_84       (auto_plic_int_in_84),
    .auto_int_in_0_85       (auto_plic_int_in_85),
    .auto_int_in_0_86       (auto_plic_int_in_86),
    .auto_int_in_0_87       (auto_plic_int_in_87),
    .auto_int_in_0_88       (auto_plic_int_in_88),
    .auto_int_in_0_89       (auto_plic_int_in_89),
    .auto_int_in_0_90       (auto_plic_int_in_90),
    .auto_int_in_0_91       (auto_plic_int_in_91),
    .auto_int_in_0_92       (auto_plic_int_in_92),
    .auto_int_in_0_93       (auto_plic_int_in_93),
    .auto_int_in_0_94       (auto_plic_int_in_94),
    .auto_int_in_0_95       (auto_plic_int_in_95),
    .auto_int_in_0_96       (auto_plic_int_in_96),
    .auto_int_in_0_97       (auto_plic_int_in_97),
    .auto_int_in_0_98       (auto_plic_int_in_98),
    .auto_int_in_0_99       (auto_plic_int_in_99),
    .auto_int_in_0_100      (auto_plic_int_in_100),
    .auto_int_in_0_101      (auto_plic_int_in_101),
    .auto_int_in_0_102      (auto_plic_int_in_102),
    .auto_int_in_0_103      (auto_plic_int_in_103),
    .auto_int_in_0_104      (auto_plic_int_in_104),
    .auto_int_in_0_105      (auto_plic_int_in_105),
    .auto_int_in_0_106      (auto_plic_int_in_106),
    .auto_int_in_0_107      (auto_plic_int_in_107),
    .auto_int_in_0_108      (auto_plic_int_in_108),
    .auto_int_in_0_109      (auto_plic_int_in_109),
    .auto_int_in_0_110      (auto_plic_int_in_110),
    .auto_int_in_0_111      (auto_plic_int_in_111),
    .auto_int_in_0_112      (auto_plic_int_in_112),
    .auto_int_in_0_113      (auto_plic_int_in_113),
    .auto_int_in_0_114      (auto_plic_int_in_114),
    .auto_int_in_0_115      (auto_plic_int_in_115),
    .auto_int_in_0_116      (auto_plic_int_in_116),
    .auto_int_in_0_117      (auto_plic_int_in_117),
    .auto_int_in_0_118      (auto_plic_int_in_118),
    .auto_int_in_0_119      (auto_plic_int_in_119),
    .auto_int_in_0_120      (auto_plic_int_in_120),
    .auto_int_in_0_121      (auto_plic_int_in_121),
    .auto_int_in_0_122      (auto_plic_int_in_122),
    .auto_int_in_0_123      (auto_plic_int_in_123),
    .auto_int_in_0_124      (auto_plic_int_in_124),
    .auto_int_in_0_125      (auto_plic_int_in_125),
    .auto_int_in_0_126      (auto_plic_int_in_126),
    .auto_int_in_0_127      (auto_plic_int_in_127),
    .auto_int_in_0_128      (auto_plic_int_in_128),
    .auto_int_in_0_129      (auto_plic_int_in_129),
    .auto_int_in_0_130      (auto_plic_int_in_130),
    .auto_int_in_0_131      (auto_plic_int_in_131),
    .auto_int_in_0_132      (auto_plic_int_in_132),
    .auto_int_in_0_133      (auto_plic_int_in_133),
    .auto_int_in_0_134      (auto_plic_int_in_134),
    .auto_int_in_0_135      (auto_plic_int_in_135),
    .auto_int_in_0_136      (auto_plic_int_in_136),
    .auto_int_in_0_137      (auto_plic_int_in_137),
    .auto_int_in_0_138      (auto_plic_int_in_138),
    .auto_int_in_0_139      (auto_plic_int_in_139),
    .auto_int_in_0_140      (auto_plic_int_in_140),
    .auto_int_in_0_141      (auto_plic_int_in_141),
    .auto_int_in_0_142      (auto_plic_int_in_142),
    .auto_int_in_0_143      (auto_plic_int_in_143),
    .auto_int_in_0_144      (auto_plic_int_in_144),
    .auto_int_in_0_145      (auto_plic_int_in_145),
    .auto_int_in_0_146      (auto_plic_int_in_146),
    .auto_int_in_0_147      (auto_plic_int_in_147),
    .auto_int_in_0_148      (auto_plic_int_in_148),
    .auto_int_in_0_149      (auto_plic_int_in_149),
    .auto_int_in_0_150      (auto_plic_int_in_150),
    .auto_int_in_0_151      (auto_plic_int_in_151),
    .auto_int_in_0_152      (auto_plic_int_in_152),
    .auto_int_in_0_153      (auto_plic_int_in_153),
    .auto_int_in_0_154      (auto_plic_int_in_154),
    .auto_int_in_0_155      (auto_plic_int_in_155),
    .auto_int_in_0_156      (auto_plic_int_in_156),
    .auto_int_in_0_157      (auto_plic_int_in_157),
    .auto_int_in_0_158      (auto_plic_int_in_158),
    .auto_int_in_0_159      (auto_plic_int_in_159),
    .auto_int_in_0_160      (auto_plic_int_in_160),
    .auto_int_in_0_161      (auto_plic_int_in_161),
    .auto_int_in_0_162      (auto_plic_int_in_162),
    .auto_int_in_0_163      (auto_plic_int_in_163),
    .auto_int_in_0_164      (auto_plic_int_in_164),
    .auto_int_in_0_165      (auto_plic_int_in_165),
    .auto_int_in_0_166      (auto_plic_int_in_166),
    .auto_int_in_0_167      (auto_plic_int_in_167),
    .auto_int_in_0_168      (auto_plic_int_in_168),
    .auto_int_in_0_169      (auto_plic_int_in_169),
    .auto_int_in_0_170      (auto_plic_int_in_170),
    .auto_int_in_0_171      (auto_plic_int_in_171),
    .auto_int_in_0_172      (auto_plic_int_in_172),
    .auto_int_in_0_173      (auto_plic_int_in_173),
    .auto_int_in_0_174      (auto_plic_int_in_174),
    .auto_int_in_0_175      (auto_plic_int_in_175),
    .auto_int_in_0_176      (auto_plic_int_in_176),
    .auto_int_in_0_177      (auto_plic_int_in_177),
    .auto_int_in_0_178      (auto_plic_int_in_178),
    .auto_int_in_0_179      (auto_plic_int_in_179),
    .auto_int_in_0_180      (auto_plic_int_in_180),
    .auto_int_in_0_181      (auto_plic_int_in_181),
    .auto_int_in_0_182      (auto_plic_int_in_182),
    .auto_int_in_0_183      (auto_plic_int_in_183),
    .auto_int_in_0_184      (auto_plic_int_in_184),
    .auto_int_in_0_185      (auto_plic_int_in_185),
    .auto_int_in_0_186      (auto_plic_int_in_186),
    .auto_int_in_0_187      (auto_plic_int_in_187),
    .auto_int_in_0_188      (auto_plic_int_in_188),
    .auto_int_in_0_189      (auto_plic_int_in_189),
    .auto_int_in_0_190      (auto_plic_int_in_190),
    .auto_int_in_0_191      (auto_plic_int_in_191),
    .auto_int_in_0_192      (auto_plic_int_in_192),
    .auto_int_in_0_193      (auto_plic_int_in_193),
    .auto_int_in_0_194      (auto_plic_int_in_194),
    .auto_int_in_0_195      (auto_plic_int_in_195),
    .auto_int_in_0_196      (auto_plic_int_in_196),
    .auto_int_in_0_197      (auto_plic_int_in_197),
    .auto_int_in_0_198      (auto_plic_int_in_198),
    .auto_int_in_0_199      (auto_plic_int_in_199),
    .auto_int_in_0_200      (auto_plic_int_in_200),
    .auto_int_in_0_201      (auto_plic_int_in_201),
    .auto_int_in_0_202      (auto_plic_int_in_202),
    .auto_int_in_0_203      (auto_plic_int_in_203),
    .auto_int_in_0_204      (auto_plic_int_in_204),
    .auto_int_in_0_205      (auto_plic_int_in_205),
    .auto_int_in_0_206      (auto_plic_int_in_206),
    .auto_int_in_0_207      (auto_plic_int_in_207),
    .auto_int_in_0_208      (auto_plic_int_in_208),
    .auto_int_in_0_209      (auto_plic_int_in_209),
    .auto_int_in_0_210      (auto_plic_int_in_210),
    .auto_int_in_0_211      (auto_plic_int_in_211),
    .auto_int_in_0_212      (auto_plic_int_in_212),
    .auto_int_in_0_213      (auto_plic_int_in_213),
    .auto_int_in_0_214      (auto_plic_int_in_214),
    .auto_int_in_0_215      (auto_plic_int_in_215),
    .auto_int_in_0_216      (auto_plic_int_in_216),
    .auto_int_in_0_217      (auto_plic_int_in_217),
    .auto_int_in_0_218      (auto_plic_int_in_218),
    .auto_int_in_0_219      (auto_plic_int_in_219),
    .auto_int_in_0_220      (auto_plic_int_in_220),
    .auto_int_in_0_221      (auto_plic_int_in_221),
    .auto_int_in_0_222      (auto_plic_int_in_222),
    .auto_int_in_0_223      (auto_plic_int_in_223),
    .auto_int_in_0_224      (auto_plic_int_in_224),
    .auto_int_in_0_225      (auto_plic_int_in_225),
    .auto_int_in_0_226      (auto_plic_int_in_226),
    .auto_int_in_0_227      (auto_plic_int_in_227),
    .auto_int_in_0_228      (auto_plic_int_in_228),
    .auto_int_in_0_229      (auto_plic_int_in_229),
    .auto_int_in_0_230      (auto_plic_int_in_230),
    .auto_int_in_0_231      (auto_plic_int_in_231),
    .auto_int_in_0_232      (auto_plic_int_in_232),
    .auto_int_in_0_233      (auto_plic_int_in_233),
    .auto_int_in_0_234      (auto_plic_int_in_234),
    .auto_int_in_0_235      (auto_plic_int_in_235),
    .auto_int_in_0_236      (auto_plic_int_in_236),
    .auto_int_in_0_237      (auto_plic_int_in_237),
    .auto_int_in_0_238      (auto_plic_int_in_238),
    .auto_int_in_0_239      (auto_plic_int_in_239),
    .auto_int_in_0_240      (auto_plic_int_in_240),
    .auto_int_in_0_241      (auto_plic_int_in_241),
    .auto_int_in_0_242      (auto_plic_int_in_242),
    .auto_int_in_0_243      (auto_plic_int_in_243),
    .auto_int_in_0_244      (auto_plic_int_in_244),
    .auto_int_in_0_245      (auto_plic_int_in_245),
    .auto_int_in_0_246      (auto_plic_int_in_246),
    .auto_int_in_0_247      (auto_plic_int_in_247),
    .auto_int_in_0_248      (auto_plic_int_in_248),
    .auto_int_in_0_249      (auto_plic_int_in_249),
    .auto_int_in_0_250      (auto_plic_int_in_250),
    .auto_int_in_0_251      (auto_plic_int_in_251),
    .auto_int_in_0_252      (auto_plic_int_in_252),
    .auto_int_in_0_253      (auto_plic_int_in_253),
    .auto_int_in_0_254      (auto_plic_int_in_254),
    .auto_int_in_0_255      (auto_plic_int_in_255),
    .auto_int_in_0_256      (auto_plic_int_in_256),
    .auto_int_in_0_257      (auto_plic_int_in_257),
    .auto_int_in_0_258      (auto_plic_int_in_258),
    .auto_int_in_0_259      (auto_plic_int_in_259),
    .auto_int_in_0_260      (auto_plic_int_in_260),
    .auto_int_in_0_261      (auto_plic_int_in_261),
    .auto_int_in_0_262      (auto_plic_int_in_262),
    .auto_int_in_0_263      (auto_plic_int_in_263),
    .auto_int_in_0_264      (auto_plic_int_in_264),
    .auto_int_in_0_265      (auto_plic_int_in_265),
    .auto_int_in_0_266      (auto_plic_int_in_266),
    .auto_int_in_0_267      (auto_plic_int_in_267),
    .auto_int_in_0_268      (auto_plic_int_in_268),
    .auto_int_in_0_269      (auto_plic_int_in_269),
    .auto_int_in_0_270      (auto_plic_int_in_270),
    .auto_int_in_0_271      (auto_plic_int_in_271),
    .auto_int_in_0_272      (auto_plic_int_in_272),
    .auto_int_in_0_273      (auto_plic_int_in_273),
    .auto_int_in_0_274      (auto_plic_int_in_274),
    .auto_int_in_0_275      (auto_plic_int_in_275),
    .auto_int_in_0_276      (auto_plic_int_in_276),
    .auto_int_in_0_277      (auto_plic_int_in_277),
    .auto_int_in_0_278      (auto_plic_int_in_278),
    .auto_int_in_0_279      (auto_plic_int_in_279),
    .auto_int_in_0_280      (auto_plic_int_in_280),
    .auto_int_in_0_281      (auto_plic_int_in_281),
    .auto_int_in_0_282      (auto_plic_int_in_282),
    .auto_int_in_0_283      (auto_plic_int_in_283),
    .auto_int_in_0_284      (auto_plic_int_in_284),
    .auto_int_in_0_285      (auto_plic_int_in_285),
    .auto_int_in_0_286      (auto_plic_int_in_286),
    .auto_int_in_0_287      (auto_plic_int_in_287),
    .auto_int_in_0_288      (auto_plic_int_in_288),
    .auto_int_in_0_289      (auto_plic_int_in_289),
    .auto_int_in_0_290      (auto_plic_int_in_290),
    .auto_int_in_0_291      (auto_plic_int_in_291),
    .auto_int_in_0_292      (auto_plic_int_in_292),
    .auto_int_in_0_293      (auto_plic_int_in_293),
    .auto_int_in_0_294      (auto_plic_int_in_294),
    .auto_int_in_0_295      (auto_plic_int_in_295),
    .auto_int_in_0_296      (auto_plic_int_in_296),
    .auto_int_in_0_297      (auto_plic_int_in_297),
    .auto_int_in_0_298      (auto_plic_int_in_298),
    .auto_int_in_0_299      (auto_plic_int_in_299),
    .auto_int_in_0_300      (auto_plic_int_in_300),
    .auto_int_in_0_301      (auto_plic_int_in_301),
    .auto_int_in_0_302      (auto_plic_int_in_302),
    .auto_int_in_0_303      (auto_plic_int_in_303),
    .auto_int_in_0_304      (auto_plic_int_in_304),
    .auto_int_in_0_305      (auto_plic_int_in_305),
    .auto_int_in_0_306      (auto_plic_int_in_306),
    .auto_int_in_0_307      (auto_plic_int_in_307),
    .auto_int_in_0_308      (auto_plic_int_in_308),
    .auto_int_in_0_309      (auto_plic_int_in_309),
    .auto_int_in_0_310      (auto_plic_int_in_310),
    .auto_int_in_0_311      (auto_plic_int_in_311),
    .auto_int_in_0_312      (auto_plic_int_in_312),
    .auto_int_in_0_313      (auto_plic_int_in_313),
    .auto_int_in_0_314      (auto_plic_int_in_314),
    .auto_int_in_0_315      (auto_plic_int_in_315),
    .auto_int_in_0_316      (auto_plic_int_in_316),
    .auto_int_in_0_317      (auto_plic_int_in_317),
    .auto_int_in_0_318      (auto_plic_int_in_318),
    .auto_int_in_0_319      (auto_plic_int_in_319),
    .auto_int_in_0_320      (auto_plic_int_in_320),
    .auto_int_in_0_321      (auto_plic_int_in_321),
    .auto_int_in_0_322      (auto_plic_int_in_322),
    .auto_int_in_0_323      (auto_plic_int_in_323),
    .auto_int_in_0_324      (auto_plic_int_in_324),
    .auto_int_in_0_325      (auto_plic_int_in_325),
    .auto_int_in_0_326      (auto_plic_int_in_326),
    .auto_int_in_0_327      (auto_plic_int_in_327),
    .auto_int_in_0_328      (auto_plic_int_in_328),
    .auto_int_in_0_329      (auto_plic_int_in_329),
    .auto_int_in_0_330      (auto_plic_int_in_330),
    .auto_int_in_0_331      (auto_plic_int_in_331),
    .auto_int_out_7_0       (_plic_auto_int_out_7_0),
    .auto_int_out_6_0       (_plic_auto_int_out_6_0),
    .auto_int_out_5_0       (_plic_auto_int_out_5_0),
    .auto_int_out_4_0       (_plic_auto_int_out_4_0),
    .auto_int_out_3_0       (_plic_auto_int_out_3_0),
    .auto_int_out_2_0       (_plic_auto_int_out_2_0),
    .auto_int_out_1_0       (_plic_auto_int_out_1_0),
    .auto_int_out_0_0       (_plic_auto_int_out_0_0),
    .auto_in_a_ready        (auto_plic_in_a_ready),
    .auto_in_a_valid        (auto_plic_in_a_valid),
    .auto_in_a_bits_opcode  (auto_plic_in_a_bits_opcode),
    .auto_in_a_bits_size    (auto_plic_in_a_bits_size),
    .auto_in_a_bits_source  (auto_plic_in_a_bits_source),
    .auto_in_a_bits_address (auto_plic_in_a_bits_address),
    .auto_in_a_bits_mask    (auto_plic_in_a_bits_mask),
    .auto_in_a_bits_data    (auto_plic_in_a_bits_data),
    .auto_in_d_ready        (auto_plic_in_d_ready),
    .auto_in_d_valid        (auto_plic_in_d_valid),
    .auto_in_d_bits_opcode  (auto_plic_in_d_bits_opcode),
    .auto_in_d_bits_size    (auto_plic_in_d_bits_size),
    .auto_in_d_bits_source  (auto_plic_in_d_bits_source),
    .auto_in_d_bits_data    (auto_plic_in_d_bits_data)
  );
  OCAH4CORECluster_IntSyncCrossingSource_n1x1 intsource (	// @[generators/rocket-chip/src/main/scala/interrupts/Crossing.scala:29:31]
    .clock           (auto_clock_in_clock),
    .reset           (auto_clock_in_reset),
    .auto_in_0       (_plic_auto_int_out_0_0),	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:367:46]
    .auto_out_sync_0 (auto_int_in_clock_xing_out_0_sync_0)
  );
  OCAH4CORECluster_IntSyncCrossingSource_n1x1 intsource_1 (	// @[generators/rocket-chip/src/main/scala/interrupts/Crossing.scala:29:31]
    .clock           (auto_clock_in_clock),
    .reset           (auto_clock_in_reset),
    .auto_in_0       (_plic_auto_int_out_4_0),	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:367:46]
    .auto_out_sync_0 (auto_int_in_clock_xing_out_1_sync_0)
  );
  OCAH4CORECluster_IntSyncSyncCrossingSink_n1x1 intsink (	// @[generators/rocket-chip/src/main/scala/interrupts/Crossing.scala:109:29]
    .auto_in_sync_0 (auto_int_out_clock_xing_in_0_sync_0),
    .auto_out_0     (_intsink_auto_out_0)
  );
  OCAH4CORECluster_IntSyncCrossingSource_n1x1 intsource_2 (	// @[generators/rocket-chip/src/main/scala/interrupts/Crossing.scala:29:31]
    .clock           (auto_clock_in_clock),
    .reset           (auto_clock_in_reset),
    .auto_in_0       (_plic_auto_int_out_1_0),	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:367:46]
    .auto_out_sync_0 (auto_int_in_clock_xing_out_2_sync_0)
  );
  OCAH4CORECluster_IntSyncCrossingSource_n1x1 intsource_3 (	// @[generators/rocket-chip/src/main/scala/interrupts/Crossing.scala:29:31]
    .clock           (auto_clock_in_clock),
    .reset           (auto_clock_in_reset),
    .auto_in_0       (_plic_auto_int_out_5_0),	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:367:46]
    .auto_out_sync_0 (auto_int_in_clock_xing_out_3_sync_0)
  );
  OCAH4CORECluster_IntSyncSyncCrossingSink_n1x1 intsink_1 (	// @[generators/rocket-chip/src/main/scala/interrupts/Crossing.scala:109:29]
    .auto_in_sync_0 (auto_int_out_clock_xing_in_1_sync_0),
    .auto_out_0     (_intsink_1_auto_out_0)
  );
  OCAH4CORECluster_IntSyncCrossingSource_n1x1 intsource_4 (	// @[generators/rocket-chip/src/main/scala/interrupts/Crossing.scala:29:31]
    .clock           (auto_clock_in_clock),
    .reset           (auto_clock_in_reset),
    .auto_in_0       (_plic_auto_int_out_2_0),	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:367:46]
    .auto_out_sync_0 (auto_int_in_clock_xing_out_4_sync_0)
  );
  OCAH4CORECluster_IntSyncCrossingSource_n1x1 intsource_5 (	// @[generators/rocket-chip/src/main/scala/interrupts/Crossing.scala:29:31]
    .clock           (auto_clock_in_clock),
    .reset           (auto_clock_in_reset),
    .auto_in_0       (_plic_auto_int_out_6_0),	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:367:46]
    .auto_out_sync_0 (auto_int_in_clock_xing_out_5_sync_0)
  );
  OCAH4CORECluster_IntSyncSyncCrossingSink_n1x1 intsink_2 (	// @[generators/rocket-chip/src/main/scala/interrupts/Crossing.scala:109:29]
    .auto_in_sync_0 (auto_int_out_clock_xing_in_2_sync_0),
    .auto_out_0     (_intsink_2_auto_out_0)
  );
  OCAH4CORECluster_IntSyncCrossingSource_n1x1 intsource_6 (	// @[generators/rocket-chip/src/main/scala/interrupts/Crossing.scala:29:31]
    .clock           (auto_clock_in_clock),
    .reset           (auto_clock_in_reset),
    .auto_in_0       (_plic_auto_int_out_3_0),	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:367:46]
    .auto_out_sync_0 (auto_int_in_clock_xing_out_6_sync_0)
  );
  OCAH4CORECluster_IntSyncCrossingSource_n1x1 intsource_7 (	// @[generators/rocket-chip/src/main/scala/interrupts/Crossing.scala:29:31]
    .clock           (auto_clock_in_clock),
    .reset           (auto_clock_in_reset),
    .auto_in_0       (_plic_auto_int_out_7_0),	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:367:46]
    .auto_out_sync_0 (auto_int_in_clock_xing_out_7_sync_0)
  );
  OCAH4CORECluster_IntSyncSyncCrossingSink_n1x1 intsink_3 (	// @[generators/rocket-chip/src/main/scala/interrupts/Crossing.scala:109:29]
    .auto_in_sync_0 (auto_int_out_clock_xing_in_3_sync_0),
    .auto_out_0     (_intsink_3_auto_out_0)
  );
endmodule

