// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 Tenstorrent USA, Inc.

// Generated by CIRCT unknown git version
// Standard header to adapt well known macros to our needs.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

module OCAH4CORECluster_PeripheryBus_pbus(	// @[generators/rocket-chip/src/main/scala/prci/ClockDomain.scala:14:9]
  input         auto_coupler_to_device_named_wdt_3_control_xing_out_a_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_coupler_to_device_named_wdt_3_control_xing_out_a_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [2:0]  auto_coupler_to_device_named_wdt_3_control_xing_out_a_bits_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [1:0]  auto_coupler_to_device_named_wdt_3_control_xing_out_a_bits_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [12:0] auto_coupler_to_device_named_wdt_3_control_xing_out_a_bits_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [31:0] auto_coupler_to_device_named_wdt_3_control_xing_out_a_bits_address,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [7:0]  auto_coupler_to_device_named_wdt_3_control_xing_out_a_bits_mask,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [63:0] auto_coupler_to_device_named_wdt_3_control_xing_out_a_bits_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_coupler_to_device_named_wdt_3_control_xing_out_d_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_coupler_to_device_named_wdt_3_control_xing_out_d_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [2:0]  auto_coupler_to_device_named_wdt_3_control_xing_out_d_bits_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [1:0]  auto_coupler_to_device_named_wdt_3_control_xing_out_d_bits_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [12:0] auto_coupler_to_device_named_wdt_3_control_xing_out_d_bits_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [63:0] auto_coupler_to_device_named_wdt_3_control_xing_out_d_bits_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_coupler_to_device_named_wdt_2_control_xing_out_a_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_coupler_to_device_named_wdt_2_control_xing_out_a_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [2:0]  auto_coupler_to_device_named_wdt_2_control_xing_out_a_bits_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [1:0]  auto_coupler_to_device_named_wdt_2_control_xing_out_a_bits_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [12:0] auto_coupler_to_device_named_wdt_2_control_xing_out_a_bits_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [31:0] auto_coupler_to_device_named_wdt_2_control_xing_out_a_bits_address,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [7:0]  auto_coupler_to_device_named_wdt_2_control_xing_out_a_bits_mask,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [63:0] auto_coupler_to_device_named_wdt_2_control_xing_out_a_bits_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_coupler_to_device_named_wdt_2_control_xing_out_d_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_coupler_to_device_named_wdt_2_control_xing_out_d_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [2:0]  auto_coupler_to_device_named_wdt_2_control_xing_out_d_bits_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [1:0]  auto_coupler_to_device_named_wdt_2_control_xing_out_d_bits_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [12:0] auto_coupler_to_device_named_wdt_2_control_xing_out_d_bits_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [63:0] auto_coupler_to_device_named_wdt_2_control_xing_out_d_bits_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_coupler_to_device_named_wdt_1_control_xing_out_a_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_coupler_to_device_named_wdt_1_control_xing_out_a_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [2:0]  auto_coupler_to_device_named_wdt_1_control_xing_out_a_bits_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [1:0]  auto_coupler_to_device_named_wdt_1_control_xing_out_a_bits_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [12:0] auto_coupler_to_device_named_wdt_1_control_xing_out_a_bits_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [31:0] auto_coupler_to_device_named_wdt_1_control_xing_out_a_bits_address,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [7:0]  auto_coupler_to_device_named_wdt_1_control_xing_out_a_bits_mask,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [63:0] auto_coupler_to_device_named_wdt_1_control_xing_out_a_bits_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_coupler_to_device_named_wdt_1_control_xing_out_d_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_coupler_to_device_named_wdt_1_control_xing_out_d_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [2:0]  auto_coupler_to_device_named_wdt_1_control_xing_out_d_bits_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [1:0]  auto_coupler_to_device_named_wdt_1_control_xing_out_d_bits_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [12:0] auto_coupler_to_device_named_wdt_1_control_xing_out_d_bits_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [63:0] auto_coupler_to_device_named_wdt_1_control_xing_out_d_bits_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_coupler_to_device_named_wdt_0_control_xing_out_a_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_coupler_to_device_named_wdt_0_control_xing_out_a_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [2:0]  auto_coupler_to_device_named_wdt_0_control_xing_out_a_bits_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [1:0]  auto_coupler_to_device_named_wdt_0_control_xing_out_a_bits_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [12:0] auto_coupler_to_device_named_wdt_0_control_xing_out_a_bits_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [31:0] auto_coupler_to_device_named_wdt_0_control_xing_out_a_bits_address,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [7:0]  auto_coupler_to_device_named_wdt_0_control_xing_out_a_bits_mask,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [63:0] auto_coupler_to_device_named_wdt_0_control_xing_out_a_bits_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_coupler_to_device_named_wdt_0_control_xing_out_d_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_coupler_to_device_named_wdt_0_control_xing_out_d_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [2:0]  auto_coupler_to_device_named_wdt_0_control_xing_out_d_bits_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [1:0]  auto_coupler_to_device_named_wdt_0_control_xing_out_d_bits_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [12:0] auto_coupler_to_device_named_wdt_0_control_xing_out_d_bits_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [63:0] auto_coupler_to_device_named_wdt_0_control_xing_out_d_bits_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_fixedClockNode_anon_out_3_clock,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_fixedClockNode_anon_out_3_reset,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_fixedClockNode_anon_out_2_clock,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_fixedClockNode_anon_out_2_reset,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_fixedClockNode_anon_out_1_clock,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_fixedClockNode_anon_out_1_reset,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_fixedClockNode_anon_out_0_clock,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_fixedClockNode_anon_out_0_reset,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_pbus_clock_groups_in_member_pbus_0_clock,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_pbus_clock_groups_in_member_pbus_0_reset,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_bus_xing_in_a_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_bus_xing_in_a_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [2:0]  auto_bus_xing_in_a_bits_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [2:0]  auto_bus_xing_in_a_bits_param,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [2:0]  auto_bus_xing_in_a_bits_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [8:0]  auto_bus_xing_in_a_bits_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [31:0] auto_bus_xing_in_a_bits_address,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [7:0]  auto_bus_xing_in_a_bits_mask,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [63:0] auto_bus_xing_in_a_bits_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_bus_xing_in_a_bits_corrupt,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_bus_xing_in_d_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_bus_xing_in_d_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [2:0]  auto_bus_xing_in_d_bits_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [1:0]  auto_bus_xing_in_d_bits_param,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [2:0]  auto_bus_xing_in_d_bits_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [8:0]  auto_bus_xing_in_d_bits_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_bus_xing_in_d_bits_sink,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_bus_xing_in_d_bits_denied,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [63:0] auto_bus_xing_in_d_bits_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_bus_xing_in_d_bits_corrupt	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
);

  wire        _coupler_to_device_named_wdt_3_auto_tl_in_a_ready;	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
  wire        _coupler_to_device_named_wdt_3_auto_tl_in_d_valid;	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
  wire [2:0]  _coupler_to_device_named_wdt_3_auto_tl_in_d_bits_opcode;	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
  wire [2:0]  _coupler_to_device_named_wdt_3_auto_tl_in_d_bits_size;	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
  wire [8:0]  _coupler_to_device_named_wdt_3_auto_tl_in_d_bits_source;	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
  wire [63:0] _coupler_to_device_named_wdt_3_auto_tl_in_d_bits_data;	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
  wire        _coupler_to_device_named_wdt_2_auto_tl_in_a_ready;	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
  wire        _coupler_to_device_named_wdt_2_auto_tl_in_d_valid;	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
  wire [2:0]  _coupler_to_device_named_wdt_2_auto_tl_in_d_bits_opcode;	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
  wire [2:0]  _coupler_to_device_named_wdt_2_auto_tl_in_d_bits_size;	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
  wire [8:0]  _coupler_to_device_named_wdt_2_auto_tl_in_d_bits_source;	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
  wire [63:0] _coupler_to_device_named_wdt_2_auto_tl_in_d_bits_data;	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
  wire        _coupler_to_device_named_wdt_1_auto_tl_in_a_ready;	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
  wire        _coupler_to_device_named_wdt_1_auto_tl_in_d_valid;	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
  wire [2:0]  _coupler_to_device_named_wdt_1_auto_tl_in_d_bits_opcode;	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
  wire [2:0]  _coupler_to_device_named_wdt_1_auto_tl_in_d_bits_size;	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
  wire [8:0]  _coupler_to_device_named_wdt_1_auto_tl_in_d_bits_source;	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
  wire [63:0] _coupler_to_device_named_wdt_1_auto_tl_in_d_bits_data;	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
  wire        _coupler_to_device_named_wdt_0_auto_tl_in_a_ready;	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
  wire        _coupler_to_device_named_wdt_0_auto_tl_in_d_valid;	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
  wire [2:0]  _coupler_to_device_named_wdt_0_auto_tl_in_d_bits_opcode;	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
  wire [2:0]  _coupler_to_device_named_wdt_0_auto_tl_in_d_bits_size;	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
  wire [8:0]  _coupler_to_device_named_wdt_0_auto_tl_in_d_bits_source;	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
  wire [63:0] _coupler_to_device_named_wdt_0_auto_tl_in_d_bits_data;	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
  wire        _atomics_auto_out_a_valid;	// @[generators/rocket-chip/src/main/scala/tilelink/AtomicAutomata.scala:289:29]
  wire [2:0]  _atomics_auto_out_a_bits_opcode;	// @[generators/rocket-chip/src/main/scala/tilelink/AtomicAutomata.scala:289:29]
  wire [2:0]  _atomics_auto_out_a_bits_param;	// @[generators/rocket-chip/src/main/scala/tilelink/AtomicAutomata.scala:289:29]
  wire [2:0]  _atomics_auto_out_a_bits_size;	// @[generators/rocket-chip/src/main/scala/tilelink/AtomicAutomata.scala:289:29]
  wire [8:0]  _atomics_auto_out_a_bits_source;	// @[generators/rocket-chip/src/main/scala/tilelink/AtomicAutomata.scala:289:29]
  wire [31:0] _atomics_auto_out_a_bits_address;	// @[generators/rocket-chip/src/main/scala/tilelink/AtomicAutomata.scala:289:29]
  wire [7:0]  _atomics_auto_out_a_bits_mask;	// @[generators/rocket-chip/src/main/scala/tilelink/AtomicAutomata.scala:289:29]
  wire [63:0] _atomics_auto_out_a_bits_data;	// @[generators/rocket-chip/src/main/scala/tilelink/AtomicAutomata.scala:289:29]
  wire        _atomics_auto_out_a_bits_corrupt;	// @[generators/rocket-chip/src/main/scala/tilelink/AtomicAutomata.scala:289:29]
  wire        _atomics_auto_out_d_ready;	// @[generators/rocket-chip/src/main/scala/tilelink/AtomicAutomata.scala:289:29]
  wire        _buffer_auto_in_a_ready;	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:75:28]
  wire        _buffer_auto_in_d_valid;	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:75:28]
  wire [2:0]  _buffer_auto_in_d_bits_opcode;	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:75:28]
  wire [1:0]  _buffer_auto_in_d_bits_param;	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:75:28]
  wire [2:0]  _buffer_auto_in_d_bits_size;	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:75:28]
  wire [8:0]  _buffer_auto_in_d_bits_source;	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:75:28]
  wire        _buffer_auto_in_d_bits_sink;	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:75:28]
  wire        _buffer_auto_in_d_bits_denied;	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:75:28]
  wire [63:0] _buffer_auto_in_d_bits_data;	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:75:28]
  wire        _buffer_auto_in_d_bits_corrupt;	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:75:28]
  wire        _buffer_auto_out_a_valid;	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:75:28]
  wire [2:0]  _buffer_auto_out_a_bits_opcode;	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:75:28]
  wire [2:0]  _buffer_auto_out_a_bits_size;	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:75:28]
  wire [8:0]  _buffer_auto_out_a_bits_source;	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:75:28]
  wire [31:0] _buffer_auto_out_a_bits_address;	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:75:28]
  wire [7:0]  _buffer_auto_out_a_bits_mask;	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:75:28]
  wire [63:0] _buffer_auto_out_a_bits_data;	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:75:28]
  wire        _buffer_auto_out_d_ready;	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:75:28]
  wire        _out_xbar_auto_anon_in_a_ready;	// @[generators/rocket-chip/src/main/scala/subsystem/PeripheryBus.scala:57:30]
  wire        _out_xbar_auto_anon_in_d_valid;	// @[generators/rocket-chip/src/main/scala/subsystem/PeripheryBus.scala:57:30]
  wire [2:0]  _out_xbar_auto_anon_in_d_bits_opcode;	// @[generators/rocket-chip/src/main/scala/subsystem/PeripheryBus.scala:57:30]
  wire [2:0]  _out_xbar_auto_anon_in_d_bits_size;	// @[generators/rocket-chip/src/main/scala/subsystem/PeripheryBus.scala:57:30]
  wire [8:0]  _out_xbar_auto_anon_in_d_bits_source;	// @[generators/rocket-chip/src/main/scala/subsystem/PeripheryBus.scala:57:30]
  wire [63:0] _out_xbar_auto_anon_in_d_bits_data;	// @[generators/rocket-chip/src/main/scala/subsystem/PeripheryBus.scala:57:30]
  wire        _out_xbar_auto_anon_out_3_a_valid;	// @[generators/rocket-chip/src/main/scala/subsystem/PeripheryBus.scala:57:30]
  wire [2:0]  _out_xbar_auto_anon_out_3_a_bits_opcode;	// @[generators/rocket-chip/src/main/scala/subsystem/PeripheryBus.scala:57:30]
  wire [2:0]  _out_xbar_auto_anon_out_3_a_bits_size;	// @[generators/rocket-chip/src/main/scala/subsystem/PeripheryBus.scala:57:30]
  wire [8:0]  _out_xbar_auto_anon_out_3_a_bits_source;	// @[generators/rocket-chip/src/main/scala/subsystem/PeripheryBus.scala:57:30]
  wire [31:0] _out_xbar_auto_anon_out_3_a_bits_address;	// @[generators/rocket-chip/src/main/scala/subsystem/PeripheryBus.scala:57:30]
  wire [7:0]  _out_xbar_auto_anon_out_3_a_bits_mask;	// @[generators/rocket-chip/src/main/scala/subsystem/PeripheryBus.scala:57:30]
  wire [63:0] _out_xbar_auto_anon_out_3_a_bits_data;	// @[generators/rocket-chip/src/main/scala/subsystem/PeripheryBus.scala:57:30]
  wire        _out_xbar_auto_anon_out_3_d_ready;	// @[generators/rocket-chip/src/main/scala/subsystem/PeripheryBus.scala:57:30]
  wire        _out_xbar_auto_anon_out_2_a_valid;	// @[generators/rocket-chip/src/main/scala/subsystem/PeripheryBus.scala:57:30]
  wire [2:0]  _out_xbar_auto_anon_out_2_a_bits_opcode;	// @[generators/rocket-chip/src/main/scala/subsystem/PeripheryBus.scala:57:30]
  wire [2:0]  _out_xbar_auto_anon_out_2_a_bits_size;	// @[generators/rocket-chip/src/main/scala/subsystem/PeripheryBus.scala:57:30]
  wire [8:0]  _out_xbar_auto_anon_out_2_a_bits_source;	// @[generators/rocket-chip/src/main/scala/subsystem/PeripheryBus.scala:57:30]
  wire [31:0] _out_xbar_auto_anon_out_2_a_bits_address;	// @[generators/rocket-chip/src/main/scala/subsystem/PeripheryBus.scala:57:30]
  wire [7:0]  _out_xbar_auto_anon_out_2_a_bits_mask;	// @[generators/rocket-chip/src/main/scala/subsystem/PeripheryBus.scala:57:30]
  wire [63:0] _out_xbar_auto_anon_out_2_a_bits_data;	// @[generators/rocket-chip/src/main/scala/subsystem/PeripheryBus.scala:57:30]
  wire        _out_xbar_auto_anon_out_2_d_ready;	// @[generators/rocket-chip/src/main/scala/subsystem/PeripheryBus.scala:57:30]
  wire        _out_xbar_auto_anon_out_1_a_valid;	// @[generators/rocket-chip/src/main/scala/subsystem/PeripheryBus.scala:57:30]
  wire [2:0]  _out_xbar_auto_anon_out_1_a_bits_opcode;	// @[generators/rocket-chip/src/main/scala/subsystem/PeripheryBus.scala:57:30]
  wire [2:0]  _out_xbar_auto_anon_out_1_a_bits_size;	// @[generators/rocket-chip/src/main/scala/subsystem/PeripheryBus.scala:57:30]
  wire [8:0]  _out_xbar_auto_anon_out_1_a_bits_source;	// @[generators/rocket-chip/src/main/scala/subsystem/PeripheryBus.scala:57:30]
  wire [31:0] _out_xbar_auto_anon_out_1_a_bits_address;	// @[generators/rocket-chip/src/main/scala/subsystem/PeripheryBus.scala:57:30]
  wire [7:0]  _out_xbar_auto_anon_out_1_a_bits_mask;	// @[generators/rocket-chip/src/main/scala/subsystem/PeripheryBus.scala:57:30]
  wire [63:0] _out_xbar_auto_anon_out_1_a_bits_data;	// @[generators/rocket-chip/src/main/scala/subsystem/PeripheryBus.scala:57:30]
  wire        _out_xbar_auto_anon_out_1_d_ready;	// @[generators/rocket-chip/src/main/scala/subsystem/PeripheryBus.scala:57:30]
  wire        _out_xbar_auto_anon_out_0_a_valid;	// @[generators/rocket-chip/src/main/scala/subsystem/PeripheryBus.scala:57:30]
  wire [2:0]  _out_xbar_auto_anon_out_0_a_bits_opcode;	// @[generators/rocket-chip/src/main/scala/subsystem/PeripheryBus.scala:57:30]
  wire [2:0]  _out_xbar_auto_anon_out_0_a_bits_size;	// @[generators/rocket-chip/src/main/scala/subsystem/PeripheryBus.scala:57:30]
  wire [8:0]  _out_xbar_auto_anon_out_0_a_bits_source;	// @[generators/rocket-chip/src/main/scala/subsystem/PeripheryBus.scala:57:30]
  wire [31:0] _out_xbar_auto_anon_out_0_a_bits_address;	// @[generators/rocket-chip/src/main/scala/subsystem/PeripheryBus.scala:57:30]
  wire [7:0]  _out_xbar_auto_anon_out_0_a_bits_mask;	// @[generators/rocket-chip/src/main/scala/subsystem/PeripheryBus.scala:57:30]
  wire [63:0] _out_xbar_auto_anon_out_0_a_bits_data;	// @[generators/rocket-chip/src/main/scala/subsystem/PeripheryBus.scala:57:30]
  wire        _out_xbar_auto_anon_out_0_d_ready;	// @[generators/rocket-chip/src/main/scala/subsystem/PeripheryBus.scala:57:30]
  wire        _fixer_auto_anon_in_a_ready;	// @[generators/rocket-chip/src/main/scala/subsystem/PeripheryBus.scala:54:33]
  wire        _fixer_auto_anon_in_d_valid;	// @[generators/rocket-chip/src/main/scala/subsystem/PeripheryBus.scala:54:33]
  wire [2:0]  _fixer_auto_anon_in_d_bits_opcode;	// @[generators/rocket-chip/src/main/scala/subsystem/PeripheryBus.scala:54:33]
  wire [2:0]  _fixer_auto_anon_in_d_bits_size;	// @[generators/rocket-chip/src/main/scala/subsystem/PeripheryBus.scala:54:33]
  wire [8:0]  _fixer_auto_anon_in_d_bits_source;	// @[generators/rocket-chip/src/main/scala/subsystem/PeripheryBus.scala:54:33]
  wire [63:0] _fixer_auto_anon_in_d_bits_data;	// @[generators/rocket-chip/src/main/scala/subsystem/PeripheryBus.scala:54:33]
  wire        _fixer_auto_anon_out_a_valid;	// @[generators/rocket-chip/src/main/scala/subsystem/PeripheryBus.scala:54:33]
  wire [2:0]  _fixer_auto_anon_out_a_bits_opcode;	// @[generators/rocket-chip/src/main/scala/subsystem/PeripheryBus.scala:54:33]
  wire [2:0]  _fixer_auto_anon_out_a_bits_size;	// @[generators/rocket-chip/src/main/scala/subsystem/PeripheryBus.scala:54:33]
  wire [8:0]  _fixer_auto_anon_out_a_bits_source;	// @[generators/rocket-chip/src/main/scala/subsystem/PeripheryBus.scala:54:33]
  wire [31:0] _fixer_auto_anon_out_a_bits_address;	// @[generators/rocket-chip/src/main/scala/subsystem/PeripheryBus.scala:54:33]
  wire [7:0]  _fixer_auto_anon_out_a_bits_mask;	// @[generators/rocket-chip/src/main/scala/subsystem/PeripheryBus.scala:54:33]
  wire [63:0] _fixer_auto_anon_out_a_bits_data;	// @[generators/rocket-chip/src/main/scala/subsystem/PeripheryBus.scala:54:33]
  wire        _fixer_auto_anon_out_d_ready;	// @[generators/rocket-chip/src/main/scala/subsystem/PeripheryBus.scala:54:33]
  wire        _fixedClockNode_auto_anon_out_0_clock;	// @[generators/rocket-chip/src/main/scala/prci/ClockGroup.scala:115:114]
  wire        _fixedClockNode_auto_anon_out_0_reset;	// @[generators/rocket-chip/src/main/scala/prci/ClockGroup.scala:115:114]
  OCAH4CORECluster_FixedClockBroadcast_5 fixedClockNode (	// @[generators/rocket-chip/src/main/scala/prci/ClockGroup.scala:115:114]
    .auto_anon_in_clock    (auto_pbus_clock_groups_in_member_pbus_0_clock),
    .auto_anon_in_reset    (auto_pbus_clock_groups_in_member_pbus_0_reset),
    .auto_anon_out_4_clock (auto_fixedClockNode_anon_out_3_clock),
    .auto_anon_out_4_reset (auto_fixedClockNode_anon_out_3_reset),
    .auto_anon_out_3_clock (auto_fixedClockNode_anon_out_2_clock),
    .auto_anon_out_3_reset (auto_fixedClockNode_anon_out_2_reset),
    .auto_anon_out_2_clock (auto_fixedClockNode_anon_out_1_clock),
    .auto_anon_out_2_reset (auto_fixedClockNode_anon_out_1_reset),
    .auto_anon_out_1_clock (auto_fixedClockNode_anon_out_0_clock),
    .auto_anon_out_1_reset (auto_fixedClockNode_anon_out_0_reset),
    .auto_anon_out_0_clock (_fixedClockNode_auto_anon_out_0_clock),
    .auto_anon_out_0_reset (_fixedClockNode_auto_anon_out_0_reset)
  );
  OCAH4CORECluster_TLFIFOFixer_1 fixer (	// @[generators/rocket-chip/src/main/scala/subsystem/PeripheryBus.scala:54:33]
    .clock                        (_fixedClockNode_auto_anon_out_0_clock),	// @[generators/rocket-chip/src/main/scala/prci/ClockGroup.scala:115:114]
    .reset                        (_fixedClockNode_auto_anon_out_0_reset),	// @[generators/rocket-chip/src/main/scala/prci/ClockGroup.scala:115:114]
    .auto_anon_in_a_ready         (_fixer_auto_anon_in_a_ready),
    .auto_anon_in_a_valid         (_buffer_auto_out_a_valid),	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:75:28]
    .auto_anon_in_a_bits_opcode   (_buffer_auto_out_a_bits_opcode),	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:75:28]
    .auto_anon_in_a_bits_size     (_buffer_auto_out_a_bits_size),	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:75:28]
    .auto_anon_in_a_bits_source   (_buffer_auto_out_a_bits_source),	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:75:28]
    .auto_anon_in_a_bits_address  (_buffer_auto_out_a_bits_address),	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:75:28]
    .auto_anon_in_a_bits_mask     (_buffer_auto_out_a_bits_mask),	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:75:28]
    .auto_anon_in_a_bits_data     (_buffer_auto_out_a_bits_data),	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:75:28]
    .auto_anon_in_d_ready         (_buffer_auto_out_d_ready),	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:75:28]
    .auto_anon_in_d_valid         (_fixer_auto_anon_in_d_valid),
    .auto_anon_in_d_bits_opcode   (_fixer_auto_anon_in_d_bits_opcode),
    .auto_anon_in_d_bits_size     (_fixer_auto_anon_in_d_bits_size),
    .auto_anon_in_d_bits_source   (_fixer_auto_anon_in_d_bits_source),
    .auto_anon_in_d_bits_data     (_fixer_auto_anon_in_d_bits_data),
    .auto_anon_out_a_ready        (_out_xbar_auto_anon_in_a_ready),	// @[generators/rocket-chip/src/main/scala/subsystem/PeripheryBus.scala:57:30]
    .auto_anon_out_a_valid        (_fixer_auto_anon_out_a_valid),
    .auto_anon_out_a_bits_opcode  (_fixer_auto_anon_out_a_bits_opcode),
    .auto_anon_out_a_bits_size    (_fixer_auto_anon_out_a_bits_size),
    .auto_anon_out_a_bits_source  (_fixer_auto_anon_out_a_bits_source),
    .auto_anon_out_a_bits_address (_fixer_auto_anon_out_a_bits_address),
    .auto_anon_out_a_bits_mask    (_fixer_auto_anon_out_a_bits_mask),
    .auto_anon_out_a_bits_data    (_fixer_auto_anon_out_a_bits_data),
    .auto_anon_out_d_ready        (_fixer_auto_anon_out_d_ready),
    .auto_anon_out_d_valid        (_out_xbar_auto_anon_in_d_valid),	// @[generators/rocket-chip/src/main/scala/subsystem/PeripheryBus.scala:57:30]
    .auto_anon_out_d_bits_opcode  (_out_xbar_auto_anon_in_d_bits_opcode),	// @[generators/rocket-chip/src/main/scala/subsystem/PeripheryBus.scala:57:30]
    .auto_anon_out_d_bits_size    (_out_xbar_auto_anon_in_d_bits_size),	// @[generators/rocket-chip/src/main/scala/subsystem/PeripheryBus.scala:57:30]
    .auto_anon_out_d_bits_source  (_out_xbar_auto_anon_in_d_bits_source),	// @[generators/rocket-chip/src/main/scala/subsystem/PeripheryBus.scala:57:30]
    .auto_anon_out_d_bits_data    (_out_xbar_auto_anon_in_d_bits_data)	// @[generators/rocket-chip/src/main/scala/subsystem/PeripheryBus.scala:57:30]
  );
  OCAH4CORECluster_TLXbar_pbus_out_i1_o4_a32d64s9k1z3u out_xbar (	// @[generators/rocket-chip/src/main/scala/subsystem/PeripheryBus.scala:57:30]
    .clock                          (_fixedClockNode_auto_anon_out_0_clock),	// @[generators/rocket-chip/src/main/scala/prci/ClockGroup.scala:115:114]
    .reset                          (_fixedClockNode_auto_anon_out_0_reset),	// @[generators/rocket-chip/src/main/scala/prci/ClockGroup.scala:115:114]
    .auto_anon_in_a_ready           (_out_xbar_auto_anon_in_a_ready),
    .auto_anon_in_a_valid           (_fixer_auto_anon_out_a_valid),	// @[generators/rocket-chip/src/main/scala/subsystem/PeripheryBus.scala:54:33]
    .auto_anon_in_a_bits_opcode     (_fixer_auto_anon_out_a_bits_opcode),	// @[generators/rocket-chip/src/main/scala/subsystem/PeripheryBus.scala:54:33]
    .auto_anon_in_a_bits_size       (_fixer_auto_anon_out_a_bits_size),	// @[generators/rocket-chip/src/main/scala/subsystem/PeripheryBus.scala:54:33]
    .auto_anon_in_a_bits_source     (_fixer_auto_anon_out_a_bits_source),	// @[generators/rocket-chip/src/main/scala/subsystem/PeripheryBus.scala:54:33]
    .auto_anon_in_a_bits_address    (_fixer_auto_anon_out_a_bits_address),	// @[generators/rocket-chip/src/main/scala/subsystem/PeripheryBus.scala:54:33]
    .auto_anon_in_a_bits_mask       (_fixer_auto_anon_out_a_bits_mask),	// @[generators/rocket-chip/src/main/scala/subsystem/PeripheryBus.scala:54:33]
    .auto_anon_in_a_bits_data       (_fixer_auto_anon_out_a_bits_data),	// @[generators/rocket-chip/src/main/scala/subsystem/PeripheryBus.scala:54:33]
    .auto_anon_in_d_ready           (_fixer_auto_anon_out_d_ready),	// @[generators/rocket-chip/src/main/scala/subsystem/PeripheryBus.scala:54:33]
    .auto_anon_in_d_valid           (_out_xbar_auto_anon_in_d_valid),
    .auto_anon_in_d_bits_opcode     (_out_xbar_auto_anon_in_d_bits_opcode),
    .auto_anon_in_d_bits_size       (_out_xbar_auto_anon_in_d_bits_size),
    .auto_anon_in_d_bits_source     (_out_xbar_auto_anon_in_d_bits_source),
    .auto_anon_in_d_bits_data       (_out_xbar_auto_anon_in_d_bits_data),
    .auto_anon_out_3_a_ready        (_coupler_to_device_named_wdt_3_auto_tl_in_a_ready),	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
    .auto_anon_out_3_a_valid        (_out_xbar_auto_anon_out_3_a_valid),
    .auto_anon_out_3_a_bits_opcode  (_out_xbar_auto_anon_out_3_a_bits_opcode),
    .auto_anon_out_3_a_bits_size    (_out_xbar_auto_anon_out_3_a_bits_size),
    .auto_anon_out_3_a_bits_source  (_out_xbar_auto_anon_out_3_a_bits_source),
    .auto_anon_out_3_a_bits_address (_out_xbar_auto_anon_out_3_a_bits_address),
    .auto_anon_out_3_a_bits_mask    (_out_xbar_auto_anon_out_3_a_bits_mask),
    .auto_anon_out_3_a_bits_data    (_out_xbar_auto_anon_out_3_a_bits_data),
    .auto_anon_out_3_d_ready        (_out_xbar_auto_anon_out_3_d_ready),
    .auto_anon_out_3_d_valid        (_coupler_to_device_named_wdt_3_auto_tl_in_d_valid),	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
    .auto_anon_out_3_d_bits_opcode  (_coupler_to_device_named_wdt_3_auto_tl_in_d_bits_opcode),	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
    .auto_anon_out_3_d_bits_size    (_coupler_to_device_named_wdt_3_auto_tl_in_d_bits_size),	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
    .auto_anon_out_3_d_bits_source  (_coupler_to_device_named_wdt_3_auto_tl_in_d_bits_source),	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
    .auto_anon_out_3_d_bits_data    (_coupler_to_device_named_wdt_3_auto_tl_in_d_bits_data),	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
    .auto_anon_out_2_a_ready        (_coupler_to_device_named_wdt_2_auto_tl_in_a_ready),	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
    .auto_anon_out_2_a_valid        (_out_xbar_auto_anon_out_2_a_valid),
    .auto_anon_out_2_a_bits_opcode  (_out_xbar_auto_anon_out_2_a_bits_opcode),
    .auto_anon_out_2_a_bits_size    (_out_xbar_auto_anon_out_2_a_bits_size),
    .auto_anon_out_2_a_bits_source  (_out_xbar_auto_anon_out_2_a_bits_source),
    .auto_anon_out_2_a_bits_address (_out_xbar_auto_anon_out_2_a_bits_address),
    .auto_anon_out_2_a_bits_mask    (_out_xbar_auto_anon_out_2_a_bits_mask),
    .auto_anon_out_2_a_bits_data    (_out_xbar_auto_anon_out_2_a_bits_data),
    .auto_anon_out_2_d_ready        (_out_xbar_auto_anon_out_2_d_ready),
    .auto_anon_out_2_d_valid        (_coupler_to_device_named_wdt_2_auto_tl_in_d_valid),	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
    .auto_anon_out_2_d_bits_opcode  (_coupler_to_device_named_wdt_2_auto_tl_in_d_bits_opcode),	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
    .auto_anon_out_2_d_bits_size    (_coupler_to_device_named_wdt_2_auto_tl_in_d_bits_size),	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
    .auto_anon_out_2_d_bits_source  (_coupler_to_device_named_wdt_2_auto_tl_in_d_bits_source),	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
    .auto_anon_out_2_d_bits_data    (_coupler_to_device_named_wdt_2_auto_tl_in_d_bits_data),	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
    .auto_anon_out_1_a_ready        (_coupler_to_device_named_wdt_1_auto_tl_in_a_ready),	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
    .auto_anon_out_1_a_valid        (_out_xbar_auto_anon_out_1_a_valid),
    .auto_anon_out_1_a_bits_opcode  (_out_xbar_auto_anon_out_1_a_bits_opcode),
    .auto_anon_out_1_a_bits_size    (_out_xbar_auto_anon_out_1_a_bits_size),
    .auto_anon_out_1_a_bits_source  (_out_xbar_auto_anon_out_1_a_bits_source),
    .auto_anon_out_1_a_bits_address (_out_xbar_auto_anon_out_1_a_bits_address),
    .auto_anon_out_1_a_bits_mask    (_out_xbar_auto_anon_out_1_a_bits_mask),
    .auto_anon_out_1_a_bits_data    (_out_xbar_auto_anon_out_1_a_bits_data),
    .auto_anon_out_1_d_ready        (_out_xbar_auto_anon_out_1_d_ready),
    .auto_anon_out_1_d_valid        (_coupler_to_device_named_wdt_1_auto_tl_in_d_valid),	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
    .auto_anon_out_1_d_bits_opcode  (_coupler_to_device_named_wdt_1_auto_tl_in_d_bits_opcode),	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
    .auto_anon_out_1_d_bits_size    (_coupler_to_device_named_wdt_1_auto_tl_in_d_bits_size),	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
    .auto_anon_out_1_d_bits_source  (_coupler_to_device_named_wdt_1_auto_tl_in_d_bits_source),	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
    .auto_anon_out_1_d_bits_data    (_coupler_to_device_named_wdt_1_auto_tl_in_d_bits_data),	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
    .auto_anon_out_0_a_ready        (_coupler_to_device_named_wdt_0_auto_tl_in_a_ready),	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
    .auto_anon_out_0_a_valid        (_out_xbar_auto_anon_out_0_a_valid),
    .auto_anon_out_0_a_bits_opcode  (_out_xbar_auto_anon_out_0_a_bits_opcode),
    .auto_anon_out_0_a_bits_size    (_out_xbar_auto_anon_out_0_a_bits_size),
    .auto_anon_out_0_a_bits_source  (_out_xbar_auto_anon_out_0_a_bits_source),
    .auto_anon_out_0_a_bits_address (_out_xbar_auto_anon_out_0_a_bits_address),
    .auto_anon_out_0_a_bits_mask    (_out_xbar_auto_anon_out_0_a_bits_mask),
    .auto_anon_out_0_a_bits_data    (_out_xbar_auto_anon_out_0_a_bits_data),
    .auto_anon_out_0_d_ready        (_out_xbar_auto_anon_out_0_d_ready),
    .auto_anon_out_0_d_valid        (_coupler_to_device_named_wdt_0_auto_tl_in_d_valid),	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
    .auto_anon_out_0_d_bits_opcode  (_coupler_to_device_named_wdt_0_auto_tl_in_d_bits_opcode),	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
    .auto_anon_out_0_d_bits_size    (_coupler_to_device_named_wdt_0_auto_tl_in_d_bits_size),	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
    .auto_anon_out_0_d_bits_source  (_coupler_to_device_named_wdt_0_auto_tl_in_d_bits_source),	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
    .auto_anon_out_0_d_bits_data    (_coupler_to_device_named_wdt_0_auto_tl_in_d_bits_data)	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
  );
  OCAH4CORECluster_TLBuffer_a32d64s9k1z3u buffer (	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:75:28]
    .clock                   (_fixedClockNode_auto_anon_out_0_clock),	// @[generators/rocket-chip/src/main/scala/prci/ClockGroup.scala:115:114]
    .reset                   (_fixedClockNode_auto_anon_out_0_reset),	// @[generators/rocket-chip/src/main/scala/prci/ClockGroup.scala:115:114]
    .auto_in_a_ready         (_buffer_auto_in_a_ready),
    .auto_in_a_valid         (_atomics_auto_out_a_valid),	// @[generators/rocket-chip/src/main/scala/tilelink/AtomicAutomata.scala:289:29]
    .auto_in_a_bits_opcode   (_atomics_auto_out_a_bits_opcode),	// @[generators/rocket-chip/src/main/scala/tilelink/AtomicAutomata.scala:289:29]
    .auto_in_a_bits_param    (_atomics_auto_out_a_bits_param),	// @[generators/rocket-chip/src/main/scala/tilelink/AtomicAutomata.scala:289:29]
    .auto_in_a_bits_size     (_atomics_auto_out_a_bits_size),	// @[generators/rocket-chip/src/main/scala/tilelink/AtomicAutomata.scala:289:29]
    .auto_in_a_bits_source   (_atomics_auto_out_a_bits_source),	// @[generators/rocket-chip/src/main/scala/tilelink/AtomicAutomata.scala:289:29]
    .auto_in_a_bits_address  (_atomics_auto_out_a_bits_address),	// @[generators/rocket-chip/src/main/scala/tilelink/AtomicAutomata.scala:289:29]
    .auto_in_a_bits_mask     (_atomics_auto_out_a_bits_mask),	// @[generators/rocket-chip/src/main/scala/tilelink/AtomicAutomata.scala:289:29]
    .auto_in_a_bits_data     (_atomics_auto_out_a_bits_data),	// @[generators/rocket-chip/src/main/scala/tilelink/AtomicAutomata.scala:289:29]
    .auto_in_a_bits_corrupt  (_atomics_auto_out_a_bits_corrupt),	// @[generators/rocket-chip/src/main/scala/tilelink/AtomicAutomata.scala:289:29]
    .auto_in_d_ready         (_atomics_auto_out_d_ready),	// @[generators/rocket-chip/src/main/scala/tilelink/AtomicAutomata.scala:289:29]
    .auto_in_d_valid         (_buffer_auto_in_d_valid),
    .auto_in_d_bits_opcode   (_buffer_auto_in_d_bits_opcode),
    .auto_in_d_bits_param    (_buffer_auto_in_d_bits_param),
    .auto_in_d_bits_size     (_buffer_auto_in_d_bits_size),
    .auto_in_d_bits_source   (_buffer_auto_in_d_bits_source),
    .auto_in_d_bits_sink     (_buffer_auto_in_d_bits_sink),
    .auto_in_d_bits_denied   (_buffer_auto_in_d_bits_denied),
    .auto_in_d_bits_data     (_buffer_auto_in_d_bits_data),
    .auto_in_d_bits_corrupt  (_buffer_auto_in_d_bits_corrupt),
    .auto_out_a_ready        (_fixer_auto_anon_in_a_ready),	// @[generators/rocket-chip/src/main/scala/subsystem/PeripheryBus.scala:54:33]
    .auto_out_a_valid        (_buffer_auto_out_a_valid),
    .auto_out_a_bits_opcode  (_buffer_auto_out_a_bits_opcode),
    .auto_out_a_bits_size    (_buffer_auto_out_a_bits_size),
    .auto_out_a_bits_source  (_buffer_auto_out_a_bits_source),
    .auto_out_a_bits_address (_buffer_auto_out_a_bits_address),
    .auto_out_a_bits_mask    (_buffer_auto_out_a_bits_mask),
    .auto_out_a_bits_data    (_buffer_auto_out_a_bits_data),
    .auto_out_d_ready        (_buffer_auto_out_d_ready),
    .auto_out_d_valid        (_fixer_auto_anon_in_d_valid),	// @[generators/rocket-chip/src/main/scala/subsystem/PeripheryBus.scala:54:33]
    .auto_out_d_bits_opcode  (_fixer_auto_anon_in_d_bits_opcode),	// @[generators/rocket-chip/src/main/scala/subsystem/PeripheryBus.scala:54:33]
    .auto_out_d_bits_size    (_fixer_auto_anon_in_d_bits_size),	// @[generators/rocket-chip/src/main/scala/subsystem/PeripheryBus.scala:54:33]
    .auto_out_d_bits_source  (_fixer_auto_anon_in_d_bits_source),	// @[generators/rocket-chip/src/main/scala/subsystem/PeripheryBus.scala:54:33]
    .auto_out_d_bits_data    (_fixer_auto_anon_in_d_bits_data)	// @[generators/rocket-chip/src/main/scala/subsystem/PeripheryBus.scala:54:33]
  );
  OCAH4CORECluster_TLAtomicAutomata_pbus atomics (	// @[generators/rocket-chip/src/main/scala/tilelink/AtomicAutomata.scala:289:29]
    .clock                   (_fixedClockNode_auto_anon_out_0_clock),	// @[generators/rocket-chip/src/main/scala/prci/ClockGroup.scala:115:114]
    .reset                   (_fixedClockNode_auto_anon_out_0_reset),	// @[generators/rocket-chip/src/main/scala/prci/ClockGroup.scala:115:114]
    .auto_in_a_ready         (auto_bus_xing_in_a_ready),
    .auto_in_a_valid         (auto_bus_xing_in_a_valid),
    .auto_in_a_bits_opcode   (auto_bus_xing_in_a_bits_opcode),
    .auto_in_a_bits_param    (auto_bus_xing_in_a_bits_param),
    .auto_in_a_bits_size     (auto_bus_xing_in_a_bits_size),
    .auto_in_a_bits_source   (auto_bus_xing_in_a_bits_source),
    .auto_in_a_bits_address  (auto_bus_xing_in_a_bits_address),
    .auto_in_a_bits_mask     (auto_bus_xing_in_a_bits_mask),
    .auto_in_a_bits_data     (auto_bus_xing_in_a_bits_data),
    .auto_in_a_bits_corrupt  (auto_bus_xing_in_a_bits_corrupt),
    .auto_in_d_ready         (auto_bus_xing_in_d_ready),
    .auto_in_d_valid         (auto_bus_xing_in_d_valid),
    .auto_in_d_bits_opcode   (auto_bus_xing_in_d_bits_opcode),
    .auto_in_d_bits_param    (auto_bus_xing_in_d_bits_param),
    .auto_in_d_bits_size     (auto_bus_xing_in_d_bits_size),
    .auto_in_d_bits_source   (auto_bus_xing_in_d_bits_source),
    .auto_in_d_bits_sink     (auto_bus_xing_in_d_bits_sink),
    .auto_in_d_bits_denied   (auto_bus_xing_in_d_bits_denied),
    .auto_in_d_bits_data     (auto_bus_xing_in_d_bits_data),
    .auto_in_d_bits_corrupt  (auto_bus_xing_in_d_bits_corrupt),
    .auto_out_a_ready        (_buffer_auto_in_a_ready),	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:75:28]
    .auto_out_a_valid        (_atomics_auto_out_a_valid),
    .auto_out_a_bits_opcode  (_atomics_auto_out_a_bits_opcode),
    .auto_out_a_bits_param   (_atomics_auto_out_a_bits_param),
    .auto_out_a_bits_size    (_atomics_auto_out_a_bits_size),
    .auto_out_a_bits_source  (_atomics_auto_out_a_bits_source),
    .auto_out_a_bits_address (_atomics_auto_out_a_bits_address),
    .auto_out_a_bits_mask    (_atomics_auto_out_a_bits_mask),
    .auto_out_a_bits_data    (_atomics_auto_out_a_bits_data),
    .auto_out_a_bits_corrupt (_atomics_auto_out_a_bits_corrupt),
    .auto_out_d_ready        (_atomics_auto_out_d_ready),
    .auto_out_d_valid        (_buffer_auto_in_d_valid),	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:75:28]
    .auto_out_d_bits_opcode  (_buffer_auto_in_d_bits_opcode),	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:75:28]
    .auto_out_d_bits_param   (_buffer_auto_in_d_bits_param),	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:75:28]
    .auto_out_d_bits_size    (_buffer_auto_in_d_bits_size),	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:75:28]
    .auto_out_d_bits_source  (_buffer_auto_in_d_bits_source),	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:75:28]
    .auto_out_d_bits_sink    (_buffer_auto_in_d_bits_sink),	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:75:28]
    .auto_out_d_bits_denied  (_buffer_auto_in_d_bits_denied),	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:75:28]
    .auto_out_d_bits_data    (_buffer_auto_in_d_bits_data),	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:75:28]
    .auto_out_d_bits_corrupt (_buffer_auto_in_d_bits_corrupt)	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:75:28]
  );
  OCAH4CORECluster_TLInterconnectCoupler_pbus_to_device_named_wdt_0 coupler_to_device_named_wdt_0 (	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
    .clock                                (_fixedClockNode_auto_anon_out_0_clock),	// @[generators/rocket-chip/src/main/scala/prci/ClockGroup.scala:115:114]
    .reset                                (_fixedClockNode_auto_anon_out_0_reset),	// @[generators/rocket-chip/src/main/scala/prci/ClockGroup.scala:115:114]
    .auto_control_xing_out_a_ready        (auto_coupler_to_device_named_wdt_0_control_xing_out_a_ready),
    .auto_control_xing_out_a_valid        (auto_coupler_to_device_named_wdt_0_control_xing_out_a_valid),
    .auto_control_xing_out_a_bits_opcode  (auto_coupler_to_device_named_wdt_0_control_xing_out_a_bits_opcode),
    .auto_control_xing_out_a_bits_size    (auto_coupler_to_device_named_wdt_0_control_xing_out_a_bits_size),
    .auto_control_xing_out_a_bits_source  (auto_coupler_to_device_named_wdt_0_control_xing_out_a_bits_source),
    .auto_control_xing_out_a_bits_address (auto_coupler_to_device_named_wdt_0_control_xing_out_a_bits_address),
    .auto_control_xing_out_a_bits_mask    (auto_coupler_to_device_named_wdt_0_control_xing_out_a_bits_mask),
    .auto_control_xing_out_a_bits_data    (auto_coupler_to_device_named_wdt_0_control_xing_out_a_bits_data),
    .auto_control_xing_out_d_ready        (auto_coupler_to_device_named_wdt_0_control_xing_out_d_ready),
    .auto_control_xing_out_d_valid        (auto_coupler_to_device_named_wdt_0_control_xing_out_d_valid),
    .auto_control_xing_out_d_bits_opcode  (auto_coupler_to_device_named_wdt_0_control_xing_out_d_bits_opcode),
    .auto_control_xing_out_d_bits_size    (auto_coupler_to_device_named_wdt_0_control_xing_out_d_bits_size),
    .auto_control_xing_out_d_bits_source  (auto_coupler_to_device_named_wdt_0_control_xing_out_d_bits_source),
    .auto_control_xing_out_d_bits_data    (auto_coupler_to_device_named_wdt_0_control_xing_out_d_bits_data),
    .auto_tl_in_a_ready                   (_coupler_to_device_named_wdt_0_auto_tl_in_a_ready),
    .auto_tl_in_a_valid                   (_out_xbar_auto_anon_out_0_a_valid),	// @[generators/rocket-chip/src/main/scala/subsystem/PeripheryBus.scala:57:30]
    .auto_tl_in_a_bits_opcode             (_out_xbar_auto_anon_out_0_a_bits_opcode),	// @[generators/rocket-chip/src/main/scala/subsystem/PeripheryBus.scala:57:30]
    .auto_tl_in_a_bits_size               (_out_xbar_auto_anon_out_0_a_bits_size),	// @[generators/rocket-chip/src/main/scala/subsystem/PeripheryBus.scala:57:30]
    .auto_tl_in_a_bits_source             (_out_xbar_auto_anon_out_0_a_bits_source),	// @[generators/rocket-chip/src/main/scala/subsystem/PeripheryBus.scala:57:30]
    .auto_tl_in_a_bits_address            (_out_xbar_auto_anon_out_0_a_bits_address),	// @[generators/rocket-chip/src/main/scala/subsystem/PeripheryBus.scala:57:30]
    .auto_tl_in_a_bits_mask               (_out_xbar_auto_anon_out_0_a_bits_mask),	// @[generators/rocket-chip/src/main/scala/subsystem/PeripheryBus.scala:57:30]
    .auto_tl_in_a_bits_data               (_out_xbar_auto_anon_out_0_a_bits_data),	// @[generators/rocket-chip/src/main/scala/subsystem/PeripheryBus.scala:57:30]
    .auto_tl_in_d_ready                   (_out_xbar_auto_anon_out_0_d_ready),	// @[generators/rocket-chip/src/main/scala/subsystem/PeripheryBus.scala:57:30]
    .auto_tl_in_d_valid                   (_coupler_to_device_named_wdt_0_auto_tl_in_d_valid),
    .auto_tl_in_d_bits_opcode             (_coupler_to_device_named_wdt_0_auto_tl_in_d_bits_opcode),
    .auto_tl_in_d_bits_size               (_coupler_to_device_named_wdt_0_auto_tl_in_d_bits_size),
    .auto_tl_in_d_bits_source             (_coupler_to_device_named_wdt_0_auto_tl_in_d_bits_source),
    .auto_tl_in_d_bits_data               (_coupler_to_device_named_wdt_0_auto_tl_in_d_bits_data)
  );
  OCAH4CORECluster_TLInterconnectCoupler_pbus_to_device_named_wdt_1 coupler_to_device_named_wdt_1 (	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
    .clock                                (_fixedClockNode_auto_anon_out_0_clock),	// @[generators/rocket-chip/src/main/scala/prci/ClockGroup.scala:115:114]
    .reset                                (_fixedClockNode_auto_anon_out_0_reset),	// @[generators/rocket-chip/src/main/scala/prci/ClockGroup.scala:115:114]
    .auto_control_xing_out_a_ready        (auto_coupler_to_device_named_wdt_1_control_xing_out_a_ready),
    .auto_control_xing_out_a_valid        (auto_coupler_to_device_named_wdt_1_control_xing_out_a_valid),
    .auto_control_xing_out_a_bits_opcode  (auto_coupler_to_device_named_wdt_1_control_xing_out_a_bits_opcode),
    .auto_control_xing_out_a_bits_size    (auto_coupler_to_device_named_wdt_1_control_xing_out_a_bits_size),
    .auto_control_xing_out_a_bits_source  (auto_coupler_to_device_named_wdt_1_control_xing_out_a_bits_source),
    .auto_control_xing_out_a_bits_address (auto_coupler_to_device_named_wdt_1_control_xing_out_a_bits_address),
    .auto_control_xing_out_a_bits_mask    (auto_coupler_to_device_named_wdt_1_control_xing_out_a_bits_mask),
    .auto_control_xing_out_a_bits_data    (auto_coupler_to_device_named_wdt_1_control_xing_out_a_bits_data),
    .auto_control_xing_out_d_ready        (auto_coupler_to_device_named_wdt_1_control_xing_out_d_ready),
    .auto_control_xing_out_d_valid        (auto_coupler_to_device_named_wdt_1_control_xing_out_d_valid),
    .auto_control_xing_out_d_bits_opcode  (auto_coupler_to_device_named_wdt_1_control_xing_out_d_bits_opcode),
    .auto_control_xing_out_d_bits_size    (auto_coupler_to_device_named_wdt_1_control_xing_out_d_bits_size),
    .auto_control_xing_out_d_bits_source  (auto_coupler_to_device_named_wdt_1_control_xing_out_d_bits_source),
    .auto_control_xing_out_d_bits_data    (auto_coupler_to_device_named_wdt_1_control_xing_out_d_bits_data),
    .auto_tl_in_a_ready                   (_coupler_to_device_named_wdt_1_auto_tl_in_a_ready),
    .auto_tl_in_a_valid                   (_out_xbar_auto_anon_out_1_a_valid),	// @[generators/rocket-chip/src/main/scala/subsystem/PeripheryBus.scala:57:30]
    .auto_tl_in_a_bits_opcode             (_out_xbar_auto_anon_out_1_a_bits_opcode),	// @[generators/rocket-chip/src/main/scala/subsystem/PeripheryBus.scala:57:30]
    .auto_tl_in_a_bits_size               (_out_xbar_auto_anon_out_1_a_bits_size),	// @[generators/rocket-chip/src/main/scala/subsystem/PeripheryBus.scala:57:30]
    .auto_tl_in_a_bits_source             (_out_xbar_auto_anon_out_1_a_bits_source),	// @[generators/rocket-chip/src/main/scala/subsystem/PeripheryBus.scala:57:30]
    .auto_tl_in_a_bits_address            (_out_xbar_auto_anon_out_1_a_bits_address),	// @[generators/rocket-chip/src/main/scala/subsystem/PeripheryBus.scala:57:30]
    .auto_tl_in_a_bits_mask               (_out_xbar_auto_anon_out_1_a_bits_mask),	// @[generators/rocket-chip/src/main/scala/subsystem/PeripheryBus.scala:57:30]
    .auto_tl_in_a_bits_data               (_out_xbar_auto_anon_out_1_a_bits_data),	// @[generators/rocket-chip/src/main/scala/subsystem/PeripheryBus.scala:57:30]
    .auto_tl_in_d_ready                   (_out_xbar_auto_anon_out_1_d_ready),	// @[generators/rocket-chip/src/main/scala/subsystem/PeripheryBus.scala:57:30]
    .auto_tl_in_d_valid                   (_coupler_to_device_named_wdt_1_auto_tl_in_d_valid),
    .auto_tl_in_d_bits_opcode             (_coupler_to_device_named_wdt_1_auto_tl_in_d_bits_opcode),
    .auto_tl_in_d_bits_size               (_coupler_to_device_named_wdt_1_auto_tl_in_d_bits_size),
    .auto_tl_in_d_bits_source             (_coupler_to_device_named_wdt_1_auto_tl_in_d_bits_source),
    .auto_tl_in_d_bits_data               (_coupler_to_device_named_wdt_1_auto_tl_in_d_bits_data)
  );
  OCAH4CORECluster_TLInterconnectCoupler_pbus_to_device_named_wdt_2 coupler_to_device_named_wdt_2 (	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
    .clock                                (_fixedClockNode_auto_anon_out_0_clock),	// @[generators/rocket-chip/src/main/scala/prci/ClockGroup.scala:115:114]
    .reset                                (_fixedClockNode_auto_anon_out_0_reset),	// @[generators/rocket-chip/src/main/scala/prci/ClockGroup.scala:115:114]
    .auto_control_xing_out_a_ready        (auto_coupler_to_device_named_wdt_2_control_xing_out_a_ready),
    .auto_control_xing_out_a_valid        (auto_coupler_to_device_named_wdt_2_control_xing_out_a_valid),
    .auto_control_xing_out_a_bits_opcode  (auto_coupler_to_device_named_wdt_2_control_xing_out_a_bits_opcode),
    .auto_control_xing_out_a_bits_size    (auto_coupler_to_device_named_wdt_2_control_xing_out_a_bits_size),
    .auto_control_xing_out_a_bits_source  (auto_coupler_to_device_named_wdt_2_control_xing_out_a_bits_source),
    .auto_control_xing_out_a_bits_address (auto_coupler_to_device_named_wdt_2_control_xing_out_a_bits_address),
    .auto_control_xing_out_a_bits_mask    (auto_coupler_to_device_named_wdt_2_control_xing_out_a_bits_mask),
    .auto_control_xing_out_a_bits_data    (auto_coupler_to_device_named_wdt_2_control_xing_out_a_bits_data),
    .auto_control_xing_out_d_ready        (auto_coupler_to_device_named_wdt_2_control_xing_out_d_ready),
    .auto_control_xing_out_d_valid        (auto_coupler_to_device_named_wdt_2_control_xing_out_d_valid),
    .auto_control_xing_out_d_bits_opcode  (auto_coupler_to_device_named_wdt_2_control_xing_out_d_bits_opcode),
    .auto_control_xing_out_d_bits_size    (auto_coupler_to_device_named_wdt_2_control_xing_out_d_bits_size),
    .auto_control_xing_out_d_bits_source  (auto_coupler_to_device_named_wdt_2_control_xing_out_d_bits_source),
    .auto_control_xing_out_d_bits_data    (auto_coupler_to_device_named_wdt_2_control_xing_out_d_bits_data),
    .auto_tl_in_a_ready                   (_coupler_to_device_named_wdt_2_auto_tl_in_a_ready),
    .auto_tl_in_a_valid                   (_out_xbar_auto_anon_out_2_a_valid),	// @[generators/rocket-chip/src/main/scala/subsystem/PeripheryBus.scala:57:30]
    .auto_tl_in_a_bits_opcode             (_out_xbar_auto_anon_out_2_a_bits_opcode),	// @[generators/rocket-chip/src/main/scala/subsystem/PeripheryBus.scala:57:30]
    .auto_tl_in_a_bits_size               (_out_xbar_auto_anon_out_2_a_bits_size),	// @[generators/rocket-chip/src/main/scala/subsystem/PeripheryBus.scala:57:30]
    .auto_tl_in_a_bits_source             (_out_xbar_auto_anon_out_2_a_bits_source),	// @[generators/rocket-chip/src/main/scala/subsystem/PeripheryBus.scala:57:30]
    .auto_tl_in_a_bits_address            (_out_xbar_auto_anon_out_2_a_bits_address),	// @[generators/rocket-chip/src/main/scala/subsystem/PeripheryBus.scala:57:30]
    .auto_tl_in_a_bits_mask               (_out_xbar_auto_anon_out_2_a_bits_mask),	// @[generators/rocket-chip/src/main/scala/subsystem/PeripheryBus.scala:57:30]
    .auto_tl_in_a_bits_data               (_out_xbar_auto_anon_out_2_a_bits_data),	// @[generators/rocket-chip/src/main/scala/subsystem/PeripheryBus.scala:57:30]
    .auto_tl_in_d_ready                   (_out_xbar_auto_anon_out_2_d_ready),	// @[generators/rocket-chip/src/main/scala/subsystem/PeripheryBus.scala:57:30]
    .auto_tl_in_d_valid                   (_coupler_to_device_named_wdt_2_auto_tl_in_d_valid),
    .auto_tl_in_d_bits_opcode             (_coupler_to_device_named_wdt_2_auto_tl_in_d_bits_opcode),
    .auto_tl_in_d_bits_size               (_coupler_to_device_named_wdt_2_auto_tl_in_d_bits_size),
    .auto_tl_in_d_bits_source             (_coupler_to_device_named_wdt_2_auto_tl_in_d_bits_source),
    .auto_tl_in_d_bits_data               (_coupler_to_device_named_wdt_2_auto_tl_in_d_bits_data)
  );
  OCAH4CORECluster_TLInterconnectCoupler_pbus_to_device_named_wdt_3 coupler_to_device_named_wdt_3 (	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
    .clock                                (_fixedClockNode_auto_anon_out_0_clock),	// @[generators/rocket-chip/src/main/scala/prci/ClockGroup.scala:115:114]
    .reset                                (_fixedClockNode_auto_anon_out_0_reset),	// @[generators/rocket-chip/src/main/scala/prci/ClockGroup.scala:115:114]
    .auto_control_xing_out_a_ready        (auto_coupler_to_device_named_wdt_3_control_xing_out_a_ready),
    .auto_control_xing_out_a_valid        (auto_coupler_to_device_named_wdt_3_control_xing_out_a_valid),
    .auto_control_xing_out_a_bits_opcode  (auto_coupler_to_device_named_wdt_3_control_xing_out_a_bits_opcode),
    .auto_control_xing_out_a_bits_size    (auto_coupler_to_device_named_wdt_3_control_xing_out_a_bits_size),
    .auto_control_xing_out_a_bits_source  (auto_coupler_to_device_named_wdt_3_control_xing_out_a_bits_source),
    .auto_control_xing_out_a_bits_address (auto_coupler_to_device_named_wdt_3_control_xing_out_a_bits_address),
    .auto_control_xing_out_a_bits_mask    (auto_coupler_to_device_named_wdt_3_control_xing_out_a_bits_mask),
    .auto_control_xing_out_a_bits_data    (auto_coupler_to_device_named_wdt_3_control_xing_out_a_bits_data),
    .auto_control_xing_out_d_ready        (auto_coupler_to_device_named_wdt_3_control_xing_out_d_ready),
    .auto_control_xing_out_d_valid        (auto_coupler_to_device_named_wdt_3_control_xing_out_d_valid),
    .auto_control_xing_out_d_bits_opcode  (auto_coupler_to_device_named_wdt_3_control_xing_out_d_bits_opcode),
    .auto_control_xing_out_d_bits_size    (auto_coupler_to_device_named_wdt_3_control_xing_out_d_bits_size),
    .auto_control_xing_out_d_bits_source  (auto_coupler_to_device_named_wdt_3_control_xing_out_d_bits_source),
    .auto_control_xing_out_d_bits_data    (auto_coupler_to_device_named_wdt_3_control_xing_out_d_bits_data),
    .auto_tl_in_a_ready                   (_coupler_to_device_named_wdt_3_auto_tl_in_a_ready),
    .auto_tl_in_a_valid                   (_out_xbar_auto_anon_out_3_a_valid),	// @[generators/rocket-chip/src/main/scala/subsystem/PeripheryBus.scala:57:30]
    .auto_tl_in_a_bits_opcode             (_out_xbar_auto_anon_out_3_a_bits_opcode),	// @[generators/rocket-chip/src/main/scala/subsystem/PeripheryBus.scala:57:30]
    .auto_tl_in_a_bits_size               (_out_xbar_auto_anon_out_3_a_bits_size),	// @[generators/rocket-chip/src/main/scala/subsystem/PeripheryBus.scala:57:30]
    .auto_tl_in_a_bits_source             (_out_xbar_auto_anon_out_3_a_bits_source),	// @[generators/rocket-chip/src/main/scala/subsystem/PeripheryBus.scala:57:30]
    .auto_tl_in_a_bits_address            (_out_xbar_auto_anon_out_3_a_bits_address),	// @[generators/rocket-chip/src/main/scala/subsystem/PeripheryBus.scala:57:30]
    .auto_tl_in_a_bits_mask               (_out_xbar_auto_anon_out_3_a_bits_mask),	// @[generators/rocket-chip/src/main/scala/subsystem/PeripheryBus.scala:57:30]
    .auto_tl_in_a_bits_data               (_out_xbar_auto_anon_out_3_a_bits_data),	// @[generators/rocket-chip/src/main/scala/subsystem/PeripheryBus.scala:57:30]
    .auto_tl_in_d_ready                   (_out_xbar_auto_anon_out_3_d_ready),	// @[generators/rocket-chip/src/main/scala/subsystem/PeripheryBus.scala:57:30]
    .auto_tl_in_d_valid                   (_coupler_to_device_named_wdt_3_auto_tl_in_d_valid),
    .auto_tl_in_d_bits_opcode             (_coupler_to_device_named_wdt_3_auto_tl_in_d_bits_opcode),
    .auto_tl_in_d_bits_size               (_coupler_to_device_named_wdt_3_auto_tl_in_d_bits_size),
    .auto_tl_in_d_bits_source             (_coupler_to_device_named_wdt_3_auto_tl_in_d_bits_source),
    .auto_tl_in_d_bits_data               (_coupler_to_device_named_wdt_3_auto_tl_in_d_bits_data)
  );
endmodule

