// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 Tenstorrent USA, Inc.

// Complete every AXI-Lite access with a fixed error response.
//
// RESP and RESP_DATA set the response code and read payload; RESP_DATA is zero-extended or
// truncated to AXI_DATA_WIDTH for r.data.
// MAX_TRANS caps accepted outstanding transactions before stalling.
// Present a struct AXI-Lite slave port over the underlying full-AXI error slave.

module prim_axi_lite_err_slv #(
  parameter int unsigned           AXI_ADDR_WIDTH = 32,  // AXI-Lite address width.
  parameter int unsigned           AXI_DATA_WIDTH = 32,  // AXI-Lite data width; a power of two of
                                                         // at least 8.
  parameter type                   axil_req_t     = logic,  // AXI4-Lite request type.
  parameter type                   axil_resp_t    = logic,  // AXI4-Lite response type.
  parameter axi_pkg::resp_t        RESP           = axi_pkg::RESP_DECERR,  // Error response generated by this slave.
  parameter int unsigned           RESP_WIDTH     = 32'd64,  // Width of RESP_DATA only; r.data is
                                                             // always AXI_DATA_WIDTH wide.
  parameter logic [RESP_WIDTH-1:0] RESP_DATA      = 64'hBADCAB1EBADCAB1E,  // Fixed read-data return value.
  parameter int unsigned           MAX_TRANS      = 1,  // Maximum accepted transactions before
                                                        // stalling.
  localparam int unsigned AxiStrbWidth = AXI_DATA_WIDTH / 8,  // Write-strobe width; derived.
  localparam type addr_t = logic [AXI_ADDR_WIDTH-1:0],  // Address type alias.
  localparam type data_t = logic [AXI_DATA_WIDTH-1:0],  // Data type alias.
  localparam type strb_t = logic [AxiStrbWidth-1:0]  // Strobe type alias.
) (
  input  logic        clk_i,  // AXI-Lite clock.
  input  logic        rst_ni,  // Async reset, active-low.

  input  axil_req_t   axil_req_i,  // AXI-Lite request from the manager.
  output axil_resp_t  axil_resp_o  // AXI-Lite error response to the manager.
);

  `include "prim_assert.sv"
  `include "ocah_assert.svh"
  `include "axi/typedef.svh"

  ////////////////
  // Assertions //
  ////////////////

  `OCAH_ASSERT_STATIC(DataWidthValid_A,
                      AXI_DATA_WIDTH >= 8 && (AXI_DATA_WIDTH & (AXI_DATA_WIDTH - 1)) == 0)

  `OCAH_OT_ASSERT(AwValidStable_A,
                  axil_req_i.aw_valid && !axil_resp_o.aw_ready |=> axil_req_i.aw_valid, clk_i,
                  !rst_ni)

  `OCAH_OT_ASSERT(WValidStable_A, axil_req_i.w_valid && !axil_resp_o.w_ready |=> axil_req_i.w_valid,
                  clk_i, !rst_ni)

  `OCAH_OT_ASSERT(ArValidStable_A,
                  axil_req_i.ar_valid && !axil_resp_o.ar_ready |=> axil_req_i.ar_valid, clk_i,
                  !rst_ni)

  /////////////////////////
  // Signal Declarations //
  /////////////////////////

  // Internal AXI4 full interface for error slave
  typedef logic id_t;
  typedef logic user_t;

  `AXI_TYPEDEF_ALL(axi, addr_t, id_t, data_t, strb_t, user_t)

  axi_req_t  axi_req;
  axi_resp_t axi_resp;


  ///////////////////////
  // Error Slave Logic //
  ///////////////////////

  axi_lite_to_axi #(
    .AxiDataWidth    (AXI_DATA_WIDTH),
    .req_lite_t      (axil_req_t),
    .resp_lite_t     (axil_resp_t),
    .axi_req_t       (axi_req_t),
    .axi_resp_t      (axi_resp_t)
  ) u_axi_lite_to_axi (
    .slv_req_lite_i  (axil_req_i),
    .slv_resp_lite_o (axil_resp_o),
    .slv_aw_cache_i  (axi_pkg::cache_t'(0)),
    .slv_ar_cache_i  (axi_pkg::cache_t'(0)),
    .mst_req_o       (axi_req),
    .mst_resp_i      (axi_resp)
  );

  axi_err_slv #(
    .AxiIdWidth ($bits(id_t)),
    .axi_req_t  (axi_req_t),
    .axi_resp_t (axi_resp_t),
    .Resp       (RESP),
    .RespWidth  (AXI_DATA_WIDTH),
    .RespData   (RESP_DATA),
    .ATOPs      (1'b0),
    .MaxTrans   (MAX_TRANS)
  ) u_axi_err_slv (
    .clk_i,
    .rst_ni,
    .test_i     (1'b0),
    .slv_req_i  (axi_req),
    .slv_resp_o (axi_resp)
  );

endmodule
