// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 Tenstorrent USA, Inc.

//-----------------------------------------------------------------------------
// SRAM Scrambler Module for 4096 x 32-bits
//
// This module implements a simplified, single-round version of the PRESENT
// block cipher for 32-bit data blocks with address tweaking.
//
// Operation (BYTE_WISE=0, full word):
//   Scramble (write):   data -> XOR round_key -> sbox4 (8 nibbles) -> perm32
//   Descramble (read):  data -> iperm32 -> ibox4 (8 nibbles) -> XOR round_key
//
// Operation (BYTE_WISE=1, per-byte):
//   Scramble (write):   data -> XOR round_key -> sbox4 (8 nibbles) -> perm8 x4
//   Descramble (read):  data -> iperm8 x4 -> ibox4 (8 nibbles) -> XOR round_key
//
// The round_key is generated by XORing the expanded address with the
// scrambler_key.
//
// Copyright 2026 Tenstorrent Inc.
//
//-----------------------------------------------------------------------------

module scrambler_4096x32
  import scrambler_pkg::*;
#(
  parameter int unsigned ADDR_WIDTH = 12,
  parameter int unsigned DATA_WIDTH = 32,
  parameter int unsigned BYTE_WISE  = 0
) (
  input  logic [ADDR_WIDTH-1:0]   addr_i,
  /* verilator lint_off UNUSEDSIGNAL */
  input  logic [DATA_WIDTH/8-1:0] byte_mask_i,
  /* verilator lint_on UNUSEDSIGNAL */
  input  logic [31:0]             scrambler_key_i,
  output logic [ADDR_WIDTH-1:0]   scrambled_addr_o,
  input  logic [DATA_WIDTH-1:0]   write_data_i,
  output logic [DATA_WIDTH-1:0]   scrambled_write_data_o,
  input  logic [DATA_WIDTH-1:0]   scrambled_read_data_i,
  output logic [DATA_WIDTH-1:0]   read_data_o
);

  logic [31:0] round_key;
  logic [31:0] after_key_xor;
  logic [31:0] after_sbox;
  logic [31:0] after_iplayer;
  logic [31:0] after_ibox;

  scrambler_addr_tweak #(
    .ADDR_WIDTH(ADDR_WIDTH)
  ) u_addr_tweak (
    .addr_i         (addr_i),
    .scrambler_key_i(scrambler_key_i),
    .round_key_o    (round_key)
  );

  assign scrambled_addr_o = addr_scramble12(addr_i, scrambler_key_i[ADDR_WIDTH-1:0]);

  // Scramble
  assign after_key_xor = write_data_i ^ round_key;
  assign after_sbox = {sbox4(after_key_xor[31:28]),
                         sbox4(after_key_xor[27:24]),
                         sbox4(after_key_xor[23:20]),
                         sbox4(after_key_xor[19:16]),
                         sbox4(after_key_xor[15:12]),
                         sbox4(after_key_xor[11:8]),
                         sbox4(after_key_xor[7:4]),
                         sbox4(after_key_xor[3:0])};

  if (BYTE_WISE == 0) begin : gen_scramble_word
    assign scrambled_write_data_o = perm32(after_sbox);
  end else begin : gen_scramble_bytewise
    assign scrambled_write_data_o = {
      perm8(after_sbox[31:24]),
      perm8(after_sbox[23:16]),
      perm8(after_sbox[15:8]),
      perm8(after_sbox[7:0])
    };
  end

  // Descramble
  if (BYTE_WISE == 0) begin : gen_descramble_word
    assign after_iplayer = iperm32(scrambled_read_data_i);
  end else begin : gen_descramble_bytewise
    assign after_iplayer = {
      iperm8(scrambled_read_data_i[31:24]),
      iperm8(scrambled_read_data_i[23:16]),
      iperm8(scrambled_read_data_i[15:8]),
      iperm8(scrambled_read_data_i[7:0])
    };
  end

  assign after_ibox = {ibox4(after_iplayer[31:28]),
                         ibox4(after_iplayer[27:24]),
                         ibox4(after_iplayer[23:20]),
                         ibox4(after_iplayer[19:16]),
                         ibox4(after_iplayer[15:12]),
                         ibox4(after_iplayer[11:8]),
                         ibox4(after_iplayer[7:4]),
                         ibox4(after_iplayer[3:0])};
  assign read_data_o = after_ibox ^ round_key;

endmodule
