# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2026 Tenstorrent USA, Inc.
"""I2C field masks from generated PeakRDL headers (shared by I2C sequences).

Addresses stay in ``smc_addr_map``; this module only exports ``_bm`` field packs
from ``hw/ip/i2c/regs/gen/c/{i2c,i2c_ctrl}.h``.
"""

from __future__ import annotations

from pathlib import Path

from .smc_addr_map import _field_mask

_REPO = Path(__file__).resolve().parents[6]
_I2C_H = _REPO / "hw" / "ip" / "i2c" / "regs" / "gen" / "c" / "i2c.h"
_I2C_CTRL_H = _REPO / "hw" / "ip" / "i2c" / "regs" / "gen" / "c" / "i2c_ctrl.h"

# Wrapper I2C_CTRL (pad mux / mode)
I2C_WRAP_EN = _field_mask(_I2C_CTRL_H, "I2C_CTRL__I2C_CTRL__I2C_EN_bm")
I2C_WRAP_CONTROLLER_MODE = _field_mask(_I2C_CTRL_H, "I2C_CTRL__I2C_CTRL__I2C_CONTROLLER_MODE_EN_bm")
I2C_WRAP_SMBUS_EN = _field_mask(_I2C_CTRL_H, "I2C_CTRL__I2C_CTRL__SMBUS_EN_bm")
I2C_WRAP_CTRL_HOST = I2C_WRAP_EN | I2C_WRAP_CONTROLLER_MODE
I2C_WRAP_CTRL_TARGET = I2C_WRAP_EN
I2C_WRAP_CTRL_HOST_SMBUS = I2C_WRAP_CTRL_HOST | I2C_WRAP_SMBUS_EN
I2C_WRAP_CTRL_TARGET_SMBUS = I2C_WRAP_CTRL_TARGET | I2C_WRAP_SMBUS_EN

# OpenTitan I2C CTRL / STATUS / FDATA / FIFO_CTRL / ACQDATA
I2C_CTRL_ENABLEHOST = _field_mask(_I2C_H, "I2C__CTRL__ENABLEHOST_bm")
I2C_CTRL_ENABLETARGET = _field_mask(_I2C_H, "I2C__CTRL__ENABLETARGET_bm")
I2C_CTRL_MULTI_CONTROLLER_MONITOR_EN = _field_mask(
    _I2C_H, "I2C__CTRL__MULTI_CONTROLLER_MONITOR_EN_bm"
)
I2C_CTRL_ACQ_START_STOP_EN = _field_mask(_I2C_H, "I2C__CTRL__ACQ_START_STOP_EN_bm")
I2C_CTRL_TX_STRETCH_CTRL_EN = _field_mask(_I2C_H, "I2C__CTRL__TX_STRETCH_CTRL_EN_bm")

I2C_STATUS_HOSTIDLE = _field_mask(_I2C_H, "I2C__STATUS__HOSTIDLE_bm")
I2C_STATUS_TARGETIDLE = _field_mask(_I2C_H, "I2C__STATUS__TARGETIDLE_bm")

# Field masks for the timeout / FIFO-config CSR sweep.
I2C_HOST_TIMEOUT_CTRL_VAL = _field_mask(_I2C_H, "I2C__HOST_TIMEOUT_CTRL__VAL_bm")
I2C_TARGET_TIMEOUT_CTRL_VAL = _field_mask(_I2C_H, "I2C__TARGET_TIMEOUT_CTRL__VAL_bm")
I2C_TARGET_TIMEOUT_CTRL_EN = _field_mask(_I2C_H, "I2C__TARGET_TIMEOUT_CTRL__EN_bm")
I2C_NACK_HANDLER_TIMEOUT_VAL = _field_mask(_I2C_H, "I2C__HOST_NACK_HANDLER_TIMEOUT__VAL_bm")
I2C_NACK_HANDLER_TIMEOUT_EN = _field_mask(_I2C_H, "I2C__HOST_NACK_HANDLER_TIMEOUT__EN_bm")
I2C_HOST_FIFO_CONFIG_RX_THRESH = _field_mask(_I2C_H, "I2C__HOST_FIFO_CONFIG__RX_THRESH_bm")
I2C_HOST_FIFO_CONFIG_FMT_THRESH = _field_mask(_I2C_H, "I2C__HOST_FIFO_CONFIG__FMT_THRESH_bm")
I2C_HOST_FIFO_STATUS_FMTLVL = _field_mask(_I2C_H, "I2C__HOST_FIFO_STATUS__FMTLVL_bm")
I2C_STATUS_ACQEMPTY = _field_mask(_I2C_H, "I2C__STATUS__ACQEMPTY_bm")
I2C_STATUS_RXEMPTY = _field_mask(_I2C_H, "I2C__STATUS__RXEMPTY_bm")
I2C_STATUS_FMTFULL = _field_mask(_I2C_H, "I2C__STATUS__FMTFULL_bm")
I2C_STATUS_FMTEMPTY = _field_mask(_I2C_H, "I2C__STATUS__FMTEMPTY_bm")
I2C_STATUS_RXFULL = _field_mask(_I2C_H, "I2C__STATUS__RXFULL_bm")
I2C_STATUS_TXFULL = _field_mask(_I2C_H, "I2C__STATUS__TXFULL_bm")
I2C_STATUS_TXEMPTY = _field_mask(_I2C_H, "I2C__STATUS__TXEMPTY_bm")
I2C_STATUS_ACQFULL = _field_mask(_I2C_H, "I2C__STATUS__ACQFULL_bm")

I2C_SMBUS_CTRL_SMBSUS = _field_mask(_I2C_H, "I2C__SMBUS_CTRL__SMBSUS_bm")
I2C_SMBUS_CTRL_SMBALERT = _field_mask(_I2C_H, "I2C__SMBUS_CTRL__SMBALERT_bm")
I2C_SMBUS_STATUS_SMBSUS = _field_mask(_I2C_H, "I2C__SMBUS_STATUS__SMBSUS_bm")
I2C_SMBUS_STATUS_SMBALERT = _field_mask(_I2C_H, "I2C__SMBUS_STATUS__SMBALERT_bm")
I2C_INTR_STATE_SMBALERT = _field_mask(_I2C_H, "I2C__INTR_STATE__SMBALERT_bm")
I2C_INTR_ENABLE_SMBALERT = _field_mask(_I2C_H, "I2C__INTR_ENABLE__SMBALERT_bm")

I2C_FDATA_START = _field_mask(_I2C_H, "I2C__FDATA__START_bm")
I2C_FDATA_STOP = _field_mask(_I2C_H, "I2C__FDATA__STOP_bm")
I2C_FDATA_READB = _field_mask(_I2C_H, "I2C__FDATA__READB_bm")

I2C_CONTROLLER_EVENTS_NACK = _field_mask(_I2C_H, "I2C__CONTROLLER_EVENTS__NACK_bm")
I2C_CONTROLLER_EVENTS_UNHANDLED_NACK_TIMEOUT = _field_mask(
    _I2C_H, "I2C__CONTROLLER_EVENTS__UNHANDLED_NACK_TIMEOUT_bm"
)
I2C_CONTROLLER_EVENTS_BUS_TIMEOUT = _field_mask(_I2C_H, "I2C__CONTROLLER_EVENTS__BUS_TIMEOUT_bm")
I2C_CONTROLLER_EVENTS_ARBITRATION_LOST = _field_mask(
    _I2C_H, "I2C__CONTROLLER_EVENTS__ARBITRATION_LOST_bm"
)
I2C_CONTROLLER_EVENTS_ALL = (
    I2C_CONTROLLER_EVENTS_NACK
    | I2C_CONTROLLER_EVENTS_UNHANDLED_NACK_TIMEOUT
    | I2C_CONTROLLER_EVENTS_BUS_TIMEOUT
    | I2C_CONTROLLER_EVENTS_ARBITRATION_LOST
)

I2C_FIFO_CTRL_RXRST = _field_mask(_I2C_H, "I2C__FIFO_CTRL__RXRST_bm")
I2C_FIFO_CTRL_FMTRST = _field_mask(_I2C_H, "I2C__FIFO_CTRL__FMTRST_bm")
I2C_FIFO_CTRL_TXRST = _field_mask(_I2C_H, "I2C__FIFO_CTRL__TXRST_bm")
I2C_FIFO_CTRL_ACQRST = _field_mask(_I2C_H, "I2C__FIFO_CTRL__ACQRST_bm")
I2C_FIFO_CTRL_RXRST_FMTRST = I2C_FIFO_CTRL_RXRST | I2C_FIFO_CTRL_FMTRST

I2C_INTR_STATE_ACQ_THRESHOLD = _field_mask(_I2C_H, "I2C__INTR_STATE__ACQ_THRESHOLD_bm")
I2C_INTR_STATE_TX_THRESHOLD = _field_mask(_I2C_H, "I2C__INTR_STATE__TX_THRESHOLD_bm")
I2C_INTR_ENABLE_ACQ_THRESHOLD = _field_mask(_I2C_H, "I2C__INTR_ENABLE__ACQ_THRESHOLD_bm")
I2C_INTR_ENABLE_TX_THRESHOLD = _field_mask(_I2C_H, "I2C__INTR_ENABLE__TX_THRESHOLD_bm")
I2C_INTR_STATE_STRETCH_TIMEOUT = _field_mask(_I2C_H, "I2C__INTR_STATE__STRETCH_TIMEOUT_bm")
I2C_INTR_ENABLE_STRETCH_TIMEOUT = _field_mask(_I2C_H, "I2C__INTR_ENABLE__STRETCH_TIMEOUT_bm")
I2C_INTR_STATE_TX_STRETCH = _field_mask(_I2C_H, "I2C__INTR_STATE__TX_STRETCH_bm")
I2C_INTR_ENABLE_TX_STRETCH = _field_mask(_I2C_H, "I2C__INTR_ENABLE__TX_STRETCH_bm")
I2C_TARGET_EVENTS_TX_PENDING = _field_mask(_I2C_H, "I2C__TARGET_EVENTS__TX_PENDING_bm")
I2C_INTR_STATE_FMT_THRESHOLD = _field_mask(_I2C_H, "I2C__INTR_STATE__FMT_THRESHOLD_bm")
I2C_INTR_ENABLE_FMT_THRESHOLD = _field_mask(_I2C_H, "I2C__INTR_ENABLE__FMT_THRESHOLD_bm")
I2C_TIMEOUT_CTRL_EN = _field_mask(_I2C_H, "I2C__TIMEOUT_CTRL__EN_bm")
I2C_TIMEOUT_CTRL_MODE = _field_mask(_I2C_H, "I2C__TIMEOUT_CTRL__MODE_bm")
I2C_TIMEOUT_CTRL_VAL = _field_mask(_I2C_H, "I2C__TIMEOUT_CTRL__VAL_bm")

I2C_TARGET_FIFO_CONFIG_ACQ_THRESH_BP = _field_mask(_I2C_H, "I2C__TARGET_FIFO_CONFIG__ACQ_THRESH_bp")
I2C_TARGET_FIFO_CONFIG_TX_THRESH_BP = _field_mask(_I2C_H, "I2C__TARGET_FIFO_CONFIG__TX_THRESH_bp")
I2C_TARGET_FIFO_STATUS_ACQLVL_BM = _field_mask(_I2C_H, "I2C__TARGET_FIFO_STATUS__ACQLVL_bm")
I2C_TARGET_FIFO_STATUS_ACQLVL_BP = _field_mask(_I2C_H, "I2C__TARGET_FIFO_STATUS__ACQLVL_bp")
I2C_TARGET_FIFO_STATUS_TXLVL_BM = _field_mask(_I2C_H, "I2C__TARGET_FIFO_STATUS__TXLVL_bm")
I2C_HOST_FIFO_CONFIG_FMT_THRESH_BP = _field_mask(_I2C_H, "I2C__HOST_FIFO_CONFIG__FMT_THRESH_bp")
I2C_HOST_FIFO_STATUS_FMTLVL_BM = _field_mask(_I2C_H, "I2C__HOST_FIFO_STATUS__FMTLVL_bm")
I2C_HOST_FIFO_STATUS_RXLVL_BM = _field_mask(_I2C_H, "I2C__HOST_FIFO_STATUS__RXLVL_bm")
I2C_HOST_FIFO_STATUS_RXLVL_BP = _field_mask(_I2C_H, "I2C__HOST_FIFO_STATUS__RXLVL_bp")

I2C_ACQDATA_ABYTE = _field_mask(_I2C_H, "I2C__ACQDATA__ABYTE_bm")
I2C_ACQDATA_SIGNAL = _field_mask(_I2C_H, "I2C__ACQDATA__SIGNAL_bm")
I2C_ACQDATA_SIGNAL_BP = _field_mask(_I2C_H, "I2C__ACQDATA__SIGNAL_bp")

# OT ACQDATA.SIGNAL encoding (OpenTitan i2c)
I2C_ACQ_SIGNAL_NONE = 0  # data byte (ACK path)
I2C_ACQ_SIGNAL_START = 1
I2C_ACQ_SIGNAL_STOP = 2


def acq_abyte(word: int) -> int:
    return int(word) & I2C_ACQDATA_ABYTE


def acq_signal(word: int) -> int:
    return (int(word) & I2C_ACQDATA_SIGNAL) >> I2C_ACQDATA_SIGNAL_BP


def pack_acq(abyte: int, signal: int) -> int:
    return (abyte & I2C_ACQDATA_ABYTE) | ((signal & 0x7) << I2C_ACQDATA_SIGNAL_BP)
