# SPDX-License-Identifier: Apache-2.0
"""P1 coverage-gap round 2: filter multi-entry sweep.

RTL exposes 16 inbound + 16 outbound filter entries. Round-1
`smc_input_fabric_axi_wr_rd_test` only touches entry 0 of each.
This test sweeps FILTER_CONFIG (offset 0x00) of every entry to prove
each filter slot's decode is alive.
"""

from __future__ import annotations

import sys
from pathlib import Path

from .smc_csr_seq_utils import SmcCsrSeq

# Generated PeakRDL map (hw/sys/smc/regs/gen/py/smc_reg.py).
_SMC_REG_PY = Path(__file__).resolve().parents[3] / "regs" / "gen" / "py"
if str(_SMC_REG_PY) not in sys.path:
    sys.path.insert(0, str(_SMC_REG_PY))

from smc_reg import (  # noqa: E402
    FILTER_CTRL_FILTER_CONFIG_REG_DEFAULT,
    SMC_INBOUND_FILTER_CTRL_0__FILTER_CONFIG_REG_ADDR,
    SMC_INBOUND_FILTER_CTRL_1__FILTER_CONFIG_REG_ADDR,
    SMC_INBOUND_FILTER_CTRL_2__FILTER_CONFIG_REG_ADDR,
    SMC_INBOUND_FILTER_CTRL_3__FILTER_CONFIG_REG_ADDR,
    SMC_INBOUND_FILTER_CTRL_4__FILTER_CONFIG_REG_ADDR,
    SMC_INBOUND_FILTER_CTRL_5__FILTER_CONFIG_REG_ADDR,
    SMC_INBOUND_FILTER_CTRL_6__FILTER_CONFIG_REG_ADDR,
    SMC_INBOUND_FILTER_CTRL_7__FILTER_CONFIG_REG_ADDR,
    SMC_INBOUND_FILTER_CTRL_8__FILTER_CONFIG_REG_ADDR,
    SMC_INBOUND_FILTER_CTRL_9__FILTER_CONFIG_REG_ADDR,
    SMC_INBOUND_FILTER_CTRL_10__FILTER_CONFIG_REG_ADDR,
    SMC_INBOUND_FILTER_CTRL_11__FILTER_CONFIG_REG_ADDR,
    SMC_INBOUND_FILTER_CTRL_12__FILTER_CONFIG_REG_ADDR,
    SMC_INBOUND_FILTER_CTRL_13__FILTER_CONFIG_REG_ADDR,
    SMC_INBOUND_FILTER_CTRL_14__FILTER_CONFIG_REG_ADDR,
    SMC_INBOUND_FILTER_CTRL_15__FILTER_CONFIG_REG_ADDR,
    SMC_OUTBOUND_FILTER_CTRL_0__FILTER_CONFIG_REG_ADDR,
    SMC_OUTBOUND_FILTER_CTRL_1__FILTER_CONFIG_REG_ADDR,
    SMC_OUTBOUND_FILTER_CTRL_2__FILTER_CONFIG_REG_ADDR,
    SMC_OUTBOUND_FILTER_CTRL_3__FILTER_CONFIG_REG_ADDR,
    SMC_OUTBOUND_FILTER_CTRL_4__FILTER_CONFIG_REG_ADDR,
    SMC_OUTBOUND_FILTER_CTRL_5__FILTER_CONFIG_REG_ADDR,
    SMC_OUTBOUND_FILTER_CTRL_6__FILTER_CONFIG_REG_ADDR,
    SMC_OUTBOUND_FILTER_CTRL_7__FILTER_CONFIG_REG_ADDR,
    SMC_OUTBOUND_FILTER_CTRL_8__FILTER_CONFIG_REG_ADDR,
    SMC_OUTBOUND_FILTER_CTRL_9__FILTER_CONFIG_REG_ADDR,
    SMC_OUTBOUND_FILTER_CTRL_10__FILTER_CONFIG_REG_ADDR,
    SMC_OUTBOUND_FILTER_CTRL_11__FILTER_CONFIG_REG_ADDR,
    SMC_OUTBOUND_FILTER_CTRL_12__FILTER_CONFIG_REG_ADDR,
    SMC_OUTBOUND_FILTER_CTRL_13__FILTER_CONFIG_REG_ADDR,
    SMC_OUTBOUND_FILTER_CTRL_14__FILTER_CONFIG_REG_ADDR,
    SMC_OUTBOUND_FILTER_CTRL_15__FILTER_CONFIG_REG_ADDR,
)

# PeakRDL-traceable FILTER_CONFIG addresses (filter_ctrl.rdl) and RDL reset
# (FILTER_CTRL_FILTER_CONFIG_REG_DEFAULT = 0x3000). Each read verifies
# per-slot decode AND the full 64-bit RDL reset content, not merely OKAY.
_INBOUND_FILTER_CONFIG = (
    SMC_INBOUND_FILTER_CTRL_0__FILTER_CONFIG_REG_ADDR,
    SMC_INBOUND_FILTER_CTRL_1__FILTER_CONFIG_REG_ADDR,
    SMC_INBOUND_FILTER_CTRL_2__FILTER_CONFIG_REG_ADDR,
    SMC_INBOUND_FILTER_CTRL_3__FILTER_CONFIG_REG_ADDR,
    SMC_INBOUND_FILTER_CTRL_4__FILTER_CONFIG_REG_ADDR,
    SMC_INBOUND_FILTER_CTRL_5__FILTER_CONFIG_REG_ADDR,
    SMC_INBOUND_FILTER_CTRL_6__FILTER_CONFIG_REG_ADDR,
    SMC_INBOUND_FILTER_CTRL_7__FILTER_CONFIG_REG_ADDR,
    SMC_INBOUND_FILTER_CTRL_8__FILTER_CONFIG_REG_ADDR,
    SMC_INBOUND_FILTER_CTRL_9__FILTER_CONFIG_REG_ADDR,
    SMC_INBOUND_FILTER_CTRL_10__FILTER_CONFIG_REG_ADDR,
    SMC_INBOUND_FILTER_CTRL_11__FILTER_CONFIG_REG_ADDR,
    SMC_INBOUND_FILTER_CTRL_12__FILTER_CONFIG_REG_ADDR,
    SMC_INBOUND_FILTER_CTRL_13__FILTER_CONFIG_REG_ADDR,
    SMC_INBOUND_FILTER_CTRL_14__FILTER_CONFIG_REG_ADDR,
    SMC_INBOUND_FILTER_CTRL_15__FILTER_CONFIG_REG_ADDR,
)
_OUTBOUND_FILTER_CONFIG = (
    SMC_OUTBOUND_FILTER_CTRL_0__FILTER_CONFIG_REG_ADDR,
    SMC_OUTBOUND_FILTER_CTRL_1__FILTER_CONFIG_REG_ADDR,
    SMC_OUTBOUND_FILTER_CTRL_2__FILTER_CONFIG_REG_ADDR,
    SMC_OUTBOUND_FILTER_CTRL_3__FILTER_CONFIG_REG_ADDR,
    SMC_OUTBOUND_FILTER_CTRL_4__FILTER_CONFIG_REG_ADDR,
    SMC_OUTBOUND_FILTER_CTRL_5__FILTER_CONFIG_REG_ADDR,
    SMC_OUTBOUND_FILTER_CTRL_6__FILTER_CONFIG_REG_ADDR,
    SMC_OUTBOUND_FILTER_CTRL_7__FILTER_CONFIG_REG_ADDR,
    SMC_OUTBOUND_FILTER_CTRL_8__FILTER_CONFIG_REG_ADDR,
    SMC_OUTBOUND_FILTER_CTRL_9__FILTER_CONFIG_REG_ADDR,
    SMC_OUTBOUND_FILTER_CTRL_10__FILTER_CONFIG_REG_ADDR,
    SMC_OUTBOUND_FILTER_CTRL_11__FILTER_CONFIG_REG_ADDR,
    SMC_OUTBOUND_FILTER_CTRL_12__FILTER_CONFIG_REG_ADDR,
    SMC_OUTBOUND_FILTER_CTRL_13__FILTER_CONFIG_REG_ADDR,
    SMC_OUTBOUND_FILTER_CTRL_14__FILTER_CONFIG_REG_ADDR,
    SMC_OUTBOUND_FILTER_CTRL_15__FILTER_CONFIG_REG_ADDR,
)


class smc_filter_multi_entry_test_seq(SmcCsrSeq):
    async def body(self) -> None:
        for i, addr in enumerate(_INBOUND_FILTER_CONFIG):
            await self.csr_read(
                f"INBOUND_FILTER_{i}_CONFIG",
                addr,
                expected=FILTER_CTRL_FILTER_CONFIG_REG_DEFAULT,
                length=8,
            )
        for i, addr in enumerate(_OUTBOUND_FILTER_CONFIG):
            await self.csr_read(
                f"OUTBOUND_FILTER_{i}_CONFIG",
                addr,
                expected=FILTER_CTRL_FILTER_CONFIG_REG_DEFAULT,
                length=8,
            )
        expected = len(_INBOUND_FILTER_CONFIG) + len(_OUTBOUND_FILTER_CONFIG)
        assert self.accesses == expected, "filter multi-entry sweep count mismatch"
