# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2026 Tenstorrent USA, Inc.
"""P1 coverage-gap: MMODE_REMAP + CLA + full ALIAS_REMAP sweep
(TC_SMC_P1CG_16/17/18).

Bundles three previously-unreached fabric-side surfaces:

* SMC_MMODE_REMAP_0..7 — machine-mode remap table entries (ATTRS).
* SMC_CLA_REG — Cluster Local Aggregator window (error-slave probes).
* SMC_ALIAS_REMAP_0..7 full sweep — P0/P1-4 only touch entry 0.
"""

from __future__ import annotations

import sys
from pathlib import Path

from .smc_csr_seq_utils import SmcCsrSeq

# Generated PeakRDL map (hw/sys/smc/regs/gen/py/smc_reg.py).
_SMC_REG_PY = Path(__file__).resolve().parents[3] / "regs" / "gen" / "py"
if str(_SMC_REG_PY) not in sys.path:
    sys.path.insert(0, str(_SMC_REG_PY))

from smc_reg import (  # noqa: E402
    SMC_ALIAS_REMAP_0__REGION_REGION_ATTRS_REG_ADDR,
    SMC_ALIAS_REMAP_0__REGION_REGION_END_REG_ADDR,
    SMC_ALIAS_REMAP_0__REGION_REGION_START_REG_ADDR,
    SMC_ALIAS_REMAP_1__REGION_REGION_ATTRS_REG_ADDR,
    SMC_ALIAS_REMAP_1__REGION_REGION_END_REG_ADDR,
    SMC_ALIAS_REMAP_1__REGION_REGION_START_REG_ADDR,
    SMC_ALIAS_REMAP_2__REGION_REGION_ATTRS_REG_ADDR,
    SMC_ALIAS_REMAP_2__REGION_REGION_END_REG_ADDR,
    SMC_ALIAS_REMAP_2__REGION_REGION_START_REG_ADDR,
    SMC_ALIAS_REMAP_3__REGION_REGION_ATTRS_REG_ADDR,
    SMC_ALIAS_REMAP_3__REGION_REGION_END_REG_ADDR,
    SMC_ALIAS_REMAP_3__REGION_REGION_START_REG_ADDR,
    SMC_ALIAS_REMAP_4__REGION_REGION_ATTRS_REG_ADDR,
    SMC_ALIAS_REMAP_4__REGION_REGION_END_REG_ADDR,
    SMC_ALIAS_REMAP_4__REGION_REGION_START_REG_ADDR,
    SMC_ALIAS_REMAP_5__REGION_REGION_ATTRS_REG_ADDR,
    SMC_ALIAS_REMAP_5__REGION_REGION_END_REG_ADDR,
    SMC_ALIAS_REMAP_5__REGION_REGION_START_REG_ADDR,
    SMC_ALIAS_REMAP_6__REGION_REGION_ATTRS_REG_ADDR,
    SMC_ALIAS_REMAP_6__REGION_REGION_END_REG_ADDR,
    SMC_ALIAS_REMAP_6__REGION_REGION_START_REG_ADDR,
    SMC_ALIAS_REMAP_7__REGION_REGION_ATTRS_REG_ADDR,
    SMC_ALIAS_REMAP_7__REGION_REGION_END_REG_ADDR,
    SMC_ALIAS_REMAP_7__REGION_REGION_START_REG_ADDR,
    SMC_CLA_REG_MAP_BASE_ADDR,
    SMC_MMODE_REMAP_0__REGION_REGION_ATTRS_REG_ADDR,
    SMC_MMODE_REMAP_1__REGION_REGION_ATTRS_REG_ADDR,
    SMC_MMODE_REMAP_2__REGION_REGION_ATTRS_REG_ADDR,
    SMC_MMODE_REMAP_3__REGION_REGION_ATTRS_REG_ADDR,
    SMC_MMODE_REMAP_4__REGION_REGION_ATTRS_REG_ADDR,
    SMC_MMODE_REMAP_5__REGION_REGION_ATTRS_REG_ADDR,
    SMC_MMODE_REMAP_6__REGION_REGION_ATTRS_REG_ADDR,
    SMC_MMODE_REMAP_7__REGION_REGION_ATTRS_REG_ADDR,
)

# Per-entry ATTRS addresses from the generated map.
MMODE_REMAP_ATTRS_ADDRS = (
    SMC_MMODE_REMAP_0__REGION_REGION_ATTRS_REG_ADDR,
    SMC_MMODE_REMAP_1__REGION_REGION_ATTRS_REG_ADDR,
    SMC_MMODE_REMAP_2__REGION_REGION_ATTRS_REG_ADDR,
    SMC_MMODE_REMAP_3__REGION_REGION_ATTRS_REG_ADDR,
    SMC_MMODE_REMAP_4__REGION_REGION_ATTRS_REG_ADDR,
    SMC_MMODE_REMAP_5__REGION_REGION_ATTRS_REG_ADDR,
    SMC_MMODE_REMAP_6__REGION_REGION_ATTRS_REG_ADDR,
    SMC_MMODE_REMAP_7__REGION_REGION_ATTRS_REG_ADDR,
)

# Per-entry START/END/ATTRS from the generated map.
ALIAS_REMAP_REGS = (
    ("ALIAS_REMAP_0_START", SMC_ALIAS_REMAP_0__REGION_REGION_START_REG_ADDR),
    ("ALIAS_REMAP_0_END", SMC_ALIAS_REMAP_0__REGION_REGION_END_REG_ADDR),
    ("ALIAS_REMAP_0_ATTRS", SMC_ALIAS_REMAP_0__REGION_REGION_ATTRS_REG_ADDR),
    ("ALIAS_REMAP_1_START", SMC_ALIAS_REMAP_1__REGION_REGION_START_REG_ADDR),
    ("ALIAS_REMAP_1_END", SMC_ALIAS_REMAP_1__REGION_REGION_END_REG_ADDR),
    ("ALIAS_REMAP_1_ATTRS", SMC_ALIAS_REMAP_1__REGION_REGION_ATTRS_REG_ADDR),
    ("ALIAS_REMAP_2_START", SMC_ALIAS_REMAP_2__REGION_REGION_START_REG_ADDR),
    ("ALIAS_REMAP_2_END", SMC_ALIAS_REMAP_2__REGION_REGION_END_REG_ADDR),
    ("ALIAS_REMAP_2_ATTRS", SMC_ALIAS_REMAP_2__REGION_REGION_ATTRS_REG_ADDR),
    ("ALIAS_REMAP_3_START", SMC_ALIAS_REMAP_3__REGION_REGION_START_REG_ADDR),
    ("ALIAS_REMAP_3_END", SMC_ALIAS_REMAP_3__REGION_REGION_END_REG_ADDR),
    ("ALIAS_REMAP_3_ATTRS", SMC_ALIAS_REMAP_3__REGION_REGION_ATTRS_REG_ADDR),
    ("ALIAS_REMAP_4_START", SMC_ALIAS_REMAP_4__REGION_REGION_START_REG_ADDR),
    ("ALIAS_REMAP_4_END", SMC_ALIAS_REMAP_4__REGION_REGION_END_REG_ADDR),
    ("ALIAS_REMAP_4_ATTRS", SMC_ALIAS_REMAP_4__REGION_REGION_ATTRS_REG_ADDR),
    ("ALIAS_REMAP_5_START", SMC_ALIAS_REMAP_5__REGION_REGION_START_REG_ADDR),
    ("ALIAS_REMAP_5_END", SMC_ALIAS_REMAP_5__REGION_REGION_END_REG_ADDR),
    ("ALIAS_REMAP_5_ATTRS", SMC_ALIAS_REMAP_5__REGION_REGION_ATTRS_REG_ADDR),
    ("ALIAS_REMAP_6_START", SMC_ALIAS_REMAP_6__REGION_REGION_START_REG_ADDR),
    ("ALIAS_REMAP_6_END", SMC_ALIAS_REMAP_6__REGION_REGION_END_REG_ADDR),
    ("ALIAS_REMAP_6_ATTRS", SMC_ALIAS_REMAP_6__REGION_REGION_ATTRS_REG_ADDR),
    ("ALIAS_REMAP_7_START", SMC_ALIAS_REMAP_7__REGION_REGION_START_REG_ADDR),
    ("ALIAS_REMAP_7_END", SMC_ALIAS_REMAP_7__REGION_REGION_END_REG_ADDR),
    ("ALIAS_REMAP_7_ATTRS", SMC_ALIAS_REMAP_7__REGION_REGION_ATTRS_REG_ADDR),
)

# Arbitrary in-window probes of the CLA error-slave decode (power-gated /
# absent in the OSS bench). Offsets are not named registers in the generated
# map — only the block base is authoritative.
CLA_WINDOW_PROBES = (
    ("CLA_WINDOW_OFF0", SMC_CLA_REG_MAP_BASE_ADDR + 0x0),
    ("CLA_WINDOW_OFF4", SMC_CLA_REG_MAP_BASE_ADDR + 0x4),
    ("CLA_WINDOW_OFF8", SMC_CLA_REG_MAP_BASE_ADDR + 0x8),
)

_EXPECTED_ACCESSES = (
    len(MMODE_REMAP_ATTRS_ADDRS) + len(ALIAS_REMAP_REGS) + len(CLA_WINDOW_PROBES)
)


class smc_remap_cla_test_seq(SmcCsrSeq):
    async def body(self) -> None:
        # MMODE_REMAP + ALIAS_REMAP are real fabric CSRs and decode/return OKAY
        # here: csr_read gates each on the scoreboard's resp_ok, so a broken remap
        # decode fails the test.
        for i, addr in enumerate(MMODE_REMAP_ATTRS_ADDRS):
            await self.csr_read(f"MMODE_REMAP_{i}_ATTRS", addr)
        for name, addr in ALIAS_REMAP_REGS:
            await self.csr_read(name, addr)
        # SMC_CLA_REG is an error-slave window (SLVERR, data=0) in the OSS bench
        # (CLA is power-gated / absent). Assert the error response deterministically
        # -- fails if it ever starts returning OKAY.
        for name, addr in CLA_WINDOW_PROBES:
            await self.csr_read_expect_error(name, addr)
        assert self.accesses == _EXPECTED_ACCESSES, (
            "MMODE + ALIAS + CLA sweep count mismatch"
        )
