// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 Tenstorrent USA, Inc.

= OCAH Code of Conduct
:doctype: book
:sectanchors:
:sectlinks:
:sectnums:
:source-highlighter: highlight.js

[WARNING]
Simplified version of the OpenTitan Code of Conduct.  Needs review.

== Code of Conduct

This code of conduct applies to all spaces managed on behalf of the OCAH project. 

- *Be welcoming*. 
+
We strive to be a community that welcomes and supports people of all backgrounds and identities. This includes, but is not limited to members of any race, ethnicity, culture, national origin, colour, immigration status, social and economic class, educational level, sex, sexual orientation, gender identity and expression, age, size, family status, political belief, religion or lack thereof, and mental and physical ability.

- *Be considerate*. 
+
Your work will be used by other people, and you in turn will depend on the work of others. Any decision you take will affect users and colleagues, and you should take those consequences into account. Remember that we’re a world-wide community, so you might not be communicating in someone else’s primary language. Many of our community members are here as part of their work, and content (words, images, videos) you share should be appropriate for professional workplaces.

- *Be respectful*. 
+
Not all of us will agree all the time, but disagreement is no excuse for poor behaviour and poor manners. We might all experience some frustration now and then, but we cannot allow that frustration to turn into a personal attack. It’s important to remember that a community where people feel uncomfortable or threatened is not a productive one. Members of the community should be respectful when dealing with other members as well as with people outside the community.

- *Be careful*
+
in the words and images that you choose and be kind to others. Do not insult or put down other participants. Harassment and other exclusionary behaviour aren’t acceptable. In general, if someone asks you to stop, then stop. Persisting in such behaviour after being asked to stop is considered harassment.
+
This includes, but is not limited to:
+
**  Violent threats or language directed against another person.
**  Discriminatory jokes and language.
** Posting sexually explicit or violent material.
** Posting (or threatening to post) other people’s personally identifying information ("doxing").
** Personal insults, especially those using racist or sexist terms.
** Unwelcome sexual attention.
** Advocating for, or encouraging, any of the above behaviour.

- *When we disagree, try to understand why*. 
+
Disagreements, both social and technical, happen all the time. It is important that we resolve disagreements and differing views constructively.  Different people have different perspectives on issues. Being unable to understand why someone holds a viewpoint doesn’t mean that they’re wrong. Focus on helping to resolve issues and learning from mistakes.

== Reporting Problems

[WARNING]
If you believe someone is violating the code of conduct you can report it to the Code of Conduct team by emailing XXXXXX.

All reports will be kept confidential. This isn’t a public list and only members of the Code of Conduct team will receive the report.  If the violation occurs at an event such as a conference or workshop and requires immediate attention, you can also reach out to any of the event organisers or staff.

[NOTE]
If you believe anyone is in physical danger, please notify appropriate law enforcement first. If you are unsure what law enforcement agency is appropriate, please include this in your report and we will attempt to notify them.

If you feel comfortable, please consider including:

* Your contact info (so we can get in touch with you if we need to follow up).
* Names (real, nicknames, or pseudonyms) of any individuals involved. If there were other witnesses besides you, please try to include them as well.
* When and where the incident occurred. Please be as specific as possible.
* Your account of what occurred. If there is a publicly available record (e.g. a mailing list archive or a public IRC logger) please include a link.
* Any extra context you believe existed for the incident.
* If you believe this incident is ongoing.
* Any other information you believe we should have.

== Attribution
This text is based on the OpenTitan Code of Conduct.

