// SPDX-License-Identifier: CC-BY-4.0
// SPDX-FileCopyrightText: 2026 Tenstorrent USA, Inc.

== Reporting Bugs and Defects

[WARNING]
====
This document is currently under development. 

- Do we need a Coordinated Vulnerability Disclosure (CVD) Policy?
====

[NOTE]
The words "Bug" and "Defect" are here used interchangeably to represent any behaviour which is not compliant to specification.

=== Reporting Vulnerabilities

We are dedicated to maintaining the security, integrity and reliability of our hardware and software designs, and we actively encourage responsible security vulnerability reporting from the user community.

Security reports must not be public issues and should use xref:security.adoc[private vulnerability reporting]

=== Reporting Bugs

Ideally, all designs are bug free. However, code will be at different states of maturity.  Some will still be under active testing and development.  Defects may even be found in production code.

If you have discovered a possible defect in the code in this repository, please raise a new GitHub Issue using the process below:

* Open a new issue from
https://github.com/tenstorrent/tt-oca-harness/issues/new/choose[New issue]
* Pick **Bug** as the issue type
** Allowed values live in `.github/issue-taxonomy.yml`
** **Task** represents work items
** **Feature** represents new feature requests
* The following fields are mandatory and must be set:
** *Workstream*
** *Subsystem*
** *Component* (use `General` if unsure)
** *Priority* (use `P2` if unsure)
** *Target release* (use `Future` if unscheduled).
* Please do not assign:
** A GitHub milestone.
** GitHub labels.

=== Defect data

Although the description field is optional, issues raised to represent bugs should include as much detail as possible about the nature of the bug and how it can be reproduced.  The goal should
always be that the defect should be reproduceable from the data in the Issue.

It is helpful to include:

* A copy of, or link to, the program or simulator output.
* Any suggested resolution to the problem.
* All the information needed to reproduce the issue.
** Git hash
** Executed command
** Program input
** Simulation seed
** etc.

=== Reporting documentation issues

If you feel a part of the documentation is inaccurate or could be improved, please raise an Issue to specify the problem.

For document errors, it is helpful to include:

* The document in which the page number occurs.
* For a PDF document
** The section and page numbers
* For the Web site
** The URL and section name
* The observed error or suggested improvement in the document




