// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 Tenstorrent USA, Inc.

== OCAH development guidelines
:doctype: book
:sectanchors:
:sectlinks:
:sectnums:
:source-highlighter: highlight.js

=== Standards

The OCAH design will follow industry or FOSS standards where appropriate:

* SystemVerilog RTL
* AMBA system buses
* SystemRDL memory map
* AsciiDoc documentation with Asciidoctor

The hardware design is written in a synthesizable subset of
SystemVerilog RTL language. The coding standards are adopted from the
lowRISC organization and are also used in OpenTitan.

System interconnect is implemented with AMBA standard buses. AXI4 and
AXI4-lite is used for data interfaces and is generally configured with
64-bit data and address. Control buses for accessing CSRs and other low
speed sources are implemented with 32-bit APB.

The system memory map and component CSRs (Configuration and Status
Registers) are defined in SystemRDL. This is the single source of truth
and all downstream representations are rendered from this source.
Examples are documentation (HTML), C headers, SystemVerilog UVM DV and
SystemVerilog RTL.

=== Development Tools

We aim primarily to use open source tools for the development of OCAH in
order to eliminate commercial dependencies and enabling open-sourcing
not only the design, but also the associated tools.

The goal is to enable new adopters of OCAH to be able to immediately
perform simulations and other analyses of the design using readily
available free tools.

For internal development and testing we will employ commercial tools to
validate the OCAH design, proving readiness for chip deployment i.e.
tapeout. This includes:

* Design verification
* lint tools for code quality
* logic synthesis

=== Component Directory Organization

All components will have a uniform directory structure which has the
following elements:

* README.md : component overview and quick start guide in Markdown
format
* doc/ : detailed AsciiDoc documentation (architecture.adoc, interface.adoc,
memmap.adoc, index.adoc)
* rtl : all SystemVerilog modules <component>_*.sv
* tb : unit level Verilator tests
* regs/ : <component>.rdl SystemRDL CSR memory map definition and generated collateral
* syn : logic synthesis constraints (optional)
* lint : lint waiver files

=== SystemVerilog Coding Guidelines

The high level goals are:

* avoid SystemVerilog constructs that are error prone or not consistently supported, 
particularly across open source tools
* ensure that the code is tidy and easy to read
* keep the code style consistent across the project's code base regardless of who authored it

OCAH will _mostly_ follow the OpenTitan SystemVerilog coding rules
defined by lowRISC group in
https://github.com/lowRISC/style-guides/blob/master/VerilogCodingStyle.md[Verilog
Coding Style]. That document is locally copied for convenience.

This section highlights a few of the most important aspects as well as a
few deviations from the OpenTitan rules. If there is a conflict between
the two, the specification here takes precedence.

* Use two spaces for indentation, matching the lowRISC style guide.
* Use all upper case letters to name enums, constants (localparam), and
parameters instead of UpperCamelCase.
* As stated in the lowRISC guidelines, SystemVerilog Interfaces can be
limited in terms of tool support, so we _highly discourage_ their use as
they are not uniformly supported by open source tools. As an
alternative, struct types can be used instead to bundle groups of input
or output signals to make ports more abstract.
* Finite State Machines (FSMs) are powerful sequence control constructs
but can spiral out of control quickly. Consequences are difficult to
understand "next state" logic and long timing paths. Separate the
combinatorial "next state" logic from the sequential state update into
distinct always blocks. *Do not* combine the two into a single clocked
always block. Opt for a
https://en.wikipedia.org/wiki/Moore_machine[Moore machine]
implementation when possible to aid in timing closure. If you have
complexity of more than ten states or so, use a microsequencer approach.
This is more scalable and maintainable.

There will be additional rules that apply to security sensitive
components such as ciphers. These will be documented in more detail, but
here is a summary for now:

* FSM state encodings are one-hot with error checking
* Error detection is implemented on storage elements and some bus and
computational elements
* Secret data is transferred and stored in secret-split fashion

=== RTL Code Comments

Include a description of the purpose and overall function of the module 
in the header. 

RTL code comments may be redundant or add little value to the code.
Keep comments in the RTL as minimal as possible and, where possible,
make the code self explanatory. 

Do not add a comment which describes the functionality of the code
where the code is clear.

If there is a tricky bit of code with some nuance, add a comment describing 
the overall goal or strategy of the code. 
