// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 Tenstorrent USA, Inc.

[[workflows]]
== Workflows

[WARNING]
====
This section is currently under development.
====

This document specifies the development methodology for this project.

=== Build with Bender and Make

Bender is used for managing IP dependencies and managing builds.

Makefiles will be used for build automation. We have previously
considered other flow such as Bazel but are hesitant to take on extra
complexity.

To initialise or update the Bender-generated file list, run the following
command:

```bash
make generate_filelist
```

=== Simulation and Testing

==== Simulation with Verilator

We will use open source tools as much as possible and hence will focus
on using Verilator for unit tests. Verilator has comprehensive
SystemVerilog (SV) support and is widely used in industry.

Verilator ingests the RTL code along with the test code written in C/C++
to generate a program which is compiled and run with gcc. Writing tests
in C/C++ has many benefits:

* high performance, typically better than commercial simulators
* incorporate third party reference code for ciphers as an example
* incorporate code for analysis
* enable development of emulation systems for firmware developers
* can be migrated to DPI based DV environments for sign-off verification

==== Testbench and Test Sequence

Verilator is our main simulation engine, and we have several choices on
how to create unit test benches and sequences for IP components and the
SEP subsystem:

* Plain _vanilla_ SystemVerilog
* C/C++
* Python with cocotb

The VeeR EL2 CPU which is used in SEP has cocotb based testbenches,
while Caliptra uses mostly C with Verilator. Either choice will be fine
and it is _TBD_ which one we shall emphasize.

We expect that chip integrators and TT verification engineers will use
UVM in their verification flows. The UVM flow is however not in scope
for the open source release of the OCAH project currently. We _may_
release the UVM verification infrastructure to assist teams in full chip
integration efforts, but that remains TBD.

Antmicro has recently released a code coverage dashboard tool which
works with Verilator. This _may_ be used in the verification flows, but
is TBD based on future evaluations.

The testbench is run and configured using a Python script. Run the
following command to see all available options:

```bash
python3 tools/dv/run_dv.py --help
```

==== Visual Debugging and Waveform Viewer

We have two open source choices: the older GTKWave and Surfer. Surfer is
the more modern of the two and runs in either the browser or standalone.
It is under active development and has many nice features such as
facilities for writing protocol interpreters so that we have mnemonic
displays for things like opcodes instead of just raw binary or hex.

Surfer binaries are available on MacOS, Linux and Windows, but can also
run in the browser which is very convenient.

==== References

* https://www.veripool.org/verilator[Verilator documents]
* https://www.cocotb.org[cocotb]
* https://github.com/antmicro/coverview[Coverview]
* https://surfer-project.org[Surfer project website]
* https://ics.jku.at/files/2024RISCVSummit_Surfer.pdf[RISC-V Summit
paper on Surfer]

=== Linting

We use linters within the development of OCAH to perform static analysis
on the codebase. The below rules will check code for errors and poor
formatting. They also enforce a consistent code style.

==== Verilog Style and Lint checking with Verible

TODO

==== Verilog Style and Lint checking with Slang

TODO

==== TCL Script Style and Lint with Tclint

TODO

==== C/C++ Style and Link with Clang-Format

TODO

==== References

* https://github.com/chipsalliance/verible[Verible GitHub]
* https://www.chipsalliance.org/news/integrating-language-server-protocol-in-verible[Verible
LSP guide]
