// SPDX-License-Identifier: Apache-2.0
// (c) 2026 Tenstorrent USA Inc

/*******************************************************************************
 * Header file for register addresses
 *
 * This file was auto-generated by this script:
 *       create_reg_sv_header.py
 * ... from this input file:
 *       tr_mmrs.py
 * ... using this as the target address space:
 *       tr
 *
 * This file should not be modified by hand.
 *
 ******************************************************************************/

`ifndef DFD_TR_CSR_PKG_SVH
`define DFD_TR_CSR_PKG_SVH

package dfd_tr_csr_pkg;



//==============================================================================
// Addresses for Address Map: tr
//==============================================================================


	localparam TR_REG_MAP_BASE_ADDR                                        = 23'h000;


	localparam TR_TRFUNNELCONTROL_REG_OFFSET                               = 23'h4000;
	localparam TR_TRFUNNELCONTROL_REG_ADDR                                 = 23'h4000;
	localparam TR_TRFUNNELIMPL_REG_OFFSET                                  = 23'h4004;
	localparam TR_TRFUNNELIMPL_REG_ADDR                                    = 23'h4004;
	localparam TR_TRFUNNELDISINPUT_REG_OFFSET                              = 23'h4008;
	localparam TR_TRFUNNELDISINPUT_REG_ADDR                                = 23'h4008;
	localparam TR_TRRAMCONTROL_REG_OFFSET                                  = 23'h5000;
	localparam TR_TRRAMCONTROL_REG_ADDR                                    = 23'h5000;
	localparam TR_TRRAMIMPL_REG_OFFSET                                     = 23'h5004;
	localparam TR_TRRAMIMPL_REG_ADDR                                       = 23'h5004;
	localparam TR_TRRAMSTARTLOW_REG_OFFSET                                 = 23'h5010;
	localparam TR_TRRAMSTARTLOW_REG_ADDR                                   = 23'h5010;
	localparam TR_TRRAMSTARTHIGH_REG_OFFSET                                = 23'h5014;
	localparam TR_TRRAMSTARTHIGH_REG_ADDR                                  = 23'h5014;
	localparam TR_TRRAMLIMITLOW_REG_OFFSET                                 = 23'h5018;
	localparam TR_TRRAMLIMITLOW_REG_ADDR                                   = 23'h5018;
	localparam TR_TRRAMLIMITHIGH_REG_OFFSET                                = 23'h501C;
	localparam TR_TRRAMLIMITHIGH_REG_ADDR                                  = 23'h501C;
	localparam TR_TRRAMWPLOW_REG_OFFSET                                    = 23'h5020;
	localparam TR_TRRAMWPLOW_REG_ADDR                                      = 23'h5020;
	localparam TR_TRRAMWPHIGH_REG_OFFSET                                   = 23'h5024;
	localparam TR_TRRAMWPHIGH_REG_ADDR                                     = 23'h5024;
	localparam TR_TRRAMRPLOW_REG_OFFSET                                    = 23'h5028;
	localparam TR_TRRAMRPLOW_REG_ADDR                                      = 23'h5028;
	localparam TR_TRRAMRPHIGH_REG_OFFSET                                   = 23'h502C;
	localparam TR_TRRAMRPHIGH_REG_ADDR                                     = 23'h502C;
	localparam TR_TRRAMDATA_REG_OFFSET                                     = 23'h5040;
	localparam TR_TRRAMDATA_REG_ADDR                                       = 23'h5040;
	localparam TR_TRCUSTOMRAMSMEMLIMITLOW_REG_OFFSET                       = 23'h5E00;
	localparam TR_TRCUSTOMRAMSMEMLIMITLOW_REG_ADDR                         = 23'h5E00;
	localparam TR_TRDSTRAMCONTROL_REG_OFFSET                               = 23'h6000;
	localparam TR_TRDSTRAMCONTROL_REG_ADDR                                 = 23'h6000;
	localparam TR_TRDSTRAMIMPL_REG_OFFSET                                  = 23'h6004;
	localparam TR_TRDSTRAMIMPL_REG_ADDR                                    = 23'h6004;
	localparam TR_TRDSTRAMSTARTLOW_REG_OFFSET                              = 23'h6010;
	localparam TR_TRDSTRAMSTARTLOW_REG_ADDR                                = 23'h6010;
	localparam TR_TRDSTRAMSTARTHIGH_REG_OFFSET                             = 23'h6014;
	localparam TR_TRDSTRAMSTARTHIGH_REG_ADDR                               = 23'h6014;
	localparam TR_TRDSTRAMLIMITLOW_REG_OFFSET                              = 23'h6018;
	localparam TR_TRDSTRAMLIMITLOW_REG_ADDR                                = 23'h6018;
	localparam TR_TRDSTRAMLIMITHIGH_REG_OFFSET                             = 23'h601C;
	localparam TR_TRDSTRAMLIMITHIGH_REG_ADDR                               = 23'h601C;
	localparam TR_TRDSTRAMWPLOW_REG_OFFSET                                 = 23'h6020;
	localparam TR_TRDSTRAMWPLOW_REG_ADDR                                   = 23'h6020;
	localparam TR_TRDSTRAMWPHIGH_REG_OFFSET                                = 23'h6024;
	localparam TR_TRDSTRAMWPHIGH_REG_ADDR                                  = 23'h6024;
	localparam TR_TRDSTRAMRPLOW_REG_OFFSET                                 = 23'h6028;
	localparam TR_TRDSTRAMRPLOW_REG_ADDR                                   = 23'h6028;
	localparam TR_TRDSTRAMRPHIGH_REG_OFFSET                                = 23'h602C;
	localparam TR_TRDSTRAMRPHIGH_REG_ADDR                                  = 23'h602C;
	localparam TR_TRDSTRAMDATA_REG_OFFSET                                  = 23'h6040;
	localparam TR_TRDSTRAMDATA_REG_ADDR                                    = 23'h6040;
	localparam TR_TRCLUSTERFUSECFGLOW_REG_OFFSET                           = 23'h7FF8;
	localparam TR_TRCLUSTERFUSECFGLOW_REG_ADDR                             = 23'h7FF8;
	localparam TR_TRCLUSTERFUSECFGHI_REG_OFFSET                            = 23'h7FFC;
	localparam TR_TRCLUSTERFUSECFGHI_REG_ADDR                              = 23'h7FFC;
	localparam TR_TRSCRATCHLO_REG_OFFSET                                   = 23'h8FE8;
	localparam TR_TRSCRATCHLO_REG_ADDR                                     = 23'h8FE8;
	localparam TR_TRSCRATCHHI_REG_OFFSET                                   = 23'h8FEC;
	localparam TR_TRSCRATCHHI_REG_ADDR                                     = 23'h8FEC;
	localparam TR_TRSCRATCHPADLO_REG_OFFSET                                = 23'h8FF0;
	localparam TR_TRSCRATCHPADLO_REG_ADDR                                  = 23'h8FF0;
	localparam TR_TRSCRATCHPADHI_REG_OFFSET                                = 23'h8FF4;
	localparam TR_TRSCRATCHPADHI_REG_ADDR                                  = 23'h8FF4;



//==============================================================================
// Bit Fields for Address Map: tr
//==============================================================================

	localparam TR_TRFUNNELCONTROL_TRFUNNELACTIVE_MASK                       = 32'h1;
	localparam TR_TRFUNNELCONTROL_TRFUNNELACTIVE_SHIFT                      = 0;
	localparam TR_TRFUNNELCONTROL_TRFUNNELACTIVE_LOW                        = 0;
	localparam TR_TRFUNNELCONTROL_TRFUNNELACTIVE_HIGH                       = 0;
	localparam TR_TRFUNNELCONTROL_TRFUNNELACTIVE_WIDTH                      = 1;

	localparam TR_TRFUNNELCONTROL_TRFUNNELENABLE_MASK                       = 32'h2;
	localparam TR_TRFUNNELCONTROL_TRFUNNELENABLE_SHIFT                      = 1;
	localparam TR_TRFUNNELCONTROL_TRFUNNELENABLE_LOW                        = 1;
	localparam TR_TRFUNNELCONTROL_TRFUNNELENABLE_HIGH                       = 1;
	localparam TR_TRFUNNELCONTROL_TRFUNNELENABLE_WIDTH                      = 1;

	localparam TR_TRFUNNELCONTROL_TRFUNNELEMPTY_MASK                        = 32'h8;
	localparam TR_TRFUNNELCONTROL_TRFUNNELEMPTY_SHIFT                       = 3;
	localparam TR_TRFUNNELCONTROL_TRFUNNELEMPTY_LOW                         = 3;
	localparam TR_TRFUNNELCONTROL_TRFUNNELEMPTY_HIGH                        = 3;
	localparam TR_TRFUNNELCONTROL_TRFUNNELEMPTY_WIDTH                       = 1;

	localparam TR_TRFUNNELIMPL_TRFUNNELVERMAJOR_MASK                        = 32'hF;
	localparam TR_TRFUNNELIMPL_TRFUNNELVERMAJOR_SHIFT                       = 0;
	localparam TR_TRFUNNELIMPL_TRFUNNELVERMAJOR_LOW                         = 0;
	localparam TR_TRFUNNELIMPL_TRFUNNELVERMAJOR_HIGH                        = 3;
	localparam TR_TRFUNNELIMPL_TRFUNNELVERMAJOR_WIDTH                       = 4;

	localparam TR_TRFUNNELIMPL_TRFUNNELVERMINOR_MASK                        = 32'hF0;
	localparam TR_TRFUNNELIMPL_TRFUNNELVERMINOR_SHIFT                       = 4;
	localparam TR_TRFUNNELIMPL_TRFUNNELVERMINOR_LOW                         = 4;
	localparam TR_TRFUNNELIMPL_TRFUNNELVERMINOR_HIGH                        = 7;
	localparam TR_TRFUNNELIMPL_TRFUNNELVERMINOR_WIDTH                       = 4;

	localparam TR_TRFUNNELIMPL_TRFUNNELCOMPTYPE_MASK                        = 32'hF00;
	localparam TR_TRFUNNELIMPL_TRFUNNELCOMPTYPE_SHIFT                       = 8;
	localparam TR_TRFUNNELIMPL_TRFUNNELCOMPTYPE_LOW                         = 8;
	localparam TR_TRFUNNELIMPL_TRFUNNELCOMPTYPE_HIGH                        = 11;
	localparam TR_TRFUNNELIMPL_TRFUNNELCOMPTYPE_WIDTH                       = 4;

	localparam TR_TRFUNNELDISINPUT_TRFUNNELDISINPUT_MASK                    = 32'hFFFF;
	localparam TR_TRFUNNELDISINPUT_TRFUNNELDISINPUT_SHIFT                   = 0;
	localparam TR_TRFUNNELDISINPUT_TRFUNNELDISINPUT_LOW                     = 0;
	localparam TR_TRFUNNELDISINPUT_TRFUNNELDISINPUT_HIGH                    = 15;
	localparam TR_TRFUNNELDISINPUT_TRFUNNELDISINPUT_WIDTH                   = 16;

	localparam TR_TRRAMCONTROL_TRRAMACTIVE_MASK                             = 32'h1;
	localparam TR_TRRAMCONTROL_TRRAMACTIVE_SHIFT                            = 0;
	localparam TR_TRRAMCONTROL_TRRAMACTIVE_LOW                              = 0;
	localparam TR_TRRAMCONTROL_TRRAMACTIVE_HIGH                             = 0;
	localparam TR_TRRAMCONTROL_TRRAMACTIVE_WIDTH                            = 1;

	localparam TR_TRRAMCONTROL_TRRAMENABLE_MASK                             = 32'h2;
	localparam TR_TRRAMCONTROL_TRRAMENABLE_SHIFT                            = 1;
	localparam TR_TRRAMCONTROL_TRRAMENABLE_LOW                              = 1;
	localparam TR_TRRAMCONTROL_TRRAMENABLE_HIGH                             = 1;
	localparam TR_TRRAMCONTROL_TRRAMENABLE_WIDTH                            = 1;

	localparam TR_TRRAMCONTROL_TRRAMEMPTY_MASK                              = 32'h8;
	localparam TR_TRRAMCONTROL_TRRAMEMPTY_SHIFT                             = 3;
	localparam TR_TRRAMCONTROL_TRRAMEMPTY_LOW                               = 3;
	localparam TR_TRRAMCONTROL_TRRAMEMPTY_HIGH                              = 3;
	localparam TR_TRRAMCONTROL_TRRAMEMPTY_WIDTH                             = 1;

	localparam TR_TRRAMCONTROL_TRRAMMODE_MASK                               = 32'h10;
	localparam TR_TRRAMCONTROL_TRRAMMODE_SHIFT                              = 4;
	localparam TR_TRRAMCONTROL_TRRAMMODE_LOW                                = 4;
	localparam TR_TRRAMCONTROL_TRRAMMODE_HIGH                               = 4;
	localparam TR_TRRAMCONTROL_TRRAMMODE_WIDTH                              = 1;

	localparam TR_TRRAMCONTROL_TRRAMSTOPONWRAP_MASK                         = 32'h100;
	localparam TR_TRRAMCONTROL_TRRAMSTOPONWRAP_SHIFT                        = 8;
	localparam TR_TRRAMCONTROL_TRRAMSTOPONWRAP_LOW                          = 8;
	localparam TR_TRRAMCONTROL_TRRAMSTOPONWRAP_HIGH                         = 8;
	localparam TR_TRRAMCONTROL_TRRAMSTOPONWRAP_WIDTH                        = 1;

	localparam TR_TRRAMIMPL_TRRAMVERMAJOR_MASK                              = 32'hF;
	localparam TR_TRRAMIMPL_TRRAMVERMAJOR_SHIFT                             = 0;
	localparam TR_TRRAMIMPL_TRRAMVERMAJOR_LOW                               = 0;
	localparam TR_TRRAMIMPL_TRRAMVERMAJOR_HIGH                              = 3;
	localparam TR_TRRAMIMPL_TRRAMVERMAJOR_WIDTH                             = 4;

	localparam TR_TRRAMIMPL_TRRAMVERMINOR_MASK                              = 32'hF0;
	localparam TR_TRRAMIMPL_TRRAMVERMINOR_SHIFT                             = 4;
	localparam TR_TRRAMIMPL_TRRAMVERMINOR_LOW                               = 4;
	localparam TR_TRRAMIMPL_TRRAMVERMINOR_HIGH                              = 7;
	localparam TR_TRRAMIMPL_TRRAMVERMINOR_WIDTH                             = 4;

	localparam TR_TRRAMIMPL_TRRAMCOMPTYPE_MASK                              = 32'hF00;
	localparam TR_TRRAMIMPL_TRRAMCOMPTYPE_SHIFT                             = 8;
	localparam TR_TRRAMIMPL_TRRAMCOMPTYPE_LOW                               = 8;
	localparam TR_TRRAMIMPL_TRRAMCOMPTYPE_HIGH                              = 11;
	localparam TR_TRRAMIMPL_TRRAMCOMPTYPE_WIDTH                             = 4;

	localparam TR_TRRAMIMPL_TRRAMHASSRAM_MASK                               = 32'h1000;
	localparam TR_TRRAMIMPL_TRRAMHASSRAM_SHIFT                              = 12;
	localparam TR_TRRAMIMPL_TRRAMHASSRAM_LOW                                = 12;
	localparam TR_TRRAMIMPL_TRRAMHASSRAM_HIGH                               = 12;
	localparam TR_TRRAMIMPL_TRRAMHASSRAM_WIDTH                              = 1;

	localparam TR_TRRAMIMPL_TRRAMHASSMEM_MASK                               = 32'h2000;
	localparam TR_TRRAMIMPL_TRRAMHASSMEM_SHIFT                              = 13;
	localparam TR_TRRAMIMPL_TRRAMHASSMEM_LOW                                = 13;
	localparam TR_TRRAMIMPL_TRRAMHASSMEM_HIGH                               = 13;
	localparam TR_TRRAMIMPL_TRRAMHASSMEM_WIDTH                              = 1;

	localparam TR_TRRAMIMPL_TRRAMVENDORFRAMELENGTH_MASK                     = 32'hF000000;
	localparam TR_TRRAMIMPL_TRRAMVENDORFRAMELENGTH_SHIFT                    = 24;
	localparam TR_TRRAMIMPL_TRRAMVENDORFRAMELENGTH_LOW                      = 24;
	localparam TR_TRRAMIMPL_TRRAMVENDORFRAMELENGTH_HIGH                     = 27;
	localparam TR_TRRAMIMPL_TRRAMVENDORFRAMELENGTH_WIDTH                    = 4;

	localparam TR_TRRAMSTARTLOW_RSVD10_MASK                                 = 32'h3;
	localparam TR_TRRAMSTARTLOW_RSVD10_SHIFT                                = 0;
	localparam TR_TRRAMSTARTLOW_RSVD10_LOW                                  = 0;
	localparam TR_TRRAMSTARTLOW_RSVD10_HIGH                                 = 1;
	localparam TR_TRRAMSTARTLOW_RSVD10_WIDTH                                = 2;

	localparam TR_TRRAMSTARTLOW_TRRAMSTARTLOW_MASK                          = 32'hFFFFFFFC;
	localparam TR_TRRAMSTARTLOW_TRRAMSTARTLOW_SHIFT                         = 2;
	localparam TR_TRRAMSTARTLOW_TRRAMSTARTLOW_LOW                           = 2;
	localparam TR_TRRAMSTARTLOW_TRRAMSTARTLOW_HIGH                          = 31;
	localparam TR_TRRAMSTARTLOW_TRRAMSTARTLOW_WIDTH                         = 30;

	localparam TR_TRRAMSTARTHIGH_TRRAMSTARTHIGH_MASK                        = 32'hFFFFFFFF;
	localparam TR_TRRAMSTARTHIGH_TRRAMSTARTHIGH_SHIFT                       = 0;
	localparam TR_TRRAMSTARTHIGH_TRRAMSTARTHIGH_LOW                         = 0;
	localparam TR_TRRAMSTARTHIGH_TRRAMSTARTHIGH_HIGH                        = 31;
	localparam TR_TRRAMSTARTHIGH_TRRAMSTARTHIGH_WIDTH                       = 32;

	localparam TR_TRRAMLIMITLOW_RSVD10_MASK                                 = 32'h3;
	localparam TR_TRRAMLIMITLOW_RSVD10_SHIFT                                = 0;
	localparam TR_TRRAMLIMITLOW_RSVD10_LOW                                  = 0;
	localparam TR_TRRAMLIMITLOW_RSVD10_HIGH                                 = 1;
	localparam TR_TRRAMLIMITLOW_RSVD10_WIDTH                                = 2;

	localparam TR_TRRAMLIMITLOW_TRRAMLIMITLOW_MASK                          = 32'hFFFFFFFC;
	localparam TR_TRRAMLIMITLOW_TRRAMLIMITLOW_SHIFT                         = 2;
	localparam TR_TRRAMLIMITLOW_TRRAMLIMITLOW_LOW                           = 2;
	localparam TR_TRRAMLIMITLOW_TRRAMLIMITLOW_HIGH                          = 31;
	localparam TR_TRRAMLIMITLOW_TRRAMLIMITLOW_WIDTH                         = 30;

	localparam TR_TRRAMLIMITHIGH_TRRAMLIMITHIGH_MASK                        = 32'hFFFFFFFF;
	localparam TR_TRRAMLIMITHIGH_TRRAMLIMITHIGH_SHIFT                       = 0;
	localparam TR_TRRAMLIMITHIGH_TRRAMLIMITHIGH_LOW                         = 0;
	localparam TR_TRRAMLIMITHIGH_TRRAMLIMITHIGH_HIGH                        = 31;
	localparam TR_TRRAMLIMITHIGH_TRRAMLIMITHIGH_WIDTH                       = 32;

	localparam TR_TRRAMWPLOW_TRRAMWRAP_MASK                                 = 32'h1;
	localparam TR_TRRAMWPLOW_TRRAMWRAP_SHIFT                                = 0;
	localparam TR_TRRAMWPLOW_TRRAMWRAP_LOW                                  = 0;
	localparam TR_TRRAMWPLOW_TRRAMWRAP_HIGH                                 = 0;
	localparam TR_TRRAMWPLOW_TRRAMWRAP_WIDTH                                = 1;

	localparam TR_TRRAMWPLOW_TRRAMWPLOW_MASK                                = 32'hFFFFFFFC;
	localparam TR_TRRAMWPLOW_TRRAMWPLOW_SHIFT                               = 2;
	localparam TR_TRRAMWPLOW_TRRAMWPLOW_LOW                                 = 2;
	localparam TR_TRRAMWPLOW_TRRAMWPLOW_HIGH                                = 31;
	localparam TR_TRRAMWPLOW_TRRAMWPLOW_WIDTH                               = 30;

	localparam TR_TRRAMWPHIGH_TRRAMWPHIGH_MASK                              = 32'hFFFFFFFF;
	localparam TR_TRRAMWPHIGH_TRRAMWPHIGH_SHIFT                             = 0;
	localparam TR_TRRAMWPHIGH_TRRAMWPHIGH_LOW                               = 0;
	localparam TR_TRRAMWPHIGH_TRRAMWPHIGH_HIGH                              = 31;
	localparam TR_TRRAMWPHIGH_TRRAMWPHIGH_WIDTH                             = 32;

	localparam TR_TRRAMRPLOW_RSVD10_MASK                                    = 32'h3;
	localparam TR_TRRAMRPLOW_RSVD10_SHIFT                                   = 0;
	localparam TR_TRRAMRPLOW_RSVD10_LOW                                     = 0;
	localparam TR_TRRAMRPLOW_RSVD10_HIGH                                    = 1;
	localparam TR_TRRAMRPLOW_RSVD10_WIDTH                                   = 2;

	localparam TR_TRRAMRPLOW_TRRAMRPLOW_MASK                                = 32'hFFFFFFFC;
	localparam TR_TRRAMRPLOW_TRRAMRPLOW_SHIFT                               = 2;
	localparam TR_TRRAMRPLOW_TRRAMRPLOW_LOW                                 = 2;
	localparam TR_TRRAMRPLOW_TRRAMRPLOW_HIGH                                = 31;
	localparam TR_TRRAMRPLOW_TRRAMRPLOW_WIDTH                               = 30;

	localparam TR_TRRAMRPHIGH_TRRAMRPHIGH_MASK                              = 32'hFFFFFFFF;
	localparam TR_TRRAMRPHIGH_TRRAMRPHIGH_SHIFT                             = 0;
	localparam TR_TRRAMRPHIGH_TRRAMRPHIGH_LOW                               = 0;
	localparam TR_TRRAMRPHIGH_TRRAMRPHIGH_HIGH                              = 31;
	localparam TR_TRRAMRPHIGH_TRRAMRPHIGH_WIDTH                             = 32;

	localparam TR_TRRAMDATA_TRRAMDATA_MASK                                  = 32'hFFFFFFFF;
	localparam TR_TRRAMDATA_TRRAMDATA_SHIFT                                 = 0;
	localparam TR_TRRAMDATA_TRRAMDATA_LOW                                   = 0;
	localparam TR_TRRAMDATA_TRRAMDATA_HIGH                                  = 31;
	localparam TR_TRRAMDATA_TRRAMDATA_WIDTH                                 = 32;

	localparam TR_TRCUSTOMRAMSMEMLIMITLOW_RSVD10_MASK                       = 32'h3;
	localparam TR_TRCUSTOMRAMSMEMLIMITLOW_RSVD10_SHIFT                      = 0;
	localparam TR_TRCUSTOMRAMSMEMLIMITLOW_RSVD10_LOW                        = 0;
	localparam TR_TRCUSTOMRAMSMEMLIMITLOW_RSVD10_HIGH                       = 1;
	localparam TR_TRCUSTOMRAMSMEMLIMITLOW_RSVD10_WIDTH                      = 2;

	localparam TR_TRCUSTOMRAMSMEMLIMITLOW_TRCUSTOMRAMSMEMLIMITLOW_MASK      = 32'hFFFFFFFC;
	localparam TR_TRCUSTOMRAMSMEMLIMITLOW_TRCUSTOMRAMSMEMLIMITLOW_SHIFT     = 2;
	localparam TR_TRCUSTOMRAMSMEMLIMITLOW_TRCUSTOMRAMSMEMLIMITLOW_LOW       = 2;
	localparam TR_TRCUSTOMRAMSMEMLIMITLOW_TRCUSTOMRAMSMEMLIMITLOW_HIGH      = 31;
	localparam TR_TRCUSTOMRAMSMEMLIMITLOW_TRCUSTOMRAMSMEMLIMITLOW_WIDTH     = 30;

	localparam TR_TRDSTRAMCONTROL_TRDSTRAMACTIVE_MASK                       = 32'h1;
	localparam TR_TRDSTRAMCONTROL_TRDSTRAMACTIVE_SHIFT                      = 0;
	localparam TR_TRDSTRAMCONTROL_TRDSTRAMACTIVE_LOW                        = 0;
	localparam TR_TRDSTRAMCONTROL_TRDSTRAMACTIVE_HIGH                       = 0;
	localparam TR_TRDSTRAMCONTROL_TRDSTRAMACTIVE_WIDTH                      = 1;

	localparam TR_TRDSTRAMCONTROL_TRDSTRAMENABLE_MASK                       = 32'h2;
	localparam TR_TRDSTRAMCONTROL_TRDSTRAMENABLE_SHIFT                      = 1;
	localparam TR_TRDSTRAMCONTROL_TRDSTRAMENABLE_LOW                        = 1;
	localparam TR_TRDSTRAMCONTROL_TRDSTRAMENABLE_HIGH                       = 1;
	localparam TR_TRDSTRAMCONTROL_TRDSTRAMENABLE_WIDTH                      = 1;

	localparam TR_TRDSTRAMCONTROL_TRDSTRAMEMPTY_MASK                        = 32'h8;
	localparam TR_TRDSTRAMCONTROL_TRDSTRAMEMPTY_SHIFT                       = 3;
	localparam TR_TRDSTRAMCONTROL_TRDSTRAMEMPTY_LOW                         = 3;
	localparam TR_TRDSTRAMCONTROL_TRDSTRAMEMPTY_HIGH                        = 3;
	localparam TR_TRDSTRAMCONTROL_TRDSTRAMEMPTY_WIDTH                       = 1;

	localparam TR_TRDSTRAMCONTROL_TRDSTRAMMODE_MASK                         = 32'h10;
	localparam TR_TRDSTRAMCONTROL_TRDSTRAMMODE_SHIFT                        = 4;
	localparam TR_TRDSTRAMCONTROL_TRDSTRAMMODE_LOW                          = 4;
	localparam TR_TRDSTRAMCONTROL_TRDSTRAMMODE_HIGH                         = 4;
	localparam TR_TRDSTRAMCONTROL_TRDSTRAMMODE_WIDTH                        = 1;

	localparam TR_TRDSTRAMCONTROL_TRDSTRAMSTOPONWRAP_MASK                   = 32'h100;
	localparam TR_TRDSTRAMCONTROL_TRDSTRAMSTOPONWRAP_SHIFT                  = 8;
	localparam TR_TRDSTRAMCONTROL_TRDSTRAMSTOPONWRAP_LOW                    = 8;
	localparam TR_TRDSTRAMCONTROL_TRDSTRAMSTOPONWRAP_HIGH                   = 8;
	localparam TR_TRDSTRAMCONTROL_TRDSTRAMSTOPONWRAP_WIDTH                  = 1;

	localparam TR_TRDSTRAMIMPL_TRDSTRAMVERMAJOR_MASK                        = 32'hF;
	localparam TR_TRDSTRAMIMPL_TRDSTRAMVERMAJOR_SHIFT                       = 0;
	localparam TR_TRDSTRAMIMPL_TRDSTRAMVERMAJOR_LOW                         = 0;
	localparam TR_TRDSTRAMIMPL_TRDSTRAMVERMAJOR_HIGH                        = 3;
	localparam TR_TRDSTRAMIMPL_TRDSTRAMVERMAJOR_WIDTH                       = 4;

	localparam TR_TRDSTRAMIMPL_TRDSTRAMVERMINOR_MASK                        = 32'hF0;
	localparam TR_TRDSTRAMIMPL_TRDSTRAMVERMINOR_SHIFT                       = 4;
	localparam TR_TRDSTRAMIMPL_TRDSTRAMVERMINOR_LOW                         = 4;
	localparam TR_TRDSTRAMIMPL_TRDSTRAMVERMINOR_HIGH                        = 7;
	localparam TR_TRDSTRAMIMPL_TRDSTRAMVERMINOR_WIDTH                       = 4;

	localparam TR_TRDSTRAMIMPL_TRDSTRAMCOMPTYPE_MASK                        = 32'hF00;
	localparam TR_TRDSTRAMIMPL_TRDSTRAMCOMPTYPE_SHIFT                       = 8;
	localparam TR_TRDSTRAMIMPL_TRDSTRAMCOMPTYPE_LOW                         = 8;
	localparam TR_TRDSTRAMIMPL_TRDSTRAMCOMPTYPE_HIGH                        = 11;
	localparam TR_TRDSTRAMIMPL_TRDSTRAMCOMPTYPE_WIDTH                       = 4;

	localparam TR_TRDSTRAMIMPL_TRDSTRAMHASSRAM_MASK                         = 32'h1000;
	localparam TR_TRDSTRAMIMPL_TRDSTRAMHASSRAM_SHIFT                        = 12;
	localparam TR_TRDSTRAMIMPL_TRDSTRAMHASSRAM_LOW                          = 12;
	localparam TR_TRDSTRAMIMPL_TRDSTRAMHASSRAM_HIGH                         = 12;
	localparam TR_TRDSTRAMIMPL_TRDSTRAMHASSRAM_WIDTH                        = 1;

	localparam TR_TRDSTRAMIMPL_TRDSTRAMHASSMEM_MASK                         = 32'h2000;
	localparam TR_TRDSTRAMIMPL_TRDSTRAMHASSMEM_SHIFT                        = 13;
	localparam TR_TRDSTRAMIMPL_TRDSTRAMHASSMEM_LOW                          = 13;
	localparam TR_TRDSTRAMIMPL_TRDSTRAMHASSMEM_HIGH                         = 13;
	localparam TR_TRDSTRAMIMPL_TRDSTRAMHASSMEM_WIDTH                        = 1;

	localparam TR_TRDSTRAMIMPL_TRDSTRAMVENDORFRAMELENGTH_MASK               = 32'hF000000;
	localparam TR_TRDSTRAMIMPL_TRDSTRAMVENDORFRAMELENGTH_SHIFT              = 24;
	localparam TR_TRDSTRAMIMPL_TRDSTRAMVENDORFRAMELENGTH_LOW                = 24;
	localparam TR_TRDSTRAMIMPL_TRDSTRAMVENDORFRAMELENGTH_HIGH               = 27;
	localparam TR_TRDSTRAMIMPL_TRDSTRAMVENDORFRAMELENGTH_WIDTH              = 4;

	localparam TR_TRDSTRAMSTARTLOW_RSVD10_MASK                              = 32'h3;
	localparam TR_TRDSTRAMSTARTLOW_RSVD10_SHIFT                             = 0;
	localparam TR_TRDSTRAMSTARTLOW_RSVD10_LOW                               = 0;
	localparam TR_TRDSTRAMSTARTLOW_RSVD10_HIGH                              = 1;
	localparam TR_TRDSTRAMSTARTLOW_RSVD10_WIDTH                             = 2;

	localparam TR_TRDSTRAMSTARTLOW_TRDSTRAMSTARTLOW_MASK                    = 32'hFFFFFFFC;
	localparam TR_TRDSTRAMSTARTLOW_TRDSTRAMSTARTLOW_SHIFT                   = 2;
	localparam TR_TRDSTRAMSTARTLOW_TRDSTRAMSTARTLOW_LOW                     = 2;
	localparam TR_TRDSTRAMSTARTLOW_TRDSTRAMSTARTLOW_HIGH                    = 31;
	localparam TR_TRDSTRAMSTARTLOW_TRDSTRAMSTARTLOW_WIDTH                   = 30;

	localparam TR_TRDSTRAMSTARTHIGH_TRDSTRAMSTARTHIGH_MASK                  = 32'hFFFFFFFF;
	localparam TR_TRDSTRAMSTARTHIGH_TRDSTRAMSTARTHIGH_SHIFT                 = 0;
	localparam TR_TRDSTRAMSTARTHIGH_TRDSTRAMSTARTHIGH_LOW                   = 0;
	localparam TR_TRDSTRAMSTARTHIGH_TRDSTRAMSTARTHIGH_HIGH                  = 31;
	localparam TR_TRDSTRAMSTARTHIGH_TRDSTRAMSTARTHIGH_WIDTH                 = 32;

	localparam TR_TRDSTRAMLIMITLOW_RSVD10_MASK                              = 32'h3;
	localparam TR_TRDSTRAMLIMITLOW_RSVD10_SHIFT                             = 0;
	localparam TR_TRDSTRAMLIMITLOW_RSVD10_LOW                               = 0;
	localparam TR_TRDSTRAMLIMITLOW_RSVD10_HIGH                              = 1;
	localparam TR_TRDSTRAMLIMITLOW_RSVD10_WIDTH                             = 2;

	localparam TR_TRDSTRAMLIMITLOW_TRDSTRAMLIMITLOW_MASK                    = 32'hFFFFFFFC;
	localparam TR_TRDSTRAMLIMITLOW_TRDSTRAMLIMITLOW_SHIFT                   = 2;
	localparam TR_TRDSTRAMLIMITLOW_TRDSTRAMLIMITLOW_LOW                     = 2;
	localparam TR_TRDSTRAMLIMITLOW_TRDSTRAMLIMITLOW_HIGH                    = 31;
	localparam TR_TRDSTRAMLIMITLOW_TRDSTRAMLIMITLOW_WIDTH                   = 30;

	localparam TR_TRDSTRAMLIMITHIGH_TRDSTRAMLIMITHIGH_MASK                  = 32'hFFFFFFFF;
	localparam TR_TRDSTRAMLIMITHIGH_TRDSTRAMLIMITHIGH_SHIFT                 = 0;
	localparam TR_TRDSTRAMLIMITHIGH_TRDSTRAMLIMITHIGH_LOW                   = 0;
	localparam TR_TRDSTRAMLIMITHIGH_TRDSTRAMLIMITHIGH_HIGH                  = 31;
	localparam TR_TRDSTRAMLIMITHIGH_TRDSTRAMLIMITHIGH_WIDTH                 = 32;

	localparam TR_TRDSTRAMWPLOW_TRDSTRAMWRAP_MASK                           = 32'h1;
	localparam TR_TRDSTRAMWPLOW_TRDSTRAMWRAP_SHIFT                          = 0;
	localparam TR_TRDSTRAMWPLOW_TRDSTRAMWRAP_LOW                            = 0;
	localparam TR_TRDSTRAMWPLOW_TRDSTRAMWRAP_HIGH                           = 0;
	localparam TR_TRDSTRAMWPLOW_TRDSTRAMWRAP_WIDTH                          = 1;

	localparam TR_TRDSTRAMWPLOW_TRDSTRAMWPLOW_MASK                          = 32'hFFFFFFFC;
	localparam TR_TRDSTRAMWPLOW_TRDSTRAMWPLOW_SHIFT                         = 2;
	localparam TR_TRDSTRAMWPLOW_TRDSTRAMWPLOW_LOW                           = 2;
	localparam TR_TRDSTRAMWPLOW_TRDSTRAMWPLOW_HIGH                          = 31;
	localparam TR_TRDSTRAMWPLOW_TRDSTRAMWPLOW_WIDTH                         = 30;

	localparam TR_TRDSTRAMWPHIGH_TRDSTRAMWPHIGH_MASK                        = 32'hFFFFFFFF;
	localparam TR_TRDSTRAMWPHIGH_TRDSTRAMWPHIGH_SHIFT                       = 0;
	localparam TR_TRDSTRAMWPHIGH_TRDSTRAMWPHIGH_LOW                         = 0;
	localparam TR_TRDSTRAMWPHIGH_TRDSTRAMWPHIGH_HIGH                        = 31;
	localparam TR_TRDSTRAMWPHIGH_TRDSTRAMWPHIGH_WIDTH                       = 32;

	localparam TR_TRDSTRAMRPLOW_RSVD10_MASK                                 = 32'h3;
	localparam TR_TRDSTRAMRPLOW_RSVD10_SHIFT                                = 0;
	localparam TR_TRDSTRAMRPLOW_RSVD10_LOW                                  = 0;
	localparam TR_TRDSTRAMRPLOW_RSVD10_HIGH                                 = 1;
	localparam TR_TRDSTRAMRPLOW_RSVD10_WIDTH                                = 2;

	localparam TR_TRDSTRAMRPLOW_TRDSTRAMRPLOW_MASK                          = 32'hFFFFFFFC;
	localparam TR_TRDSTRAMRPLOW_TRDSTRAMRPLOW_SHIFT                         = 2;
	localparam TR_TRDSTRAMRPLOW_TRDSTRAMRPLOW_LOW                           = 2;
	localparam TR_TRDSTRAMRPLOW_TRDSTRAMRPLOW_HIGH                          = 31;
	localparam TR_TRDSTRAMRPLOW_TRDSTRAMRPLOW_WIDTH                         = 30;

	localparam TR_TRDSTRAMRPHIGH_TRDSTRAMRPHIGH_MASK                        = 32'hFFFFFFFF;
	localparam TR_TRDSTRAMRPHIGH_TRDSTRAMRPHIGH_SHIFT                       = 0;
	localparam TR_TRDSTRAMRPHIGH_TRDSTRAMRPHIGH_LOW                         = 0;
	localparam TR_TRDSTRAMRPHIGH_TRDSTRAMRPHIGH_HIGH                        = 31;
	localparam TR_TRDSTRAMRPHIGH_TRDSTRAMRPHIGH_WIDTH                       = 32;

	localparam TR_TRDSTRAMDATA_TRDSTRAMDATA_MASK                            = 32'hFFFFFFFF;
	localparam TR_TRDSTRAMDATA_TRDSTRAMDATA_SHIFT                           = 0;
	localparam TR_TRDSTRAMDATA_TRDSTRAMDATA_LOW                             = 0;
	localparam TR_TRDSTRAMDATA_TRDSTRAMDATA_HIGH                            = 31;
	localparam TR_TRDSTRAMDATA_TRDSTRAMDATA_WIDTH                           = 32;

	localparam TR_TRCLUSTERFUSECFGLOW_SCHARVESTSTRAP_MASK                   = 32'hFF;
	localparam TR_TRCLUSTERFUSECFGLOW_SCHARVESTSTRAP_SHIFT                  = 0;
	localparam TR_TRCLUSTERFUSECFGLOW_SCHARVESTSTRAP_LOW                    = 0;
	localparam TR_TRCLUSTERFUSECFGLOW_SCHARVESTSTRAP_HIGH                   = 7;
	localparam TR_TRCLUSTERFUSECFGLOW_SCHARVESTSTRAP_WIDTH                  = 8;

	localparam TR_TRCLUSTERFUSECFGLOW_RSVD98_MASK                           = 32'h300;
	localparam TR_TRCLUSTERFUSECFGLOW_RSVD98_SHIFT                          = 8;
	localparam TR_TRCLUSTERFUSECFGLOW_RSVD98_LOW                            = 8;
	localparam TR_TRCLUSTERFUSECFGLOW_RSVD98_HIGH                           = 9;
	localparam TR_TRCLUSTERFUSECFGLOW_RSVD98_WIDTH                          = 2;

	localparam TR_TRCLUSTERFUSECFGLOW_EXPORTRESTRICTIONENABLED_MASK         = 32'h400;
	localparam TR_TRCLUSTERFUSECFGLOW_EXPORTRESTRICTIONENABLED_SHIFT        = 10;
	localparam TR_TRCLUSTERFUSECFGLOW_EXPORTRESTRICTIONENABLED_LOW          = 10;
	localparam TR_TRCLUSTERFUSECFGLOW_EXPORTRESTRICTIONENABLED_HIGH         = 10;
	localparam TR_TRCLUSTERFUSECFGLOW_EXPORTRESTRICTIONENABLED_WIDTH        = 1;

	localparam TR_TRCLUSTERFUSECFGLOW_IOCOHERENCYDISABLE_MASK               = 32'h800;
	localparam TR_TRCLUSTERFUSECFGLOW_IOCOHERENCYDISABLE_SHIFT              = 11;
	localparam TR_TRCLUSTERFUSECFGLOW_IOCOHERENCYDISABLE_LOW                = 11;
	localparam TR_TRCLUSTERFUSECFGLOW_IOCOHERENCYDISABLE_HIGH               = 11;
	localparam TR_TRCLUSTERFUSECFGLOW_IOCOHERENCYDISABLE_WIDTH              = 1;

	localparam TR_TRCLUSTERFUSECFGLOW_RSVD1512_MASK                         = 32'hF000;
	localparam TR_TRCLUSTERFUSECFGLOW_RSVD1512_SHIFT                        = 12;
	localparam TR_TRCLUSTERFUSECFGLOW_RSVD1512_LOW                          = 12;
	localparam TR_TRCLUSTERFUSECFGLOW_RSVD1512_HIGH                         = 15;
	localparam TR_TRCLUSTERFUSECFGLOW_RSVD1512_WIDTH                        = 4;

	localparam TR_TRCLUSTERFUSECFGLOW_CORE0ENABLE_MASK                      = 32'h10000;
	localparam TR_TRCLUSTERFUSECFGLOW_CORE0ENABLE_SHIFT                     = 16;
	localparam TR_TRCLUSTERFUSECFGLOW_CORE0ENABLE_LOW                       = 16;
	localparam TR_TRCLUSTERFUSECFGLOW_CORE0ENABLE_HIGH                      = 16;
	localparam TR_TRCLUSTERFUSECFGLOW_CORE0ENABLE_WIDTH                     = 1;

	localparam TR_TRCLUSTERFUSECFGLOW_CORE0VID_MASK                         = 32'hE0000;
	localparam TR_TRCLUSTERFUSECFGLOW_CORE0VID_SHIFT                        = 17;
	localparam TR_TRCLUSTERFUSECFGLOW_CORE0VID_LOW                          = 17;
	localparam TR_TRCLUSTERFUSECFGLOW_CORE0VID_HIGH                         = 19;
	localparam TR_TRCLUSTERFUSECFGLOW_CORE0VID_WIDTH                        = 3;

	localparam TR_TRCLUSTERFUSECFGLOW_CORE1ENABLE_MASK                      = 32'h100000;
	localparam TR_TRCLUSTERFUSECFGLOW_CORE1ENABLE_SHIFT                     = 20;
	localparam TR_TRCLUSTERFUSECFGLOW_CORE1ENABLE_LOW                       = 20;
	localparam TR_TRCLUSTERFUSECFGLOW_CORE1ENABLE_HIGH                      = 20;
	localparam TR_TRCLUSTERFUSECFGLOW_CORE1ENABLE_WIDTH                     = 1;

	localparam TR_TRCLUSTERFUSECFGLOW_CORE1VID_MASK                         = 32'hE00000;
	localparam TR_TRCLUSTERFUSECFGLOW_CORE1VID_SHIFT                        = 21;
	localparam TR_TRCLUSTERFUSECFGLOW_CORE1VID_LOW                          = 21;
	localparam TR_TRCLUSTERFUSECFGLOW_CORE1VID_HIGH                         = 23;
	localparam TR_TRCLUSTERFUSECFGLOW_CORE1VID_WIDTH                        = 3;

	localparam TR_TRCLUSTERFUSECFGLOW_CORE2ENABLE_MASK                      = 32'h1000000;
	localparam TR_TRCLUSTERFUSECFGLOW_CORE2ENABLE_SHIFT                     = 24;
	localparam TR_TRCLUSTERFUSECFGLOW_CORE2ENABLE_LOW                       = 24;
	localparam TR_TRCLUSTERFUSECFGLOW_CORE2ENABLE_HIGH                      = 24;
	localparam TR_TRCLUSTERFUSECFGLOW_CORE2ENABLE_WIDTH                     = 1;

	localparam TR_TRCLUSTERFUSECFGLOW_CORE2VID_MASK                         = 32'hE000000;
	localparam TR_TRCLUSTERFUSECFGLOW_CORE2VID_SHIFT                        = 25;
	localparam TR_TRCLUSTERFUSECFGLOW_CORE2VID_LOW                          = 25;
	localparam TR_TRCLUSTERFUSECFGLOW_CORE2VID_HIGH                         = 27;
	localparam TR_TRCLUSTERFUSECFGLOW_CORE2VID_WIDTH                        = 3;

	localparam TR_TRCLUSTERFUSECFGLOW_CORE3ENABLE_MASK                      = 32'h10000000;
	localparam TR_TRCLUSTERFUSECFGLOW_CORE3ENABLE_SHIFT                     = 28;
	localparam TR_TRCLUSTERFUSECFGLOW_CORE3ENABLE_LOW                       = 28;
	localparam TR_TRCLUSTERFUSECFGLOW_CORE3ENABLE_HIGH                      = 28;
	localparam TR_TRCLUSTERFUSECFGLOW_CORE3ENABLE_WIDTH                     = 1;

	localparam TR_TRCLUSTERFUSECFGLOW_CORE3VID_MASK                         = 32'hE0000000;
	localparam TR_TRCLUSTERFUSECFGLOW_CORE3VID_SHIFT                        = 29;
	localparam TR_TRCLUSTERFUSECFGLOW_CORE3VID_LOW                          = 29;
	localparam TR_TRCLUSTERFUSECFGLOW_CORE3VID_HIGH                         = 31;
	localparam TR_TRCLUSTERFUSECFGLOW_CORE3VID_WIDTH                        = 3;

	localparam TR_TRCLUSTERFUSECFGHI_CORE4ENABLE_MASK                       = 32'h1;
	localparam TR_TRCLUSTERFUSECFGHI_CORE4ENABLE_SHIFT                      = 0;
	localparam TR_TRCLUSTERFUSECFGHI_CORE4ENABLE_LOW                        = 0;
	localparam TR_TRCLUSTERFUSECFGHI_CORE4ENABLE_HIGH                       = 0;
	localparam TR_TRCLUSTERFUSECFGHI_CORE4ENABLE_WIDTH                      = 1;

	localparam TR_TRCLUSTERFUSECFGHI_CORE4VID_MASK                          = 32'hE;
	localparam TR_TRCLUSTERFUSECFGHI_CORE4VID_SHIFT                         = 1;
	localparam TR_TRCLUSTERFUSECFGHI_CORE4VID_LOW                           = 1;
	localparam TR_TRCLUSTERFUSECFGHI_CORE4VID_HIGH                          = 3;
	localparam TR_TRCLUSTERFUSECFGHI_CORE4VID_WIDTH                         = 3;

	localparam TR_TRCLUSTERFUSECFGHI_CORE5ENABLE_MASK                       = 32'h10;
	localparam TR_TRCLUSTERFUSECFGHI_CORE5ENABLE_SHIFT                      = 4;
	localparam TR_TRCLUSTERFUSECFGHI_CORE5ENABLE_LOW                        = 4;
	localparam TR_TRCLUSTERFUSECFGHI_CORE5ENABLE_HIGH                       = 4;
	localparam TR_TRCLUSTERFUSECFGHI_CORE5ENABLE_WIDTH                      = 1;

	localparam TR_TRCLUSTERFUSECFGHI_CORE5VID_MASK                          = 32'hE0;
	localparam TR_TRCLUSTERFUSECFGHI_CORE5VID_SHIFT                         = 5;
	localparam TR_TRCLUSTERFUSECFGHI_CORE5VID_LOW                           = 5;
	localparam TR_TRCLUSTERFUSECFGHI_CORE5VID_HIGH                          = 7;
	localparam TR_TRCLUSTERFUSECFGHI_CORE5VID_WIDTH                         = 3;

	localparam TR_TRCLUSTERFUSECFGHI_CORE6ENABLE_MASK                       = 32'h100;
	localparam TR_TRCLUSTERFUSECFGHI_CORE6ENABLE_SHIFT                      = 8;
	localparam TR_TRCLUSTERFUSECFGHI_CORE6ENABLE_LOW                        = 8;
	localparam TR_TRCLUSTERFUSECFGHI_CORE6ENABLE_HIGH                       = 8;
	localparam TR_TRCLUSTERFUSECFGHI_CORE6ENABLE_WIDTH                      = 1;

	localparam TR_TRCLUSTERFUSECFGHI_CORE6VID_MASK                          = 32'hE00;
	localparam TR_TRCLUSTERFUSECFGHI_CORE6VID_SHIFT                         = 9;
	localparam TR_TRCLUSTERFUSECFGHI_CORE6VID_LOW                           = 9;
	localparam TR_TRCLUSTERFUSECFGHI_CORE6VID_HIGH                          = 11;
	localparam TR_TRCLUSTERFUSECFGHI_CORE6VID_WIDTH                         = 3;

	localparam TR_TRCLUSTERFUSECFGHI_CORE7ENABLE_MASK                       = 32'h1000;
	localparam TR_TRCLUSTERFUSECFGHI_CORE7ENABLE_SHIFT                      = 12;
	localparam TR_TRCLUSTERFUSECFGHI_CORE7ENABLE_LOW                        = 12;
	localparam TR_TRCLUSTERFUSECFGHI_CORE7ENABLE_HIGH                       = 12;
	localparam TR_TRCLUSTERFUSECFGHI_CORE7ENABLE_WIDTH                      = 1;

	localparam TR_TRCLUSTERFUSECFGHI_CORE7VID_MASK                          = 32'hE000;
	localparam TR_TRCLUSTERFUSECFGHI_CORE7VID_SHIFT                         = 13;
	localparam TR_TRCLUSTERFUSECFGHI_CORE7VID_LOW                           = 13;
	localparam TR_TRCLUSTERFUSECFGHI_CORE7VID_HIGH                          = 15;
	localparam TR_TRCLUSTERFUSECFGHI_CORE7VID_WIDTH                         = 3;

	localparam TR_TRCLUSTERFUSECFGHI_DEBUGENABLE_MASK                       = 32'h30000;
	localparam TR_TRCLUSTERFUSECFGHI_DEBUGENABLE_SHIFT                      = 16;
	localparam TR_TRCLUSTERFUSECFGHI_DEBUGENABLE_LOW                        = 16;
	localparam TR_TRCLUSTERFUSECFGHI_DEBUGENABLE_HIGH                       = 17;
	localparam TR_TRCLUSTERFUSECFGHI_DEBUGENABLE_WIDTH                      = 2;

	localparam TR_TRCLUSTERFUSECFGHI_CLAENABLE_MASK                         = 32'h40000;
	localparam TR_TRCLUSTERFUSECFGHI_CLAENABLE_SHIFT                        = 18;
	localparam TR_TRCLUSTERFUSECFGHI_CLAENABLE_LOW                          = 18;
	localparam TR_TRCLUSTERFUSECFGHI_CLAENABLE_HIGH                         = 18;
	localparam TR_TRCLUSTERFUSECFGHI_CLAENABLE_WIDTH                        = 1;

	localparam TR_TRCLUSTERFUSECFGHI_TRACEENABLE_MASK                       = 32'h80000;
	localparam TR_TRCLUSTERFUSECFGHI_TRACEENABLE_SHIFT                      = 19;
	localparam TR_TRCLUSTERFUSECFGHI_TRACEENABLE_LOW                        = 19;
	localparam TR_TRCLUSTERFUSECFGHI_TRACEENABLE_HIGH                       = 19;
	localparam TR_TRCLUSTERFUSECFGHI_TRACEENABLE_WIDTH                      = 1;

	localparam TR_TRCLUSTERFUSECFGHI_DSTENABLE_MASK                         = 32'h100000;
	localparam TR_TRCLUSTERFUSECFGHI_DSTENABLE_SHIFT                        = 20;
	localparam TR_TRCLUSTERFUSECFGHI_DSTENABLE_LOW                          = 20;
	localparam TR_TRCLUSTERFUSECFGHI_DSTENABLE_HIGH                         = 20;
	localparam TR_TRCLUSTERFUSECFGHI_DSTENABLE_WIDTH                        = 1;

	localparam TR_TRCLUSTERFUSECFGHI_JTAG2UARCHENABLE_MASK                  = 32'h200000;
	localparam TR_TRCLUSTERFUSECFGHI_JTAG2UARCHENABLE_SHIFT                 = 21;
	localparam TR_TRCLUSTERFUSECFGHI_JTAG2UARCHENABLE_LOW                   = 21;
	localparam TR_TRCLUSTERFUSECFGHI_JTAG2UARCHENABLE_HIGH                  = 21;
	localparam TR_TRCLUSTERFUSECFGHI_JTAG2UARCHENABLE_WIDTH                 = 1;

	localparam TR_TRCLUSTERFUSECFGHI_RSVD3022_MASK                          = 32'h7FC00000;
	localparam TR_TRCLUSTERFUSECFGHI_RSVD3022_SHIFT                         = 22;
	localparam TR_TRCLUSTERFUSECFGHI_RSVD3022_LOW                           = 22;
	localparam TR_TRCLUSTERFUSECFGHI_RSVD3022_HIGH                          = 30;
	localparam TR_TRCLUSTERFUSECFGHI_RSVD3022_WIDTH                         = 9;

	localparam TR_TRCLUSTERFUSECFGHI_LOCK_MASK                              = 32'h80000000;
	localparam TR_TRCLUSTERFUSECFGHI_LOCK_SHIFT                             = 31;
	localparam TR_TRCLUSTERFUSECFGHI_LOCK_LOW                               = 31;
	localparam TR_TRCLUSTERFUSECFGHI_LOCK_HIGH                              = 31;
	localparam TR_TRCLUSTERFUSECFGHI_LOCK_WIDTH                             = 1;

	localparam TR_TRSCRATCHLO_DATA_MASK                                     = 32'hFFFFFFFF;
	localparam TR_TRSCRATCHLO_DATA_SHIFT                                    = 0;
	localparam TR_TRSCRATCHLO_DATA_LOW                                      = 0;
	localparam TR_TRSCRATCHLO_DATA_HIGH                                     = 31;
	localparam TR_TRSCRATCHLO_DATA_WIDTH                                    = 32;

	localparam TR_TRSCRATCHHI_DATA_MASK                                     = 32'hFFFFFFFF;
	localparam TR_TRSCRATCHHI_DATA_SHIFT                                    = 0;
	localparam TR_TRSCRATCHHI_DATA_LOW                                      = 0;
	localparam TR_TRSCRATCHHI_DATA_HIGH                                     = 31;
	localparam TR_TRSCRATCHHI_DATA_WIDTH                                    = 32;

	localparam TR_TRSCRATCHPADLO_DATA_MASK                                  = 32'hFFFFFFFF;
	localparam TR_TRSCRATCHPADLO_DATA_SHIFT                                 = 0;
	localparam TR_TRSCRATCHPADLO_DATA_LOW                                   = 0;
	localparam TR_TRSCRATCHPADLO_DATA_HIGH                                  = 31;
	localparam TR_TRSCRATCHPADLO_DATA_WIDTH                                 = 32;

	localparam TR_TRSCRATCHPADHI_DATA_MASK                                  = 32'hFFFFFFFF;
	localparam TR_TRSCRATCHPADHI_DATA_SHIFT                                 = 0;
	localparam TR_TRSCRATCHPADHI_DATA_LOW                                   = 0;
	localparam TR_TRSCRATCHPADHI_DATA_HIGH                                  = 31;
	localparam TR_TRSCRATCHPADHI_DATA_WIDTH                                 = 32;

	localparam TR_NUM_REGISTERS                                             = 32;


	typedef struct packed {
		logic               TrCsrTrfunnelcontrolHit;
		logic               TrCsrTrfunnelimplHit;
		logic               TrCsrTrfunneldisinputHit;
		logic               TrCsrTrramcontrolHit;
		logic               TrCsrTrramimplHit;
		logic               TrCsrTrramstartlowHit;
		logic               TrCsrTrramstarthighHit;
		logic               TrCsrTrramlimitlowHit;
		logic               TrCsrTrramlimithighHit;
		logic               TrCsrTrramwplowHit;
		logic               TrCsrTrramwphighHit;
		logic               TrCsrTrramrplowHit;
		logic               TrCsrTrramrphighHit;
		logic               TrCsrTrramdataHit;
		logic               TrCsrTrcustomramsmemlimitlowHit;
		logic               TrCsrTrdstramcontrolHit;
		logic               TrCsrTrdstramimplHit;
		logic               TrCsrTrdstramstartlowHit;
		logic               TrCsrTrdstramstarthighHit;
		logic               TrCsrTrdstramlimitlowHit;
		logic               TrCsrTrdstramlimithighHit;
		logic               TrCsrTrdstramwplowHit;
		logic               TrCsrTrdstramwphighHit;
		logic               TrCsrTrdstramrplowHit;
		logic               TrCsrTrdstramrphighHit;
		logic               TrCsrTrdstramdataHit;
		logic               TrCsrTrclusterfusecfglowHit;
		logic               TrCsrTrclusterfusecfghiHit;
		logic               TrCsrTrscratchloHit;
		logic               TrCsrTrscratchhiHit;
		logic               TrCsrTrscratchpadloHit;
		logic               TrCsrTrscratchpadhiHit;
	} TrCsrHit_s;






	typedef struct packed {
		logic    [0:0]        Trfunnelempty ;
		logic    [0:0]        Trfunnelenable ;
		logic    [0:0]        Trfunnelactive ;
	} TrTrfunnelcontrolCsr_s;



	typedef struct packed {
		logic    [3:0]        Trfunnelcomptype ;
		logic    [3:0]        Trfunnelverminor ;
		logic    [3:0]        Trfunnelvermajor ;
	} TrTrfunnelimplCsr_s;



	typedef struct packed {
		logic   [15:0]        Trfunneldisinput ;
	} TrTrfunneldisinputCsr_s;



	typedef struct packed {
		logic    [0:0]        Trramstoponwrap ;
		logic    [0:0]        Trrammode ;
		logic    [0:0]        Trramempty ;
		logic    [0:0]        Trramenable ;
		logic    [0:0]        Trramactive ;
	} TrTrramcontrolCsr_s;



	typedef struct packed {
		logic    [3:0]        Trramvendorframelength ;
		logic    [0:0]        Trramhassmem ;
		logic    [0:0]        Trramhassram ;
		logic    [3:0]        Trramcomptype ;
		logic    [3:0]        Trramverminor ;
		logic    [3:0]        Trramvermajor ;
	} TrTrramimplCsr_s;



	typedef struct packed {
		logic   [29:0]        Trramstartlow ;
		logic    [1:0]        Rsvd10 ;
	} TrTrramstartlowCsr_s;



	typedef struct packed {
		logic   [31:0]        Trramstarthigh ;
	} TrTrramstarthighCsr_s;



	typedef struct packed {
		logic   [29:0]        Trramlimitlow ;
		logic    [1:0]        Rsvd10 ;
	} TrTrramlimitlowCsr_s;



	typedef struct packed {
		logic   [31:0]        Trramlimithigh ;
	} TrTrramlimithighCsr_s;



	typedef struct packed {
		logic   [29:0]        Trramwplow ;
		logic    [0:0]        Trramwrap ;
	} TrTrramwplowCsr_s;



	typedef struct packed {
		logic   [31:0]        Trramwphigh ;
	} TrTrramwphighCsr_s;



	typedef struct packed {
		logic   [29:0]        Trramrplow ;
		logic    [1:0]        Rsvd10 ;
	} TrTrramrplowCsr_s;



	typedef struct packed {
		logic   [31:0]        Trramrphigh ;
	} TrTrramrphighCsr_s;



	typedef struct packed {
		logic   [31:0]        Trramdata ;
	} TrTrramdataCsr_s;



	typedef struct packed {
		logic   [29:0]        Trcustomramsmemlimitlow ;
		logic    [1:0]        Rsvd10 ;
	} TrTrcustomramsmemlimitlowCsr_s;



	typedef struct packed {
		logic    [0:0]        Trdstramstoponwrap ;
		logic    [0:0]        Trdstrammode ;
		logic    [0:0]        Trdstramempty ;
		logic    [0:0]        Trdstramenable ;
		logic    [0:0]        Trdstramactive ;
	} TrTrdstramcontrolCsr_s;



	typedef struct packed {
		logic    [3:0]        Trdstramvendorframelength ;
		logic    [0:0]        Trdstramhassmem ;
		logic    [0:0]        Trdstramhassram ;
		logic    [3:0]        Trdstramcomptype ;
		logic    [3:0]        Trdstramverminor ;
		logic    [3:0]        Trdstramvermajor ;
	} TrTrdstramimplCsr_s;



	typedef struct packed {
		logic   [29:0]        Trdstramstartlow ;
		logic    [1:0]        Rsvd10 ;
	} TrTrdstramstartlowCsr_s;



	typedef struct packed {
		logic   [31:0]        Trdstramstarthigh ;
	} TrTrdstramstarthighCsr_s;



	typedef struct packed {
		logic   [29:0]        Trdstramlimitlow ;
		logic    [1:0]        Rsvd10 ;
	} TrTrdstramlimitlowCsr_s;



	typedef struct packed {
		logic   [31:0]        Trdstramlimithigh ;
	} TrTrdstramlimithighCsr_s;



	typedef struct packed {
		logic   [29:0]        Trdstramwplow ;
		logic    [0:0]        Trdstramwrap ;
	} TrTrdstramwplowCsr_s;



	typedef struct packed {
		logic   [31:0]        Trdstramwphigh ;
	} TrTrdstramwphighCsr_s;



	typedef struct packed {
		logic   [29:0]        Trdstramrplow ;
		logic    [1:0]        Rsvd10 ;
	} TrTrdstramrplowCsr_s;



	typedef struct packed {
		logic   [31:0]        Trdstramrphigh ;
	} TrTrdstramrphighCsr_s;



	typedef struct packed {
		logic   [31:0]        Trdstramdata ;
	} TrTrdstramdataCsr_s;



	typedef struct packed {
		logic    [2:0]        Core3Vid ;
		logic    [0:0]        Core3Enable ;
		logic    [2:0]        Core2Vid ;
		logic    [0:0]        Core2Enable ;
		logic    [2:0]        Core1Vid ;
		logic    [0:0]        Core1Enable ;
		logic    [2:0]        Core0Vid ;
		logic    [0:0]        Core0Enable ;
		logic    [3:0]        Rsvd1512 ;
		logic    [0:0]        IoCoherencyDisable ;
		logic    [0:0]        ExportRestrictionEnabled ;
		logic    [1:0]        Rsvd98 ;
		logic    [7:0]        ScHarvestStrap ;
	} TrTrclusterfusecfglowCsr_s;



	typedef struct packed {
		logic    [0:0]        Lock ;
		logic    [8:0]        Rsvd3022 ;
		logic    [0:0]        Jtag2UarchEnable ;
		logic    [0:0]        DstEnable ;
		logic    [0:0]        TraceEnable ;
		logic    [0:0]        ClaEnable ;
		logic    [1:0]        DebugEnable ;
		logic    [2:0]        Core7Vid ;
		logic    [0:0]        Core7Enable ;
		logic    [2:0]        Core6Vid ;
		logic    [0:0]        Core6Enable ;
		logic    [2:0]        Core5Vid ;
		logic    [0:0]        Core5Enable ;
		logic    [2:0]        Core4Vid ;
		logic    [0:0]        Core4Enable ;
	} TrTrclusterfusecfghiCsr_s;



	typedef struct packed {
		logic   [31:0]        Data ;
	} TrTrscratchloCsr_s;



	typedef struct packed {
		logic   [31:0]        Data ;
	} TrTrscratchhiCsr_s;



	typedef struct packed {
		logic   [31:0]        Data ;
	} TrTrscratchpadloCsr_s;



	typedef struct packed {
		logic   [31:0]        Data ;
	} TrTrscratchpadhiCsr_s;




	typedef struct packed {
		logic    [27:0]        rsvd_1 ;
		logic    [0:0]        Trfunnelempty ;
		logic    [0:0]        rsvd_0 ;
		logic    [0:0]        Trfunnelenable ;
		logic    [0:0]        Trfunnelactive ;
	} TrTrfunnelcontrolCsrUnpack_s;



	typedef struct packed {
		logic    [19:0]        rsvd_0 ;
		logic    [3:0]        Trfunnelcomptype ;
		logic    [3:0]        Trfunnelverminor ;
		logic    [3:0]        Trfunnelvermajor ;
	} TrTrfunnelimplCsrUnpack_s;



	typedef struct packed {
		logic    [15:0]        rsvd_0 ;
		logic   [15:0]        Trfunneldisinput ;
	} TrTrfunneldisinputCsrUnpack_s;



	typedef struct packed {
		logic    [22:0]        rsvd_2 ;
		logic    [0:0]        Trramstoponwrap ;
		logic    [2:0]        rsvd_1 ;
		logic    [0:0]        Trrammode ;
		logic    [0:0]        Trramempty ;
		logic    [0:0]        rsvd_0 ;
		logic    [0:0]        Trramenable ;
		logic    [0:0]        Trramactive ;
	} TrTrramcontrolCsrUnpack_s;



	typedef struct packed {
		logic    [3:0]        rsvd_1 ;
		logic    [3:0]        Trramvendorframelength ;
		logic    [9:0]        rsvd_0 ;
		logic    [0:0]        Trramhassmem ;
		logic    [0:0]        Trramhassram ;
		logic    [3:0]        Trramcomptype ;
		logic    [3:0]        Trramverminor ;
		logic    [3:0]        Trramvermajor ;
	} TrTrramimplCsrUnpack_s;



	typedef struct packed {
		logic   [29:0]        Trramstartlow ;
		logic    [1:0]        Rsvd10 ;
	} TrTrramstartlowCsrUnpack_s;



	typedef struct packed {
		logic   [31:0]        Trramstarthigh ;
	} TrTrramstarthighCsrUnpack_s;



	typedef struct packed {
		logic   [29:0]        Trramlimitlow ;
		logic    [1:0]        Rsvd10 ;
	} TrTrramlimitlowCsrUnpack_s;



	typedef struct packed {
		logic   [31:0]        Trramlimithigh ;
	} TrTrramlimithighCsrUnpack_s;



	typedef struct packed {
		logic   [29:0]        Trramwplow ;
		logic    [0:0]        rsvd_0 ;
		logic    [0:0]        Trramwrap ;
	} TrTrramwplowCsrUnpack_s;



	typedef struct packed {
		logic   [31:0]        Trramwphigh ;
	} TrTrramwphighCsrUnpack_s;



	typedef struct packed {
		logic   [29:0]        Trramrplow ;
		logic    [1:0]        Rsvd10 ;
	} TrTrramrplowCsrUnpack_s;



	typedef struct packed {
		logic   [31:0]        Trramrphigh ;
	} TrTrramrphighCsrUnpack_s;



	typedef struct packed {
		logic   [31:0]        Trramdata ;
	} TrTrramdataCsrUnpack_s;



	typedef struct packed {
		logic   [29:0]        Trcustomramsmemlimitlow ;
		logic    [1:0]        Rsvd10 ;
	} TrTrcustomramsmemlimitlowCsrUnpack_s;



	typedef struct packed {
		logic    [22:0]        rsvd_2 ;
		logic    [0:0]        Trdstramstoponwrap ;
		logic    [2:0]        rsvd_1 ;
		logic    [0:0]        Trdstrammode ;
		logic    [0:0]        Trdstramempty ;
		logic    [0:0]        rsvd_0 ;
		logic    [0:0]        Trdstramenable ;
		logic    [0:0]        Trdstramactive ;
	} TrTrdstramcontrolCsrUnpack_s;



	typedef struct packed {
		logic    [3:0]        rsvd_1 ;
		logic    [3:0]        Trdstramvendorframelength ;
		logic    [9:0]        rsvd_0 ;
		logic    [0:0]        Trdstramhassmem ;
		logic    [0:0]        Trdstramhassram ;
		logic    [3:0]        Trdstramcomptype ;
		logic    [3:0]        Trdstramverminor ;
		logic    [3:0]        Trdstramvermajor ;
	} TrTrdstramimplCsrUnpack_s;



	typedef struct packed {
		logic   [29:0]        Trdstramstartlow ;
		logic    [1:0]        Rsvd10 ;
	} TrTrdstramstartlowCsrUnpack_s;



	typedef struct packed {
		logic   [31:0]        Trdstramstarthigh ;
	} TrTrdstramstarthighCsrUnpack_s;



	typedef struct packed {
		logic   [29:0]        Trdstramlimitlow ;
		logic    [1:0]        Rsvd10 ;
	} TrTrdstramlimitlowCsrUnpack_s;



	typedef struct packed {
		logic   [31:0]        Trdstramlimithigh ;
	} TrTrdstramlimithighCsrUnpack_s;



	typedef struct packed {
		logic   [29:0]        Trdstramwplow ;
		logic    [0:0]        rsvd_0 ;
		logic    [0:0]        Trdstramwrap ;
	} TrTrdstramwplowCsrUnpack_s;



	typedef struct packed {
		logic   [31:0]        Trdstramwphigh ;
	} TrTrdstramwphighCsrUnpack_s;



	typedef struct packed {
		logic   [29:0]        Trdstramrplow ;
		logic    [1:0]        Rsvd10 ;
	} TrTrdstramrplowCsrUnpack_s;



	typedef struct packed {
		logic   [31:0]        Trdstramrphigh ;
	} TrTrdstramrphighCsrUnpack_s;



	typedef struct packed {
		logic   [31:0]        Trdstramdata ;
	} TrTrdstramdataCsrUnpack_s;



	typedef struct packed {
		logic    [2:0]        Core3Vid ;
		logic    [0:0]        Core3Enable ;
		logic    [2:0]        Core2Vid ;
		logic    [0:0]        Core2Enable ;
		logic    [2:0]        Core1Vid ;
		logic    [0:0]        Core1Enable ;
		logic    [2:0]        Core0Vid ;
		logic    [0:0]        Core0Enable ;
		logic    [3:0]        Rsvd1512 ;
		logic    [0:0]        IoCoherencyDisable ;
		logic    [0:0]        ExportRestrictionEnabled ;
		logic    [1:0]        Rsvd98 ;
		logic    [7:0]        ScHarvestStrap ;
	} TrTrclusterfusecfglowCsrUnpack_s;



	typedef struct packed {
		logic    [0:0]        Lock ;
		logic    [8:0]        Rsvd3022 ;
		logic    [0:0]        Jtag2UarchEnable ;
		logic    [0:0]        DstEnable ;
		logic    [0:0]        TraceEnable ;
		logic    [0:0]        ClaEnable ;
		logic    [1:0]        DebugEnable ;
		logic    [2:0]        Core7Vid ;
		logic    [0:0]        Core7Enable ;
		logic    [2:0]        Core6Vid ;
		logic    [0:0]        Core6Enable ;
		logic    [2:0]        Core5Vid ;
		logic    [0:0]        Core5Enable ;
		logic    [2:0]        Core4Vid ;
		logic    [0:0]        Core4Enable ;
	} TrTrclusterfusecfghiCsrUnpack_s;



	typedef struct packed {
		logic   [31:0]        Data ;
	} TrTrscratchloCsrUnpack_s;



	typedef struct packed {
		logic   [31:0]        Data ;
	} TrTrscratchhiCsrUnpack_s;



	typedef struct packed {
		logic   [31:0]        Data ;
	} TrTrscratchpadloCsrUnpack_s;



	typedef struct packed {
		logic   [31:0]        Data ;
	} TrTrscratchpadhiCsrUnpack_s;







	typedef struct packed {
		TrTrfunnelcontrolCsr_s Data;
		logic                 TrfunnelemptyWrEn ;
		logic                 TrfunnelenableWrEn ;
		logic                 TrfunnelactiveWrEn ;
	} TrTrfunnelcontrolCsrWr_s;



	typedef struct packed {
		TrTrfunnelimplCsr_s   Data;
	} TrTrfunnelimplCsrWr_s;



	typedef struct packed {
		TrTrfunneldisinputCsr_s Data;
		logic                 TrfunneldisinputWrEn ;
	} TrTrfunneldisinputCsrWr_s;



	typedef struct packed {
		TrTrramcontrolCsr_s   Data;
		logic                 TrramstoponwrapWrEn ;
		logic                 TrrammodeWrEn ;
		logic                 TrramemptyWrEn ;
		logic                 TrramenableWrEn ;
		logic                 TrramactiveWrEn ;
	} TrTrramcontrolCsrWr_s;



	typedef struct packed {
		TrTrramimplCsr_s      Data;
	} TrTrramimplCsrWr_s;



	typedef struct packed {
		TrTrramstartlowCsr_s  Data;
		logic                 TrramstartlowWrEn ;
	} TrTrramstartlowCsrWr_s;



	typedef struct packed {
		TrTrramstarthighCsr_s Data;
		logic                 TrramstarthighWrEn ;
	} TrTrramstarthighCsrWr_s;



	typedef struct packed {
		TrTrramlimitlowCsr_s  Data;
		logic                 TrramlimitlowWrEn ;
	} TrTrramlimitlowCsrWr_s;



	typedef struct packed {
		TrTrramlimithighCsr_s Data;
		logic                 TrramlimithighWrEn ;
	} TrTrramlimithighCsrWr_s;



	typedef struct packed {
		TrTrramwplowCsr_s     Data;
		logic                 TrramwplowWrEn ;
		logic                 TrramwrapWrEn ;
	} TrTrramwplowCsrWr_s;



	typedef struct packed {
		TrTrramwphighCsr_s    Data;
		logic                 TrramwphighWrEn ;
	} TrTrramwphighCsrWr_s;



	typedef struct packed {
		TrTrramrplowCsr_s     Data;
		logic                 TrramrplowWrEn ;
	} TrTrramrplowCsrWr_s;



	typedef struct packed {
		TrTrramrphighCsr_s    Data;
		logic                 TrramrphighWrEn ;
	} TrTrramrphighCsrWr_s;



	typedef struct packed {
		TrTrramdataCsr_s      Data;
		logic                 TrramdataWrEn ;
	} TrTrramdataCsrWr_s;



	typedef struct packed {
		TrTrcustomramsmemlimitlowCsr_s Data;
	} TrTrcustomramsmemlimitlowCsrWr_s;



	typedef struct packed {
		TrTrdstramcontrolCsr_s Data;
		logic                 TrdstramstoponwrapWrEn ;
		logic                 TrdstrammodeWrEn ;
		logic                 TrdstramemptyWrEn ;
		logic                 TrdstramenableWrEn ;
		logic                 TrdstramactiveWrEn ;
	} TrTrdstramcontrolCsrWr_s;



	typedef struct packed {
		TrTrdstramimplCsr_s   Data;
	} TrTrdstramimplCsrWr_s;



	typedef struct packed {
		TrTrdstramstartlowCsr_s Data;
		logic                 TrdstramstartlowWrEn ;
	} TrTrdstramstartlowCsrWr_s;



	typedef struct packed {
		TrTrdstramstarthighCsr_s Data;
		logic                 TrdstramstarthighWrEn ;
	} TrTrdstramstarthighCsrWr_s;



	typedef struct packed {
		TrTrdstramlimitlowCsr_s Data;
		logic                 TrdstramlimitlowWrEn ;
	} TrTrdstramlimitlowCsrWr_s;



	typedef struct packed {
		TrTrdstramlimithighCsr_s Data;
		logic                 TrdstramlimithighWrEn ;
	} TrTrdstramlimithighCsrWr_s;



	typedef struct packed {
		TrTrdstramwplowCsr_s  Data;
		logic                 TrdstramwplowWrEn ;
		logic                 TrdstramwrapWrEn ;
	} TrTrdstramwplowCsrWr_s;



	typedef struct packed {
		TrTrdstramwphighCsr_s Data;
		logic                 TrdstramwphighWrEn ;
	} TrTrdstramwphighCsrWr_s;



	typedef struct packed {
		TrTrdstramrplowCsr_s  Data;
		logic                 TrdstramrplowWrEn ;
	} TrTrdstramrplowCsrWr_s;



	typedef struct packed {
		TrTrdstramrphighCsr_s Data;
		logic                 TrdstramrphighWrEn ;
	} TrTrdstramrphighCsrWr_s;



	typedef struct packed {
		TrTrdstramdataCsr_s   Data;
		logic                 TrdstramdataWrEn ;
	} TrTrdstramdataCsrWr_s;



	typedef struct packed {
		TrTrfunnelcontrolCsr_s TrCsrTrfunnelcontrol;
		TrTrfunnelimplCsr_s   TrCsrTrfunnelimpl;
		TrTrfunneldisinputCsr_s TrCsrTrfunneldisinput;
		TrTrramcontrolCsr_s   TrCsrTrramcontrol;
		TrTrramimplCsr_s      TrCsrTrramimpl;
		TrTrramstartlowCsr_s  TrCsrTrramstartlow;
		TrTrramstarthighCsr_s TrCsrTrramstarthigh;
		TrTrramlimitlowCsr_s  TrCsrTrramlimitlow;
		TrTrramlimithighCsr_s TrCsrTrramlimithigh;
		TrTrramwplowCsr_s     TrCsrTrramwplow;
		TrTrramwphighCsr_s    TrCsrTrramwphigh;
		TrTrramrplowCsr_s     TrCsrTrramrplow;
		TrTrramrphighCsr_s    TrCsrTrramrphigh;
		TrTrramdataCsr_s      TrCsrTrramdata;
		TrTrcustomramsmemlimitlowCsr_s TrCsrTrcustomramsmemlimitlow;
		TrTrdstramcontrolCsr_s TrCsrTrdstramcontrol;
		TrTrdstramimplCsr_s   TrCsrTrdstramimpl;
		TrTrdstramstartlowCsr_s TrCsrTrdstramstartlow;
		TrTrdstramstarthighCsr_s TrCsrTrdstramstarthigh;
		TrTrdstramlimitlowCsr_s TrCsrTrdstramlimitlow;
		TrTrdstramlimithighCsr_s TrCsrTrdstramlimithigh;
		TrTrdstramwplowCsr_s  TrCsrTrdstramwplow;
		TrTrdstramwphighCsr_s TrCsrTrdstramwphigh;
		TrTrdstramrplowCsr_s  TrCsrTrdstramrplow;
		TrTrdstramrphighCsr_s TrCsrTrdstramrphigh;
		TrTrdstramdataCsr_s   TrCsrTrdstramdata;
		TrTrclusterfusecfglowCsr_s TrCsrTrclusterfusecfglow;
		TrTrclusterfusecfghiCsr_s TrCsrTrclusterfusecfghi;
		TrTrscratchloCsr_s    TrCsrTrscratchlo;
		TrTrscratchhiCsr_s    TrCsrTrscratchhi;
		TrTrscratchpadloCsr_s TrCsrTrscratchpadlo;
		TrTrscratchpadhiCsr_s TrCsrTrscratchpadhi;
	} TrCsrs_s;


	typedef struct packed {
		TrTrfunnelcontrolCsrWr_s TrCsrTrfunnelcontrolWr;
		TrTrfunnelimplCsrWr_s TrCsrTrfunnelimplWr;
		TrTrfunneldisinputCsrWr_s TrCsrTrfunneldisinputWr;
		TrTrramcontrolCsrWr_s TrCsrTrramcontrolWr;
		TrTrramimplCsrWr_s    TrCsrTrramimplWr;
		TrTrramstartlowCsrWr_s TrCsrTrramstartlowWr;
		TrTrramstarthighCsrWr_s TrCsrTrramstarthighWr;
		TrTrramlimitlowCsrWr_s TrCsrTrramlimitlowWr;
		TrTrramlimithighCsrWr_s TrCsrTrramlimithighWr;
		TrTrramwplowCsrWr_s   TrCsrTrramwplowWr;
		TrTrramwphighCsrWr_s  TrCsrTrramwphighWr;
		TrTrramrplowCsrWr_s   TrCsrTrramrplowWr;
		TrTrramrphighCsrWr_s  TrCsrTrramrphighWr;
		TrTrramdataCsrWr_s    TrCsrTrramdataWr;
		TrTrcustomramsmemlimitlowCsrWr_s TrCsrTrcustomramsmemlimitlowWr;
		TrTrdstramcontrolCsrWr_s TrCsrTrdstramcontrolWr;
		TrTrdstramimplCsrWr_s TrCsrTrdstramimplWr;
		TrTrdstramstartlowCsrWr_s TrCsrTrdstramstartlowWr;
		TrTrdstramstarthighCsrWr_s TrCsrTrdstramstarthighWr;
		TrTrdstramlimitlowCsrWr_s TrCsrTrdstramlimitlowWr;
		TrTrdstramlimithighCsrWr_s TrCsrTrdstramlimithighWr;
		TrTrdstramwplowCsrWr_s TrCsrTrdstramwplowWr;
		TrTrdstramwphighCsrWr_s TrCsrTrdstramwphighWr;
		TrTrdstramrplowCsrWr_s TrCsrTrdstramrplowWr;
		TrTrdstramrphighCsrWr_s TrCsrTrdstramrphighWr;
		TrTrdstramdataCsrWr_s TrCsrTrdstramdataWr;
	} TrCsrsWr_s;



	function automatic TrTrfunnelcontrolCsrUnpack_s unpack_TrTrfunnelcontrolCsr;
		input TrTrfunnelcontrolCsr_s packed_csr;
		begin
			unpack_TrTrfunnelcontrolCsr = '0;
			unpack_TrTrfunnelcontrolCsr.Trfunnelactive = packed_csr.Trfunnelactive;
			unpack_TrTrfunnelcontrolCsr.Trfunnelenable = packed_csr.Trfunnelenable;
			unpack_TrTrfunnelcontrolCsr.Trfunnelempty = packed_csr.Trfunnelempty;
		end
	endfunction


	function automatic TrTrfunnelimplCsrUnpack_s unpack_TrTrfunnelimplCsr;
		input TrTrfunnelimplCsr_s packed_csr;
		begin
			unpack_TrTrfunnelimplCsr = '0;
			unpack_TrTrfunnelimplCsr.Trfunnelvermajor = packed_csr.Trfunnelvermajor;
			unpack_TrTrfunnelimplCsr.Trfunnelverminor = packed_csr.Trfunnelverminor;
			unpack_TrTrfunnelimplCsr.Trfunnelcomptype = packed_csr.Trfunnelcomptype;
		end
	endfunction


	function automatic TrTrfunneldisinputCsrUnpack_s unpack_TrTrfunneldisinputCsr;
		input TrTrfunneldisinputCsr_s packed_csr;
		begin
			unpack_TrTrfunneldisinputCsr = '0;
			unpack_TrTrfunneldisinputCsr.Trfunneldisinput = packed_csr.Trfunneldisinput;
		end
	endfunction


	function automatic TrTrramcontrolCsrUnpack_s unpack_TrTrramcontrolCsr;
		input TrTrramcontrolCsr_s packed_csr;
		begin
			unpack_TrTrramcontrolCsr = '0;
			unpack_TrTrramcontrolCsr.Trramactive = packed_csr.Trramactive;
			unpack_TrTrramcontrolCsr.Trramenable = packed_csr.Trramenable;
			unpack_TrTrramcontrolCsr.Trramempty = packed_csr.Trramempty;
			unpack_TrTrramcontrolCsr.Trrammode = packed_csr.Trrammode;
			unpack_TrTrramcontrolCsr.Trramstoponwrap = packed_csr.Trramstoponwrap;
		end
	endfunction


	function automatic TrTrramimplCsrUnpack_s unpack_TrTrramimplCsr;
		input TrTrramimplCsr_s packed_csr;
		begin
			unpack_TrTrramimplCsr = '0;
			unpack_TrTrramimplCsr.Trramvermajor = packed_csr.Trramvermajor;
			unpack_TrTrramimplCsr.Trramverminor = packed_csr.Trramverminor;
			unpack_TrTrramimplCsr.Trramcomptype = packed_csr.Trramcomptype;
			unpack_TrTrramimplCsr.Trramhassram = packed_csr.Trramhassram;
			unpack_TrTrramimplCsr.Trramhassmem = packed_csr.Trramhassmem;
			unpack_TrTrramimplCsr.Trramvendorframelength = packed_csr.Trramvendorframelength;
		end
	endfunction


	function automatic TrTrramstartlowCsrUnpack_s unpack_TrTrramstartlowCsr;
		input TrTrramstartlowCsr_s packed_csr;
		begin
			unpack_TrTrramstartlowCsr = '0;
			unpack_TrTrramstartlowCsr.Rsvd10 = packed_csr.Rsvd10;
			unpack_TrTrramstartlowCsr.Trramstartlow = packed_csr.Trramstartlow;
		end
	endfunction


	function automatic TrTrramstarthighCsrUnpack_s unpack_TrTrramstarthighCsr;
		input TrTrramstarthighCsr_s packed_csr;
		begin
			unpack_TrTrramstarthighCsr = '0;
			unpack_TrTrramstarthighCsr.Trramstarthigh = packed_csr.Trramstarthigh;
		end
	endfunction


	function automatic TrTrramlimitlowCsrUnpack_s unpack_TrTrramlimitlowCsr;
		input TrTrramlimitlowCsr_s packed_csr;
		begin
			unpack_TrTrramlimitlowCsr = '0;
			unpack_TrTrramlimitlowCsr.Rsvd10 = packed_csr.Rsvd10;
			unpack_TrTrramlimitlowCsr.Trramlimitlow = packed_csr.Trramlimitlow;
		end
	endfunction


	function automatic TrTrramlimithighCsrUnpack_s unpack_TrTrramlimithighCsr;
		input TrTrramlimithighCsr_s packed_csr;
		begin
			unpack_TrTrramlimithighCsr = '0;
			unpack_TrTrramlimithighCsr.Trramlimithigh = packed_csr.Trramlimithigh;
		end
	endfunction


	function automatic TrTrramwplowCsrUnpack_s unpack_TrTrramwplowCsr;
		input TrTrramwplowCsr_s packed_csr;
		begin
			unpack_TrTrramwplowCsr = '0;
			unpack_TrTrramwplowCsr.Trramwrap = packed_csr.Trramwrap;
			unpack_TrTrramwplowCsr.Trramwplow = packed_csr.Trramwplow;
		end
	endfunction


	function automatic TrTrramwphighCsrUnpack_s unpack_TrTrramwphighCsr;
		input TrTrramwphighCsr_s packed_csr;
		begin
			unpack_TrTrramwphighCsr = '0;
			unpack_TrTrramwphighCsr.Trramwphigh = packed_csr.Trramwphigh;
		end
	endfunction


	function automatic TrTrramrplowCsrUnpack_s unpack_TrTrramrplowCsr;
		input TrTrramrplowCsr_s packed_csr;
		begin
			unpack_TrTrramrplowCsr = '0;
			unpack_TrTrramrplowCsr.Rsvd10 = packed_csr.Rsvd10;
			unpack_TrTrramrplowCsr.Trramrplow = packed_csr.Trramrplow;
		end
	endfunction


	function automatic TrTrramrphighCsrUnpack_s unpack_TrTrramrphighCsr;
		input TrTrramrphighCsr_s packed_csr;
		begin
			unpack_TrTrramrphighCsr = '0;
			unpack_TrTrramrphighCsr.Trramrphigh = packed_csr.Trramrphigh;
		end
	endfunction


	function automatic TrTrramdataCsrUnpack_s unpack_TrTrramdataCsr;
		input TrTrramdataCsr_s packed_csr;
		begin
			unpack_TrTrramdataCsr = '0;
			unpack_TrTrramdataCsr.Trramdata = packed_csr.Trramdata;
		end
	endfunction


	function automatic TrTrcustomramsmemlimitlowCsrUnpack_s unpack_TrTrcustomramsmemlimitlowCsr;
		input TrTrcustomramsmemlimitlowCsr_s packed_csr;
		begin
			unpack_TrTrcustomramsmemlimitlowCsr = '0;
			unpack_TrTrcustomramsmemlimitlowCsr.Rsvd10 = packed_csr.Rsvd10;
			unpack_TrTrcustomramsmemlimitlowCsr.Trcustomramsmemlimitlow = packed_csr.Trcustomramsmemlimitlow;
		end
	endfunction


	function automatic TrTrdstramcontrolCsrUnpack_s unpack_TrTrdstramcontrolCsr;
		input TrTrdstramcontrolCsr_s packed_csr;
		begin
			unpack_TrTrdstramcontrolCsr = '0;
			unpack_TrTrdstramcontrolCsr.Trdstramactive = packed_csr.Trdstramactive;
			unpack_TrTrdstramcontrolCsr.Trdstramenable = packed_csr.Trdstramenable;
			unpack_TrTrdstramcontrolCsr.Trdstramempty = packed_csr.Trdstramempty;
			unpack_TrTrdstramcontrolCsr.Trdstrammode = packed_csr.Trdstrammode;
			unpack_TrTrdstramcontrolCsr.Trdstramstoponwrap = packed_csr.Trdstramstoponwrap;
		end
	endfunction


	function automatic TrTrdstramimplCsrUnpack_s unpack_TrTrdstramimplCsr;
		input TrTrdstramimplCsr_s packed_csr;
		begin
			unpack_TrTrdstramimplCsr = '0;
			unpack_TrTrdstramimplCsr.Trdstramvermajor = packed_csr.Trdstramvermajor;
			unpack_TrTrdstramimplCsr.Trdstramverminor = packed_csr.Trdstramverminor;
			unpack_TrTrdstramimplCsr.Trdstramcomptype = packed_csr.Trdstramcomptype;
			unpack_TrTrdstramimplCsr.Trdstramhassram = packed_csr.Trdstramhassram;
			unpack_TrTrdstramimplCsr.Trdstramhassmem = packed_csr.Trdstramhassmem;
			unpack_TrTrdstramimplCsr.Trdstramvendorframelength = packed_csr.Trdstramvendorframelength;
		end
	endfunction


	function automatic TrTrdstramstartlowCsrUnpack_s unpack_TrTrdstramstartlowCsr;
		input TrTrdstramstartlowCsr_s packed_csr;
		begin
			unpack_TrTrdstramstartlowCsr = '0;
			unpack_TrTrdstramstartlowCsr.Rsvd10 = packed_csr.Rsvd10;
			unpack_TrTrdstramstartlowCsr.Trdstramstartlow = packed_csr.Trdstramstartlow;
		end
	endfunction


	function automatic TrTrdstramstarthighCsrUnpack_s unpack_TrTrdstramstarthighCsr;
		input TrTrdstramstarthighCsr_s packed_csr;
		begin
			unpack_TrTrdstramstarthighCsr = '0;
			unpack_TrTrdstramstarthighCsr.Trdstramstarthigh = packed_csr.Trdstramstarthigh;
		end
	endfunction


	function automatic TrTrdstramlimitlowCsrUnpack_s unpack_TrTrdstramlimitlowCsr;
		input TrTrdstramlimitlowCsr_s packed_csr;
		begin
			unpack_TrTrdstramlimitlowCsr = '0;
			unpack_TrTrdstramlimitlowCsr.Rsvd10 = packed_csr.Rsvd10;
			unpack_TrTrdstramlimitlowCsr.Trdstramlimitlow = packed_csr.Trdstramlimitlow;
		end
	endfunction


	function automatic TrTrdstramlimithighCsrUnpack_s unpack_TrTrdstramlimithighCsr;
		input TrTrdstramlimithighCsr_s packed_csr;
		begin
			unpack_TrTrdstramlimithighCsr = '0;
			unpack_TrTrdstramlimithighCsr.Trdstramlimithigh = packed_csr.Trdstramlimithigh;
		end
	endfunction


	function automatic TrTrdstramwplowCsrUnpack_s unpack_TrTrdstramwplowCsr;
		input TrTrdstramwplowCsr_s packed_csr;
		begin
			unpack_TrTrdstramwplowCsr = '0;
			unpack_TrTrdstramwplowCsr.Trdstramwrap = packed_csr.Trdstramwrap;
			unpack_TrTrdstramwplowCsr.Trdstramwplow = packed_csr.Trdstramwplow;
		end
	endfunction


	function automatic TrTrdstramwphighCsrUnpack_s unpack_TrTrdstramwphighCsr;
		input TrTrdstramwphighCsr_s packed_csr;
		begin
			unpack_TrTrdstramwphighCsr = '0;
			unpack_TrTrdstramwphighCsr.Trdstramwphigh = packed_csr.Trdstramwphigh;
		end
	endfunction


	function automatic TrTrdstramrplowCsrUnpack_s unpack_TrTrdstramrplowCsr;
		input TrTrdstramrplowCsr_s packed_csr;
		begin
			unpack_TrTrdstramrplowCsr = '0;
			unpack_TrTrdstramrplowCsr.Rsvd10 = packed_csr.Rsvd10;
			unpack_TrTrdstramrplowCsr.Trdstramrplow = packed_csr.Trdstramrplow;
		end
	endfunction


	function automatic TrTrdstramrphighCsrUnpack_s unpack_TrTrdstramrphighCsr;
		input TrTrdstramrphighCsr_s packed_csr;
		begin
			unpack_TrTrdstramrphighCsr = '0;
			unpack_TrTrdstramrphighCsr.Trdstramrphigh = packed_csr.Trdstramrphigh;
		end
	endfunction


	function automatic TrTrdstramdataCsrUnpack_s unpack_TrTrdstramdataCsr;
		input TrTrdstramdataCsr_s packed_csr;
		begin
			unpack_TrTrdstramdataCsr = '0;
			unpack_TrTrdstramdataCsr.Trdstramdata = packed_csr.Trdstramdata;
		end
	endfunction


	function automatic TrTrclusterfusecfglowCsrUnpack_s unpack_TrTrclusterfusecfglowCsr;
		input TrTrclusterfusecfglowCsr_s packed_csr;
		begin
			unpack_TrTrclusterfusecfglowCsr = '0;
			unpack_TrTrclusterfusecfglowCsr.ScHarvestStrap = packed_csr.ScHarvestStrap;
			unpack_TrTrclusterfusecfglowCsr.Rsvd98 = packed_csr.Rsvd98;
			unpack_TrTrclusterfusecfglowCsr.ExportRestrictionEnabled = packed_csr.ExportRestrictionEnabled;
			unpack_TrTrclusterfusecfglowCsr.IoCoherencyDisable = packed_csr.IoCoherencyDisable;
			unpack_TrTrclusterfusecfglowCsr.Rsvd1512 = packed_csr.Rsvd1512;
			unpack_TrTrclusterfusecfglowCsr.Core0Enable = packed_csr.Core0Enable;
			unpack_TrTrclusterfusecfglowCsr.Core0Vid = packed_csr.Core0Vid;
			unpack_TrTrclusterfusecfglowCsr.Core1Enable = packed_csr.Core1Enable;
			unpack_TrTrclusterfusecfglowCsr.Core1Vid = packed_csr.Core1Vid;
			unpack_TrTrclusterfusecfglowCsr.Core2Enable = packed_csr.Core2Enable;
			unpack_TrTrclusterfusecfglowCsr.Core2Vid = packed_csr.Core2Vid;
			unpack_TrTrclusterfusecfglowCsr.Core3Enable = packed_csr.Core3Enable;
			unpack_TrTrclusterfusecfglowCsr.Core3Vid = packed_csr.Core3Vid;
		end
	endfunction


	function automatic TrTrclusterfusecfghiCsrUnpack_s unpack_TrTrclusterfusecfghiCsr;
		input TrTrclusterfusecfghiCsr_s packed_csr;
		begin
			unpack_TrTrclusterfusecfghiCsr = '0;
			unpack_TrTrclusterfusecfghiCsr.Core4Enable = packed_csr.Core4Enable;
			unpack_TrTrclusterfusecfghiCsr.Core4Vid = packed_csr.Core4Vid;
			unpack_TrTrclusterfusecfghiCsr.Core5Enable = packed_csr.Core5Enable;
			unpack_TrTrclusterfusecfghiCsr.Core5Vid = packed_csr.Core5Vid;
			unpack_TrTrclusterfusecfghiCsr.Core6Enable = packed_csr.Core6Enable;
			unpack_TrTrclusterfusecfghiCsr.Core6Vid = packed_csr.Core6Vid;
			unpack_TrTrclusterfusecfghiCsr.Core7Enable = packed_csr.Core7Enable;
			unpack_TrTrclusterfusecfghiCsr.Core7Vid = packed_csr.Core7Vid;
			unpack_TrTrclusterfusecfghiCsr.DebugEnable = packed_csr.DebugEnable;
			unpack_TrTrclusterfusecfghiCsr.ClaEnable = packed_csr.ClaEnable;
			unpack_TrTrclusterfusecfghiCsr.TraceEnable = packed_csr.TraceEnable;
			unpack_TrTrclusterfusecfghiCsr.DstEnable = packed_csr.DstEnable;
			unpack_TrTrclusterfusecfghiCsr.Jtag2UarchEnable = packed_csr.Jtag2UarchEnable;
			unpack_TrTrclusterfusecfghiCsr.Rsvd3022 = packed_csr.Rsvd3022;
			unpack_TrTrclusterfusecfghiCsr.Lock = packed_csr.Lock;
		end
	endfunction


	function automatic TrTrscratchloCsrUnpack_s unpack_TrTrscratchloCsr;
		input TrTrscratchloCsr_s packed_csr;
		begin
			unpack_TrTrscratchloCsr = '0;
			unpack_TrTrscratchloCsr.Data = packed_csr.Data;
		end
	endfunction


	function automatic TrTrscratchhiCsrUnpack_s unpack_TrTrscratchhiCsr;
		input TrTrscratchhiCsr_s packed_csr;
		begin
			unpack_TrTrscratchhiCsr = '0;
			unpack_TrTrscratchhiCsr.Data = packed_csr.Data;
		end
	endfunction


	function automatic TrTrscratchpadloCsrUnpack_s unpack_TrTrscratchpadloCsr;
		input TrTrscratchpadloCsr_s packed_csr;
		begin
			unpack_TrTrscratchpadloCsr = '0;
			unpack_TrTrscratchpadloCsr.Data = packed_csr.Data;
		end
	endfunction


	function automatic TrTrscratchpadhiCsrUnpack_s unpack_TrTrscratchpadhiCsr;
		input TrTrscratchpadhiCsr_s packed_csr;
		begin
			unpack_TrTrscratchpadhiCsr = '0;
			unpack_TrTrscratchpadhiCsr.Data = packed_csr.Data;
		end
	endfunction



	function automatic TrTrfunnelcontrolCsr_s pack_TrTrfunnelcontrolCsr;
		input TrTrfunnelcontrolCsrUnpack_s unpacked_csr;
		begin
			pack_TrTrfunnelcontrolCsr.Trfunnelactive = unpacked_csr.Trfunnelactive;
			pack_TrTrfunnelcontrolCsr.Trfunnelenable = unpacked_csr.Trfunnelenable;
			pack_TrTrfunnelcontrolCsr.Trfunnelempty = unpacked_csr.Trfunnelempty;
		end
	endfunction


	function automatic TrTrfunnelimplCsr_s pack_TrTrfunnelimplCsr;
		input TrTrfunnelimplCsrUnpack_s unpacked_csr;
		begin
			pack_TrTrfunnelimplCsr.Trfunnelvermajor = unpacked_csr.Trfunnelvermajor;
			pack_TrTrfunnelimplCsr.Trfunnelverminor = unpacked_csr.Trfunnelverminor;
			pack_TrTrfunnelimplCsr.Trfunnelcomptype = unpacked_csr.Trfunnelcomptype;
		end
	endfunction


	function automatic TrTrfunneldisinputCsr_s pack_TrTrfunneldisinputCsr;
		input TrTrfunneldisinputCsrUnpack_s unpacked_csr;
		begin
			pack_TrTrfunneldisinputCsr.Trfunneldisinput = unpacked_csr.Trfunneldisinput;
		end
	endfunction


	function automatic TrTrramcontrolCsr_s pack_TrTrramcontrolCsr;
		input TrTrramcontrolCsrUnpack_s unpacked_csr;
		begin
			pack_TrTrramcontrolCsr.Trramactive = unpacked_csr.Trramactive;
			pack_TrTrramcontrolCsr.Trramenable = unpacked_csr.Trramenable;
			pack_TrTrramcontrolCsr.Trramempty = unpacked_csr.Trramempty;
			pack_TrTrramcontrolCsr.Trrammode = unpacked_csr.Trrammode;
			pack_TrTrramcontrolCsr.Trramstoponwrap = unpacked_csr.Trramstoponwrap;
		end
	endfunction


	function automatic TrTrramimplCsr_s pack_TrTrramimplCsr;
		input TrTrramimplCsrUnpack_s unpacked_csr;
		begin
			pack_TrTrramimplCsr.Trramvermajor = unpacked_csr.Trramvermajor;
			pack_TrTrramimplCsr.Trramverminor = unpacked_csr.Trramverminor;
			pack_TrTrramimplCsr.Trramcomptype = unpacked_csr.Trramcomptype;
			pack_TrTrramimplCsr.Trramhassram = unpacked_csr.Trramhassram;
			pack_TrTrramimplCsr.Trramhassmem = unpacked_csr.Trramhassmem;
			pack_TrTrramimplCsr.Trramvendorframelength = unpacked_csr.Trramvendorframelength;
		end
	endfunction


	function automatic TrTrramstartlowCsr_s pack_TrTrramstartlowCsr;
		input TrTrramstartlowCsrUnpack_s unpacked_csr;
		begin
			pack_TrTrramstartlowCsr.Rsvd10 = unpacked_csr.Rsvd10;
			pack_TrTrramstartlowCsr.Trramstartlow = unpacked_csr.Trramstartlow;
		end
	endfunction


	function automatic TrTrramstarthighCsr_s pack_TrTrramstarthighCsr;
		input TrTrramstarthighCsrUnpack_s unpacked_csr;
		begin
			pack_TrTrramstarthighCsr.Trramstarthigh = unpacked_csr.Trramstarthigh;
		end
	endfunction


	function automatic TrTrramlimitlowCsr_s pack_TrTrramlimitlowCsr;
		input TrTrramlimitlowCsrUnpack_s unpacked_csr;
		begin
			pack_TrTrramlimitlowCsr.Rsvd10 = unpacked_csr.Rsvd10;
			pack_TrTrramlimitlowCsr.Trramlimitlow = unpacked_csr.Trramlimitlow;
		end
	endfunction


	function automatic TrTrramlimithighCsr_s pack_TrTrramlimithighCsr;
		input TrTrramlimithighCsrUnpack_s unpacked_csr;
		begin
			pack_TrTrramlimithighCsr.Trramlimithigh = unpacked_csr.Trramlimithigh;
		end
	endfunction


	function automatic TrTrramwplowCsr_s pack_TrTrramwplowCsr;
		input TrTrramwplowCsrUnpack_s unpacked_csr;
		begin
			pack_TrTrramwplowCsr.Trramwrap = unpacked_csr.Trramwrap;
			pack_TrTrramwplowCsr.Trramwplow = unpacked_csr.Trramwplow;
		end
	endfunction


	function automatic TrTrramwphighCsr_s pack_TrTrramwphighCsr;
		input TrTrramwphighCsrUnpack_s unpacked_csr;
		begin
			pack_TrTrramwphighCsr.Trramwphigh = unpacked_csr.Trramwphigh;
		end
	endfunction


	function automatic TrTrramrplowCsr_s pack_TrTrramrplowCsr;
		input TrTrramrplowCsrUnpack_s unpacked_csr;
		begin
			pack_TrTrramrplowCsr.Rsvd10 = unpacked_csr.Rsvd10;
			pack_TrTrramrplowCsr.Trramrplow = unpacked_csr.Trramrplow;
		end
	endfunction


	function automatic TrTrramrphighCsr_s pack_TrTrramrphighCsr;
		input TrTrramrphighCsrUnpack_s unpacked_csr;
		begin
			pack_TrTrramrphighCsr.Trramrphigh = unpacked_csr.Trramrphigh;
		end
	endfunction


	function automatic TrTrramdataCsr_s pack_TrTrramdataCsr;
		input TrTrramdataCsrUnpack_s unpacked_csr;
		begin
			pack_TrTrramdataCsr.Trramdata = unpacked_csr.Trramdata;
		end
	endfunction


	function automatic TrTrcustomramsmemlimitlowCsr_s pack_TrTrcustomramsmemlimitlowCsr;
		input TrTrcustomramsmemlimitlowCsrUnpack_s unpacked_csr;
		begin
			pack_TrTrcustomramsmemlimitlowCsr.Rsvd10 = unpacked_csr.Rsvd10;
			pack_TrTrcustomramsmemlimitlowCsr.Trcustomramsmemlimitlow = unpacked_csr.Trcustomramsmemlimitlow;
		end
	endfunction


	function automatic TrTrdstramcontrolCsr_s pack_TrTrdstramcontrolCsr;
		input TrTrdstramcontrolCsrUnpack_s unpacked_csr;
		begin
			pack_TrTrdstramcontrolCsr.Trdstramactive = unpacked_csr.Trdstramactive;
			pack_TrTrdstramcontrolCsr.Trdstramenable = unpacked_csr.Trdstramenable;
			pack_TrTrdstramcontrolCsr.Trdstramempty = unpacked_csr.Trdstramempty;
			pack_TrTrdstramcontrolCsr.Trdstrammode = unpacked_csr.Trdstrammode;
			pack_TrTrdstramcontrolCsr.Trdstramstoponwrap = unpacked_csr.Trdstramstoponwrap;
		end
	endfunction


	function automatic TrTrdstramimplCsr_s pack_TrTrdstramimplCsr;
		input TrTrdstramimplCsrUnpack_s unpacked_csr;
		begin
			pack_TrTrdstramimplCsr.Trdstramvermajor = unpacked_csr.Trdstramvermajor;
			pack_TrTrdstramimplCsr.Trdstramverminor = unpacked_csr.Trdstramverminor;
			pack_TrTrdstramimplCsr.Trdstramcomptype = unpacked_csr.Trdstramcomptype;
			pack_TrTrdstramimplCsr.Trdstramhassram = unpacked_csr.Trdstramhassram;
			pack_TrTrdstramimplCsr.Trdstramhassmem = unpacked_csr.Trdstramhassmem;
			pack_TrTrdstramimplCsr.Trdstramvendorframelength = unpacked_csr.Trdstramvendorframelength;
		end
	endfunction


	function automatic TrTrdstramstartlowCsr_s pack_TrTrdstramstartlowCsr;
		input TrTrdstramstartlowCsrUnpack_s unpacked_csr;
		begin
			pack_TrTrdstramstartlowCsr.Rsvd10 = unpacked_csr.Rsvd10;
			pack_TrTrdstramstartlowCsr.Trdstramstartlow = unpacked_csr.Trdstramstartlow;
		end
	endfunction


	function automatic TrTrdstramstarthighCsr_s pack_TrTrdstramstarthighCsr;
		input TrTrdstramstarthighCsrUnpack_s unpacked_csr;
		begin
			pack_TrTrdstramstarthighCsr.Trdstramstarthigh = unpacked_csr.Trdstramstarthigh;
		end
	endfunction


	function automatic TrTrdstramlimitlowCsr_s pack_TrTrdstramlimitlowCsr;
		input TrTrdstramlimitlowCsrUnpack_s unpacked_csr;
		begin
			pack_TrTrdstramlimitlowCsr.Rsvd10 = unpacked_csr.Rsvd10;
			pack_TrTrdstramlimitlowCsr.Trdstramlimitlow = unpacked_csr.Trdstramlimitlow;
		end
	endfunction


	function automatic TrTrdstramlimithighCsr_s pack_TrTrdstramlimithighCsr;
		input TrTrdstramlimithighCsrUnpack_s unpacked_csr;
		begin
			pack_TrTrdstramlimithighCsr.Trdstramlimithigh = unpacked_csr.Trdstramlimithigh;
		end
	endfunction


	function automatic TrTrdstramwplowCsr_s pack_TrTrdstramwplowCsr;
		input TrTrdstramwplowCsrUnpack_s unpacked_csr;
		begin
			pack_TrTrdstramwplowCsr.Trdstramwrap = unpacked_csr.Trdstramwrap;
			pack_TrTrdstramwplowCsr.Trdstramwplow = unpacked_csr.Trdstramwplow;
		end
	endfunction


	function automatic TrTrdstramwphighCsr_s pack_TrTrdstramwphighCsr;
		input TrTrdstramwphighCsrUnpack_s unpacked_csr;
		begin
			pack_TrTrdstramwphighCsr.Trdstramwphigh = unpacked_csr.Trdstramwphigh;
		end
	endfunction


	function automatic TrTrdstramrplowCsr_s pack_TrTrdstramrplowCsr;
		input TrTrdstramrplowCsrUnpack_s unpacked_csr;
		begin
			pack_TrTrdstramrplowCsr.Rsvd10 = unpacked_csr.Rsvd10;
			pack_TrTrdstramrplowCsr.Trdstramrplow = unpacked_csr.Trdstramrplow;
		end
	endfunction


	function automatic TrTrdstramrphighCsr_s pack_TrTrdstramrphighCsr;
		input TrTrdstramrphighCsrUnpack_s unpacked_csr;
		begin
			pack_TrTrdstramrphighCsr.Trdstramrphigh = unpacked_csr.Trdstramrphigh;
		end
	endfunction


	function automatic TrTrdstramdataCsr_s pack_TrTrdstramdataCsr;
		input TrTrdstramdataCsrUnpack_s unpacked_csr;
		begin
			pack_TrTrdstramdataCsr.Trdstramdata = unpacked_csr.Trdstramdata;
		end
	endfunction


	function automatic TrTrclusterfusecfglowCsr_s pack_TrTrclusterfusecfglowCsr;
		input TrTrclusterfusecfglowCsrUnpack_s unpacked_csr;
		begin
			pack_TrTrclusterfusecfglowCsr.ScHarvestStrap = unpacked_csr.ScHarvestStrap;
			pack_TrTrclusterfusecfglowCsr.Rsvd98 = unpacked_csr.Rsvd98;
			pack_TrTrclusterfusecfglowCsr.ExportRestrictionEnabled = unpacked_csr.ExportRestrictionEnabled;
			pack_TrTrclusterfusecfglowCsr.IoCoherencyDisable = unpacked_csr.IoCoherencyDisable;
			pack_TrTrclusterfusecfglowCsr.Rsvd1512 = unpacked_csr.Rsvd1512;
			pack_TrTrclusterfusecfglowCsr.Core0Enable = unpacked_csr.Core0Enable;
			pack_TrTrclusterfusecfglowCsr.Core0Vid = unpacked_csr.Core0Vid;
			pack_TrTrclusterfusecfglowCsr.Core1Enable = unpacked_csr.Core1Enable;
			pack_TrTrclusterfusecfglowCsr.Core1Vid = unpacked_csr.Core1Vid;
			pack_TrTrclusterfusecfglowCsr.Core2Enable = unpacked_csr.Core2Enable;
			pack_TrTrclusterfusecfglowCsr.Core2Vid = unpacked_csr.Core2Vid;
			pack_TrTrclusterfusecfglowCsr.Core3Enable = unpacked_csr.Core3Enable;
			pack_TrTrclusterfusecfglowCsr.Core3Vid = unpacked_csr.Core3Vid;
		end
	endfunction


	function automatic TrTrclusterfusecfghiCsr_s pack_TrTrclusterfusecfghiCsr;
		input TrTrclusterfusecfghiCsrUnpack_s unpacked_csr;
		begin
			pack_TrTrclusterfusecfghiCsr.Core4Enable = unpacked_csr.Core4Enable;
			pack_TrTrclusterfusecfghiCsr.Core4Vid = unpacked_csr.Core4Vid;
			pack_TrTrclusterfusecfghiCsr.Core5Enable = unpacked_csr.Core5Enable;
			pack_TrTrclusterfusecfghiCsr.Core5Vid = unpacked_csr.Core5Vid;
			pack_TrTrclusterfusecfghiCsr.Core6Enable = unpacked_csr.Core6Enable;
			pack_TrTrclusterfusecfghiCsr.Core6Vid = unpacked_csr.Core6Vid;
			pack_TrTrclusterfusecfghiCsr.Core7Enable = unpacked_csr.Core7Enable;
			pack_TrTrclusterfusecfghiCsr.Core7Vid = unpacked_csr.Core7Vid;
			pack_TrTrclusterfusecfghiCsr.DebugEnable = unpacked_csr.DebugEnable;
			pack_TrTrclusterfusecfghiCsr.ClaEnable = unpacked_csr.ClaEnable;
			pack_TrTrclusterfusecfghiCsr.TraceEnable = unpacked_csr.TraceEnable;
			pack_TrTrclusterfusecfghiCsr.DstEnable = unpacked_csr.DstEnable;
			pack_TrTrclusterfusecfghiCsr.Jtag2UarchEnable = unpacked_csr.Jtag2UarchEnable;
			pack_TrTrclusterfusecfghiCsr.Rsvd3022 = unpacked_csr.Rsvd3022;
			pack_TrTrclusterfusecfghiCsr.Lock = unpacked_csr.Lock;
		end
	endfunction


	function automatic TrTrscratchloCsr_s pack_TrTrscratchloCsr;
		input TrTrscratchloCsrUnpack_s unpacked_csr;
		begin
			pack_TrTrscratchloCsr.Data = unpacked_csr.Data;
		end
	endfunction


	function automatic TrTrscratchhiCsr_s pack_TrTrscratchhiCsr;
		input TrTrscratchhiCsrUnpack_s unpacked_csr;
		begin
			pack_TrTrscratchhiCsr.Data = unpacked_csr.Data;
		end
	endfunction


	function automatic TrTrscratchpadloCsr_s pack_TrTrscratchpadloCsr;
		input TrTrscratchpadloCsrUnpack_s unpacked_csr;
		begin
			pack_TrTrscratchpadloCsr.Data = unpacked_csr.Data;
		end
	endfunction


	function automatic TrTrscratchpadhiCsr_s pack_TrTrscratchpadhiCsr;
		input TrTrscratchpadhiCsrUnpack_s unpacked_csr;
		begin
			pack_TrTrscratchpadhiCsr.Data = unpacked_csr.Data;
		end
	endfunction


endpackage

`endif
