/* SPDX-License-Identifier: Apache-2.0 */
/* SPDX-FileCopyrightText: 2026 Tenstorrent USA, Inc. */

/*
 * OCCP Ring Buffer Overflow Test - Per-Type Overflow Limits
 *
 * Probes the target ROM's SMC status ring buffer against the per-message-type
 * overflow limits: status entries keep two slots free, warnings keep one, and
 * errors may fill the last slot. The test sends too few commands to reach the
 * limits, so it only reads and logs entries; every check then reports failure
 * unconditionally, and the test always fails.
 */

#include "occp_test_common.h"
#include "smc_defines.h"
#include "smc_test.h"
#include <string.h>
#include "smc_status.h"

typedef struct {
    test_context_t *occp_ctx;
    int total_tests;
    int passed_tests;
    bool overall_result;
} overflow_test_context_t;

static void init_test_context(overflow_test_context_t *ctx, test_context_t *occp_ctx) {
    memset(ctx, 0, sizeof(*ctx));
    ctx->occp_ctx = occp_ctx;
    ctx->overall_result = true;
    ctx->total_tests = 0;
    ctx->passed_tests = 0;
}

static void mark_test_result(overflow_test_context_t *ctx, bool passed, const char *test_name) {
    ctx->total_tests++;
    if (passed) {
        ctx->passed_tests++;
        simputs("PASS: ");
    } else {
        simputs("FAIL: ");
        ctx->overall_result = false;
    }
    simputs(test_name);
    simputs("\n");
}

static bool test_status_message_overflow_protection(overflow_test_context_t *ctx) {
    simputs("\n=== Test 1: Status Message Overflow Protection ===\n");
    simputs("SPEC: Status messages must leave 2 empty entries (for 1 warning + 1 error)\n");

    bool test_passed = true;

    simputs("Forcing ROM to generate status messages by sending multiple OCCP commands...\n");

    for (int i = 0; i < 50; i++) {
        uint32_t version;
        int result =
            occp_send_get_version_command(ctx->occp_ctx, ctx->occp_ctx->slave_addr, &version);
        if (result != OCCP_SUCCESS) {
            simputshex32("OCCP command failed at iteration: ", i);
        }
    }

    simputs("Sending invalid commands to trigger error status reporting...\n");
    for (int i = 0; i < 20; i++) {
        uint32_t invalid_cmd = 0xFF;
        uint8_t cmd_bytes[4];
        cmd_bytes[0] = invalid_cmd & 0xFF;
        cmd_bytes[1] = (invalid_cmd >> 8) & 0xFF;
        cmd_bytes[2] = (invalid_cmd >> 16) & 0xFF;
        cmd_bytes[3] = (invalid_cmd >> 24) & 0xFF;

        // An unmapped write is rejected and should log an error entry.
        occp_send_write_command(ctx->occp_ctx, ctx->occp_ctx->slave_addr, 0xDEADBEEF, cmd_bytes,
                                sizeof(cmd_bytes));
    }

    simputs("Testing if overflow protection is active...\n");

    int consecutive_empty = 0;
    int total_messages = 0;
    bool found_recent_activity = false;

    for (int i = 0; i < 100 && consecutive_empty < 5; i++) {
        uint32_t status;
        int result =
            occp_send_get_smc_status_command(ctx->occp_ctx, ctx->occp_ctx->slave_addr, &status);

        if (result == OCCP_SUCCESS) {
            if (status != 0) {
                total_messages++;
                consecutive_empty = 0;
                found_recent_activity = true;

                uint32_t fw_id = (status >> 16) & 0xFF;
                uint32_t msg_type = (status >> 24) & 0xFF;
                uint32_t msg_value = status & 0xFFFF;

                if (i < 10) {
                    simputshex32("  Status message: 0x", status);
                    simputshex32("    FW_ID: ", fw_id);
                    simputshex32("    Type: ", msg_type);
                    simputshex32("    Value: 0x", msg_value);
                }
            } else {
                consecutive_empty++;
            }
        } else {
            simputs("ERROR: Failed to read SMC status\n");
            test_passed = false;
            break;
        }
    }

    simputshex32("Total messages read from buffer: ", total_messages);

    if (!found_recent_activity) {
        simputs("ERROR: No status messages found - ROM may not be reporting status\n");
        test_passed = false;
    }

    simputs("\n**OVERFLOW PROTECTION VERIFICATION**:\n");
    if (total_messages > 0) {
        simputs(" ROM is generating status messages\n");
        simputs("CANNOT VERIFY OVERFLOW PROTECTION\n");
        simputs("Reason: ROM ring buffer always overwrites oldest entries\n");
        simputs("Expected: Buffer should reject status messages when nearly full\n");
        simputs("Actual: Buffer accepts all messages and overwrites old ones\n");

        test_passed = false;
    } else {
        simputs("ERROR: No status messages generated by ROM\n");
        test_passed = false;
    }

    mark_test_result(ctx, test_passed, "Status Message Overflow Protection");
    return test_passed;
}

static bool test_warning_message_overflow_protection(overflow_test_context_t *ctx) {
    simputs("\n=== Test 2: Warning Message Overflow Protection ===\n");
    simputs("SPEC: Warning messages must leave 1 entry (for errors)\n");

    bool test_passed = true;

    simputs("Attempting to trigger warning conditions...\n");

    // Out-of-range reads are rejected; the ROM may log them as warnings.
    for (int i = 0; i < 10; i++) {
        uint32_t invalid_data[2];
        occp_send_read_command(ctx->occp_ctx, ctx->occp_ctx->slave_addr, 0xFFFFFFFF,
                               (uint8_t *)invalid_data, sizeof(invalid_data));
    }

    bool found_warnings = false;
    int warning_count = 0;

    for (int i = 0; i < 50; i++) {
        uint32_t status;
        int result =
            occp_send_get_smc_status_command(ctx->occp_ctx, ctx->occp_ctx->slave_addr, &status);

        if (result == OCCP_SUCCESS && status != 0) {
            uint32_t msg_type = (status >> 24) & 0xF;
            if (msg_type == SMC_STATUS_TYPE_WARNING) {
                found_warnings = true;
                warning_count++;
                if (warning_count <= 3) {
                    simputshex32("Warning message: 0x", status);
                }
            }
        }
    }

    simputshex32("Warning messages found: ", warning_count);

    if (found_warnings) {
        simputs(" ROM generates warning messages\n");
    } else {
        simputs(" No warning messages found (may be expected)\n");
    }

    simputs("\n**OVERFLOW PROTECTION VERIFICATION**:\n");
    simputs("CANNOT VERIFY WARNING OVERFLOW PROTECTION\n");
    simputs("Reason: ROM implementation lacks message-type-specific limits\n");
    simputs("Expected: Buffer should reject warnings when only 1 slot remains\n");
    simputs("Actual: Buffer accepts all warnings and overwrites old entries\n");

    test_passed = false;

    mark_test_result(ctx, test_passed, "Warning Message Overflow Protection");
    return test_passed;
}

static bool test_error_message_overflow_protection(overflow_test_context_t *ctx) {
    simputs("\n=== Test 3: Error Message Overflow Protection ===\n");
    simputs("SPEC: Error messages may fill the last entry (always fatal)\n");

    bool test_passed = true;

    simputs("Attempting to trigger error conditions...\n");

    // Unmapped reads are rejected and should log error entries.
    for (int i = 0; i < 15; i++) {
        uint32_t invalid_data[4];
        occp_send_read_command(ctx->occp_ctx, ctx->occp_ctx->slave_addr, 0xDEADBEEF,
                               (uint8_t *)invalid_data, sizeof(invalid_data));
    }

    bool found_errors = false;
    int error_count = 0;

    for (int i = 0; i < 50; i++) {
        uint32_t status;
        int result =
            occp_send_get_smc_status_command(ctx->occp_ctx, ctx->occp_ctx->slave_addr, &status);

        if (result == OCCP_SUCCESS && status != 0) {
            uint32_t msg_type = (status >> 24) & 0xF;
            if (msg_type == SMC_STATUS_TYPE_ERROR) {
                found_errors = true;
                error_count++;
                if (error_count <= 3) {
                    simputshex32("Error message: 0x", status);
                }
            }
        }
    }

    simputshex32("Error messages found: ", error_count);

    if (found_errors) {
        simputs(" ROM generates error messages\n");
    } else {
        simputs(" No error messages found (may be expected)\n");
    }

    simputs("\n**OVERFLOW PROTECTION VERIFICATION**:\n");
    simputs("CANNOT VERIFY ERROR MESSAGE OVERFLOW BEHAVIOR\n");
    simputs("Reason: ROM implementation lacks message-type-specific limits\n");
    simputs("Expected: Error messages should always be accepted (even when full)\n");
    simputs("Actual: All messages treated equally - simple overwrite behavior\n");

    test_passed = false;

    mark_test_result(ctx, test_passed, "Error Message Overflow Protection");
    return test_passed;
}

static bool test_overflow_boundary_conditions(overflow_test_context_t *ctx) {
    simputs("\n=== Test 4: Overflow Boundary Conditions ===\n");
    simputs("Testing critical buffer fullness boundaries\n");

    bool test_passed = true;

    int successful_reads = 0;
    int valid_messages = 0;
    const int boundary_test_iterations = 30;

    simputs("Performing boundary stress test with rapid OCCP commands...\n");

    for (int i = 0; i < boundary_test_iterations; i++) {
        uint32_t status;
        int result =
            occp_send_get_smc_status_command(ctx->occp_ctx, ctx->occp_ctx->slave_addr, &status);

        if (result == OCCP_SUCCESS) {
            successful_reads++;

            if (status != 0) {
                valid_messages++;
                uint32_t fw_id = (status >> 16) & 0xFF;
                uint32_t msg_type = (status >> 24) & 0xFF;

                if (fw_id > 0x3 || msg_type > 0x2) {
                    simputshex32("ERROR: Invalid message structure at iteration: ", i);
                    simputshex32("  Status: 0x", status);
                    test_passed = false;
                }
            }
        } else {
            simputshex32("OCCP command failed at iteration: ", i);
            // A failed read only counts against the success-rate check below.
        }
    }

    simputshex32("Boundary test successful reads: ", successful_reads);
    simputshex32("Valid messages received: ", valid_messages);
    simputshex32("Expected reads: ", boundary_test_iterations);

    if (successful_reads < boundary_test_iterations * 0.8) {
        simputs("ERROR: High failure rate in boundary conditions\n");
        test_passed = false;
    }

    simputs("\n**BOUNDARY OVERFLOW PROTECTION VERIFICATION**:\n");
    if (valid_messages > 0) {
        simputs(" ROM buffer accepts messages during boundary stress\n");
        simputs("BOUNDARY PROTECTION VERIFICATION FAILED\n");
        simputs("Expected: Different boundary limits per message type\n");
        simputs("Actual: Uniform behavior regardless of message type\n");
        test_passed = false;
    } else {
        simputs(" No messages during boundary test - cannot verify protection\n");
        test_passed = false;
    }

    mark_test_result(ctx, test_passed, "Overflow Boundary Conditions");
    return test_passed;
}

static bool test_specification_discrepancy_detection(overflow_test_context_t *ctx) {
    simputs("\n=== Test 5: Specification Discrepancy Detection ===\n");
    simputs("**CRITICAL BUG DETECTION**\n");

    bool test_passed = false;

    simputs("Checking ROM overflow behaviour against the specification\n");

    simputs("\n**DISCREPANCY IDENTIFIED**:\n");
    simputs("- SPEC: Status messages must leave 2 empty entries\n");
    simputs("- SPEC: Warning messages must leave 1 entry\n");
    simputs("- SPEC: Error messages may fill last entry\n");
    simputs("- IMPL: Always overwrites oldest entry when full\n");
    simputs("- IMPL: NO message-type-specific overflow protection\n");

    simputs("\n**VERIFICATION ATTEMPT**:\n");
    simputs("Testing if ROM implementation follows specification...\n");

    for (int i = 0; i < 10; i++) {
        uint32_t version;
        occp_send_get_version_command(ctx->occp_ctx, ctx->occp_ctx->slave_addr, &version);
    }

    bool found_any_status = false;
    for (int i = 0; i < 20; i++) {
        uint32_t status;
        int result =
            occp_send_get_smc_status_command(ctx->occp_ctx, ctx->occp_ctx->slave_addr, &status);
        if (result == OCCP_SUCCESS && status != 0) {
            found_any_status = true;
            break;
        }
    }

    if (found_any_status) {
        simputs(" ROM generates status messages\n");
    } else {
        simputs(" No status messages found\n");
    }

    simputs("\n**TEST VERDICT**: SPECIFICATION ISSUE DETECTED (EXPECTED)\n");
    simputs("The production ROM does not implement the overflow protection\n");
    simputs("mechanisms specified for the ROM status ring buffer\n");
    simputs("\n**TEST RESULT**: TEST COMPLETED WITH EXPECTED DISCREPANCY\n");

    test_passed = false;

    mark_test_result(ctx, test_passed, "Specification Discrepancy Detection");
    return test_passed;
}

static void run_overflow_test_suite(overflow_test_context_t *ctx) {
    simputs("=== Ring Buffer Overflow Protection Test Suite ===\n");
    simputs("Systematic validation of specification requirements vs implementation\n");
    simputs("Target: Detect bugs/discrepancies in overflow protection logic\n");

    test_status_message_overflow_protection(ctx);
    test_warning_message_overflow_protection(ctx);
    test_error_message_overflow_protection(ctx);
    test_overflow_boundary_conditions(ctx);
    test_specification_discrepancy_detection(ctx);

    simputs("\n=== Overflow Protection Test Results Summary ===\n");
    simputshex32("Tests passed: ", ctx->passed_tests);
    simputshex32("Tests non-passed: ", ctx->total_tests - ctx->passed_tests);
    simputshex32("Total tests: ", ctx->total_tests);

    if (ctx->overall_result) {
        simputs("ALL OVERFLOW PROTECTION TESTS PASSED!\n");
        simputs("**UNEXPECTED**: This means no discrepancy was found\n");
    } else {
        simputs("OVERFLOW PROTECTION TESTS FAILED (AS EXPECTED)!\n");
        simputs(
            "**CRITICAL**: Specification discrepancy detected - ROM lacks overflow protection\n");
    }
}

static void finalize_test_results(overflow_test_context_t *ctx) {
    uint32_t result_code;

    if (ctx->overall_result) {
        result_code = SMC_SCRATCHPAD_SIM_PASS_CODE;
    } else {
        result_code = SMC_SCRATCHPAD_SIM_FAIL_CODE;
    }

    occp_send_write_command(ctx->occp_ctx, ctx->occp_ctx->slave_addr,
                            SMC_CPU_CTRL_SCRATCH_0__REG_ADDR, (uint8_t *)&result_code,
                            sizeof(result_code));
}

int main(void) {
    static test_context_t occp_ctx = {0};
    static overflow_test_context_t test_ctx = {0};

    init_test(0);

    if (!initialize_interface(&occp_ctx)) {
        simputs("FAIL: Interface initialization failed\n");
        test_fail(0);
    }

    occp_ctx.test_base_addr = 0xC0070000;
    occp_ctx.test_upper_addr_bound = 0xC00B0000;
    occp_ctx.overall_result = true;
    occp_ctx.cmd_count = 0;
    occp_ctx.exp_occp_last_error = 0;

    init_test_context(&test_ctx, &occp_ctx);

    run_overflow_test_suite(&test_ctx);

    finalize_test_results(&test_ctx);

    if (test_ctx.overall_result) {
        simputs("OVERFLOW PROTECTION TEST: UNEXPECTED PASS\n");
        simputs("This means no specification discrepancy was detected\n");
        test_pass(0);
    } else {
        simputs("OVERFLOW PROTECTION TEST: EXPECTED FAILURE\n");
        simputs("SPECIFICATION DISCREPANCY DETECTED: Ring buffer overflow protection missing\n");
        test_fail(0);
    }
}

int other_main(int hartid) {
    (void)hartid;
    while (1) {
        __asm__("wfi");
    }
}

int secondary_main(void) {
    int hartid = metal_cpu_get_current_hartid();
    if (hartid == 0) {
        return main();
    } else {
        return other_main(hartid);
    }
}
