// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 Tenstorrent USA, Inc.

// Sequence SMC reset-unit register controls into reset trees.
//
// Decodes reset-unit register writes into reset_ctrl_t holds and force-to-ref-clk.
// Orders warm and cold assertion so domain resets release in a defined sequence.

module smc_reset_ctrl (
  input  logic                                   clk_ref_i,  // Ref clock.
  input  logic                                   powergood_i,  // Powergood signal from
                                                               // the pad (BP_POWERGOOD).

  input  logic                                   rst_cold_ni,  // Cold reset signal from
                                                               // the pad (BP_RESETN).

  input  logic                                   fuse_reset_ni,  // Fuse reset signal,
                                                                 // asserted after fuse
                                                                 // sensing is done and
                                                                 // DFT is complete.

  input  logic                                   rst_ext_wdt_ni,  // Other watchdog
                                                                  // timers.
  input  logic                                   smc_wdt_first_timeout_i,  // Smc wdt first
                                                                           // timeout.
  input  logic                                   smc_wdt_second_timeout_i,  // Smc wdt second
                                                                            // timeout.

  input  logic                                   rst_cool_from_pin_ni,  // Received by
                                                                        // secondary chiplets.
  input  logic                                   rst_cool_from_flr_ni,  // Generated by primary
                                                                        // chiplets and sent to
                                                                        // secondary chiplets.

  output logic                                   powergood_stable_o,  // Stable powergood
                                                                      // signal.
  output logic                                   stable_cold_rst_no,  // Stable cold reset
                                                                      // signal.
  output logic                                   rst_primary_no,  // Primary reset signal.
  output logic                                   rst_warm_no,  // Warm reset signal.
  output logic                                   rst_wdt_no,  // WDT reset signal.

  input  logic                                   test_en_i,  // Test en.
  input  logic                                   scan_rst_ni  // Scan rst.
);

  // Reset de-glitcher parameters
  localparam int unsigned RESET_DEGLITCH_WIDTH = 32;

  logic powergood_stable;
  logic cold_rst_pre_extend;
  logic cold_rst_deglitch_to_rstbypass;
  logic stable_cold_rst_n;
  logic stable_cool_rst_n;

  ///////////////////////////////
  // Powergood Stretch Circuit //
  ///////////////////////////////

  // Note: in simulation, an X/Z on powergood_i makes the synchronizer's async-reset
  // condition evaluate as false, so the chain shifts in 1s and powergood_stable resolves
  // to 1. This is safe in practice: if power is not actually stable there is no clk_ref_i
  // to clock that 1 through the synchronizer.

  // Wait 32 cycles after power good de-assertion before broadcasting to rest of chip
  prim_sync_reset #(
    .WIDTH(32)
  ) u_powergood_stretcher_n0_scan (
    .clk_i(clk_ref_i),
    .rst_ni(powergood_i),
    .test_mode_i(test_en_i),
    .scan_rst_ni(scan_rst_ni),
    .sync_rst_no(powergood_stable)
  );

  /////////////////////////////////////////////////////////////////////////////////////////////
  // COLD reset de-glitcher circuit
  // Only assert reset downstream when it has been seen for at least 32 refclk cycles == 320ns
  /////////////////////////////////////////////////////////////////////////////////////////////
  logic [RESET_DEGLITCH_WIDTH-1:0] cold_rst_deglitch_shift_reg_n0_scan;

  always @(posedge clk_ref_i or negedge powergood_stable) begin
    if (~powergood_stable) begin
      cold_rst_deglitch_shift_reg_n0_scan <= '0;
      cold_rst_deglitch_to_rstbypass      <= 1'b0;
    end else begin
      cold_rst_deglitch_shift_reg_n0_scan <= {
        cold_rst_deglitch_shift_reg_n0_scan[RESET_DEGLITCH_WIDTH-2:0], rst_cold_ni
      };
      cold_rst_deglitch_to_rstbypass <= |{
        cold_rst_deglitch_shift_reg_n0_scan[RESET_DEGLITCH_WIDTH-2:0], rst_cold_ni
      };
    end
  end

  prim_rst_mux2_hf_n u_cold_rst_pre_extend_rstbypass (
    .rst0_ni(cold_rst_deglitch_to_rstbypass),
    .rst1_ni(scan_rst_ni),
    .sel_i  (test_en_i),
    .rst_no (cold_rst_pre_extend)
  );

  // Cold reset extender circuit
  // When powergood_stable is 1, hold reset_n to 0 for 255 cycles after it is de-asserted
  localparam int unsigned RESET_EXTEND_DURATION = 255;
  localparam int unsigned EXTEND_COUNT_WIDTH = $clog2(RESET_EXTEND_DURATION + 1);
  logic [EXTEND_COUNT_WIDTH-1:0] extend_count_n0_scan;

  always @(posedge clk_ref_i or negedge cold_rst_pre_extend) begin
    if (~cold_rst_pre_extend) begin
      extend_count_n0_scan <= RESET_EXTEND_DURATION;
    end else begin
      if (powergood_stable && (|extend_count_n0_scan)) begin
        extend_count_n0_scan <= extend_count_n0_scan - {{(EXTEND_COUNT_WIDTH - 1) {1'b0}}, 1'b1};
      end
    end
  end

  always_comb begin
    stable_cold_rst_n = 1'b0;
    if (powergood_stable) begin
      if (~(|extend_count_n0_scan)) begin
        stable_cold_rst_n = cold_rst_pre_extend;
      end
    end
  end

  /////////////////////////////////////////////////////////////////////////////////////////////
  // COOL reset de-glitcher circuit
  /////////////////////////////////////////////////////////////////////////////////////////////
  logic [RESET_DEGLITCH_WIDTH-1:0] cool_rst_deglitch_shift_reg_n0_scan;

  always @(posedge clk_ref_i or negedge powergood_stable) begin
    if (~powergood_stable) begin
      cool_rst_deglitch_shift_reg_n0_scan <= '0;
      stable_cool_rst_n                   <= 1'b0;
    end else begin
      cool_rst_deglitch_shift_reg_n0_scan <= {
        cool_rst_deglitch_shift_reg_n0_scan[RESET_DEGLITCH_WIDTH-2:0], rst_cool_from_pin_ni
      };
      stable_cool_rst_n <= |{
        cool_rst_deglitch_shift_reg_n0_scan[RESET_DEGLITCH_WIDTH-2:0],
        rst_cool_from_pin_ni
      };
    end
  end

  // Final reset outputs
  logic smc_wdt_second_timeout_n;
  logic wdt_reset_n;
  logic rst_primary_cold_cool_n;
  logic rst_warm_wdt_primary_n;

  prim_inv u_smc_wdt_timeout_inv (
    .in_i  (smc_wdt_second_timeout_i),
    .out_o (smc_wdt_second_timeout_n)
  );

  prim_and2 #(
    .Width(1)
  ) u_smc_wdt_reset_and (
    .in0_i (rst_ext_wdt_ni),
    .in1_i (smc_wdt_second_timeout_n),
    .out_o (wdt_reset_n)
  );

  prim_and2 #(
    .Width(1)
  ) u_rst_primary_cold_cool_and (
    .in0_i (stable_cold_rst_n),
    .in1_i (stable_cool_rst_n),
    .out_o (rst_primary_cold_cool_n)
  );

  prim_and2 #(
    .Width(1)
  ) u_rst_primary_flr_and (
    .in0_i (rst_primary_cold_cool_n),
    .in1_i (rst_cool_from_flr_ni),
    .out_o (rst_primary_no)
  );

  prim_and2 #(
    .Width(1)
  ) u_rst_warm_wdt_primary_and (
    .in0_i (wdt_reset_n),
    .in1_i (rst_primary_no),
    .out_o (rst_warm_wdt_primary_n)
  );

  prim_and2 #(
    .Width(1)
  ) u_rst_warm_fuse_and (
    .in0_i (rst_warm_wdt_primary_n),
    .in1_i (fuse_reset_ni),
    .out_o (rst_warm_no)
  );

  assign rst_wdt_no = wdt_reset_n;

  assign stable_cold_rst_no = stable_cold_rst_n;
  assign powergood_stable_o = powergood_stable;

endmodule
