# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2026 Tenstorrent USA, Inc.
################################################################################
# smc_cdc_max_delay_generated.tcl - GENERATED, do not hand-edit
#
# One call per CDC element in the SMC design, enumerated offline against the
# elaborated netlist. The procs it calls come from
# flows/synth/constraints/cdc_max_delay_procs.tcl; constraints.sdc sources both.
#
# Paths and clock names are OCAH's. To apply this file to a design that
# instantiates the block elsewhere, or drives it from differently named clocks,
# set ::cdc_hier_prefix / ::cdc_clock_alias rather than editing here.
#
# Regeneration runs in the closed synthesis flow, not here, and is needed only
# when the block is reconfigured such that the set of CDC elements changes. The
# file goes stale silently in that case - nothing warns about an element that
# was never listed. Hand-written overrides belong in smc_cdc_max_delay.tcl,
# which sources this file.
################################################################################

# Hierarchical instance paths below run past 100 characters and cannot be wrapped:
# a Tcl word does not survive a line break. Brace-quoted words keep a trailing
# backslash-newline literal, and inside quotes it collapses to a space, either way
# corrupting the path. Only the length rule is disabled; the rest still apply.
# tclint-disable line-length


# ---- prim_sync2r (6 instances) ----
set_cdc_max_delay_prim_sync2 {u_smc_peripherals/telemetry_receiver_wrap/gen_telemetry_receivers[0].afready_sync2r} TELEMETRYCLK
set_cdc_max_delay_prim_sync2 {u_smc_peripherals/telemetry_receiver_wrap/gen_telemetry_receivers[0].afvalid_sync2r} SMCCLK
set_cdc_max_delay_prim_sync2 {u_smc_peripherals/telemetry_receiver_wrap/gen_telemetry_receivers[1].afready_sync2r} TELEMETRYCLK
set_cdc_max_delay_prim_sync2 {u_smc_peripherals/telemetry_receiver_wrap/gen_telemetry_receivers[1].afvalid_sync2r} SMCCLK
set_cdc_max_delay_prim_sync2 {u_smc_peripherals/telemetry_receiver_wrap/gen_telemetry_receivers[2].afready_sync2r} TELEMETRYCLK
set_cdc_max_delay_prim_sync2 {u_smc_peripherals/telemetry_receiver_wrap/gen_telemetry_receivers[2].afvalid_sync2r} SMCCLK

# ---- prim_sync3 (51 instances) ----
set_cdc_max_delay_prim_sync3 u_smc_base/u_ext_debug_bus_sync3 SMCCLK
set_cdc_max_delay_prim_sync3 u_smc_base/u_ext_interrupts_sync3 SMCCLK
set_cdc_max_delay_prim_sync3 u_smc_cpu_wrapper/u_smc_cpu_ctrl_wrap/refclk_counter/sync_cnt_en_count REFCLK
set_cdc_max_delay_prim_sync3 u_smc_cpu_wrapper/u_smc_cpu_ctrl_wrap/refclk_counter/sync_ref_count SMCCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/avsbus_controller/cmd_async_fifo_inst/rd_ptr_gray_sync_to_wr_clk[0]} PERIPHERALCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/avsbus_controller/cmd_async_fifo_inst/rd_ptr_gray_sync_to_wr_clk[1]} PERIPHERALCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/avsbus_controller/cmd_async_fifo_inst/rd_ptr_gray_sync_to_wr_clk[2]} PERIPHERALCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/avsbus_controller/cmd_async_fifo_inst/rd_ptr_gray_sync_to_wr_clk[3]} PERIPHERALCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/avsbus_controller/cmd_async_fifo_inst/wr_ptr_gray_sync_to_rd_clk[0]} {AVS_CLK_DIV_CLK_O_FROM_PERIPHERALCLK AVS_CLK_DIV_CLK_O_FROM_REFCLK}
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/avsbus_controller/cmd_async_fifo_inst/wr_ptr_gray_sync_to_rd_clk[1]} {AVS_CLK_DIV_CLK_O_FROM_PERIPHERALCLK AVS_CLK_DIV_CLK_O_FROM_REFCLK}
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/avsbus_controller/cmd_async_fifo_inst/wr_ptr_gray_sync_to_rd_clk[2]} {AVS_CLK_DIV_CLK_O_FROM_PERIPHERALCLK AVS_CLK_DIV_CLK_O_FROM_REFCLK}
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/avsbus_controller/cmd_async_fifo_inst/wr_ptr_gray_sync_to_rd_clk[3]} {AVS_CLK_DIV_CLK_O_FROM_PERIPHERALCLK AVS_CLK_DIV_CLK_O_FROM_REFCLK}
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/avsbus_controller/readasync_back_fifo_inst/rd_ptr_gray_sync_to_wr_clk[0]} {AVS_CLK_DIV_CLK_O_FROM_PERIPHERALCLK AVS_CLK_DIV_CLK_O_FROM_REFCLK}
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/avsbus_controller/readasync_back_fifo_inst/rd_ptr_gray_sync_to_wr_clk[1]} {AVS_CLK_DIV_CLK_O_FROM_PERIPHERALCLK AVS_CLK_DIV_CLK_O_FROM_REFCLK}
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/avsbus_controller/readasync_back_fifo_inst/rd_ptr_gray_sync_to_wr_clk[2]} {AVS_CLK_DIV_CLK_O_FROM_PERIPHERALCLK AVS_CLK_DIV_CLK_O_FROM_REFCLK}
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/avsbus_controller/readasync_back_fifo_inst/rd_ptr_gray_sync_to_wr_clk[3]} {AVS_CLK_DIV_CLK_O_FROM_PERIPHERALCLK AVS_CLK_DIV_CLK_O_FROM_REFCLK}
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/avsbus_controller/readasync_back_fifo_inst/wr_ptr_gray_sync_to_rd_clk[0]} PERIPHERALCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/avsbus_controller/readasync_back_fifo_inst/wr_ptr_gray_sync_to_rd_clk[1]} PERIPHERALCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/avsbus_controller/readasync_back_fifo_inst/wr_ptr_gray_sync_to_rd_clk[2]} PERIPHERALCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/avsbus_controller/readasync_back_fifo_inst/wr_ptr_gray_sync_to_rd_clk[3]} PERIPHERALCLK
set_cdc_max_delay_prim_sync3 u_smc_peripherals/avsbus_controller/u_avs_readback_en_resync PERIPHERALCLK
set_cdc_max_delay_prim_sync3 u_smc_peripherals/avsbus_controller/u_gate_refclk_en_sync REFCLK
set_cdc_max_delay_prim_sync3 u_smc_peripherals/avsbus_controller/u_idle_clk_reg_resync {AVS_CLK_DIV_CLK_O_FROM_PERIPHERALCLK AVS_CLK_DIV_CLK_O_FROM_REFCLK}
set_cdc_max_delay_prim_sync3 u_smc_peripherals/avsbus_controller/u_max_retries_attempted_resync PERIPHERALCLK
set_cdc_max_delay_prim_sync3 u_smc_peripherals/avsbus_controller/u_readback_fifo_full_resync PERIPHERALCLK
set_cdc_max_delay_prim_sync3 u_smc_peripherals/avsbus_controller/u_slave_interrupt_resync PERIPHERALCLK
set_cdc_max_delay_prim_sync3 u_smc_peripherals/avsbus_controller/u_slave_resync_pending_resync {AVS_CLK_DIV_CLK_O_FROM_PERIPHERALCLK AVS_CLK_DIV_CLK_O_FROM_REFCLK}
set_cdc_max_delay_prim_sync3 u_smc_peripherals/avsbus_controller/u_slave_unresponsive_resync PERIPHERALCLK
set_cdc_max_delay_prim_sync3 u_smc_peripherals/u_boot_stall_combined_sync SMCCLK
set_cdc_max_delay_prim_sync3 u_smc_peripherals/u_rst_ext_wdt_irq_sync SMCCLK
set_cdc_max_delay_prim_sync3 u_smc_peripherals/u_smc_peripherals_cdc/gen_sync3.u_avs_cg_en_periph_sync PERIPHERALCLK
set_cdc_max_delay_prim_sync3 u_smc_peripherals/u_smc_peripherals_cdc/gen_sync3.u_avs_cg_en_ref_sync REFCLK
set_cdc_max_delay_prim_sync3 u_smc_peripherals/u_smc_peripherals_cdc/gen_sync3.u_avsbus_irq_sync SMCCLK
set_cdc_max_delay_prim_sync3 u_smc_peripherals/u_smc_peripherals_cdc/gen_sync3.u_i2c_cg_en_sync PERIPHERALCLK
set_cdc_max_delay_prim_sync3 u_smc_peripherals/u_smc_peripherals_cdc/gen_sync3.u_i2c_debug_sync SMCCLK
set_cdc_max_delay_prim_sync3 u_smc_peripherals/u_smc_peripherals_cdc/gen_sync3.u_i2c_enable_sync SMCCLK
set_cdc_max_delay_prim_sync3 u_smc_peripherals/u_smc_peripherals_cdc/gen_sync3.u_i2c_irq_sync SMCCLK
set_cdc_max_delay_prim_sync3 u_smc_peripherals/u_smc_peripherals_cdc/gen_sync3.u_i3c_cg_en_sync PERIPHERALCLK
set_cdc_max_delay_prim_sync3 u_smc_peripherals/u_smc_peripherals_cdc/gen_sync3.u_i3c_irq_sync SMCCLK
set_cdc_max_delay_prim_sync3 u_smc_peripherals/u_smc_peripherals_cdc/gen_sync3.u_tel_cg_en_sync TELEMETRYCLK
set_cdc_max_delay_prim_sync3 u_smc_peripherals/u_smc_peripherals_cdc/gen_sync3.u_uart_cg_en_sync PERIPHERALCLK
set_cdc_max_delay_prim_sync3 u_smc_peripherals/u_smc_peripherals_cdc/gen_sync3.u_uart_combined_irq_sync SMCCLK
set_cdc_max_delay_prim_sync3 u_smc_peripherals/u_smc_peripherals_cdc/gen_sync3.u_uart_enable_sync SMCCLK
set_cdc_max_delay_prim_sync3 u_smc_peripherals/u_smc_peripherals_cdc/u_ndmreset_request_sync SMCCLK
set_cdc_max_delay_prim_sync3 u_smc_peripherals/u_smc_reset_unit/u_smc_cool_reset_wrap/u_cfg_flr_pf_active_sync_ref REFCLK
set_cdc_max_delay_prim_sync3 u_smc_peripherals/u_smc_reset_unit/u_smc_cool_reset_wrap/u_cfg_flr_pf_active_sync_smc SMCCLK
set_cdc_max_delay_prim_sync3 u_smc_peripherals/u_smc_reset_unit/u_smc_cool_reset_wrap/u_isolate_req_pin_sync SMCCLK
set_cdc_max_delay_prim_sync3 u_smc_peripherals/u_smc_reset_unit/u_smc_cool_reset_wrap/u_rst_cool_ni_sync_smc SMCCLK
set_cdc_max_delay_prim_sync3 u_smc_peripherals/u_smc_reset_unit/u_smc_cool_reset_wrap/u_rst_cool_no_sync_smc SMCCLK
set_cdc_max_delay_prim_sync3 u_smc_peripherals/u_smc_reset_unit/u_smc_subsystem_resets/u_reset_complete_sync SMCCLK

# ---- prim_sync3r (166 instances) ----
set_cdc_max_delay_prim_sync3 u_smc_base/u_internal_regs/u_smc_dfd_wrap/ref_clk_sync SMCCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_padring/gen_gpio_intf[0].u_gpio_interface/pad2core_sync} SMCCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_padring/gen_gpio_intf[10].u_gpio_interface/pad2core_sync} SMCCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_padring/gen_gpio_intf[11].u_gpio_interface/pad2core_sync} SMCCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_padring/gen_gpio_intf[12].u_gpio_interface/pad2core_sync} SMCCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_padring/gen_gpio_intf[13].u_gpio_interface/pad2core_sync} SMCCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_padring/gen_gpio_intf[14].u_gpio_interface/pad2core_sync} SMCCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_padring/gen_gpio_intf[15].u_gpio_interface/pad2core_sync} SMCCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_padring/gen_gpio_intf[16].u_gpio_interface/pad2core_sync} SMCCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_padring/gen_gpio_intf[17].u_gpio_interface/pad2core_sync} SMCCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_padring/gen_gpio_intf[18].u_gpio_interface/pad2core_sync} SMCCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_padring/gen_gpio_intf[19].u_gpio_interface/pad2core_sync} SMCCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_padring/gen_gpio_intf[1].u_gpio_interface/pad2core_sync} SMCCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_padring/gen_gpio_intf[20].u_gpio_interface/pad2core_sync} SMCCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_padring/gen_gpio_intf[21].u_gpio_interface/pad2core_sync} SMCCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_padring/gen_gpio_intf[22].u_gpio_interface/pad2core_sync} SMCCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_padring/gen_gpio_intf[23].u_gpio_interface/pad2core_sync} SMCCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_padring/gen_gpio_intf[24].u_gpio_interface/pad2core_sync} SMCCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_padring/gen_gpio_intf[25].u_gpio_interface/pad2core_sync} SMCCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_padring/gen_gpio_intf[26].u_gpio_interface/pad2core_sync} SMCCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_padring/gen_gpio_intf[27].u_gpio_interface/pad2core_sync} SMCCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_padring/gen_gpio_intf[28].u_gpio_interface/pad2core_sync} SMCCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_padring/gen_gpio_intf[29].u_gpio_interface/pad2core_sync} SMCCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_padring/gen_gpio_intf[2].u_gpio_interface/pad2core_sync} SMCCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_padring/gen_gpio_intf[30].u_gpio_interface/pad2core_sync} SMCCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_padring/gen_gpio_intf[31].u_gpio_interface/pad2core_sync} SMCCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_padring/gen_gpio_intf[32].u_gpio_interface/pad2core_sync} SMCCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_padring/gen_gpio_intf[33].u_gpio_interface/pad2core_sync} SMCCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_padring/gen_gpio_intf[34].u_gpio_interface/pad2core_sync} SMCCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_padring/gen_gpio_intf[35].u_gpio_interface/pad2core_sync} SMCCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_padring/gen_gpio_intf[36].u_gpio_interface/pad2core_sync} SMCCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_padring/gen_gpio_intf[37].u_gpio_interface/pad2core_sync} SMCCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_padring/gen_gpio_intf[38].u_gpio_interface/pad2core_sync} SMCCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_padring/gen_gpio_intf[39].u_gpio_interface/pad2core_sync} SMCCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_padring/gen_gpio_intf[3].u_gpio_interface/pad2core_sync} SMCCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_padring/gen_gpio_intf[40].u_gpio_interface/pad2core_sync} SMCCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_padring/gen_gpio_intf[41].u_gpio_interface/pad2core_sync} SMCCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_padring/gen_gpio_intf[42].u_gpio_interface/pad2core_sync} SMCCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_padring/gen_gpio_intf[43].u_gpio_interface/pad2core_sync} SMCCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_padring/gen_gpio_intf[44].u_gpio_interface/pad2core_sync} SMCCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_padring/gen_gpio_intf[45].u_gpio_interface/pad2core_sync} SMCCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_padring/gen_gpio_intf[46].u_gpio_interface/pad2core_sync} SMCCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_padring/gen_gpio_intf[47].u_gpio_interface/pad2core_sync} SMCCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_padring/gen_gpio_intf[48].u_gpio_interface/pad2core_sync} SMCCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_padring/gen_gpio_intf[49].u_gpio_interface/pad2core_sync} SMCCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_padring/gen_gpio_intf[4].u_gpio_interface/pad2core_sync} SMCCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_padring/gen_gpio_intf[50].u_gpio_interface/pad2core_sync} SMCCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_padring/gen_gpio_intf[51].u_gpio_interface/pad2core_sync} SMCCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_padring/gen_gpio_intf[52].u_gpio_interface/pad2core_sync} SMCCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_padring/gen_gpio_intf[53].u_gpio_interface/pad2core_sync} SMCCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_padring/gen_gpio_intf[54].u_gpio_interface/pad2core_sync} SMCCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_padring/gen_gpio_intf[55].u_gpio_interface/pad2core_sync} SMCCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_padring/gen_gpio_intf[56].u_gpio_interface/pad2core_sync} SMCCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_padring/gen_gpio_intf[57].u_gpio_interface/pad2core_sync} SMCCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_padring/gen_gpio_intf[58].u_gpio_interface/pad2core_sync} SMCCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_padring/gen_gpio_intf[59].u_gpio_interface/pad2core_sync} SMCCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_padring/gen_gpio_intf[5].u_gpio_interface/pad2core_sync} SMCCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_padring/gen_gpio_intf[60].u_gpio_interface/pad2core_sync} SMCCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_padring/gen_gpio_intf[61].u_gpio_interface/pad2core_sync} SMCCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_padring/gen_gpio_intf[62].u_gpio_interface/pad2core_sync} SMCCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_padring/gen_gpio_intf[63].u_gpio_interface/pad2core_sync} SMCCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_padring/gen_gpio_intf[64].u_gpio_interface/pad2core_sync} SMCCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_padring/gen_gpio_intf[6].u_gpio_interface/pad2core_sync} SMCCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_padring/gen_gpio_intf[7].u_gpio_interface/pad2core_sync} SMCCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_padring/gen_gpio_intf[8].u_gpio_interface/pad2core_sync} SMCCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_padring/gen_gpio_intf[9].u_gpio_interface/pad2core_sync} SMCCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_peripherals_cdc/u_avsbus_axi_cdc/i_axi_cdc_dst/i_cdc_fifo_gray_dst_ar/gen_sync[0].i_sync/gen_tt_sync3_async_clr.prim_sync3r} PERIPHERALCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_peripherals_cdc/u_avsbus_axi_cdc/i_axi_cdc_dst/i_cdc_fifo_gray_dst_ar/gen_sync[1].i_sync/gen_tt_sync3_async_clr.prim_sync3r} PERIPHERALCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_peripherals_cdc/u_avsbus_axi_cdc/i_axi_cdc_dst/i_cdc_fifo_gray_dst_aw/gen_sync[0].i_sync/gen_tt_sync3_async_clr.prim_sync3r} PERIPHERALCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_peripherals_cdc/u_avsbus_axi_cdc/i_axi_cdc_dst/i_cdc_fifo_gray_dst_aw/gen_sync[1].i_sync/gen_tt_sync3_async_clr.prim_sync3r} PERIPHERALCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_peripherals_cdc/u_avsbus_axi_cdc/i_axi_cdc_dst/i_cdc_fifo_gray_dst_w/gen_sync[0].i_sync/gen_tt_sync3_async_clr.prim_sync3r} PERIPHERALCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_peripherals_cdc/u_avsbus_axi_cdc/i_axi_cdc_dst/i_cdc_fifo_gray_dst_w/gen_sync[1].i_sync/gen_tt_sync3_async_clr.prim_sync3r} PERIPHERALCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_peripherals_cdc/u_avsbus_axi_cdc/i_axi_cdc_dst/i_cdc_fifo_gray_src_b/gen_sync[0].i_sync/gen_tt_sync3_async_clr.prim_sync3r} PERIPHERALCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_peripherals_cdc/u_avsbus_axi_cdc/i_axi_cdc_dst/i_cdc_fifo_gray_src_b/gen_sync[1].i_sync/gen_tt_sync3_async_clr.prim_sync3r} PERIPHERALCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_peripherals_cdc/u_avsbus_axi_cdc/i_axi_cdc_dst/i_cdc_fifo_gray_src_r/gen_sync[0].i_sync/gen_tt_sync3_async_clr.prim_sync3r} PERIPHERALCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_peripherals_cdc/u_avsbus_axi_cdc/i_axi_cdc_dst/i_cdc_fifo_gray_src_r/gen_sync[1].i_sync/gen_tt_sync3_async_clr.prim_sync3r} PERIPHERALCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_peripherals_cdc/u_avsbus_axi_cdc/i_axi_cdc_src/i_cdc_fifo_gray_dst_b/gen_sync[0].i_sync/gen_tt_sync3_async_clr.prim_sync3r} SMCCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_peripherals_cdc/u_avsbus_axi_cdc/i_axi_cdc_src/i_cdc_fifo_gray_dst_b/gen_sync[1].i_sync/gen_tt_sync3_async_clr.prim_sync3r} SMCCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_peripherals_cdc/u_avsbus_axi_cdc/i_axi_cdc_src/i_cdc_fifo_gray_dst_r/gen_sync[0].i_sync/gen_tt_sync3_async_clr.prim_sync3r} SMCCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_peripherals_cdc/u_avsbus_axi_cdc/i_axi_cdc_src/i_cdc_fifo_gray_dst_r/gen_sync[1].i_sync/gen_tt_sync3_async_clr.prim_sync3r} SMCCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_peripherals_cdc/u_avsbus_axi_cdc/i_axi_cdc_src/i_cdc_fifo_gray_src_ar/gen_sync[0].i_sync/gen_tt_sync3_async_clr.prim_sync3r} SMCCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_peripherals_cdc/u_avsbus_axi_cdc/i_axi_cdc_src/i_cdc_fifo_gray_src_ar/gen_sync[1].i_sync/gen_tt_sync3_async_clr.prim_sync3r} SMCCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_peripherals_cdc/u_avsbus_axi_cdc/i_axi_cdc_src/i_cdc_fifo_gray_src_aw/gen_sync[0].i_sync/gen_tt_sync3_async_clr.prim_sync3r} SMCCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_peripherals_cdc/u_avsbus_axi_cdc/i_axi_cdc_src/i_cdc_fifo_gray_src_aw/gen_sync[1].i_sync/gen_tt_sync3_async_clr.prim_sync3r} SMCCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_peripherals_cdc/u_avsbus_axi_cdc/i_axi_cdc_src/i_cdc_fifo_gray_src_w/gen_sync[0].i_sync/gen_tt_sync3_async_clr.prim_sync3r} SMCCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_peripherals_cdc/u_avsbus_axi_cdc/i_axi_cdc_src/i_cdc_fifo_gray_src_w/gen_sync[1].i_sync/gen_tt_sync3_async_clr.prim_sync3r} SMCCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_peripherals_cdc/u_i2c_axi_cdc/i_axi_cdc_dst/i_cdc_fifo_gray_dst_ar/gen_sync[0].i_sync/gen_tt_sync3_async_clr.prim_sync3r} PERIPHERALCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_peripherals_cdc/u_i2c_axi_cdc/i_axi_cdc_dst/i_cdc_fifo_gray_dst_ar/gen_sync[1].i_sync/gen_tt_sync3_async_clr.prim_sync3r} PERIPHERALCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_peripherals_cdc/u_i2c_axi_cdc/i_axi_cdc_dst/i_cdc_fifo_gray_dst_aw/gen_sync[0].i_sync/gen_tt_sync3_async_clr.prim_sync3r} PERIPHERALCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_peripherals_cdc/u_i2c_axi_cdc/i_axi_cdc_dst/i_cdc_fifo_gray_dst_aw/gen_sync[1].i_sync/gen_tt_sync3_async_clr.prim_sync3r} PERIPHERALCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_peripherals_cdc/u_i2c_axi_cdc/i_axi_cdc_dst/i_cdc_fifo_gray_dst_w/gen_sync[0].i_sync/gen_tt_sync3_async_clr.prim_sync3r} PERIPHERALCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_peripherals_cdc/u_i2c_axi_cdc/i_axi_cdc_dst/i_cdc_fifo_gray_dst_w/gen_sync[1].i_sync/gen_tt_sync3_async_clr.prim_sync3r} PERIPHERALCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_peripherals_cdc/u_i2c_axi_cdc/i_axi_cdc_dst/i_cdc_fifo_gray_src_b/gen_sync[0].i_sync/gen_tt_sync3_async_clr.prim_sync3r} PERIPHERALCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_peripherals_cdc/u_i2c_axi_cdc/i_axi_cdc_dst/i_cdc_fifo_gray_src_b/gen_sync[1].i_sync/gen_tt_sync3_async_clr.prim_sync3r} PERIPHERALCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_peripherals_cdc/u_i2c_axi_cdc/i_axi_cdc_dst/i_cdc_fifo_gray_src_r/gen_sync[0].i_sync/gen_tt_sync3_async_clr.prim_sync3r} PERIPHERALCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_peripherals_cdc/u_i2c_axi_cdc/i_axi_cdc_dst/i_cdc_fifo_gray_src_r/gen_sync[1].i_sync/gen_tt_sync3_async_clr.prim_sync3r} PERIPHERALCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_peripherals_cdc/u_i2c_axi_cdc/i_axi_cdc_src/i_cdc_fifo_gray_dst_b/gen_sync[0].i_sync/gen_tt_sync3_async_clr.prim_sync3r} SMCCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_peripherals_cdc/u_i2c_axi_cdc/i_axi_cdc_src/i_cdc_fifo_gray_dst_b/gen_sync[1].i_sync/gen_tt_sync3_async_clr.prim_sync3r} SMCCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_peripherals_cdc/u_i2c_axi_cdc/i_axi_cdc_src/i_cdc_fifo_gray_dst_r/gen_sync[0].i_sync/gen_tt_sync3_async_clr.prim_sync3r} SMCCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_peripherals_cdc/u_i2c_axi_cdc/i_axi_cdc_src/i_cdc_fifo_gray_dst_r/gen_sync[1].i_sync/gen_tt_sync3_async_clr.prim_sync3r} SMCCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_peripherals_cdc/u_i2c_axi_cdc/i_axi_cdc_src/i_cdc_fifo_gray_src_ar/gen_sync[0].i_sync/gen_tt_sync3_async_clr.prim_sync3r} SMCCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_peripherals_cdc/u_i2c_axi_cdc/i_axi_cdc_src/i_cdc_fifo_gray_src_ar/gen_sync[1].i_sync/gen_tt_sync3_async_clr.prim_sync3r} SMCCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_peripherals_cdc/u_i2c_axi_cdc/i_axi_cdc_src/i_cdc_fifo_gray_src_aw/gen_sync[0].i_sync/gen_tt_sync3_async_clr.prim_sync3r} SMCCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_peripherals_cdc/u_i2c_axi_cdc/i_axi_cdc_src/i_cdc_fifo_gray_src_aw/gen_sync[1].i_sync/gen_tt_sync3_async_clr.prim_sync3r} SMCCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_peripherals_cdc/u_i2c_axi_cdc/i_axi_cdc_src/i_cdc_fifo_gray_src_w/gen_sync[0].i_sync/gen_tt_sync3_async_clr.prim_sync3r} SMCCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_peripherals_cdc/u_i2c_axi_cdc/i_axi_cdc_src/i_cdc_fifo_gray_src_w/gen_sync[1].i_sync/gen_tt_sync3_async_clr.prim_sync3r} SMCCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_peripherals_cdc/u_i3c_axi_cdc/i_axi_cdc_dst/i_cdc_fifo_gray_dst_ar/gen_sync[0].i_sync/gen_tt_sync3_async_clr.prim_sync3r} PERIPHERALCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_peripherals_cdc/u_i3c_axi_cdc/i_axi_cdc_dst/i_cdc_fifo_gray_dst_ar/gen_sync[1].i_sync/gen_tt_sync3_async_clr.prim_sync3r} PERIPHERALCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_peripherals_cdc/u_i3c_axi_cdc/i_axi_cdc_dst/i_cdc_fifo_gray_dst_aw/gen_sync[0].i_sync/gen_tt_sync3_async_clr.prim_sync3r} PERIPHERALCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_peripherals_cdc/u_i3c_axi_cdc/i_axi_cdc_dst/i_cdc_fifo_gray_dst_aw/gen_sync[1].i_sync/gen_tt_sync3_async_clr.prim_sync3r} PERIPHERALCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_peripherals_cdc/u_i3c_axi_cdc/i_axi_cdc_dst/i_cdc_fifo_gray_dst_w/gen_sync[0].i_sync/gen_tt_sync3_async_clr.prim_sync3r} PERIPHERALCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_peripherals_cdc/u_i3c_axi_cdc/i_axi_cdc_dst/i_cdc_fifo_gray_dst_w/gen_sync[1].i_sync/gen_tt_sync3_async_clr.prim_sync3r} PERIPHERALCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_peripherals_cdc/u_i3c_axi_cdc/i_axi_cdc_dst/i_cdc_fifo_gray_src_b/gen_sync[0].i_sync/gen_tt_sync3_async_clr.prim_sync3r} PERIPHERALCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_peripherals_cdc/u_i3c_axi_cdc/i_axi_cdc_dst/i_cdc_fifo_gray_src_b/gen_sync[1].i_sync/gen_tt_sync3_async_clr.prim_sync3r} PERIPHERALCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_peripherals_cdc/u_i3c_axi_cdc/i_axi_cdc_dst/i_cdc_fifo_gray_src_r/gen_sync[0].i_sync/gen_tt_sync3_async_clr.prim_sync3r} PERIPHERALCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_peripherals_cdc/u_i3c_axi_cdc/i_axi_cdc_dst/i_cdc_fifo_gray_src_r/gen_sync[1].i_sync/gen_tt_sync3_async_clr.prim_sync3r} PERIPHERALCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_peripherals_cdc/u_i3c_axi_cdc/i_axi_cdc_src/i_cdc_fifo_gray_dst_b/gen_sync[0].i_sync/gen_tt_sync3_async_clr.prim_sync3r} SMCCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_peripherals_cdc/u_i3c_axi_cdc/i_axi_cdc_src/i_cdc_fifo_gray_dst_b/gen_sync[1].i_sync/gen_tt_sync3_async_clr.prim_sync3r} SMCCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_peripherals_cdc/u_i3c_axi_cdc/i_axi_cdc_src/i_cdc_fifo_gray_dst_r/gen_sync[0].i_sync/gen_tt_sync3_async_clr.prim_sync3r} SMCCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_peripherals_cdc/u_i3c_axi_cdc/i_axi_cdc_src/i_cdc_fifo_gray_dst_r/gen_sync[1].i_sync/gen_tt_sync3_async_clr.prim_sync3r} SMCCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_peripherals_cdc/u_i3c_axi_cdc/i_axi_cdc_src/i_cdc_fifo_gray_src_ar/gen_sync[0].i_sync/gen_tt_sync3_async_clr.prim_sync3r} SMCCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_peripherals_cdc/u_i3c_axi_cdc/i_axi_cdc_src/i_cdc_fifo_gray_src_ar/gen_sync[1].i_sync/gen_tt_sync3_async_clr.prim_sync3r} SMCCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_peripherals_cdc/u_i3c_axi_cdc/i_axi_cdc_src/i_cdc_fifo_gray_src_aw/gen_sync[0].i_sync/gen_tt_sync3_async_clr.prim_sync3r} SMCCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_peripherals_cdc/u_i3c_axi_cdc/i_axi_cdc_src/i_cdc_fifo_gray_src_aw/gen_sync[1].i_sync/gen_tt_sync3_async_clr.prim_sync3r} SMCCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_peripherals_cdc/u_i3c_axi_cdc/i_axi_cdc_src/i_cdc_fifo_gray_src_w/gen_sync[0].i_sync/gen_tt_sync3_async_clr.prim_sync3r} SMCCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_peripherals_cdc/u_i3c_axi_cdc/i_axi_cdc_src/i_cdc_fifo_gray_src_w/gen_sync[1].i_sync/gen_tt_sync3_async_clr.prim_sync3r} SMCCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_peripherals_cdc/u_log_engine_axi_cdc/i_axi_cdc_dst/i_cdc_fifo_gray_dst_ar/gen_sync[0].i_sync/gen_tt_sync3_async_clr.prim_sync3r} SMCCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_peripherals_cdc/u_log_engine_axi_cdc/i_axi_cdc_dst/i_cdc_fifo_gray_dst_ar/gen_sync[1].i_sync/gen_tt_sync3_async_clr.prim_sync3r} SMCCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_peripherals_cdc/u_log_engine_axi_cdc/i_axi_cdc_dst/i_cdc_fifo_gray_dst_aw/gen_sync[0].i_sync/gen_tt_sync3_async_clr.prim_sync3r} SMCCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_peripherals_cdc/u_log_engine_axi_cdc/i_axi_cdc_dst/i_cdc_fifo_gray_dst_aw/gen_sync[1].i_sync/gen_tt_sync3_async_clr.prim_sync3r} SMCCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_peripherals_cdc/u_log_engine_axi_cdc/i_axi_cdc_dst/i_cdc_fifo_gray_dst_w/gen_sync[0].i_sync/gen_tt_sync3_async_clr.prim_sync3r} SMCCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_peripherals_cdc/u_log_engine_axi_cdc/i_axi_cdc_dst/i_cdc_fifo_gray_dst_w/gen_sync[1].i_sync/gen_tt_sync3_async_clr.prim_sync3r} SMCCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_peripherals_cdc/u_log_engine_axi_cdc/i_axi_cdc_dst/i_cdc_fifo_gray_src_b/gen_sync[0].i_sync/gen_tt_sync3_async_clr.prim_sync3r} SMCCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_peripherals_cdc/u_log_engine_axi_cdc/i_axi_cdc_dst/i_cdc_fifo_gray_src_b/gen_sync[1].i_sync/gen_tt_sync3_async_clr.prim_sync3r} SMCCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_peripherals_cdc/u_log_engine_axi_cdc/i_axi_cdc_dst/i_cdc_fifo_gray_src_r/gen_sync[0].i_sync/gen_tt_sync3_async_clr.prim_sync3r} SMCCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_peripherals_cdc/u_log_engine_axi_cdc/i_axi_cdc_dst/i_cdc_fifo_gray_src_r/gen_sync[1].i_sync/gen_tt_sync3_async_clr.prim_sync3r} SMCCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_peripherals_cdc/u_log_engine_axi_cdc/i_axi_cdc_src/i_cdc_fifo_gray_dst_b/gen_sync[0].i_sync/gen_tt_sync3_async_clr.prim_sync3r} PERIPHERALCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_peripherals_cdc/u_log_engine_axi_cdc/i_axi_cdc_src/i_cdc_fifo_gray_dst_b/gen_sync[1].i_sync/gen_tt_sync3_async_clr.prim_sync3r} PERIPHERALCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_peripherals_cdc/u_log_engine_axi_cdc/i_axi_cdc_src/i_cdc_fifo_gray_dst_r/gen_sync[0].i_sync/gen_tt_sync3_async_clr.prim_sync3r} PERIPHERALCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_peripherals_cdc/u_log_engine_axi_cdc/i_axi_cdc_src/i_cdc_fifo_gray_dst_r/gen_sync[1].i_sync/gen_tt_sync3_async_clr.prim_sync3r} PERIPHERALCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_peripherals_cdc/u_log_engine_axi_cdc/i_axi_cdc_src/i_cdc_fifo_gray_src_ar/gen_sync[0].i_sync/gen_tt_sync3_async_clr.prim_sync3r} PERIPHERALCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_peripherals_cdc/u_log_engine_axi_cdc/i_axi_cdc_src/i_cdc_fifo_gray_src_ar/gen_sync[1].i_sync/gen_tt_sync3_async_clr.prim_sync3r} PERIPHERALCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_peripherals_cdc/u_log_engine_axi_cdc/i_axi_cdc_src/i_cdc_fifo_gray_src_aw/gen_sync[0].i_sync/gen_tt_sync3_async_clr.prim_sync3r} PERIPHERALCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_peripherals_cdc/u_log_engine_axi_cdc/i_axi_cdc_src/i_cdc_fifo_gray_src_aw/gen_sync[1].i_sync/gen_tt_sync3_async_clr.prim_sync3r} PERIPHERALCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_peripherals_cdc/u_log_engine_axi_cdc/i_axi_cdc_src/i_cdc_fifo_gray_src_w/gen_sync[0].i_sync/gen_tt_sync3_async_clr.prim_sync3r} PERIPHERALCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_peripherals_cdc/u_log_engine_axi_cdc/i_axi_cdc_src/i_cdc_fifo_gray_src_w/gen_sync[1].i_sync/gen_tt_sync3_async_clr.prim_sync3r} PERIPHERALCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_peripherals_cdc/u_uart_axi_cdc/i_axi_cdc_dst/i_cdc_fifo_gray_dst_ar/gen_sync[0].i_sync/gen_tt_sync3_async_clr.prim_sync3r} PERIPHERALCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_peripherals_cdc/u_uart_axi_cdc/i_axi_cdc_dst/i_cdc_fifo_gray_dst_ar/gen_sync[1].i_sync/gen_tt_sync3_async_clr.prim_sync3r} PERIPHERALCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_peripherals_cdc/u_uart_axi_cdc/i_axi_cdc_dst/i_cdc_fifo_gray_dst_aw/gen_sync[0].i_sync/gen_tt_sync3_async_clr.prim_sync3r} PERIPHERALCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_peripherals_cdc/u_uart_axi_cdc/i_axi_cdc_dst/i_cdc_fifo_gray_dst_aw/gen_sync[1].i_sync/gen_tt_sync3_async_clr.prim_sync3r} PERIPHERALCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_peripherals_cdc/u_uart_axi_cdc/i_axi_cdc_dst/i_cdc_fifo_gray_dst_w/gen_sync[0].i_sync/gen_tt_sync3_async_clr.prim_sync3r} PERIPHERALCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_peripherals_cdc/u_uart_axi_cdc/i_axi_cdc_dst/i_cdc_fifo_gray_dst_w/gen_sync[1].i_sync/gen_tt_sync3_async_clr.prim_sync3r} PERIPHERALCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_peripherals_cdc/u_uart_axi_cdc/i_axi_cdc_dst/i_cdc_fifo_gray_src_b/gen_sync[0].i_sync/gen_tt_sync3_async_clr.prim_sync3r} PERIPHERALCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_peripherals_cdc/u_uart_axi_cdc/i_axi_cdc_dst/i_cdc_fifo_gray_src_b/gen_sync[1].i_sync/gen_tt_sync3_async_clr.prim_sync3r} PERIPHERALCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_peripherals_cdc/u_uart_axi_cdc/i_axi_cdc_dst/i_cdc_fifo_gray_src_r/gen_sync[0].i_sync/gen_tt_sync3_async_clr.prim_sync3r} PERIPHERALCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_peripherals_cdc/u_uart_axi_cdc/i_axi_cdc_dst/i_cdc_fifo_gray_src_r/gen_sync[1].i_sync/gen_tt_sync3_async_clr.prim_sync3r} PERIPHERALCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_peripherals_cdc/u_uart_axi_cdc/i_axi_cdc_src/i_cdc_fifo_gray_dst_b/gen_sync[0].i_sync/gen_tt_sync3_async_clr.prim_sync3r} SMCCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_peripherals_cdc/u_uart_axi_cdc/i_axi_cdc_src/i_cdc_fifo_gray_dst_b/gen_sync[1].i_sync/gen_tt_sync3_async_clr.prim_sync3r} SMCCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_peripherals_cdc/u_uart_axi_cdc/i_axi_cdc_src/i_cdc_fifo_gray_dst_r/gen_sync[0].i_sync/gen_tt_sync3_async_clr.prim_sync3r} SMCCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_peripherals_cdc/u_uart_axi_cdc/i_axi_cdc_src/i_cdc_fifo_gray_dst_r/gen_sync[1].i_sync/gen_tt_sync3_async_clr.prim_sync3r} SMCCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_peripherals_cdc/u_uart_axi_cdc/i_axi_cdc_src/i_cdc_fifo_gray_src_ar/gen_sync[0].i_sync/gen_tt_sync3_async_clr.prim_sync3r} SMCCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_peripherals_cdc/u_uart_axi_cdc/i_axi_cdc_src/i_cdc_fifo_gray_src_ar/gen_sync[1].i_sync/gen_tt_sync3_async_clr.prim_sync3r} SMCCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_peripherals_cdc/u_uart_axi_cdc/i_axi_cdc_src/i_cdc_fifo_gray_src_aw/gen_sync[0].i_sync/gen_tt_sync3_async_clr.prim_sync3r} SMCCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_peripherals_cdc/u_uart_axi_cdc/i_axi_cdc_src/i_cdc_fifo_gray_src_aw/gen_sync[1].i_sync/gen_tt_sync3_async_clr.prim_sync3r} SMCCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_peripherals_cdc/u_uart_axi_cdc/i_axi_cdc_src/i_cdc_fifo_gray_src_w/gen_sync[0].i_sync/gen_tt_sync3_async_clr.prim_sync3r} SMCCLK
set_cdc_max_delay_prim_sync3 {u_smc_peripherals/u_smc_peripherals_cdc/u_uart_axi_cdc/i_axi_cdc_src/i_cdc_fifo_gray_src_w/gen_sync[1].i_sync/gen_tt_sync3_async_clr.prim_sync3r} SMCCLK

# ---- sync (100 instances) ----
set_cdc_max_delay_sync {u_smc_peripherals/u_smc_peripherals_cdc/u_avsbus_axi_cdc/i_axi_cdc_dst/i_cdc_fifo_gray_dst_ar/gen_sync[0].i_sync} PERIPHERALCLK
set_cdc_max_delay_sync {u_smc_peripherals/u_smc_peripherals_cdc/u_avsbus_axi_cdc/i_axi_cdc_dst/i_cdc_fifo_gray_dst_ar/gen_sync[1].i_sync} PERIPHERALCLK
set_cdc_max_delay_sync {u_smc_peripherals/u_smc_peripherals_cdc/u_avsbus_axi_cdc/i_axi_cdc_dst/i_cdc_fifo_gray_dst_aw/gen_sync[0].i_sync} PERIPHERALCLK
set_cdc_max_delay_sync {u_smc_peripherals/u_smc_peripherals_cdc/u_avsbus_axi_cdc/i_axi_cdc_dst/i_cdc_fifo_gray_dst_aw/gen_sync[1].i_sync} PERIPHERALCLK
set_cdc_max_delay_sync {u_smc_peripherals/u_smc_peripherals_cdc/u_avsbus_axi_cdc/i_axi_cdc_dst/i_cdc_fifo_gray_dst_w/gen_sync[0].i_sync} PERIPHERALCLK
set_cdc_max_delay_sync {u_smc_peripherals/u_smc_peripherals_cdc/u_avsbus_axi_cdc/i_axi_cdc_dst/i_cdc_fifo_gray_dst_w/gen_sync[1].i_sync} PERIPHERALCLK
set_cdc_max_delay_sync {u_smc_peripherals/u_smc_peripherals_cdc/u_avsbus_axi_cdc/i_axi_cdc_dst/i_cdc_fifo_gray_src_b/gen_sync[0].i_sync} PERIPHERALCLK
set_cdc_max_delay_sync {u_smc_peripherals/u_smc_peripherals_cdc/u_avsbus_axi_cdc/i_axi_cdc_dst/i_cdc_fifo_gray_src_b/gen_sync[1].i_sync} PERIPHERALCLK
set_cdc_max_delay_sync {u_smc_peripherals/u_smc_peripherals_cdc/u_avsbus_axi_cdc/i_axi_cdc_dst/i_cdc_fifo_gray_src_r/gen_sync[0].i_sync} PERIPHERALCLK
set_cdc_max_delay_sync {u_smc_peripherals/u_smc_peripherals_cdc/u_avsbus_axi_cdc/i_axi_cdc_dst/i_cdc_fifo_gray_src_r/gen_sync[1].i_sync} PERIPHERALCLK
set_cdc_max_delay_sync {u_smc_peripherals/u_smc_peripherals_cdc/u_avsbus_axi_cdc/i_axi_cdc_src/i_cdc_fifo_gray_dst_b/gen_sync[0].i_sync} SMCCLK
set_cdc_max_delay_sync {u_smc_peripherals/u_smc_peripherals_cdc/u_avsbus_axi_cdc/i_axi_cdc_src/i_cdc_fifo_gray_dst_b/gen_sync[1].i_sync} SMCCLK
set_cdc_max_delay_sync {u_smc_peripherals/u_smc_peripherals_cdc/u_avsbus_axi_cdc/i_axi_cdc_src/i_cdc_fifo_gray_dst_r/gen_sync[0].i_sync} SMCCLK
set_cdc_max_delay_sync {u_smc_peripherals/u_smc_peripherals_cdc/u_avsbus_axi_cdc/i_axi_cdc_src/i_cdc_fifo_gray_dst_r/gen_sync[1].i_sync} SMCCLK
set_cdc_max_delay_sync {u_smc_peripherals/u_smc_peripherals_cdc/u_avsbus_axi_cdc/i_axi_cdc_src/i_cdc_fifo_gray_src_ar/gen_sync[0].i_sync} SMCCLK
set_cdc_max_delay_sync {u_smc_peripherals/u_smc_peripherals_cdc/u_avsbus_axi_cdc/i_axi_cdc_src/i_cdc_fifo_gray_src_ar/gen_sync[1].i_sync} SMCCLK
set_cdc_max_delay_sync {u_smc_peripherals/u_smc_peripherals_cdc/u_avsbus_axi_cdc/i_axi_cdc_src/i_cdc_fifo_gray_src_aw/gen_sync[0].i_sync} SMCCLK
set_cdc_max_delay_sync {u_smc_peripherals/u_smc_peripherals_cdc/u_avsbus_axi_cdc/i_axi_cdc_src/i_cdc_fifo_gray_src_aw/gen_sync[1].i_sync} SMCCLK
set_cdc_max_delay_sync {u_smc_peripherals/u_smc_peripherals_cdc/u_avsbus_axi_cdc/i_axi_cdc_src/i_cdc_fifo_gray_src_w/gen_sync[0].i_sync} SMCCLK
set_cdc_max_delay_sync {u_smc_peripherals/u_smc_peripherals_cdc/u_avsbus_axi_cdc/i_axi_cdc_src/i_cdc_fifo_gray_src_w/gen_sync[1].i_sync} SMCCLK
set_cdc_max_delay_sync {u_smc_peripherals/u_smc_peripherals_cdc/u_i2c_axi_cdc/i_axi_cdc_dst/i_cdc_fifo_gray_dst_ar/gen_sync[0].i_sync} PERIPHERALCLK
set_cdc_max_delay_sync {u_smc_peripherals/u_smc_peripherals_cdc/u_i2c_axi_cdc/i_axi_cdc_dst/i_cdc_fifo_gray_dst_ar/gen_sync[1].i_sync} PERIPHERALCLK
set_cdc_max_delay_sync {u_smc_peripherals/u_smc_peripherals_cdc/u_i2c_axi_cdc/i_axi_cdc_dst/i_cdc_fifo_gray_dst_aw/gen_sync[0].i_sync} PERIPHERALCLK
set_cdc_max_delay_sync {u_smc_peripherals/u_smc_peripherals_cdc/u_i2c_axi_cdc/i_axi_cdc_dst/i_cdc_fifo_gray_dst_aw/gen_sync[1].i_sync} PERIPHERALCLK
set_cdc_max_delay_sync {u_smc_peripherals/u_smc_peripherals_cdc/u_i2c_axi_cdc/i_axi_cdc_dst/i_cdc_fifo_gray_dst_w/gen_sync[0].i_sync} PERIPHERALCLK
set_cdc_max_delay_sync {u_smc_peripherals/u_smc_peripherals_cdc/u_i2c_axi_cdc/i_axi_cdc_dst/i_cdc_fifo_gray_dst_w/gen_sync[1].i_sync} PERIPHERALCLK
set_cdc_max_delay_sync {u_smc_peripherals/u_smc_peripherals_cdc/u_i2c_axi_cdc/i_axi_cdc_dst/i_cdc_fifo_gray_src_b/gen_sync[0].i_sync} PERIPHERALCLK
set_cdc_max_delay_sync {u_smc_peripherals/u_smc_peripherals_cdc/u_i2c_axi_cdc/i_axi_cdc_dst/i_cdc_fifo_gray_src_b/gen_sync[1].i_sync} PERIPHERALCLK
set_cdc_max_delay_sync {u_smc_peripherals/u_smc_peripherals_cdc/u_i2c_axi_cdc/i_axi_cdc_dst/i_cdc_fifo_gray_src_r/gen_sync[0].i_sync} PERIPHERALCLK
set_cdc_max_delay_sync {u_smc_peripherals/u_smc_peripherals_cdc/u_i2c_axi_cdc/i_axi_cdc_dst/i_cdc_fifo_gray_src_r/gen_sync[1].i_sync} PERIPHERALCLK
set_cdc_max_delay_sync {u_smc_peripherals/u_smc_peripherals_cdc/u_i2c_axi_cdc/i_axi_cdc_src/i_cdc_fifo_gray_dst_b/gen_sync[0].i_sync} SMCCLK
set_cdc_max_delay_sync {u_smc_peripherals/u_smc_peripherals_cdc/u_i2c_axi_cdc/i_axi_cdc_src/i_cdc_fifo_gray_dst_b/gen_sync[1].i_sync} SMCCLK
set_cdc_max_delay_sync {u_smc_peripherals/u_smc_peripherals_cdc/u_i2c_axi_cdc/i_axi_cdc_src/i_cdc_fifo_gray_dst_r/gen_sync[0].i_sync} SMCCLK
set_cdc_max_delay_sync {u_smc_peripherals/u_smc_peripherals_cdc/u_i2c_axi_cdc/i_axi_cdc_src/i_cdc_fifo_gray_dst_r/gen_sync[1].i_sync} SMCCLK
set_cdc_max_delay_sync {u_smc_peripherals/u_smc_peripherals_cdc/u_i2c_axi_cdc/i_axi_cdc_src/i_cdc_fifo_gray_src_ar/gen_sync[0].i_sync} SMCCLK
set_cdc_max_delay_sync {u_smc_peripherals/u_smc_peripherals_cdc/u_i2c_axi_cdc/i_axi_cdc_src/i_cdc_fifo_gray_src_ar/gen_sync[1].i_sync} SMCCLK
set_cdc_max_delay_sync {u_smc_peripherals/u_smc_peripherals_cdc/u_i2c_axi_cdc/i_axi_cdc_src/i_cdc_fifo_gray_src_aw/gen_sync[0].i_sync} SMCCLK
set_cdc_max_delay_sync {u_smc_peripherals/u_smc_peripherals_cdc/u_i2c_axi_cdc/i_axi_cdc_src/i_cdc_fifo_gray_src_aw/gen_sync[1].i_sync} SMCCLK
set_cdc_max_delay_sync {u_smc_peripherals/u_smc_peripherals_cdc/u_i2c_axi_cdc/i_axi_cdc_src/i_cdc_fifo_gray_src_w/gen_sync[0].i_sync} SMCCLK
set_cdc_max_delay_sync {u_smc_peripherals/u_smc_peripherals_cdc/u_i2c_axi_cdc/i_axi_cdc_src/i_cdc_fifo_gray_src_w/gen_sync[1].i_sync} SMCCLK
set_cdc_max_delay_sync {u_smc_peripherals/u_smc_peripherals_cdc/u_i3c_axi_cdc/i_axi_cdc_dst/i_cdc_fifo_gray_dst_ar/gen_sync[0].i_sync} PERIPHERALCLK
set_cdc_max_delay_sync {u_smc_peripherals/u_smc_peripherals_cdc/u_i3c_axi_cdc/i_axi_cdc_dst/i_cdc_fifo_gray_dst_ar/gen_sync[1].i_sync} PERIPHERALCLK
set_cdc_max_delay_sync {u_smc_peripherals/u_smc_peripherals_cdc/u_i3c_axi_cdc/i_axi_cdc_dst/i_cdc_fifo_gray_dst_aw/gen_sync[0].i_sync} PERIPHERALCLK
set_cdc_max_delay_sync {u_smc_peripherals/u_smc_peripherals_cdc/u_i3c_axi_cdc/i_axi_cdc_dst/i_cdc_fifo_gray_dst_aw/gen_sync[1].i_sync} PERIPHERALCLK
set_cdc_max_delay_sync {u_smc_peripherals/u_smc_peripherals_cdc/u_i3c_axi_cdc/i_axi_cdc_dst/i_cdc_fifo_gray_dst_w/gen_sync[0].i_sync} PERIPHERALCLK
set_cdc_max_delay_sync {u_smc_peripherals/u_smc_peripherals_cdc/u_i3c_axi_cdc/i_axi_cdc_dst/i_cdc_fifo_gray_dst_w/gen_sync[1].i_sync} PERIPHERALCLK
set_cdc_max_delay_sync {u_smc_peripherals/u_smc_peripherals_cdc/u_i3c_axi_cdc/i_axi_cdc_dst/i_cdc_fifo_gray_src_b/gen_sync[0].i_sync} PERIPHERALCLK
set_cdc_max_delay_sync {u_smc_peripherals/u_smc_peripherals_cdc/u_i3c_axi_cdc/i_axi_cdc_dst/i_cdc_fifo_gray_src_b/gen_sync[1].i_sync} PERIPHERALCLK
set_cdc_max_delay_sync {u_smc_peripherals/u_smc_peripherals_cdc/u_i3c_axi_cdc/i_axi_cdc_dst/i_cdc_fifo_gray_src_r/gen_sync[0].i_sync} PERIPHERALCLK
set_cdc_max_delay_sync {u_smc_peripherals/u_smc_peripherals_cdc/u_i3c_axi_cdc/i_axi_cdc_dst/i_cdc_fifo_gray_src_r/gen_sync[1].i_sync} PERIPHERALCLK
set_cdc_max_delay_sync {u_smc_peripherals/u_smc_peripherals_cdc/u_i3c_axi_cdc/i_axi_cdc_src/i_cdc_fifo_gray_dst_b/gen_sync[0].i_sync} SMCCLK
set_cdc_max_delay_sync {u_smc_peripherals/u_smc_peripherals_cdc/u_i3c_axi_cdc/i_axi_cdc_src/i_cdc_fifo_gray_dst_b/gen_sync[1].i_sync} SMCCLK
set_cdc_max_delay_sync {u_smc_peripherals/u_smc_peripherals_cdc/u_i3c_axi_cdc/i_axi_cdc_src/i_cdc_fifo_gray_dst_r/gen_sync[0].i_sync} SMCCLK
set_cdc_max_delay_sync {u_smc_peripherals/u_smc_peripherals_cdc/u_i3c_axi_cdc/i_axi_cdc_src/i_cdc_fifo_gray_dst_r/gen_sync[1].i_sync} SMCCLK
set_cdc_max_delay_sync {u_smc_peripherals/u_smc_peripherals_cdc/u_i3c_axi_cdc/i_axi_cdc_src/i_cdc_fifo_gray_src_ar/gen_sync[0].i_sync} SMCCLK
set_cdc_max_delay_sync {u_smc_peripherals/u_smc_peripherals_cdc/u_i3c_axi_cdc/i_axi_cdc_src/i_cdc_fifo_gray_src_ar/gen_sync[1].i_sync} SMCCLK
set_cdc_max_delay_sync {u_smc_peripherals/u_smc_peripherals_cdc/u_i3c_axi_cdc/i_axi_cdc_src/i_cdc_fifo_gray_src_aw/gen_sync[0].i_sync} SMCCLK
set_cdc_max_delay_sync {u_smc_peripherals/u_smc_peripherals_cdc/u_i3c_axi_cdc/i_axi_cdc_src/i_cdc_fifo_gray_src_aw/gen_sync[1].i_sync} SMCCLK
set_cdc_max_delay_sync {u_smc_peripherals/u_smc_peripherals_cdc/u_i3c_axi_cdc/i_axi_cdc_src/i_cdc_fifo_gray_src_w/gen_sync[0].i_sync} SMCCLK
set_cdc_max_delay_sync {u_smc_peripherals/u_smc_peripherals_cdc/u_i3c_axi_cdc/i_axi_cdc_src/i_cdc_fifo_gray_src_w/gen_sync[1].i_sync} SMCCLK
set_cdc_max_delay_sync {u_smc_peripherals/u_smc_peripherals_cdc/u_log_engine_axi_cdc/i_axi_cdc_dst/i_cdc_fifo_gray_dst_ar/gen_sync[0].i_sync} SMCCLK
set_cdc_max_delay_sync {u_smc_peripherals/u_smc_peripherals_cdc/u_log_engine_axi_cdc/i_axi_cdc_dst/i_cdc_fifo_gray_dst_ar/gen_sync[1].i_sync} SMCCLK
set_cdc_max_delay_sync {u_smc_peripherals/u_smc_peripherals_cdc/u_log_engine_axi_cdc/i_axi_cdc_dst/i_cdc_fifo_gray_dst_aw/gen_sync[0].i_sync} SMCCLK
set_cdc_max_delay_sync {u_smc_peripherals/u_smc_peripherals_cdc/u_log_engine_axi_cdc/i_axi_cdc_dst/i_cdc_fifo_gray_dst_aw/gen_sync[1].i_sync} SMCCLK
set_cdc_max_delay_sync {u_smc_peripherals/u_smc_peripherals_cdc/u_log_engine_axi_cdc/i_axi_cdc_dst/i_cdc_fifo_gray_dst_w/gen_sync[0].i_sync} SMCCLK
set_cdc_max_delay_sync {u_smc_peripherals/u_smc_peripherals_cdc/u_log_engine_axi_cdc/i_axi_cdc_dst/i_cdc_fifo_gray_dst_w/gen_sync[1].i_sync} SMCCLK
set_cdc_max_delay_sync {u_smc_peripherals/u_smc_peripherals_cdc/u_log_engine_axi_cdc/i_axi_cdc_dst/i_cdc_fifo_gray_src_b/gen_sync[0].i_sync} SMCCLK
set_cdc_max_delay_sync {u_smc_peripherals/u_smc_peripherals_cdc/u_log_engine_axi_cdc/i_axi_cdc_dst/i_cdc_fifo_gray_src_b/gen_sync[1].i_sync} SMCCLK
set_cdc_max_delay_sync {u_smc_peripherals/u_smc_peripherals_cdc/u_log_engine_axi_cdc/i_axi_cdc_dst/i_cdc_fifo_gray_src_r/gen_sync[0].i_sync} SMCCLK
set_cdc_max_delay_sync {u_smc_peripherals/u_smc_peripherals_cdc/u_log_engine_axi_cdc/i_axi_cdc_dst/i_cdc_fifo_gray_src_r/gen_sync[1].i_sync} SMCCLK
set_cdc_max_delay_sync {u_smc_peripherals/u_smc_peripherals_cdc/u_log_engine_axi_cdc/i_axi_cdc_src/i_cdc_fifo_gray_dst_b/gen_sync[0].i_sync} PERIPHERALCLK
set_cdc_max_delay_sync {u_smc_peripherals/u_smc_peripherals_cdc/u_log_engine_axi_cdc/i_axi_cdc_src/i_cdc_fifo_gray_dst_b/gen_sync[1].i_sync} PERIPHERALCLK
set_cdc_max_delay_sync {u_smc_peripherals/u_smc_peripherals_cdc/u_log_engine_axi_cdc/i_axi_cdc_src/i_cdc_fifo_gray_dst_r/gen_sync[0].i_sync} PERIPHERALCLK
set_cdc_max_delay_sync {u_smc_peripherals/u_smc_peripherals_cdc/u_log_engine_axi_cdc/i_axi_cdc_src/i_cdc_fifo_gray_dst_r/gen_sync[1].i_sync} PERIPHERALCLK
set_cdc_max_delay_sync {u_smc_peripherals/u_smc_peripherals_cdc/u_log_engine_axi_cdc/i_axi_cdc_src/i_cdc_fifo_gray_src_ar/gen_sync[0].i_sync} PERIPHERALCLK
set_cdc_max_delay_sync {u_smc_peripherals/u_smc_peripherals_cdc/u_log_engine_axi_cdc/i_axi_cdc_src/i_cdc_fifo_gray_src_ar/gen_sync[1].i_sync} PERIPHERALCLK
set_cdc_max_delay_sync {u_smc_peripherals/u_smc_peripherals_cdc/u_log_engine_axi_cdc/i_axi_cdc_src/i_cdc_fifo_gray_src_aw/gen_sync[0].i_sync} PERIPHERALCLK
set_cdc_max_delay_sync {u_smc_peripherals/u_smc_peripherals_cdc/u_log_engine_axi_cdc/i_axi_cdc_src/i_cdc_fifo_gray_src_aw/gen_sync[1].i_sync} PERIPHERALCLK
set_cdc_max_delay_sync {u_smc_peripherals/u_smc_peripherals_cdc/u_log_engine_axi_cdc/i_axi_cdc_src/i_cdc_fifo_gray_src_w/gen_sync[0].i_sync} PERIPHERALCLK
set_cdc_max_delay_sync {u_smc_peripherals/u_smc_peripherals_cdc/u_log_engine_axi_cdc/i_axi_cdc_src/i_cdc_fifo_gray_src_w/gen_sync[1].i_sync} PERIPHERALCLK
set_cdc_max_delay_sync {u_smc_peripherals/u_smc_peripherals_cdc/u_uart_axi_cdc/i_axi_cdc_dst/i_cdc_fifo_gray_dst_ar/gen_sync[0].i_sync} PERIPHERALCLK
set_cdc_max_delay_sync {u_smc_peripherals/u_smc_peripherals_cdc/u_uart_axi_cdc/i_axi_cdc_dst/i_cdc_fifo_gray_dst_ar/gen_sync[1].i_sync} PERIPHERALCLK
set_cdc_max_delay_sync {u_smc_peripherals/u_smc_peripherals_cdc/u_uart_axi_cdc/i_axi_cdc_dst/i_cdc_fifo_gray_dst_aw/gen_sync[0].i_sync} PERIPHERALCLK
set_cdc_max_delay_sync {u_smc_peripherals/u_smc_peripherals_cdc/u_uart_axi_cdc/i_axi_cdc_dst/i_cdc_fifo_gray_dst_aw/gen_sync[1].i_sync} PERIPHERALCLK
set_cdc_max_delay_sync {u_smc_peripherals/u_smc_peripherals_cdc/u_uart_axi_cdc/i_axi_cdc_dst/i_cdc_fifo_gray_dst_w/gen_sync[0].i_sync} PERIPHERALCLK
set_cdc_max_delay_sync {u_smc_peripherals/u_smc_peripherals_cdc/u_uart_axi_cdc/i_axi_cdc_dst/i_cdc_fifo_gray_dst_w/gen_sync[1].i_sync} PERIPHERALCLK
set_cdc_max_delay_sync {u_smc_peripherals/u_smc_peripherals_cdc/u_uart_axi_cdc/i_axi_cdc_dst/i_cdc_fifo_gray_src_b/gen_sync[0].i_sync} PERIPHERALCLK
set_cdc_max_delay_sync {u_smc_peripherals/u_smc_peripherals_cdc/u_uart_axi_cdc/i_axi_cdc_dst/i_cdc_fifo_gray_src_b/gen_sync[1].i_sync} PERIPHERALCLK
set_cdc_max_delay_sync {u_smc_peripherals/u_smc_peripherals_cdc/u_uart_axi_cdc/i_axi_cdc_dst/i_cdc_fifo_gray_src_r/gen_sync[0].i_sync} PERIPHERALCLK
set_cdc_max_delay_sync {u_smc_peripherals/u_smc_peripherals_cdc/u_uart_axi_cdc/i_axi_cdc_dst/i_cdc_fifo_gray_src_r/gen_sync[1].i_sync} PERIPHERALCLK
set_cdc_max_delay_sync {u_smc_peripherals/u_smc_peripherals_cdc/u_uart_axi_cdc/i_axi_cdc_src/i_cdc_fifo_gray_dst_b/gen_sync[0].i_sync} SMCCLK
set_cdc_max_delay_sync {u_smc_peripherals/u_smc_peripherals_cdc/u_uart_axi_cdc/i_axi_cdc_src/i_cdc_fifo_gray_dst_b/gen_sync[1].i_sync} SMCCLK
set_cdc_max_delay_sync {u_smc_peripherals/u_smc_peripherals_cdc/u_uart_axi_cdc/i_axi_cdc_src/i_cdc_fifo_gray_dst_r/gen_sync[0].i_sync} SMCCLK
set_cdc_max_delay_sync {u_smc_peripherals/u_smc_peripherals_cdc/u_uart_axi_cdc/i_axi_cdc_src/i_cdc_fifo_gray_dst_r/gen_sync[1].i_sync} SMCCLK
set_cdc_max_delay_sync {u_smc_peripherals/u_smc_peripherals_cdc/u_uart_axi_cdc/i_axi_cdc_src/i_cdc_fifo_gray_src_ar/gen_sync[0].i_sync} SMCCLK
set_cdc_max_delay_sync {u_smc_peripherals/u_smc_peripherals_cdc/u_uart_axi_cdc/i_axi_cdc_src/i_cdc_fifo_gray_src_ar/gen_sync[1].i_sync} SMCCLK
set_cdc_max_delay_sync {u_smc_peripherals/u_smc_peripherals_cdc/u_uart_axi_cdc/i_axi_cdc_src/i_cdc_fifo_gray_src_aw/gen_sync[0].i_sync} SMCCLK
set_cdc_max_delay_sync {u_smc_peripherals/u_smc_peripherals_cdc/u_uart_axi_cdc/i_axi_cdc_src/i_cdc_fifo_gray_src_aw/gen_sync[1].i_sync} SMCCLK
set_cdc_max_delay_sync {u_smc_peripherals/u_smc_peripherals_cdc/u_uart_axi_cdc/i_axi_cdc_src/i_cdc_fifo_gray_src_w/gen_sync[0].i_sync} SMCCLK
set_cdc_max_delay_sync {u_smc_peripherals/u_smc_peripherals_cdc/u_uart_axi_cdc/i_axi_cdc_src/i_cdc_fifo_gray_src_w/gen_sync[1].i_sync} SMCCLK

# ---- prim_sync_reset (16 instances) ----
set_cdc_max_delay_prim_sync_reset u_smc_cpu_wrapper/u_smc_cpu_ctrl_wrap/refclk_counter/prst_rd_clk_domain_sync REFCLK
set_cdc_max_delay_prim_sync_reset u_smc_cpu_wrapper/u_smc_cpu_ctrl_wrap/refclk_counter/prst_wr_clk_domain_sync SMCCLK
set_cdc_max_delay_prim_sync_reset u_smc_peripherals/avsbus_controller/apb_clk_reset_sync PERIPHERALCLK
set_cdc_max_delay_prim_sync_reset u_smc_peripherals/avsbus_controller/avs_clk_reset_sync {AVS_CLK_DIV_CLK_O_FROM_PERIPHERALCLK AVS_CLK_DIV_CLK_O_FROM_REFCLK}
set_cdc_max_delay_prim_sync_reset u_smc_peripherals/avsbus_controller/pre_div_clk_reset_sync {AVS_CLKMUX_OUTPUT_FROM_PERIPHERALCLK AVS_CLKMUX_OUTPUT_FROM_REFCLK}
set_cdc_max_delay_prim_sync_reset u_smc_peripherals/avsbus_controller/u_clear_avs_slave_int_resync/i_dest/src_reset_n_sync {AVS_CLK_DIV_CLK_O_FROM_PERIPHERALCLK AVS_CLK_DIV_CLK_O_FROM_REFCLK}
set_cdc_max_delay_prim_sync_reset u_smc_peripherals/avsbus_controller/u_clear_slave_unresponsive_int_resync/i_dest/src_reset_n_sync {AVS_CLK_DIV_CLK_O_FROM_PERIPHERALCLK AVS_CLK_DIV_CLK_O_FROM_REFCLK}
set_cdc_max_delay_prim_sync_reset u_smc_peripherals/avsbus_controller/u_clk_div/reset_sync {AVS_CLKMUX_OUTPUT_FROM_PERIPHERALCLK AVS_CLKMUX_OUTPUT_FROM_REFCLK}
set_cdc_max_delay_prim_sync_reset u_smc_peripherals/u_smc_reset_unit/u_smc_reset_ctrl/powergood_stretcher_n0_scan REFCLK
set_cdc_max_delay_prim_sync_reset u_smc_peripherals/u_smc_reset_unit/u_smc_reset_sync/u_rst_cold_ref_clk_sync REFCLK
set_cdc_max_delay_prim_sync_reset u_smc_peripherals/u_smc_reset_unit/u_smc_reset_sync/u_rst_cold_smc_sync SMCCLK
set_cdc_max_delay_prim_sync_reset u_smc_peripherals/u_smc_reset_unit/u_smc_reset_sync/u_rst_primary_periph_clk_sync PERIPHERALCLK
set_cdc_max_delay_prim_sync_reset u_smc_peripherals/u_smc_reset_unit/u_smc_reset_sync/u_rst_primary_ref_clk_sync REFCLK
set_cdc_max_delay_prim_sync_reset u_smc_peripherals/u_smc_reset_unit/u_smc_reset_sync/u_rst_primary_smc_sync SMCCLK
set_cdc_max_delay_prim_sync_reset u_smc_peripherals/u_smc_reset_unit/u_smc_reset_sync/u_rst_warm_smc_sync SMCCLK
set_cdc_max_delay_prim_sync_reset u_smc_peripherals/u_smc_reset_unit/u_smc_reset_sync/u_rst_wdt_smc_sync SMCCLK

# ---- prim_sync3_pulse (2 instances) ----
set_cdc_max_delay_prim_sync3_pulse u_smc_peripherals/avsbus_controller/u_clear_avs_slave_int_resync {AVS_CLK_DIV_CLK_O_FROM_PERIPHERALCLK AVS_CLK_DIV_CLK_O_FROM_REFCLK}
set_cdc_max_delay_prim_sync3_pulse u_smc_peripherals/avsbus_controller/u_clear_slave_unresponsive_int_resync {AVS_CLK_DIV_CLK_O_FROM_PERIPHERALCLK AVS_CLK_DIV_CLK_O_FROM_REFCLK}

# ---- prim_fifo_async (4 instances) ----
set_cdc_max_delay_prim_fifo_async u_smc_cpu_wrapper/u_smc_cpu_ctrl_wrap/refclk_counter/cnt_update_async_fifo SMCCLK REFCLK
set_cdc_max_delay_prim_fifo_async {u_smc_peripherals/telemetry_receiver_wrap/gen_telemetry_receivers[0].at_req_fifo_async} TELEMETRYCLK SMCCLK
set_cdc_max_delay_prim_fifo_async {u_smc_peripherals/telemetry_receiver_wrap/gen_telemetry_receivers[1].at_req_fifo_async} TELEMETRYCLK SMCCLK
set_cdc_max_delay_prim_fifo_async {u_smc_peripherals/telemetry_receiver_wrap/gen_telemetry_receivers[2].at_req_fifo_async} TELEMETRYCLK SMCCLK

# ---- avsbus_async_fifo (2 instances) ----
set_cdc_max_delay_avsbus_async_fifo u_smc_peripherals/avsbus_controller/cmd_async_fifo_inst PERIPHERALCLK {AVS_CLK_DIV_CLK_O_FROM_PERIPHERALCLK AVS_CLK_DIV_CLK_O_FROM_REFCLK}
set_cdc_max_delay_avsbus_async_fifo u_smc_peripherals/avsbus_controller/readasync_back_fifo_inst {AVS_CLK_DIV_CLK_O_FROM_PERIPHERALCLK AVS_CLK_DIV_CLK_O_FROM_REFCLK} PERIPHERALCLK

# ---- prim_sync_data_autohs (10 instances) ----
set_cdc_max_delay_prim_sync_data_autohs u_smc_peripherals/avsbus_controller/u_cur_state_resync {AVS_CLK_DIV_CLK_O_FROM_PERIPHERALCLK AVS_CLK_DIV_CLK_O_FROM_REFCLK} PERIPHERALCLK
set_cdc_max_delay_prim_sync_data_autohs u_smc_peripherals/avsbus_controller/u_divider_value_resync PERIPHERALCLK {AVS_CLKMUX_OUTPUT_FROM_PERIPHERALCLK AVS_CLKMUX_OUTPUT_FROM_REFCLK}
set_cdc_max_delay_prim_sync_data_autohs u_smc_peripherals/avsbus_controller/u_duty_numerator_resync PERIPHERALCLK {AVS_CLKMUX_OUTPUT_FROM_PERIPHERALCLK AVS_CLKMUX_OUTPUT_FROM_REFCLK}
set_cdc_max_delay_prim_sync_data_autohs u_smc_peripherals/avsbus_controller/u_max_retries_resync PERIPHERALCLK {AVS_CLK_DIV_CLK_O_FROM_PERIPHERALCLK AVS_CLK_DIV_CLK_O_FROM_REFCLK}
set_cdc_max_delay_prim_sync_data_autohs u_smc_peripherals/avsbus_controller/u_readback_occupied_resync {AVS_CLK_DIV_CLK_O_FROM_PERIPHERALCLK AVS_CLK_DIV_CLK_O_FROM_REFCLK} PERIPHERALCLK
set_cdc_max_delay_prim_sync_data_autohs u_smc_peripherals/avsbus_controller/u_readback_vacant_resync {AVS_CLK_DIV_CLK_O_FROM_PERIPHERALCLK AVS_CLK_DIV_CLK_O_FROM_REFCLK} PERIPHERALCLK
set_cdc_max_delay_prim_sync_data_autohs u_smc_peripherals/avsbus_controller/u_total_retries_resync {AVS_CLK_DIV_CLK_O_FROM_PERIPHERALCLK AVS_CLK_DIV_CLK_O_FROM_REFCLK} PERIPHERALCLK
set_cdc_max_delay_prim_sync_data_autohs u_smc_peripherals/u_smc_peripherals_cdc/u_avsbus_cur_state_debug_sync PERIPHERALCLK SMCCLK
set_cdc_max_delay_prim_sync_data_autohs u_smc_peripherals/u_smc_reset_unit/u_smc_cool_reset_wrap/u_flr_reset_set_cnt_sync SMCCLK REFCLK
set_cdc_max_delay_prim_sync_data_autohs u_smc_peripherals/u_smc_reset_unit/u_smc_cool_reset_wrap/u_flr_set_cnt_sync SMCCLK REFCLK

# ---- axi_cdc (5 instances) ----
set_cdc_max_delay_axi_cdc u_smc_peripherals/u_smc_peripherals_cdc/u_avsbus_axi_cdc SMCCLK PERIPHERALCLK
set_cdc_max_delay_axi_cdc u_smc_peripherals/u_smc_peripherals_cdc/u_i2c_axi_cdc SMCCLK PERIPHERALCLK
set_cdc_max_delay_axi_cdc u_smc_peripherals/u_smc_peripherals_cdc/u_i3c_axi_cdc SMCCLK PERIPHERALCLK
set_cdc_max_delay_axi_cdc u_smc_peripherals/u_smc_peripherals_cdc/u_log_engine_axi_cdc PERIPHERALCLK SMCCLK
set_cdc_max_delay_axi_cdc u_smc_peripherals/u_smc_peripherals_cdc/u_uart_axi_cdc SMCCLK PERIPHERALCLK

# ---- Rocket AsyncQueue sinks (3) ----
set_cdc_max_delay_rocket_async_queue u_smc_cpu_wrapper/u_smc_cpu/u_digital_top/tlDM/dmInner/dmactive_synced_dmInner_io_innerCtrl_sink SMCCLK
set_cdc_max_delay_rocket_async_queue u_smc_cpu_wrapper/u_smc_cpu/u_digital_top/tlDM/dmInner/dmiXing/nodeOut_a_sink SMCCLK
set_cdc_max_delay_rocket_async_queue u_smc_cpu_wrapper/u_smc_cpu/u_digital_top/tlDM/dmOuter/asource/nodeIn_d_sink JTAG_TCK
