# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2026 Tenstorrent USA, Inc.
"""NIST ACVP ML-DSA-87 keyGen vectors, parsed from the vendored C header.

``hw/sys/sep/dv/fw/tests/common/abr_nist_vectors.h`` is generated by
``fw/tests/common/gen_abr_nist_vectors.py`` from the NIST ACVP-Server
internalProjection. This module is the Python golden for the no_cpu keyGen
KAT; it does not re-encode the words.
"""

from __future__ import annotations

import re
from pathlib import Path

_HEADER = (
    Path(__file__).resolve().parents[2]
    / "fw" / "tests" / "common" / "abr_nist_vectors.h"
)


def _load_u32_array(name: str) -> list[int]:
    text = _HEADER.read_text()
    m = re.search(
        rf"static const uint32_t {name}\[(\d+)\] = \{{(.*?)\}};",
        text,
        re.S,
    )
    if not m:
        raise RuntimeError(f"{name} not found in {_HEADER}")
    words = [int(tok, 16) for tok in re.findall(r"0x([0-9a-fA-F]+)u", m.group(2))]
    n = int(m.group(1))
    if len(words) != n:
        raise RuntimeError(f"{name}: parsed {len(words)} words, header says {n}")
    return words


NIST_KG_SEED = _load_u32_array("nist_kg_seed")
NIST_KG_PK = _load_u32_array("nist_kg_pk")

assert len(NIST_KG_SEED) == 8
assert len(NIST_KG_PK) == 648
assert any(w != 0 for w in NIST_KG_SEED)
assert any(w != 0 for w in NIST_KG_PK)
