+define+TARGET_AOU
+define+TARGET_FLIST
+define+SIMULATION=1
hw/common/defs/ocah_vendor_defines.svh
// Package(aou) Target(aou)
vendor/tenstorrent/aou/upstream/RTL/packet_def_pkg.sv
vendor/tenstorrent/aou/upstream/RTL/AOU_RX_CORE.sv
vendor/tenstorrent/aou/upstream/RTL/AOU_ACTIVATION_CTRL.sv
vendor/tenstorrent/aou/upstream/RTL/AOU_DATA_W_FIFO_NS1M_TPSRAM.sv
vendor/tenstorrent/aou/upstream/RTL/AOU_DATA_R_FIFO_NS1M_TPSRAM.sv
vendor/tenstorrent/aou/upstream/RTL/AOU_AXI_WLAST_GEN.v
vendor/tenstorrent/aou/upstream/RTL/AOU_CORE_TOP.sv
vendor/tenstorrent/aou/upstream/RTL/AOU_CRD_CTRL.sv
vendor/tenstorrent/aou/upstream/RTL/AOU_RX_CRD_CTRL.sv
vendor/tenstorrent/aou/upstream/RTL/AOU_TX_CRD_CTRL.sv
vendor/tenstorrent/aou/upstream/RTL/AOU_FWD_RS.sv
vendor/tenstorrent/aou/upstream/RTL/AOU_REV_RS.sv
vendor/tenstorrent/aou/upstream/RTL/AOU_ISO_RS.sv
vendor/tenstorrent/aou/upstream/RTL/AOU_SYNC_FIFO_REG.v
vendor/tenstorrent/aou/upstream/RTL/AOU_TX_CORE.sv
vendor/tenstorrent/aou/upstream/RTL/AOU_2X1_ARBITER.v
vendor/tenstorrent/aou/upstream/RTL/AOU_3X1_ARBITER.v
vendor/tenstorrent/aou/upstream/RTL/AOU_4X1_ARBITER.v
vendor/tenstorrent/aou/upstream/RTL/AOU_TX_ARBITER.sv
vendor/tenstorrent/aou/upstream/RTL/AOU_TX_AXI_BUFFER.sv
vendor/tenstorrent/aou/upstream/RTL/AOU_TX_QOS_BUFFER.sv
vendor/tenstorrent/aou/upstream/RTL/AOU_TX_QOS_ARBITER.sv
vendor/tenstorrent/aou/upstream/RTL/AOU_CORE_SFR.v
vendor/tenstorrent/aou/upstream/RTL/AOU_SYNC_FIFO_NS1M.sv
vendor/tenstorrent/aou/upstream/RTL/AOU_SYNC_FIFO_NS1M_SREADY.sv
vendor/tenstorrent/aou/upstream/RTL/AOU_TPSRAM.sv
vendor/tenstorrent/aou/upstream/RTL/AOU_TX_FDI_IF.sv
vendor/tenstorrent/aou/upstream/RTL/AOU_RX_FDI_IF.sv
vendor/tenstorrent/aou/upstream/RTL/AOU_EARLY_BRESP_CTRL_AWCACHE.sv
vendor/tenstorrent/aou/upstream/RTL/AOU_EARLY_TABLE.sv
vendor/tenstorrent/aou/upstream/RTL/AOU_AXIMUX_1XN_SS.v
vendor/tenstorrent/aou/upstream/RTL/AOU_ERROR_INFO.sv
vendor/tenstorrent/aou/upstream/RTL/AOU_SLV_AXI_INFO.sv
vendor/tenstorrent/aou/upstream/RTL/AOU_CORE.sv
vendor/tenstorrent/aou/upstream/RTL/AOU_CORE_RP.sv
vendor/tenstorrent/aou/upstream/RTL/AOU_FIFO_RP.sv
vendor/tenstorrent/aou/upstream/RTL/AOU_AW_W_ALIGNER.sv
vendor/tenstorrent/aou/upstream/RTL/AOU_TX_CORE_OUT_MUX.sv
vendor/tenstorrent/aou/upstream/RTL/AOU_RX_CORE_IN_MUX.sv
vendor/tenstorrent/aou/upstream/RTL/AOU_FDI_BRINGUP_CTRL.sv
vendor/tenstorrent/aou/upstream/RTL/AOU_TOP.sv
vendor/tenstorrent/aou/upstream/RTL/AXI4MUX_3X1/AOU_AXI4MUX_3X1_TOP.v
vendor/tenstorrent/aou/upstream/RTL/AXI4MUX_3X1/AOU_AXI4MUX_3X1_256.v
vendor/tenstorrent/aou/upstream/RTL/AXI4MUX_3X1/AOU_AXI4MUX_3X1_512.v
vendor/tenstorrent/aou/upstream/RTL/AXI4MUX_3X1/AOU_AXI4MUX_3X1_1024.v
vendor/tenstorrent/aou/upstream/RTL/AXI4MUX_3X1/AOU_AXI_INST_SPLITTER.v
vendor/tenstorrent/aou/upstream/RTL/AXI4MUX_3X1/AOU_AXI_UP.v
vendor/tenstorrent/aou/upstream/RTL/AXI4MUX_3X1/AOU_AXI_DOWN.v
vendor/tenstorrent/aou/upstream/RTL/AXI4MUX_3X1/AOU_UP_FIFO.v
vendor/tenstorrent/aou/upstream/RTL/AXI4MUX_3X1/AOU_AXI_DOWN_RDATA_ORDER.sv
vendor/tenstorrent/aou/upstream/RTL/AXI4MUX_3X1/AOU_AXI_SPLIT_ADDRGEN.v
vendor/tenstorrent/aou/upstream/RTL/AXI4MUX_3X1/AOU_AXI_SPLIT_TR.v
vendor/tenstorrent/aou/upstream/RTL/AXI4MUX_3X1/AOU_SPLIT_WR_PENDING_INFO.sv
vendor/tenstorrent/aou/upstream/RTL/AXI4MUX_3X1/AOU_SPLIT_RD_PENDING_INFO.sv
vendor/tenstorrent/aou/upstream/RTL/AXI4MUX_3X1/AOU_AGGREGATOR.v
vendor/tenstorrent/aou/upstream/RTL/AXI4MUX_3X1/AOU_AGGREGATOR_INFO.sv
vendor/tenstorrent/aou/upstream/RTL/LIB/AOU_SOC_BUF.v
vendor/tenstorrent/aou/upstream/RTL/LIB/AOU_SOC_GFMUX_LVT.v
vendor/tenstorrent/aou/upstream/RTL/LIB/AOU_SOC_SYNCHSR.v
vendor/tenstorrent/aou/upstream/RTL/LIB/ASYNC_APB_BRIDGE/ASYNC_APB_BRIDGE_MI.v
vendor/tenstorrent/aou/upstream/RTL/LIB/ASYNC_APB_BRIDGE/ASYNC_APB_BRIDGE_SI.v
vendor/tenstorrent/aou/upstream/RTL/LIB/ASYNC_APB_BRIDGE/ASYNC_APB_BRIDGE.v

