+incdir+hw/common/defs
+incdir+hw/common/assert
+incdir+hw/common/assert
+incdir+hw/common/defs
+incdir+hw/ip/efuse/rtl/svh
+incdir+vendor/chipsalliance/Cores-VeeR-EL2/overlay/snapshots/sep
+incdir+vendor/chipsalliance/Cores-VeeR-EL2/upstream/design/include
+incdir+vendor/lowRISC/opentitan/upstream/hw/ip/prim/rtl
+incdir+vendor/pulp-platform/apb/upstream/include
+incdir+vendor/pulp-platform/axi/upstream/include
+incdir+vendor/pulp-platform/axi_stream/upstream/include
+incdir+vendor/pulp-platform/common_cells/upstream/include
+incdir+vendor/pulp-platform/idma/overlay/target/rtl/include
+incdir+vendor/pulp-platform/idma/upstream/src/include
+incdir+vendor/pulp-platform/obi/upstream/include
+incdir+vendor/pulp-platform/register_interface/upstream/include
+incdir+vendor/tenstorrent/tt-hw-debug/upstream/dependencies/common
+incdir+vendor/tenstorrent/tt-hw-debug/upstream/rtl
+incdir+vendor/tenstorrent/tt-hw-debug/upstream/rtl/cla
+incdir+vendor/tenstorrent/tt-hw-debug/upstream/rtl/mmr
+incdir+vendor/tenstorrent/tt-hw-debug/upstream/rtl/trace
+define+TARGET_APB_RTL
+define+TARGET_AXI_RTL
+define+TARGET_COMMON_CELLS_RTL
+define+TARGET_COMMON_CELL_SYNC_SHIM
+define+TARGET_DTP
+define+TARGET_FLIST
+define+TARGET_REGISTER_INTERFACE_L1
+define+TARGET_SIMULATION
// Package(common_verification) Target(any(simulation, verilator))
vendor/pulp-platform/common_verification/upstream/src/clk_rst_gen.sv
vendor/pulp-platform/common_verification/upstream/src/sim_timeout.sv
vendor/pulp-platform/common_verification/upstream/src/stream_watchdog.sv
vendor/pulp-platform/common_verification/upstream/src/signal_highlighter.sv
// Package(common_verification) Target(simulation)
vendor/pulp-platform/common_verification/upstream/src/rand_verif_pkg.sv
// Package(common_cells) Target(*)
vendor/pulp-platform/common_cells/upstream/src/cf_math_pkg.sv
// Package(common_cells) Target(any(sep_wrapper, smu_wrapper, all(common_cells_rtl, not(all(vivado_ipx, xilinx)))))
vendor/pulp-platform/common_cells/upstream/src/fifo_v3.sv
vendor/pulp-platform/common_cells/upstream/src/counter.sv
// Package(common_cells) Target(common_cells_rtl)
vendor/pulp-platform/common_cells/upstream/src/binary_to_gray.sv
// Package(common_cells) Target(all(common_cells_rtl, not(all(vivado_ipx, xilinx))))
vendor/pulp-platform/common_cells/upstream/src/cb_filter_pkg.sv
vendor/pulp-platform/common_cells/upstream/src/cc_onehot.sv
vendor/pulp-platform/common_cells/upstream/src/cdc_reset_ctrlr_pkg.sv
vendor/pulp-platform/common_cells/upstream/src/credit_counter.sv
vendor/pulp-platform/common_cells/upstream/src/delta_counter.sv
vendor/pulp-platform/common_cells/upstream/src/ecc_pkg.sv
vendor/pulp-platform/common_cells/upstream/src/edge_propagator_tx.sv
vendor/pulp-platform/common_cells/upstream/src/exp_backoff.sv
vendor/pulp-platform/common_cells/upstream/src/gray_to_binary.sv
vendor/pulp-platform/common_cells/upstream/src/heaviside.sv
vendor/pulp-platform/common_cells/upstream/src/isochronous_4phase_handshake.sv
vendor/pulp-platform/common_cells/upstream/src/isochronous_spill_register.sv
vendor/pulp-platform/common_cells/upstream/src/lfsr.sv
vendor/pulp-platform/common_cells/upstream/src/lfsr_16bit.sv
vendor/pulp-platform/common_cells/upstream/src/lfsr_8bit.sv
vendor/pulp-platform/common_cells/upstream/src/lossy_valid_to_stream.sv
vendor/pulp-platform/common_cells/upstream/src/mv_filter.sv
vendor/pulp-platform/common_cells/upstream/src/onehot_to_bin.sv
vendor/pulp-platform/common_cells/upstream/src/plru_tree.sv
vendor/pulp-platform/common_cells/upstream/src/passthrough_stream_fifo.sv
vendor/pulp-platform/common_cells/upstream/src/popcount.sv
vendor/pulp-platform/common_cells/upstream/src/ring_buffer.sv
vendor/pulp-platform/common_cells/upstream/src/rr_arb_tree.sv
vendor/pulp-platform/common_cells/upstream/src/serial_deglitch.sv
vendor/pulp-platform/common_cells/upstream/src/shift_reg.sv
vendor/pulp-platform/common_cells/upstream/src/shift_reg_gated.sv
vendor/pulp-platform/common_cells/upstream/src/spill_register_flushable.sv
vendor/pulp-platform/common_cells/upstream/src/stream_demux.sv
vendor/pulp-platform/common_cells/upstream/src/stream_filter.sv
vendor/pulp-platform/common_cells/upstream/src/stream_fork.sv
vendor/pulp-platform/common_cells/upstream/src/stream_intf.sv
vendor/pulp-platform/common_cells/upstream/src/stream_join_dynamic.sv
vendor/pulp-platform/common_cells/upstream/src/stream_mux.sv
vendor/pulp-platform/common_cells/upstream/src/stream_throttle.sv
vendor/pulp-platform/common_cells/upstream/src/sub_per_hash.sv
vendor/pulp-platform/common_cells/upstream/src/unread.sv
vendor/pulp-platform/common_cells/upstream/src/read.sv
vendor/pulp-platform/common_cells/upstream/src/addr_decode_dync.sv
vendor/pulp-platform/common_cells/upstream/src/boxcar.sv
vendor/pulp-platform/common_cells/upstream/src/cdc_2phase.sv
vendor/pulp-platform/common_cells/upstream/src/cdc_4phase.sv
vendor/pulp-platform/common_cells/upstream/src/trip_counter.sv
vendor/pulp-platform/common_cells/upstream/src/addr_decode.sv
vendor/pulp-platform/common_cells/upstream/src/addr_decode_napot.sv
vendor/pulp-platform/common_cells/upstream/src/multiaddr_decode.sv
vendor/pulp-platform/common_cells/upstream/src/cb_filter.sv
vendor/pulp-platform/common_cells/upstream/src/cdc_fifo_2phase.sv
vendor/pulp-platform/common_cells/upstream/src/ecc_decode.sv
vendor/pulp-platform/common_cells/upstream/src/ecc_encode.sv
vendor/pulp-platform/common_cells/upstream/src/lzc.sv
vendor/pulp-platform/common_cells/upstream/src/max_counter.sv
vendor/pulp-platform/common_cells/upstream/src/spill_register.sv
vendor/pulp-platform/common_cells/upstream/src/stream_delay.sv
vendor/pulp-platform/common_cells/upstream/src/stream_fifo.sv
vendor/pulp-platform/common_cells/upstream/src/stream_fork_dynamic.sv
vendor/pulp-platform/common_cells/upstream/src/stream_join.sv
vendor/pulp-platform/common_cells/upstream/src/cdc_reset_ctrlr.sv
vendor/pulp-platform/common_cells/upstream/src/cdc_fifo_gray.sv
vendor/pulp-platform/common_cells/upstream/src/fall_through_register.sv
vendor/pulp-platform/common_cells/upstream/src/id_queue.sv
vendor/pulp-platform/common_cells/upstream/src/stream_to_mem.sv
vendor/pulp-platform/common_cells/upstream/src/stream_arbiter_flushable.sv
vendor/pulp-platform/common_cells/upstream/src/stream_fifo_optimal_wrap.sv
vendor/pulp-platform/common_cells/upstream/src/stream_register.sv
vendor/pulp-platform/common_cells/upstream/src/stream_xbar.sv
vendor/pulp-platform/common_cells/upstream/src/cdc_fifo_gray_clearable.sv
vendor/pulp-platform/common_cells/upstream/src/cdc_2phase_clearable.sv
vendor/pulp-platform/common_cells/upstream/src/mem_to_banks_detailed.sv
vendor/pulp-platform/common_cells/upstream/src/stream_arbiter.sv
vendor/pulp-platform/common_cells/upstream/src/stream_omega_net.sv
vendor/pulp-platform/common_cells/upstream/src/mem_to_banks.sv
// Package(apb) Target(*)
vendor/pulp-platform/apb/upstream/apb_pkg.sv
// Package(apb) Target(apb_rtl)
vendor/pulp-platform/apb/upstream/apb_intf.sv
vendor/pulp-platform/apb/upstream/apb_cdc.sv
vendor/pulp-platform/apb/upstream/apb_demux.sv
// Package(axi) Target(*)
vendor/pulp-platform/axi/upstream/src/axi_pkg.sv
// Package(axi) Target(axi_rtl)
vendor/pulp-platform/axi/upstream/src/axi_demux_id_counters.sv
vendor/pulp-platform/axi/upstream/src/axi_intf.sv
vendor/pulp-platform/axi/upstream/src/axi_atop_filter.sv
vendor/pulp-platform/axi/upstream/src/axi_burst_splitter_gran.sv
vendor/pulp-platform/axi/upstream/src/axi_burst_unwrap.sv
vendor/pulp-platform/axi/upstream/src/axi_bus_compare.sv
vendor/pulp-platform/axi/upstream/src/axi_cdc_dst.sv
vendor/pulp-platform/axi/upstream/src/axi_cdc_src.sv
vendor/pulp-platform/axi/upstream/src/axi_cut.sv
vendor/pulp-platform/axi/upstream/src/axi_delayer.sv
vendor/pulp-platform/axi/upstream/src/axi_demux_simple.sv
vendor/pulp-platform/axi/upstream/src/axi_dw_downsizer.sv
vendor/pulp-platform/axi/upstream/src/axi_dw_upsizer.sv
vendor/pulp-platform/axi/upstream/src/axi_fifo.sv
vendor/pulp-platform/axi/upstream/src/axi_fifo_delay_dyn.sv
vendor/pulp-platform/axi/upstream/src/axi_id_remap.sv
vendor/pulp-platform/axi/upstream/src/axi_id_prepend.sv
vendor/pulp-platform/axi/upstream/src/axi_inval_filter.sv
vendor/pulp-platform/axi/upstream/src/axi_isolate.sv
vendor/pulp-platform/axi/upstream/src/axi_join.sv
vendor/pulp-platform/axi/upstream/src/axi_lite_demux.sv
vendor/pulp-platform/axi/upstream/src/axi_lite_dw_converter.sv
vendor/pulp-platform/axi/upstream/src/axi_lite_from_mem.sv
vendor/pulp-platform/axi/upstream/src/axi_lite_isolate.sv
vendor/pulp-platform/axi/upstream/src/axi_lite_join.sv
vendor/pulp-platform/axi/upstream/src/axi_lite_lfsr.sv
vendor/pulp-platform/axi/upstream/src/axi_lite_mailbox.sv
vendor/pulp-platform/axi/upstream/src/axi_lite_mux.sv
vendor/pulp-platform/axi/upstream/src/axi_lite_regs.sv
vendor/pulp-platform/axi/upstream/src/axi_lite_to_apb.sv
vendor/pulp-platform/axi/upstream/src/axi_lite_to_axi.sv
vendor/pulp-platform/axi/upstream/src/axi_modify_address.sv
vendor/pulp-platform/axi/upstream/src/axi_mux.sv
vendor/pulp-platform/axi/upstream/src/axi_rw_join.sv
vendor/pulp-platform/axi/upstream/src/axi_rw_split.sv
vendor/pulp-platform/axi/upstream/src/axi_serializer.sv
vendor/pulp-platform/axi/upstream/src/axi_slave_compare.sv
vendor/pulp-platform/axi/upstream/src/axi_throttle.sv
vendor/pulp-platform/axi/upstream/src/axi_to_detailed_mem.sv
vendor/pulp-platform/axi/upstream/src/axi_burst_splitter.sv
vendor/pulp-platform/axi/upstream/src/axi_cdc.sv
vendor/pulp-platform/axi/upstream/src/axi_cdc_clearable.sv
vendor/pulp-platform/axi/upstream/src/axi_demux.sv
vendor/pulp-platform/axi/upstream/src/axi_dw_converter.sv
vendor/pulp-platform/axi/upstream/src/axi_from_mem.sv
vendor/pulp-platform/axi/upstream/src/axi_id_serialize.sv
vendor/pulp-platform/axi/upstream/src/axi_lfsr.sv
vendor/pulp-platform/axi/upstream/src/axi_multicut.sv
vendor/pulp-platform/axi/upstream/src/axi_to_axi_lite.sv
vendor/pulp-platform/axi/upstream/src/axi_to_mem.sv
vendor/pulp-platform/axi/upstream/src/axi_zero_mem.sv
vendor/pulp-platform/axi/upstream/src/axi_interleaved_xbar.sv
vendor/pulp-platform/axi/upstream/src/axi_iw_converter.sv
vendor/pulp-platform/axi/upstream/src/axi_lite_xbar.sv
vendor/pulp-platform/axi/upstream/src/axi_xbar_unmuxed.sv
vendor/pulp-platform/axi/upstream/src/axi_to_mem_banked.sv
vendor/pulp-platform/axi/upstream/src/axi_to_mem_interleaved.sv
vendor/pulp-platform/axi/upstream/src/axi_to_mem_split.sv
vendor/pulp-platform/axi/upstream/src/axi_xbar.sv
vendor/pulp-platform/axi/upstream/src/axi_xp.sv
vendor/pulp-platform/axi/upstream/src/axi_spill_regs.sv
vendor/pulp-platform/axi/upstream/src/axi5_lite_mux.sv
vendor/pulp-platform/axi/upstream/src/axi5_lite_mux_brcst.sv
vendor/pulp-platform/axi/upstream/src/axi5_lite_demux.sv
vendor/pulp-platform/axi/upstream/src/axi5_lite_demux_brcst.sv
vendor/pulp-platform/axi/upstream/src/axi5_lite_xbar.sv
vendor/pulp-platform/axi/upstream/src/axi5_lite_xbar_brcst.sv
vendor/pulp-platform/axi/upstream/src/axi_hidestrb.sv
// Package(axi) Target(any(axi_rtl, sep_wrapper, smu_wrapper))
vendor/pulp-platform/axi/upstream/src/axi_err_slv.sv
// Package(axi_stream) Target(*)
vendor/pulp-platform/axi_stream/upstream/src/axi_stream_intf.sv
vendor/pulp-platform/axi_stream/upstream/src/axi_stream_cut.sv
vendor/pulp-platform/axi_stream/upstream/src/axi_stream_dw_downsizer.sv
vendor/pulp-platform/axi_stream/upstream/src/axi_stream_dw_upsizer.sv
vendor/pulp-platform/axi_stream/upstream/src/axi_stream_multicut.sv
// Package(obi) Target(*)
vendor/pulp-platform/obi/upstream/src/obi_pkg.sv
// Package(register_interface) Target(register_interface_l1)
vendor/pulp-platform/register_interface/../../../vendor/lowRISC/opentitan/upstream/hw/ip/prim/rtl/prim_subreg_pkg.sv
vendor/pulp-platform/register_interface/../../../vendor/lowRISC/opentitan/upstream/hw/ip/prim/rtl/prim_mubi_pkg.sv
vendor/pulp-platform/register_interface/upstream/src/reg_intf.sv
vendor/pulp-platform/register_interface/upstream/src/reg_demux.sv
vendor/pulp-platform/register_interface/upstream/src/reg_mux.sv
vendor/pulp-platform/register_interface/upstream/src/periph_to_reg.sv
vendor/pulp-platform/register_interface/upstream/src/axi_to_reg_v2.sv
// Package(opentitan) Target(any(cross_trigger, dtp, entropy_source, key_manager, opentitan_smu, sep, smc, smu, system_timer_octs, uart))
vendor/lowRISC/opentitan/upstream/hw/ip/prim/rtl/prim_util_pkg.sv
vendor/lowRISC/opentitan/upstream/hw/ip/prim/rtl/prim_count_pkg.sv
vendor/lowRISC/opentitan/upstream/hw/ip/prim/rtl/prim_ram_1p_pkg.sv
vendor/lowRISC/opentitan/upstream/hw/ip/prim/rtl/prim_count.sv
vendor/lowRISC/opentitan/upstream/hw/ip/prim/rtl/prim_edge_detector.sv
vendor/lowRISC/opentitan/upstream/hw/ip/prim/rtl/prim_fifo_sync.sv
vendor/lowRISC/opentitan/upstream/hw/ip/prim/rtl/prim_fifo_sync_cnt.sv
// Package(opentitan) Target(all(any(cross_trigger, dtp, entropy_source, key_manager, opentitan_smu, sep, smc, smu, system_timer_octs, uart), not(synth)))
vendor/lowRISC/opentitan/upstream/hw/ip/prim_generic/rtl/prim_and2.sv
vendor/lowRISC/opentitan/upstream/hw/ip/prim_generic/rtl/prim_buf.sv
vendor/lowRISC/opentitan/upstream/hw/ip/prim_generic/rtl/prim_clock_buf.sv
vendor/lowRISC/opentitan/upstream/hw/ip/prim_generic/rtl/prim_clock_gating.sv
vendor/lowRISC/opentitan/upstream/hw/ip/prim_generic/rtl/prim_clock_inv.sv
vendor/lowRISC/opentitan/upstream/hw/ip/prim_generic/rtl/prim_clock_mux2.sv
vendor/lowRISC/opentitan/upstream/hw/ip/prim_generic/rtl/prim_flop.sv
vendor/lowRISC/opentitan/upstream/hw/ip/prim_generic/rtl/prim_flop_2sync.sv
vendor/lowRISC/opentitan/upstream/hw/ip/prim_generic/rtl/prim_inv.sv
vendor/lowRISC/opentitan/upstream/hw/ip/prim_generic/rtl/prim_xnor2.sv
vendor/lowRISC/opentitan/upstream/hw/ip/prim_generic/rtl/prim_xor2.sv
// Package(opentitan) Target(all(simulation, any(cross_trigger, dtp, system_timer_octs, uart)))
vendor/lowRISC/opentitan/upstream/hw/ip/prim/rtl/prim_cdc_rand_delay.sv
// Package(tt-oca-harness) Target(all(dtp, not(sep)))
hw/sys/sep/regs/gen/sv/sep_addrmap_pkg.sv
// Package(tt-oca-harness) Target(any(dtp, key_manager, sep, smc, system_timer_octs, uart))
hw/common/och_prim/rtl/prim_jtag_pkg.sv
hw/common/och_prim/rtl/prim_ram_1p_adv_ext_pkg.sv
// Package(tt-oca-harness) Target(any(cross_trigger, dtp))
hw/ip/cross_trigger/cross_trigger_matrix/regs/gen/sv/cross_trigger_matrix_addrmap_pkg.sv
hw/ip/cross_trigger/cross_trigger_matrix/regs/gen/sv/cross_trigger_matrix_reg_pkg.sv
hw/ip/cross_trigger/cross_trigger_matrix/rtl/cross_trigger_matrix_pkg.sv
hw/ip/cross_trigger/cross_trigger_network/regs/gen/sv/cross_trigger_network_addrmap_pkg.sv
hw/ip/cross_trigger/cross_trigger_network/rtl/cross_trigger_network_pkg.sv
hw/ip/cross_trigger/cross_trigger_port/regs/gen/sv/cross_trigger_port_reg_pkg.sv
hw/ip/cross_trigger/cross_trigger_port/rtl/cross_trigger_port_pkg.sv
// Package(tt-oca-harness) Target(any(dtp, sep, smc))
hw/ip/efuse/rtl/efuse_pkg.sv
// Package(tt-oca-harness) Target(dtp)
hw/ip/jtag/jtag_ptap/rtl/jtag_inst_reg_pkg.sv
hw/ip/jtag/jtag_ptap/rtl/jtag_tap_pkg.sv
hw/ip/jtag/jtag_ptap/rtl/jtag_tmp_pkg.sv
hw/sys/dtp/rtl/dtp_pkg.sv
// Package(tt-oca-harness) Target(any(dtp, sep))
hw/sys/sep/rtl/sep_lifecycle_ctrl_pkg.sv
hw/sys/sep/rtl/efuse/sep_efuse_pkg.sv
// Package(tt-oca-harness) Target(any(axi_hang_detector, dtp, key_manager, sep, smc, system_timer_octs, uart))
hw/common/och_prim/rtl/prim_axi_snoop.sv
// Package(tt-oca-harness) Target(any(dtp, key_manager, sep, smc, system_timer_octs, uart))
hw/common/och_prim/rtl/prim_ag_clk_mux.sv
hw/common/och_prim/rtl/prim_apb_arb.sv
hw/common/och_prim/rtl/prim_axi_addr_fixer.sv
hw/common/och_prim/rtl/prim_axi_id_converter.sv
hw/common/och_prim/rtl/prim_axi_id_prepend_wrap.sv
hw/common/och_prim/rtl/prim_axi_lite_err_slv.sv
hw/common/och_prim/rtl/prim_axi_lite_to_apb_single.sv
hw/common/och_prim/rtl/prim_axi_user_override.sv
hw/common/och_prim/rtl/prim_axil_addr_fixer.sv
hw/common/och_prim/rtl/prim_axil_prot_filter.sv
hw/common/och_prim/rtl/prim_bin2gray.sv
hw/common/och_prim/rtl/prim_carry_select_adder.sv
hw/common/och_prim/rtl/prim_cg_req.sv
hw/common/och_prim/rtl/prim_clk_counter.sv
hw/common/och_prim/rtl/prim_clk_counter_fifo_sync.sv
hw/common/och_prim/rtl/prim_clk_gater_hysteresis.sv
hw/common/och_prim/rtl/prim_clkmux4.sv
hw/common/och_prim/rtl/prim_diff_decode_multi.sv
hw/common/och_prim/rtl/prim_diff_encode_multi.sv
hw/common/och_prim/rtl/prim_fair_rr_arb.sv
hw/common/och_prim/rtl/prim_fifo_sync_parity.sv
hw/common/och_prim/rtl/prim_gray2bin.sv
hw/common/och_prim/rtl/prim_jtag_scan_reg.sv
hw/common/och_prim/rtl/prim_jtag_sib_mux_post.sv
hw/common/och_prim/rtl/prim_jtag_sib_mux_pre.sv
hw/common/och_prim/rtl/prim_pipe_stages.sv
hw/common/och_prim/rtl/prim_prog_clk_div_posedge.sv
hw/common/och_prim/rtl/prim_pulse_signal.sv
hw/common/och_prim/rtl/prim_refclk_count_w_cdc.sv
hw/common/och_prim/rtl/prim_rev_cell.sv
hw/common/och_prim/rtl/prim_rst_mux2_hf_n.sv
hw/common/och_prim/rtl/prim_sync3.sv
hw/common/och_prim/rtl/prim_sync3_pulse.sv
hw/common/och_prim/rtl/prim_sync3r.sv
hw/common/och_prim/rtl/prim_sync4.sv
hw/common/och_prim/rtl/prim_sync4r.sv
hw/common/och_prim/rtl/prim_sync_data_autohs.sv
hw/common/och_prim/rtl/prim_sync_reset.sv
hw/common/och_prim/rtl/prim_updown_counter.sv
hw/common/och_prim/rtl/prim_zero_counter.sv
hw/common/sync.sv
// Package(tt-oca-harness) Target(all(any(dtp, entropy_source, key_manager, sep, smc, system_timer_octs, uart), not(synth)))
hw/common/och_prim_generic/rtl/prim_ao222.sv
hw/common/och_prim_generic/rtl/prim_clock_nand2.sv
hw/common/och_prim_generic/rtl/prim_flop_3sync.sv
hw/common/och_prim_generic/rtl/prim_flop_3sync_r.sv
hw/common/och_prim_generic/rtl/prim_flop_3sync_s.sv
hw/common/och_prim_generic/rtl/prim_flop_4sync.sv
hw/common/och_prim_generic/rtl/prim_flop_4sync_r.sv
hw/common/och_prim_generic/rtl/prim_flop_4sync_s.sv
hw/common/och_prim_generic/rtl/prim_latch_n.sv
hw/common/och_prim_generic/rtl/prim_metastab_hardened_dffr.sv
hw/common/och_prim_generic/rtl/prim_nand4.sv
hw/common/och_prim_generic/rtl/prim_nor4.sv
hw/common/och_prim_generic/rtl/prim_or2.sv
hw/common/och_prim_generic/rtl/prim_or4.sv
hw/common/och_prim_generic/rtl/prim_stdmux2.sv
// Package(tt-oca-harness) Target(any(cross_trigger, dtp))
hw/ip/cross_trigger/cross_trigger_matrix/regs/gen/sv/cross_trigger_matrix_reg.sv
hw/ip/cross_trigger/cross_trigger_matrix/rtl/cross_trigger_matrix.sv
hw/ip/cross_trigger/cross_trigger_matrix/rtl/ctm_src_selector.sv
hw/ip/cross_trigger/cross_trigger_network/rtl/cross_trigger_network.sv
hw/ip/cross_trigger/cross_trigger_network/rtl/ctn_clock_stop_ctrl.sv
hw/ip/cross_trigger/cross_trigger_port/regs/gen/sv/cross_trigger_port_reg.sv
hw/ip/cross_trigger/cross_trigger_port/rtl/cross_trigger_port.sv
hw/ip/cross_trigger/cross_trigger_port/rtl/cross_trigger_port_core.sv
hw/ip/cross_trigger/cross_trigger_port/rtl/ctp_edge_detector.sv
hw/ip/cross_trigger/cross_trigger_port/rtl/ctp_handshake_ctrl.sv
hw/ip/cross_trigger/cross_trigger_port/rtl/ctp_pulse_stretcher.sv
hw/ip/cross_trigger/cross_trigger_port/rtl/ctp_synchronizer.sv
// Package(tt-oca-harness) Target(dtp)
hw/ip/jtag/jtag2axi/rtl/jtag2axi.sv
hw/ip/jtag/jtag_intf_unit/rtl/jtag_intf_unit.sv
hw/ip/jtag/jtag_ptap/rtl/jtag_3dcr_reg.sv
hw/ip/jtag/jtag_ptap/rtl/jtag_byp_reg.sv
hw/ip/jtag/jtag_ptap/rtl/jtag_caps_reg.sv
hw/ip/jtag/jtag_ptap/rtl/jtag_debug_ctrl_reg.sv
hw/ip/jtag/jtag_ptap/rtl/jtag_ic_reset_reg.sv
hw/ip/jtag/jtag_ptap/rtl/jtag_idcode_reg.sv
hw/ip/jtag/jtag_ptap/rtl/jtag_inst_reg.sv
hw/ip/jtag/jtag_ptap/rtl/jtag_inv_byp_reg.sv
hw/ip/jtag/jtag_ptap/rtl/jtag_jtag2axi_caps_reg.sv
hw/ip/jtag/jtag_ptap/rtl/jtag_ptap.sv
hw/ip/jtag/jtag_ptap/rtl/jtag_tap_ctrlr.sv
hw/ip/jtag/jtag_ptap/rtl/jtag_tmp.sv
hw/ip/jtag/jtag_ptap/rtl/jtag_tmp_status_reg.sv
hw/ip/jtag/jtag_stap/rtl/jtag_stap.sv
hw/sys/dtp/rtl/dtp.sv

hw/sys/dtp/dv/tb/dtp_dv_cfg_pkg.sv
hw/sys/dtp/dv/tb/dtp_j2a_state_flags.sv
hw/common/dv/vip/ocah_jtag_vip/interface/ocah_jtag_if.sv
hw/common/dv/vip/ocah_axi_vip/interface/ocah_axi_if.sv
hw/common/dv/vip/ocah_jtag_vip/sva/ocah_jtag_sva.sv
hw/common/dv/vip/ocah_axi_vip/sva/ocah_axi_sva.sv
hw/sys/dtp/dv/tb/dtp_tb_if.sv
hw/sys/dtp/dv/tb/dtp_scan_if.sv
hw/sys/dtp/dv/tb/dtp_xtrig_if.sv
hw/sys/dtp/dv/cov/sv/dtp_fcov.sv
hw/sys/dtp/dv/cov/sv/dtp_jtag2axi_fcov.sv
hw/sys/dtp/dv/cov/sv/dtp_debug_tdr_fcov.sv
hw/sys/dtp/dv/cov/sv/dtp_scan_fcov.sv
hw/sys/dtp/dv/cov/sv/dtp_xtrig_fcov.sv
hw/sys/dtp/dv/tb/tb_top.sv
