# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2026 Tenstorrent USA, Inc.
"""Write smc_cov_scope.hier, the VCS coverage scope of the smc DUT.

The scope follows the rule the SEP scope states: the bench, the CPU subtree
and the library cells leave the database, and functional third-party IP stays
graded regardless of authorship. VCS scopes by design unit, and the trees to
drop are instantiated at hundreds of places inside SMC's own modules where no
instance tree reaches them, so this lists every module, interface and program
the build compiled from those trees as a `-module` line, grouped by the reason
it leaves.

    python3 hw/sys/smc/dv/cov/config/vcs/gen_smc_cov_scope.py [--check]

Reads the filelists a `run_dv.py --dut smc` build leaves under
hw/sys/smc/dv/build, so run a build (any tool) first; `--check` exits 1 when
the committed file is out of date instead of rewriting it.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[6]
FILELISTS = (
    ROOT / "hw/sys/smc/dv/build/smc_dut_compile.f",
    ROOT / "hw/sys/smc/dv/build/smc_bender.f",
)
OUT = HERE / "smc_cov_scope.hier"

# The same trees ../verilator/smc_cov_scope.vlt names with coverage_off.
# (reason, source-path matcher). A unit compiled from a matching path leaves the
# database under that reason; every other compiled unit stays graded. Library
# cells are leaf primitives (pulp common_cells, the OpenTitan and OCAH prim
# libraries); interconnect cells are the vendored AXI/APB mux, demux, crossbar
# and converter children, whose SMC-side wrappers stay graded.
DROPPED: tuple[tuple[str, re.Pattern[str]], ...] = (
    ("bench", re.compile(r"/hw/sys/smc/dv/(tb|models)/|/hw/ip/[^/]+/dv/")),
    ("cpu subtree", re.compile(r"chipyard_generated_files/")),
    ("library cells", re.compile(r"/vendor/pulp-platform/common_cells/")),
    ("library cells", re.compile(r"/vendor/lowRISC/opentitan/.*/prim[^/]*/")),
    ("library cells", re.compile(r"/hw/common/och_prim/")),
    (
        "interconnect cells",
        re.compile(r"/vendor/pulp-platform/(axi|apb|register_interface|axi_stream|obi)/"),
    ),
)
# Units dropped by name: packages carry no logic and would otherwise report an
# assertion row of their own.
DROPPED_UNITS: tuple[tuple[str, str], ...] = (("package", "axi_pkg"),)
# Instance trees dropped whole, the way SEP drops `sep_cpu`: a large third-party
# block that one SMC leaf reaches and that carries its own block bench
# (hw/ip/i3ccore_wrap/dv), so its internals are graded there.
DROPPED_TREES: tuple[tuple[str, str], ...] = (
    ("i3c controllers", "smc_uvm_top.u_dut.u_smc.u_smc_peripherals.u_i3ccore_wrapper"),
)
UNIT = re.compile(
    r"^\s*(?:module|macromodule|interface|program)\s+(?:automatic\s+)?"
    r"([A-Za-z_][A-Za-z0-9_$]*)",
    re.M,
)
COMMENTS = re.compile(r"//[^\n]*|/\*.*?\*/", re.S)

HEADER = """\
// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 Tenstorrent USA, Inc.
//
// VCS coverage scope for the smc DUT. Generated by gen_smc_cov_scope.py from
// the build filelists on the rule the SEP scope states: the bench, the CPU
// subtree, the library cells and one barely-exercised third-party block with
// a bench of its own leave the database; every other functional third-party
// IP stays graded regardless of authorship. Dropped design units are named,
// because they are instantiated inside SMC's own modules where no instance
// tree reaches them. README.md says what stays and why.
//
// Regenerate after a build whenever the compiled source set changes.

-tree smc_uvm_top 1
"""


def compiled_sources() -> list[Path]:
    out: list[Path] = []
    for fl in FILELISTS:
        if not fl.is_file():
            raise SystemExit(f"{fl} not found: run a --dut smc build first")
        for line in fl.read_text().splitlines():
            line = line.strip()
            if line.endswith((".sv", ".v")) and not line.startswith(("+", "-")):
                out.append(Path(line))
    return out


def excluded_units(sources: list[Path]) -> dict[str, list[str]]:
    """Map each drop reason to the sorted design units compiled from its trees."""
    units: dict[str, set[str]] = {reason: set() for reason, _ in DROPPED}
    for src in sources:
        reason = next((r for r, pattern in DROPPED if pattern.search(str(src))), None)
        if reason is None:
            continue
        try:
            text = COMMENTS.sub("", src.read_text(errors="replace"))
        except OSError:
            continue
        units[reason].update(m.group(1) for m in UNIT.finditer(text))
    for reason, unit in DROPPED_UNITS:
        units.setdefault(reason, set()).add(unit)
    return {reason: sorted(names) for reason, names in units.items() if names}


def render(units: dict[str, list[str]]) -> str:
    out = [HEADER]
    for reason, tree in DROPPED_TREES:
        out.append(f"\n// {reason}\n-tree {tree}\n")
    for reason in sorted(units):
        out.append(f"\n// {reason}\n")
        out.extend(f"-module {u}\n" for u in units[reason])
    return "".join(out)


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n", maxsplit=1)[0])
    ap.add_argument("--check", action="store_true", help="fail if the file is out of date")
    args = ap.parse_args(argv)
    text = render(excluded_units(compiled_sources()))
    if args.check:
        if OUT.read_text() != text:
            print(f"{OUT} is out of date; rerun without --check", file=sys.stderr)
            return 1
        return 0
    OUT.write_text(text)
    print(f"{OUT}: {text.count('-module ')} units excluded")
    return 0


if __name__ == "__main__":
    sys.exit(main())
