#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2026 Tenstorrent USA, Inc.
"""Write smc_ports_only_exclusions.el: the line and condition points of ports-only units.

T2 to T12 are the units smc_reviewed_exclusions.toml records as graded on their
ports: the unit's own ports stay in the score and the points inside it leave
while the run leaves them uncovered.
Their toggle points go to the toggle files
gen_smc_toggle_exclusions.py writes; this file holds their line blocks and
condition rows while the run's raw report leaves them uncovered. The same
units' register-block and FSM points go to smc_regblock_exclusions.el and
smc_fsm_exclusions.el, which gen_smc_cov_exclusions.py writes from the same
plan.

Input is the templates urg writes for the merged database and the run's raw
report::

    urg -dir <run dir>/cov/merged.vdb -dump full_exclusions tgl+line+fsm+cond+branch \
        -report <dir>

    python3 gen_smc_ports_only_exclusions.py <template dir> <run dir>/cov/report_raw/modinfo.txt
    python3 gen_smc_ports_only_exclusions.py <template dir> <modinfo> --check
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import smc_toggle_exclusions as toggles

HERE = Path(__file__).resolve().parent
OUT = HERE / "smc_ports_only_exclusions.el"

HEADER = (
    "// SPDX-License-Identifier: Apache-2.0",
    "// SPDX-FileCopyrightText: 2026 Tenstorrent USA, Inc.",
    "//==================================================",
    "// SMC VCS coverage exclusions -- units graded on their ports.",
    "// Format Version: 2",
    "// ExclMode: default",
    "//",
    "// Generated by gen_smc_ports_only_exclusions.py from urg's templates and",
    "// the run's raw report; regenerate from each graded run rather than edit.",
    "// T2 to T12 keep each unit's ports graded; this file holds the uncovered",
    "// line blocks and condition rows inside the units smc_reviewed_exclusions.toml",
    "// records. Their toggle points are in smc_toggle_module_exclusions.el and",
    "// smc_toggle_instance_exclusions.el. README.md states every class.",
    "//==================================================",
)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("template_dir", type=Path, help="holds the fullexclude templates")
    ap.add_argument("modinfo", type=Path, help="the run's cov/report_raw/modinfo.txt")
    ap.add_argument("--check", action="store_true", help="fail if the committed file is stale")
    args = ap.parse_args()
    _, planner = toggles.plan(args.template_dir, args.modinfo)
    units, counts = planner.blocks(planner.manifest.classes_in(OUT.name))
    text = "\n".join([*HEADER, *units]) + "\n"
    if args.check:
        if not OUT.is_file() or OUT.read_text() != text:
            print(f"{OUT} is stale; rerun without --check", file=sys.stderr)
            return 1
        return 0
    OUT.write_text(text)
    print(f"wrote {OUT.name}: " + ", ".join(f"{k} {v}" for k, v in sorted(counts.items())))
    return 0


if __name__ == "__main__":
    sys.exit(main())
