# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2026 Tenstorrent USA, Inc.
"""Write smc_cov_scope.hier, the VCS form of ../verilator/smc_cov_scope.vlt.

Verilator scopes coverage by source file and VCS by design unit, and the
trees the SMC bench does not own -- vendored RTL, hw/ip, hw/common, the
chipyard-generated CPU cluster, the bench's own models -- are instantiated
at hundreds of places inside SMC's own modules, so no instance tree reaches
them. `-module` does: this lists every module, interface and program the
build compiled from those trees, so a `-cm_hier` file names the same set the
Verilator globs drop.

    python3 hw/sys/smc/dv/cov/config/vcs/gen_smc_cov_scope.py [--check]

Reads the filelists a `run_dv.py --dut smc` build leaves under
hw/sys/smc/dv/build, so run a build (any tool) first; `--check` exits 1 when
the committed file is out of date instead of rewriting it.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[6]
FILELISTS = (
    ROOT / "hw/sys/smc/dv/build/smc_dut_compile.f",
    ROOT / "hw/sys/smc/dv/build/smc_bender.f",
)
OUT = HERE / "smc_cov_scope.hier"

# The same trees ../verilator/smc_cov_scope.vlt names with coverage_off.
NOT_OWNED = re.compile(
    r"/(vendor|hw/ip|hw/common)/|chipyard_generated_files/|/hw/sys/smc/dv/(tb|models)/"
)
UNIT = re.compile(
    r"^\s*(?:module|macromodule|interface|program)\s+(?:automatic\s+)?"
    r"([A-Za-z_][A-Za-z0-9_$]*)",
    re.M,
)
COMMENTS = re.compile(r"//[^\n]*|/\*.*?\*/", re.S)

HEADER = """\
// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 Tenstorrent USA, Inc.
//
// VCS coverage scope for the smc DUT, the -cm_hier form of
// ../verilator/smc_cov_scope.vlt. Generated by gen_smc_cov_scope.py from the
// build filelists: every design unit compiled from a tree SMC does not own is
// excluded by name, because those units are instantiated inside SMC's own
// modules where no instance tree reaches them. README.md says what stays.
//
// Regenerate after a build whenever the compiled source set changes.

-tree smc_uvm_top 1
"""


def compiled_sources() -> list[Path]:
    out: list[Path] = []
    for fl in FILELISTS:
        if not fl.is_file():
            raise SystemExit(f"{fl} not found: run a --dut smc build first")
        for line in fl.read_text().splitlines():
            line = line.strip()
            if line.endswith((".sv", ".v")) and not line.startswith(("+", "-")):
                out.append(Path(line))
    return out


def excluded_units(sources: list[Path]) -> list[str]:
    units: set[str] = set()
    for src in sources:
        if not NOT_OWNED.search(str(src)):
            continue
        try:
            text = COMMENTS.sub("", src.read_text(errors="replace"))
        except OSError:
            continue
        units.update(m.group(1) for m in UNIT.finditer(text))
    return sorted(units)


def render(units: list[str]) -> str:
    return HEADER + "".join(f"-module {u}\n" for u in units)


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n", maxsplit=1)[0])
    ap.add_argument("--check", action="store_true", help="fail if the file is out of date")
    args = ap.parse_args(argv)
    text = render(excluded_units(compiled_sources()))
    if args.check:
        if OUT.read_text() != text:
            print(f"{OUT} is out of date; rerun without --check", file=sys.stderr)
            return 1
        return 0
    OUT.write_text(text)
    print(f"{OUT}: {text.count(chr(10)) - HEADER.count(chr(10))} units excluded")
    return 0


if __name__ == "__main__":
    sys.exit(main())
