#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2026 Tenstorrent USA, Inc.
"""Write smc_group_exclusions.el from urg's group exclusion template.

`-cm_hier` scopes line, condition, FSM, toggle and branch, and with
`-cm_common_hier` the assertions too, but a covergroup declared inside RTL
follows none of them: every covergroup the elaboration instantiates lands in
urg's GROUP score. SMC grades its own `cov/sv` covergroups there; the
covergroups the vendored blocks under `u_dut` carry belong to those blocks'
own benches. This script names those covergroups, with the reason for each
class, in the exclusion file `-elfile` consumes at report time.

The input is the template urg writes for a coverage database::

    urg -dir <run dir>/cov/merged.vdb -dump full_exclusions group -report <dir>

which leaves `fullexclude.tb_def` (per definition) and `fullexclude.tb_inst`
(per instance) in the working directory. The definition form carries the
checksum urg requires and one commented `covergroup` line per instance path,
so the names and checksums below are never typed by hand.

    python3 gen_smc_group_exclusions.py <fullexclude.tb_def>
    python3 gen_smc_group_exclusions.py <fullexclude.tb_def> --check
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
OUTPUT = HERE / "smc_group_exclusions.el"
TB_TOP = "smc_uvm_top"
OWN_PREFIX = f"{TB_TOP}.u_smc_"

# (class name, matcher over the covergroup path, reason). The first match wins.
# Every covergroup under the DUT must match a class: a new one the template
# lists and no class names is a decision nobody made, and the script stops.
CLASSES: list[tuple[str, re.Pattern[str], str]] = [
    (
        "VENDORED-I3C",
        re.compile(r"\.u_i3ccore_wrapper\..*::cg_bus_event_fsm_transitions$"),
        "the target-FSM bus-event covergroup the chipsalliance I3C core declares in "
        "i3c_target_fsm.sv, one per controller. The controllers' internals are graded by "
        "hw/ip/i3ccore_wrap/dv, and the scope file already drops the u_i3ccore_wrapper "
        "tree from the code metrics; SMC's own view of them is the cov/sv points.",
    ),
]

CHECKSUM_RE = re.compile(r"^// (CHECKSUM: \".*\")$")
GROUP_RE = re.compile(r"^// covergroup (\S+)$")


def dut_groups(template: Path) -> list[tuple[str, str]]:
    """Return (checksum line, covergroup path) for every covergroup under the DUT."""
    lines = template.read_text().splitlines()
    groups: list[tuple[str, str]] = []
    checksum: str | None = None
    for line in lines:
        match = CHECKSUM_RE.match(line)
        if match:
            checksum = match.group(1)
            continue
        match = GROUP_RE.match(line)
        if not match:
            continue
        path = match.group(1)
        if path.startswith(OWN_PREFIX):
            continue
        if not path.startswith(f"{TB_TOP}."):
            sys.exit(f"{template}: covergroup outside {TB_TOP}: {path}")
        if checksum is None:
            sys.exit(f"{template}: no CHECKSUM line before `{path}`")
        groups.append((checksum, path))
    if not groups:
        sys.exit(f"{template}: no covergroup under {TB_TOP}.u_dut; nothing to exclude")
    return groups


def render(groups: list[tuple[str, str]]) -> str:
    out = [
        "// SPDX-License-Identifier: Apache-2.0",
        "// SPDX-FileCopyrightText: 2026 Tenstorrent USA, Inc.",
        "//==================================================",
        "// SMC VCS covergroup exclusions, applied with -elfile at report time.",
        "// Format Version: 2",
        "// ExclMode: default",
        "//",
        "// Generated by gen_smc_group_exclusions.py from urg's",
        "// `-dump full_exclusions group` template of the coverage database; regenerate",
        "// rather than edit. README.md beside this file states what each class",
        "// drops and why; the ANNOTATION before each class repeats the reason.",
        "//==================================================",
    ]
    by_class: dict[str, list[tuple[str, str]]] = {name: [] for name, _, _ in CLASSES}
    for checksum, path in groups:
        for name, pattern, _ in CLASSES:
            if pattern.search(path):
                by_class[name].append((checksum, path))
                break
        else:
            sys.exit(f"covergroup under the DUT matches no class; decide on it: {path}")
    for name, _, reason in CLASSES:
        rows = by_class[name]
        if not rows:
            sys.exit(f"class {name} matched no covergroup; the template or the rules moved")
        out += ["", f'ANNOTATION: "SMC-GROUP-{name}: {reason}"']
        for checksum, path in sorted(rows, key=lambda row: row[1]):
            out += [checksum, f"covergroup {path}"]
    return "\n".join(out) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("template", type=Path, help="urg fullexclude.tb_def")
    parser.add_argument("--check", action="store_true", help="fail if the file is stale")
    args = parser.parse_args()
    text = render(dut_groups(args.template))
    if args.check:
        if OUTPUT.read_text() != text:
            print(f"{OUTPUT} is stale; rerun without --check", file=sys.stderr)
            return 1
        print(f"{OUTPUT} is current")
        return 0
    OUTPUT.write_text(text)
    excluded = sum(1 for line in text.splitlines() if line.startswith("covergroup "))
    print(f"wrote {OUTPUT}: {excluded} covergroup exclusions")
    return 0


if __name__ == "__main__":
    sys.exit(main())
