// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 Tenstorrent USA, Inc.
//==================================================
// SMC VCS coverage exclusions -- FSM extraction facts.
// Format Version: 2
// ExclMode: default
//
// Generated from urg's FSM template and the merged report; regenerate
// rather than edit. F2 takes the edges into the
// always_comb default's state that no case arm of the source produces, F3 the
// states a tied-off response never lets the master enter, F4 a state whose
// decode arm a parameter leaves unelaborated, F5 the edges that exist only as
// a state register's reset assignment, F6 the edge an enable-edge load cannot
// supply, F7 and F8 the I2C override edges the design forbids from a state, and
// B2 the rest of those override edges, which this bench cannot aim. The
// ANNOTATION before each block states the facts.
//==================================================

CHECKSUM: "2347466248 2272768170"
ANNOTATION: "SMC-FSM-F2-DEFAULT: next_state = AVS_IDLE is the always_comb default of the protocol FSM, which the extractor lists as a transition from every state; every state has a case arm and every arm assigns next_state, so the default never fires. The three states whose own arm assigns AVS_IDLE reach it in the ordinary sequence and stay graded."
ANNOTATION: "SMC-FSM-F5-RESET-EDGE: the state register's reset assignment is expanded into a transition from every state, and no case arm of the source state assigns the reset state, so the edge exists only if the block's reset is asserted while the FSM occupies that one state. The DV package grades reset behaviour through its reset leaves."
MODULE: avsbus_controller
Fsm cur_state "2272768170"
Transition AVS_END_1ST_SUBFRAME->AVS_IDLE "32->8"
Transition AVS_END_1ST_SUBFRAME->AVS_RESET "32->1"
Transition AVS_END_LAST_SUBFRAME->AVS_RESET "512->1"
Transition AVS_END_MID_SUBFRAME->AVS_IDLE "128->8"
Transition AVS_END_MID_SUBFRAME->AVS_RESET "128->1"
Transition AVS_LAUNCH_FRAME_POST_RESYNC->AVS_IDLE "4->8"
Transition AVS_LAUNCH_FRAME_POST_RESYNC->AVS_RESET "4->1"
Transition AVS_PROCESS_PREVIOUS_SDATA->AVS_IDLE "65536->8"
Transition AVS_PROCESS_PREVIOUS_SDATA->AVS_RESET "65536->1"
Transition AVS_RESET->AVS_IDLE "1->8"
Transition AVS_RETRY_END_RECV_SUBFRAME->AVS_IDLE "32768->8"
Transition AVS_RETRY_END_RECV_SUBFRAME->AVS_RESET "32768->1"
Transition AVS_RETRY_END_XMIT_AND_RECV_SUBFRAME->AVS_IDLE "2048->8"
Transition AVS_RETRY_END_XMIT_AND_RECV_SUBFRAME->AVS_RESET "2048->1"
Transition AVS_RETRY_END_XMIT_SUBFRAME->AVS_IDLE "8192->8"
Transition AVS_RETRY_END_XMIT_SUBFRAME->AVS_RESET "8192->1"
Transition AVS_RETRY_SHIFT_RECV_SUBFRAME->AVS_IDLE "16384->8"
Transition AVS_RETRY_SHIFT_RECV_SUBFRAME->AVS_RESET "16384->1"
Transition AVS_RETRY_SHIFT_XMIT_AND_RECV_SUBFRAME->AVS_IDLE "1024->8"
Transition AVS_RETRY_SHIFT_XMIT_AND_RECV_SUBFRAME->AVS_RESET "1024->1"
Transition AVS_RETRY_SHIFT_XMIT_SUBFRAME->AVS_IDLE "4096->8"
Transition AVS_RETRY_SHIFT_XMIT_SUBFRAME->AVS_RESET "4096->1"
Transition AVS_SHIFT_1ST_SUBFRAME->AVS_IDLE "16->8"
Transition AVS_SHIFT_1ST_SUBFRAME->AVS_RESET "16->1"
Transition AVS_SHIFT_LAST_SUBFRAME->AVS_IDLE "256->8"
Transition AVS_SHIFT_LAST_SUBFRAME->AVS_RESET "256->1"
Transition AVS_SHIFT_MID_SUBFRAME->AVS_IDLE "64->8"
Transition AVS_SHIFT_MID_SUBFRAME->AVS_RESET "64->1"

CHECKSUM: "2879032915 249869120"
ANNOTATION: "SMC-FSM-F4-PARAM-OFF: the MMR register map exists only when the eFuse instance has lifecycle state, and smc_efuse_wrapper instantiates the controller with HAS_LC_STATE = 0, so the decode arm selecting EFUSE_MMR_REG_MAP is not elaborated and no access reaches the state or its edges."
MODULE: efuse_interface_controller
Fsm efuse_reg_select "249869120"
State EFUSE_MMR_REG_MAP "2"
Transition EFUSE_CSR_REG_MAP->EFUSE_MMR_REG_MAP "1->2"
Transition EFUSE_MMR_REG_MAP->ERR_DECODE "2->3"
Transition ERR_DECODE->EFUSE_MMR_REG_MAP "3->2"
Transition SHADOW_REG_MAP->EFUSE_MMR_REG_MAP "0->2"

CHECKSUM: "1114926396 2231107179"
ANNOTATION: "SMC-FSM-F5-RESET-EDGE: the state register's reset assignment is expanded into a transition from every state, and no case arm of the source state assigns the reset state, so the edge exists only if the block's reset is asserted while the FSM occupies that one state. The DV package grades reset behaviour through its reset leaves."
MODULE: efuse_interface_shim
Fsm efuse_write_state_q "2089111316"
Transition ST_WRITE_ACCESS->ST_WRITE_IDLE "3->0"
Transition ST_WRITE_INIT->ST_WRITE_IDLE "1->0"
Transition ST_WRITE_READ_BACK_ACCESS->ST_WRITE_IDLE "6->0"
Transition ST_WRITE_READ_BACK_SETUP->ST_WRITE_IDLE "5->0"
Transition ST_WRITE_READ_BACK_WAIT->ST_WRITE_IDLE "7->0"
Transition ST_WRITE_SETUP->ST_WRITE_IDLE "2->0"
Transition ST_WRITE_WAIT->ST_WRITE_IDLE "4->0"

CHECKSUM: "1655169995 1106336131"
ANNOTATION: "SMC-FSM-F5-RESET-EDGE: the state register's reset assignment is expanded into a transition from every state, and no case arm of the source state assigns the reset state, so the edge exists only if the block's reset is asserted while the FSM occupies that one state. The DV package grades reset behaviour through its reset leaves."
MODULE: efuse_shadow_regs
Fsm efuse_sense_state_q "1106336131"
Transition ST_READ->ST_IDLE "1->0"

CHECKSUM: "1495589902 2401410025"
ANNOTATION: "SMC-FSM-F6-ENABLE-EDGE: the monitor enters ST_BUS_BUSY_HIGH from the ST_BUS_BUSY_LOW arm on an idle bus, and from the rising edge of the monitor enable in multi-controller mode, where the disabled branch has already parked the register at ST_BUS_FREE; ST_BUS_BUSY_STOP has no arm to ST_BUS_BUSY_HIGH and cannot be the register's value at that edge, so an edge from there is an extraction artefact. The edge from ST_BUS_BUSY_LOW is the ordinary sequence and stays graded."
MODULE: i2c_bus_monitor
Fsm state_q "2401410025"
Transition ST_BUS_BUSY_STOP->ST_BUS_BUSY_HIGH "3->2"

CHECKSUM: "4121512156 3696659517"
ANNOTATION: "SMC-FSM-F8-NO-INTERFERENCE: sda_released_but_low is gated on scl_sync, and the interference and arbitration-lost terms built on it are gated on the transmitting flag, so from a state whose output block leaves transmitting_o at zero, or that drives scl_d low, the term is identically false and the fan-in override it feeds cannot fire from that state. A state whose own case arm assigns the same destination for another reason is not named here."
ANNOTATION: "SMC-FSM-B2-UNAIMED-OVERRIDE: a property of this bench, not of the design. The I2C FSMs end their next-state logic with fan-in overrides taken on a bus event or a register write: start detect to ACQUIRE_START; stop detect, bus timeout or target disable to IDLE; arbitration loss to WAIT_FOR_STOP; controller interference or a failed symbol to IDLE. The states those overrides leave are timed below one bit by the block's own counters, and the SMC bench drives the bus through the pads and the registers, so it cannot place a bus event or a write in a chosen one of them; the edge an override would take out of a given state is uncovered for want of that aim. A bench that can place a bus event or a register write in a chosen sub-bit state retires the class. An edge the source state's own case arm assigns is reachable another way and stays graded, and F7 and F8 name the edges the design itself forbids."
MODULE: i2c_controller_fsm
Fsm state_q "3696659517"
Transition ACTIVE->IDLE "1->0"
Transition CLOCK_LOW->IDLE "9->0"
Transition CLOCK_LOW_ACK->IDLE "12->0"
Transition CLOCK_START->IDLE "5->0"
Transition CLOCK_STOP->IDLE "8->0"
Transition HOLD_BIT->IDLE "11->0"
Transition HOLD_DEV_ACK->IDLE "14->0"
Transition HOLD_START->IDLE "4->0"
Transition HOST_CLOCK_LOW_ACK->IDLE "18->0"
Transition HOST_HOLD_BIT_ACK->IDLE "20->0"
Transition READ_CLOCK_LOW->IDLE "15->0"
Transition READ_HOLD_BIT->IDLE "17->0"

CHECKSUM: "2664491312 4008718806"
ANNOTATION: "SMC-FSM-F7-SCL-HELD-LOW: the bus monitor raises start_detect only on a falling SDA while SCL is high on two samples, and clears the pending flag whenever SCL is low, so a target state that drives scl_d = 1'b0 holds the wired-AND SCL low for its whole duration and start_detect_i cannot rise in it. The fan-in override that takes the FSM to ACQUIRE_START cannot fire from such a state."
ANNOTATION: "SMC-FSM-F8-NO-INTERFERENCE: sda_released_but_low is gated on scl_sync, and the interference and arbitration-lost terms built on it are gated on the transmitting flag, so from a state whose output block leaves transmitting_o at zero, or that drives scl_d low, the term is identically false and the fan-in override it feeds cannot fire from that state. A state whose own case arm assigns the same destination for another reason is not named here."
ANNOTATION: "SMC-FSM-B2-UNAIMED-OVERRIDE: a property of this bench, not of the design. The I2C FSMs end their next-state logic with fan-in overrides taken on a bus event or a register write: start detect to ACQUIRE_START; stop detect, bus timeout or target disable to IDLE; arbitration loss to WAIT_FOR_STOP; controller interference or a failed symbol to IDLE. The states those overrides leave are timed below one bit by the block's own counters, and the SMC bench drives the bus through the pads and the registers, so it cannot place a bus event or a write in a chosen one of them; the edge an override would take out of a given state is uncovered for want of that aim. A bench that can place a bus event or a register write in a chosen sub-bit state retires the class. An edge the source state's own case arm assigns is reachable another way and stays graded, and F7 and F8 name the edges the design itself forbids."
MODULE: i2c_target_fsm
Fsm state_q "4008718806"
Transition ACQUIRE_ACK_HOLD->ACQUIRE_START "18->1"
Transition ACQUIRE_ACK_HOLD->IDLE "18->0"
Transition ACQUIRE_ACK_HOLD->WAIT_FOR_STOP "18->13"
Transition ACQUIRE_ACK_PULSE->ACQUIRE_START "17->1"
Transition ACQUIRE_ACK_PULSE->IDLE "17->0"
Transition ACQUIRE_ACK_PULSE->WAIT_FOR_STOP "17->13"
Transition ACQUIRE_ACK_SETUP->ACQUIRE_START "16->1"
Transition ACQUIRE_ACK_SETUP->IDLE "16->0"
Transition ACQUIRE_ACK_SETUP->WAIT_FOR_STOP "16->13"
Transition ACQUIRE_ACK_WAIT->ACQUIRE_START "15->1"
Transition ACQUIRE_ACK_WAIT->IDLE "15->0"
Transition ACQUIRE_BYTE->WAIT_FOR_STOP "14->13"
Transition ACQUIRE_START->WAIT_FOR_STOP "1->13"
Transition ADDR_ACK_HOLD->ACQUIRE_START "6->1"
Transition ADDR_ACK_HOLD->IDLE "6->0"
Transition ADDR_ACK_PULSE->ACQUIRE_START "5->1"
Transition ADDR_ACK_PULSE->IDLE "5->0"
Transition ADDR_ACK_PULSE->WAIT_FOR_STOP "5->13"
Transition ADDR_ACK_SETUP->ACQUIRE_START "4->1"
Transition ADDR_ACK_SETUP->IDLE "4->0"
Transition ADDR_ACK_SETUP->WAIT_FOR_STOP "4->13"
Transition ADDR_ACK_WAIT->ACQUIRE_START "3->1"
Transition ADDR_ACK_WAIT->IDLE "3->0"
Transition IDLE->WAIT_FOR_STOP "0->13"
Transition STRETCH_ACQ_FULL->ACQUIRE_START "24->1"
Transition STRETCH_ACQ_SETUP->ACQUIRE_START "25->1"
Transition STRETCH_ACQ_SETUP->IDLE "25->0"
Transition STRETCH_ACQ_SETUP->WAIT_FOR_STOP "25->13"
Transition STRETCH_ADDR->ACQUIRE_START "21->1"
Transition STRETCH_ADDR->IDLE "21->0"
Transition STRETCH_ADDR_ACK->ACQUIRE_START "19->1"
Transition STRETCH_ADDR_ACK->IDLE "19->0"
Transition STRETCH_ADDR_ACK_SETUP->ACQUIRE_START "20->1"
Transition STRETCH_ADDR_ACK_SETUP->IDLE "20->0"
Transition STRETCH_ADDR_ACK_SETUP->WAIT_FOR_STOP "20->13"
Transition STRETCH_TX->ACQUIRE_START "22->1"
Transition STRETCH_TX_SETUP->ACQUIRE_START "23->1"
Transition STRETCH_TX_SETUP->IDLE "23->0"
Transition STRETCH_TX_SETUP->WAIT_FOR_STOP "23->13"
Transition TRANSMIT_ACK->ACQUIRE_START "11->1"
Transition TRANSMIT_ACK->WAIT_FOR_STOP "11->13"
Transition TRANSMIT_ACK_PULSE->ACQUIRE_START "12->1"
Transition TRANSMIT_HOLD->ACQUIRE_START "10->1"
Transition TRANSMIT_HOLD->IDLE "10->0"
Transition TRANSMIT_HOLD->WAIT_FOR_STOP "10->13"
Transition TRANSMIT_PULSE->ACQUIRE_START "9->1"
Transition TRANSMIT_PULSE->IDLE "9->0"
Transition TRANSMIT_SETUP->ACQUIRE_START "8->1"
Transition TRANSMIT_SETUP->IDLE "8->0"
Transition TRANSMIT_SETUP->WAIT_FOR_STOP "8->13"
Transition TRANSMIT_WAIT->ACQUIRE_START "7->1"
Transition TRANSMIT_WAIT->IDLE "7->0"
Transition TRANSMIT_WAIT->WAIT_FOR_STOP "7->13"

CHECKSUM: "1036002057 2698801009"
ANNOTATION: "SMC-FSM-B4-SRAM-AUTOINIT-BYPASSED: a property of this bench, not of the design. The CPU scratch SRAM is zeroed by a hardware sequence that runs after its reset unless smc_disable_sram_auto_init_i is high, and the SMC testbench top ties that input high, so the sequence goes from MEM_ZERO_IDLE straight to MEM_ZERO_DONE and MEM_ZERO_BUSY is never entered. A bench that deasserts the input runs the sequence and retires the class."
MODULE: smc_4core_cpu
Fsm state "2698801009"
State MEM_ZERO_BUSY "2"
Transition MEM_ZERO_BUSY->MEM_ZERO_DONE "2->4"
Transition MEM_ZERO_BUSY->MEM_ZERO_IDLE "2->1"
Transition MEM_ZERO_IDLE->MEM_ZERO_BUSY "1->2"

CHECKSUM: "2121805547 1063748259"
ANNOTATION: "SMC-FSM-F5-RESET-EDGE: the state register's reset assignment is expanded into a transition from every state, and no case arm of the source state assigns the reset state, so the edge exists only if the block's reset is asserted while the FSM occupies that one state. The DV package grades reset behaviour through its reset leaves."
MODULE: smc_cool_reset_wrap
Fsm flr_counter_state "909361475"
Transition COUNT_DOWN->IDLE "1->0"

CHECKSUM: "1319975045 330493458"
ANNOTATION: "SMC-FSM-F9-LOOP-INDEX-EXTRACTION: a property of the extraction, not of the design. block_index is a loop index local to an always_comb, set at the top of the block and walked by the for loop over the message's counters, with no flop behind it. The extractor reports it as an FSM because it is state-shaped, and the values and transitions it records are whichever it samples from that combinational loop; none of them is a state or a transition of the design. Only the points the report marks uncovered are written, so the sampled values it did record stay in the score."
MODULE: telemetry_receiver
Fsm block_index "330493458"
State 'h0 "0"
State 'h1 "1"
Transition 'h0->'h1 "0->1"

CHECKSUM: "404099673 995141053"
ANNOTATION: "SMC-FSM-F3-TIEOFF: smc_dfd_wrap ties every m_trc_axi_* response input to zero, so the trace write master never completes a response handshake and cannot pass REQ_HANDSHAKE; the states an aw_ready, w_ready or b_valid is needed to enter, and the edges touching them, have no stimulus. The request the master issues on valid_i is reachable, so RESET_VALUE, REQ_HANDSHAKE and the edge between them stay graded."
MODULE: trace_axi_master
Fsm state "995141053"
State AW_HANDSHAKE "2"
State RESP_HANDSHAKE "4"
State W_HANDSHAKE "3"
Transition AW_HANDSHAKE->RESET_VALUE "2->0"
Transition AW_HANDSHAKE->RESP_HANDSHAKE "2->4"
Transition REQ_HANDSHAKE->AW_HANDSHAKE "1->2"
Transition REQ_HANDSHAKE->RESP_HANDSHAKE "1->4"
Transition REQ_HANDSHAKE->W_HANDSHAKE "1->3"
Transition RESP_HANDSHAKE->RESET_VALUE "4->0"
Transition W_HANDSHAKE->RESET_VALUE "3->0"
Transition W_HANDSHAKE->RESP_HANDSHAKE "3->4"

CHECKSUM: "134859043 4062283189"
ANNOTATION: "SMC-FSM-F5-RESET-EDGE: the state register's reset assignment is expanded into a transition from every state, and no case arm of the source state assigns the reset state, so the edge exists only if the block's reset is asserted while the FSM occupies that one state. The DV package grades reset behaviour through its reset leaves."
MODULE: zeroer
Fsm cur_state "4062283189"
Transition ST_ISSUE_ADDR->ST_IDLE "2->1"

CHECKSUM: "3775597833 2717742095"
INSTANCE: smc_uvm_top.u_dut.u_smc.u_smc_base.u_internal_regs.u_smc_dfd_wrap.u_dfd_top.dst_wrapper.dst_inst[0].debug_sig_trace_packetizer.accumulator_instance.gen_accumulator_bank_instance[0].accumulator_bank_instance
ANNOTATION: "SMC-F11-FSM-IN-PORTS-ONLY-UNIT: this FSM sits inside a unit graded on its ports (a T-series class), which design engineering reviewed excluding whole; its states and transitions are excluded while uncovered. Retired by an enrolled leaf that covers the point, or design engineering withdrawing the review of the enclosing unit."
Fsm bank_status "2717742095"
Transition BANK_EMPTY->BANK_FULL "0->2"
Transition BANK_FULL->BANK_PARTIAL "2->1"

CHECKSUM: "3775597833 2717742095"
INSTANCE: smc_uvm_top.u_dut.u_smc.u_smc_base.u_internal_regs.u_smc_dfd_wrap.u_dfd_top.dst_wrapper.dst_inst[0].debug_sig_trace_packetizer.accumulator_instance.gen_accumulator_bank_instance[1].accumulator_bank_instance
ANNOTATION: "SMC-F11-FSM-IN-PORTS-ONLY-UNIT: this FSM sits inside a unit graded on its ports (a T-series class), which design engineering reviewed excluding whole; its states and transitions are excluded while uncovered. Retired by an enrolled leaf that covers the point, or design engineering withdrawing the review of the enclosing unit."
Fsm bank_status "2717742095"
Transition BANK_EMPTY->BANK_FULL "0->2"
Transition BANK_FULL->BANK_PARTIAL "2->1"

CHECKSUM: "404099673 995141053"
INSTANCE: smc_uvm_top.u_dut.u_smc.u_smc_base.u_internal_regs.u_smc_dfd_wrap.u_dfd_top.trace_wrapper.trace_inst.trace_funnel_inst.trace_smem_axi_master
ANNOTATION: "SMC-F11-FSM-IN-PORTS-ONLY-UNIT: this FSM sits inside a unit graded on its ports (a T-series class), which design engineering reviewed excluding whole; its states and transitions are excluded while uncovered. Retired by an enrolled leaf that covers the point, or design engineering withdrawing the review of the enclosing unit."
Fsm state "995141053"
State AW_HANDSHAKE "2"
State RESP_HANDSHAKE "4"
State W_HANDSHAKE "3"
Transition AW_HANDSHAKE->RESET_VALUE "2->0"
Transition AW_HANDSHAKE->RESP_HANDSHAKE "2->4"
Transition REQ_HANDSHAKE->AW_HANDSHAKE "1->2"
Transition REQ_HANDSHAKE->RESP_HANDSHAKE "1->4"
Transition REQ_HANDSHAKE->W_HANDSHAKE "1->3"
Transition RESP_HANDSHAKE->RESET_VALUE "4->0"
Transition W_HANDSHAKE->RESET_VALUE "3->0"
Transition W_HANDSHAKE->RESP_HANDSHAKE "3->4"

CHECKSUM: "134859043 4062283189"
INSTANCE: smc_uvm_top.u_dut.u_smc.u_smc_base.u_smc_data_accelerator_wrap.u_zeroer
ANNOTATION: "SMC-F10-FSM-REVIEWED: design engineering reviewed these FSM states and transitions as not exercised by the SMC bench. Retired by an enrolled leaf that covers the point, or design engineering withdrawing the review."
Fsm cur_state "4062283189"
Transition ST_ISSUE_ADDR->ST_IDLE "2->1"

CHECKSUM: "1036002057 2698801009"
INSTANCE: smc_uvm_top.u_dut.u_smc.u_smc_cpu_wrapper.u_smc_cpu
ANNOTATION: "SMC-F10-FSM-REVIEWED: design engineering reviewed these FSM states and transitions as not exercised by the SMC bench. Retired by an enrolled leaf that covers the point, or design engineering withdrawing the review."
Fsm state "2698801009"
State MEM_ZERO_BUSY "2"
Transition MEM_ZERO_BUSY->MEM_ZERO_DONE "2->4"
Transition MEM_ZERO_BUSY->MEM_ZERO_IDLE "2->1"
Transition MEM_ZERO_IDLE->MEM_ZERO_BUSY "1->2"

CHECKSUM: "2347466248 2272768170"
INSTANCE: smc_uvm_top.u_dut.u_smc.u_smc_peripherals.u_avsbus_controller
ANNOTATION: "SMC-F10-FSM-REVIEWED: design engineering reviewed these FSM states and transitions as not exercised by the SMC bench. Retired by an enrolled leaf that covers the point, or design engineering withdrawing the review."
Fsm cur_state "2272768170"
Transition AVS_END_1ST_SUBFRAME->AVS_IDLE "32->8"
Transition AVS_END_1ST_SUBFRAME->AVS_RESET "32->1"
Transition AVS_END_LAST_SUBFRAME->AVS_RESET "512->1"
Transition AVS_END_MID_SUBFRAME->AVS_IDLE "128->8"
Transition AVS_END_MID_SUBFRAME->AVS_RESET "128->1"
Transition AVS_LAUNCH_FRAME_POST_RESYNC->AVS_IDLE "4->8"
Transition AVS_LAUNCH_FRAME_POST_RESYNC->AVS_RESET "4->1"
Transition AVS_PROCESS_PREVIOUS_SDATA->AVS_IDLE "65536->8"
Transition AVS_PROCESS_PREVIOUS_SDATA->AVS_RESET "65536->1"
Transition AVS_RESET->AVS_IDLE "1->8"
Transition AVS_RETRY_END_RECV_SUBFRAME->AVS_IDLE "32768->8"
Transition AVS_RETRY_END_RECV_SUBFRAME->AVS_RESET "32768->1"
Transition AVS_RETRY_END_XMIT_AND_RECV_SUBFRAME->AVS_IDLE "2048->8"
Transition AVS_RETRY_END_XMIT_AND_RECV_SUBFRAME->AVS_RESET "2048->1"
Transition AVS_RETRY_END_XMIT_SUBFRAME->AVS_IDLE "8192->8"
Transition AVS_RETRY_END_XMIT_SUBFRAME->AVS_RESET "8192->1"
Transition AVS_RETRY_SHIFT_RECV_SUBFRAME->AVS_IDLE "16384->8"
Transition AVS_RETRY_SHIFT_RECV_SUBFRAME->AVS_RESET "16384->1"
Transition AVS_RETRY_SHIFT_XMIT_AND_RECV_SUBFRAME->AVS_IDLE "1024->8"
Transition AVS_RETRY_SHIFT_XMIT_AND_RECV_SUBFRAME->AVS_RESET "1024->1"
Transition AVS_RETRY_SHIFT_XMIT_SUBFRAME->AVS_IDLE "4096->8"
Transition AVS_RETRY_SHIFT_XMIT_SUBFRAME->AVS_RESET "4096->1"
Transition AVS_SHIFT_1ST_SUBFRAME->AVS_IDLE "16->8"
Transition AVS_SHIFT_1ST_SUBFRAME->AVS_RESET "16->1"
Transition AVS_SHIFT_LAST_SUBFRAME->AVS_IDLE "256->8"
Transition AVS_SHIFT_LAST_SUBFRAME->AVS_RESET "256->1"
Transition AVS_SHIFT_MID_SUBFRAME->AVS_IDLE "64->8"
Transition AVS_SHIFT_MID_SUBFRAME->AVS_RESET "64->1"

CHECKSUM: "1495589902 2401410025"
INSTANCE: smc_uvm_top.u_dut.u_smc.u_smc_peripherals.u_i2c_wrap.gen_i2cs[0].u_i2c.u_i2c_core.u_i2c_bus_monitor
ANNOTATION: "SMC-F10-FSM-REVIEWED: design engineering reviewed these FSM states and transitions as not exercised by the SMC bench. Retired by an enrolled leaf that covers the point, or design engineering withdrawing the review."
Fsm state_q "2401410025"
Transition ST_BUS_BUSY_STOP->ST_BUS_BUSY_HIGH "3->2"

CHECKSUM: "4121512156 3696659517"
INSTANCE: smc_uvm_top.u_dut.u_smc.u_smc_peripherals.u_i2c_wrap.gen_i2cs[0].u_i2c.u_i2c_core.u_i2c_controller_fsm
ANNOTATION: "SMC-F10-FSM-REVIEWED: design engineering reviewed these FSM states and transitions as not exercised by the SMC bench. Retired by an enrolled leaf that covers the point, or design engineering withdrawing the review."
Fsm state_q "3696659517"
Transition ACTIVE->IDLE "1->0"
Transition CLOCK_LOW->IDLE "9->0"
Transition CLOCK_LOW_ACK->IDLE "12->0"
Transition CLOCK_START->IDLE "5->0"
Transition CLOCK_STOP->IDLE "8->0"
Transition HOLD_BIT->IDLE "11->0"
Transition HOLD_DEV_ACK->IDLE "14->0"
Transition HOLD_START->IDLE "4->0"
Transition HOST_CLOCK_LOW_ACK->IDLE "18->0"
Transition HOST_HOLD_BIT_ACK->IDLE "20->0"
Transition READ_CLOCK_LOW->IDLE "15->0"
Transition READ_HOLD_BIT->IDLE "17->0"

CHECKSUM: "2664491312 4008718806"
INSTANCE: smc_uvm_top.u_dut.u_smc.u_smc_peripherals.u_i2c_wrap.gen_i2cs[0].u_i2c.u_i2c_core.u_i2c_target_fsm
ANNOTATION: "SMC-F10-FSM-REVIEWED: design engineering reviewed these FSM states and transitions as not exercised by the SMC bench. Retired by an enrolled leaf that covers the point, or design engineering withdrawing the review."
Fsm state_q "4008718806"
Transition ACQUIRE_ACK_HOLD->ACQUIRE_START "18->1"
Transition ACQUIRE_ACK_HOLD->IDLE "18->0"
Transition ACQUIRE_ACK_HOLD->WAIT_FOR_STOP "18->13"
Transition ACQUIRE_ACK_PULSE->ACQUIRE_START "17->1"
Transition ACQUIRE_ACK_PULSE->IDLE "17->0"
Transition ACQUIRE_ACK_PULSE->WAIT_FOR_STOP "17->13"
Transition ACQUIRE_ACK_SETUP->ACQUIRE_START "16->1"
Transition ACQUIRE_ACK_SETUP->IDLE "16->0"
Transition ACQUIRE_ACK_SETUP->WAIT_FOR_STOP "16->13"
Transition ACQUIRE_ACK_WAIT->ACQUIRE_START "15->1"
Transition ACQUIRE_ACK_WAIT->IDLE "15->0"
Transition ACQUIRE_BYTE->WAIT_FOR_STOP "14->13"
Transition ACQUIRE_START->WAIT_FOR_STOP "1->13"
Transition ADDR_ACK_HOLD->ACQUIRE_START "6->1"
Transition ADDR_ACK_HOLD->IDLE "6->0"
Transition ADDR_ACK_PULSE->ACQUIRE_START "5->1"
Transition ADDR_ACK_PULSE->IDLE "5->0"
Transition ADDR_ACK_PULSE->WAIT_FOR_STOP "5->13"
Transition ADDR_ACK_SETUP->ACQUIRE_START "4->1"
Transition ADDR_ACK_SETUP->IDLE "4->0"
Transition ADDR_ACK_SETUP->WAIT_FOR_STOP "4->13"
Transition ADDR_ACK_WAIT->ACQUIRE_START "3->1"
Transition ADDR_ACK_WAIT->IDLE "3->0"
Transition ADDR_READ->WAIT_FOR_STOP "2->13"
Transition IDLE->WAIT_FOR_STOP "0->13"
Transition STRETCH_ACQ_FULL->ACQUIRE_START "24->1"
Transition STRETCH_ACQ_SETUP->ACQUIRE_START "25->1"
Transition STRETCH_ACQ_SETUP->IDLE "25->0"
Transition STRETCH_ACQ_SETUP->WAIT_FOR_STOP "25->13"
Transition STRETCH_ADDR->ACQUIRE_START "21->1"
Transition STRETCH_ADDR->IDLE "21->0"
Transition STRETCH_ADDR->WAIT_FOR_STOP "21->13"
Transition STRETCH_ADDR_ACK->ACQUIRE_START "19->1"
Transition STRETCH_ADDR_ACK->IDLE "19->0"
Transition STRETCH_ADDR_ACK->WAIT_FOR_STOP "19->13"
Transition STRETCH_ADDR_ACK_SETUP->ACQUIRE_START "20->1"
Transition STRETCH_ADDR_ACK_SETUP->IDLE "20->0"
Transition STRETCH_ADDR_ACK_SETUP->WAIT_FOR_STOP "20->13"
Transition STRETCH_TX->ACQUIRE_START "22->1"
Transition STRETCH_TX_SETUP->ACQUIRE_START "23->1"
Transition STRETCH_TX_SETUP->IDLE "23->0"
Transition STRETCH_TX_SETUP->WAIT_FOR_STOP "23->13"
Transition TRANSMIT_ACK->ACQUIRE_START "11->1"
Transition TRANSMIT_ACK->WAIT_FOR_STOP "11->13"
Transition TRANSMIT_ACK_PULSE->ACQUIRE_START "12->1"
Transition TRANSMIT_HOLD->ACQUIRE_START "10->1"
Transition TRANSMIT_HOLD->IDLE "10->0"
Transition TRANSMIT_HOLD->WAIT_FOR_STOP "10->13"
Transition TRANSMIT_PULSE->ACQUIRE_START "9->1"
Transition TRANSMIT_PULSE->IDLE "9->0"
Transition TRANSMIT_SETUP->ACQUIRE_START "8->1"
Transition TRANSMIT_SETUP->IDLE "8->0"
Transition TRANSMIT_SETUP->WAIT_FOR_STOP "8->13"
Transition TRANSMIT_WAIT->ACQUIRE_START "7->1"
Transition TRANSMIT_WAIT->IDLE "7->0"
Transition TRANSMIT_WAIT->WAIT_FOR_STOP "7->13"

CHECKSUM: "1495589902 2401410025"
INSTANCE: smc_uvm_top.u_dut.u_smc.u_smc_peripherals.u_i2c_wrap.gen_i2cs[1].u_i2c.u_i2c_core.u_i2c_bus_monitor
ANNOTATION: "SMC-F10-FSM-REVIEWED: design engineering reviewed these FSM states and transitions as not exercised by the SMC bench. Retired by an enrolled leaf that covers the point, or design engineering withdrawing the review."
Fsm state_q "2401410025"
Transition ST_BUS_BUSY_STOP->ST_BUS_BUSY_HIGH "3->2"

CHECKSUM: "4121512156 3696659517"
INSTANCE: smc_uvm_top.u_dut.u_smc.u_smc_peripherals.u_i2c_wrap.gen_i2cs[1].u_i2c.u_i2c_core.u_i2c_controller_fsm
ANNOTATION: "SMC-F10-FSM-REVIEWED: design engineering reviewed these FSM states and transitions as not exercised by the SMC bench. Retired by an enrolled leaf that covers the point, or design engineering withdrawing the review."
Fsm state_q "3696659517"
Transition ACTIVE->IDLE "1->0"
Transition CLOCK_LOW->IDLE "9->0"
Transition CLOCK_LOW->SETUP_START "9->3"
Transition CLOCK_LOW_ACK->IDLE "12->0"
Transition CLOCK_PULSE_ACK->IDLE "13->0"
Transition CLOCK_START->IDLE "5->0"
Transition CLOCK_STOP->IDLE "8->0"
Transition HOLD_BIT->IDLE "11->0"
Transition HOLD_DEV_ACK->IDLE "14->0"
Transition HOLD_START->IDLE "4->0"
Transition HOLD_STOP->IDLE "7->0"
Transition HOST_CLOCK_LOW_ACK->IDLE "18->0"
Transition HOST_CLOCK_PULSE_ACK->IDLE "19->0"
Transition HOST_HOLD_BIT_ACK->IDLE "20->0"
Transition HOST_HOLD_BIT_ACK->POP_FMT_FIFO "20->2"
Transition HOST_HOLD_BIT_ACK->READ_CLOCK_LOW "20->15"
Transition IDLE->CLOCK_STOP "0->8"
Transition POP_FMT_FIFO->CLOCK_STOP "2->8"
Transition READ_CLOCK_LOW->IDLE "15->0"
Transition READ_CLOCK_PULSE->IDLE "16->0"
Transition READ_HOLD_BIT->IDLE "17->0"
Transition SETUP_START->IDLE "3->0"
Transition SETUP_STOP->IDLE "6->0"

CHECKSUM: "2664491312 4008718806"
INSTANCE: smc_uvm_top.u_dut.u_smc.u_smc_peripherals.u_i2c_wrap.gen_i2cs[1].u_i2c.u_i2c_core.u_i2c_target_fsm
ANNOTATION: "SMC-F10-FSM-REVIEWED: design engineering reviewed these FSM states and transitions as not exercised by the SMC bench. Retired by an enrolled leaf that covers the point, or design engineering withdrawing the review."
Fsm state_q "4008718806"
Transition ACQUIRE_ACK_HOLD->ACQUIRE_START "18->1"
Transition ACQUIRE_ACK_HOLD->IDLE "18->0"
Transition ACQUIRE_ACK_HOLD->WAIT_FOR_STOP "18->13"
Transition ACQUIRE_ACK_PULSE->ACQUIRE_START "17->1"
Transition ACQUIRE_ACK_PULSE->IDLE "17->0"
Transition ACQUIRE_ACK_PULSE->WAIT_FOR_STOP "17->13"
Transition ACQUIRE_ACK_SETUP->ACQUIRE_START "16->1"
Transition ACQUIRE_ACK_SETUP->IDLE "16->0"
Transition ACQUIRE_ACK_SETUP->WAIT_FOR_STOP "16->13"
Transition ACQUIRE_ACK_WAIT->ACQUIRE_START "15->1"
Transition ACQUIRE_ACK_WAIT->IDLE "15->0"
Transition ACQUIRE_BYTE->WAIT_FOR_STOP "14->13"
Transition ACQUIRE_START->WAIT_FOR_STOP "1->13"
Transition ADDR_ACK_HOLD->ACQUIRE_START "6->1"
Transition ADDR_ACK_HOLD->IDLE "6->0"
Transition ADDR_ACK_HOLD->WAIT_FOR_STOP "6->13"
Transition ADDR_ACK_PULSE->ACQUIRE_START "5->1"
Transition ADDR_ACK_PULSE->IDLE "5->0"
Transition ADDR_ACK_PULSE->WAIT_FOR_STOP "5->13"
Transition ADDR_ACK_SETUP->ACQUIRE_START "4->1"
Transition ADDR_ACK_SETUP->IDLE "4->0"
Transition ADDR_ACK_SETUP->WAIT_FOR_STOP "4->13"
Transition ADDR_ACK_WAIT->ACQUIRE_START "3->1"
Transition ADDR_ACK_WAIT->IDLE "3->0"
Transition IDLE->WAIT_FOR_STOP "0->13"
Transition STRETCH_ACQ_FULL->ACQUIRE_START "24->1"
Transition STRETCH_ACQ_SETUP->ACQUIRE_START "25->1"
Transition STRETCH_ACQ_SETUP->IDLE "25->0"
Transition STRETCH_ACQ_SETUP->WAIT_FOR_STOP "25->13"
Transition STRETCH_ADDR->ACQUIRE_START "21->1"
Transition STRETCH_ADDR->IDLE "21->0"
Transition STRETCH_ADDR->WAIT_FOR_STOP "21->13"
Transition STRETCH_ADDR_ACK->ACQUIRE_START "19->1"
Transition STRETCH_ADDR_ACK->IDLE "19->0"
Transition STRETCH_ADDR_ACK->WAIT_FOR_STOP "19->13"
Transition STRETCH_ADDR_ACK_SETUP->ACQUIRE_START "20->1"
Transition STRETCH_ADDR_ACK_SETUP->IDLE "20->0"
Transition STRETCH_ADDR_ACK_SETUP->WAIT_FOR_STOP "20->13"
Transition STRETCH_TX->ACQUIRE_START "22->1"
Transition STRETCH_TX->IDLE "22->0"
Transition STRETCH_TX_SETUP->ACQUIRE_START "23->1"
Transition STRETCH_TX_SETUP->IDLE "23->0"
Transition STRETCH_TX_SETUP->WAIT_FOR_STOP "23->13"
Transition TRANSMIT_ACK->ACQUIRE_START "11->1"
Transition TRANSMIT_ACK->IDLE "11->0"
Transition TRANSMIT_ACK->WAIT_FOR_STOP "11->13"
Transition TRANSMIT_ACK_PULSE->ACQUIRE_START "12->1"
Transition TRANSMIT_HOLD->ACQUIRE_START "10->1"
Transition TRANSMIT_HOLD->IDLE "10->0"
Transition TRANSMIT_HOLD->WAIT_FOR_STOP "10->13"
Transition TRANSMIT_PULSE->ACQUIRE_START "9->1"
Transition TRANSMIT_PULSE->IDLE "9->0"
Transition TRANSMIT_PULSE->WAIT_FOR_STOP "9->13"
Transition TRANSMIT_SETUP->ACQUIRE_START "8->1"
Transition TRANSMIT_SETUP->IDLE "8->0"
Transition TRANSMIT_SETUP->WAIT_FOR_STOP "8->13"
Transition TRANSMIT_WAIT->ACQUIRE_START "7->1"
Transition TRANSMIT_WAIT->IDLE "7->0"
Transition TRANSMIT_WAIT->WAIT_FOR_STOP "7->13"
Transition WAIT_FOR_STOP->ACQUIRE_START "13->1"

CHECKSUM: "1495589902 2401410025"
INSTANCE: smc_uvm_top.u_dut.u_smc.u_smc_peripherals.u_i2c_wrap.gen_i2cs[2].u_i2c.u_i2c_core.u_i2c_bus_monitor
ANNOTATION: "SMC-F10-FSM-REVIEWED: design engineering reviewed these FSM states and transitions as not exercised by the SMC bench. Retired by an enrolled leaf that covers the point, or design engineering withdrawing the review."
Fsm state_q "2401410025"
Transition ST_BUS_BUSY_STOP->ST_BUS_BUSY_HIGH "3->2"

CHECKSUM: "4121512156 3696659517"
INSTANCE: smc_uvm_top.u_dut.u_smc.u_smc_peripherals.u_i2c_wrap.gen_i2cs[2].u_i2c.u_i2c_core.u_i2c_controller_fsm
ANNOTATION: "SMC-F10-FSM-REVIEWED: design engineering reviewed these FSM states and transitions as not exercised by the SMC bench. Retired by an enrolled leaf that covers the point, or design engineering withdrawing the review."
Fsm state_q "3696659517"
Transition ACTIVE->IDLE "1->0"
Transition CLOCK_LOW->IDLE "9->0"
Transition CLOCK_LOW->SETUP_START "9->3"
Transition CLOCK_LOW_ACK->IDLE "12->0"
Transition CLOCK_PULSE_ACK->IDLE "13->0"
Transition CLOCK_START->IDLE "5->0"
Transition CLOCK_STOP->IDLE "8->0"
Transition HOLD_BIT->IDLE "11->0"
Transition HOLD_DEV_ACK->IDLE "14->0"
Transition HOLD_START->IDLE "4->0"
Transition HOLD_STOP->IDLE "7->0"
Transition HOST_CLOCK_LOW_ACK->IDLE "18->0"
Transition HOST_CLOCK_PULSE_ACK->IDLE "19->0"
Transition HOST_HOLD_BIT_ACK->IDLE "20->0"
Transition HOST_HOLD_BIT_ACK->POP_FMT_FIFO "20->2"
Transition IDLE->CLOCK_STOP "0->8"
Transition POP_FMT_FIFO->CLOCK_STOP "2->8"
Transition READ_CLOCK_LOW->IDLE "15->0"
Transition READ_CLOCK_PULSE->IDLE "16->0"
Transition READ_HOLD_BIT->IDLE "17->0"
Transition SETUP_START->IDLE "3->0"
Transition SETUP_STOP->IDLE "6->0"

CHECKSUM: "2664491312 4008718806"
INSTANCE: smc_uvm_top.u_dut.u_smc.u_smc_peripherals.u_i2c_wrap.gen_i2cs[2].u_i2c.u_i2c_core.u_i2c_target_fsm
ANNOTATION: "SMC-F10-FSM-REVIEWED: design engineering reviewed these FSM states and transitions as not exercised by the SMC bench. Retired by an enrolled leaf that covers the point, or design engineering withdrawing the review."
Fsm state_q "4008718806"
Transition ACQUIRE_ACK_HOLD->ACQUIRE_START "18->1"
Transition ACQUIRE_ACK_HOLD->IDLE "18->0"
Transition ACQUIRE_ACK_HOLD->WAIT_FOR_STOP "18->13"
Transition ACQUIRE_ACK_PULSE->ACQUIRE_START "17->1"
Transition ACQUIRE_ACK_PULSE->IDLE "17->0"
Transition ACQUIRE_ACK_PULSE->WAIT_FOR_STOP "17->13"
Transition ACQUIRE_ACK_SETUP->ACQUIRE_START "16->1"
Transition ACQUIRE_ACK_SETUP->IDLE "16->0"
Transition ACQUIRE_ACK_SETUP->WAIT_FOR_STOP "16->13"
Transition ACQUIRE_ACK_WAIT->ACQUIRE_START "15->1"
Transition ACQUIRE_ACK_WAIT->IDLE "15->0"
Transition ACQUIRE_BYTE->WAIT_FOR_STOP "14->13"
Transition ACQUIRE_START->WAIT_FOR_STOP "1->13"
Transition ADDR_ACK_HOLD->ACQUIRE_START "6->1"
Transition ADDR_ACK_HOLD->IDLE "6->0"
Transition ADDR_ACK_HOLD->WAIT_FOR_STOP "6->13"
Transition ADDR_ACK_PULSE->ACQUIRE_START "5->1"
Transition ADDR_ACK_PULSE->IDLE "5->0"
Transition ADDR_ACK_PULSE->WAIT_FOR_STOP "5->13"
Transition ADDR_ACK_SETUP->ACQUIRE_START "4->1"
Transition ADDR_ACK_SETUP->IDLE "4->0"
Transition ADDR_ACK_SETUP->WAIT_FOR_STOP "4->13"
Transition ADDR_ACK_WAIT->ACQUIRE_START "3->1"
Transition ADDR_ACK_WAIT->IDLE "3->0"
Transition IDLE->WAIT_FOR_STOP "0->13"
Transition STRETCH_ACQ_FULL->ACQUIRE_START "24->1"
Transition STRETCH_ACQ_SETUP->ACQUIRE_START "25->1"
Transition STRETCH_ACQ_SETUP->IDLE "25->0"
Transition STRETCH_ACQ_SETUP->WAIT_FOR_STOP "25->13"
Transition STRETCH_ADDR->ACQUIRE_START "21->1"
Transition STRETCH_ADDR->IDLE "21->0"
Transition STRETCH_ADDR->WAIT_FOR_STOP "21->13"
Transition STRETCH_ADDR_ACK->ACQUIRE_START "19->1"
Transition STRETCH_ADDR_ACK->IDLE "19->0"
Transition STRETCH_ADDR_ACK->WAIT_FOR_STOP "19->13"
Transition STRETCH_ADDR_ACK_SETUP->ACQUIRE_START "20->1"
Transition STRETCH_ADDR_ACK_SETUP->IDLE "20->0"
Transition STRETCH_ADDR_ACK_SETUP->WAIT_FOR_STOP "20->13"
Transition STRETCH_TX->ACQUIRE_START "22->1"
Transition STRETCH_TX->IDLE "22->0"
Transition STRETCH_TX_SETUP->ACQUIRE_START "23->1"
Transition STRETCH_TX_SETUP->IDLE "23->0"
Transition STRETCH_TX_SETUP->WAIT_FOR_STOP "23->13"
Transition TRANSMIT_ACK->ACQUIRE_START "11->1"
Transition TRANSMIT_ACK->IDLE "11->0"
Transition TRANSMIT_ACK->WAIT_FOR_STOP "11->13"
Transition TRANSMIT_ACK_PULSE->ACQUIRE_START "12->1"
Transition TRANSMIT_ACK_PULSE->IDLE "12->0"
Transition TRANSMIT_ACK_PULSE->TRANSMIT_WAIT "12->7"
Transition TRANSMIT_HOLD->ACQUIRE_START "10->1"
Transition TRANSMIT_HOLD->IDLE "10->0"
Transition TRANSMIT_HOLD->WAIT_FOR_STOP "10->13"
Transition TRANSMIT_PULSE->ACQUIRE_START "9->1"
Transition TRANSMIT_PULSE->IDLE "9->0"
Transition TRANSMIT_PULSE->WAIT_FOR_STOP "9->13"
Transition TRANSMIT_SETUP->ACQUIRE_START "8->1"
Transition TRANSMIT_SETUP->IDLE "8->0"
Transition TRANSMIT_SETUP->WAIT_FOR_STOP "8->13"
Transition TRANSMIT_WAIT->ACQUIRE_START "7->1"
Transition TRANSMIT_WAIT->IDLE "7->0"
Transition TRANSMIT_WAIT->TRANSMIT_SETUP "7->8"
Transition TRANSMIT_WAIT->WAIT_FOR_STOP "7->13"
Transition WAIT_FOR_STOP->ACQUIRE_START "13->1"

CHECKSUM: "2879032915 249869120"
INSTANCE: smc_uvm_top.u_dut.u_smc.u_smc_peripherals.u_smc_efuse_wrapper.u_efuse_interface_controller
ANNOTATION: "SMC-F10-FSM-REVIEWED: design engineering reviewed these FSM states and transitions as not exercised by the SMC bench. Retired by an enrolled leaf that covers the point, or design engineering withdrawing the review."
Fsm efuse_reg_select "249869120"
State EFUSE_MMR_REG_MAP "2"
Transition EFUSE_CSR_REG_MAP->EFUSE_MMR_REG_MAP "1->2"
Transition EFUSE_MMR_REG_MAP->ERR_DECODE "2->3"
Transition ERR_DECODE->EFUSE_MMR_REG_MAP "3->2"
Transition SHADOW_REG_MAP->EFUSE_MMR_REG_MAP "0->2"

CHECKSUM: "1655169995 1106336131"
INSTANCE: smc_uvm_top.u_dut.u_smc.u_smc_peripherals.u_smc_efuse_wrapper.u_efuse_interface_controller.u_efuse_shadow_regs
ANNOTATION: "SMC-F10-FSM-REVIEWED: design engineering reviewed these FSM states and transitions as not exercised by the SMC bench. Retired by an enrolled leaf that covers the point, or design engineering withdrawing the review."
Fsm efuse_sense_state_q "1106336131"
Transition ST_READ->ST_IDLE "1->0"

CHECKSUM: "2121805547 1063748259"
INSTANCE: smc_uvm_top.u_dut.u_smc.u_smc_peripherals.u_smc_reset_unit.u_smc_cool_reset_wrap
ANNOTATION: "SMC-F10-FSM-REVIEWED: design engineering reviewed these FSM states and transitions as not exercised by the SMC bench. Retired by an enrolled leaf that covers the point, or design engineering withdrawing the review."
Fsm flr_counter_state "909361475"
Transition COUNT_DOWN->IDLE "1->0"

CHECKSUM: "1319975045 330493458"
INSTANCE: smc_uvm_top.u_dut.u_smc.u_smc_peripherals.u_telemetry_receiver_wrap.gen_telemetry_receivers[0].u_telemetry_receiver
ANNOTATION: "SMC-F10-FSM-REVIEWED: design engineering reviewed these FSM states and transitions as not exercised by the SMC bench. Retired by an enrolled leaf that covers the point, or design engineering withdrawing the review."
Fsm block_index "330493458"
State 'h0 "0"
State 'h1 "1"
Transition 'h0->'h1 "0->1"

CHECKSUM: "1319975045 330493458"
INSTANCE: smc_uvm_top.u_dut.u_smc.u_smc_peripherals.u_telemetry_receiver_wrap.gen_telemetry_receivers[1].u_telemetry_receiver
ANNOTATION: "SMC-F10-FSM-REVIEWED: design engineering reviewed these FSM states and transitions as not exercised by the SMC bench. Retired by an enrolled leaf that covers the point, or design engineering withdrawing the review."
Fsm block_index "330493458"
State 'h0 "0"
State 'h1 "1"
Transition 'h0->'h1 "0->1"

CHECKSUM: "1319975045 330493458"
INSTANCE: smc_uvm_top.u_dut.u_smc.u_smc_peripherals.u_telemetry_receiver_wrap.gen_telemetry_receivers[2].u_telemetry_receiver
ANNOTATION: "SMC-F10-FSM-REVIEWED: design engineering reviewed these FSM states and transitions as not exercised by the SMC bench. Retired by an enrolled leaf that covers the point, or design engineering withdrawing the review."
Fsm block_index "330493458"
State 'h0 "0"
State 'h1 "1"
Transition 'h0->'h1 "0->1"

CHECKSUM: "1114926396 2231107179"
INSTANCE: smc_uvm_top.u_dut.u_smc_ip_integration.u_efuse_interface_shim
ANNOTATION: "SMC-F11-FSM-IN-PORTS-ONLY-UNIT: this FSM sits inside a unit graded on its ports (a T-series class), which design engineering reviewed excluding whole; its states and transitions are excluded while uncovered. Retired by an enrolled leaf that covers the point, or design engineering withdrawing the review of the enclosing unit."
Fsm efuse_read_state_q "4179072252"
Transition ST_READ_INIT->ST_READ_IDLE "1->0"
Fsm efuse_write_state_q "2089111316"
Transition ST_WRITE_ACCESS->ST_WRITE_IDLE "3->0"
Transition ST_WRITE_INIT->ST_WRITE_IDLE "1->0"
Transition ST_WRITE_READ_BACK_ACCESS->ST_WRITE_IDLE "6->0"
Transition ST_WRITE_READ_BACK_SETUP->ST_WRITE_IDLE "5->0"
Transition ST_WRITE_READ_BACK_WAIT->ST_WRITE_IDLE "7->0"
Transition ST_WRITE_SETUP->ST_WRITE_IDLE "2->0"
Transition ST_WRITE_WAIT->ST_WRITE_IDLE "4->0"
