# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2026 Tenstorrent USA, Inc.

Checks:
  synthesis-loop-before-reset-check,
  synthesis-undriven-range,
  synthesis-always-f-f-assignment-outside-conditional,
  synthesis-unused-sensitive-signal,
  style-no-dot-var-in-port-connection,
  style-generate-named,
  style-no-implicit-port-name-in-port-connection,
  synthesis-cast-signed-index,
  style-only-a-n-s-i-port-decl,
  style-no-dot-star-in-port-connection,
  style-enforce-module-instantiation-prefix,
  style-always-f-f-blocking,
  style-always-comb-block-named,
  style-no-old-always-syntax,
  style-enforce-port-suffix,
  synthesis-register-has-no-reset,
  synthesis-only-assigned-on-reset,
  synthesis-no-latches-on-design,
  style-always-comb-non-blocking,
  style-enforce-port-prefix

CheckConfigs:
  clkName: "clk_i",
  resetName: "rst_ni",
  clkNameRegexString: "clk\S*|clock\S*",
  resetIsActiveHigh: "false",
  inputPortSuffix: "_i",
  outputPortSuffix: "_o",
  inoutPortSuffix: "_io",
  moduleInstantiationPrefix: "u_"
