# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2026 Tenstorrent USA, Inc.

"""List the documented RTL sources and read their // header and declaration clauses."""

import re
from pathlib import Path

DECL_START = re.compile(r"^\s*(module|interface|package)\b")
DESC = re.compile(r"^Description:\s*", re.IGNORECASE)
RULE = re.compile(r"^[-=*_]{3,}$")
_COMMENT_ONLY = re.compile(r"^\s*//")
_ASSIGN = re.compile(r"(?<![=!<>])=(?!=)")
_SPDX = re.compile(r"^(SPDX-|Copyright\b)")
_TYPEDEF_OPEN = re.compile(r"^\s*typedef\s+(struct|union)\b[^{]*\{")
_TYPEDEF_CLOSE = re.compile(r"^\s*\}\s*([A-Za-z_][\w$]*)")


def rtl_sources(rtl: Path) -> list:
    """The .sv files under an rtl directory, without register, DV or PeakRDL output."""
    files = []
    for path in sorted(rtl.rglob("*.sv")):
        if "regs/gen" in path.parts or "dv" in path.parts:
            continue
        head = "".join(path.read_text(errors="replace").splitlines(True)[:4])
        if "Generated by PeakRDL" not in head:
            files.append(path)
    return files


def rtl_blocks(root: Path) -> list:
    """(group, slug, rtl directory) of each block with sources, in catalog order."""
    ip = sorted(root.glob("hw/ip/*/rtl")) + sorted(root.glob("hw/ip/*/*/rtl"))
    blocks = [("ip", rtl.parent.name, rtl) for rtl in ip]
    blocks += [("sys", n, root / "hw/sys" / n / "rtl") for n in ("sep", "smc", "dtp", "smu")]
    blocks += [
        ("common", n, root / "hw/common" / n / "rtl")
        for n in ("ocah_prim", "ocah_prim_generic", "tlul")
    ]
    return [b for b in blocks if b[2].is_dir() and rtl_sources(b[2])]


def first_decl(lines):
    """Index of the first module, interface or package line, or None."""
    return next((i for i, line in enumerate(lines) if DECL_START.match(line)), None)


def header_prose(lines) -> str:
    """The // block above the first declaration, license text and rules removed.

    Preprocessor and import lines between the block and the declaration are skipped.
    """
    start = first_decl(lines)
    if start is None:
        return ""
    prose = []
    for line in lines[:start]:
        stripped = line.strip()
        if not stripped:
            if prose and prose[-1] != "":
                prose.append("")
            continue
        if stripped.startswith(("`", "import ")):
            continue
        if not stripped.startswith("//"):
            prose = []
            continue
        body = stripped[2:].strip()
        if (
            _SPDX.match(body)
            or body.startswith("*")
            or body.startswith("http")
            or "License" in body
            or "limitations under" in body
        ):
            prose = []
            continue
        # CIRCT stamps a version line, then comments on the macro preamble.
        # Those comments are not the module.
        if body.lower().startswith("generated by circt"):
            return "Generated by CIRCT."
        if RULE.match(body):
            continue
        body = DESC.sub("", body).strip()
        if body == "" and (not prose or prose[-1] == ""):
            continue
        prose.append(body)
    while prose and prose[-1] == "":
        prose.pop()
    return "\n".join(prose).strip()


def declared_name(code: str) -> str:
    """The last identifier outside brackets before the default value."""
    head = re.sub(r"\[[^\]]*\]", " ", _ASSIGN.split(code, 1)[0])
    idents = re.findall(r"[A-Za-z_][\w$]*", head)
    return idents[-1] if idents else ""


def clause(lines, i: int):
    """(text, next) for the same-line // clause of lines[i].

    The clause continues on the following comment-only lines whose // starts
    at or right of the clause's //. next is the first line after it.
    """
    col = lines[i].index("//")
    parts = [lines[i][col + 2 :].strip()]
    j = i + 1
    while j < len(lines) and _COMMENT_ONLY.match(lines[j]) and lines[j].index("//") >= col:
        parts.append(lines[j].split("//", 1)[1].strip())
        j += 1
    return " ".join(p for p in parts if p), j


def struct_field_clauses(lines) -> dict:
    """{typedef: {field: clause}} for the struct and union fields with a same-line // clause."""
    found = {}
    fields = None
    i = 0
    while i < len(lines):
        code = lines[i].split("//", 1)[0]
        if fields is None:
            if _TYPEDEF_OPEN.match(code) and "}" not in code:
                fields = {}
        elif end := _TYPEDEF_CLOSE.match(code):
            found[end.group(1)] = fields
            fields = None
        elif code.strip() and "//" in lines[i]:
            text, nxt = clause(lines, i)
            text = DESC.sub("", text).strip()
            if text:
                fields[declared_name(code)] = text
            i = nxt
            continue
        i += 1
    return found
