// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 Tenstorrent USA, Inc.
//
// Attaches dtp_ir_props to every jtag_ptap instance under the dtp formal top. Internal signals
// reach the property module through this port list only; the RTL carries no properties.

bind jtag_ptap dtp_ir_props u_dtp_ir_props (
  .tck_i                (client_tap_ctrl_i.tck),
  .jtag_trst_ni         (jtag_trst_n),
  .state_i              (current_state_o),
  .inst_i               (inst_decoded_o),
  .ir_shift_i           (u_jtag_inst_reg.instruction_shift_reg_q_bits),
  .ir_rst_ni            (ir_scan_ctrl.rst_n),
  .ir_capture_en_i      (ir_scan_ctrl.capture_en),
  .ir_update_en_i       (ir_scan_ctrl.update_en),
  .dr_select_i          (dr_scan_ctrl.select),
  .dr_capture_en_i      (dr_scan_ctrl.capture_en),
  .dr_shift_en_i        (dr_scan_ctrl.shift_en),
  .dr_scan_select_reg_i (dr_scan_select_reg),
  .ir_select_i          (ir_scan_ctrl.select),
  .stap_select_i        (stap_select),
  .client_tdi_i         (client_tdi_i),
  .client_tdo_i         (client_tdo_o),
  .tdr_mux_i            (tdr_mux),
  .inst_reg_scan_out_i  (inst_reg_scan_out),
  .byp_scan_out_i       (byp_reg_scan_out),
  .inv_byp_scan_out_i   (inv_byp_reg_scan_out),
  .idcode_scan_out_i    (idcode_reg_scan_out),
  .tap_3dcr_scan_out_i  (tap_3dcr_reg_scan_out),
  .tmp_status_scan_out_i (tmp_status_reg_scan_out),
  .ic_reset_scan_out_i  (ic_reset_reg_scan_out),
  .debug_ctrl_scan_out_i (debug_ctrl_reg_scan_out),
  .caps_scan_out_i      (caps_reg_scan_out),
  .smc_otp_caps_scan_out_i (smc_otp_2axi_caps_reg_scan_out),
  .sep_otp_caps_scan_out_i (sep_otp_2axi_caps_reg_scan_out),
  .smc_caps_scan_out_i  (smc_2axi_caps_reg_scan_out),
  .smc_otp_j2a_scan_out_i (smc_otp_jtag2axi_scan_out),
  .sep_otp_j2a_scan_out_i (sep_otp_jtag2axi_scan_out),
  .smc_j2a_scan_out_i   (smc_jtag2axi_scan_out),
  .bsr_scan_in_i        (bsr_host_scan_in_i),
  .ijtag_scan_in_i      (ijtag_host_scan_in_i),
  .byp_sel_i            (byp_reg_scan_ctrl.select),
  .inv_byp_sel_i        (inv_byp_reg_scan_ctrl.select),
  .idcode_sel_i         (idcode_reg_scan_ctrl.select),
  .tap_3dcr_sel_i       (tap_3dcr_reg_scan_ctrl.select),
  .tmp_status_sel_i     (tmp_status_reg_scan_ctrl.select),
  .ic_reset_sel_i       (ic_reset_reg_scan_ctrl.select),
  .debug_ctrl_sel_i     (debug_ctrl_reg_scan_ctrl.select),
  .caps_sel_i           (caps_reg_scan_ctrl.select),
  .smc_otp_caps_sel_i   (smc_otp_2axi_caps_reg_scan_ctrl.select),
  .sep_otp_caps_sel_i   (sep_otp_2axi_caps_reg_scan_ctrl.select),
  .smc_caps_sel_i       (smc_2axi_caps_reg_scan_ctrl.select),
  .smc_otp_j2a_sel_i    (smc_otp_jtag2axi_scan_ctrl.select),
  .sep_otp_j2a_sel_i    (sep_otp_jtag2axi_scan_ctrl.select),
  .smc_j2a_sel_i        (smc_jtag2axi_scan_ctrl.select),
  .bsr_sel_i            (bsr_host_scan_ctrl_o.select),
  .ijtag_sel_i          (ijtag_host_scan_ctrl_o.select),
  .idcode_scan_i        (u_jtag_idcode_reg.u_idcode_scan_reg.scan_data),
  .idcode_value_i       (u_jtag_idcode_reg.IdcodeValue),
  .caps_scan_i          (u_jtag_caps_reg.u_caps_scan_reg.scan_data),
  .caps_value_i         (u_jtag_caps_reg.CapsValue)
);
