// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 Tenstorrent USA, Inc.
//
// Attaches dtp_stap_props to every jtag_intf_unit instance under the dtp formal top. The per-STAP
// vectors list the STAPs in chain order, I/O at bit 0 and the extra STAP at bit 3; the
// synchronizer vectors follow the dbg_disable_t field order. Internal signals reach the property
// module through this port list only; the RTL carries no properties.

bind jtag_intf_unit dtp_stap_props #(
  .NUM_STAPS   (4),
  .NUM_DISABLE ($bits(sep_lifecycle_ctrl_pkg::dbg_disable_t))
) u_dtp_stap_props (
  .tck_i                (ptap_client_tap_ctrl_i.tck),
  .trst_ni              (ptap_host_tap_ctrl.trst_n),
  .pwr_on_rst_ni        (pwr_on_rst_ni),
  .client_tms_i         (ptap_host_tap_ctrl.tms),
  .shift_en_i           (ptap_stap_host_scan_ctrl.shift_en),
  .dbg_disable_i        (dbg_disable_bits),
  .dbg_disable_stage1_i ({gen_dbg_disable_sync_n0_scan[10].u_dbg_disable_sync_n0_scan.intq,
                          gen_dbg_disable_sync_n0_scan[9].u_dbg_disable_sync_n0_scan.intq,
                          gen_dbg_disable_sync_n0_scan[8].u_dbg_disable_sync_n0_scan.intq,
                          gen_dbg_disable_sync_n0_scan[7].u_dbg_disable_sync_n0_scan.intq,
                          gen_dbg_disable_sync_n0_scan[6].u_dbg_disable_sync_n0_scan.intq,
                          gen_dbg_disable_sync_n0_scan[5].u_dbg_disable_sync_n0_scan.intq,
                          gen_dbg_disable_sync_n0_scan[4].u_dbg_disable_sync_n0_scan.intq,
                          gen_dbg_disable_sync_n0_scan[3].u_dbg_disable_sync_n0_scan.intq,
                          gen_dbg_disable_sync_n0_scan[2].u_dbg_disable_sync_n0_scan.intq,
                          gen_dbg_disable_sync_n0_scan[1].u_dbg_disable_sync_n0_scan.intq,
                          gen_dbg_disable_sync_n0_scan[0].u_dbg_disable_sync_n0_scan.intq}),
  .dbg_disable_q_i      (dbg_disable_bits_q_n0_scan),
  .stap_disable_i       ({gen_extra_staps.gen_extra_stap[0].u_stap_extra.security_disable_i,
                          gen_stap_sep_dbg.u_stap_sep_dbg.security_disable_i,
                          gen_stap_smc_dbg.u_stap_smc_dbg.security_disable_i,
                          gen_stap_io.u_stap_io.security_disable_i}),
  .stap_sel_i           ({gen_extra_staps.gen_extra_stap[0].u_stap_extra.stap_sel,
                          gen_stap_sep_dbg.u_stap_sep_dbg.stap_sel,
                          gen_stap_smc_dbg.u_stap_smc_dbg.stap_sel,
                          gen_stap_io.u_stap_io.stap_sel}),
  .stap_sel_int_i       ({gen_extra_staps.gen_extra_stap[0].u_stap_extra.stap_sel_int,
                          gen_stap_sep_dbg.u_stap_sep_dbg.stap_sel_int,
                          gen_stap_smc_dbg.u_stap_smc_dbg.stap_sel_int,
                          gen_stap_io.u_stap_io.stap_sel_int}),
  .stap_tms_hold_i      ({gen_extra_staps.gen_extra_stap[0].u_stap_extra.tms_hold,
                          gen_stap_sep_dbg.u_stap_sep_dbg.tms_hold,
                          gen_stap_smc_dbg.u_stap_smc_dbg.tms_hold,
                          gen_stap_io.u_stap_io.tms_hold}),
  .stap_config_hold_i   ({gen_extra_staps.gen_extra_stap[0].u_stap_extra.config_hold,
                          gen_stap_sep_dbg.u_stap_sep_dbg.config_hold,
                          gen_stap_smc_dbg.u_stap_smc_dbg.config_hold,
                          gen_stap_io.u_stap_io.config_hold}),
  .stap_3dcr_gate_ni    ({gen_extra_staps.gen_extra_stap[0].u_stap_extra.rst_n_gate,
                          gen_stap_sep_dbg.u_stap_sep_dbg.rst_n_gate,
                          gen_stap_smc_dbg.u_stap_smc_dbg.rst_n_gate,
                          gen_stap_io.u_stap_io.rst_n_gate}),
  .host_tms_i           ({stap_extra_host_tap_ctrl_o[0].tms,
                          stap_sep_host_tap_ctrl_o.tms,
                          stap_smc_host_tap_ctrl_o.tms,
                          stap_io_host_tap_ctrl_o.tms}),
  .host_tdo_i           ({stap_extra_host_tdo_o[0],
                          stap_sep_host_tdo_o,
                          stap_smc_host_tdo_o,
                          stap_io_host_tdo_o}),
  .host_tdo_oen_i       ({stap_extra_host_tdo_oen_o[0],
                          stap_sep_host_tdo_oen_o,
                          stap_smc_host_tdo_oen_o,
                          stap_io_host_tdo_oen_o}),
  .ptap_stap_select_i   (u_jtag_ptap.stap_select),
  .ptap_tdo_mux_i       (u_jtag_ptap.tdo_mux),
  .ptap_zlb_tdr_mux_i   (u_jtag_ptap.zlb_tdr_mux),
  .ptap_stap_scan_in_i  (ptap_stap_host_scan_in),
  .stap_host_disable_i  (stap_host_security_disable),
  .chain_out_i          (extra_stap_scan_out[NUM_EXTRA_STAPS]),
  .stap_host_scan_in_i  (stap_host_scan_in_i),
  .ptap_stap_ctrl_i     (ptap_stap_host_scan_ctrl),
  .stap_host_ctrl_i     (stap_host_scan_ctrl_o)
);
