# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2026 Tenstorrent USA, Inc.

name: spdx

on: [push, pull_request, workflow_dispatch]

jobs:
  check-spdx-licenses:
    name: SPDX license headers
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check SPDX licenses
        uses: tenstorrent/tt-github-actions/.github/actions/spdx-checker@main
        with:
          ignore_config_file: .github/spdx_ignore.yaml
          verbose: "true"
